### ISSUE TITLE
Out of date examples

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#100]
Looking at [this example](https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/addVectors/server.js), it's stated that gradeAnswer() is optional when it is in fact required.

**Comment by mwest1066** [comment]
It should be optional. Does something break if you don't have it?

**Comment by tnip** [comment]
Yup; `node server` yells at you if you don't have it. Working on a repro.

**Comment by tnip** [comment]
And a repro:

1.  Remove L45-52 from [server.js in addVectors](https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/addVectors/server.js)
2. `node start`
3. Go into Homework 1
4. Try the question (should be Q1.1)
5. Fill in required fields, hit "Submit for Practice"
6. ???
7. Profit! 

You get the error:
```
error: returning error code=500, msg=Error in addVectors gradeAnswer(): TypeError: undefined is not a function, stack=TypeError: undefined is not a function
```

with a stack trace that I can provide via email.

The end user gets:

```
Error submitting question for grading to server: Internal Server Error
```
