### ISSUE TITLE
Show issue reporter's email on instructor variant view

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1000]
When following a link from Issues tab to a specific manually-reported issue, there's no way to see who reported an issue without going back to the main issues list. This makes responding to issues difficult. The red cards on the instance page should show the name and email of the student who reported the issue.

**Comment by nwalters512** [comment]
Since this is the 100th issue, some numbers...

* 24 contributors
* 1378 files
* 2609 commits
* 88,379 lines of code/comments

Go team!

**Comment by echuber2** [comment]
related: #1505

**Comment by mwest1066** [comment]
Fixed now.
