### ISSUE TITLE
pl-richtext-editor should have a word/character count as students type

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10009]
As discussed on Slack, it would be useful to add a word/character count to the `pl-richtext-editor` element so students can see the word count as they type.

**Comment by firasm** [comment]
There is now a bare-bones implementation [based on the custom module described on the QuillJS guide](https://quilljs.com/docs/guides/building-a-custom-module) in my [course here](https://github.com/PrairieLearnUBC/pl-ubc-cpsc430/tree/master/elements/pl-rich-text-editor)

<img width="1241" alt="Screenshot 2024-06-12 at 6 54 55 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/e2598282-f964-4ea6-8210-2e3cf8db642a">

Things left to do:

- [ ] Disable this by default, and add an option: `counter="words", counter="characters" or counter="none"` default should be none
- [ ] Conditional logic needs to be adjusted so it accepts, 'words', 'characters', or 'none' rather than the current code which is words or else length.
- [ ] Clean up CSS and make it look prettier (if necessary)
- [ ] Fix linting etc
- [ ] Update docs

**Comment by nishanthkarthik** [comment]
https://github.com/PrairieLearn/PrairieLearn/pull/10017
