### ISSUE TITLE
pl-richtext-editor element does not mark submissions as invalid if a previous submission was valid

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10011]
I think this is a bug, but might be a deliberate choice so reporting the issue here for discussion.

I've just noticed that if a submission to a `pl-richtext-editor` element is valid (i.e. put in any text), then if you remove that text and try another submission, the submission doesn't get flagged as invalid. In fact, the format_error is also removed even from the first submission.

Here's a gif of what I mean:

![pl_richtext_bug](https://github.com/PrairieLearn/PrairieLearn/assets/2507459/0bf597e6-bd4d-4fa6-9bd2-107ce106ec9a)

This is in contrast to the `integer-input` element, which behaves as expected under the same conditions

<img width="670" alt="Screenshot 2024-06-13 at 12 50 38 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/88908aa7-b91e-4f48-b175-f12a50eb5cea">

**Comment by jonatanschroeder** [comment]
I had noticed this before. In essence this comes from how the element identifies that an answer is blank, and in the scenario you provided, the answer will not technically be blank, but rather will be something like `<p></p>` (which is not technically empty). This will also happen if you just type something then erase it (i.e., you don't need an early submission), or if you perform any action that would cause some formatting to show up (e.g., hit Ctrl-I to make it italic).

The solution to this is likely going to be a clear definition of what constitutes blank, and it will likely require some HTML/cheerio interpretation to come up with a proper definition of blank. Trying to retrieve only the "inner text" of the content (sanitizing and ignoring spaces) is likely a good heuristic, but there should be some consideration of if this does not raise any false positives or false negatives.

**Comment by nwalters512** [comment]
Quill can give us the text without any formatting; that could give us an approximate "is there real content". I'm not sure how that would work with e.g. embedded images or math.

**Comment by jonatanschroeder** [comment]
> Quill can give us the text without any formatting; that could give us an approximate "is there real content".

That would require some client-side checking if the content is empty or not, while this check is usually done at the element's "parse" function. This may or may not be a problem.

> I'm not sure how that would work with e.g. embedded images or math.

For math we use a custom extension that converts it to Mathjax-appropriate input, so this should be fine. As for images, these may be tricky and one of the possible false positives to consider. While the menu does not give you the option to add an image, you can copy/paste an image and it would be submitted without problems.

**Comment by nwalters512** [comment]
> That would require some client-side checking if the content is empty or not, while this check is usually done at the element's "parse" function. This may or may not be a problem.

My proposal would be that on the client, immediately before syncing to the hidden input, we'd run the "is there actual content" check and if not, just write the empty string. Then the backend element checking can take over and do its usual thing.

**Comment by jonatanschroeder** [comment]
> My proposal would be that on the client, immediately before syncing to the hidden input, we'd run the "is there actual content" check and if not, just write the empty string. Then the backend element checking can take over and do its usual thing.

That's actually not a bad idea...

**Comment by nwalters512** [comment]
$10 says we can find whatever check Quill is using to know when to display the placeholder text, then we can use that as our "do we have content" check 😉

**Comment by firasm** [comment]
I suspected it was related to `<p></p>` and what blank means for this element. Thanks, I think the proposal above would result in expected behaviour!

Just want to flag this part in case it was missed and is a separate issue:

```
In fact, the format_error is also removed even from the first submission.
```

If you notice from my gif in the last frame, the `format_error` is removed from the first submitted answer when the second submission is valid. That probably shouldn't happen right?

**Comment by nwalters512** [comment]
@firasm I'm 95% sure that's just a consequence of that being a purely manual graded question. IIRC we don't show any status badges for anything but the most recent submission. @jonatanschroeder can probably confirm.

**Comment by jonatanschroeder** [comment]
> $10 says we can find whatever check Quill is using to know when to display the placeholder text, then we can use that as our "do we have content" check 😉

How about `quill.editor.isBlank()`? Easy enough? 😆 

https://github.com/slab/quill/blob/d5efd42de7857ee25fcf16446d81a96a38ff1bca/packages/quill/src/core/editor.ts#L245

**Comment by jonatanschroeder** [comment]
> @firasm I'm 95% sure that's just a consequence of that being a purely manual graded question. IIRC we don't show any status badges for anything but the most recent submission. @jonatanschroeder can probably confirm.

Indeed that is the case for manual-only questions.
