### ISSUE TITLE
Non-existant function referenced in `sync_topics.sql`

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#10018]
I just ran into this while doing dev for something else, I don't think the function `array_arr` exists. Should it be `array_agg`? 

It seems this code is not being tested. 

https://github.com/PrairieLearn/PrairieLearn/blob/1dfd177b8595fff1e2c8d8990fabb4147de17d9b/apps/prairielearn/src/sprocs/sync_topics.sql#L46-L50

**Comment by nwalters512** [comment]
Yep, this should be changed to `array_agg`. PR welcome!
