### ISSUE TITLE
Multi-server changes

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1002]
Here are the things that we need to fix or lock to run multiple servers simultaneously:

* [x] use ENV vars for config, not `config.js` and `config.json` -- or DB where possible
* [x] migrations
* [x] sprocs
* [x] sync
* [ ] after sync, need to prompt all servers to reload course elements for v2 questions, or shift v2 questions to use an external code runner like v3
* [ ] after sync, need to call `freeformServer.reloadElementsForCourse()` on all servers, or push this into the DB?
* [x] cron
* [x] grading results webhook, and other jobs that are running and need to feed data back to clients via websocket (use redis)

**Comment by nwalters512** [comment]
There are two unchecked things in the above list:

- Re: v2 code reloading, we're in the process of switching to executing them in a v3-style single-use process, so we won't need to explicitly reload code.
- Re: v3 element reloading, the element list is now tied to the course commit hash, so we'll automatically reload the elements whenever there's a new course version.

@mwest1066 I think this can be closed?

**Comment by mwest1066** [comment]
Yep, I think this is all (almost) done.
