### ISSUE TITLE
Adding extra attributes to pl-figure

### ISSUE THREAD

**Issue by jcrayb** [PrairieLearn/PrairieLearn#10079]
Hello! I am a student developer for class that uses Prairielearn (TAM 251 @ Illinois), and have come upon cases where it would be useful to use the "title" attribute as well as extra classes to the pl-figure element. I modified the mustache and py files for the element and have the functionalities working, but do not have write access to the repo to push the changes. Would it be possible to be added as a collaborator? Thank you!

**Comment by jonatanschroeder** [comment]
Hi, @jcrayb, thank you for your contribution. Note that you can submit a PR from your local fork of PrairieLearn, see https://github.com/PrairieLearn/PrairieLearn/blob/master/CONTRIBUTING.md.

**Comment by jcrayb** [comment]
Perfect will do thank you!
