### ISSUE TITLE
On file upload, warn the user if they navigate away before saving or grading

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1022]
From a student:
> I took quiz 1, in the CBTF today, and in a hurry to finish the quiz in time I uploaded the file but forgot to press the save button on Prairielearn.

Could maybe use the `onbeforeunload` function? https://stackoverflow.com/questions/1119289/how-to-show-the-are-you-sure-you-want-to-navigate-away-from-this-page-when-ch

**Comment by mwest1066** [comment]
See #1132 --- same issue
