### ISSUE TITLE
In Students tab, with a group assessment, search does not find students

### ISSUE THREAD

**Issue by moveisi** [PrairieLearn/PrairieLearn#10263]
In Students tab, with a group assessment, search does not look into group members. So, xyz@ubc.ca does not find the xyz student.
(Also see [discussion on pl-help](https://prairielearn.slack.com/archives/C266KEH9A/p1721372271679939))

**Comment by moveisi** [comment]
Great. Then should us (you or me) close this one which is a duplicate?

**Comment by jonatanschroeder** [comment]
I don't think this one is a duplicate. My suggestion in the other PR would be to work on all three problems together (since they are related).
