### ISSUE TITLE
In Students tab, allow sorting by "Fingerprint Changes" 

### ISSUE THREAD

**Issue by moveisi** [PrairieLearn/PrairieLearn#10262]
In the Students tab, allow sorting by "Fingerprint Changes" which makes it easier to find those who have unexpected number of Fingerprint Changes.
(Also see [discussion on pl-help](https://prairielearn.slack.com/archives/C266KEH9A/p1721372271679939))

**Comment by jonatanschroeder** [comment]
This seems to be a regression (introduced in #9725), where the 'sortable' option for this column was not set in the modernization. Should be an easy fix.
