### ISSUE TITLE
Warn students the exam is about to end

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10295]
Through some UI and UX improvements, we are hoping to address the issue of PrairieLearn exams closing and students not saving their work in time.

The problem that needs to be addressed is that students "lose" their work if they don't remember to click "Save" or "Save and Grade" before the timer runs out. This applies to all questions, but is particularly an issue for longer multi-part questions where the timer is at the top of the page, and for workspace questions where there currently isn't a timer present.

## Current Behaviour

For an assessment, the timer is shown at the top right, it updates live, but when there is > 1 minute left, it ticks down in minutes (rather than seconds).

<img width="1727" alt="Screenshot 2024-07-25 at 3 25 23 PM" src="https://github.com/user-attachments/assets/e877e892-c40f-4f8f-878b-b5527f1cdb70">

The progress bar switches to yellow at some point when the end is near:

<img width="1727" alt="Screenshot 2024-07-25 at 3 38 08 PM" src="https://github.com/user-attachments/assets/2b475ca7-0618-4529-a08b-88697bae9912">

When there is less than 1 minute remaining, the timer shown is in seconds and counts down:

<img width="1727" alt="Screenshot 2024-07-25 at 3 38 44 PM" src="https://github.com/user-attachments/assets/3f432e6c-0e01-42c0-bafd-c1d9ea5c942f">

When time expires, a popup is shown and students are informed time has expired:
<img width="1727" alt="Screenshot 2024-07-25 at 3 39 42 PM" src="https://github.com/user-attachments/assets/70cf6fe1-721e-400e-847c-6b7c7498e21b">

In a Workspace question, no timer is shown.

## Proposed behaviour

This is currently proposed, and subject to change after discussion/consultation:

- When there is less than 2 minutes remaining on the exam, there should be a persistent yellow sticky banner at the top of the page that shows the time remaining: "There are less than 2 minutes remaining on this assessment"

- When there is just over 1 minute remaining on the exam, there should be a pop-up dialog box that tells students:
    - time is almost up (less than 1 min left).
    - they should save or save and grade answers to all questions.
    - Any unsaved work will be lost.
    - Students need to click "Ok" (timer remains ticking)
    
- The yellow/red banners should be shown on all pages of the PL assessment, including workspaces (in the Teal bar)

- The time remaining should be added to the Teal workspace banner at the top (it can be left in terms of minutes remaining)

<img width="1727" alt="Screenshot 2024-07-25 at 3 26 36 PM" src="https://github.com/user-attachments/assets/75d78475-b123-4c2e-88ed-916edf381b64">

**Comment by jonatanschroeder** [comment]
Here are my personal opinions about this:

> * When there is less than 2 minutes remaining on the exam, there should be a persistent yellow sticky banner at the top of the page that shows the time remaining: "There are less than 2 minutes remaining on this assessment"

I'd be ok with some sort of element highlighting this information, but "top of the page" may be a bit too disruptive, particularly if they are in the process of writing something that happens to be in that area. I'd suggest this shows up as a sticky note (fixed, not scrollable) on the right side, in the same horizontal area as the right-side controls.

> * When there is just over 1 minute remaining on the exam, there should be a pop-up dialog box that tells students:
>   
>   * time is almost up (less than 1 min left).
>   * they should save or save and grade answers to all questions.
>   * Any unsaved work will be lost.
>   * Students need to click "Ok" (timer remains ticking)

I'm strongly against a dialog that interrupts the students flow. Again, a student may be in the middle of writing something, in the rush of the last minute, and this is probably the worst moment to have an interrupting action. I agree with such a warning message, but it should not disrupt the element focus.

> * The yellow/red banners should be shown on all pages of the PL assessment, including workspaces (in the Teal bar)
> * The time remaining should be added to the Teal workspace banner at the top (it can be left in terms of minutes remaining)

I strongly agree with such an addition, preferably using the same UI as the current time remaining block.

**Comment by firasm** [comment]
Thanks Jonatan! Fixed sticky note is very reasonable.

> I'm strongly against a dialog that interrupts the students flow. Again, a student may be in the middle of writing something, in the rush of the last minute, and this is probably the worst moment to have an interrupting action. I agree with such a warning message, but it should not disrupt the element focus.

I agree with you if this wasn't configurable by the instructor for each assessment, but this suggestion came out of a longer discussion at the Thursday Office Hours as a compromise to address the fact that students weren't remembering to save their work.

**Comment by nwalters512** [comment]
I do think there's a potential accessibility issue with moving focus into a modal without user interaction, especially in an "every second counts" situation like the final minutes of an exam. Specifically, it may take the student time to reorient themselves after dismissing a modal as they navigate back to the last focused item.

Rather than forcefully interrupting the user's flow, what if we instead used a bright yellow [Bootstrap toast](https://getbootstrap.com/docs/5.3/components/toasts/) that pops up in an animated way at the bottom/top/somewhere on screen and jiggles, expands/contracts, etc. to get the student's attention? Coupled with `aria-live` for folks using a screen reader, it should be very difficult to ignore while still ensuring that students can stay in flow. It'd of course have to be dismissable to ensure that it doesn't permanently cover any exam content.

**Comment by nwalters512** [comment]
Here's a prototype so we have something specific to discuss: https://jsfiddle.net/nwalters512/q89ymf4h/13/

**Comment by jonatanschroeder** [comment]
> Here's a prototype so we have something specific to discuss: https://jsfiddle.net/nwalters512/q89ymf4h/13/

I like this. My only pet peeve is that the close button moves with the jiggle...

**Comment by nwalters512** [comment]
I tested in Chrome, Safari, and Firefox, and assuming you get your mouse to the button while the jiggle isn't occurring, they all retain the button's original hitbox. We can also plpay with the animation timing/scale/etc, e.g. here where it's a smaller growth with a longer pause in between: https://jsfiddle.net/nwalters512/q89ymf4h/15/

**Comment by firasm** [comment]
Hehe, ngl I love the jiggle. It's like it's alive.

**Comment by nwalters512** [comment]
I talked with @mwest1066 offline and he's in agreement that a non-modal toast is the way to go.

**Comment by mwest1066** [comment]
> I talked with @mwest1066 offline and he's in agreement that a non-modal toast is the way to go.

Yep! Great idea.

**Comment by firasm** [comment]
Things left to do on this before coding begins:

- [ ] Work out exactly what the message should read.
- [ ] Figure out when to show the message and if the message should change in different circumstances
- [ ] Figure out location of the message (sticky top, stick top-right-sidebar)

Conditions to consider:

- Realtime grading enabled (default): message should say something about save and grade being clicked before time runs out
- Realtime grading disabled: message should say something about saving answers
- message should not show if the assessment doesn't have a time limit
    - It's probably easy to tell if there's a time limit from an access rule. 
    - I'm sure there's also way to tell if there's a time limit assigned from PrairieTest (i.e. not explicitly in an access rule)

Can anyone think of anything else ?

**Comment by jonatanschroeder** [comment]
> * message should not show if the assessment doesn't have a time limit
>   * It's probably easy to tell if there's a time limit from an access rule.
>   * I'm sure there's also way to tell if there's a time limit assigned from PrairieTest (i.e. not explicitly in an access rule)

I'd assume this message would come from the same functionality that shows the time limit in the first place, which already takes care of this functionality, so I don't see this as a problem.
