### ISSUE TITLE
assessment scorebar stays 0% when role==student

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1034]
Reported on cbtf-proctors, the student has a red 0% scorebar at the top of https://prairielearn.engr.illinois.edu/pl/course_instance/8170/assessment_instance/357368 but his total points are 37.5/42.

ME270 assessment: https://github.com/PrairieLearn/pl-me270/blob/master/courseInstances/2018_Spring/assessments/Hour%20Exam%201/infoAssessment.json

PL bug? Or config bug the way the assessment is configured?

**Comment by trombonekenny** [comment]
I'm leaning towards PL bug showing up for students but not instructors.

I reproduced it by copying the `pl-me270` repo, pointing my PL docker at it. When I did the assessment as an instructor (default), the scorebars updated. This was also true on the production PL server.

When I updated my docker PL for an effective role of student, started a new assessment, answered a question correctly, the scorebar did not update. This seems consistent with what the students are seeing in the CBTF.

**Comment by trombonekenny** [comment]
Since the view shows up as 0% for both instructors and students, it leads me to believe the problem is not in how the scorebar is viewed but something in how the question is scored/saved?

The other data point is all of ME270's questions are v1 question types -- most calculation, some `multiplechoice` or `checkbox`

**Comment by mwest1066** [comment]
I bet he doesn't have credit set. Students need an explicit credit: 100 to get credit. Otherwise it acts like a homework that is past the due date, so you can do questions, but not get percentage credit for them.

**Comment by trombonekenny** [comment]
It was the lack of credit set; sorry I missed that!
