### ISSUE TITLE
add pl_text_input element

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1035]
Add a simple way to do text comparisons like we do with `pl_number_input`

Matt suggested the [addBinary](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/addBinary) question as an example of how to do this outside of an element.

**Comment by coatless** [comment]
I think I'm going to try to knock this out tomorrow. Before I invest time, do you know if anyone was working on it at or after hackillinois?

**Comment by nwalters512** [comment]
Nope, I don't think anyone gave it a shot. It's all yours!

**Comment by mfsilva22** [comment]
I agree this can be done with `pl-string-input`

**Comment by trombonekenny** [comment]
Thanks, closing out
