### ISSUE TITLE
Add flag to disable Personal Notes on specific assessments

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10386]
[Personal Notes](https://prairielearn.readthedocs.io/en/latest/assessment/#student-attached-personal-notes) are described as ways for students to take notes for themselves that are not visible to the instructor.

It would be nice if instructors could disable the personal notes feature for specific assessments to facilitate using a second assessment as a reference/formula sheet.

**Comment by jonatanschroeder** [comment]
Closed by #10426.
