### ISSUE TITLE
Quotations suppressed in dropdown 

### ISSUE THREAD

**Issue by kurmasz** [PrairieLearn/PrairieLearn#10396]
(Apologies if this is the documented and expected behavior.)

When I put <code>""</code> in a `pl-multiple-choice element`, the quotes, and anything after them don't appear. 

Specifically, this code:

```
v5 = <pl-multiple-choice answers-name="v5" display="dropdown">
    <pl-answer correct="true"><code>0</code></pl-answer>
    <pl-answer correct="false"><code>False</code></pl-answer>
    <pl-answer correct="false"><code>None</code></pl-answer>
    <pl-answer correct="false">z<code>""</code>x</pl-answer>
</pl-multiple-choice>
```

produces this visual drop-down:

![Screenshot 2024-08-06 at 11 19 56 AM](https://github.com/user-attachments/assets/120566e7-839a-4fa7-9829-999112578625)

Notice that in item (d), the "z" appears, but the quotes and the "x" following the quotes does not.

I am using a MacBook Pro running 14.5.  I am seeing the same behavior on both Safari and Chrome.

* Using   `<pl-answer correct="false">z<code>&quot;&quot;</code>x</pl-answer>` produces the same result.
*  `<pl-answer correct="false">a<code>b&quot;c&quot;d</code>e</pl-answer>` produces an `a` in regular font followed by a `b` in code font. The c, d, and e are not displayed.

**Comment by jonatanschroeder** [comment]
Found the bug, PR coming.

**Comment by kurmasz** [comment]
That was impressively quick :)
