### ISSUE TITLE
Customise pl-order-blocks answer message

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieLearn#10419]
A previous PR #6456 changed the wording of the answer panel in the `pl-order-blocks` to be more ambiguous. I see the reasoning behind this change but it now causes the opposite issue. When there is only one correct order, students may try and argue that their solution is correct because it states "there may be other solutions"

A way to customise this message or a parameter such as `one-solution` would be beneficial so that both use cases can be accounted for.

![image](https://github.com/user-attachments/assets/1f343b2c-fd11-411c-9ccf-33ee4174cf44)

**Comment by ZacWarham** [comment]
Re-visiting this with better knowledge (as I attempt to fix it for myself as a PR) and it appears this situation only occurs when grading method is `DAG` or `RANKING` and I am uncertain if this is the result of using the wrong grading method (i.e. dag and ranking will always have multiple answers and must state this) or if there is a situation where these grading methods should be used for a singular solution question.

**Comment by SethPoulsen** [comment]
> students may try and argue that their solution is correct because it states "there may be other solutions" 

This argument doesn't make any sense to me. If a student said this, it can easily be shut down by "ya, there are multiple solutions, the thing that you submitted isn't any of them". This true for many many problems on PrairieLearn. 

If that is the main issue here, I recommend we close this, but if there are other use cases you had in mind I am happy to hear them. Thanks!

**Comment by ZacWarham** [comment]
> but if there are other use cases you had in mind I am happy to hear them. Thanks!

The concern is more that if a question only has one specific order for the rankings, for example order the movies by highest to lowest ticket sales. There can only be one correct order but the answer panel suggests there are more. You could say that this should be considered an `ordered`, `grading-method` but then the docs state "There is no partial credit for this option." and we may want partial credit for this.

It might just be that the docs should clarify that `ordered` can be partial credit through `LCS` if that is possible, otherwise we may want a partial credit grading method on a one ordered solution

**Comment by ZacWarham** [comment]
>  Would updating the docs resolve all of your concerns then?

That seems like the most logical approach!

[Here is where](https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/elements.md?plain=1#L887-L888) it says no partial credit is allowed

**Comment by SethPoulsen** [comment]
Thanks for finding that! the correct information is actually in the table above, so we had conflicting information. Should be fixed now.
