### ISSUE TITLE
Reset-question button for instructors

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1041]
Allow instructors to invalidate any open variants of a question and force new ones. Useful if a question is updated to fix a bug and you want to remove any of the previous variants with bad data.

**Comment by mwest1066** [comment]
Presumably the same as #756

**Comment by mwest1066** [comment]
Also the same as #233

**Comment by trombonekenny** [comment]
This came up in office hours again today with two different courses that changed questions in-flight and now the question won't render for the student (trying to map old stored data back to the new version of the question)

**Comment by trombonekenny** [comment]
Another ping.

**Comment by trombonekenny** [comment]
This came up in office hours again today.

**Comment by cbm755** [comment]
I hit this again today too.  I wonder if I change the problem to 999 attempts instead of unlimited attempts, then a "New Variant" button would appear and I could mass-message students to click it...

(In my case its maybe 50 students out of 700 who accessed the Assessment before I fixed the error in my problem).

**Comment by cbm755** [comment]
In case it helps someone else:
  * I changed remove `single-variant = true` from my problem and set the number of attempts at a large number (I choose 32).  With some very limited testing, I think this gives everyone (even those that started before the change) the New Variant button.
  * Then I changed the problem text to say:
    > <b>UPDATE</b>: If you first accessed this question before Nov 20th,
    > please type “<tt>pi*(1-c)</tt>” in this box: this is not the correct
    > answer, but I don’t know how to force an update: its possible clicking
    > “New Variant” below will also fix this.

**Comment by eliotwrobson** [comment]
Related PRs:
- https://github.com/PrairieLearn/PrairieLearn/pull/3552
- https://github.com/PrairieLearn/PrairieLearn/pull/3216

**Comment by jeffgerickson** [comment]
Another related PR: https://github.com/PrairieLearn/PrairieLearn/pull/6531
