### ISSUE TITLE
Some elements don't render expected thing for missing input

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#10429]
Some elements appear to intend to render a specific value when a submitted answer can't be found:

https://github.com/PrairieLearn/PrairieLearn/blob/9af9e7c48ebb23924f9438a124abf8aa7a979e7a/apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.mustache#L119-L124

However, `missing_input` isn't set in the dictionary that's passed to Chevron, so this code path is never hit:

https://github.com/PrairieLearn/PrairieLearn/blob/9af9e7c48ebb23924f9438a124abf8aa7a979e7a/apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py#L182-L191

We should either add `missing_input` to all elements where it's needed, or remove this branch from the Mustache templates.

**Comment by eliotwrobson** [comment]
We should probably just get rid of these sections. The mustache templates have a lot of boilerplate, so this probably had some use at some point, and we can always get this code back out of the version control if we have a need for it. I'll make a pass through and remove these when I get the chance 👍🏽

**Comment by nwalters512** [comment]
Thank you! 🎉
