### ISSUE TITLE
Simultaneous Workspaces Constantly Refresh

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieLearn#10498]
Whenever I have more than one RStudio workspace open at the same time in different tabs, each tab refreshes over and over and shows the following errors in the console log.

![image](https://github.com/user-attachments/assets/44e030f6-e3d0-4106-adc1-360a2708c50f)

Our instance - https://ca.prairielearn.com/pl/course_instance/7227/instructor/assessment/47863/questions

To reproduce:

1. Add the two zipped questions to the questions in the course and sync
2. Add the questions to the TemplateCourseInstance Homework questions
3. Switch to student view to view the assessment (may need to change access time in HW?)
4. Open to the first workspace question
5. Open the workspace and once it has loaded switch tabs to the Homework
6. Go to the next question and open it's workspace
7. Should now have 3 tabs open, the question and both workspaces
8. Typically starts refreshing within 30 seconds of the second one being loaded and then happens every few seconds

Occurs in multiple courses using the same two questions and in multiple browsers (Edge and Chrome inside Windows 11 VM)

[others.zip](https://github.com/user-attachments/files/16642871/others.zip)

Let me know if anything further is needed to investigate

Edit: tested Jupyter; it is working, just RStudio is the problem

**Comment by ZacWarham** [comment]
I tried to remove some variables so I opened Docker Desktop and ran two instances of `prairielearn/workspace-rstudio` based on two recent tags. The refreshing still occurs and I did witness the MIME type error in the console logs (potentially others but they disappear on each refresh)

**Comment by ZacWarham** [comment]
I tried the `rocker/tidyverse` image after this and it still occurs - through some research it looks like the issue is an RStudio issue

https://stackoverflow.com/questions/22938305/run-multiple-instances-of-rstudio-in-a-web-browser#:~:text=Unfortunately%2C%20RStudio%2Dserver%20still%20prevents,it%20by%20using%20different%20browsers.

https://www.reddit.com/r/RStudio/comments/usjipt/using_multiple_rstudio_server_sessions_at_once/

Will leave open in case there are any suggestions but feel free to close as it's beyond the scope of PL

**Comment by nwalters512** [comment]
Given that this is an inherent limitation with RStudio, there's nothing currently actionable for us here. In the medium to long term, we plan to isolate individual workspaces to unique subdomains, which would hopefully solve this issue by allowing each workspace to independently maintain session/auth/etc. cookies.

**Comment by echuber2** [comment]
@eddelbuettel FYI - Judging from the Reddit thread, if it is somehow storing the RStudio server PID for reference in the local storage and that's causing a conflict, there may be a way we could randomize something to prevent this from happening. But I'm confused about whether this skirts a licensing issue on how the free version of RStudio is intended to be limited anyway.

**Comment by eddelbuettel** [comment]
@echuber2 My memory is foggy on this but I do believe that "yes indeed" this used to work way-back-when allowing multiple instances per user on one machine, but also that "cannot have nice things" it was turned off for if I recall correctly a technical reason related to overall state management. I am unsure -- this was always a fringe use case to me.

You could chase this in the sources and we could build our own binary but ... I think this triggers "black hole detected" alerts.  Maybe our time is better spent elsewhere?
