### ISSUE TITLE
Documentation should specify behaviours of different modes

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#105]
As-is, there doesn't seem to be documentation on what the difference is between Exam Mode and Public Mode, nor is there an explanation of what "Default" is in the Instructor's panel.

I also vaguely remember seeing a commit about exam lockdown mode; some documentation (and user-facing indication) that that's being enforced, in addition to what the lockdown mode restricts access to, would be immensely helpful.

**Comment by mwest1066** [comment]
I added more text to [writingTests](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/writingTests.md) and also put explanation text on the `User` tab within PrairieLearn itself. Added in 50289d09ab9e474e7aa8140b209c7221e5b26d47

I'm closing this issue for now, but please re-open if the additional docs/text are not clear enough. Or tell me what sort of explanation would be helpful for you: what's confusing at the moment, what questions do you have, etc.
