### ISSUE TITLE
HTML Elements Documentation Structure

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1050]
I'd like to clean up the documentation surrounding HTML elements. 

I'm proposing that:

- [ ] HTML elements are split into subcategories of "decorative" (e.g. `pl_code`, `pl_figure`, ...) and "input fields" (e.g. `pl_number_input`, `pl_multiple_choice`, ... ) 
- [ ] Renaming and tagging test suite questions to match more closely to what they show.
- [ ] Adding links in the documentation to view source of test question code in the repository (e.g. `question.html`, `info.json`, ... )

**Comment by mwest1066** [comment]
This would be awesome!
