### ISSUE TITLE
Batch download statistics for assignments

### ISSUE THREAD

**Issue by moneypro** [PrairieLearn/PrairieLearn#1051]
In each assignment, there is a tab `Downloads` which has:
* scores
* points
* instances

For a class with a large number of assignments, instructors have to click into every assignment and go to Downloads to download statistics. 
![image](https://user-images.githubusercontent.com/9099607/36688619-a3856d36-1af2-11e8-934c-207aedc2b550.png)

I purpose to change the last line of the `Assessment` page which currently having the line `Download CS101_Sp18_assessment_stats.csv (includes more statistics columns than displayed above)` into a small panel of batch downloading stats which is essentially the same as the Download for each assessment, but batch download those stats for ALL assessments.

**Comment by mwest1066** [comment]
We now recommend using the API for dumping full course data.
