### ISSUE TITLE
Viewing UID can be changed to users which don't exist

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#106]
Ideally would also default to their viewing role?

**Comment by mwest1066** [comment]
I like both of these suggestions. Want to have a go at fixing them?

**Comment by mwest1066** [comment]
Note that this form input is using the new [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) HTML element, so it's behavior is somewhat browser-dependent.
