### ISSUE TITLE
pl-answer alignment with block level elements

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#10645]
I noticed that `<pl-answer>` doesn't vertically line up when we put `<pl-code>` (or `<markdown>`) in it. Is this a markdown 5 regression?

```html
<p>
<pl-multiple-choice answers-name="foo">
    <pl-answer correct="true"><code>array([6, 10.1, "foo"])</code></pl-answer>
    <pl-answer correct="false"><pl-code language="python">array([6, 10.1, "foo"])</pl-code></pl-answer>
    <pl-answer correct="false"><markdown>`array([6, 10.1, "foo"])`</markdown></pl-answer>
</pl-multiple-choice>
</p>
```

Rendered today as 
![image](https://github.com/user-attachments/assets/56a889e8-c4f1-4bc3-88ef-dc706e89d788)

**Comment by nwalters512** [comment]
`<pl-code>` renders with bottom margin, and `<markdown>` will end up wrapping the `<code>` it produces in a `<p>`.

One option to fix this: add CSS to `pl-multiple-choice` that can remove the bottom margin from the last child of each `<pl-answer>`. I don't know if this would have other unintended consequences.
