### ISSUE TITLE
[Feature Request] Alert students who opt to save on exam if multiple grade attempts are possible

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1065]
One of the behavior's that I noticed from the midterm data is some students are always pressing "Save" while other students opted to "Grade" immediately. Students who opted to "Save" were unintentionally penalized more as they _never_ reattempted the question if they got it wrong. 

I think it might be advantageous to provide help text or emphasize that multiple attempts are possible or required. Consider the first question of hw2, here it isn't immediately apparent that the question _requires_ multiple attempts to be awarded all the points  c.f. 

![screen shot 2018-03-06 at 10 27 42 am](https://user-images.githubusercontent.com/833642/37044596-8133ad32-2129-11e8-9a17-6675deb40185.png)

In comparison, under a "submitted" answer that is correct note that the button switches to "Try question again" but does not enforce a new question generation.

![screen shot 2018-03-06 at 10 23 55 am](https://user-images.githubusercontent.com/833642/37044335-cf6e228a-2128-11e8-8206-e3f4249d97cb.png)

**Comment by trombonekenny** [comment]
This has been discussed in a few different places. I think we all agree the current UI isn't consistently interpreted by the students, but we're not sure what will fix it.

I'd like to see the two buttons moved next to each other (left or right justified) and changed to say "Save" and "Save and Grade".

Students only saving on homeworks is a new one, but that probably gets fixed as they get socialized to how PL works? (i.e. keep doing the homeworks until you get 100%). I could also see a "Try question again" button in the Question panel on the right all the time for homeworks. Like a "Points are still available, keep trying!" button.

**Comment by mwest1066** [comment]
@coatless are you mainly talking here about `Homework` or `Exam` scoring and UI? The screenshots are from a HW but you also mention midterm data.

**Comment by mwest1066** [comment]
We rearranged the buttons some time ago and haven't heard any complaints since. I'll close this for now.
