### ISSUE TITLE
Open default browser when launching docker container

### ISSUE THREAD

**Issue by joelostblom** [PrairieLearn/PrairieLearn#10662]
Currently, the docker container [prints `info: Go to http://localhost:3000`](https://github.com/PrairieLearn/PrairieLearn/blob/45d91bd60f726f3c07918ce5a0bb6a2e50328d10/apps/prairielearn/src/server.js#L2696) when it is launched. It would be convenient if it opened this URL in the default browser instead of manually having to click (or, as is the case for many terminals, copy/paste think link in the browser manually). So similar to how e.g. JupyterLab works when it is launched.

**Comment by ZacWarham** [comment]
> Currently, the docker container [prints `info: Go to http://localhost:3000`](https://github.com/PrairieLearn/PrairieLearn/blob/45d91bd60f726f3c07918ce5a0bb6a2e50328d10/apps/prairielearn/src/server.js#L2696) when it is launched. It would be convenient if it opened this URL in the default browser instead of manually having to click (or, as is the case for many terminals, copy/paste think link in the browser manually). So similar to how e.g. JupyterLab works when it is launched.

I see a similar prompt in my workflow but I launch it through the makefile inside of the Docker. If it is the same situation, would it cause nodemon to open a new tab every time it finds a change?

**Comment by jonatanschroeder** [comment]
It might be tricky to do that from within a container. Note that some terminal applications are able to detect a URL and create a link, on Windows Terminal I can do it with Ctrl-Click.

**Comment by joelostblom** [comment]
Yes, I can just click the URL in the terminal I'm using (kitty) as well.

I guess this feature would just be a minor convenience and as you said hard to achieve due to it running in a container. I found a workaround that I post below for those interested and will close this issue, since there are probably more helpful ones to focus on.

This workaround uses curl to check if the localhost page is up, and launches the default browser if it is (swap out `xdg-open` accordingly depending on your OS). Since it takes at least 20 s for PL to start on my system, I sleep for that time initially before starting to ping with curl. I already have the large command from https://github.com/PrairieLearn/PrairieLearn/discussions/10661 as a shell alias/function, so prepending this line to that makes it convenient to run.

```bash
(sleep 20 && curl --silent --retry 15 --retry-delay 1 --head --fail --retry-all-errors http://localhost:3000 &> /dev/null && xdg-open http://localhost:3000) & ; <YOUR_DOCKER_COMMAND>
```
