### ISSUE TITLE
student assessment open/closed status from assessments page

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1067]
When a student visits their course_instance assessments page, there's no way to tell on that page if the assessment is closed or not. The score column says 'Not started', but it doesn't differentiate between an open or closed assessment.

Should we add a column for status?
Or change the score column to be different for closed exams?
Or override the Available credit column to show there is no more available credit for a closed exam?

Backstory: SEB exams show up in that list, and have a more elaborate setup. I wouldn't want the student to go through loading up the Safe Exam Browser just to see that it's closed. We'd either need to remove closed SEB exams from that list, or hint to them there that they're done somehow. (We would probably still remove access to the closed SEB exam so they can't review the questions afterwards.)

**Comment by trombonekenny** [comment]
Working on this in the SEB branch. Decided to put 'Assessment closed' in the available credit column.

**Comment by mwest1066** [comment]
@trombonekenny: I think you fixed this?

**Comment by mwest1066** [comment]
I'm pretty sure this is now fixed.
