### ISSUE TITLE
Seed faker in Python zygote

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#10683]
The Python zygote seeds the randomization process based on the variant's seed, both for the built-in random function and for numpy:

https://github.com/PrairieLearn/PrairieLearn/blob/97c57fcd8d7ba5e380cc72de919a4646e3e1f692/apps/prairielearn/python/zygote.py#L236-L237

The idea is that by running the generate function with the same variant seed, we will usually get the same params (with the caveat that changes in the question code, or even in the version of numpy, may cause changes in this process).

One other library often used for random information is faker. It also provides a [mechanism for seeding through `Faker.seed(...)`](https://faker.readthedocs.io/en/master/#seeding-the-generator). Given that the library has been used in multiple contexts, including [the example course](https://github.com/PrairieLearn/PrairieLearn/blob/97c57fcd8d7ba5e380cc72de919a4646e3e1f692/exampleCourse/questions/demo/randomFakeData/server.py#L8-L29), I believe it makes sense to also add a call to the seeder in the zygote itself. The alternative is to rely on instructors to seed it in the generate function, but I don't think most instructors would think of doing that.

This came about because I tried to regenerate a question with the same seed, and the values generated with the random library were recreated as before, but the values generated with faker were not.

I don't mind making the change, but I'm raising the issue to check if there are any thoughts around it.

**Comment by eliotwrobson** [comment]
Seems like a reasonable change to make. I don't think anyone should be relying on the previous behavior? There might be a case I'm not thinking of.
