### ISSUE TITLE
Lack of top margin for pre/pl-code elements

### ISSUE THREAD

**Issue by joelostblom** [PrairieLearn/PrairieLearn#10693]
It seems like the margin on top of pre/pl-code elements is missing

![image](https://github.com/user-attachments/assets/92177700-0452-470b-91f9-5aa3a129a12f)

If I compare to the bootstrap docs, they have spacing both above and below the code blocks, which makes them stand out more instead of blending together with the text above.

![image](https://github.com/user-attachments/assets/a6b200c2-e2f9-4ff2-a412-23c9ff859e58)

While it is possible to add `<br>` tags to each question individually, I wonder if you would consider adding spacing above code blocks in PL as the default?

Question source:

```
<pl-question-panel>
    paragraph of text here paragraph of text here paragraph of text here
    paragraph of text here paragraph of text here paragraph of text here
    paragraph of text here

    <pl-code language="r">
+ scale_color_manual(values = c('#FF7F50', '#4682B4', '#663399'))
</pl-code>
    paragraph of text here paragraph of text here paragraph of text here
    paragraph of text here paragraph of text here paragraph of text here
    paragraph of text here
</pl-question-panel>

```

**Comment by joelostblom** [comment]
I see now that other elements have similar issues, e.g. the rich text editor is also flush against the preceding text rather than separated by a little bit of whitespace.

![image](https://github.com/user-attachments/assets/648a9d6f-008c-47f3-96f8-d5e5f3f73165)

Here, using `margin-top` does have the intended effect (15px in the screenshot):

![image](https://github.com/user-attachments/assets/2c5b1154-d7df-4182-a112-b1606fe7e31b)

**Comment by nwalters512** [comment]
Bootstrap's spacing system relies on margins *after* (on the bottom of) each element. For both proper spacing and correct semantic meaning, you should wrap "paragraph text here..." in the [`<p>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p).

**Comment by joelostblom** [comment]
Ah yes that does it, this is a non-issue/user-error then. Thanks for the quick reply!
