### ISSUE TITLE
Issues reported on manual grading page show incorrect user

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieLearn#10700]
Whilst manually grading questions, the staff information panel allows you to report an issue however it is reported as the student name, not the staff member who creates the issue

![image](https://github.com/user-attachments/assets/9ba4d105-6595-43f7-ba7e-d416e944d79e)

![image](https://github.com/user-attachments/assets/b1db94d6-3ebe-4974-856d-aee663485fa9)

**Comment by nwalters512** [comment]
Issues track both `user_id` and `authn_user_id`. When an issue is reported for a variant, the `user_id` is set to the owner of the variant, assuming that it's a non-group-work assessment:

https://github.com/PrairieLearn/PrairieLearn/blob/d333c67a5c4a63bda972a0f42c862f4cb4524727/apps/prairielearn/src/sprocs/issues_insert_for_variant.sql#L21-L39

This isn't very intuitive to me. I'm inclined to say that we should no longer infer the user based on the variant and instead rely on it being explicitly passed to `insertIssue`. In most cases, we should then be able to do the following:

```js
user_id: res.locals.user.user_id,
authn_user_id: res.locals.authn_user.user_id,
```

**Comment by mwest1066** [comment]
I agree we should explicitly pass in both user IDs rather than attempt (incorrectly) to infer them.

**Comment by echuber2** [comment]
I'm not sure if it's actually related, but I recalled a much older issue that was similar: https://github.com/PrairieLearn/PrairieLearn/issues/1505 Linking it here to avoid deja vu later.
