### ISSUE TITLE
Jupyterlab and jupyterlab-python docker images seems to be out of sync

### ISSUE THREAD

**Issue by joelostblom** [PrairieLearn/PrairieLearn#10719]
I noticed that there is much more config and recent updates in the jupyterlab-python image compared to the jupyterlab image. Take for example the [server config for the former](https://github.com/PrairieLearn/PrairieLearn/blob/master/workspaces/jupyterlab-python/jupyter_server_config.py) versus [that of the latter](https://github.com/PrairieLearn/PrairieLearn/blob/master/workspaces/jupyterlab/jupyter_notebook_config.py).

I wanted to create a jupyterlab image that uses R so I ended up copying the server config and other differences from the Python directory and build a new image. It would be convenient if the jupyterlab image was kept up to date with all the latest non-python related changes so that all other images could build off this image and then add language specific setup.

**Comment by nwalters512** [comment]
`prairielearn/workspace-jupyterlab` is not maintained and is not recommended for use or meant as a foundation for other images. This is a good reminder that we should document that somewhere.

**Comment by joelostblom** [comment]
Thanks for the info! Would you consider maintaining a base image that can serve as the foundation for both R and Py images using jupyterlab? E.g. in this PR https://github.com/UBC-MDS/prairielearn-dockers/pull/15 I wanted to have R and Py in the same jupyterlab, so I opted to use the included mamba installer to facilitate this. I also don't need all the packages that are currently pip installed in jupyterlab-python image, so would prefer an image without those.

**Comment by nwalters512** [comment]
I think introducing a `prairielearn/workspace-jupyterlab-base` image would be reasonable. We've thought about doing the same for VS Code with a hypothetical `prairielearn/workspace-vscode-base` image that could be used to build workspaces for any language.

I won't commit to or even suggest a timeline in which we might get to this, but I'd be happy to review a PR that splits the current Python Jupyterlab image into a base image and a Python-specific image.

**Comment by joelostblom** [comment]
Great! I could put up a PR that simply moves all the non-python specific config to jupyterlab-base (so essentially all of the server config and everything except the python package install from install.sh) and then bases the python images off jupyterlab-base.

**Comment by echuber2** [comment]
@joelostblom I'd love it if you could take a look at https://github.com/PrairieLearn/PrairieLearn/pull/9831 that's in limbo currently. I think if PL offers vscode and jupyter "base" images it would make sense to hide all the uid/gid fixes away in that layer.

**Comment by joelostblom** [comment]
I agree that it would be great to have a layer like this to deal with any required permission settings! I will leave a comment there.

**Comment by nwalters512** [comment]
#10720 added documentation to make it clear that `prairielearn/workspace-jupyterlab` is no longer maintained. I'm still very open to the introduction of a `prairielearn/workspace-jupyterlab-base` image, but further discussion of that should be done in a separate issue.
