### ISSUE TITLE
authzCourseInstance: `force_mode` not needed anymore?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1071]
In `authzCourseInstance` there is a `force_mode` flag that overrides the `authn_mode` with whatever the cookie is. A strange side effect of this is that in the `effectiveUser` page the default mode is always the selected mode (in development, where authType =='none'):

https://github.com/PrairieLearn/PrairieLearn/blob/1bf13e0c67005f7e179c6c86b1577a0d3bbbc5a2/middlewares/authzCourseInstance.sql#L3

That seems like a bit of legacy code hold-over before `authn_mode` and `mode` were split in `res.locals.authz_data`. I suspect it's not needed anymore and could be removed? If not, why?

**Comment by nwalters512** [comment]
This was removed in #3020.
