### ISSUE TITLE
Instructional Videos for PL Use

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1079]
When I was talking with my CAs, I noticed that having the following resources would likely help in understanding PLs system:

- Workflow for developing a question
- Answering a question on PrairieLearn
- Setting up a course (via pl template)

**Comment by coatless** [comment]
@mwest1066 + @trombonekenny 

Shot a few “rough” videos on the setup procedure a course with PL.

https://www.youtube.com/playlist?list=PL50Yqb_ZFDeeWlWSASZMGMLLjYW07xz8A

This is due to #2006. May be useful for onboarding in the interim.

**Note:** These focus on "copying" and "pasting" examples from web docs with slight changes.

**Comment by coatless** [comment]
Outline for Videos

### Setting up a Course

**Goal:** Fast course creation.

- Show request to Matt?
- Login to PrairieLearn
- Modify infoCourse.json from web interface
- Modify infoCourseInstance.json from web interface
- Add example question?

### Question Development

Focus on three elements:

- pl-multiple-choice
- pl-number-input
- pl-symbolic-input

Potentially, show how to construct a question with each element in the web browser interface.

Consider borrowing ideas from SP 20 training by @mfsilva22 

- https://github.com/PrairieLearn/pl-train101/blob/master/Docs/Starting-with-PL.md

### Welcome to PrairieLearn

Provides an overview to PrairieLearn and its features.

- Login to PrairieLearn
- Course Enrollment
- Demo of assessment questions
  - Emphasize mastery learning approach
  - Show retry attempts
- Explore a few demo questions in the XC course.

@echuber2 shot something similar for MCSDS: https://mediaspace.illinois.edu/media/t/1_98sr4m91


@mwest1066 @trombonekenny @nicknytko @mfsilva22  Thoughts on the outline? 

How did you feel about the code zooms in the first set of videos? 

https://www.youtube.com/playlist?list=PL50Yqb_ZFDeeWlWSASZMGMLLjYW07xz8A

**Comment by mwest1066** [comment]
I would focus on `pl-multiple-choice`, `pl-checkbox`, and `pl-number-input`. I think anything else is too complicated for a beginner. You could give a "whirlwind tour" of other elements just to inspire people, but I'd stick with the basics.

**Comment by mwest1066** [comment]
Are we assuming that we give people course repos with a minimal structure already in them? That is, one course instance, one question, one assessment, or something like that? So they can then modify them? Maybe two questions, one homework, and one exam?

**Comment by coatless** [comment]
@mwest1066 that was my hope. Basically, use `pl-dept101` as the template course. Show how we're modifying it. 

This means when you're creating the new repo, its being done with [Import repository](https://github.com/new/import) or GitHub's [template feature](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/). 

![Screen Shot 2020-03-18 at 9 07 14 PM](https://user-images.githubusercontent.com/833642/77024427-80617600-695c-11ea-9123-8b7e1d248dc4.png)

**Comment by coatless** [comment]
@mwest1066 one issue that is coming up in the process is we can't create a new question from something in the example course. Maybe @tbretl could add that real quick?

**Comment by nicknytko** [comment]
Hey, don't have access to the `pl-dept101` repo?

**Comment by mwest1066** [comment]
> Hey, don't have access to the `pl-dept101` repo?

Fixed!
