### ISSUE TITLE
Make "correctness" message more accurate for end users when uploading files

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#108]
Currently, students are told that their submission was "correct" when files are uploaded. However, that's really more of an indication that the file was successfully uploaded. It might be worth adding a condition to determine if a question is a file upload question - and if it is, say that the file was uploaded successfully (and that correctness will be determined later) or something along those lines.

**Comment by mwest1066** [comment]
This is a good idea. Want to try adding in an extra flag somewhere to indicate that questions have deferred grading?

**Comment by mwest1066** [comment]
This should be handled by #313.

**Comment by mwest1066** [comment]
Closing in favor of #313
