### ISSUE TITLE
release-image.sh tag specification not working

### ISSUE THREAD

**Issue by Binary-Eater** [PrairieLearn/PrairieLearn#1081]
Cannot seem to get the script to build to a tag other than latest

Command Issued
./tools/release-image.sh -t valgrind-test centos7-cs225
Log of command output.
[release-tool-log.txt](https://github.com/PrairieLearn/PrairieLearn/files/1839235/release-tool-log.txt)

**Comment by mwest1066** [comment]
@nwalters512 might have something to say about this?

**Comment by nwalters512** [comment]
Yep, on my radar, I'll take at the meeting today.

**Comment by mwest1066** [comment]
We've transitioned away from using these scripts in favor of letting courses figure out their own image release systems.
