### ISSUE TITLE
Support server_files_course_file in dynamic workspace files

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieLearn#10874]
Creating an issue as mentioned from @jonatanschroeder in [Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1730315528219469)

> Actually it may be better to add an issue to support server_files_course_file alternative to question_file in dynamic workspace files

I don't quite follow the specifics personally so hopefully Jonatan can jump in with more information if required

**Comment by jonatanschroeder** [comment]
Details in PR description for #10875.
