### ISSUE TITLE
Python autograder: `__name__` is not set to `__main__`

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#10897]
A good programming practice in Python is to use a pattern like:

```python
if __name__ == '__main__':
    # global code
```

This is currently not possible in the autograder because student code runs with `__name__` set to "builtins", as seen below (from https://us.prairielearn.com/pl/course_instance/4970/instructor/question/7455975/preview/?variant_id=106441703):

![Image](https://github.com/user-attachments/assets/f7c9e766-b0f6-4fe2-86f3-80bade35765d)

If there is a way to override (?) the value of `__name__` in the autograder's execution of student code that would be good.

**Comment by eliotwrobson** [comment]
![Image](https://github.com/user-attachments/assets/4ae095e3-4c30-4f46-8b2b-646d7918b3a5)

Maybe try putting this in the leading code?

**Comment by jonatanschroeder** [comment]
I know I can do that as a workaround, I'm asking if this should be the default.

**Comment by nwalters512** [comment]
I can't imagine we could make this the default in a backwards-compatible way. It'd be entirely valid for an instructor to say "implement your code in `def fib(...)` and place any personal testing code in a `if __name__ == '__main__': ...` block" and remain confident that that testing code won't run during test execution.

**Comment by jonatanschroeder** [comment]
Ok, that's fair. I'll make a PR to add a comment in the docs with a way to set it up in leading_code or setup_code.
