### ISSUE TITLE
Exam number isn't reflected on index page

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#110]
When you're doing an exam, there's a floating module on the right hand side that tells you you're working on "ExamTest #1". However, the main index page merely says that it's "ExamTest" with no indication that it's the first one. Changing the exam title in info.json so that it's "ExamTest1" results in the module saying "ExamTest 1 #1" and the main index page "ExamTest 1".

**Comment by mwest1066** [comment]
Would you mind sending me a pull request to fix this?

**Comment by mwest1066** [comment]
Fixed in 32c205c9d5a36132386f6959798049d61265e805
