### ISSUE TITLE
Make course_instance available from an instructor question instance

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1100]
This is needed to ensure that course custom elements can be rendered properly during an async submission panel rerendering for external grading.

**Comment by rbessick5** [comment]
I believe that `locals.course_instance` is defined whenever you load the `instructorQuestion` page within a course instance. Does the external grading need it to be available somewhere else?

**Comment by mwest1066** [comment]
We shouldn't need a `course_instance` to render a question, especially because we might not have a course instance yet (we might have a course that only contains questions for sharing, for example).
