### ISSUE TITLE
Improve Local Development Experience

### ISSUE THREAD

**Issue by reteps** [PrairieLearn/PrairieLearn#11009]
I had a slightly annoying time setting up local development due to inconsistent preinstalled versions of things I had (wrong node, wrong postgres, missing pg_vector, missing redis). I have been following along and comparing tools like `pyenv`, `asdf`, etc. for my own local setup. Now there is a tool, `mise`, which I think shows the most promise out of all of them: https://mise.jdx.dev/

It core features stood out to me as adding value:

- makefile replacement with tab completion syntax, and support for CLI flags (https://mise.jdx.dev/tasks/toml-tasks.html#toml-based-tasks, https://mise.jdx.dev/tasks/file-tasks.html#arguments)
- very straightforward dependency lists (https://mise.jdx.dev/dev-tools/#dev-tools)

I might play around with this a little bit and see if one could use mise to get the repo running locally without Docker, and without installing anything extra. Curious if this is something we are interested in: would massively simplify the local development experience, and if we switch the makefiles, running stuff as well.

**Comment by mwest1066** [comment]
Improving the local dev experience without docker would certainly be great!

I see that `mise` handles node and python, which is nice. Does it have some way of managing servers like postgres and redis?

**Comment by mwest1066** [comment]
I see there is also #11010? Dup?

**Comment by nwalters512** [comment]
It does look like it can manage Postgres and such, per https://mise.jdx.dev/registry.html. There are caveats:

- Postgres is built from source (https://github.com/smashedtoatoms/asdf-postgres) which is much less seamless than just letting Homebrew do its thing.
- You have to specifically keep `redis-server` running in a shell for anything to work: https://github.com/smashedtoatoms/asdf-redis.

With these caveats, I'd keep on doing exactly what I do with Homebrew right now even if we had a `mise.toml` file.

I frankly don't think this is even close to the worst part of local dev. On macOS + Linux (the core dev team almost exclusively uses the former, I think), system package managers like Homebrew make it dead simple to install our dependencies (Node, Python, Postgres, Redis). I spend on the order of minutes each year managing these things; I hope this is true for others as well.

I'm personally a lot more excited about possibly getting a working devcontainer config (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).

The current Makefile is used in our production deployment. If you plan to replace it (I'd need an argument as to why it's insufficient), we'd have to carefully coordinate that to ensure we don't break production deployments.

**Comment by reteps** [comment]
Good points, specifically relating to redis-server. I'm fine closing this with redis-server in mind.

**Comment by echuber2** [comment]
Regarding dev containers... most recently, if I needed to experiment with the PL code itself, I've just used the PL Docker with local source mounted in.

**Comment by mwest1066** [comment]
Personally I've native found local dev (no docker) on MacOS to be easy to manage. I install Postgres/Redis/Python with Homebrew, make a venv for python before running `make deps`, and everything is smooth. I have no idea about Windows/Linux local dev, however.

I guess one nonobvious note is that I need to install `pygraphviz` with:
```
pip install --config-settings="--global-option=build_ext" \
                   --config-settings="--global-option=-I$(brew --prefix graphviz)/include/" \
                   --config-settings="--global-option=-L$(brew --prefix graphviz)/lib/" \
                   pygraphviz
```
Otherwise `pygraphviz` can't find the homebrew-installed graphviz headers.

I do think we should update https://prairielearn.readthedocs.io/en/latest/installingNative/ with instructions for using a venv. Let me try and do this right now.

**Comment by nwalters512** [comment]
Regarding venvs, see https://github.com/PrairieLearn/PrairieLearn/pull/10984, where I updated the dev scripts to use one by default and taught PL how to automatically use it, even without explicit activation. Let me know what you think of this approach.

**Comment by mwest1066** [comment]
Ah, sorry, I'm too far behind here. I just made #11012 but added a ref to #10984 in it. Let me experiment with #10984 later.

**Comment by reteps** [comment]
Maybe I can close this in favor of a future issue specifically about a dev containers configuration in the future?

**Comment by nwalters512** [comment]
@reteps that sounds good to me! In the meantime, if there are any documentation changes that would have helped you get up and running faster, PRs are definitely welcome to help folks until we can tackle Dev Containers or some other bigger solution.

**Comment by reteps** [comment]
Note for myself: a more detailed step-by-step native guide would be helpful. Especially resolving a previously installed, incompatible version of postgres.
