### ISSUE TITLE
Type res.locals in TypeScript

### ISSUE THREAD

**Issue by reteps** [PrairieLearn/PrairieLearn#11026]
- Should be possible: https://stackoverflow.com/a/75546820/5684541

- Requires #11022

**Comment by nwalters512** [comment]
The reason it's not just as simple as type augmentation is that the things that are present in `res.locals` vary widely between pages.

**Comment by reteps** [comment]
I agree, that link I sent would give you optional res.locals. If you want a fully typed res.locals that would be really hard.

- https://stackoverflow.com/a/66320733/5684541
- https://stackoverflow.com/questions/74145585/typescript-types-for-middleware-transformation-pipe

**Comment by reteps** [comment]
Certainly a hard problem that requires a large discussion.

**Comment by reteps** [comment]
Going to close this until there is further discussion.
