### ISSUE TITLE
Strongly type element attributes

### ISSUE THREAD

**Issue by reteps** [PrairieLearn/PrairieLearn#11049]
Currently, element attributes are typed using this syntax:

```
VARIABLES_DEFAULT = ""
SIZE_DEFAULT = 35
SHOW_HELP_TEXT_DEFAULT = True
WEIGHT_DEFAULT = 1
DISPLAY_DEFAULT = DisplayType.INLINE
BIG_O_TYPE_DEFAULT = BigOType.BIG_O
PLACEHOLDER_DEFAULT = "asymptotic expression"
SHOW_SCORE_DEFAULT = True
ALLOW_BLANK_DEFAULT = False
BLANK_VALUE_DEFAULT = "1"
BIG_O_INPUT_MUSTACHE_TEMPLATE_NAME = "pl-big-o-input.mustache"
```

```python
    required_attribs = ["answers-name"]
    optional_attribs = [
        "weight",
        "correct-answer",
        "variable",
        "size",
        "display",
        "show-help-text",
        "type",
        "placeholder",
        "show-score",
        "allow-blank",
        "blank-value",
    ]
    pl.check_attribs(element, required_attribs, optional_attribs)
```

```python
    name = pl.get_string_attrib(element, "answers-name")
    variables = phs.get_items_list(
        pl.get_string_attrib(element, "variable", VARIABLES_DEFAULT)
    )
    display = pl.get_enum_attrib(element, "display", DisplayType, DISPLAY_DEFAULT)
    size = pl.get_integer_attrib(element, "size", SIZE_DEFAULT)

    bigo_type = pl.get_enum_attrib(element, "type", BigOType, BIG_O_TYPE_DEFAULT).value
    placeholder = pl.get_string_attrib(element, "placeholder", PLACEHOLDER_DEFAULT)
    show_score = pl.get_boolean_attrib(element, "show-score", SHOW_SCORE_DEFAULT)
    show_info = pl.get_boolean_attrib(element, "show-help-text", SHOW_HELP_TEXT_DEFAULT)
```

I propose some clever use of https://docs.pydantic.dev/latest/#pydantic for handling these. I.e. each element defines a Pydantic Class for attribute deserialization.

Immediate benefits:

- Can type/annotate attributes from the source code itself (see #11006) using the Pydantic models
- Way less boilerplate

I am envisioning something like

```python
class BigOModel(BaseModel):
    name: str
    value: Enum[1, 2, 3]
    foo: str = "bar"

try:
    element_attrs = BigOModel(element)
except ValidationError as err:
   # raise some error
```

See [Validators](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) for more information.

Which then gives you access to a fully typed `elements_attrs` object.

Cons:

- A pain to review: I would be willing to convert a sample element over break and then convert the rest if we like the idea.
- Another dependency to install in the grading container
- Still needs a serialization layer to convert from lxml to a format that Pydantic understands (e.g. JSON). So the deserialization from html layer still exists, but it doesn't need to do validation at that layer anymore.

**Comment by eliotwrobson** [comment]
I've thought about doing something like this in the past. It's definitely elegant, especially if it can help us automate our documentation creation, but my main hesitation is lack of immediate benefits to end users for a large change that could break something. This would be a really good idea if we were adding new elements every few weeks, but after a bunch of additions a couple years ago the number of new elements has slowed way down.

**Comment by reteps** [comment]
Going to close this in light of @eliotwrobson 's comments -- I may reopen this at a future point.
