### ISSUE TITLE
Request: New Exam Question Feedback Format

### ISSUE THREAD

**Issue by w-chang** [PrairieLearn/PrairieLearn#1105]
For multi-part exam questions, make available the exact solution of the part after the student submit an answer within the allowable tolerance in addition to the current feedback of marking it as correct. The goal here is to prevent students from getting the wrong answer(s) in subsequent parts due to error propagation.

**Comment by mwest1066** [comment]
This has been implemented for `pl-number-input`. Clicking on the "100%" badge shows the exact value of the answer. This is not very discoverable, but it _is_ there.
