### ISSUE TITLE
Question title shows name of directory

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#111]
When you're completing a question, regardless of whether it's a homework or test question, you get both the "colloquial", end-user friendly (and Instructor/TA/etc. specified) title as well as the name of the directory in parenthesis.

**Comment by mwest1066** [comment]
This is intentional and is controlled by the `seeQID` permission: https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/courseConfig.md
