### ISSUE TITLE
[Feature Request] Adding answers to Instructor's Questions page

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1114]
On the question page, it would be nice if we could have a section under the question panel that shows the answers for each part of the question, c.f. LON-CAPA's implementation:

![screen shot 2018-04-22 at 10 16 34 am](https://user-images.githubusercontent.com/833642/39096494-6cade60e-4616-11e8-8eed-49ed97c37bc7.png)

In addition, it may be useful to provide a "script-vars" option that display the `params` array instead of clicking into `Test Once with full details`

**Comment by mwest1066** [comment]
See #1560 for essentially the same thing.

**Comment by mwest1066** [comment]
closing in favor of #1560
