### ISSUE TITLE
help sheet student uploads for exams

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1115]
Allow students to upload a help sheet to PrairieLearn outside of the CBTF that they can access inside.

Feature request to work around bringing paper into the CBTF.

**Comment by coatless** [comment]
💯 I do this right now by including pre-made cheat sheets... But, wow... This would be nice!

**Comment by trombonekenny** [comment]
This issue came up in a conversation with Abdu today. He'd like the ability for course staff to upload reference sheets for an assessment per-student instead of assessment-wide ones. That's a little different use case than the root issue because students wouldn't be able to attach them, but staff would.

**Comment by firasm** [comment]
Quick update on this issue: 

As of #10432, `"allowPersonalNotes"` can be set as False as a top-level option in the infoAssessment.json to disable personal notes in assessments.

With the file-upload element set to one submission only, Manual Grading (to review sheets before exams in case there are limitations on the formula sheet), and access modes (to allow students the ability to see other assessments in a CBTF), we now have all the pieces needed to do formula sheets securely in PrairieLearn.

More [details are here](https://prairielearn.readthedocs.io/en/latest/assessment/#student-attached-personal-notes). 

I would consider this issue resolved. During office hours, we considered more heavy weight functionality, but felt that this was a pretty good solution.

@trombonekenny and @coatless - can we close this issue ?

**Comment by nwalters512** [comment]
This is of course not quite as elegant as some fancy cheat-sheet-specific functionality, but I think this solution is good enough for now, as it's not too difficult to describe or implement. We might consider officially documenting this as a pattern that we can point folks too, but this comes up infrequently enough that I don't think there's a ton of value in doing so right now.
