### ISSUE TITLE
Is it possible to add an option to remove the "hint" inside the input box?

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#1118]
For the input element, I think it will be beneficial if we can disable the message inside the text box indicating what is the type of tolerance used. I understand this is an important feature, and most people would use it anyways, but I think adding the option would be nice (I have cases in which I would prefer to remove it. BTW, anyone out there planning to implement an "integer" box?

**Comment by coatless** [comment]
I've rigged a development version with `hide_help_text` to disable the placeholder within the input field. I assume there won't be an issue if we leave in the `?` mark with a mouseover?

![screen shot 2018-04-23 at 9 23 03 pm](https://user-images.githubusercontent.com/833642/39162738-a26e1e86-473c-11e8-80aa-6908f39ed51d.png)

**Comment by coatless** [comment]
@mwest1066 this can be closed out as well.

**Comment by mwest1066** [comment]
@coatless thanks!
