### ISSUE TITLE
Assessments don't update after changing viewing role

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#112]
Prereqs:
(1) Role defaults to Superuser
(2) Have an active assessment that has minRole set to "Student"

Repro:
(1) Change viewing role to student
(2) Click on "Assessment"
(3) Nothing shows up even though API calls are being made

I haven't verified that this issue exists in production.

**Comment by mwest1066** [comment]
I can't reproduce this. Can you try with a fully-updated PL and using the default exampleCourse? If you change to "Student" role then you should see just Homework 1 on the Assessments page.

I also opened #113, which might be related to what you say here (although it's not the issue with the Assessment page).

**Comment by tnip** [comment]
This still occurs on and off - I'm assuming I'm just moving a bit faster than required resources can update with the new state.

**Comment by mwest1066** [comment]
Thanks for confirming. Are you still doing the procedure in your initial comment? That is, changing role then switching to the Assessment page? Is it then the case that the Assessment page is blank? I'm having trouble reproducing this, hence all the questions!

**Comment by mwest1066** [comment]
Superseded by v2
