### ISSUE TITLE
Improved Makefile

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1124]
Right now, the `Makefile` for the project is hidden underneath the `doc/` directory.  

I'd like to add a `Makefile` into the main directory that focuses on:

**docs**
1. Build the `doc/` folder using `mkdocs build`
1. Serve the `doc/` folder using `mkdocs serve`
1. Render automatically generated images. 

**pl-dev**
1. Build the PL Development Docker Container
1. Launch a PL Development Docker Container

**pl-dev-tests**
1. Run the linters against the PL Development Docker Container
1. Run the test suite against the PL Development Docker Container

I think naming the recipes along the lines of `build-docker`, `run-docker`, et cetera would be appropriate.

**Comment by nwalters512** [comment]
@coatless do you still want to contribute this? Otherwise I'll close this issue.
