### ISSUE TITLE
Non-feedback Exam Mode

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1128]
Per a [reddit](https://www.reddit.com/r/UIUC/comments/8ecp7t/cbtf_tests/dxva3f9/) comment on the CBTF:

> More like on written exams you aren’t given the chance to slowly watch your grade drop with each wrong attempt

I think it may be advantageous to setup a mode where correct/incorrect responses are not shown if there is only one attempt allotted. This allows for the matching of a traditional paper-based exam and may influence the effects of slipping (Wrong Answer | Know Material) and guessing (Right Answer | Don't Know Material) on a given exam.

**Comment by mwest1066** [comment]
Fixed by @trombonekenny in 4b88ed0ea7a5017746fc807cb0016efc566a35e2
