### ISSUE TITLE
warn student leaving a question instance page without saving

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1132]
Add the javascript 'are you sure you want to navigate away' warning to question instance pages. I don't think that's custom code; it's just triggering the browser to warn.

From Mariana based on her TA's walk-through of a first time with PrairieLearn. Maybe Relate does this?

**Comment by nwalters512** [comment]
I think this is custom code, and it probably requires changes (and collaboration, somehow) for all elements on the page.

**Comment by trombonekenny** [comment]
https://stackoverflow.com/questions/1119289/how-to-show-the-are-you-sure-you-want-to-navigate-away-from-this-page-when-ch

We just need something like this in a `<script>` in the header:

```js
// Enable navigation prompt
window.onbeforeunload = function() {
    return true;
};
```

**Comment by mwest1066** [comment]
Presumably the same as #506

**Comment by tdy** [comment]
Just to clarify, are we talking about using this JS on question pages? If so, it's firing on all unloads, even if I've done nothing on the page... save, save+grade, back, settings/stats tab, etc.

```js
<script>
   // Enable navigation prompt
    window.onbeforeunload = function() {
        return true;
    };
</script>
```

**Comment by mwest1066** [comment]
The idea is that this JS fires on all page unloads, at which point it needs to check whether the student actually has unsaved data. If so, then it could put up a dialog saying something like "You have not saved your answer" and buttons like "Save and proceed" or "Discard changes and proceed" or something.

To detect whether the answer has changed will require saving a copy of what the answer looked like when the page first loaded. All answers are stored in form elements inside the question form, so we are trying to detect whether the form `value` attributes have changed. We could save a copy of them either using client-side JS that scrapes them out of the form after page load (may be racy with students editing the form?) or by having the server walk the form HTML before sending it and copying `value` into `data-original-value` in each form element, or something like that. This could be done in https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/question.js#L1189 which is the function that makes all the HTML for the question page panels (question panel, answer panel, etc).

**Comment by tdy** [comment]
So in [lib/question.js#L1189](https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/question.js#L1189), would we be scraping `locals.question`? or `locals.questionHtml`? or something else? and then saving the state in another `locals` var? still not totally clear what's happening server-side.

BTW is it worth implementing this server-side or should I just submit the client-side PR now?

**Comment by mwest1066** [comment]
I think `locals.questionHtml` is exactly what we'd need -- that's precisely what is going into the question panel that the student will see.

Do you have a working client-side version already? If so, submit it as a PR so we can take a look, even if we end up going with a server-side solution.

**Comment by tdy** [comment]
Ok, I do have a client-side version tested in Firefox/Chrome/Edge (no convenient access to Safari since my MBP died). I'll post the PR.

**Comment by tdy** [comment]
Just for posterity -- (I think) the server-side version would actually use "submission" locals instead of "question" locals. From my cursory debugging, it seems `locals.questionHtmls` only holds the text part of questions. I think input fields are generated using `locals.submission.submitted_answer`.

However, server-side walking will not work for client-side form controls like ace-mode, pl-drawing, pl-file, etc.

#2215 is a client-side version that works for all controls (tested so far) but theoretically could introduce a race condition.
