### ISSUE TITLE
pl_multiple_choice duplicates correct pl_answer, one is false?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1134]
Proctors reported the student saying there was a duplicate answer on a multiple choice v3 question. They chose one, got it wrong, then chose the other for full credit.

https://prairielearn.engr.illinois.edu/pl/course_instance/8303/instance_question/17307084

Question only lists the correct answer once:
https://github.com/PrairieLearn/pl-stat385/blob/master/questions/midterm2MCstr_detect2/question.html

I don't think @coatless coded the question wrong but I can't explain it. pl_answer bug?

**Comment by coatless** [comment]
Issue with the question. Two of the same answers already initiated a patch.

**Comment by trombonekenny** [comment]
Ah, I didn't realize I was looking at an already fixed question.html. (Long day.) Sorry about that @coatless -- thanks for the quick fix and sorry for the extra issue.

**Comment by coatless** [comment]
@trombonekenny no worries. Appreciate the heads up.
