### ISSUE TITLE
Student information inside the issue report

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1136]
It would be nice to include the student info on the issue report inside the question:

<img width="699" alt="screen shot 2018-04-26 at 8 26 32 am" src="https://user-images.githubusercontent.com/833642/39308681-a8b619ce-492b-11e8-8991-cf922f6c2533.png">

**Comment by coatless** [comment]
So, digging into the source, we have the issue being displayed within the question here:

https://github.com/PrairieLearn/PrairieLearn/blob/d778207853a33910a76719146d57f0e61feae843/pages/partials/question.ejs#L16-L27

The data that is supporting this call is found under `issues`. What I'm missing is where the `issues` data is being fetched from. Is this a direct call into the `issues` table?

https://github.com/PrairieLearn/PrairieLearn/blob/c8de1553955c200ca6ffb15b2ac94a17cd01b291/database/tables/issues.pg#L1-L5

Or is this being fed by a separate view?

https://github.com/PrairieLearn/PrairieLearn/blob/c8de1553955c200ca6ffb15b2ac94a17cd01b291/pages/instructorIssues/instructorIssues.sql#L21-L34

**Comment by mwest1066** [comment]
Apologies that the control-flow is a bit convoluted here. I added docs on how question rendering works: http://prairielearn.readthedocs.io/en/latest/dev-guide/#question-rendering-control-flow

Specifically for `issues`:

1. Issues are loaded by https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/question.sql#L1

2. They are then stored as `res.locals.issues` by https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/question.js#L1257

3. They are rendered at https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/partials/question.ejs#L6

To add the user we will need to modify the SQL to add a JOIN on the `users` table to get the `uid` for display, and then we'd need to render it in the `pages/partials/question.ejs` template.

**Comment by coatless** [comment]
@mwest1066 Thanks for the breakdown!

I've implemented the add as:

![screen shot 2018-04-29 at 8 44 55 pm](https://user-images.githubusercontent.com/833642/39413334-40fa6270-4bee-11e8-95a6-1df7bee719ef.png)

This combines the `user.name` and `user.uid`

https://github.com/PrairieLearn/PrairieLearn/blob/c8de1553955c200ca6ffb15b2ac94a17cd01b291/database/tables/users.pg#L2-L4

See the PR for details.

**Comment by nwalters512** [comment]
Resolved by #1140
