### ISSUE TITLE
Instructor assessment slow to download files

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1137]
https://github.com/PrairieLearn/PrairieLearn/blob/291a63790d755410807959e11b519b6ca776a957/pages/instructorAssessment/instructorAssessment.sql#L329

Long query run related to sequential scan of the `submissions` table.

Query passes on docker and pl-dev but hangs on the production PL table.

**Comment by mwest1066** [comment]
Fixed by #1152
