### ISSUE TITLE
Rendering Externally Graded File Containing Single Space Generates Error

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1147]
![image](https://user-images.githubusercontent.com/445443/39673122-0824b8d4-50fc-11e8-8a51-419756bee199.png)

Note that this is an attempt to work around the fact that an empty externally-graded starter file causes the editor to contain "None" (clearly Python at work) at startup.

**Comment by nicknytko** [comment]
@gchallen are you still experiencing this?  I'm not able to reproduce on my end.

**Comment by nicknytko** [comment]
Closing, the line in the error seems to have been fixed now and I can't reproduce.
