### ISSUE TITLE
Deleting assessment instance is slow

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1148]
We should analyze the query that removes assessment instances. It takes a noticeable amount of time (10s?) to remove even a single assessment instance without many questions or variants on the production server. Maybe something needs an index?

**Comment by trombonekenny** [comment]
Hitting this again with ESPL's workflows

**Comment by mwest1066** [comment]
Setting this as a bug. The right way to fix it is to move to soft-deletes.

**Comment by trombonekenny** [comment]
Resolved with #1293
