### ISSUE TITLE
Files download fails

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1155]
As an example, CS 125 final exam file download fails. Running the query by hand takes about 80 s and returns 5 MB of data, both of which should be manageable.

**Comment by gchallen** [comment]
Anecdotally I also think that this query can cause serious problems with ongoing assessments—at minimum within the same course and maybe across the whole PL instance? (No evidence for that.) Evidence: two attempts to run this query both created clustered of "Rendering failed" issues during our CS 125 exam, with timestamps that matched well with the time that the downloads were attempted. I didn't try to reproduce 🙁.

**Comment by trombonekenny** [comment]
gwa: I think the PrairieLearn front end had python concurrency problems due to finals load around the same time these database calls were done. Lacking any more definitive evidence, I can't see how a long database pull would have caused other v3 question rendering problems. (Unless something is sync that shouldn't be and caused other timeouts.)

matt: Do we know if it's the query time or the data returned that's the problem? Any logs on why it fails?

**Comment by gchallen** [comment]
I'm assuming you have the logs to run this down. If it's a coincidence, it's a very very strange one—particularly given that we saw so more similar problems all day despite having heavier exam periods later that Wednesday (IIRC).

**Comment by mwest1066** [comment]
Long-delayed followup to this:

1. There was an issue with large CSV downloads blocking student question code. This was fixed by #1364 

2. The API can be used as a work-around for large CSV downloads. Downloading from the API does not have any size restrictions because it's done object-by-object and the client is in control.

3. We should in any case still fix large CSV downloads to stream results from the DB query, which would allow very large CSVs to be downloaded. This should use https://node-postgres.com/api/cursor

**Comment by nwalters512** [comment]
This was resolved as of #7284. Query results are now streamed from the database using cursors, and the CSVs themselves are constructed via streaming instead of concatenation in memory.
