### ISSUE TITLE
Only report server load + usage when running in EC2

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1169]
These things currently use `externalGradingUseAws` as a flag to decide when to report stats, but we could be using the AWS-powered grader when running locally. There are already TODOs in code at the relevant points, this is just an issue to actually track them.

https://github.com/PrairieLearn/PrairieLearn/blob/master/cron/serverLoad.js#L11
https://github.com/PrairieLearn/PrairieLearn/blob/master/cron/serverUsage.js#L10

**Comment by mwest1066** [comment]
On further consideration it seems like we should replace both instances above with a new `config.useCloudwatchMetrics` variable/

**Comment by nwalters512** [comment]
This has since been addressed with the `runningInEc2` config option.
