### ISSUE TITLE
Investigate SSR for MathJax

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1183]
https://github.com/mathjax/MathJax-node (and https://github.com/pkra/mathjax-node-page/) exists, which means we could potentially avoid shipping any MathJax JS to the client. Combined with caching, this will help speed up page loads and avoid that annoying flash of un-mathjaxed content while the JS is loading and executing.

**Comment by mwest1066** [comment]
Oh, that would be sweet! I looked at this about three years ago and it was a huge mess at that time, but if SSR MathJax works now then it would be awesome.

**Comment by nwalters512** [comment]
I did a really basic test of this, it's adding considerable latency (300+ms for a question with 2 submissions) to all question renders. Obviously this is helped by caching, but still. Not sure if it's better to have the cost be on the server or the client.

**Comment by mwest1066** [comment]
I guess this is tempting because caching should make an enormous difference? But probably not a super high priority at the moment.

**Comment by nwalters512** [comment]
Not super high, no. This was really easy to do though, < 10 lines of code. We can easily revisit later.

**Comment by mwest1066** [comment]
If adding caching is only another 10 lines of code (which I guess it might be) then this could be extra tempting!

**Comment by nwalters512** [comment]
Caching is automatic once the other PR lands; this would happen as we're generating HTML to be cached.

**Comment by mwest1066** [comment]
I guess I was thinking we should add explicit caching for this. So sha256 of tex string to rendered math, or similar. Most math in a question is independent of the variant, so by caching the individual math strings the second student would get a much faster initial render. If that makes any sense?

**Comment by nwalters512** [comment]
Ahhh sure. I guess as long as we already have everything in AST format, we can just walk that and replace things that look like mathjax with their rendered version. The library I was using did the whole page at once, but it's built on another lib that only does typesetting of math bits. If we're willing to shoulder more complexity, we could definitely render and cache more granularly, which would hopefully see big perf wins.

**Comment by mwest1066** [comment]
Worth revisiting now that render caching has landed?

**Comment by echuber2** [comment]
https://katex.org/ is another option for this.

**Comment by nwalters512** [comment]
Client-side rendering of math hasn't caused any problems, and is in fact crucial for the way some newer elements work. Going to close this; we have no plans to implement this functionality.
