### ISSUE TITLE
Build scripts via npm run

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1191]
From PR #1141 

> Is this somewhere where we should instead be using more npm scripts? See https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

### Goals

1. Build development version of {PL, docs} and preview
2. Download live version of PL and preview
3. Switch between `exampleCourse` and live course

### Approach Sketch

Modify the `package.json` with:

```json
{
    "name": "PrairieLearn",
    "description": "PrairieLearn online problem-solving system",
    "version": "3.0.0",
    "private": true,
   "config": {
      "course": "./"
   }
  "devDependencies": {
        "@prairielearn/prairielib": "^1.5.1",
        "adm-zip": "^0.4.11",
        "archiver": "^2.1.1",
         " ... ": "..."
  },
  "scripts": {
        "start": "node server.js",
        "start-nodemon": "nodemon server.js",
        "test": "nyc --reporter=lcov mocha --exit tests/index.js",
        "lint-js": "eslint --ext js \"**/*.js\"",
        "lint-python": "python3.6 -m flake8 ./",
        "extensions_here":"..."
  }
}
```

Example of course dir set:

```bash
 # once only
npm set prairielearn:course_dir "/Users/mwest/git/pl-tam212"

# uses the config variable from able
npm run pl    
```

Dependency-wise:

- `pre<build>` for building docker image (c.f. ) 
- `post<build>` for cleaning

Variables accessed with:

```
$npm_package_config_{NAME}
```

**Comment by nwalters512** [comment]
We've since dropped `scripts` from `package.json` entirely (#4590) to work around an issue with npm v7.
