### ISSUE TITLE
Rate limit submissions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1195]
Add an option to assessment questions to rate limit submissions. It's probably better to have it set per-question and per-assessment, not just in the question itself.

**Comment by jonatanschroeder** [comment]
@mwest1066 I'm trying to come up with an implementation for this. A couple of questions:

* You mention a per-assessment setting, would this just be a default for each question (i.e., if I limit an assessment to one submission every 5 minutes, and submit one of the questions, I can submit another question within 5 minutes, but not the same question)? I think so, and I'm planning to implement it this way, unless you have something else in mind.
* We talked about this, but just to document it: this limit would apply to grading, not to submissions themselves. In other words, students can save at any rate, but can only save and grade based on this rate.
* Would this limit apply on the question level or the variant level? In other words, if I submit for one variant, get it correct, then get another variant, can I submit to the new variant faster than this rate? I'm fine either way for my use-case (the questions I have in mind for this will only present one variant to the students), but I'd guess this should apply to the question.
* The "Grade XX answers" in the Overview should also take this into account. I imagine that a simple warning if there are questions that cannot be graded yet (that these questions won't be graded) should suffice.
* When closing an assessment, I imagine the grading that happens on close supersedes this limit, i.e., grading that happens on assessment close can happen even if the submission rate hasn't been fulfilled yet for a question.

**Comment by mwest1066** [comment]
> * You mention a per-assessment setting, would this just be a default for each question (i.e., if I limit an assessment to one submission every 5 minutes, and submit one of the questions, I can submit another question within 5 minutes, but not the same question)? I think so, and I'm planning to implement it this way, unless you have something else in mind.

Yes, I agree with you. I actually think it would be fine to have this setting only at the question level. I don't mind having it at the assessment level as well, but I don't actually think it's really that useful.

> * We talked about this, but just to document it: this limit would apply to grading, not to submissions themselves. In other words, students can save at any rate, but can only save and grade based on this rate.

Yes, only limit grading.

> * Would this limit apply on the question level or the variant level? In other words, if I submit for one variant, get it correct, then get another variant, can I submit to the new variant faster than this rate? I'm fine either way for my use-case (the questions I have in mind for this will only present one variant to the students), but I'd guess this should apply to the question.

I think doing it at the question level is fine.

> * The "Grade XX answers" in the Overview should also take this into account. I imagine that a simple warning if there are questions that cannot be graded yet (that these questions won't be graded) should suffice.

Yep, sounds reasonable.

> * When closing an assessment, I imagine the grading that happens on close supersedes this limit, i.e., grading that happens on assessment close can happen even if the submission rate hasn't been fulfilled yet for a question.

Agreed. And any instructor-initiated grading (like regrades) would also supersede this limit.

**Comment by jonatanschroeder** [comment]
@mwest1066 One more question: is `grading_jobs.date` an appropriate choice for the base date to compute when to allow new submissions to be accepted? And in that case do you think it's a good idea to ignore grading_jobs marked as ungradable? This seems to be the criterion for limiting the number of attempts, may be good to keep consistency.

**Comment by mwest1066** [comment]
> @mwest1066 One more question: is `grading_jobs.date` an appropriate choice for the base date to compute when to allow new submissions to be accepted? And in that case do you think it's a good idea to ignore grading_jobs marked as ungradable? This seems to be the criterion for limiting the number of attempts, may be good to keep consistency.

Yep, that date is good. I agree that ungradable submissions shouldn't count.

**Comment by jonatanschroeder** [comment]
If a submission is blocked for a period of time, what happens when the time expires (i.e., the student can submit again)?

1. Nothing: the user needs to refresh manually (or switch to another page and come back) to be able to submit again.
2. Button is disabled, and Javascript enables the Grade button automatically after the precomputed time.
3. Submit button is removed, and after the timer is computed, the web socket used to update the submission view on grading status change is invoked, and the question footer is re-retrieved.

Option 3 is probably the most aesthetically pleasing. It is also best if you consider that other events (e.g., group work, instructor updates, manual grading jobs) could affect timing, but those won't happen often. Sorry @mwest1066  to keep bugging you with these, but any thoughts?

**Comment by mwest1066** [comment]
> Option 3 is probably the most aesthetically pleasing. It is also best if you consider that other events (e.g., group work, instructor updates, manual grading jobs) could affect timing, but those won't happen often. Sorry @mwest1066 to keep bugging you with these, but any thoughts?

I agree that option 3 seems to be the most reliable way to do this.

I have a slight preference for the Save&Grade button to still be there but disabled, with a countdown timer (using `pages/partials/countdown.ejs`, for example). This is all just details, however.

**Comment by mwest1066** [comment]
> Sorry @mwest1066 to keep bugging you with these, but any thoughts?

This is the opposite of bugging! I'm super happy that you are solving these tricky issues and I'm happy to answer questions anytime!
