### ISSUE TITLE
CBTF test reloading with different values

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#120]
From Dave:

I also witnessed at least one TAM 210/211 student who worked out his problems on paper, had to reload or something to get the problems to work, and they came back with different numbers (so his prep was no longer valid). I thought that if a student was issued a question, that question would be sticky, but that didn’t appear so to him with that exam. We reloaded the page a few more times and he got different numbers.
 
Unsure if that’s a quiz configuration deliberate choice, or mistake on the 210 teachers or not….

**Comment by trombonekenny** [comment]
I don't have the netid but I remember the system (the one just left of the desk in the middle-- that you would walk directly to it if you came into the room). Desk 6? 7?

I can't remember when I witnessed it (Friday afternoon?) but I bet we can look at the logs and deduce who in 210/211 was using it.

I think he's also going to bring this up with his instructors.

**Comment by mwest1066** [comment]
Ok, thanks! If it happens again let's try and get all the details (NetID, date/time) so we can easily find it in the logs.

**Comment by mwest1066** [comment]
This has apparently not reoccurred in the last year so I'm closing it.
