### ISSUE TITLE
Reimplement 'PrairieGeom.js' and 'PrairieDraw.js' as Python libraries

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#1204]
These libraries are mainly used by older questions and PD figure drawing, which required them to load client-side. It would be cleaner to re-implement these in Python and keep their usage server-side.

In particular, this would allow PrairieDraw-type figures to be rendered within `server.py` through the `pl-figure` element instead of the `pl-prairiedraw-figure` element and separate drawing script.

Some of the functions implemented in these libraries (particularly PrairieGeom) perform functions that are available from SymPy as well.

**Comment by nwalters512** [comment]
Wouldn't you still need client support for interaction with the drawings? IIRC that's a thing you can do.

**Comment by rbessick5** [comment]
That's a good point -- and it doesn't look like there's a better way to handle interactive elements aside from HTML canvas elements and JS.

Maybe we leave this be for now unless something bad happens with the current library, and encourage folks to think about sympy plots if they don't need interactive figures.

**Comment by trombonekenny** [comment]
@mfsilva22 Do your new elements resolve this?

**Comment by mwest1066** [comment]
Resolved by `pl-drawing` element
