### ISSUE TITLE
File preview UX enhancements

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1208]
When a student uploads a file type we don't recognize, we should make the error message more user friendly. It current looks like:

![image](https://user-images.githubusercontent.com/10765199/43424595-929c38dc-9415-11e8-9bae-e0e308e0f792.png)

If we don't have a more flexible file viewer, maybe also give the student the chance to download to preview their work?

**Comment by eliotwrobson** [comment]
Looks like this was resolved here: https://github.com/PrairieLearn/PrairieLearn/pull/3217

This should be closed.
