### ISSUE TITLE
File questions in exam mode don't automatically detect deltas given the same filename

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#121]
Repro:

Upload $FILE
Hit "Save Answer"
Upload $FILE
Observe that the "Save answer" button is still disabled

**Comment by tnip** [comment]
cf  ```PrairieLearn/pl-cs421/questions/ml3-*/file-upload.js```

**Comment by tnip** [comment]
There's a "hack" on StackOverflow somewhere where if you determine there exist changes to the file's last modified date, you can transparently nullify the upload field, then have it set to be the new file. It also lives in our repo somewhere...

**Comment by mwest1066** [comment]
Fixed with v3 file upload question.
