### ISSUE TITLE
Fix alignment on pl-checkbox and friends

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1215]
When multiple choice questions have very tall options, the placement of the checkboxes looks potentially confusing. We should consider adding custom styles to make this use case look better.

<img width="609" alt="screen shot 2018-08-19 at 7 02 00 pm" src="https://user-images.githubusercontent.com/1476544/44316773-770bd280-a3e2-11e8-84d6-f9468e143523.png">

**Comment by mwest1066** [comment]
Yeah, that's horrible. But what should we do about it?

**Comment by tbretl** [comment]
If you are willing to wait a couple weeks, I'd be happy to address this problem.

**Comment by mwest1066** [comment]
Very willing! I've assigned this issue to you :-)

**Comment by nicknytko** [comment]
Are you looking for something like this, with the checkboxes aligned to the choice labels?
<img width="372" alt="Screen Shot 2019-09-04 at 4 19 58 PM" src="https://user-images.githubusercontent.com/1790491/64292785-c1e68280-cf30-11e9-9b92-a48c02dae31a.png">

**Comment by mfsilva22** [comment]
This looks so much better! Yes, I would like that :-)

Would this work as well with `pl-code`?

**Comment by nwalters512** [comment]
I was working on a more ambitious rewrite on the `new-multiple-choice-style` branch:

<img width="805" alt="Screen Shot 2019-09-04 at 6 08 43 PM" src="https://user-images.githubusercontent.com/1476544/64303887-155fcd00-cf3f-11e9-9559-f4a2653a6b27.png">

I think it's in a pretty good place, we just have to consider if we want the inline variant to change, and also make similar changes `pl-checkbox`. Feedback welcome!

**Comment by nicknytko** [comment]
That's looking good so far!  I didn't realise this was being actively
worked on.

**Comment by coatless** [comment]
Just documenting a few things from discussion on Slack.

--- 

**Goal:** Allow for block-level elements in answer content. 

**Requirements:**

- Use standard browser UI elements
- Retain labels

Standard UI elements provide familiarity with input fields found throughout the web. Moving to a style shown above adds a training requirement. 

Labels help when comparing the question, the true answer, and potentially several submissions. 

--- 

Under the above conditions, the design is not viable as it removes the standard input from being selected. That said, the process might be interesting and Slack messages disappear after less than a month nowadays.

Initially started out by porting the MC style to checkboxes with:

![Initial port of multiple choice style to checkboxes with greyed styling](https://user-images.githubusercontent.com/833642/67026713-f459d280-f0cd-11e9-9930-529fbbc5d0af.png)

Switched to greying the check marks. 

![Grey check marks](https://user-images.githubusercontent.com/833642/67026712-f459d280-f0cd-11e9-95ca-31a1390d913f.png)

Before opting for a check showing in hover state.

![Show checkbox in hover state](https://user-images.githubusercontent.com/833642/67026710-f459d280-f0cd-11e9-9577-ace0d500e8d3.png)

Experiments with labels:

![Two column labels](https://user-images.githubusercontent.com/833642/67026707-f459d280-f0cd-11e9-8974-c4f9e6637de1.png)

![Single column labeling](https://user-images.githubusercontent.com/833642/67026704-f459d280-f0cd-11e9-9a7a-f077169bbb84.png)

**Comment by mwest1066** [comment]
Our eventual decision here was to retain the standard HTML styling (native browser styles) for checkboxes and radios. However, fixing the vertical alignment as @nicknytko showed above would be fantastic, to make it clear which checkbox goes with which answer.
