### ISSUE TITLE
Incorrect Row Count

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1221]
Frequently my attempts to link directly to assessments on PL produce results like this for students:

![image](https://user-images.githubusercontent.com/445443/44682582-68887100-aa09-11e8-877a-e7a28b5bf499.png)

I have a hard time reproducing this problem (the links work for me, that's why I send them in the first place). But it seems to be caused by either:

1. accidentally providing an instructor link to a student, or
1. cases where the student isn't yet signed up for the class on PL

In both cases it would be helpful if a more useful error message was displayed. In the first case it seems like a simple redirect to the student version of the assessment would be possible, and in the second perhaps a redirect to a page where they can sign up for the course.

**Comment by trombonekenny** [comment]
Based on the ErrorID gwa screen-shotted, it's this error that needs some cleaning up.

https://github.com/PrairieLearn/PrairieLearn/blob/9af6519d13c785f177d3b817edd8098504db490d/middlewares/selectAndAuthzAssessmentInstance.js#L17
