### ISSUE TITLE
Add obfuscation to pl-code element

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1224]
In 225, we convert all source code in questions into images with the goal of preventing copy-paste to just run the code during exams. It's of questionable utility in the first place (anyone with a decent WPM can just retype the code in under a minute), but assuming this is a desirable property sometimes, we should add optional similar protections to the `<pl-code>` element. I'm thinking something as simple as disabling right-click and preventing text selection will be enough for most people. This doesn't prevent people from just viewing the source, of course, but I'm guessing that's ok.

Open to suggestions for attribute names. `obfuscate="true"`? This should definitely default to false.

**Comment by mfsilva22** [comment]
We do the same in CS 357 (convert to images)! I think will be a great feature added to `pl-code`. I think the suggested attribute name is fine.

**Comment by trombonekenny** [comment]
obfuscate could mean a lot of things in a coding context, I would avoid it.

prevent-copying?

**Comment by nwalters512** [comment]
I like it.
