### ISSUE TITLE
iOS curly quotation marks not supported

### ISSUE THREAD

**Issue by josh-byster** [PrairieLearn/PrairieLearn#1225]
This may not be an issue depending on implementation, but I just wanted to give a heads up that with smart quotations in iOS 11 and higher, one cannot type the single quote character `'` with their keyboard. without having special preferences enabled. This becomes an issue with, for example, CS233 homework when done on mobile since the single quote character is required in some of the submissions.

**Comment by josh-byster** [comment]
Ah, thanks Nathan. I suppose I was making the suggestion that it might be able to accept that unicode value as a single-quote character and double quote respectively.

**Comment by nwalters512** [comment]
I guess I should have asked a few more questions - do things fail on submission or on grading? Can you send me a reference to a question that doesn't work?

**Comment by nwalters512** [comment]
Followed up with Josh offline - this is for questions that require inputs like `(x'y)'`. This is specific to 233's parser and PL can't really do anything here.
