### ISSUE TITLE
Support multiple courses in local docker

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1230]
Requested by @egunter and @rwiltfon. We should allow more courses to be mounted locally on `/course2`, `/course3`, etc.

**Comment by trombonekenny** [comment]
Bump from PL office hours this summer

**Comment by nwalters512** [comment]
In the meantime, a workaround for this is to mount a custom `config.json` to the docker image with additional paths.

**Comment by trombonekenny** [comment]
Do you see any problem with adding `/course2`, `/course3` to the docker'd `config.json`? Then the course staff can either mount other courses into those paths and not also have to do a `config.json` If those paths are empty, the sync might report that but it shouldn't error?

**Comment by mwest1066** [comment]
That seems like a great idea. It would be worth checking that sync will do the right thing, but that would be an easy fix to make it ignore empty `/courseN` dirs if it doesn’t already ignore them.

**Comment by nwalters512** [comment]
Yep, that's the correct fix here. Syncing will happily ignore any directories. The suggestion was just for if they needed to be able to multiple courses this very minute 😛

**Comment by mwest1066** [comment]
Fixed by #2197
