### ISSUE TITLE
self-closing PrarieLearn elements in the new renderer

### ISSUE THREAD

**Issue by egunter** [PrairieLearn/PrairieLearn#1244]
There is a gap / inconsistency in the description of how self-closing PrairieLearn elements will be handled in the documentation going forward with new renderer compared with the examples in the description of how to write a question.html file.  In the question.html file description examples, self-closing pl-elements , e.g. <pl-number-input answers_name="F" comparison="sigfig" digits="2" />, are used, and yet further down the page it seems to indicate that no self-closing PrairieLearn elements will be allowed by the new renderer.  It would be helpful if all examples given were compliant with the new renderer, and if some self-closing PrairieLearn elements are in fact allowed, the wording changed to reflect that, and a list or tagging of allowed self-closing PrairieLearn elements were added to the HTML Element list page.

**Comment by nwalters512** [comment]
The new renderer is still opt-in, so I didn't feel the need to update the examples yet. I'll keep this around to remind me to update the examples before we switch the new renderer on by default.

**Comment by mwest1066** [comment]
We should address this as part of #1492
