### ISSUE TITLE
Git Sync No Output

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1254]
Frequently recently when I try to Git sync I end up at this screen:

![image](https://user-images.githubusercontent.com/445443/45597621-bd7a3000-b994-11e8-87ab-283362e25b5b.png)

(Note that I just did this now, which I assume is not a period of heavy load...)

Note that the sync seems to complete fine—it's just that no output is displayed.

**Comment by nwalters512** [comment]
Looks like a broken websocket, as the output is there, it just didn't show up live. Can you check the console for errors next time this happens to you?

**Comment by gchallen** [comment]
Sure.

**Comment by nwalters512** [comment]
@gchallen has this happened to you recently? haven't had any other reports of this, so if it's not happening anymore, I'll close this out.

**Comment by tbretl** [comment]
@nwalters512 yeah, it happens to me all the time - I’ve just ignored it

**Comment by mwest1066** [comment]
Asking around informally, it seems that no one has seen this bug occur for a long time. I'm going to assume it was some random websocket issue and close this issue. Please let me know if anyone is still seeing this problem.
