### ISSUE TITLE
Handle netid changes better

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1257]
Currently if someone uses PL or PS and then has their NetID changed, subsequent logins fail with a `duplicate key value violates unique constraint "users_uin_key"`

As long as there's a UIN and it matches an existing row with the shibboleth provider, we should allow the `users_select_or_insert` function to update the `uid`.

**Comment by mwest1066** [comment]
Agreed!

**Comment by trombonekenny** [comment]
Bump.

**Comment by mwest1066** [comment]
Resolved by #1476
