### ISSUE TITLE
Course instance deletion not propagating to assessments?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1259]
https://cbtf.engr.illinois.edu/sched/course/122/home is James' course and is PL linked. When it date range searches allowAccess rules across all the course instances, it finds an 'exam 1' at https://prairielearn.engr.illinois.edu/pl/course_instance/8396/instructor/assessment/172847/

That assessment is unavailable because it's from a course instance that's no longer available. But whatever action deleted that course instance didn't propagate the delete down to the assessments.

**Comment by mwest1066** [comment]
We deliberately don't delete assessments when someone (soft-)deletes a courseInstance. This allows instructors to recover from accidentally deleting a courseInstance by just putting it back again.

To fix the query, I suggest JOINing on `course_instances AS ci` and adding a `WHERE ci.deleted_at IS NULL`. Would that do what we need?

**Comment by trombonekenny** [comment]
This has been resolved in PrairieSchedule. Thanks for the pointer.
