### ISSUE TITLE
pl-string-input Content Hardcoded to "string"

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1276]
This is a bit confusing. Starting the input blank would probably be a better choice.

![image](https://user-images.githubusercontent.com/445443/45908769-cec3a200-bdc3-11e8-9900-2a06848fed90.png)

**Comment by nwalters512** [comment]
I'm ok with this - maybe we can add an attribute to set the placeholder text too?

**Comment by mwest1066** [comment]
I agree that we should probably default to blank for this particular element, given that there is really no format that the answer has to have. An option to set the placeholder text would also be great!

**Comment by mfsilva22** [comment]
I can submit the PR. Suggestions for the attribute name?

**Comment by trombonekenny** [comment]
placeholder ref: https://www.w3schools.com/TAGS/att_input_placeholder.asp

**Comment by mwest1066** [comment]
Fixed by #1277
