### ISSUE TITLE
Allow Cut and Paste In Instructor Mode

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1279]
I believe that PL has cut and paste disabled from code blocks by default. (If I'm doing this let me know.) This is great in exam mode, but a bit of a PITA in non-exam mode. For example, frequently I'd like to be able C&P from code when responding to issues that students have raised.

Is there any way to just enable this when a student is actually taking an exam, and disable it otherwise?

**Comment by nwalters512** [comment]
This appears to be a feature of your course: https://github.com/PrairieLearn/pl-cs125/blob/8d46fdcd9697c44cb107b4ed00f6b779ce76f5fd/lib/skipcode.js#L18

If you use the `pl-code` element, you can use the `prevent-attribute` attribute to control this behavior. We don't have a way to change the behavior of elements if they're in exam mode or not.
