### ISSUE TITLE
Add one-way remote logging in production with rsyslog or similar.

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#128]

**Comment by mwest1066** [comment]
This was just a reminder to set up something similar to what we have now with CW logs (exporting logs from potentially-ephemeral systems to a centralized permanent log repository). If we think we need more of this we should open a new issue in our internal dev-ops tracker.

**Comment by nwalters512** [comment]
We already have some other internal issues tracking improvements to logging; I'll close this!
