### ISSUE TITLE
pl-string-input: remove-spaces on by default

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1288]
After a support case with CHEM 104 not grading correctly a `pl-string-input` because students put an accidental space at the end of the text, I propose the following changes:

- We make remove-spaces `true` by default. If someone needs blank spaces on the perimeter of the string, they can enable it but I think the much more common case is the other way around.
- Include in the input help popup bubble a blurb about this config and its status. i.e. `Leading and trailing spaces will be allowed.`
- Could we do some `<span>` highlighting in the submission and correct answer displays of the element that would better show the trailing white space?
- Maybe clean up the rest of the student facing interface for this to something kinder to the CS layperson than String? Use the word text instead? I'm not suggesting we need to change the element name, but just how it's referenced in the student UI.

**Comment by mfsilva22** [comment]
Regarding this comment: "Could we do some <span> highlighting in the submission and correct answer displays of the element that would better show the trailing white space?"

I am assuming that we would give this feedback when `remove-leading-trailing=false` correct? So if the user submits with trailing or leading spaces (when they are not supposed to be there), we would highlight them in the submitted answer? Should this be an additional attribute? 

We used this highlighting idea for the `pl-component-matrix-input` to help students identifying invalid answers, but in this case here, the question is actually marked as incorrect.
