### ISSUE TITLE
Watch wire traffic to ensure sensitive data is not sent to students

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#129]

**Comment by tnip** [comment]
I suspect we should define "sensitive data" here, as I've been abusing the open endpoints to get a few features to work. :)

**Comment by mwest1066** [comment]
Care to elaborate? :-) I don't want to break something you are using!

**Comment by tnip** [comment]
I abuse the submission endpoint (which I suppose needs to be public) and the qInstances endpoint (which I suppose also needs to be public) I believe, to get "Skip Extra Credit" working.

**Comment by mwest1066** [comment]
What is this "skip extra credit"? Is it in pl-cs421 somewhere?

**Comment by mwest1066** [comment]
Largely eliminated by the move to server-side rendering with PLv2.
