### ISSUE TITLE
Request for "do not grade this element" feature

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#1291]
For a couple research studies, I'd like to have a consent form where people can choose between "I agree to participate" and "I do not agree to participate" and then also have a text box to enter their name.
Of course, it would probably be better if the element was more flexible and allowed for more or fewer inputs.

Here's an example of what I'd like to be able to have, except that it would not be graded and that the multiple-choice would display both "true" answers.
<pl-multiple-choice answers-name="consent" weight="0" fixed-order="true" number-answers="2">
 <pl-answer correct="true">I agree to participate in this study</pl-answer>
 <pl-answer correct="true">I do not agree to participate in this study</pl-answer>
</pl-multiple-choice>

<pl-string-input answers_name="name" allow-blank="true" weight = "1"></pl-string-input>

**Comment by coatless** [comment]
Ditto. Would be great to have for:

- I [ ] like [ ] dislike the exams in this style
- In general, the exam questions are [ ] too hard [ ] too easy [ ] just right
- I [ ] have plenty of time [ ] have just enough time [ ] do not have enough time to
finish the exam questions.

**Comment by coatless** [comment]
@gchallen as you 👍 the question. @glherman shared his method via Slack. 

In short, configure the question like a normal PL question, just setup **server.py** with:

```py
def grade(data):

	data["score"] = 1
```

He adds in an **answer.html** with:

```html
<p>Thank you for your response!</p>
```

I think this helps differentiate the question.

**Comment by eliotwrobson** [comment]
Should this be closed? The PR with the example question was closed without merging, so it seems like the example isn't needed?

**Comment by coatless** [comment]
PRs were closed out as they sat inactive despite bumps. So, the issue could
be closed.

If anything, there is an example that can be found by searching do not
grade or survey question.

**Comment by eliotwrobson** [comment]
Well it's easy enough to resubmit a PR if it's something people might find helpful. I can bundle this with another example question I wanted to make.

**Comment by eliotwrobson** [comment]
@coatless @glherman I've reopened and rebased the original PR resolving this (https://github.com/PrairieLearn/PrairieLearn/pull/1867). It would be great if you could take a look, then we can merge and resolve this issue, since I think having an example like this is probably better than making an all-purpose survey element.
