### ISSUE TITLE
frequent BLOCKED-AT messages

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1301]
We seem to be getting frequent “BLOCKED-AT” messages referencing `/PrairieLearn/node_modules/csv-stringify/lib/index.js:56:21`

Maybe we should use a different CSV library that releases control back to the event loop during CSV creation?

**Comment by mwest1066** [comment]
Should be fixed by #1364 — should check logs after that is deployed

**Comment by nwalters512** [comment]
I don't think this has been a problem for us recently, going to close this. @mwest1066 feel free to reopen if you think this is still relevant!
