### ISSUE TITLE
Add UIN to Gradebook

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1304]
Having the UIN in the PL gradebook would make it much easier to interface with other tools. For example, Banner grade uploads are keyed on UIN, not NetID, so this requires another level of mapping if the UIN isn't provided.

Craig had claimed that the CBTF has access to this information via AD somehow. It doesn't seem to be accessible to me...

**Comment by trombonekenny** [comment]
Bump from a conversation with Elsa on this summer.

**Comment by trombonekenny** [comment]
Bruce is asking about getting this information for ESPL test results as well.
