### ISSUE TITLE
parse unicode minus in pl-symbolic-input (and other elements)

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#1319]
A while ago we modified `pl-matrix-input` and `pl-number-input` to replace unicode minus with hyphen minus wherever it occurs in a raw submitted answer. We should do the same for `pl-symbolic-input` and other elements, as appropriate.
```
# Replace unicode minus with hyphen minus wherever it occurs
a_sub = a_sub.replace(u'\u2212', '-')
```

**Comment by nicknytko** [comment]
This looks like only `pl-symbolic-input` needs to be updated here, other elements are calling `pl.string_to_number()` and `pl.string_to_integer()` which will handle unicode minus.
