### ISSUE TITLE
Access rule for closed exams

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1346]
Elsa just mentioned a case where they open up exams after they finish in the CBTF with credit:0% and mode:public so students can see their answers (and try the questions again). That runs into trouble when a student hasn't already taken the exam and then can see it outside of the testing center.

Could we have an allowAccess rule that only applies if the assessment instance is closed? Would that be appropriate in this case?

**Comment by mwest1066** [comment]
See #863 for a similar request

**Comment by mwest1066** [comment]
Also see #1451 for another very similar request (and possible solution).

**Comment by mwest1066** [comment]
Implemented in #3993
