### ISSUE TITLE
Number parsing fails with unicode-minus for negative numbers

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#135]
The calculator app on EWS Linux machines copies negative numbers with a unicode-minus U+2212 rather than the regular hyphen-minus U-002D. This breaks JavaScript's `Number()` conversion from string.

**Comment by trombonekenny** [comment]
@tbretl We should make sure this copy/paste from the calculator on EWS Linux (CBTF) is parsed properly in the new v3 inputs.

**Comment by mwest1066** [comment]
Yes, if @tbretl can resolve this super-long-standing issue then that would be so awesome!

**Comment by tbretl** [comment]
This should be easy. Is there a deadline?

**Comment by mwest1066** [comment]
Sep 20 is when the BioE 201 exam goes live.

**Comment by tbretl** [comment]
Just put in PR to support unicode minus in `pl_number_input` and `pl_matrix_input`. Do we also need support for unicode minus in v2?

**Comment by mwest1066** [comment]
We don't need to fix v2 questions, I think. Everyone with existing questions has already dealt with this issue in one way or another, and all new users should be using v3.
