### ISSUE TITLE
ExampleCourse GitHub links are still broken in production

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1358]
Looks like #1338 didn't actually fix things in prod, because `res.locals.course.repository` is not NULL for `exampleCourse` at https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorQuestion/instructorQuestion.js#L174

Instead I think we should reverse the order of the `if` and `else if` to first check whether we have `exampleCourse`?

**Comment by trombonekenny** [comment]
I removed the `pl_courses.repository` for XC 101 in production. That should also fix the problem, but it needs a PL restart to go into effect?

We don't use sync on the exampleCourse anyway, and the repository field was set to the pl-XXX.git default. If you look at the sync logs for the production example course, it seems to get its git history from /PrairieLearn :)

**Comment by mwest1066** [comment]
Works for me. Doesn't need a restart -- it's working right now.
