### ISSUE TITLE
Add client-side validation of numeric inputs

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#136]
This would deal with #135

**Comment by trombonekenny** [comment]
Fixed in v3?

**Comment by mwest1066** [comment]
Not yet. Current `<pl_number_input>` does server-side validation, which is 90% of the functionality, but it would still be nice to add something client-side (especially to warn about insufficient precision).

**Comment by mwest1066** [comment]
Fixed in `<pl-number-input>`, but still needs to be added to other elements: see #1319
