### ISSUE TITLE
convert numpy integer types to/from json properly

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#1366]
If I do this in `server.py`:
`data['params']['a'] = np.int64(5)`

Then I see this error:
TypeError: Object of type 'int64' is not JSON serializable

This is because `json.dumps` can't handle numpy integer types. Either create a custom serializer or modify `pl.to_json` and `pl.from_json` to handle these types.

**Comment by nicknytko** [comment]
Is it really important to keep the distinction that it is a numpy type here?  It wouldn't be difficult to add another case to the `pl.to_json()` and `pl.from_json()` methods but I'm wondering if it would be okay to just discretely convert to the base types?  My thoughts are that most people would just want to store _an_ integer or _a_ floating point number and using the conversion methods is an extra annoyance, but I might be totally wrong here.

**Comment by eliotwrobson** [comment]
To do the conversion mentioned in the original issue, all that's needed is to convert the numpy integer to a python `int` and then back. For more complex conversions (i.e. json serializing an entire array), there's a dependency that can be added: https://github.com/mverleg/pyjson_tricks
