### ISSUE TITLE
Option to Disable MathJax

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1367]
Please provide an option to disable MathJax. It goes after random bits of the page and formats them horribly. You never know when it will strike.

It even jumps on stuff on the issues page!

![image](https://user-images.githubusercontent.com/445443/48234985-85cea980-e381-11e8-8419-5126e85e5490.png)

Please get MathJax under control! 😄

**Comment by KritR** [comment]
You can disable MathJax already by using the "tex2jax_ignore" class in a div surrounding your content.
```
<div class="tex2jax_ignore">
   <p> Given two numbers $a = {{params.a}}$ and $b = {{params.b}}$.</p>
  <p> What is the sum $c = a + b$?</p>
</div>
```
will result in no MathJax evaluation within that block.
More details can be found http://docs.mathjax.org/en/latest/options/preprocessors/tex2jax.html.

**Comment by mwest1066** [comment]
Closing this, as MathJax apparently already provides the requested functionality.
