### ISSUE TITLE
Sync code buffer with localStorage and rehydrate on load

### ISSUE THREAD

**Issue by pranaygp** [PrairieLearn/PrairieLearn#1371]
navigating to another page causes me to lose my work. by autosaving and rehydrating, I can always come back to the page and still have my code

As per a discussion with @nwalters512

**Comment by gchallen** [comment]
Will this fix the problem with student work being lost when they are logged out due to inactivity? Another option seems to be to just do a manual save before the logout happens.

**Comment by pranaygp** [comment]
@gchallen would we want to clear localStorage on logout? Or perhaps it doesn't matter, and then yes, we could solve that issue 😀

**Comment by gchallen** [comment]
You'd probably need to clear localStorage on logout for shared machines, although I'm not hugely familiar with this interface. (Is it encrypted somehow? Would it be possible for students to harvest submissions from old sessions on shared machines?)

**Comment by nwalters512** [comment]
Are there any machines on campus where students share user accounts? That's indeed something we should try to design for - simple encryption based on variant ID + UIN + ??? might be a good idea.

**Comment by pranaygp** [comment]
That'd be a bit overkill. @nwalters512 why not just trigger a remote save (i.e. the Save button) on logout and then clear localStorage. Logging back in should restore from the server, but while you have a session and are opening/closing tabs, code in the buffer is always stored and rehydrated offline :)

**Comment by trombonekenny** [comment]
I worry about automatic saving or anything that changes a submission without the user knowing it.

What about just implementing warnings when navigating away and see if the simple fix is enough? #506 and #1132 

If there is a session timeout, that seems like a logical place to put into local storage, refresh into a logged in session, and replace it?

**Comment by mwest1066** [comment]
Yeah, I’m much more enthusiastic about detecting unsaved changes and popping up a modal. That’s pretty easy to do in a centralized way for all questions (v3 at least). We’ll extend the session timeout stuff in any case.

**Comment by MatthewScholefield** [comment]
There's been many times where I've worked on a homework problem only to hit submit and be greeted by the login screen, losing whatever I had been working on. In fact, now it has become muscle memory to hit `ctrl+a`, `ctrl+c` before submitting. It'd be really nice to get an improvement around this eventually.

**Comment by mwest1066** [comment]
@MatthewScholefield any interest in implementing this? PrairieLearn will be at HackIllinois again this year, or we'd certainly be happy to work with you directly. We have office hours Tuesdays 11-1 in Siebel 2124 if you want to stop by.

**Comment by trombonekenny** [comment]
This was worked on by a student Friday night at the hackathon, but I don't know the current state.

**Comment by MatthewScholefield** [comment]
I've been busy, but I'll try and submit a PR in a day or two.

**Comment by mwest1066** [comment]
Also see #2268 as another strategy to mitigate this problem.

**Comment by nwalters512** [comment]
As of #2621, we now extend the cookie expiration date regularly, so students should essentially never hit the case where they're forced to re-authenticate while working on an assignment. We've also implemented warnings on unsaved changes, which should cover the case of someone losing their work be navigating to another page or closing the tab.

**Comment by jonatanschroeder** [comment]
Just to leave a note (in case this comes up in a search): there is still the case where students are unable to save due to time limit or network connectivity, but that is covered by another issue: #3358.
