### ISSUE TITLE
infoCourseInstance.json: add ps_linked

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1373]
`course_instances.ps_linked` boolean exists in the database and is used for exam mode checking against PrairieSchedule. Let's make that configurable via the infoCourseInstance.json file.

**Comment by trombonekenny** [comment]
Bump again for SP19.

**Comment by mwest1066** [comment]
@trombonekenny is this still needed with the new UUID linking?

**Comment by mwest1066** [comment]
bumping for @trombonekenny — I think we don’t need this anymore with UUID linking

**Comment by trombonekenny** [comment]
I use this flag with the ZJUI courses because they use exam mode but not PS checking. I guess it depends how we deprecate the PS linking which would determine if we need this db column anymore.

The issue was to make that field configurable in the JSON files so that we can easier document to the ZJUI courses what they need to set. Better than the current "setup your courseInstance, sync, and then tell me so I can fiddle something behind the scenes to make the exams work"

**Comment by trombonekenny** [comment]
Another bump for Fall 2020. We should figure out how to not have to toggle `ps_linked` for the non-CBTF mode:Exam exams.

**Comment by mwest1066** [comment]
I think we can just delete this entire ELSE block: https://github.com/PrairieLearn/PrairieLearn/blob/180124d964913d64bd9c6c3df6d2b9a00c8b2f30/sprocs/check_assessment_access_rule.sql#L91

And then also delete the `ps_linked` column.

All the Illinois exams are using `exam_uuid` so they don't use the ELSE block above anyway. And the ZJUI courses don't have `ps_linked` set, so we should be fine with the above deletions.

Alternatively, we could leave the above code in place and just set `ps_linked = NULL` and `pl_course_id = NULL` everywhere, which should also just work?

**Comment by trombonekenny** [comment]
I agree it's probably much easier to rip things out than understand all of the specific edge cases that grew in over the years. CBTF has switched entirely to examUuid linking so anything else it used can go away. I always need to go back to the unit tests when it comes to this sproc to make sure the default cases work as we expect.

**Comment by mwest1066** [comment]
I think on the PL side it's fine to just rip this all out. I grepped in PS and there are a number of hits for `pl_course_id`. It wasn't immediately clear to me whether things would continue to work if we just set `pl_course_id = NULL` everywhere (or delete this column)?

**Comment by trombonekenny** [comment]
Bump for Spring 2022

**Comment by trombonekenny** [comment]
Bump for Fall 2022

**Comment by trombonekenny** [comment]
In the same PR I'll likely take out the PraireScheduler checking and just focus on PrairieTest (for simplicity). This also means updating the tests to mimic PT since they currently only do PS.

**Comment by mwest1066** [comment]
This sounds correct to me. Thinking through the current users, this should take care of all the cases. And it will be much cleaner!

**Comment by trombonekenny** [comment]
It means it will run this query for each mode:Exam check:

```sql
        SELECT x.uuid
        INTO exam_uuid
        FROM
            pt_reservations AS r
            JOIN pt_enrollments AS e ON (e.id = r.enrollment_id)
            JOIN pt_exams AS x ON (x.id = r.exam_id)
        WHERE
            (date BETWEEN r.access_start AND r.access_end)
            AND e.user_id = check_assessment_access_rule.user_id;
```

I assume that's not going to be a problem at scale?

**Comment by trombonekenny** [comment]
Tests refactored to look like:

![image](https://user-images.githubusercontent.com/10765199/203629001-d20a7d2a-5d95-49d3-bd3f-d428bbb89fa3.png)

**Comment by nwalters512** [comment]
@trombonekenny can we close this now? I reread the comments and I'm not sure if there's anything else actionable for us here.
