### ISSUE TITLE
home.sql: c.short_name does not exist

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1385]
If you load the PL homepage with an empty database (nothing in `pl_courses`) the query in home.sql errors with a `column c.short_name does not exist`

The jsonb_build_object calls should be more defensive against an empty database.

Or we should bootstrap the database differently so it doesn't start empty?

**Comment by mwest1066** [comment]
Fixed in PrairieSchedule 9fc1f75f1b201054cbe698b4d3cfaca2c4f0e6e5.
