### ISSUE TITLE
Does PL support any other way of creating quiz-style questions other than importing hard-code html?

### ISSUE THREAD

**Issue by Pezhin** [PrairieLearn/PrairieLearn#1412]
As title says, I am wondering if there is a better way of creating quizzes, e.g., directly type in fields and question pages are generated automatically. 

If this is not supported, is this in the road-map or are there any specific reasons not to have those kinds of functionalities?

I am interesting in contributing and think to figure out questions above before proceeding

**Comment by nwalters512** [comment]
It's certainly possible to build abstractions on top of PL. For instance, CS 225 generated all of our questions from Markdown files with custom scripts. There's always a trade-off to be made between flexibility and simplicity, and so far PL has erred firmly on the side of flexibility.

We're certainly open to potential improvements to the question authoring experience, but at it's core, questions will likely always be represented by files on disk in a repository. In general, we've seen that the flexibility offered by this is worth the small tradeoff in having to potentially author questions in raw HTML-like syntax.

**Comment by mwest1066** [comment]
The other thing we are working towards here (see #1344) is to allow the HTML to be edited within the browser. Once this is done, it would also be easy to add in-browser editing of questions as Markdown or ASCIIDoc or any other format.

@Pezhin if you are interested in working on any of this then let me know. We’d love to have more people join the team and contribute to PL development!

**Comment by Pezhin** [comment]
Thanks @nwalters512 and @mwest1066. I think a toolkit GUI page for building questions directly could help instructors with non-tech background to use the system, also save users from learning the correct pl-html syntax and etc. 

I think #1344 should help. 

I plan (not sure if it really going to happen, xD) to build some abstraction pages for myself to generate questions that ease the pain. If it is stable enough, I can share it (maybe, in the help channel on slack) for anyone who wants to use it and you guys can decide if it is needed to be integrated in PL or not.

I am closing this issue as I got the answer I was looking for.
