### ISSUE TITLE
docker API communication via TCP

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1419]
For local PL development with external graders, can we convert to TCP communication for the docker API between PL and host? This would remove the need to volume mount the host docker socket, which would let us support Windows environment for external grading development.

**Comment by echuber2** [comment]
Would this have issues on systems running a software firewall?

**Comment by mwest1066** [comment]
Turns out that mounting the socket works fine under Windows, so not change is needed.
