### ISSUE TITLE
Assessment dates are missing in student view

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1443]
The student assessment page has empty access dates for all assessments.

**Comment by mwest1066** [comment]
Looks like the regression was introduced in 0174bdca5c92475bfe8cd82ad676241aa6596ed5 (PR #1440).

**Comment by mwest1066** [comment]
It's the upgrade of Bootstrap from 4.2.1 to 4.3.1.

**Comment by nwalters512** [comment]
Oof, what changed here?

**Comment by mwest1066** [comment]
https://github.com/twbs/bootstrap/commit/7bc4d2e0bc65151b6f60dccad50c9c8f50252bd6

This is how they fixed the CVE. They added a `sanitize` option to popovers to strip stuff out of the HTML. It seems you can't turn sanitizing off from HTML, only from JS: https://getbootstrap.com/docs/4.3/components/popovers/#options

**Comment by mwest1066** [comment]
Looks like `<table>` is not whitelisted by default: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tools/sanitizer.js#L21

This causes problems for https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/partials/studentAccessRulesPopover.ejs

**Comment by mwest1066** [comment]
Fixed in #1444 and #1446
