### ISSUE TITLE
allowAccess: create_instance toggle

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1451]
For review sessions, setting examUuid and credit: 0% in the allowAccess config gives the student access to the exam. 

If they somehow take the review session before they actually take the exam, we should have a way to enforce that review sessions can only view existing assessment instances and not create new ones.

**Comment by mwest1066** [comment]
Perhaps we could handle this automatically by having PL pull the flag from PS that says this exam is a review session, and then disallowing instance creation in this case?

Although I agree that having an explicit allowAccess flag like this would also be helpful for cases when people want to open up an exam for students to publicly review, but not to create new instances. So I guess we want both? 😄

**Comment by mwest1066** [comment]
This would also allow instructors to show students that an assessment exists before it is available. For online exams, students could see the future time at which the exam was scheduled for them.

**Comment by trombonekenny** [comment]
Could we bring this functionality and the `showClosedAssessment` config into one place? Like some sort of studentActions array that defaults to all of them but can specified in per-user or per-time access control rules?

"studentActions": ["start", "view_open", "save", "grade", "close", "view_closed"]

Are there other states that would be worth configuring?

**Comment by mwest1066** [comment]
This is appealing. I guess `view_total_score` is one more.

**Comment by mwest1066** [comment]
This has been implemented with the `"active"` access rule in #3993
