### ISSUE TITLE
R matrix representation

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1460]
Once #1453 is merged. 

The _R_ implementation for exporting a matrix would require the modification of [`string_from_2darray()`](https://github.com/PrairieLearn/PrairieLearn/blob/eca00c02848560d1aff19f1c5f4ae7311c833a3a/question-servers/freeformPythonLib/prairielearn.py#L326-L379) to create a string in the form of:

```
X = matrix(c(data1, data2), nrow = , ncol = )) # matrix
```

## Extension possibilities

Note: `array2string` print prefix/suffix doesn't override `[]`.
c.f. https://github.com/numpy/numpy/issues/11142

### Joining

```py
import numpy as np

# Sample data
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

#  Dump to comma separated list
y_star = ','.join(','.join('%0.3f' %a for a in y) for y in x)
                                  # ^^^ formatting.

# Convert to R format
r_variant = 'matrix(c(' + y_star + '))'

# Display variant
print(r_variant)
# matrix(c(1.000,2.000,3.000,4.000,5.000,6.000))
```

### Regular expression route

```py
import numpy as np
import re

# Sample data
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

# Array conversion
y = np.array2string(x, precision=2, separator=',')

# Remove brackets with regular expressions
y_star = re.sub('[\[\]]', '', y) 

# Modify with R syntax
r_variant = "matrix(c(" + y_star + "))")

# Display
print(r_variant)
# matrix(c(1,2,3, 4,5,6))
```

### Misc

Subset index trick, e.g. `y[1:-1]` would breaks for a 2D array... 

```py
# matrix(c([1,2,3],
# [4,5,6]))
 #^        ^ :'(
```

**Comment by coatless** [comment]
companion to https://github.com/PrairieLearn/PrairieLearn/issues/1365

**Comment by mwest1066** [comment]
#1453 and #1365 are now both implemented/resolved, in case anyone wants to revisit this issue again
