### ISSUE TITLE
Correct answer is still showing for `pl-checkbox` when `hide-answer-panel="true"`

### ISSUE THREAD

**Issue by eliving2** [PrairieLearn/PrairieLearn#1461]
The correct answer is hidden when partial credit is enabled, however, it should be hidden whenever `hide-answer-panel="true"`

**Comment by eliving2** [comment]
Set to True:
<img src="https://user-images.githubusercontent.com/35576120/54241737-00eeca80-44f0-11e9-8896-33302256c670.png" width="700" height="400">

Still works with partial credit enable:
<img src="https://user-images.githubusercontent.com/35576120/54241843-56c37280-44f0-11e9-9437-aebd1cafd090.png" width="700" height="400">

**Comment by eliving2** [comment]
To clarify, the correct answer is still not shown in the "correct answer panel".

The issue with this element is the icons that show which checkbox is correct will still render.

**Comment by mfsilva22** [comment]
Here is what I know about this feature:

1) `hide-answer-panel` was implemented only to hide the answer panel. So it is technically not a bug, but what it was decided to be implemented at the time.

2) The display or not of the feedback icons is currently controlled by `show_answer_feedback` which is not set as an attribute of `pl-checkbox`. Instead, at this time, this attribute is only set to `true` when `partial_credit=true`.

To address this issue request, we could:

a) make the `hide-answer-panel` hide the answer panel and the feedback icons

or 

b) make `show_answer_feedback` be an attribute

(i am sure there are other options as well)

I can work on this once we can converge to one solution :-)

**Comment by echuber2** [comment]
Is there an update to this?

**Comment by mwest1066** [comment]
I think we should go with option (a) from Mariana. That is, make the `hide-answer-panel` attribute hide the answer panel and the feedback icons.

I also think we should make this behavior the default when partial credit is being awarded.

**Comment by echuber2** [comment]
It sounds like this would be the opposite of the direction that the matrix component input chose? Either way, it should be a pretty easy change to implement. In a pinch, it seems the checkbox selection can be implemented as several "Yes" "No" MC questions with security..

**Comment by eliotwrobson** [comment]
It looks like `hide-score-badge` has been added as an attribute since this issue was opened, and this hides the correct/incorrect icons that appear in the submitted answer panel. It seems like this issue can be closed.

**Comment by mwest1066** [comment]
Implemented via `hide-score-badge` (PR #2895) as @eliotwrobson said above.
