### ISSUE TITLE
best_submissions.csv includes saved-but-not-graded submissions

### ISSUE THREAD

**Issue by njohnwalker** [PrairieLearn/PrairieLearn#1465]
Maybe related to #1415:

CS 421 Spring 2019 ran an exam full of "Calculation" type questions that were to be graded offline, so the `server.gradeAnswer` method always returns 1.

The `best_submissions.csv` for these questions occasionally reported one of the student's save-only submissions rather than their save-and-grade submission.

**Comment by echuber2** [comment]
Created #1512 which seems to stem from the same issue somehow.
