### ISSUE TITLE
UX: Grading timed out after 60 seconds with explanation

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1469]
We understand that a grading timeout for a externally graded job probably means bad student code or bad course question code. Unfortunately, the `Grading timed out after 60 seconds.` error doesn't give the student (or course staff?) a clue on how to fix it.

Could we improve that error with some suggestions on why it might have happened?

**Comment by mwest1066** [comment]
See https://github.com/PrairieLearn/PrairieGrader/pull/56

This was merged a month ago, but I still need to deploy PG to make it live. I’ve got the new AMI built now, so I’ll push it out tomorrow morning.
