### ISSUE TITLE
Require file submission if in CBTF

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1475]
If a student navigates away from a question without submitting a file, there should probably be a warning.

**Comment by trombonekenny** [comment]
Dupe (or enhancement on) #1132?

**Comment by nwalters512** [comment]
Seems like a duplicate, yeah - assuming "submitting" means "clicking save/save and grade". @coatless can you confirm that #1132 is what you want?

**Comment by coatless** [comment]
Sort of. I would say there should be perhaps a larger error associated with a file rejection? E.g. you did the work and tried to submit, but it didn't work....

**Comment by nwalters512** [comment]
What counts as "didn't work"? Do you have a specific example in mind?

**Comment by coatless** [comment]
So, I think what happened is:

A student tried to upload a file named `my-bad-file-name.R`, which goes against the upload naming conventions of `my-app-here.R`. They then navigate away from the page thinking their answer was submitted.

**Comment by nwalters512** [comment]
we already have a warning like "**my-bad-file-name.R** did not match any accepted file for this question." that's shown as soon as they try to select such a file. We can only do so much - if students refuse to read instructions/warnings/etc., that's on them.
