### ISSUE TITLE
Doc Revamp v3

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1480]
Running through the user guide, there lacks a "quick" start portion and each section is highly detailed (good!) but the conclusion and the hand-off between sections can be worked on a bit more.

I think maybe a better structure would be:

- Installation
    - Docker
    - Launching from Command Line
    - Web-based Editor (discuss with @tbretl)
    - Aliases (Faster start?) 
- Course Setup
     - One-time: `infoCourse`
     - Every semester: `courseInstance`
- Question Creation
    - Question Components
    - High-level Element Overview
    - Best practices for external graders
- Assessment Creation
    - Start/end permissions
- Syncing
    - Production

From there, we'll split off the element documentation to be _per_ element. That is, each element now has its own page within the documentation. 

So:

```bash
- Elements
   - Submission
     - pl-*-input
   - Drawing
     - pl-*-drawing
   - Decorative
     - pl-code
   - Conditional
     - pl-*-panel
```

Other thoughts on what should be there? Or not be there?

**Comment by mwest1066** [comment]
This sounds great! The current docs are structured in a way that mirrors the code/database structure, which makes no sense for users 😄

**Comment by echuber2** [comment]
Can we have a mirror of the old docs? Links are going to break with a restructuring like this (including some legacy links in internal staff notes) and it will be necessarily to gradually reconcile those.
