### ISSUE TITLE
True/False Element

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1482]
The present way to create a True/False question is to use the `pl-multiple-choice` option. This option lacks the ability to easily _fix_ True/False positioning.

As an example, here is a common pattern for generating the T/F question:

### question.html

```
<pl-question-panel>
<p> {{{params.question_prompt}}}</p>
</pl-question-panel>

<pl-multiple-choice answers_name="ex" weight="1">
  <pl-answer>                {{params.wrong_answer}}</pl-answer>
  <pl-answer correct="true"> {{correct_answers.right_answer}}</pl-answer>
</pl-multiple-choice>
```

### server.py

```
import random

def generate(data):
    
    # List
    prompts = [
      "The color of the sky is blue.",
      "The color of the sky is pink."
     ]
    
    truth_statements = [True, False]
    
    # Pick prompt
    qid = random.randint(0, len(prompts) - 1)
    question = prompts[qid]
    correct = truth_statements[qid]
    
    # Setup parameters
    data['params']['question_prompt'] = question
    data['params']['wrong_answer'] = str(not correct)
    
    # Correct naming
    data["correct_answers"]["right_answer"] = str(correct)
```

**Comment by mwest1066** [comment]
Would it be easier to add an option to `pl-multiple-choice` to not randomize the order of answers? I think we used to have such an option with the old v2 multiple choice question type, but we didn’t add it in v3 yet. Other than saving an element, implementing T/F via M/C also has the advantage that instructors can choose exactly what wording they want “True/False”, “Yes/No”, “Agree/Disagree”, etc.

**Comment by mwest1066** [comment]
We now have a `fixed-order` options for `pl-multiple-choice`, which seems to remove the need for this new element.

**Comment by coatless** [comment]
See template added in #2173

https://github.com/PrairieLearn/PrairieLearn/tree/576c2754c8b25ca7f931d575fd938d32272420a9/exampleCourse/questions/templateMultipleChoiceTrueFalseFromList

**Comment by mwest1066** [comment]
Perfect!
