### ISSUE TITLE
GPU-enabled Graders

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1484]
From our chat on Thursday of last week with @mwest1066, @echuber2 + Milt Epstein (CS), & @coatless (myself), we were discussing the best possible route to add a configurable toggle to enable GPU accelerated code. 

The chat lead to discussions about:

- Separate queuing system for GPU-enabled jobs
    - Present grading fleet doesn't use GPU resources.
    - Each grading job is assigned to a single CPU core to ensure stability and performance.
- Potentially need to develop code to use spot instances
    - https://aws.amazon.com/ec2/spot/
    - Consider using a `while()` loop to prevent losing the instance.
- Create a flag for `info.json` to indicate GPU usage.
- Verify docker's ability to handle GPUs
    - [Nvidia's Docker](https://github.com/NVIDIA/nvidia-docker)
    - [SO: Using GPU from a docker container?](https://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container)

**Comment by echuber2** [comment]
Note also, Amazon's own GPU-enabled Dockers https://docs.aws.amazon.com/dlami/latest/devguide/deep-learning-containers-ec2.html

**Comment by echuber2** [comment]
"AWS DL Containers support TensorFlow and Apache MXNet, with PyTorch and other frameworks coming soon." - https://aws.amazon.com/machine-learning/containers/
:-/

**Comment by echuber2** [comment]
https://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html

**Comment by mwest1066** [comment]
The main thing we’d need to add here from the PL side is separate grading queues. From the PrairieGrader side we don’t need to do much, other than to add whatever flags docker needs to start with GPU support. Our infrastructure would need to add another autoscaling group running PG, pointing at the new SQS queue. That’s pretty easy if there is just one more of them (it’s another CloudFormation template), but it would be a hassle if were going to run lots of different types of grader VMs. For the foreseeable future, just CPU-only and GPU-enabled is probably enough.

The main thing we need before starting any of this is to confirm that there are available docker containers that can access AWS GPUs and can run the necessary code that the courses need. I believe @echuber2 is looking into this. The AWS DL containers sound great, so long as they support whatever the courses need (PyTorch??).

My personal opinion is that we shouldn’t worry about using spot instances. That’s just an extra headache that we can do without.

**Comment by echuber2** [comment]
Milt was looking into the docker situation and I think there were several viable ways to access GPU from a docker container, including a solution AWS came up with themselves, but we shelved work on that for the time being because the course that was slated to use it changed plans. This is still on the roadmap for the near future though.

**Comment by mwest1066** [comment]
@echuber2 sounds good, let me know if/when you guys want to look into it again.

**Comment by echuber2** [comment]
@mepstein-gh FYI

**Comment by coatless** [comment]
@mwest1066 I'll pick your brain about this the first week in September. Though, we need to figure out scoping from some of the deep learning projects.

**Comment by coatless** [comment]
- SQS queue: https://aws.amazon.com/sqs/
- 

PrairieLearn only deals with the queues listed here: 

https://github.com/PrairieLearn/PrairieLearn/blob/109a8f9a7ce523f1473844c35e90a66a7c1518f1/lib/config.js#L42-L43


Add a new queue that is configured in any setup. 

- GPU queue
- "Big data" queue 

In the question, we need to specify which queue to specify. 

https://github.com/PrairieLearn/PrairieLearn/blob/76412166bfd7e985d60971ed3fb783143b3d2fdc/lib/externalGraderSqs.js#L93-L109


Not going down the route of two configs...

- cpus
- gpu (enable)

**Comment by coatless** [comment]
Management of the scaling of the graders needs to be updated.

https://github.com/PrairieLearn/PrairieLearn/blob/6ed95919ef957c027b9c525148715a327a376895/cron/externalGraderLoad.js

**Comment by coatless** [comment]
After discussing, we're likely going to put extra queues on-hold until next semester.

**Comment by nwalters512** [comment]
@coatless is this still something that you'd like to see? Candidly, one of the biggest issues with this would be cost, as the GPU-enabled EC2 instances are 1-2 orders of magnitude more expensive than the ones we currently use for external grading. IMO we'd need some way to do per-course invoiced billing (as opposed to the per-institution, pay-up-front model we generally use), but we currently have zero infrastructure for collecting money in an automated way. Given that alone, I'm inclined to close this issue and only revisit this in the future once we have some billing foundations in place.

**Comment by echuber2** [comment]
I think courses have gotten around this so far by:
- students train models on something else (Colab/AWS) and submit a model only
- (or) students use CPU versions of Pytorch, etc. to do small toy examples on PL

**Comment by coatless** [comment]
Always interested in being able to scale or change resources depending on the requirements. But, this is probably a further down the line addition due to the billing requirements.

**Comment by nwalters512** [comment]
Something to consider would be a bring-your-own-compute option like GitHub's self-hosted runner option for Actions (https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).
