### ISSUE TITLE
Are student assessment instances visible to instructors if the student unenrolls?

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1500]
(Sorry I could not cram a better description into the title.)

Suppose we have a course instance set up only to facilitate an exam (placement, proficiency, etc.). Then a student may add that course instance just to take the exam, possibly with a proctor. If they remove themselves from the course instance a few days later, will that wipe out their exam record? (It should not.) I can't reproduce this by myself to find out. Can someone help me to see what happens, and then we can think about whether there are other issues to resolve with it?

I should note that in using the solo Docker version of PL, it seemed like if I took an assessment and then removed myself from the course, the stats screen for the assessment showed that nobody had taken the assessment (once again). So this worries me. We definitely need to be able to retain records regardless of student add/drop status.

**Comment by trombonekenny** [comment]
My guess is yes, but if someone has a quick way to confirm I encouraged Eric to post the issue.

**Comment by echuber2** [comment]
I just tried it out now that I've made a throwaway Gmail account. It looks like unrenrolling yourself doesn't affect the record of the assessment taken.

**Comment by mwest1066** [comment]
If a student unenrolls then it doesn't remove any of their records that the instructor sees. The student role will show as "None" if they are unenrolled, versus "Student" when they are still enrolled. All other data is identical. If the student re-enrolls then they can see all of their data again just like nothing ever happened.

**Comment by echuber2** [comment]
Okay, thanks for clarifying. I'll just close this issue.
