### ISSUE TITLE
Assessment question stats CSV export needs question ID (QID) column

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1507]
If you export the detailed question statistics CSV from a given assessment's question stats page, it shows the question title as a column but the question ID is nowhere to be found, although the PL web table view displays it. This is really inconvenient.

I'm wondering if PL is just exporting something different than intended _in general_, given that the web view has two different tables (statistics and "detailed" statistics), but they both produce the same CSV export, filename and all.

Related to #554

**Comment by echuber2** [comment]
See also #1508 as both tables have the same HTML ID.

**Comment by trombonekenny** [comment]
That seems like a fairly straightforward patch if someone is looking for a starter PL development project.

**Comment by mwest1066** [comment]
@echuber2 it’s just a bug that the QID is not included (in the HTML and in the CSV). Want to fix it? I’d be happy to have the question title replaced by the QID in the HTML tables (keep the tables compact), and add the QID to the CSV. I don’t think it really matters much whether the title is in the CSV or not.
