### ISSUE TITLE
Assessment questions stats page has two tables with same HTML ID

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1508]
The assessment overview question stats table view page (whew!) has two different tables, "statistics" vs. "detailed statistics," that both have the same ID, `id="questionsTable"`. Unless I'm mistaken, this is a no-no. I wonder if it's related to the export issue raised here: #1507

**Comment by mwest1066** [comment]
@echuber2 this is definitely just a bug. Would you be able to fix it? I think this is unrelated to #1507
