### ISSUE TITLE
dev_user login mode

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1509]
A challenge of development of auth systems is the config.authType == 'none' overrides some other options - for example, if you wanted to easily test LTI or password based authentication.

This issue proposes stripping out the magic in `middlewares/authn.js` that makes "Dev User" auth work and make it a full `pages/authCallbackDev` method. We'd still want to make sure it only triggers in certain cases, but having it be peers with other auth systems would make testing and developing other auth systems easier.

If we want to make the Docker user experience the same, perhaps default unprompted to Dev auth (like it does now), but on logout you can choose other systems?

**Comment by mwest1066** [comment]
I’m definitely on board with making dev auth work in the same way as the other auth systems. So long as we disable the route when we are running in production mode, this seems safe. I like your idea of forwarding unprompted to dev auth when we are not in production, and providing some mechanism to use other auth systems in dev.
