### ISSUE TITLE
Password exam locking behavior needs changes

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1579]
A potential UI issue for people taking an exam remotely with a proctor (password-protected): returning to the front page of PL causes the exam to re-lock. This makes the top navbar dangerous; students accidentally click "Assessments" trying to return to the exam overview instead of using the "Assessment Overview" button. Although re-locking the exam doesn't stop the exam timer, proctors may balk at logging students back into the exam if this happens, or the student may panic and not know what to do.

It would be good if there were some way to disable parts of the top navbar in specific situations. We already noticed it caused confusion for LTI students, but I think @trombonekenny has a solution drafted for that, see #1494

If hiding the navbar entirely would cause issues, perhaps we could add a modal warning popup when a student taking an exam clicks one of the links in the top navbar.

**Comment by nwalters512** [comment]
Is there any reason an exam should re-lock in the first place? Is that an exam security feature of some sort, or just an accident?

**Comment by echuber2** [comment]
The current behavior is that returning to the front page `/pl` will re-lock the exam, even if one just right-clicks the PrairieLearn logo and chooses "Open link in new tab." It appears that visiting *other* pages on PL doesn't relock the exam, so for example. you can have another course's page open in another tab and refresh it without relocking the exam. Maybe this is all just a bug.

I can see a benefit in having the exam auto-lock under various circumstances. For example, it avoids a situation where the proctor and student end the session but the student *does not finalize their exam*, which would allow them to be sneaky and log back in to continue working on it alone. Currently, we instruct proctors to watch students finalize their exam and log out.

There is yet another potential security issue in the current implementation, because it seems logging out itself **does not** deactivate the password login. This probably constitutes a bug. Example to reproduce the issue:

* Enter the password and begin exam on Tab 1
* Copy and paste the current URL to a new tab, Tab 2. Enter. Now the exam is open on both tabs.
* On Tab 2, click Log Out. Close the tab.
* On Tab 1, refresh the page. It takes you to the login screen. I click "Sign in with Google" (testing with a Gmail student account, no staff credentials).
* I'm back at the exam page, no lock engaged.

Furthermore, logging out and closing the browser alone also will not relock the exam, unless the browser cookies/cache are cleared, or if the exam was in a private browsing session. As long as the Google login credentials are retained in the browser, and as long as you don't navigate to `/pl`, it seems you can go directly back to the exam page based on its URL.

I think we need to change this to *not* relock just because of navigating to `/pl`, but instead to relock when the student logs out of PL. @trombonekenny I think I recall you saying that it should relock upon logout in the past, anyway.

**Comment by mwest1066** [comment]
@trombonekenny is the expert on this exam locking and password stuff. Let’s wait until he’s back and get his input on the best way to attack this.

**Comment by trombonekenny** [comment]
I see it, but I don't know how many cycles in August I can devote to tracking it down. As you mentioned, it's somewhat tied to the "what do the LTI users see in terms of navigation" issue - and the bigger scope of that scenario is making me rethink the PR in-progress.

A good solution is probably to look at what's resetting the password in the user cookie when they leave the course instance and see if we can adjust that - and also to adjust the navigation options when linked in through a limited scope, like LTI.

**Comment by trombonekenny** [comment]
Confirmed that logging out doesn't clear the password cookie (it should), and visiting /pl does clear the cookie (thanks to `server.js` calling https://github.com/PrairieLearn/PrairieLearn/blob/master/middlewares/clearCookies.js) where it probably shouldn't.

I'll get a PR in soon for these.
