### ISSUE TITLE
Consider adding autocomplete="off" to elements with inputs

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1624]
Chrome (and presumably other browsers) will aggressively remember and suggest previous inputs to form inputs by the `name` attribute. This is of limited, if any, utility to PL, and can be disabled to some degree with `autocomplete="off"` on input elements. We should investigate if this would have any adverse consequences and consider adding it to all input elements.

**Comment by mwest1066** [comment]
Excellent idea! It annoys me a lot when I’m typing in a numeric answer and it wants to autocomplete to the wrong thing. I can’t see any downside to this. Can you think of any potential issues?

**Comment by nwalters512** [comment]
I can't really think of any reason why we shouldn't do this, figured I'd ask y'all first though! I'll go ahead with this.
