### ISSUE TITLE
testFileEdit needs git email, leaves directories behind on error

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1639]
If you try to run the mocha tests from a shell in the PL docker container, they will fail with a git initialization problem:

```
  1) test file editor
       not the example course
         "before all" hook: create test course files in "not the example course":
     Async Stacktrace:
    at /PrairieLearn/tests/testFileEditor.js:218:21
    at /PrairieLearn/tests/testFileEditor.js:403:13
    at /PrairieLearn/tests/testFileEditor.js:378:21

Error: Command failed: git commit -m "initial commit"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@463fdd28683c.(none)')

      at ChildProcess.exithandler (child_process.js:297:12)
      at ChildProcess.EventEmitter.emit (domain.js:471:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
This has a secondary problem when the test fails it doesn't cleanup the directories it creates in `tests/testFileEditor` and fails the next times in a different way:

```  1) test file editor
       not the example course
         "before all" hook: create test course files in "not the example course":
     Async Stacktrace:
    at /PrairieLearn/tests/testFileEditor.js:218:21
    at /PrairieLearn/tests/testFileEditor.js:403:13
    at /PrairieLearn/tests/testFileEditor.js:352:21

Error: Command failed: git clone /PrairieLearn/tests/testFileEditor/courseOrigin /PrairieLearn/tests/testFileEditor/courseLive
fatal: destination path '/PrairieLearn/tests/testFileEditor/courseLive' already exists and is not an empty directory.
```

Solving the first part can be done by setting the `GIT_AUTHOR_EMAIL` environment variable before running the tests. That seems to work for me. I suppose we don't see this in Travis because that's set in their environment bootstrapping somehow? How can we add this to the docker environment so it works there too? What does PL set for this field when it does git operations in production?

For the path littering, I'd recommend checking for the directories when the test starts and removing them if they exist. I wouldn't do a cleanup on exit so that there's forensics to look at if things break, but I would make the test blow away anything it was going to create when it starts.

**Comment by mwest1066** [comment]
@trombonekenny how did you run the tests to get this failure? It works for me if I do:
```
docker run -it --rm prairielearn/prairielearn /bin/bash
# /PrairieLearn/docker/test_js.sh
```

**Comment by trombonekenny** [comment]
I did it manually (not via `test_js.sh`) by noodling around on the shell ... `npm test` or `npx mocha -b tests`, etc.)

Looking at `test_js.sh` I see why that execution passed:
```
[root@269d248747b9 /]# cat /PrairieLearn/docker/test_js.sh 
#!/bin/bash

cd /PrairieLearn
docker/start_postgres.sh

git config --global user.email "dev@illinois.edu"
git config --global user.name "Dev User"

npm test
```

**Comment by mwest1066** [comment]
Closing as not-a-bug. The system we have with setting the git user is a bit hacky, but it does work.
