### ISSUE TITLE
Duplicate Test Fails When Topic is JavaScript Object Property

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1651]
The new duplicate check that was introduced as part of the new syncing logic fails on things like `toString` that are built-in JavaScript object properties.

Essentially it's not safe to test `seen[v]` if `v` is `toString`, since it will return `true` the first time even before being set. (Actually it returns the function, but this is considered a truthy value or at least not a falsey value.)

And yes, I discovered this because I have questions named `toString` ;-).

**Comment by mwest1066** [comment]
This is now deployed. @gchallen: thanks for the extremely clear bug report and root-cause analysis!
