### ISSUE TITLE
pl-answer-panel tag ignored in new renderer

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1653]
I added the following code to the bottom of a question.html

```html
<pl-answer-panel>
    <p><strong>
    P.S. If you want to try out the "Report an issue" feature, go ahead. It's
    on the sidebar to the right.
    </strong></p>
</pl-answer-panel>
```

With `useNewQuestionRenderer` false, it renders as expected - only in the correct answer panel. With `useNewQuestionRenderer` true, it shows up like it's not in a panel at all (appears in all three panel contexts).

**Comment by nicknytko** [comment]
^ I put the above into a fresh `question.html` and I can't reproduce it:

![image](https://user-images.githubusercontent.com/1790491/78164286-2908de80-740f-11ea-95e0-5006434a0f27.png)

I'm probably going to go with @nwalters512 's suggestion here that there was a missing end tag or something and the HTML was malformed.   This is something that would probably be fixed as a result of a validator being put in place (https://github.com/PrairieLearn/PrairieLearn/pull/1170?)
