### ISSUE TITLE
Course-level element defaults

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1658]
Came up in a discussion with @daviddalpiaz regarding numerical tolerances.

The idea here would be to add into `infoCourse.json` a set of defaults that can be accessed instead of PrairieLearn defaults setup on a per-element basis, c.f. 

https://github.com/PrairieLearn/PrairieLearn/blob/75d8476922e9c8ca871c487a970f369267bc023a/elements/pl-number-input/pl-number-input.py#L10-L14

**Comment by coatless** [comment]
Consider placing a global configuration in the course elements directory.

**Comment by eddelbuettel** [comment]
Alternatively that's easily addressable via tinytest and its extensions mechanism.  Just define a set a test predicates which _also_ pick up a set of global defaults.
