### ISSUE TITLE
centos7-python image causing build status error

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1664]
The `centos7-python` image was renamed recently to `grader-python`. It seems like a remnant still exists in the main repo build. 

![Screen Shot 2019-08-31 at 9 52 12 AM](https://user-images.githubusercontent.com/833642/64065612-1a3a1f00-cbd5-11e9-9e53-84ad9a029dc1.png)

**Comment by mwest1066** [comment]
I removed the autobuild for `centos7-python`, which should fix this.
