### ISSUE TITLE
example Homework and Exam JSON examples are needed

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1667]
From @nwalters512: we need complete examples of Exam and Homework assessment config showing off all the various options and combinations of them. There is a partial Exam example at https://prairielearn.readthedocs.io/en/latest/assessment/, but it’s not annotated as such and is probably incomplete.

**Comment by eliotwrobson** [comment]
@mwest1066 is this still needed? I think there are plenty examples of this in the example course now.

**Comment by mwest1066** [comment]
The example course certainly has enough examples. I think the documentation is still a bit lacking in this respect, but I'm happy to close this issue until we come up with a better plan to improve the docs.

**Comment by eliotwrobson** [comment]
Sounds good, there are plenty of open docs issues anyhow
