### ISSUE TITLE
Add LTI for Coursera integration

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#167]
Coursera currently uses LTI 1.1: https://tech.coursera.org/app-platform/lti/

See http://www.imsglobal.org/specs/ltiv1p1/implementation-guide

An example course is: https://www.coursera.org/learn/python/

**Comment by trombonekenny** [comment]
LTI would let you talk back to Blackboard (Compass 2G) as well, which could be useful for gradebook purposes.

**Comment by mwest1066** [comment]
Implemented by @trombonekenny in 45ae9cfbf74f15d8e5f7c133acc0dc5316195a29
