### ISSUE TITLE
Project Svelte: audit centos7-plbase image

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1689]
Our Docker images have ballooned in size. Our base image `prairielearn/centos7-plbase` is now over 2GB, and the `prairielearn/prairielearn` image is now sitting at 2.5GB. These images are slow to build, slow to download, and will start blocking deploys if/when we move towards running PrairieLearn inside containers in production.

I propose that we audit everything that's being installed in this container and figure out how we can slim it down. As a starting point, here's some output from `du` at various locations in `prairielearn/centos7-plbase`:

```
[root@c22491fc594f /]# du -h --max-depth=1 / | sort -h -r | head -n 10
2.0G	/
1.8G	/usr
102M	/var
97M	/nvm
12M	/etc
6.0M	/root
104K	/run
36K	/tmp
4.0K	/srv
4.0K	/opt

[root@c22491fc594f /]# du -h --max-depth=1 /usr | sort -h -r | head -n 10
1.8G	/usr
958M	/usr/lib64
350M	/usr/share
297M	/usr/lib
79M	/usr/libexec
69M	/usr/bin
35M	/usr/include
20M	/usr/pgsql-11
8.2M	/usr/sbin
132K	/usr/local

[root@c22491fc594f /]# du -h --max-depth=1 /usr/lib64 | sort -h -r | head -n 10
958M	/usr/lib64
471M	/usr/lib64/R
310M	/usr/lib64/python3.6
32M	/usr/lib64/python2.7
18M	/usr/lib64/perl5
7.3M	/usr/lib64/gconv
2.2M	/usr/lib64/nss
1.7M	/usr/lib64/girepository-1.0
1.1M	/usr/lib64/security
956K	/usr/lib64/graphviz

[root@c22491fc594f /]# du -h --max-depth=1 /usr/share | sort -h -r | head -n 10
350M	/usr/share
230M	/usr/share/texlive
25M	/usr/share/perl5
12M	/usr/share/poppler
11M	/usr/share/fonts
9.5M	/usr/share/i18n
9.0M	/usr/share/cracklib
7.1M	/usr/share/hwdata
6.9M	/usr/share/ghostscript
5.5M	/usr/share/mime

[root@c22491fc594f /]# du -h --max-depth=1 /usr/lib | sort -h -r | head -n 10
297M	/usr/lib
166M	/usr/lib/jvm
92M	/usr/lib/python3.6
12M	/usr/lib/udev
9.2M	/usr/lib/systemd
8.7M	/usr/lib/gcc
5.1M	/usr/lib/python2.7
1.6M	/usr/lib/locale
1.4M	/usr/lib/cups
1.2M	/usr/lib/dracut
```

Of note:
- The entire JDK
- Perl
- 2 versions of Python
- Almost half a gig of `R` stuff - cc @coatless
- 230MB of `texlive`

My suspicion is that much of this is unneeded, especially at runtime.

#1626 should help with this effort, as it will allow us to separate PrairieLearn runtime from the question code runtime when building images for production.

**Comment by coatless** [comment]
Might be able to switch over to using: 

https://copr.fedorainfracloud.org/coprs/iucar/cran/

This would allow us to avoid compiling _R_ packages from source.

**Comment by nwalters512** [comment]
I've spent time on this over the years and haven't managed to shrink the image size significantly. Our best bet is to split `plbase` into a "runtime" image and a "development" image that builds on top of "runtime" with `git`/`gcc`/etc. If we want to pursue that, we'll open a new issue.
