### ISSUE TITLE
Instructor Question Quickview

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#169]
I'd like a way to quickly jump to a question and validate that it's working as expected without having to suffer through the Exam modes. Historically, I've created a "BasicExam" which lets me do that, but because the schema is different between Basic and Exam, it becomes rather onerous rather quickly.

**Comment by mwest1066** [comment]
Should be addressed by #159

**Comment by tnip** [comment]
Closing per @mwest1066, #159
