### ISSUE TITLE
pl-file-download cannot be used with clientFilesAssessment & clientFilesCourseInstance

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1691]
Stumbled across this one... The `pl-file-download` element cannot access `clientFilesAssessment` or `clientFilesCourseInstance` as it isn't in the list. 

https://github.com/PrairieLearn/PrairieLearn/blob/c639c85aaa693fa27d0381dcb0bf61bb6571d57c/elements/pl-file-download/pl-file-download.py#L31-L34

**Comment by nwalters512** [comment]
My guess as to why: any question using these wouldn't be portable between assessments or course instances. What use case do you have in mind for this?

**Comment by coatless** [comment]
@nwalters512 a few motivating examples:

- syllabus. 
- (fixed) data set. 

Though, I think these files would be available one-level up. e.g `../file.ext`

There seemed to be an example with `clientFilesAssessment` with `data.txt` and the docs also have a section on kinds.


https://prairielearn.readthedocs.io/en/latest/clientServerFiles/
https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/courseInstances/Sp15/assessments/homework2/clientFilesAssessment

**Comment by mwest1066** [comment]
Closing this as not-a-bug. We'd like questions to be independent of the assessment or course instance.

@coatless feel free to re-open
