### ISSUE TITLE
Add answer feedback to multiple choice/checkbox elements

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1693]
Based on an instructor's request for an ability to show specific feedback for correct or incorrect answers, like "This is not the correct answer because XYZ". To enable this, we'll introduce new functionality to the `<pl-multiple-choice>` and `<pl-checkbox>` elements. We'll add a new type of child called `<pl-feedback>` that will allow content developers to specify specific feedback for each element. Here's how that will look:

```html
<pl-multiple-choice>
  <pl-answer correct="true">The correct thing</pl-answer>
  <pl-feedback>This is the right answer! Good job.</pl-feedback>
  <pl-answer correct="false">The wrong answer :(</pl-answer>
  <pl-feedback>That isn't correct; you should study some more.</pl-feedback>
</pl-multiple-choice>
```

Thus, the feedback will be associated with the preceding `<pl-answer>` element. We will allow for only a subset of the answers having feedback. We can do some basic validation, such as ensuring that any `<pl-feedback>` element is immediately preceded by a corresponding `<pl-answer>` element.

**Comment by nicknytko** [comment]
assigning to @RDT04

**Comment by RDT04** [comment]
I will be working on this project.

**Comment by nicknytko** [comment]
Echoing what @trombonekenny mentioned earlier, I think I would rather have the markup look something like:

```html
<pl-multiple-choice>
  <pl-answer correct="true">The correct thing <pl-feedback>This is the right answer! Good job.</pl-feedback></pl-answer>
  <pl-answer correct="false">The wrong answer :( <pl-feedback>That isn't correct; you should study some more.</pl-feedback></pl-answer>
</pl-multiple-choice>
```

I don't know, it just feels weird to me to assign values based on their relative positioning.

**Comment by ashnaarya** [comment]
#3861

**Comment by eliotwrobson** [comment]
Seems like feedback has been implemented for both of these elements. I think this issue can be closed.
