### ISSUE TITLE
Optimize conditional rendering in questions

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1695]
Right now, all "conditional" elements (`<pl-answer-panel>`, etc.) are implemented as normal PL elements in Python. This means that for every such panel, we have to serialize the relevant portion of the tree to a string, send to to the Python element code, parse it, reserialize it, send it back to JavaScript, and re-parse it. This could be avoided by making these elements "pseudoelements" that don't have an implementation in Python, but rather are implemented as a core part of the renderer. Thus, to "render" such an element, we just check if the element name is `pl-answer-panel`, and if we aren't rendering that part of the tree, just throw it away; if we are, we can just lift the children elements up to be children of the parent.

Once https://github.com/PrairieLearn/PrairieLearn/issues/1694 is implemented, we could easily implement that as a "pseudoelement" too.

Currently, a course could theoretically create their own version of `pl-answer-panel` or the like by putting it in their own `elements` directory. Although I don't think any course has done that yet, we should be consistent and continue offering that same level of flexibility. That is, we should use a course's implementation of these elements even if they are implemented as "pseudoelements" in the renderer.

**Comment by echuber2** [comment]
Has #1694 been implemented in the necessary way now?

**Comment by coatless** [comment]
@echuber2 added as [`<pl-hide-in-panel>`](https://prairielearn.readthedocs.io/en/latest/elements/#pl-hide-in-panel-element). c.f.  #1710

**Comment by eliotwrobson** [comment]
@nwalters512 is this no longer relevant in light of https://github.com/PrairieLearn/PrairieLearn/pull/7128? I think all of the savings in efficiency from this issue are done more comprehensively in that PR.

**Comment by nwalters512** [comment]
Good call, that's going to be a much better solution to this minor problem. I'll close this!
