### ISSUE TITLE
[Minor feature request] Exam numbering

### ISSUE THREAD

**Issue by GittyupMule** [PrairieLearn/PrairieLearn#1701]
I took CS 225's Exam **0** exactly one week ago. When navigating to the "Start Assessment" screen, the exam was labeled as

> **Exam 1**: Exam 0

So I'm requesting that minor configuration to allow exams to be numbered from 0 in the UI be added.

**Comment by nwalters512** [comment]
This was done explicitly by CS 225; they have `"number": "1"` in their assessment config. I suggest contacting someone on course staff directly about this concern. Thanks!
