### ISSUE TITLE
textarea overflows its container

### ISSUE THREAD

**Issue by jasonxia17** [PrairieLearn/PrairieLearn#1704]
![image](https://user-images.githubusercontent.com/8812440/64927772-08f83180-d7d5-11e9-8032-29ffe6b100a4.png)

When using Chrome on Ubuntu 16.04, the textarea element is too wide. This could be fixed by adding the property "max-width: 100%" to the textarea's CSS rule.

**Comment by nwalters512** [comment]
This question is using a raw `<textarea>` tag and not one of the [elements](https://prairielearn.readthedocs.io/en/latest/elements/) that we provide, so we don't have control over how this question is rendered. I suggest you reach out to someone on 233 course staff to have them correct this!
