### ISSUE TITLE
Option to set "Correct answer" panel text

### ISSUE THREAD

**Issue by leehaoxin** [PrairieLearn/PrairieLearn#1709]
Right now if we use `<pl-answer-panel>`, the grey box always says “Correct answer”, even if our feedback in the box tells the student their answer was incorrect. It would be great if we could have the option to change what the grey box says.

**Comment by trombonekenny** [comment]
@leehaoxin Can you describe more of this? Or did you find a work around for it? (Potentially not scoring the question correct so that the Correct answer panel doesn't show? Or would a toggle to turn off the correct answer panel entirely solve this?

**Comment by leehaoxin** [comment]
@trombonekenny Hi, we got around it by putting the answers into `<pl-submission-panel>`, but it would be great if there'd be an option to turn off the correct answer panel! Here's what it looks like on our end:
<img width="627" alt="workaround" src="https://user-images.githubusercontent.com/12851431/79495532-5a2a0700-7fea-11ea-9a47-6b28a2a5cf1a.png">
As you can see, the "Correct Answer" panel is still there, but empty.

**Comment by echuber2** [comment]
Related: #623

**Comment by eliotwrobson** [comment]
Hiding the correct answer panel was resolved in #5908, closing this issue.
