### ISSUE TITLE
Add timer for exam modes

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#171]
(requested by Mindy)

This is needed when we have 1 h and 2 h exams running at the same time, especially given that the 2 h exams are staggered with respect to each other.

**Comment by mwest1066** [comment]
Depends on #138

**Comment by trombonekenny** [comment]
What happens when the timer expires? The student can't use the quiz anymore? They can, but questions are flagged as after time?

**Comment by mwest1066** [comment]
Implemented for non-CBTF exams in 46de0ef681a1d57537e57f28454e2ba51161128d
