### ISSUE TITLE
course instance show user roles

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1721]
We don't currently have an UI to display the user roles for a course instance. (Adding in-browser editing for `infoCourseInstance.json` helps with this, but it's not as nice as something shown in the display.)

Another table in the access tab for the course instance seems reasonable.

**Comment by mwest1066** [comment]
I’d actually be inclined to add a separate “Roles” page, just to keep things simple. I agree it’s annoying that we don’t have this.
