### ISSUE TITLE
Doc entry for styling questions

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1753]
From a few conversations, I think it might be helpful to mention that there are [`Bootstrap`](https://getbootstrap.com/docs/4.3/components/card/) CSS classes available for use to style questions. 

Predominantly, there is a way to create "cards" within `question.html` via:

```html
<div class="card my-2">

    <div class="card-body">
        <pl-question-panel>
            <markdown>Some content</markdown>
        </pl-question-panel>
    </div>

</div>
```

These boxes can have a title with additional markup: 

```html
<div class="card my-2">

    <div class="card-header">
        Title here
    </div>

    <div class="card-body">
        <pl-question-panel>
            <markdown>Some content</markdown>
        </pl-question-panel>
    </div>

</div>
```

Are there other style components that should be mentioned?

**Comment by nwalters512** [comment]
Related: maybe a `pl-card` element is in order?

While I understand that questions do and will likely continue to rely on Bootstrap styling, I don't necessarily like that fact - it means we'll be effectively locked to Bootstrap v4 forever, as the global classes on the page become a de facto part of the public API of PrairieLearn. If we abstract away as much styling as possible from users, we make the potential upgrade to newer versions of Bootstrap easier in the future.

**Comment by mwest1066** [comment]
Yes! I don’t know what to do about this. I really don’t want questions to use bootstrap classes, because then everything will break when we upgrade to Bootstrap 5 (or whatever). Should we aim to provide a set of `pl-` classes that questions can use? So `class=“pl-table”`, for example, which we could map to bootstrap? I don’t have a good sense of how ugly this would get.

**Comment by trombonekenny** [comment]
I'm in favor of making the underlying frameworks visible/discoverable to advanced course content creators who wish to use them. I don't think it does us a service to abstract well defined web things under new `pl-` classes or elements just to make upgrade paths easier. (If anything, that makes _us_ responsible for figuring out how to map technology A to technology B, when I think that should the course content creator's responsibility. It's part of their risk embedding technology A in the first place.)

We could build tools to help identify questions with outdated classes or methods. Maybe with tags? Or sync errors? Or some sort of course repo CI? But that's about as far as I would go (and probably wouldn't even need to be our custom code if someone else has a linter for that stuff).

**Comment by nwalters512** [comment]
> I'm in favor of making the underlying frameworks visible/discoverable to advanced course content creators who wish to use them.

I think it's fundamentally impossible for us to actually hide the underlying styles on the page from courses - after all, their content and code is running in exactly the same environment that ours is. My concern is that right now, people don't have a *choice* on if they rely on them - if you want to use a card, or a button, etc., you need to rely explicitly on Bootstrap classes. Right now, we neither inform people that this is potentially risky, or provide alternatives that avoid that risk.

> I don't think it does us a service to abstract well defined web things under new pl- classes or elements just to make upgrade paths easier.

I do agree that providing our own classes is not the right approach, at least as long as we continue to use Bootstrap. If we start providing classes, we may as well just opt out of Bootstrap entirely and start maintaining our own design system (which I would love to do, iff we had the resources to support that, which we do not).

> We could build tools to help identify questions with outdated classes or methods. Maybe with tags? Or sync errors? Or some sort of course repo CI? But that's about as far as I would go (and probably wouldn't even need to be our custom code if someone else has a linter for that stuff).

I don't think this is solvable via linting - our element system is about as hostile to static analysis as one can get.

It's entirely possible that this will be a non-issue, and that the Bootstrap API has stabilized and won't have major breaking changes in the future. But the longer we wait to think seriously about this problem, the more content that will be created explicitly for Bootstrap 4 without a clear migration path.

As an interesting aside: this is a problem that's been "solved" for years in the React world. Libraries and tooling exist where components (React's version of our elements) declare their own styles, which are then scoped to individual components at build time or runtime. I don't know if this necessarily means something to us, but it's some interesting prior art!

**Comment by coatless** [comment]
I'm going to bump this question slightly... 

Are there any well-formatted/structured questions that can be showcased as good examples of question layout? 

The example questions we have now as part of the test suite are hit-or-miss.

**Comment by mwest1066** [comment]
I think this comes back to the need to split `exampleCourse` into two courses: `testCourse` and `exampleCourse`. Everything the test suite needs should go into `testCourse` and all of the `example*` questions go into `exampleCourse`. Then we make `exampleCourse` publicly available and never mention `testCourse` outside of the test suite.

The relation of this to the current issue is that we can then go through the `exampleCourse` questions and make sure they conform to our style guidelines.

**Comment by mwest1066** [comment]
I think the big issues here are:

1. Do we encourage or discourage the use of Bootstrap styles in questions? Either way, we should document this for instructors, and make sure that our example questions match this decision.

2. If we discourage the use of Bootstrap styles, should we provide some other styling guidance to question authors?
