### ISSUE TITLE
Randomization of Code Scenarios in Starter Files through Mustache Templating

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1758]
**Goal:**
 
Better support for randomization within code scenarios.

**Idea:**

Given a starter code file and a set of dynamic parameters, run the code file through `mustache` to modify the template with the appropriate `data` parameters. Serve the template to the user.

**Example:**
```
<pl-code source-file-name='my_script.R" template="true"></pl-code>
```

**Use case:**

Customizing random seed given to students.

----

Present sketch...

**server.py**
```python
def generate(data): 
       # Scenario specific changes
       file_params = {
        'value': 1
       }

       # Write scenario into starter template with mustache
        with open('some_code_file.R', 'r', encoding='utf-8') as f:
           written_file = chevron.render(f, file_params).strip()

      # Release into problem
      data['params']['code_template'] = written_file
```

**question.html**
```html
<pl-code language='r'>
{{{params.code_template}}}
</pl-code>
```

**Comment by nwalters512** [comment]
A general question: are there any languages with a double-curly-brace syntax that could conflict with this? Does mustache allow escaping of curly braces if so?

**Comment by coatless** [comment]
@nwalters512 not that I'm aware of. 

Looks like mustache also has support for templating escapes:

```
* {{ default_tags }}
{{=<% %>=}}
* <% erb_style_tags %>
<%={{ }}=%>
* {{ default_tags_again }}
```

c.f. https://github.com/janl/mustache.js#setting-in-templates

**Comment by coatless** [comment]
@eliotwrobson this isn't a zip file question?

**Comment by eliotwrobson** [comment]
@coatless in the example, the zip file contains a python file generated from a template, similar to the example code you have here.
