### ISSUE TITLE
Share parameters between questions

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1823]
Use case: 

Using the same seed to regenerate question data allowing the same underlying data set between different questions. 

From Slack @trombonekenny mentioned:

> If there was a way to define "this group of questions will all get the same random seed", would that work for your needs?

My thought would be adding a `dependsOn:` key required inside of a question zone. Maybe it would need to be in the question's `info.json`....

**Comment by steven-wolfman** [comment]
@ffund pointed this issue out to me when I [posted this on Slack](https://prairielearn.slack.com/archives/C0PHG0GQZ/p1666288158389869). This was my thought for having a "stable" randomly generated object across multiple questions:

Make some shared utility code that does this:
1. Generate a key by, say, concatenating the user UUID as a string, the assessment UUID as a string, and maybe a salt (some arbitrary string). (Can I access UUIDs? Could I also have some text in there that depends on the number of variants requested by the student so this would work for problems where they can generate new variants? I guess just using the variant ID would work if I can get access to that?)
2. Taking its hash code.
3. Seed my random number generator with that.
4. Generate the object.

Now, each problem can use the same utility code and I can be confident that the student will get identical objects at the top of each problem in a given assessment (for a given variant if that part would work) but they would receive uncorrelated objects across different assessments/students (with reasonably hash functions and randomization, of course).

**Comment by nwalters512** [comment]
Discussion of this potential feature continues here: #5501

**Comment by jeffgerickson** [comment]
This issue should be reopened.
