### ISSUE TITLE
grading jobs stuck in report phase

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1842]
We've see a couple of instances where external grading jobs get stuck in the report phase for several minutes. It always seems to last about 4 minutes.

![2019-11-05 at 22 21](https://user-images.githubusercontent.com/875833/68268245-0ec30400-001b-11ea-80df-58641c2d9bb6.png)

**Comment by echuber2** [comment]
These are nice charts.

**Comment by mwest1066** [comment]
Yay!
