### ISSUE TITLE
sympy to/from json loses Symbol assumptions

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1844]
`server.py`
```
import prairielearn as pl
import sympy
import python_helper_sympy as phs

def generate(data):
    c = sympy.var('c', positive=True, real=True)
    ans = 1 / sympy.sqrt(c)
    data['correct_answers']['foo'] = pl.to_json(ans)
```
When the `grade` function unpacks the JSON'd answer back into Sympy (`python_helper_sympy.json_to_sympy`) it loses the assumptions made with the c Symbol so the answers don't match.

(Because this is [one of those edge cases](https://docs.sympy.org/latest/tutorial/simplification.html#powers) where the `positive=True, real=True` assumptions need to be set with the variable. If we do that on the `generate` it doesn't persist through to the `grade`

@tbretl How should we fix this?

**Comment by mwest1066** [comment]
I'm assigning this to @tbretl in case he finds some extra time on the flight back from China 😄

**Comment by trombonekenny** [comment]
@coatless Suggested https://github.com/PrairieLearn/pl-stat400/blob/master/questions/symbolic_differentiation_sqrt/server.py would be a good test question too.

**Comment by coatless** [comment]
@tbretl did you ever get a chance to look into preserving assumptions set within `sympy` when converted with `pl.to_json()`?

**Comment by echuber2** [comment]
Here's a relevant chunk of the code:

https://github.com/PrairieLearn/PrairieLearn/blob/905d6d62afb11f6b187653aea7a178b0aeb58844/lib/python_helper_sympy.py#L251

Could have `sympy_to_json` include another key in the object, `_assumptions`, that is a dict mapping each variable in `_variables` to yet another dict of that variable's assumptions. I think you can already get that with the `assumptions0` property:

```
>>> c = sympy.var('c', positive=True, real=True)
>>> c.assumptions0
{'negative': False, 'infinite': False, 'extended_nonpositive': False, 'nonzero': True, 'extended_negative': False, 'complex': True, 'zero': False, 'extended_real': True, 'positive': True, 'finite': True, 'commutative': True, 'hermitian': True, 'extended_nonzero': True, 'extended_positive': True, 'imaginary': False, 'nonnegative': True, 'nonpositive': False, 'extended_nonnegative': True, 'real': True}
```

These would have to be reapplied in the constructor when the variables are recreated in `convert_string_to_sympy`:

https://github.com/PrairieLearn/PrairieLearn/blob/905d6d62afb11f6b187653aea7a178b0aeb58844/lib/python_helper_sympy.py#L221

There, we may need to validate that the assumptions don't conflict when the symbol is recreated. It looks like Sympy will automatically throw an InconsistentAssumptions error if that happens:

```python
import sympy
from sympy.core.facts import InconsistentAssumptions

try:
    q = sympy.Symbol('q', positive=True, negative=True)
except InconsistentAssumptions:
    print("Contradiction!")
```

There is an entirely different assumptions system available in Sympy, too. See: https://stackoverflow.com/a/16435975

Another problem I had working on the sympy matrix component input element, was that I did want to allow float factors in the Sympy expressions, but the upstream Sympy elements on PL explicitly disallow that in various places. So I had to make a forked copy of the support libraries and re-allow that. I think that could be configurable.
