### ISSUE TITLE
Best-practices documentation

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1853]
We currently have fairly good reference docs, but we are lacking in "best practices" documentation, or tutorials that explain "this is the way you should achieve goal X". PR #1672 is an example of what we need, I think.

**Comment by eliotwrobson** [comment]
I'll try to take a crack at this at some point. I think some related discussion is available in existing documentation (like on questions, for example). But this discussion is pretty light, and it would be good to add some detailed discussion about setting up CI and using GitHub actions to help manage code for large courses.

**Comment by eliotwrobson** [comment]
This has been discussed in the following post: https://github.com/PrairieLearn/PrairieLearn/discussions/10582
@mwest1066 should this be closed?

**Comment by mwest1066** [comment]
Thanks for closing!
