### ISSUE TITLE
Tab titles should reflect the subpage that is open

### ISSUE THREAD

**Issue by astrosticks** [PrairieLearn/PrairieLearn#1863]
Currently, every single PrairieLearn page just has "PrairieLearn" as the name that shows up in tabs and window titles. This makes it so that users with multiple PrairieLearn tabs/windows open have to manually keep track of which tab has which page open. 

Here is an example of how my tabs appear to me when I do multiple pre-lectures for CS233 at once:

![image](https://user-images.githubusercontent.com/32315760/68894038-0ab67680-06ec-11ea-98d3-14b097c0b9d0.png)

It would be nice to see the page titles contain information about the subpage that is open, formatted with information like the name of the problem that is open, the associated course, and possibly the word "PrairieLearn".

**Comment by astrosticks** [comment]
![image](https://user-images.githubusercontent.com/32315760/68894211-726cc180-06ec-11ea-90fa-e135c662e271.png)
A page that looks like this could have a formatted title of "PRE17: Recursion (CS 233, fa19) - PrairieLearn"

**Comment by coatless** [comment]
@astrosticks thanks for the request. Easy is a bit subjective here. Unfortunately, it's currently hard coded in a page partial. 

https://github.com/PrairieLearn/PrairieLearn/blob/77e142b1d71254e6f68eacb46500b20df289b001/pages/partials/head.ejs#L4
