### ISSUE TITLE
Make "Finish Exam" button more obvious

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#190]
Students have been asking me how to finish an exam relatively often - it might be good to change the text of the button from "Assessment Overview" to something that implies both the overview and the finish&grade button are there - or make it so that when you get to the last question, a Finish Exam button appears.

**Comment by mwest1066** [comment]
Also see #49 and #198.

**Comment by kevinwang** [comment]
Closed by #301.
