### ISSUE TITLE
Invisible unicode character at end of input is hard to fix

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1912]
See `submission_id = 22539594`. The submitted answer is `5.333<U+202C>`, which is `INVALID` for `pl-number-input`, but displays fine because U+202C is invisible.

Exporting all submissions to CSV give a submitted answer of `null`. It’s not clear why the actual submitted answer doesn’t show up here.

**Comment by mwest1066** [comment]
I think we could fix the web display issue by adding a python helper to render non-printable characters (untested):
```
print_chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ '
def string_to_printable(s):
    return ''.join([c if c in print_chars else f'<U+{ord(c):x}>' for c in s])
```
This could go in the `prairielearn.py` library, so all elements can use it when displaying invalid input (maybe also for valid input?).

**Comment by echuber2** [comment]
@mwest1066 I think the input element needs to be updated to flag it as invalid from the get-go, or if nothing else, the invisible character should be stripped upon submission; and then maybe there's no need to deal with displaying it (once removed).

It looks like there are existing methods for handling this situation:
https://stackoverflow.com/questions/92438/stripping-non-printable-characters-from-a-string-in-python
https://stackoverflow.com/questions/7147396/python-how-to-delete-hidden-signs-from-string

**Comment by echuber2** [comment]
I don't know if this would break internationalization for future users of PL who maybe enter numbers in a left-to-right script, if that requires some invisible unicode stuff to be present.

**Comment by echuber2** [comment]
I probably don't have access to the specific submission to reproduce this. Is there a more specific reproduction sample? Should we just be working on treatment of `5.333<U+202C>` (etc.) when submitted through `pl-number-input` as a testcase? ]

**Comment by mwest1066** [comment]
@echuber2 I think the `5.333<U+202C>` submitted to `pl-number-input` is a good testcase.

I like your "strip non-printable" fix as well. It seems to me we should add `string_to_printable()` and `strip_nonprintable()` functions to `prairielearn.py`, and then different elements can use these as appropriate.

For example, I think that you are correct in suggesting that `pl-number-input` could just strip non-printable characters, because these are never part of numbers. However, `pl-string-input` probably has to be more careful, because of unicode things like right-to-left strings. In that case, it might be better to accept everything, but make sure we display non-printable characters so students can see them.

**Comment by echuber2** [comment]
@mwest1066 If you're going to do that, then perhaps they should be displayed as full-width space with color highlighting or something. Not sure how to make that accessible too. Show a placeholder glyph like a mid-dot?
