### ISSUE TITLE
Add institution information for instructors

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1961]
We should add the course institution to `pages/instructorCourseAdminSettings`.

And the user's institution to `pages/userSettings`.

**Comment by mwest1066** [comment]
(this came up in #1958)

**Comment by mwest1066** [comment]
We also need to show them which institution their own course is in. This could go on `pages/instructorCourseAdminSettings`.

And which institution they are in as a user. This could go on `pages/userSettings`.

**Comment by nwalters512** [comment]
Institution information was added to the course admin settings page in #6952 and to the user page in #7286.
