### ISSUE TITLE
pl-code Rust syntax highlighting

### ISSUE THREAD

**Issue by zmabry2** [PrairieLearn/PrairieLearn#1962]
is it possible to have rust syntax highlighting added to pl-code elements?

We have a class that will be in Rust next semester, and would like to use pl-code rather than file submission if possible, just for ease of use.

**Comment by nwalters512** [comment]
I opened #1963 to add support for Rust to `pl-code`. `pl-file-editor` should already have Rust support; let me know if you're seeing otherwise. Those should be the only two elements where Rust support is needed.

**Comment by zmabry2** [comment]
Thank you for the quick support, I appreciate it!

**Comment by nwalters512** [comment]
Happy to help! Note that this isn't in production yet, but it'll be available in the Docker image if you want to start working on course content.
