### ISSUE TITLE
Course instances are hard to find after changing courses

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1965]
Steps to reproduce:

1. As an instructor, go into a course.

2. Select the "Questions" tab (or any tab that isn't "Course instances").

3. Select a different course from the dropdown next to the course name.

4. It's not obvious how to get to a particular course instance.

One possibility would be to have a dropdown in the navbar for "Choose course instance". Another possibility would be to default to the most recent course instance (the one with the highest `number`).

**Comment by tbretl** [comment]
I assume the reason you haven't said the same thing about assessments (go into a course instance, select any tab other than "Assessments", and switch course instances - then "it's not obvious how to get to a particular [assessment]") is that we include a link to the "Assessments" list in the nav-bar.

So, I suggest putting "Course Instances" in the nav-bar as well. It will then be equally obvious how to get to the list of Course Instances and to the list of Assessments. The downside is that this crowds more into the nav-bar (which will soon have to accommodate some kind of institution switcher as well).

The alternatives you proposed are workable (I tried implementing the dropdown, for example) but inconsistent with how we handle assessments.

**Comment by mwest1066** [comment]
That’s a good point about Assessments not suffering from the same issue, at least not to the same extent. However, the entire navigation mode of assessments is different. For example, if you are in HW1 and you click “Gradebook” (or any other CI-level page) then you “go out of” the assessment in the sense that the assessment no longer appears in the navbar. This is in contrast to course instances, where clicking on course-level pages (like Questions) keeps you “in” the course instance.

I’m having trouble imagining a separate “Course Instances” tab in the navbar. It seems like it would almost always be redundant with the current course instance button and its associated dropdown?

I do generally like the idea of keeping the fast switcher dropdown in the navbar at all times, just labeled “Choose” or “Instance” or something if we don’t have a current course instance.

We could actually do the same thing for Assessments, to make them more like Course Instances, although this doesn’t seem as necessary.

**Comment by mwest1066** [comment]
Following up on the Assessments behavior, I’ve found many times that my expected behavior is that changing the “current object” (current course instance or current assessment) should not change which page I’m on.

For example, if I’m viewing the Statistics page for HW3 in Fall 2019, and I change to Spring 2018, then I’d ideally like to still be on the Statistics page for HW3 in the other semester. Of course I appreciate the difficulties in making this happen, I’m just reporting what I expected as a user 😄

Another example is that I’m viewing the contents of the `infoAssessment.json` file in HW3, and I switch to HW4. I would have expected to now be viewing `infoAssessment.json` for HW4, but I’m actually dropped back to the base level of the Files tab. Again, I fully appreciated why it does this, but the behavior was nonetheless unexpected 😄

To be clear, I’m not suggesting that we need to immediately (or ever) address these particular switching situations.

**Comment by tbretl** [comment]
Fair enough about nav structure difference, instances vs assessments. I already have the dropdown implemented, so we can go with that.

With respect to your other comment, obviously the instance / assessment switchers should keep the page the same if possible - the `navSubPage` is kept the same when switching, for example, for exactly this reason. Doing this more broadly has long been on my list of non-MVP to-do's.
