### ISSUE TITLE
Instructor mode with emulated user may have wrong nav bar

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1984]
Reported by @daviddalpiaz 

Steps to reproduce:

1. Go to the instructor view of a course instance.

2. Select "Your name" -> "Change effective user" and change effective user to a student in the current course instance.

3. Now you will still be in Instructor view for the course instance, but the top navbar will no longer display the course shortcuts like "Issues" and "Questions"

**Comment by daviddalpiaz** [comment]
I think this actually has additional effects that I'm noticing as a test more. For example, after changing effect user from student, then back to instructor, ability to edit questions is lost.
