### ISSUE TITLE
File editor shows greyed out edit button for some file types

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#1985]
As seen in the screenshot below, the `.R` files have a greyed out `Edit` button.  The files can be edited by first clicking the name of the file and then clicking the `Edit` button from within that window, but you cannot enter the editing screen from the overview page in the screenshot.

![Screen Shot 2020-01-17 at 1 04 49 PM](https://user-images.githubusercontent.com/9003346/72638945-7622fb80-395c-11ea-9366-6d31456c5aba.png)

**Comment by mwest1066** [comment]
Currently the "Edit" link is enabled based on a white-list of file extensions. I think the right thing to do here is to use `isBinaryFile` on each file to find out whether it's a text file or not, and enable the "Edit" link for all text files.

`isBinaryFile` is used here: https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorFileEditor/instructorFileEditor.js#L126

**Comment by jonatanschroeder** [comment]
Better option: https://github.com/ajaxorg/ace/blob/master/demo/modelist.html, which allows you to find a mode based on the extension. This would allow all files supported by Ace to be directed to the proper mode. The default is text mode, but it the extension also has a regular expression for the current mode, which allows you to check if the mode itself officially supports that extension.
