### ISSUE TITLE
Introduction text for Homework type assessments is too specific or not necessary

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#1989]
Text in screenshot below appears at the top of Homework assessments. If `maxPoints` is not set, this text does not align with how the user interacts with the assessment.

Two possible fixes:

- Remove this text.
- Make this text user modifiable.

![screen_shot_2020-01-18_at_12 39 40_pm](https://user-images.githubusercontent.com/9003346/72684376-12bdd880-3ad8-11ea-9e9f-db589a1ecd95.png)

**Comment by mwest1066** [comment]
I agree that we should probably just remove this text completely.
