### ISSUE TITLE
syntax highlighting code segments

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#199]
From Lawrence Angrave:

In multiple choice questions, automatic syntax highlighting of Java and C code inside <code> tags

Dave: Perhaps incorporate https://highlightjs.org/ into PL?

**Comment by tnip** [comment]
++. We've got a super simple hack going on in our world to differentiate between prose and code right now - because:

(1) hax
(2) making sure code is readable for all people (regardless of impairment)

**Comment by mwest1066** [comment]
@tnip, can you point to an example?

**Comment by tnip** [comment]
I've got two examples.

We have our "in-PL" highlighting (i.e., using ```font-family:monospace```) which you can see in pretty much any question we have, and we have our "more information popup" highlighting where we try to break out code segments into something more colorful so the page isn't a white block of text.

You can see that in our questions for ML4 in any of the ```.html``` files (minus ```question.html```).

**Comment by trombonekenny** [comment]
Closed by #992
