### ISSUE TITLE
Shib authUid is null error needs more user-friendly message

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1997]
At UBC it's possible that Shib logins happen with no attributes passed. That's not an error case but a service denial - the user hasn't been setup to release the data to PL.

We should soften up the error message so it still applies for UIUC but gives some hint on what to do next.

**Comment by mwest1066** [comment]
Are we currently catching that here? https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/authCallbackShib/authCallbackShib.js#L20

**Comment by trombonekenny** [comment]
Yeah that's right.

**Comment by tdy** [comment]
Is this as simple as changing the `'authUid is (null)'` string? What should be the new error message?

**Comment by mwest1066** [comment]
Good question -- I think something like "Your account is not registered for this service. Please contact your course instructor or IT support."
