### ISSUE TITLE
Multiple multiple choice

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#200]
cf `PrairieLearn/pl-cs421/questions/midterm1-envTracing-*`

**Comment by tnip** [comment]
Working on this in [tnip/PrairieLearn/tree/feature-multiTrueFalse](https://github.com/tnip/PrairieLearn/tree/feature-multiTrueFalse).

**Comment by mwest1066** [comment]
Implemented completely in v3.
