### ISSUE TITLE
Inbrowser editor failure on new course creation

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2006]
Starting from scratch (e.g. empty .git repo) one cannot use the in-browser editor to modify course configuration or create a new instance on production: https://prairielearn.engr.illinois.edu/

#### Modifying `infoCourse.json`

<img width="727" alt="Screen Shot 2020-01-27 at 3 16 07 PM" src="https://user-images.githubusercontent.com/833642/73214625-2f7d9000-4118-11ea-8b33-a5bc9ec6b58f.png">
<img width="727" alt="Screen Shot 2020-01-27 at 3 16 13 PM" src="https://user-images.githubusercontent.com/833642/73214626-2f7d9000-4118-11ea-8303-8454a6aee4aa.png">

-----

#### Modifying/creating a new `courseInstance`.

<img width="729" alt="Add courseInstance" src="https://user-images.githubusercontent.com/833642/73214586-1c6ac000-4118-11ea-87a8-ca542bba5643.png">
<img width="730" alt="Add courseInstance error" src="https://user-images.githubusercontent.com/833642/73214587-1c6ac000-4118-11ea-980d-c4583cf53808.png">

**Comment by trombonekenny** [comment]
That likely explains the two PL restarts around that time yesterday:

> Jan 27 21:14:52 ip-10-0-0-204 node: /PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg-pool/index.js:247
Jan 27 21:14:52 ip-10-0-0-204 node: throw new Error('Release called on client which has already been released to the pool.'
Jan 27 21:14:52 ip-10-0-0-204 node: ^
Jan 27 21:14:52 ip-10-0-0-204 node: Error: Release called on client which has already been released to the pool.
Jan 27 21:14:52 ip-10-0-0-204 node: at client.release (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg-
Jan 27 21:14:52 ip-10-0-0-204 node: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:384:13
Jan 27 21:14:52 ip-10-0-0-204 node: at Query.callback (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:22
Jan 27 21:14:52 ip-10-0-0-204 node: at Query.handleReadyForQuery (/PrairieLearn/node_modules/@prairielearn/prairielib/node_
Jan 27 21:14:52 ip-10-0-0-204 node: at Connection.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_mod
Jan 27 21:14:52 ip-10-0-0-204 node: at Connection.emit (events.js:223:5)
Jan 27 21:14:52 ip-10-0-0-204 node: at Connection.EventEmitter.emit (domain.js:475:20)
Jan 27 21:14:52 ip-10-0-0-204 node: at Socket.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules
Jan 27 21:14:52 ip-10-0-0-204 node: at Socket.emit (events.js:223:5)
Jan 27 21:14:52 ip-10-0-0-204 node: at Socket.EventEmitter.emit (domain.js:475:20)
Jan 27 21:14:52 ip-10-0-0-204 node: at addChunk (_stream_readable.js:309:12)
Jan 27 21:14:52 ip-10-0-0-204 node: at readableAddChunk (_stream_readable.js:290:11)
Jan 27 21:14:52 ip-10-0-0-204 node: at Socket.Readable.push (_stream_readable.js:224:10)
Jan 27 21:14:52 ip-10-0-0-204 node: at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by coatless** [comment]
@trombonekenny I think that might be something else. 

I triggered both errors around 3:13 pm. Log stamps are showing 21:14:52 -> 9:14 pm?

**Comment by trombonekenny** [comment]
No, it's the same. The server is on UTC time, -06 hours.
