### ISSUE TITLE
Documentation for question templates

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#201]
per craig's/matt's mention during the pl users meeting

**Comment by mwest1066** [comment]
I think I want to rework this feature to have a `questionDefaults` directory at the top level of the course directory, exactly mirroring the system-wide `backend/questionDefaults` directory. I think this results in cleaner code (templates tangle questions together, which can produce a mess).

**Comment by mwest1066** [comment]
Closing as WONTFIX because it’s a legacy v2 feature
