### ISSUE TITLE
Course element javascript fails on instructor question pages

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2012]
Course elements (e.g., in `pl-tam212/elements`) load client javascript from URLs of the form `/pl/course_instance/${course_instance.id}/elements/${file}`

This is done here: https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/freeform.js#L1048

If we are viewing a question at the course level then this fails because we don't have a `course_instance`.

**Comment by tbretl** [comment]
This looks fine. It would be nice to have some tests that make sure we don't break this in future.
