### ISSUE TITLE
Canvas LTI with PL

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2015]
From e-mail with @trombonekenny 

Under the **Canvas Pilot**, it would be great to be able to create an LTI-enable assessment with PrairieLearn.

**Canvas Pilot URL:** https://illinoisedu.instructure.com/

Right now, the LTI endpoint can't be reached. Alternatively, there may need to be additional parts added?

This is using PL's endpoint of:

<https://prairielearn.engr.illinois.edu/pl/lti>

### Workflow: 

Assignments (Menu) -> (+) Assignment -> Submission Type -> External Tool -> Paste PL URL -> Create

"Can't find valid settings for URL"

<img width="494" alt="Screen Shot 2020-01-31 at 11 34 19 AM" src="https://user-images.githubusercontent.com/833642/73560962-a919c480-441d-11ea-8a79-6d9c58458722.png">
<img width="524" alt="Screen Shot 2020-01-31 at 11 34 27 AM" src="https://user-images.githubusercontent.com/833642/73560963-a919c480-441d-11ea-88a7-fdef89f6fae8.png">

**Comment by coatless** [comment]
So, I have a temporary workaround by using PL's API to download data, merging with Canvas' gradebook, and pushing a grade release with Canvas' API.

Unfortunately, there isn't a simpler way as the LMS export for Canvas isn't just a (Username, Point) pairing unlike Compass2g. Ahh, the joy of being in a pilot.

<img width="898" alt="Screen Shot 2020-02-05 at 7 27 58 PM" src="https://user-images.githubusercontent.com/833642/73898134-f34fdb00-484d-11ea-8bcf-daec181c1d1d.png">
  

https://community.canvaslms.com/docs/DOC-16546-4152813649

**Comment by echuber2** [comment]
I hear that it works with Canvas now.

**Comment by coatless** [comment]
I had to migrate back over to Compass2g. So, I can't easily verify if there was a change associated with the LTI link.

**Comment by nwalters512** [comment]
For anyone landing here: we still intend to build out LTI 1.3 support, which will greatly improve compatibility with Canvas. This work will be planned and tracked in other issues.

**Comment by joelostblom** [comment]
@nwalters512 Could you point me to the issue(s) tracking grade export from PL to Canvas (similar to Gradescope, where there is a button for each quiz to sync grades back to canvas). Is it dependent only on this PR being merged https://github.com/PrairieLearn/PrairieLearn/pull/10605, or maybe also this issue being closed https://github.com/PrairieLearn/PrairieLearn/issues/10624? I also saw mention of a beta testing starting in Fall 2024 and would be interested in knowing more once there is info https://github.com/PrairieLearn/PrairieLearn/issues/4547#issuecomment-2258953585

**Comment by nwalters512** [comment]
@joelostblom #10605 will introduce grade syncing to Canvas via LTI 1.3. Even once that's merged and deployed, the feature will still be dependent on a) your institution working with us to set up the LTI link (we're working on this with UBC) and b) your institution enabling the PrairieLearn app in Canvas (we have no control over this). My generic advice would be to reach out to UBC's Canvas admins to track the status of this work and request the app once the integration is ready. If you have further questions for us at PL, I'd recommend reaching out on Slack or via email (support at prairielearn dot com).

**Comment by joelostblom** [comment]
Great, thank you! I'm at UBC so I will keep an eye on how it goes and reach out to the Canvas' admins here as needed.

**Comment by coatless** [comment]
Oi! It's @joelostblom 👋

**Comment by joelostblom** [comment]
Haha, hi there @coatless! Nice to see you here too =)
