### ISSUE TITLE
Logging file uploads upon actual success

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#202]
Will have example of that in `PrairieLearn/pl-cs421/questions/ml4-*/file-upload.js`

**Comment by mwest1066** [comment]
Can you explain more what this means?

**Comment by tnip** [comment]
Students should have a record of the file they've uploaded and the time that they've last uploaded. Given the level of customizability that exists in PL right now, it may not necessarily be the case that having students download their files to verify success is guaranteed. As such, there should be functionality in place to independently show to users what files they've uploaded, and at what time that was done.

**Comment by tnip** [comment]
I suppose to elaborate a bit more now that I have some spare cycles, what we do is listen for an AJAX response and take it for granted that if it was successful, the data was saved successfully. However, there should be a way to go, "I know non-empty data was submitted, and through a series of transformations which I may or may not want to do in server.js, I know non-empty data should be recorded."

**Comment by mwest1066** [comment]
I think this issue should be resolved by #295, but I'm leaving it open in case there is something else here that I'm missing.

**Comment by mwest1066** [comment]
Fixed in v3 file upload questions.
