### ISSUE TITLE
Disable `timeLimitMin` rule on Exam mode assessments

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2054]
Since `"mode": "Exam"` assessments have their timing managed by the CBTF and proctors, we should reconsider 1) if assessment time limits should apply in that environment, or 2) if we should try to make the visible time limits sourced from the scheduler instead of the assessment.

**Comment by mwest1066** [comment]
It would be great to pull time limits from PS. I think we now have all the proctor-level controls needed to extend time, so there is nothing stopping us from doing this.

**Comment by trombonekenny** [comment]
Bump. This keeps coming up with course support for the CBTF. We might want to implement this block, making it config toggleable, so it can be set later if issues escalate.

**Comment by mwest1066** [comment]
Two changes needed:
* [ ] Add a second CASE option like `WHEN aar.mode = 'Exam' THEN NULL` here: https://github.com/PrairieLearn/PrairieLearn/blob/4fb8e0c5f31f69cfce4b1a6271b63409d59d45cd/sprocs/check_assessment_access.sql#L44
* [ ] Add a documentation note near "Note that time limits should not be set for exams" to say that time limits will not activate in Exam mode: https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/accessControl.md
