### ISSUE TITLE
pl-string-input does not render answer as verbatim string

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2055]
pl-string-input uses the `<samp>` element to display the correct answer, which displays `a \\ b` as `a \ b`.

**Comment by zillesc** [comment]
Just to be clear, the way in Python that you print a backslash is print('\\') because the backslash needs to be escaped.  The current problem is that the pl-string-input collapses any number of slashes into a single slash.  I'm okay with '\\\\' being rendered as '\\' but not as '\'.

**Comment by mwest1066** [comment]
I think the correct solution is to use `<pre>` rather than `<samp>`, but we'll need to add some custom CSS to set `display: inline`.
