### ISSUE TITLE
GitHub API deprecation notice

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2073]
The @prairielearn1engr GitHub account got the following deprecation notice. I'm not sure what this is being triggered by.

> Hi @prairielearn1engr,
>
> On February 11th, 2020 at 14:00 (UTC) your personal access token (pl-bot repo access) using octokit/rest.js v15.7.0 was used as part of a query parameter to access an endpoint through the GitHub API:
>
> https://api.github.com/repositories/20046997/branches/master
>
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.
>
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
>
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
>
> Thanks,
> The GitHub Team

**Comment by mwest1066** [comment]
Turns out this is alma bot. We need to update `octokit` in it.

**Comment by nwalters512** [comment]
Old Alma is no longer around; long live new Alma!
