### ISSUE TITLE
Use email field for emails rather than UID

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2075]
(requested by @cheeren)

Some schools use a separate email address from the UID address (e.g., UBC) so we should switch to using `users.email` for all email links (and display this in more places, like an instructor-facing user page).

**Comment by jonatanschroeder** [comment]
Now that more instructors at UBC are using it, this is becoming a bit more important. Any chance this can be bumped in the priority queue?

**Comment by jonatanschroeder** [comment]
I believe this is resolved, closing. Please reopen if there's something pending.
