### ISSUE TITLE
Add LTI server config documentation

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2082]
Describe what needs to be added to `server.conf` to enable LTI tool provider in PrairieLearn.

Add the `hasLti` and `ltiRedirectUrl` configuration options to the serverConfig schemas. For bonus points, audit all the `lib/config.js` options to make sure they have matching schema statements and potentially enable strict schema checking on server load. (I'm surprised PL doesn't do this?)

Added from conversations with UCB.

**Comment by nwalters512** [comment]
LTI 1.1 is being deprecated. LTI 1.3 is the way to go in the future. We have basic documentation for that on https://prairielearn.readthedocs.io/en/latest/lti13/#placements, with more coming in https://github.com/PrairieLearn/PrairieLearn/pull/10518.
