### ISSUE TITLE
Allow resubmission of singleVariant question after scoring max points

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#2083]
This issue was raised by @mattoxb. Summarizing the issue briefly, comments from @trombonekenny:

> If a student gets 100% on a question, PL does not let them submit again. You can wrap the question in assessments that let them try it again (homeworks or multi-instances exams), but that's a new instance of the question.
>
> It's a design choice that I don't think has a toggle (if you're thinking of something in the info.json to enable submissions beyond 100%)

Another temporary workaround:

> I think locking something that has hand-graded components to <100% to enable multiple submissions even if they pass a check is OK as long as that's explained to the student.

Comments from @mwest1066:

> For questions that are marked as "singleVariant": true there is no way for students to continue to submit after they have completed the question.
>
> I'd be very happy to take a PR to add this functionality. I think it would be easy to add. We'd just need to enable the "Save & Grade" button for singleVariant questions even when the student has max points. The grading will be safe because we never decrease points in any case.

**Comment by mwest1066** [comment]
Note that this only applies to `"singleVariant": true` questions on `"type": "Homework"` assessments.

**Comment by mwest1066** [comment]
Actually, on `"type": "Homework"` assessments, questions marked as `"singleVariant": true` are can be retried without limit.

I think the original issue was referring to `singleVariant` questions on `Exam` assessments. But in that case, I think the correct behavior _is_ to block resubmissions after max points are scored. If the instructor does not want to award max points for a particular answer, they can simply change the grader to give less than 100%.

The original use-case was an instructor wanting to do a hand-grading of a programming question after the exam was over, but where the programming question also had an autograder that would give some proportion of the credit (and run in real-time during the exam). The solution in this case was to just make the autograder award 80% maximum (or something like this) by having a final test case that was worth 20% and always failed, called "20% of points will come from manual grading after the exam is over".
