### ISSUE TITLE
New version of matplotlib/sympy break sympy plotting

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2085]
With `matplotlib=3.0.2` and `sympy=1.3` we could use `sympy.plot_parametric()` to plot functions inside `server.py`.

With `matplotlib=3.1.2` and `sympy=1.5.1` we get the error:
```
/usr/local/lib/python3.6/site-packages/sympy/plotting/plot.py:1253: UserWarning: tight_layout : falling back to Agg renderer
  self.fig.tight_layout()
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/figure.py", line 433, in show
    manager = getattr(self.canvas, 'manager')
AttributeError: 'FigureCanvasAgg' object has no attribute 'manager'
```

**Comment by mwest1066** [comment]
@eliotwrobson would you mind checking to see whether this particular issue has been resolved?

**Comment by eliotwrobson** [comment]
@mwest1066 Running this on the latest image `sympy.plot_parametric()` works!

**Comment by nwalters512** [comment]
@eliotwrobson thanks for confirming! I'll close this 🚀

**Comment by mwest1066** [comment]
> @mwest1066 Running this on the latest image `sympy.plot_parametric()` works!

Thanks for checking!
