### ISSUE TITLE
fileEditorUseGit defaults to false

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2088]
(reported by @andrewstec)

It seems dangerous to default `fileEditorUseGit` to `false`. With this setting, file edits through the website will be immediately overwritten by syncs from GitHub, with no warning. This caught the UBC folks on a staging server they had set up.

@tbretl are you aware of any reasons to not default this to `true`?

**Comment by nwalters512** [comment]
@mwest1066 I think the main reason to _not_ set this to `true` is that folks doing local development would suddenly find their changes immediately pushed to GitHub, which might be unexpected. Maybe there's a compromise where we default `fileEditorUseGit: process.env.NODE_ENV === 'production'?`

**Comment by mwest1066** [comment]
I'm fine to leave this as `false`. I agree that we want it to be `false` in local dev and I'm not enthusiastic about having more variables magically changing their defaults based on `NODE_ENV`.
