### ISSUE TITLE
HTTP version doesn't redirect to HTTPS version

### ISSUE THREAD

**Issue by sayanb06** [PrairieLearn/PrairieLearn#2089]
When I go to http://prairielearn.engr.illinois.edu/, I get shown an old prairielearn version which doesn't use HTTPS (and doesn't redirect to it either). I get options to login through University of Illinois Login, Google Login, and INTL ID Login. When I click on University of Illinois Login, I get prompted for my UIUC credentials and then am thrown in a redirect loop with the prefix https://shibboleth.illinois.edu/idp/profile/SAML2/Redirect/SSO?... The Google login redirects me to the HTTPS version though. The same thing happens in incognito mode and when I delete all cookies.

**Comment by trombonekenny** [comment]
Thanks for the report. I've observed this too. We'll investigate and get it resolved. In the meantime, making sure you're using https:// should solve the Shibboleth infinite loop problem.

**Comment by mwest1066** [comment]
We used to redirect but I removed it when switching to LetsEncrypt, because the LE validation required a non-redirected HTTP first request. My immediate hacky fix was to completely disable the HTTP->HTTS redirect, but we should fix this properly by special-casing the LE request.

**Comment by mwest1066** [comment]
Fixed
