### ISSUE TITLE
Add v2/v3 type to Questions list

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2094]
Requested by @gcevans 

> Is there a way to search to see what questions are v3 or not in the PL interface?
> In the course questions I can filter by topic and tag but it would be nice to filter so as only to see v3 quesions.
> That is where I was looking since I was using that to sort though the huge catelog of questions in cs 225.

**Comment by nicknytko** [comment]
The question page currently looks like this:

![image](https://user-images.githubusercontent.com/1790491/75585632-2eea5900-5a38-11ea-9cb9-f09548025d39.png)

Where instructors can search through all questions for a course.  It would be nice to be able to filter between older (v2) and new (v3) questions.

**Comment by kevin88tu** [comment]
09/03/2020 - Kevin will be working on this

**Comment by mwest1066** [comment]
Merged in #2151
