### ISSUE TITLE
Changes "News" badge from red colour to something less scary

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#2097]
When new 'news' posts are added users get a red notification badge displaying how many posts are unread.  Red is a scary colour, lets change this to something nicer like blue.

**Comment by KaveeshaW** [comment]
I'll take this. I found what to change as well. Its under the navbar.ejs in the partials folder.

**Comment by nicknytko** [comment]
Hey!  I can help you create a pull request for this tomorrow.

**Comment by mwest1066** [comment]
Implemented in #2152
