### ISSUE TITLE
pl.to_json Object of type ndarray is not JSON serializable

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2099]
@tbretl Did something change since creating the https://github.com/PrairieLearn/pl-ece470/tree/master/questions/fromWedge question (see it live at https://prairielearn.engr.illinois.edu/pl/course/112/question/1244932/preview)? 

Trying to load it now gives an error:

`TypeError: Object of type 'ndarray' is not JSON serializable`

My guess is something about `pl.to_json()` used to work to serialize the data but now it doesn't (maybe with nested ndarrays)? Any insights?

**Comment by eliotwrobson** [comment]
It looks like this is no longer an issue? Can probably close this issue.
