### ISSUE TITLE
Course question externally graded errors: course_instance is not defined

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2142]
Under the new layout it's possible to run questions outside of a course instance (for example, go the Example Course course, Questions, and run the demoCodeEditorAutograded Fibonacci in-editor question where the menu at the top still says "Choose course instance..."

Submitting will cause an error with `pages/partials/submissionInfoModal.ejs` because `res.locals.course_instance` never gets set. It does this on docker and the production server.

The externally graded question code should get reviewed to be able to run without being under a course instance. This might also resolve #1100

**Comment by jonatanschroeder** [comment]
I believe this is resolved. Closing.
