### ISSUE TITLE
Allow instructors to re-enable (i.e. "unfinish") exams for students

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#215]

**Comment by mwest1066** [comment]
I agree that we should probably implement this, just to give instructors full control, but I hope no-one uses it very much.

I guess we'll need to add a new `RetryExamTestServer.unfinish()` method. This will need to change `tInstance.open` back to `true`, and make sure that all submissions have `submission._private` set to hide everything again as in `updateWithSubmission()` (except that `feedback` should not be private).

**Comment by mwest1066** [comment]
Implemented for v2 in 9fbc78a4c6e98e13ec3494df31ba14ac6cc7a6bc
