### ISSUE TITLE
Change "close all" issues to only close the visible ones

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2154]
On the Issues tab, the "Close all issues" button would be more useful it was "Close all visible issues", where we'd need to use the current filter to select what to close.

**Comment by cheeren** [comment]
Came here to request this exact thing.

**Comment by armandofox** [comment]
We could really use this as well, it's come up on a number of occasions at Cal.

**Comment by nwalters512** [comment]
For anyone subscribed to this issue, #9077 was just deployed, which includes this functionality!
