### ISSUE TITLE
Allow externally graded question to return status of not gradable

### ISSUE THREAD

**Issue by dowobeha** [PrairieLearn/PrairieLearn#2160]
Consider the following case:

- A student is working on a coding question (possibly in an exam setting)
- The student submits their code
- The code fails to compile

In this setting, there should be a mechanism whereby the question is not graded (in the same way that a blank submission is not graded).

**Comment by nicknytko** [comment]
to be incorporated into #1999

**Comment by coatless** [comment]
@nicknytko maybe unhook this from #1999. I'm worried about feature creep and getting another huge PR that sits in stasis for a long time.

**Comment by nicknytko** [comment]
true, I'll put this into its own PR since it sounds like @dowobeha would like this merged soon

**Comment by nicknytko** [comment]
with the reduced scope of #1999 hopefully this will get done soon™️ 🤞
