### ISSUE TITLE
Enable hiding of Correct Answer panel

### ISSUE THREAD

**Issue by dowobeha** [PrairieLearn/PrairieLearn#2161]
There are times where it doesn't make sense to show an answer panel. It would be nice to allow questions to be configured such that this is hidden.

**Comment by echuber2** [comment]
I think this is a duplicate of https://github.com/PrairieLearn/PrairieLearn/issues/623

**Comment by nicknytko** [comment]
This looks like a duplicate, closing in favour of #623.
