### ISSUE TITLE
Snipping File Contents in Log

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#2168]
We should trim the "_files" "contents" output in the log for file upload questions.  (The one where you go to see student submissions, when they generated a variant, etc.)

Some of the files students upload are rather large, and looking through the log entails scrolling through pages of meaningless letters.  We could instead just display some or none of it and then put a [snipped].  We could have a "show remainder" link people could click if they wanted to see the rest.

**Comment by bowmnath** [comment]
Matt suggested that it might be possible to do this largely with CSS.

https://getbootstrap.com/docs/4.4/utilities/text/#text-wrapping-and-overflow

https://caniuse.com/#feat=css-line-clamp

Or it might be possible to just truncate it in the EJS template.

**Comment by mwest1066** [comment]
I actually think that doing it in the EJS template is probably best. Just detect long entries and put a truncated value into the HTML, with a "show more" link like:

```
<a data-toggle="collapse" href="#entry23892" role="button">show more</a>
<div class="collapse" id="entry23892">
   ... rest of the truncated entry goes here...
</div>
```

See https://getbootstrap.com/docs/4.4/components/collapse/
