### ISSUE TITLE
Rename 'Freeform' to 'v3' inside the code

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2174]
From @mwest1066 on Slack:

> Everything that instructors see calls it v3, but inside the code it’s called Freeform. This is just left-over code from a partial rename long ago.

**Comment by tdy** [comment]
More from @mwest1066:

> It's also in the DB, so it will require a migration. Specifically, the enum_question_type needs to be changed: https://github.com/PrairieLearn/PrairieLearn/blob/master/database/enums/enum_question_type.pg
>  
> Other that that, mainly it should be a search&replace
