### ISSUE TITLE
Allow hiding of completed questions during exams

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2175]
Add a feature so that, once a student has exhausted their attempts on a question, they can't view it anymore.

Requested by @gchallen and @cheeren

**Comment by mwest1066** [comment]
Actually, when a question is not yet correct and attempts remain, display as normal. But when the question is correct (or when attempts are exhausted?) don't display anything except the final score.

**Comment by nwalters512** [comment]
What's the value in this option? That is, when would we document that someone would benefit from turning this on?

**Comment by mwest1066** [comment]
This feature hasn't been requested by anyone since the original issue was opened so I think we should close this issue.

**Comment by gchallen** [comment]
Fine by me. I have no memory of requesting this :smile:.
