### ISSUE TITLE
Add "save-only-no-grade" feature for exam questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2179]
Requested by @lkwagner and @PrairieLearn/pl-cs233 

This should remove the "Save&Grade" button from questions and only permit saving.

**Comment by trombonekenny** [comment]
At the per question level, isn't that essentially `gradingMethod: Manual`?

**Comment by mwest1066** [comment]
Yep, it will do the same thing, but without the message. And it will be a flag at the assessment level, so you can use your regular questions but force them to all to disallow grading. If I remember, I should also make it check that you don't have any points for partial credit with repeated submissions.
