### ISSUE TITLE
Add "don't display the student score under any circumstances" feature for assessments

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2181]
Requested by @cheeren and @lkwagner.

This should replicate the experience of a pen-and-paper exam, where you answer all the questions (saving answers as many times as you want) but it's graded later by the professor.

**Comment by ataraxie** [comment]
I would like to vote for this feature. In our class we have some manual grading components for our exams and the percentage shown too students is very misleading.

**Comment by jyoo980** [comment]
Also want to chime in here.

This would be a great feature to have, would effectively resolve another issue I opened a few months ago #2688

**Comment by ataraxie** [comment]
Thank you so much for implementing this @mwest1066 and @falkirks !

@jyoo980 look, they implemented it!!
