### ISSUE TITLE
Incorrect path constructed by PrairieDraw:drawImage

### ISSUE THREAD

**Issue by zillesc** [PrairieLearn/PrairieLearn#221]
Calls to PrairieDraw:drawImage do not include 'backend/' in the path.  In the cs233 installation, if I do:

``` javascript
this.pd.drawImage("clientFiles/foo.png", ...
```

it generates the url: https://prairielearn.engr.illinois.edu/cs233/clientFiles/foo.png
but it should generate the url: https://prairielearn.engr.illinois.edu/backend/cs233/clientFiles/foo.png

The workaround that I did in 'questions/digital_logic/client.js' was to do the following:

``` javascript
this.pd.drawImage("../backend/cs233/clientFiles/foo.png", ...
```

if/when you fix this, I'll need to update my code, so let's do this in concert.

**Comment by mwest1066** [comment]
Closing this as PrairieDraw is now deprecated.
