### ISSUE TITLE
Errors in elementElementCodeDocumentation example question

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2210]
Some elements seem to be behaving badly when dealing with incomplete (invalid) data. Steps to reproduce:

1. Go to the `elementElementCodeDocumentation` question in the exampleCourse (XC 101).

2. Choose an answer for the first multiple choice question, but leave all of the other ones blank.

3. Click "Save & Grade".

4. There will be errors thrown by some element on the page.

**Comment by coatless** [comment]
Probably should split this question down instead of creating a mega question. 
Likely required anyway for #1843
