### ISSUE TITLE
allowRealTimeGrading:false rejects questions with length-1 points arrays

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2211]
When we sync an assessment with `"allowRealTimeGrading": false`, we check to make sure it doesn't contain questions with arrays of points for multiple attempts, like this:
```
"points": [10, 8, 6, 4]
```

We currently check for this by insisting that `points` should be a scalar (non-array) value, like `"points": 10`. But some instructors are leaving the brackets, like `"points": [10]`, and are confused about why this also triggers an error.

We should fix this by allowing a length-1 array as well, and improve the error message to only talk about arrays with more than one points value (or something like that).

**Comment by echau01** [comment]
I can work on this.
