### ISSUE TITLE
Remaining time does not consider endDate

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2217]
When using a timed exam, at the moment the remaining time does not take the allowAccess endDate into consideration. For example, if a student is taking an exam with `timeLimitMin = 50` in a 1-hour window, if they start the exam 30 minutes late then they will in fact only have 30 minutes to work on it, but the countdown timer will show them the full 50 minutes.

When we compute the remaining time to send to the client, we should limit it to be no longer than the time until the endDate (if any) of the current access rule.

**Comment by mwest1066** [comment]
Note that we are referencing this issue in `doc/remoteExams.md` so we should delete that reference when we fix this.

**Comment by tdy** [comment]
Can this be handled via `countdown.ejs` or does it go even deeper?

**Comment by mwest1066** [comment]
> Can this be handled via `countdown.ejs` or does it go even deeper?

I think the necessary changes are all server-side.

The way the countdown timer works is that when the student starts an exam we use `time_limit_min` to compute the `date_limit` and store it as `assessment_instances.date_limit`:

https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/studentAssessmentExam/studentAssessmentExam.js#L36
https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/assessment.js#L80
https://github.com/PrairieLearn/PrairieLearn/blob/master/sprocs/assessment_instances_insert.sql#L47

Whenever the student accesses the assessment, we check `date_limit` and if it is not NULL then we use it to compute `assessment_instance_time_limit_ms` to send to the client (this is what `countdown.ejs` uses to count down). The calculation of `assessment_instance_time_limit_ms` happens here:

https://github.com/PrairieLearn/PrairieLearn/blob/master/middlewares/selectAndAuthzAssessmentInstance.sql#L17

To fix the current issue, it seems to me that we could either:

1. Take `end_date` into account when we initially compute `date_limit`. The most straightforward way to do this would probably be to compute `time_limit_min` by limiting it to the `end_date` when we first read it from the DB: https://github.com/PrairieLearn/PrairieLearn/blob/master/sprocs/check_assessment_access.sql#L41

This change would have the advantage that when a student goes to the exam page and they see the message saying "you have XX minutes", the "XX" would correctly reflect the time until `end_date`. A disadvantage of this change would be that the instructor could not give the student more time on the exam by editing the `endDate`. We'd need to implement #2293 to add this.

2. Alternatively, we could leave `date_limit` as it is, and change the calculation of `assessment_instance_time_limit_ms` to reflect `end_date`. This would have advantage that if an instructor realized their `endDate` was too soon, they could just extend it and everything would be ok. The disadvantage of this is that we aren't directly storing the time limit in one single place, so fixing #2149 would be more complex.

I guess I feel like option (1) above is the way to go. And clearly it would be good to also fix #2149 and implement #2293 😄 

One more thing to consider is that there will be a race condition for exams with a time limit that expires exactly at the `end_date`. The "finish exam" event will auto-finish the exam at the time limit, but if this is just after the `end_date` then we will block access and the exam will not actually be closed and the student won't see their final score. One way to handle this (without fixing the underlying race condition) would be to set the time limit to 30 seconds less than the `end_date`, or something like that.
