### ISSUE TITLE
demoCodeEditorAutograded question fails without course instance

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2230]
Steps to reproduce:

1. From the main PrairieLearn page, click on the "XC 101" course (NOT the Sp15 course instance of XC 101, but just the course itself).

2. Click on "Questions" in the navbar.

3. Click on "Demo: Fibonacci function, in-browser editor, external grading"

4. Edit the code to replace "pass" with "return 1"

5. Click "Save & Grade"

6. An error is reported:

```
/PrairieLearn/pages/instructorQuestionPreview/instructorQuestionPreview.ejs:26 24| <div class="row"> 25| <div class="col-lg-9 col-sm-12"> >> 26| <%- include('../partials/question', {question_context: 'instructor'}); %> 27| </div> 28| 29| <div class="col-lg-3 col-sm-12"> /PrairieLearn/pages/partials/question.ejs:151 149| <% if (showSubmissions) { %> 150| <% submissions.forEach(function(submission, idx) { %> >> 151| <%- include('submission', {submission: submission, submissionCount: submissions.length, submissionIdx: submissions.length - idx, submissionHtml: submissionHtmls[idx]}); %> 152| <% }); %> 153| <% } %> 154| /PrairieLearn/pages/partials/submission.ejs:30 28| </div> 29| >> 30| <%- include('submissionInfoModal', {submission: submission}); %> 31| </div> 32| 33| <script> /PrairieLearn/pages/partials/submissionInfoModal.ejs:58 56| <span style="display: inline-block; width: <%- submission.grading_job_stats.phases[4] %>%; height: 10px;" class="bg-danger m-0"></span> 57| </div> >> 58| <% if (course_instance) { %> 59| <a class="btn btn-primary mt-2" href="<%= plainUrlPrefix %>/course_instance/<%= course_instance.id %>/instructor/grading_job/<%= submission.grading_job_id %>">View grading job <%= submission.grading_job_id %></a> 60| <% } else { %> 61| <a class="btn btn-primary mt-2" href="<%= urlPrefix %>/grading_job/<%= submission.grading_job_id %>">View grading job <%= submission.grading_job_id %></a> course_instance is not defined
```

**Comment by mwest1066** [comment]
Note the real error is right at the end of the error message: `course_instance is not defined`

This question works just fine if there is an active course instance (e.g., if you are in Sp15 for XC 101).

**Comment by mwest1066** [comment]
Seems to be a dup of #2142 and maybe #1100

**Comment by trombonekenny** [comment]
As of 7/16 this seems resolved, as running the example course externally graded question outside of a course instance doesn't fail.

However, if you click the info (i) button in the submission result, which gives timing stats and a "View grading job <job_number>" button, which in my test linked too https://prairielearn.engr.illinois.edu/pl/course/108/grading_job/29767680  That route returns a Not Found.

We need to plumb a route for grading_job under a course and not just a course instance and make it sure it works without CI info. https://github.com/PrairieLearn/PrairieLearn/blob/e3e37b4f20c31a3da3ead3bcc7ee862624810ff8/server.js#L433

**Comment by nwalters512** [comment]
None of the issues describe here remain.
