### ISSUE TITLE
Disable grade button on click, also for externally-graded questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2234]
This was implemented in #2187 but it turns out that it broke repeated submissions to externally-graded questions. I reverted that change in #2233. It would be great to re-do #2187 while taking externally-graded questions into account.

Externally-graded questions are different in that they still do a form-submit and page-reload to submit the answers, but because they are not yet graded they use websockets to update the grading information after page load. Something about this (the ungraded status? websocket updates?) seems to interact badly with the logic we were using to prevent double-clicks on the Grade button.

**Comment by echuber2** [comment]
I made a suggestion on the thread at https://github.com/PrairieLearn/PrairieLearn/pull/2187 but maybe it's more complicated than I think.

**Comment by tdy** [comment]
When I circle back to this, I think I'll start off by just writing the disable script (or your timeout suggestion) from scratch instead of copying the v2 script. I didn't totally understand what they were doing in the v2 script, but I just went with it since it seemed to work at the time.

**Comment by mwest1066** [comment]
Sounds good, I'm completely in favor of having a clean re-implementation.

**Comment by tdy** [comment]
Update: Disabling via `onsubmit` also prevents its `value` from being posted (thus `unknown __action: undefined` -- also confirmed via google), so that explains why the v2 script clones a new button.

**Comment by mwest1066** [comment]
> Update: Disabling via `onsubmit` also prevents its `value` from being posted (thus `unknown __action: undefined` when I tried it -- also confirmed via google), so that explains why the v2 script clones a new button.

Oh, interesting! Good to know there was some method behind the madness there 😄
