### ISSUE TITLE
Consider renaming "mode": "Exam" to "location": "CBTF"

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2247]
We use `Exam` both in `"mode": "Exam"` and `"type": "Exam"`, which is very confusing.

"Mode" is also just weird, because it really refers to IP-based location restrictions.

We should introduce new, better names for "mode" and silently continue to support the old names.

**Comment by coatless** [comment]
This. 💯 two years ago.

**Comment by tdy** [comment]
Followup question, what is SEB mode?

**Comment by coatless** [comment]
@tdy SEB is Safe Exam Browser mode. @trombonekenny wrote that feature :) 
https://safeexambrowser.org/news_en.html

**Comment by nwalters512** [comment]
As of https://github.com/PrairieLearn/PrairieLearn/pull/10505, we've started phasing out the notion of assessment access mode entirely.
