### ISSUE TITLE
Add remote exam doc example with real-time grading disabled

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2249]
`allowRealTimeGrading = false` and `showClosedAssessments = false` and timed exams

**Comment by tdy** [comment]
So this just means describing exam02 at [remoteExams.md](https://prairielearn.readthedocs.io/en/latest/remoteExams/)? And if so, we would be documenting exam02 in its MC-only form (#2286)?

**Comment by mwest1066** [comment]
Yep. And adding a note that disabling real-time grading means that students are unable to re-attempt questions, so this is best used only with multiple-choice questions. Disabling real-time grading with more complex questions (even just numeric-answer questions) is not recommended, because it's hard for students to get numeric answers exactly correct on the first attempt.
