### ISSUE TITLE
Create a Mechanism for Group Work

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#2251]
It would be nice if somehow two students could be tied to the same assessment instance so that they could both submit answers and shared a grade.

My use case: Students work on their projects in pairs.  Their project grades are exam-style -- they go down with every wrong submission.  So, I tell them only one student is allowed to submit so they don't circumvent this.  This has three downsides: 1) only one of them can submit, 2) I need to manually verify that they didn't split their submissions to avoid a grade decrease, 3) I need to verify who partnered with who on every project and manually copy their grades over.

This would likely require changes to the database and checks for race conditions.  Also, we would need some way for students to join a team for an assessment, and possibly assessment controls that force a minimum and maximum team size, and maybe prevent students from opening the assessment until they have their team ready.

**Comment by mfsilva22** [comment]
Here is the current work related to this request:

(1) implement a table database that maps students into groups
(2) create different options of how students are assigned to groups:
     a) instructors upload the groups with corresponding students;
     b) PL automatically assigns students to groups at random; 
    c) students assign themselves to groups.

The initial plan was to finish item (1) and (2a) this Spring semester (or possibly end of the Summer).
