### ISSUE TITLE
DB migration failing silently

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#2252]
On 6ed3f257ec5ed663504d47cfb23d2e0e33f37d7b, migration `166_assessments__require_honor_code__add.sql` doesn't get applied and doesn't give any errors:
```
$ docker run -it --rm -p 3000:3000 -v /c/Users/Tim/PL/PrairieLearn:/PrairieLearn prairielearn/prairielearn
info: PrairieLearn server start
info: Not using Redis for message passing
info: External grader running locally
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000/pl
```
Load from Disk then produces:
> Error message: error: column "require_honor_code" of relation "assessments" does not exist

(Stack track: [2228#issuecomment-604489205](https://github.com/PrairieLearn/PrairieLearn/pull/2228#issuecomment-604489205))

**Comment by trombonekenny** [comment]
Works for me?

**Comment by tdy** [comment]
Just to document the timeline before I forget:

* At the time, the latest migration on 6ed3f257ec was 165, so I named mine 166
* Migration 166 was not being applied and kept giving the "column does not exist" error
* Pushed to github to get code review since I couldn't figure out what was wrong
* Travis failed because 166 existed on `master`
* I renamed to 167 and pushed
* Migration 167 succeeded both locally and with Travis

After screensharing with @mwest1066:

* Locally renamed my migration from 167 back to 166 -> migration not applied (silent failure)
* Renamed to 167 -> migration applied
* Renamed to 166 -> migration not applied again

**Comment by nwalters512** [comment]
We haven't seen issues with migrations in over three years. In #6129, we changed our migration files to use timestamps instead of indexes, which will hopefully prevent similar issues from occurring again.
