### ISSUE TITLE
Unknown __action errors with blank __action

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2255]
We have many errors in the logs that look like `unknown __action` where `__action=""`.

For example:

```
Error: unknown __action:
at /PrairieLearn/pages/studentInstanceQuestionHomework/studentInstanceQuestionHomework.js:89:20

"referrer": "https://prairielearn.engr.illinois.edu/pl/course_instance/51965/instance_question/81008826/"

"body":{"__csrf_token":"REDACTED","postData":"","__action":""}
```

The `postData` input is defined here: https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/partials/questionFooter.ejs#L84

The location in `questionFooter.ejs` indicates that this is a v2 question.

It turns out that all of the errors of this type are from v2 questions.

**Comment by mwest1066** [comment]
There are also some errors that look like `unknown __action: undefined`. These are from v3 questions, but they are all from CS 105.

**Comment by echuber2** [comment]
I'm wondering if this could also be caused by a course using LTI, since the LTI vs. vanilla PL session management has been known to have other issues.

**Comment by nwalters512** [comment]
We haven't heard any reports of this recently, so I'm going to close this issue. If anyone can reproduce, I'm happy to reopen.

**Comment by echuber2** [comment]
Anecdotally, I thought some CS 421 students had encountered this with legacy v2 questions still this past fall, but the course staff would have to confirm.
