### ISSUE TITLE
Same random answer when more than one multiple choice part

### ISSUE THREAD

**Issue by ePotential** [PrairieLearn/PrairieLearn#2258]
If you make a question that has more than one multiple choice part, and each part has the same number of choices, then the randomly chosen answer will be the same for each part. For instance, say you have two multiple choice parts with 4 possible choices each. If the first part chooses (a) to be the correct answer, then the second part will also choose (a) to be the correct answer.

**Comment by ePotential** [comment]
This is also an issue with having multiple checkboxes.

**Comment by nicknytko** [comment]
This looks like it happens because the randomization is tied to the variant &mdash; each element will randomize the order in the same way.  This is probably an easy fix by just re-seeding inside the element.

**Comment by mwest1066** [comment]
It looks like we are re-seeding the PRNG on every Python function call: https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/python-caller-trampoline.py#L73

That is, we are re-seeding _inside_ the function-call loop: https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/python-caller-trampoline.py#L46

Instead, we should re-seed when we enter the `worker_loop()`: https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/python-caller-trampoline.py#L42

We call `worker_loop()` every time we are going to run a phase (e.g., the `generate` phase). The inner loop (`while True`) processes all the different elements within the phase.

**Comment by nicknytko** [comment]
Yes, in any case this should still be an easy fix :slightly_smiling_face:
