### ISSUE TITLE
Allow grade() to modify data["params"]

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2259]
We already have code in place to update the `params` and `true_answer` after running internal grading code: https://github.com/PrairieLearn/PrairieLearn/blob/master/sprocs/grading_jobs_insert_internal.sql#L75

But we block `params` modification: https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/freeform.js#L364

**Comment by eliotwrobson** [comment]
@mwest1066 It looks like `grade()` is allowed to modify params now: https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/src/question-servers/freeform.js#L483

It appears the docs are out of date however...
