### ISSUE TITLE
Change server.py test() to take a test_type parameter

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2269]
At the moment the `test()` function in `server.py` (and in elements) is supposed generate a testing submission and the expected parsing and grading result for that submission. PL uses this by calling `test()`, then taking the returned submission and running it through `parse()` and `grade()` to make sure that the result is as expected.

As an example: https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-number-input/pl-number-input.py#L376

`test()` should fill in `raw_submitted_answers` (not `submitted_answers`), `format_errors`, `partial_scores`, and `score` (only for `server.py`, not for elements?).

We want to test the handling of three types of submissions: correct, incorrect, and invalid. At the moment we do this by having each `test()` function randomly decide which of these it's going to generate. This is bad because PL can't ensure that it's tested one submission of each type.

To fix this, we should change `test()` to accept a `test_type` parameter with a value of `correct`, `incorrect`, or `invalid`, and it should generate a submission with this type. This will require changing all elements that currently have `test()` functions.

We can then also change `startTestQuestion()` in `lib/question.js` to always iterate through a cycle of correct/incorrect/invalid submissions.

See also #1214 and #1700

**Comment by nicknytko** [comment]
Do we also want to test each permutation of `correct`, `incorrect`, `invalid` for individual elements?  For example if we have a question with 3 input elements should we run $3^3=27$ tests?  Elements are largely independent of one another, though, so I could see this being unnecessary.

**Comment by mwest1066** [comment]
I think just three tests for each question are enough (all elements get the same test type).

**Comment by nicknytko** [comment]
Fantastic, that's way less complicated.
