### ISSUE TITLE
Convert exam02 into scantron style

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#2286]
One issue with throwing `"requireHonorCode": false` into exam02-realTimeGradingDisabled is that there's no logical connection between real-time grading and honor codes.

For example, yesterday @astrosticks was wondering if there was a bug in my honor code PR, until we figured out he had used exam02 as his template (in which we've disabled the honor code). I suspect this will continue to happen whenever someone uses exam02 as their template.

Should we create an exam03 demo'ing `"multipleInstances": true, "requireHonorCode": false`? These seem logically related (practice exam with honor code disabled), and the name would make it clear what the demo exam was actually showing. Maybe `exam03-honorCodeDisabledPracticeExam` or `exam03-honorCodeDisabledMultipleInstances`?

Alternatively, find a way to make it clear to new users that exam02 also has honor code explicitly disabled.

Thoughts?

**Comment by astrosticks** [comment]
Makes a lot of sense. Would be nice to have a demo exam with multipleInstances by default, too. Would have saved me a lot of stashing while I was developing features related to it.

**Comment by tdy** [comment]
This is probably going to be irrelevant after Mariana revamps `exampleCourse` (if I understood the convo between @mfsilva22 and @mwest1066 earlier). Feel free to close if so.

**Comment by mwest1066** [comment]
This is definitely a very bad/confusing exam - my apologies! 😄 

It might be nice to convert this to a "traditional MC exam" example. That is, MC questions only, no real-time grading, etc. Basically the closest we can do to emulating a scantron exam.

**Comment by tdy** [comment]
But I was the one who threw `requireHonorCode` into exam02 😆 

Anyway just to clarify, this new scantron demo should not set `"requireHonorCode": false`, right?

**Comment by mwest1066** [comment]
Right. I think we want these exams to be good templates for people to copy, and we don't want people to turn off the honor code! 😄
