### ISSUE TITLE
Add instructor button to extend timeLimitMin for in-progress exams

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2293]
At the moment, once an exam is started with a time limit there is no way for the instructor to change the active timer. It would be great to add both per-instance buttons and a for-all-students button to add (or subtract) time.

The current time limit is stored in `instance_questions.date_limit`, so we need to add to that value (presumably only for open exams? or do we re-open closed ones and also give them more time).

See also #611, #2275

**Comment by mwest1066** [comment]
We've already had two cases where people urgently needed this for remote exams. Once was due to server issues where all students were given extra time, and once was due to misconfigured DRES exceptions where one student needed extra time. We handled both of these by live DB edits during the exam, which is clearly not optimal 😄

**Comment by tdy** [comment]
Given #2405, does this `+Time` button just call a sproc that increments `date_limit`? I have a feeling it's more complicated since it's `diff:medium`.

**Comment by mwest1066** [comment]
> Given #2405, does this `+Time` button just call a sproc that increments `date_limit`? I have a feeling it's more complicated since it's `diff:medium` (or I'm not appreciating all the nitty gritty details yet 😆).

That's basically it. Maybe it doesn't deserve a "diff:medium" tag 😄 

One thing to consider is DRES (extended time) students. If everyone gets 10 minutes extra, I guess they should get 15 min if they are on 1.5x time? So maybe we should do percentage changes? Extra 10% time? Or maybe this is just overthinking things.

**Comment by mwest1066** [comment]
Note that #2506 will need to be fixed for this PR. Maybe that elevates it back to "medium" difficulty!

**Comment by cheeren** [comment]
I've been thinking about this a bit... I'm a little worried about the fact that these kinds of changes allow for inconsistent state between the database and the infoAssessment.json.  In principle, I don't mind thinking of the .json as the starting point, and changes that happen via UI as a sort of transaction on top of that, BUT it gets messy when we start admitting the possibility of changing the .json file during the assessment period. What happens, for example, if an instructor extends time on a live exam, but then also adds and access rule that both opens and closes within that extended window? 

It's a minor behavioral point, but I now consider the json to be a record of the assessment timeline, and making changes via the UI will make that view on the timeline not quite accurate.

**Comment by mwest1066** [comment]
> I've been thinking about this a bit... I'm a little worried about the fact that these kinds of changes allow for inconsistent state between the database and the infoAssessment.json. In principle, I don't mind thinking of the .json as the starting point, and changes that happen via UI as a sort of transaction on top of that, BUT it gets messy when we start admitting the possibility of changing the .json file during the assessment period. What happens, for example, if an instructor extends time on a live exam, but then also adds and access rule that both opens and closes within that extended window?

I agree that there is a lot of room for confusion between what's in JSON and what's in the DB. One general principle that we've tried to follow in PL is that all student-specific data is only in the DB (e.g., enrollments, scores, etc). We violated this principle with UID lists in access rules, and I wonder whether that is driving some of this confusion? I wonder whether separating out the "generic access" (in JSON) from "exceptional access" (only in the DB) might help here? See #3342 

> It's a minor behavioral point, but I now consider the json to be a record of the assessment timeline, and making changes via the UI will make that view on the timeline not quite accurate.

I think that the JSON is already not an accurate record of what actually happened, given the fact that it might have been edited during the assessment. The consequences of editing access rules while an assessment is live can be complicated! Perhaps we should be adding pages to more clearly show the actual recorded timeline? Like the per-student logs that we have now, but maybe for the whole class?
