### ISSUE TITLE
"Edit in new tab" button for in-browser file editing

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2340]
When viewing a file list in the browser, it would be great to add a button to the set of actions to allow the user to "Edit in new tab". This might encourage people to use multiple browser tabs for file editing, rather than clicking back and forwards between files.

See #2339

**Comment by nwalters512** [comment]
Is there a reason to not rely on native browser functionality (e.g. Command-click) for this?

Re: the "clicking back and forth" problem, we're probably better off adding some kind of side-by-side editor/preview layout.

**Comment by mwest1066** [comment]
I agree that some kind of side-by-side editor/preview is really the right way to deal with this.
