### ISSUE TITLE
JSON editor in browser

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2341]
Should we consider the use of a JSON editor for in-browser editing of JSON files? Examples:

1. https://github.com/json-editor/json-editor
2. https://github.com/josdejong/jsoneditor

These can be driven by JSON Schema so they only allow the creation of correctly-structured JSON.

An alternative would be embedding Visual Studio Code for general editing, which has JSON editing modes driven by JSON Schema to give hints.

**Comment by nwalters512** [comment]
We're taking a different approach and building bespoke editors for each JSON file that we want to be easily editable from the browser.
