### ISSUE TITLE
Element inputs should have autocomplete="off"

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2344]
All answer inputs should have `autocomplete="off"` to stop them suggesting previous values.

See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by eliotwrobson** [comment]
This has now been implemented for all of the most commonly used input elements. Follow-up issues will be created for refactoring elements that are not as actively maintained.
