### ISSUE TITLE
Duplicate copies of highlight.js

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2348]
`pl-code` uses a downloaded copy of `highlight.js` in `public/javascripts` (see comments in `pl-code.py`), while `pages/instructorFileBrowser` uses `node_modules/highlight`. It's not clear to me why this is the case, or whether we can delete one copy (preferably the `javascripts` copy).

If we do delete the copy in `public/javascripts` we should be careful to add a back-compat route to serve the `node_modules` version on the old path, for the sake of any questions importing it directly. Also note that we'll need to override this in Apache for prod.

**Comment by nicknytko** [comment]
It seems the version in `public/javascripts` contains all languages pre-packaged in one javascript file, while the version in `node_modules` requires languages to be loaded via separate javascript files.  Do you think we should give dynamically loading these language files a try?

**Comment by mwest1066** [comment]
How does the dynamic loading work? Do we need to do anything or does `highlight` figure out which one to load and take care of it all? Assuming so, that sounds much better, because we get to use the updated `node_modules` version and we also don't ship every client a huge set of languages when they just want one.

**Comment by nicknytko** [comment]
We'd need to `import` or `require` (whatever module loader is being used) all the languages manually, which I'm worried could break backwards compatibility.

**Comment by mwest1066** [comment]
Ah, ok, I get it. In `instructorFileBrowser` we are doing server-side highlighting using `highlight.js`, but in `pl-code` we can't do this because we are running in Python. We thus do highlighting client-side. Yuck!

Can you think of a good reason why we don't use Pygments in pl-code?

**Comment by nicknytko** [comment]
I’m totally in favor of using Pygments here, I’ve used it before in the python autograder and it works great.

**Comment by mwest1066** [comment]
If you switch pl-code to Pygments then we can probably delete `/javascripts/highlight`, which would be great! One less thing that slowly bitrots.
