### ISSUE TITLE
Separator symbols in instructor navbar don't clearly communicate what they are

### ISSUE THREAD

**Issue by astrosticks** [PrairieLearn/PrairieLearn#2350]
Update: See https://github.com/PrairieLearn/PrairieLearn/pull/2390#issuecomment-615564050
___

This leads to some confusing wrapping on thin screens: 

![image](https://user-images.githubusercontent.com/32315760/78510904-3e0ea600-775e-11ea-97f9-40c19980ee01.png)

**Comment by astrosticks** [comment]
Apparently, these circles are actually separators, not identifiers: https://github.com/PrairieLearn/PrairieLearn/pull/2390#issuecomment-615564050

**Comment by echuber2** [comment]
I agree that the circle symbols have unclear meaning. I would recommend changing them to a smaller bullet point, a dash, or a slash "/".

Using slash would go along well with one suggestion I made: https://github.com/PrairieLearn/PrairieLearn/issues/2391
