### ISSUE TITLE
`pl-matrix-component` cells are unaligned

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#2352]
Screenshot:

<img width="419" alt="Screen Shot 2020-04-06 at 11 00 03 AM" src="https://user-images.githubusercontent.com/1790491/78578943-d6a43500-77f5-11ea-8357-027caf99a117.png">

I am guessing with the recent changes to add padding to tables we missed that the matrices should not be padded.

**Comment by mwest1066** [comment]
Oh yuck!! 😱
