### ISSUE TITLE
Support questions folder nesting

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2360]
Instead of requiring all the questions in a single folder, allow subfolders under `questions` which get scanned on sync. Put the full relative path into `QID`

**Comment by nicknytko** [comment]
Bump, is this being actively worked on @tdy?  I'd actually love this feature for one of my courses.

**Comment by cheeren** [comment]
I'd really love this, too!! My question directories are such a nightmare...

**Comment by tdy** [comment]
Unfortunately haven't had a chance to get to it yet, but still on the to-do. @nicknytko are you asking to take over the issue (feel free) or just checking the status?

**Comment by nicknytko** [comment]
Mostly just asking about the status, though if you're busy with other things I can take a crack at this

**Comment by nicknytko** [comment]
@tdy I can take this over if you're not working on it

**Comment by tdy** [comment]
@nicknykto sure
