### ISSUE TITLE
Sticky headers in grade book page

### ISSUE THREAD

**Issue by aigagror** [PrairieLearn/PrairieLearn#2365]
Please make the headers sticky in the grade book page. It's currently really hard to see which column refers to which with such a big table.

Here is an example with names censored:
<img width="1362" alt="Screen Shot 2020-04-08 at 10 22 37 AM" src="https://user-images.githubusercontent.com/19999715/78802209-2cf2ae80-7983-11ea-9a02-eae42c2b5bda.png">

**Comment by trombonekenny** [comment]
Hi Eddie, thanks for the feedback. We already have this enhancement under development under #2103 and have a student team working on it - although I'm not sure the current status of that development. Let's close this issue and track the work on the other one, OK?
