### ISSUE TITLE
Add Sync Button to Main UI

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#2370]
About 95% of the time I'm going to PL it's just to sync my course. It would be great if there was a sync option on the main landing page. There seems like there is room in the current UI:

![image](https://user-images.githubusercontent.com/445443/78939074-12026600-7a79-11ea-9b7e-c826f4502a61.png)

Low priority but probably an easy and simple change for someone who wants to cut their teeth on PL development.

**Comment by coatless** [comment]
Add this as an API option.

Potentially, pair this with a GitHub action in the future.

**Comment by nwalters512** [comment]
Syncing always happens within the context of a particular course; a global button wouldn't make much sense since it's not clear which course such a button would sync.
