### ISSUE TITLE
Automatically handle DRES accommodations for timed exams

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2379]
It would eliminate a lot of work and errors if we could automatically give students extended time accommodations on remote timed exams, just like we would in the CBTF. We could have the CBTF proctors maintain a global list of extended-time accommodations. I think an MVP here would need:

1. A new DB table to store the extra-time accommodations. This would need at least a `user_id` and time scale factor (e.g., 1.5 or 2 for 50% extra time and double time).

2. Use this new table to scale the `timeLimitMin` when we start an exam.

3. Add `admin_queries` to allow admins to view/add/delete extra-time accommodation entries.

4. Display the extra-time accommodation for students on their `userSettings` page.

Extra things that would be nice to have are:

1. A separate `fixedTimeLimitMin` access rule that doesn't automatically scale for accommodations, in case someone really needs to give all students the same time for some reason.

2. A nice page (not just `admin_queries`) to edit the accommodation list.

**Comment by tdy** [comment]
Self-assigning, but not working on this immediately. If someone gets inspiration to tackle this in the meantime, please do.

**Comment by nwalters512** [comment]
@mwest1066 is it fair to say that PrairieTest handles this now? Is there anything missing in our current PT implementation that we should file issues for?

**Comment by mwest1066** [comment]
Yep, this functionality has been subsumed by PT.
