### ISSUE TITLE
Represent breadcrumbs for recent aux pages like News with query string

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#2391]
As mentioned in a chat a while back, to simplify the way that pages like `news_items` are mounted and to maintain the correspondence between recently-stacked auxiliary pageviews and the breadcrumbs bar, perhaps these pages that are auxiliary (not part of the main course administration stack) should be indicated by a query string on the URL that virtualizes a secondary path, something like:

*Old:*
`https://prairielearn.engr.illinois.edu/pl/course_instance/12345/instructor/news_items`

*New:*
`https://prairielearn.engr.illinois.edu/pl/course_instance/12345/instructor/instance_admin/assessments?nav=news_items`
(with the URL also showing the actual page that was active before clicking to read the news)

To indicate `/` in the query string, it could be URL encoded or perhaps converted to `--` or `---`, whatever is more readable and less likely to conflict with a desired pathname component in reality.

**Comment by echuber2** [comment]
To flesh out the idea a bit more, perhaps `?nav=` would mean that the query string path was the one actively displayed, while `?aux=` would mean the base path is the one actively displayed, while the aux path is the recently-viewed content remaining temporarily displayed on the right end of the breadcrumbs bar.

In this way, the user could click News, read the news, then use the navbar to go back to exactly where they were (e.g. gradebook), and even jump back to the news page after that; but navigating to any other subpage from the gradebook would cause the aux breadcrumbs to go away. I think that the breadcrumbs in file manager apps usually work like this.

A benefit is that it doesn't require specifying in advance the many mount points for a page like `news_items`, since it can be virtually mounted as a subpage from anywhere, and this can be extended to entire subpaths if there is any additional complexity later on with aux pages. I'm wondering if we might have a user preferences page or an about licensing page, for example.

**Comment by echuber2** [comment]
I think it is possible to do exotic routing patterns in Express, such that in the `?nav=` case the query string part would end being the _actual_ route and the part before it becoming parameters, and vice versa in the `?aux=` case. https://stackabuse.com/get-query-strings-and-parameters-in-express-js/#extractingrouteparameters But I may be overlooking some potential ambiguity problems or vulnerabilities that would arise with this.

**Comment by nwalters512** [comment]
This seems like a fair amount of complexity for little gain. The browser back button exists for a reason, and I think users generally understand how it works. Other websites like ours with deeply-nested navigation _and_ "auxiliary" pages like GitHub get by just fine without the functionality proposed here.
