### ISSUE TITLE
Make navbar easier to understand for newer users

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#2393]
As discussed in #2390, the current navbar is very powerful for those who understand its design, but not so much for users who haven't yet solidified a mental model of PL's structure.

The goal is to strike a better balance of intuitive-for-newbies and powerful-for-experts.

---

> Here's how I view the navigation structure of PL. There is a tree structure of courses, course-instances, assessments. Then any of these things has a set of pages (tabs) corresponding to it.

```
PL
|
+- CS 233 -> Access, Questions, Issues, Tags
|     |
|     +- Sp20 -> Assessments, Access, Gradebook
|     |    |
|     |    +- Exam1 -> Downloads, Files, Statistics
|     |    |
|     |    +- Exam2 -> Downloads, Files, Statistics
|     |
|     +- Fa19 -> Assessments, Access, Gradebook
|          |
|          +- Exam1 -> Downloads, Files, Statistics
|
+- TAM 212 -> Access, Questions, Issues, Tags
      |
      +- Sp20 -> Assessments, Access, Gradebook
      |    |
      |    +- Homework1 -> Downloads, Files, Statistics
      |
      +- Fa19 -> Assessments, Access, Gradebook
           |
           +- Homework1 -> Downloads, Files, Statistics
           |
           +- Homework2 -> Downloads, Files, Statistics
```

_Originally posted by @mwest1066 in https://github.com/PrairieLearn/PrairieLearn/pull/2390#issuecomment-615568645_

**Comment by nwalters512** [comment]
@mwest1066 think we can close this in favor of #10608?
