### ISSUE TITLE
Styling error on right panel

### ISSUE THREAD

**Issue by cheeren** [PrairieLearn/PrairieLearn#2408]
I believe I was in student mode, piloting an assessment when I noticed a style issue with one of the boxes the right panel. See screenshot. Browser was Safari.

<img width="484" alt="Screen Shot 2020-04-20 at 5 05 31 AM" src="https://user-images.githubusercontent.com/4000222/79752118-9e5a2780-82c8-11ea-9c4b-d5e6012e9869.png">

**Comment by nwalters512** [comment]
@cheeren are you still able to reproduce this?

**Comment by nwalters512** [comment]
I was able to reproduce this just now. This seems to be a fundamental issue with our extensive usage of tables. Probably the fix involves reworking the display of this information. We could also improve this by shortening "Submission status" to just "Status".

**Comment by nwalters512** [comment]
We ultimately resolved this by changing and shortening the labels that are displayed here.
