### ISSUE TITLE
PDF submissions break submissions_for_manual_grading.csv

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#2409]
For file upload questions, the "submitted answer" section of the downloadable grading csv (or just the "_files" part of it if there is more than one part to the question) is large and not meaningful and, in some cases, makes the csv file invalid.

For questions where students are uploading a text-based file (e.g. code), it is just a minor nuisance and the column can easily be manually deleted.  However, when students upload a PDF, something about the way the "_files" section is formatted introduces extraneous commas that invalidate the formatting of the CSV file.  These files cannot be rendered correctly in Excel or using the Linux `cut` utility, so the column cannot be easily deleted.  Also, I did not try, but I doubt that it would upload to PL correctly.  This may also occur with other binary image types -- I have not had a question that tests this.

I would suggest not including "_files" at all in the downloadable csv to avoid this issue.

**Comment by bowmnath** [comment]
If it would be helpful to have an example invalid csv, let me know and I can generate one.  I didn't want to upload the actual one from my course here for obvious reasons.

**Comment by echuber2** [comment]
I haven't tried this recently; is it true that the binary files are bundled right into the csv? I think that should be optional (one version with, one without) and if it is bundled into the csv, it certainly needs to be escaped somehow. What about encoding it as base64 just to avoid further problems?

**Comment by echuber2** [comment]
Or, put a unique number in the "files" column, and then have a corresponding zip of the files where it can be found (possibly a zip of zips, e.g. 0123456789.zip containing all of that student's submitted files).
