### ISSUE TITLE
No way to delete manual feedback

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#2411]
When doing manual grading by uploading a csv with a "feedback" column, if you accidentally upload feedback for a student you did not mean to, there is no way to erase it.  If you "blank out" the feedback in the csv, the system assumes you want to leave the feedback how it was (which, FWIW, is almost always what I would want).  To get around this, you have to upload new feedback to overwrite the old feedback (e.g. a generic "Good job!").

Uploading new feedback to replace the accidental feedback is simple, and most ways I can think of to allow erasing feedback would make the system more confusing, so I'd be perfectly happy if this is determined to be a "feature" and not a "bug", but I thought I'd leave that decision up to the devs.

**Comment by jonatanschroeder** [comment]
Reviewing manual grading issues, I'm going to close this. A workaround to change the feedback via upload is by adding a `feedback_json` column with the content `{"manual": ""}`, though I would assume using the UI for manual grading is a better option at this point.
