### ISSUE TITLE
Buttons that provide feedback not working, clicking does nothing

### ISSUE THREAD

**Issue by zeh3** [PrairieLearn/PrairieLearn#2483]
The buttons that provide feedback aren't working. Clicking on "QuestionTest" should provide a more detailed description of what went wrong and what test case was failed, but instead nothing happens. Clicking on "hide," "show preview," and "checkstyle" also does nothing. I was able to reproduce this error on both Safari and Chrome.
<img width="828" alt="Screen Shot 2020-05-03 at 9 34 39 AM" src="https://user-images.githubusercontent.com/55011615/80917328-b21f7800-8d23-11ea-9d37-1d9b890be4b6.png">

**Comment by nicknytko** [comment]
Can you paste a link to the affected question?

**Comment by zeh3** [comment]
I've tried a few different questions from a few different classes and they all seem to be affected, but [this](https://prairielearn.engr.illinois.edu/pl/course_instance/52292/instructor/question/5254063/preview) is the link to the question I screenshotted and posted here.

**Comment by nicknytko** [comment]
After some digging, this looks like an issue with bootstrap itself (https://github.com/twbs/bootstrap/issues/30553) that can be temporarily fixed by downgrading jquery.

**Comment by echuber2** [comment]
I've made a temporary fix you can apply client-side using the Stylus browser add-on for Firefox. (Use Stylus, *not* Stylish! Stylish is spyware.)

https://gist.github.com/echuber2/9aade0bbcc510130074fdf6a8d8fccb3

**Comment by zeh3** [comment]
I installed it on Chrome and can confirm that it works on Chrome as well! Thank you!
