### ISSUE TITLE
Need to validate time limit expiry on the server

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2506]
At the moment, when a student's browser sends a `__timeLimitExpired` POST request, we unconditionally close the assessment. This can cause a problem when we manually extend a time limit, but the student has an old tab open with a countdown timer that's using the old time limit.

We should check that we are indeed at the time limit on the server before closing the assessment. If not, we can just redirect back to the page with no changes.

This issue will be important when we implement manual time limit changes in #2293

**Comment by tdy** [comment]
> We should check that we are indeed at the time limit on the server before closing the assessment. If not, we can just redirect back to the page with no changes.

If I understand correctly, this sounds like a bandaid for a bigger issue -- students won't see updated timers unless they personally refresh their page? Can we resolve both issues by somehow force-refreshing existing assessment timers?

**Comment by mwest1066** [comment]
The places where we process time limit expirations is: https://github.com/PrairieLearn/PrairieLearn/blob/bf2f3c3a6b618f79a426a069b61b4fb5553aabaa/pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.js#L34 and: https://github.com/PrairieLearn/PrairieLearn/blob/bf2f3c3a6b618f79a426a069b61b4fb5553aabaa/pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js#L73

**Comment by mwest1066** [comment]
Here's how we test whether the time limit has actually expired: https://github.com/PrairieLearn/PrairieLearn/blob/bf2f3c3a6b618f79a426a069b61b4fb5553aabaa/pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js#L62
