### ISSUE TITLE
Element request: pl-dropdown

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2512]
Make an element that renders a dropdown with a list of options to choose. Demo questions could include:

1. A paragraph where multiple words are replaced with dropdowns, and the student needs to pick which word to fill in to make the paragraph correct.

2. A `pl-overlay` question that has a map of the U.S. states with five random states containing dropdowns with all 50 states listed in them. So the student has to pick the names of 5 different states, getting 20% of the points for each one that is correct.

**Comment by andrewstec** [comment]
@mwest1066 

I will jump on this. I think this is a super simple and nice starting point to get involved in the application.

**Comment by andrewstec** [comment]
(Unless you have other suggestions!)

**Comment by mwest1066** [comment]
> I will jump on this. I think this is a super simple and nice starting point to get involved in the application.

Awesome! Jump into #pl-dev if you need any pointers.
