### ISSUE TITLE
demoCodeEditorAutograded only runs one test

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2515]
Steps to reproduce:

1. Go to the `demoCodeEditorAutograded ` question as an instructor.

2. Answer:
```
def fib(n):
    return 1
```

3. Grade it.

4. Score is 0%, and only the `fib(0)` test ran. Later tests did not run. I expected to get some partial credit because the second test (checking `fib(1)`) would have passed.

**Comment by nicknytko** [comment]
Resolved in #2516
