### ISSUE TITLE
Missing accent on nav bar over Files when in file editing mode

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2575]
When overlooking the **Files** tab, there is a blue accent at the top of the tab: 

<img width="590" alt="file tab accent present" src="https://user-images.githubusercontent.com/833642/83990248-96a12180-a90e-11ea-8af4-0e721e9398df.png">

After moving to "edit", the contents the accent disappears from the navigation bar. 

<img width="590" alt="file tab accent mia" src="https://user-images.githubusercontent.com/833642/83990247-956ff480-a90e-11ea-88d9-fcf091d84e38.png">

**Comment by mwest1066** [comment]
@astrosticks will this be fixed by #2281 or one of your other PRs?

**Comment by coatless** [comment]
@mwest1066 #2281 is geared toward HTML title changes not underlying navbar changes. I do not think there is an open PR with the issue solved (last work on the topic was in #2292, where accents were added). So, @astrosticks would likely need a separate one-off PR.

**Comment by astrosticks** [comment]
> 
> 
> @astrosticks will this be fixed by #2281 or one of your other PRs?

Not included

**Comment by coatless** [comment]
@nwalters512 not the same fix as described

**Comment by nwalters512** [comment]
@coatless it looks like @astrosticks misunderstood what "accent" was referring to.
