### ISSUE TITLE
format error on checkbox items for multiline options

### ISSUE THREAD

**Issue by cheeren** [PrairieLearn/PrairieLearn#2586]
<img width="728" alt="Screen Shot 2020-06-16 at 1 09 39 AM" src="https://user-images.githubusercontent.com/4000222/84749416-cc798200-af6e-11ea-8c60-276f73619888.png">

Occurs on Chrome running locally, Chrome production, and Safari production. Could not reproduce on Firefox.

**Comment by cheeren** [comment]
duplicate of 2582

**Comment by echuber2** [comment]
Just leaving a cross-reference: #2582
