### ISSUE TITLE
custom grading function example

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2588]
Question:

How can I have a solution that checks if student input is an integer (without quotation) or a string (quotation) using `pl-string-input`

From matt on #pl-help

```python
def grade(data):
    # note quote order
    if data["submitted_answers"]["solution"] == '"1"' or data["submitted_answers"]["solution"] == "'1'": 
        data["partial_scores"]["solution"] = {"score": 1, "feedback": "you got this correct!"}
    else:
        data["partial_scores"]["solution"] = {"score": 0, "feedback": "you got this wrong, sorry"}
```

In the `question.html` you can add:

```html
<pl-string-input answers-name="solution"></pl-string-input>
<pl-submission-panel>
    {{partial_scores.solution.feedback}}
</pl-submission-panel>
```

**Comment by eliotwrobson** [comment]
@coatless should this be closed? We have more complex examples of custom graded questions now.

**Comment by coatless** [comment]
@eliotwrobson great question. Can you remind me about the examples?

**Comment by eliotwrobson** [comment]
There's others but here's a solid one I think: https://us.prairielearn.com/pl/course_instance/4970/instructor/question/1152385/preview
