### ISSUE TITLE
Retitle main buttons to 'Grade and Retry' and 'Final Submission'

### ISSUE THREAD

**Issue by DallasTrinkle** [PrairieLearn/PrairieLearn#259]
Change the titles on the buttons on the main page to reflect that one allows students to retry questions, while the other is their final submission.

**Comment by mwest1066** [comment]
The button text sounds good to me: "Grade and retry", and "Final submission". The warning dialog text should also be changed to be more immediate. For "Final submission" we could say:

    Warning: you will not be able to answer any more questions after the final submission.

The current warning dialog text for "Grade and retry" sounds fine.

**Comment by kevinwang** [comment]
"Grade and retry" sounds to me like the user has unlimited retries. How does "Grade and continue" sound?

**Comment by mwest1066** [comment]
I agree that "Grade and continue" sounds better than "Grade and retry".
