### ISSUE TITLE
Unload confirmation does not work for v2 questions

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#2612]
#2215 initializes question state by serializing `form.question-form`, but v2 `input` fields were located outside the form.

**Comment by tdy** [comment]
The only way that I can think to fix this is to do a blanket `$('input').serialize()`. @mwest1066 I'm guessing you won't approve since you were already leery of a generic `form` selector (so it became `form.question-form`).

At this point, I'm inclined to just say v2 questions won't have unload confirmation (they don't break, it just won't have an effect) unless @mwest1066 @nicknytko have other ideas?

**Comment by mwest1066** [comment]
I’m fine with not supporting new features for v2 questions (like unload confirmation), so long as we don’t introduce regressions for them.

**Comment by tdy** [comment]
Sounds good, closing
