### ISSUE TITLE
instructorAssessments CSV download links broken

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2616]
Links at the bottom of https://prairielearn.engr.illinois.edu/pl/course_instance/4970/instructor/instance_admin/assessments throw a not found

**Comment by nicknytko** [comment]
To reproduce this locally you can open up the test/example courses and try clicking one of these two links on the bottom:

![image](https://user-images.githubusercontent.com/1790491/85897313-b74af180-b7bf-11ea-9293-c5cf9bb97038.png)
