### ISSUE TITLE
live_all_submissions.csv file does not contain information about grade student received

### ISSUE THREAD

**Issue by DallasTrinkle** [PrairieLearn/PrairieLearn#263]
A new column should be added that reflects either (a) that a student graded a given submission, and/or (b) the grade received for that submission. This will allow better analysis of a student's quiz grade, and better regrading.

**Comment by rbessick5** [comment]
Submissions stored in the database don't maintain their own 'graded' status, so we can't load this information yet.

**Comment by mwest1066** [comment]
Eliminated by PLv2.
