### ISSUE TITLE
Mouse hovering over assessment due date draws extra instances of datestring

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#265]
On assessment page, hovering the mouse over the due date (seeing text entry cursor) causes the following to draw:
1) "Due Date: (Day of week), (Date string)" appears on left edge of browser, one line below the assessment. This disappears if the cursor is moved.
2) Identical string appears on left edge of browser below the assessment bounding box. These only disappear by navigating away from assessments (or refreshing page). They also "auto-sort" by date (earliest first) if you hover over more than one assignment.

This only happens with assessments that have an explicit date (such as homeworks and finished quizzes); nothing happens if the listed date is "in progress" (such as open quizzes from instructor/TA view).

This bug appears on the live versions of PL for TAM 210 and TAM 251; it does not appear for TAM 212. I am using Chrome v48.0.2564.116 m (64-bit).

**Comment by mwest1066** [comment]
Dup of #220, fixed in 1.19.0 (not yet live for 210 and 251).
