### ISSUE TITLE
Click on image element

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#2680]
It'd be nice to have an element that indicates creates clickable regions in an image that we can use for students to identify components of an image. For example, if shown an image of a cell, the student is asked to click on the nucleus or cell membrane.

**Comment by mfsilva22** [comment]
We don’t have that now, but I think you can already use pl-overlay and pl-drawing to make something that works for this use case

**Comment by cheeren** [comment]
Do I need to make new button elements in order to have them draw rectangles or circles?

**Comment by eliotwrobson** [comment]
Going to go ahead and close this, since similar things can be accomplished with existing elements (like pl-overlay with graded elements like pl-dropdown).
