### ISSUE TITLE
Add function to clean numeric data in dataframes

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#2706]
(From discussion in https://github.com/PrairieLearn/PrairieLearn/pull/2702)

Provide a `df_clean` function which

1. if data is string, Latex etc - just leave it alone and pass through
2. if all column data is float format (except header), check magnitude of ALL numbers in a columns and use some simple logic like (really big or really small use e format else use d format), sort of like
```
if -3 < log_10 (max mag) < 3 convert to string in e format with desired # of figs
else convert to string in d format with desired # of figs
```

We should add this to the freeform python lib

**Comment by echuber2** [comment]
Plug for my PR: https://github.com/PrairieLearn/PrairieLearn/pull/2703

**Comment by eliotwrobson** [comment]
Is this issue redundant now? I think there are already generic dataframe creation functions, and better support for encoding different types of data in this PR: https://github.com/PrairieLearn/PrairieLearn/pull/6744
