### ISSUE TITLE
pl-code display error

### ISSUE THREAD

**Issue by lumetta** [PrairieLearn/PrairieLearn#2738]
https://prairielearn.engr.illinois.edu/pl/course_instance/86802/instructor/question/8086098/preview

garbage at end of pl-code display; I'm going to paste the question.html below--I'm still working on this stuff, and bug may vanish (and I don't have commit version from web interface)

--Steve

<pl-question-panel>

<pl-code language="c">
#include <stdio.h>
int main ()
{
    int A, B, C, D;
    printf ("Please enter three numbers: ");
    if (3 != scanf ("%d%d%d", &A, &B, &C)) {
        printf ("Invalid input.\n");
	return 3;
    }
    if (A < B) {
        D = A;
	A = B;
	B = D;
    }
    if (A < C) {
        D = A;
	A = C;
	C = D;
    }
    if (B < C) {
        D = B;
	B = C;
	C = D;
    }
    printf ("The numbers are %d, %d, and %d.\n",
            A, B, C);
    return 0;
}
</pl-code>

<p>How does the program above change <tt>A</tt>, <tt>B</tt>, and <tt>C</tt>
before printing them?</p>

</pl-question-panel>

<pl-multiple-choice answers-name='W6Q1' number-answers=4>

  <pl-answer correct='true'>
    The values are sorted, with <tt>A</tt> holding the largest and
    <tt>C</tt> the smallest.
  </pl-answer>

  <pl-answer>
    All three are made equal to the original value of <tt>A</tt>.
  </pl-answer>

  <pl-answer>
    All three are made equal to the original value of <tt>B</tt>.
  </pl-answer>

  <pl-answer>
    All three are made equal to the original value of <tt>C</tt>.
  </pl-answer>

  <pl-answer>
    The three are permuted randomly.
  </pl-answer>

  <pl-answer>
    The largest number is put into <tt>A</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The largest number is put into <tt>C</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The smallest number is put into <tt>A</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The smallest number is put into <tt>C</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The values are sorted, with <tt>A</tt> holding the smallest and
    <tt>C</tt> the largest.
  </pl-answer>

  <pl-answer>
    The middle value is put into <tt>A</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The middle value is put into <tt>B</tt>, and the others are
    left unchanged.
  </pl-answer>

  <pl-answer>
    The middle value is put into <tt>C</tt>, and the others are
    left unchanged.
  </pl-answer>

</pl-multiple-choice>

**Comment by nicknytko** [comment]
Hi Steve,

This is a known issue with placing html characters on the page (https://prairielearn.readthedocs.io/en/latest/elements/#common-pitfalls).  The workarounds we currently have are to escape the characters (i.e. use `&lt;` for `<`) or to define the code snippet in a separate file.  We've tried getting a proper fix for this but found it was too much of a hassle to deal with the edge cases of automatically escaping characters.

**Comment by lumetta** [comment]
Er.

Sorry.  Now I feel kind of lame.  I did look at the description, but I 
didn't read to the bottom, apparently.

--Steve

--
