### ISSUE TITLE
"Request a Course" page should be customized by institution...

### ISSUE THREAD

**Issue by cheeren** [PrairieLearn/PrairieLearn#2772]
https://prairielearn.readthedocs.io/en/latest/requestCourse/ (now accessible via button from main PL page) gives instructions specific to UIUC faculty.  UBC faculty who click on that button will be stymied at the gate! :)

**Comment by mwest1066** [comment]
@cheeren apologies for the hard-coded first pass of the "request" button. @nicknytko has a built-in system coming: #2673

**Comment by cheeren** [comment]
Thank you!!
