### ISSUE TITLE
Fix slashes in tag names breaking question search

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#2775]
https://github.com/PrairieLearn/PrairieLearn/blob/e309d01d250ebe83409de07fb36d310edf216372/pages/instructorQuestions/instructorQuestions.ejs#L99

Having slashes in a tag name will break the filter regex, this can probably be fixed by using a `RegExp()` object instead of the slash notation.  We should do this for the assessments filter as well.

**Comment by mwest1066** [comment]
Great catch! If we want to use regexps then we should escape the search string (`tag.name`) before inserting it into a regexp. Lodash has a function for this: https://stackoverflow.com/a/29700268

I think changing this to `return /\b<%= _.escapeRegExp(tag.name) %>\b/.test(e);` will work. But that will require a `locals._ = _` in the JS to inject lodash, if we aren't doing this already.

@nicknytko as you say, it would be great to check the rest of the code to see whether we are doing the same thing elsewhere in other tablesorter functions.

Using a `RegExp()` object might fix the particular issue of forward slashes, but it will still break on other special regexp characters (e.g., if there is a `$` in a tag name).

An alternative in this particular case would be something like `e.split(/ +/).includes(tag.name)`. In fact, the really correct way to implement this would be to store the raw list of tags somewhere as a true JS variable, so we could match against it. But I think the regexp method above is good --- it's just that we need to change it to 

Docs for tablesorter custom filters are https://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#how_to_add_custom_filter_types

**Comment by trombonekenny** [comment]
I'm pretty sure I've used lodash in an .ejs file without having to do anything fancy (sshhhhhhh don't tell matt)

**Comment by nicknytko** [comment]
Will be fixed by #3385
