### ISSUE TITLE
Invalid working directory in file browser after changing directory name with broken sync

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#2793]
Do these things with the in-browser editor:

- Make a copy of a course instance
- Make a change to the `infoCourseInstance.json` file of the new course instance that breaks sync (e.g., remove a comma)
- Make a change to the CIID of the new course instance (from the instance admin "Settings" tab)
- Try to access `infoCourseInstance.json` of the new course instance from the file browser (the instance admin "Files" tab)

Then you will see an error saying "Invalid working directory":

<img width="960" alt="Screen Shot 2020-07-31 at 5 31 18 PM" src="https://user-images.githubusercontent.com/14169175/89082469-ba537780-d353-11ea-8664-aba56af06ba8.png">

It's likely the same thing would happen with an existing course instance and with anything that breaks sync. It's likely the same thing would happen with other "objects" like questions and assessments.

**Comment by mwest1066** [comment]
Should be fixed by #1640
