### ISSUE TITLE
Stuck nowait lock query

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2839]
We are seeing occasional cases where the locking code gets stuck in acquiring a `nowait` lock. This manifests as the `BLOCK lock_row_nowait` query timing out in state `idle in transaction`. Although we are using `SKIP LOCKED` for `nowait` locks, from https://www.postgresql.org/docs/current/sql-select.html it sounds like we might be getting stuck waiting for the `ROW SHARE` table-level lock. To avoid this we should use `LOCK` with the `NOWAIT` option first on the table-level lock.

**Comment by nwalters512** [comment]
@mwest1066 I don't recall seeing anything like this recently; do you think there's still anything we need to do here?

**Comment by mwest1066** [comment]
I think this error has vanished so I'm happy to close this issue, although unfortunately I can't pinpoint what the actual problem was.
