### ISSUE TITLE
Showing closed assessments is broken on LTI

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#2847]
It seems that `showClosedAssessment` defaults to true, however, on LTI exam items, students can't get back into the closed exam item later to inspect their results, whether it is set to true or false or left undefined. Since we aren't exactly sure why this is happening, I'm worried about what might be the underlying cause with the authorization or page routing sequence. Also, I don't have the access needed to reproduce and debug this one by myself.

Example assessment where this had happened (using LTI integration on Coursera):
https://prairielearn.engr.illinois.edu/pl/course_instance/82516/assessment_instance/1659853/

@trombonekenny suggested the issue might be with this line, but I can't view the server terminal live to investigate it further by myself:

https://github.com/PrairieLearn/PrairieLearn/blob/b048e7341229521b80bdaf2117d635b0b7d53ccb/middlewares/studentAssessmentAccess.js#L60

Also, it's hard to debug LTI in this situation without having a way to simulate the LMS endpoint for the LTI using the dev container.

**Comment by echuber2** [comment]
Edited for clarity: I think this could be somewhat serious since the cause isn't known. As a separate matter, I feel that once this issue is ironed out, `showClosedAssessment` should probably default to false rather than true.

**Comment by echuber2** [comment]
Before I forget: Dave suggested earlier that this might be related to the PL password protection on an exam item. I'll need to experiment with it some more.

**Comment by nwalters512** [comment]
@echuber2 is this still an issue for y'all using LTI 1.1?

**Comment by echuber2** [comment]
I'll have to test this when the vendor's site is working again.

**Comment by echuber2** [comment]
I was able to test. It doesn't look like it's an issue anymore so I'll just close this for now.
