### ISSUE TITLE
Combine PRs #2760 and #2625 

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#2865]
# Combine PRs #2760 and #2625 into one:

Writing up the design ideas, so we can better take the next steps when combining both PRs. 

## `pl-parson-problem` element

Drag and drop to arrange answer tiles to form a (potentially ordered) list of answers. 

#### Sample Element

```html
<pl-parsons-problem answers-name="result" shuffle-options="true">
  <pl-answer correct="false">This tile should not be moved</pl-answer>
  <pl-answer correct="true">This tile should be moved</pl-answer>
  <pl-answer correct="true" indent=1>This tile should be moved with one indentation</pl-answer>
</pl-parsons-problem>  
```
#### Customizations

Attribute | Type | Default | Description
--- | --- | --- | ---
`answers-name` | string | — | Variable name to store data in.
`shuffle-options` | boolean | true | Specify whether the ordering of options on the left-hand-side should be shuffled. If false, the ordering in the HTML file will be used.
`permutation-mode` | string | "html-order" | One of the following: "any", "html-order", "ranking". See details below for description.
`max-distractors` | integer | 2 | Select the maximum number of distractors.
`min-distractors` | integer | 1 | Select the maximum number of distractors.
`check-indentation` | boolean | true | Whether indentation is checked while marking.
`external-grader` | boolean | false | Whether an external grader is used to determine the correct answers.
`header-left-column` | string | "Drag from here" | Initial the header of the left column.
`header-right-column` | string| "Construct your solution here" |  Initial the header of the right column.
`leading-code` | string | — | The file name of the leading code.
`trailing-code` | string | — | The file name of the trailing code.

Within the `pl-parsons-problem` element, each answer tile must be specified with
a `pl-answer` that has the following attributes:

Attribute | Type | Default | Description
--- | --- | --- | ---
`correct` | boolean | true | Specifies whether the answer tile is a correct answer to the question. **If attribute is not provided, the attribute defaults to `true` for backward compatibility reasons**.
`ranking` | positive integer | — | Specifies the correct ranking of this answer tile. For example, an answer tile with ranking `2` should be placed below an answer tile with ranking `1`.
`indent` | integer in [-1, 4] | -1 | Specifies the correct indentation level of the answer tile. For example, a value of `2` means the tile should be indented twice. A value of `-1` means the indention for this answer does not matter.

### Details

Three different `permutation-mode` are available:

* `any`: in this mode, if `n` is the total number of answers, each answer dragged and submitted by the student is given `1/n` points, and the ordering of the answer tile does not matter. That is, any permutation of the answers are accepted. 
* `html-order`: in this mode, the ordering of the answer tiles submitted by the student must match the ordering of the `pl-answer` options within the HTML file. There is no partial credit for this option.
* `ranking`: in this mode, the `ranking` attribute of the `pl-answer` options are used to check answer ordering. Every answer tile *X* should have a `ranking` integer that is less than or equal to the answer tile immediately below *X*. That is, the sequence of `ranking` integers of all the answer tiles should form a *nonstrictly increasing* sequence. If `n` is the total number of answers, each correctly ordered answer is worth `1/n`, up to the first incorrectly ordered answer.

## TO DO and general comments

- element name will be `pl-parsons-problem`. 

- looks like the best option is to start combining the PRs using #2760 as starting point. 

- make sure debugging code is removed from the latest PR version (before merge)

- [ ] PR#2625 uses the attribute `file-name` to decide whether autograde is used or not. We should remove this. `file-name` should have a default name in the backend (we should use `user_code.py` to keep consistency with the autograder implementation). Instead, we are adding the attribute `external-grader` to `pl-parson-problem` element.

- [x] in the `prepare` function, make sure only `answers-name` is required. Other attributes should be optional. Use the default values from the above table. (the idea is we do not want the instructor to add a lot of attributes in the most common use-case + make change compatible with current implementation of CS 105 questions)

- [x] add back the check for indentation (it is in PR#2625, but not #2760)

- [ ] incorporate `min-distractors` and `max-distractors`. this will be similar to `min-correct` and `max-correct` in the other choice elements, but instead will determine the number of `pl-answer` tiles with `correct=false`

- [x] we need to revise if `pl-info` is needed. I think it can be removed. We can instead use `leading-code` with `leading-code-visible=true` to display this "info" text. 

- Can we add backwards compatibility on the old pl-parsons-element, or at least explore the best way forward to resolve any differences between the new UBC pl-parsons-element and the UIUC one? It seems that we will be able  write scripts to modify Cinda's and Craig's questions to match the updates.

**Comment by Frozemint** [comment]
I made some small edits to the specs, including an `indent` field in `pl-answer`. Pls take a look and see if you think it's a reasonable design.

**Comment by Frozemint** [comment]
attributes implementation list:

 - [x] `answers-name` 
- [ ] `shuffle-options` 
- [ ] `permutation-mode` 
- [ ] `max-distractors` 
- [ ]  `min-distractors` 
- [ ]  `check-indentation` 
- [ ]  `external-grader` 
- [ ]  `header-left-column` 
- [ ]  `header-right-column`
- [ ]  `leading-code` 
- [ ]  `leading-code-visible` 
- [ ]  `trailing-code` 
- [ ]  `trailing-code-visible`

**Comment by Frozemint** [comment]
so I was looking at possible backward compatibility for the element, and I found that the tests for some questions could break: some legacy questions do not have any incorrect options, and the way my tests submission submits only incorrect options. The result is my test submission is blank, which correctly triggers a `format_error` and failing the test. 

Is it ok if we just allow broken tests? From my own testing this looks like an edge case.

**Comment by mfsilva22** [comment]
Let's discuss this in the Thursday's dev meeting

**Comment by cheeren** [comment]
The design of this looks great to me!! Easy to use, and clearly described.

I am late to the game, and you've all probably thought about this already, but I'm curious about the _appearance_ of the options, and especially the mechanism for making sure font is consistent between the leading file, and the answers. Can the "leading code" file actually be markdown, for example? The question is motivated by the fact that this question type is likely to be used for proofs, which of course have non-code text (and actually should even have latex capability).

**Comment by cheeren** [comment]
Here's another front-end concern that occurs to me in the context of writing proofs: Could the layout be adapted so that instead of dragging side-to-side, we have the options in a block followed by the answer block? This request/comment is also motivated by the fact that this will be used for proofs, whose statements are likely to be long lines (or even paragraphs?) of text.

**Comment by SethPoulsen** [comment]
On proofs:
I'm realizing that in order to grade proofs, having the "ranking" property does not give me enough control, because there are many different orders that steps can be placed in and still be correct. Rather, the dependence of deductive steps on one another should be modeled as a DAG (directed acyclic graph), so that we can clearly state which prior steps must have happened for a given deduction to be valid. 

For example, consider a proof that assumes two even integers, $m$, and $n$. The first few steps of the proof might be: 
1. Take some $m \in \mathbb{Z}$ 
2. assume $m$ is even
3. Take some $n \in \mathbb{Z}$ 
4. assume $n$ is even 
5. $\exists l \in \mathbb{Z}$ such that $m = 2l$
6. $\exists k \in \mathbb{Z}$ such that $n = 2k$
7. *Do something using $m, n, l,$ and $k$

In this case statement 2 depends on 1, but statement 4 only depends on statement 3, and statement 3 doesn't depend on any prior statements. Statement 5 depends only on 1 and 2, and 6 depends only on 3 and 4. Only when you get to 7 do you depend on all previous statements. Here is is impossible to capture all possible correct answers using `ranking`.

Maybe we could have a different permutation mode called `dag` and  you will use a `depends` property to list which prior statements a given statement depends on?

Of course, I'll need to play around with this a bit more and make sure it works, and of course it doesn't need to go in right away. Just getting my though process out here so others can comment.

**Comment by SethPoulsen** [comment]
Is it possible to turn off indentation altogether? it seems like this would also be a useful feature for proofs

**Comment by Frozemint** [comment]
Yes, by setting `check-indentation` to false in the element attribute. Additionally, the default behaviour for grading correct `pl-answer` blocks with indents never specified is that the indentation does not affect grading.

@ the DAG suggestion, ill look into it, rn I am looking to add the autograder feature in.

**Comment by SethPoulsen** [comment]
I wouldn't worry about the DAG thing yet, getting this pushed initially is definitely higher priority.

**Comment by Frozemint** [comment]
Yep, thanks for letting me know about the feature request tho. Funny enough, the class I finished this year's May covered DAGs. Can't believe I'll put what I learnt to use so quickly :smile:

**Comment by cheeren** [comment]
The DAG request is so good! We should at least come up with a canonical way of handling this in the grade() function.
