### ISSUE TITLE
Support for multiple submissions of multiple choice (IF-AT) format questions?

### ISSUE THREAD

**Issue by a6** [PrairieLearn/PrairieLearn#2885]
Hello PrairieLearn Team,

This is a remarkable platform, thank you for making it open source.

I have read through the documentation and GitHub issues pages but was not able to find the feature of interest.
I am wondering if a multiple submission feature is implemented for multiple choice questions.

This question type notifies the student if a selection was incorrect and then prompts for selection again (crossing out the incorrectly selected choice), with an optional additional description of why that selection was incorrect. No credit is awarded until a correct answer is selected, and credit is assigned on a sliding scale based on the number of submissions required.

This would be the online equivalent to paper-based IF-AT format scratchers:
http://www.epsteineducation.com/home/about
https://www.uc.edu/content/dam/uc/cetl/docs/IF-ATinstructions.pdf
https://poorvucenter.yale.edu/UsingIF-ATForms
https://www.jstor.org/stable/10.2979/teachlearninqu.3.1.31

**Comment by nwalters512** [comment]
Hello, thanks for the question!

> I am wondering if a multiple submission feature is implemented for multiple choice questions.
>
> This question type notifies the student if a selection was incorrect and then prompts for selection again (crossing out the incorrectly selected choice), with an optional additional description of why that selection was incorrect. No credit is awarded until a correct answer is selected, and credit is assigned on a sliding scale based on the number of submissions required.

In general, this is how PrairieLearn is meant to be used! For both homeworks and exams, it uses repeated attempts with immediate feedback to encourage learning. One of the faculty members of the team could probably describe this better in academic-speak 🙂 But for every type of question (multiple choice, input, coding, diagramming, etc.) this is how PrairieLearn is meant to be used.

To answer the specific question about multiple choice questions, they work this way by default in Exam-type assessments. Students can retry the question a specified number of times, and get a different amount of points based on how many attempts they've already made.

It differs subtly from what you describe in that incorrect prompts aren't crossed out. However, the student can see their past submissions and use that to inform their future choices.

You can see an example of this in the "Exam Design: Best Practices" example assessment: 

https://github.com/PrairieLearn/PrairieLearn/blob/d4306520a7c9cff858aea21b4298200baeec00dd/exampleCourse/courseInstances/Sp15/assessments/exam01-bestPractices/infoAssessment.json#L52-L57

In this case, the `points` array specifies that the student has 5 attempts to get the question right. If they get it right on the first attempt, they get 10 points. If they get it right on the 4th attempt, they get 7 points. If they don't get it right after 5 attempts, they get 0 points and cannot try again.

> I have read through the documentation and GitHub issues pages but was not able to find the feature of interest.
I am wondering if a multiple submission feature is implemented for multiple choice questions.

Apologies for this - the documentation isn't currently the friendliest for newcomers, especially those who haven't been onboarded to the platform by someone experienced with the platform. This is something that needs to be improved in the future!

**Comment by a6** [comment]
Thank you for the super prompt response.

This sounds great. Minus the part about crossing out prior selections, this seems like the feature I was looking for. I do wonder if that could be an option for ```pl-multiple-choice``` submission elements. It would be a shame if a student submitted the same answer twice on accident.

A few tangentially related platform questions:
- Can one configure a question to require a text response (perhaps through ```pl-string-input```) in addition to a ```pl-multiple-choice```? The aim is to ask the student to provide justification text for their multiple choice selection.
Based on my cursory understanding of the [Question Configuration](https://prairielearn.readthedocs.io/en/latest/question) and the [string input example](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/element/stringInput), it seems like it is possible to write a question template with multiple submission elements, it just seems like it would require a custom ```server.py``` for that type of question since the justification text would not be graded on the fly.
- I see in the [element options](https://prairielearn.readthedocs.io/en/latest/elements/#pl-string-input-element) a ```pl-string-input``` can have a definable size. I presume that is width of the input box. Can it be set to have a larger height? Can there also be a character limit set? Some of these features seem to be a part of ```pl-file-editor```, but that seems to be more for code submission.
This would help to facilitate a free-response text submissions (e.g., the justification text in the note above).
- Does PrairieLearn support any framework for peer-grading of submissions (or portions of submissions)?
For the aforementioned justification submission portions of questions, I'd like to have students grade each other's submissions as part of the learning process.

**Comment by nwalters512** [comment]
>  I do wonder if that could be an option for `pl-multiple-choice` submission elements.

This wouldn't be trivial to do, though it isn't out of the question. In technical terms, there's currently no notion of state that's both global to a question variant and also mutable over the lifetime of the variant. That could be added, however.

> Can one configure a question to require a text response (perhaps through` pl-string-input`) in addition to a `pl-multiple-choice`?

Yes! All elements are completely independent and are designed to be mixed and matched as much as you'd like. For a particularly over-the-top example of that, check out the [`codeDocumentation` example question](https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/element/codeDocumentation/question.html) - it features most (if not all) of the PrairieLearn elements in a single question!

> it just seems like it would require a custom server.py for that type of question since the justification text would not be graded on the fly.

Depending on exactly how you want to score it, you may or may not need a custom `server.py`. By default, if a correct answer isn't specified for `<pl-string-input>`, it simply won't contribute anything to the score, which it sounds like is what you want.

> I presume that is width of the input box. Can it be set to have a larger height?

Currently, no. The `pl-string-input` element is currently built with just an HTML `<input>` element, which won't do anything useful with an increased height. However, there's no reason we couldn't add support for this! Specifically, I'm thinking of a potential `multiline="true"` attribute for `pl-string-input` that would tell it to use a `<textarea>` instead. 

> Does PrairieLearn support any framework for peer-grading of submissions (or portions of submissions)?
For the aforementioned justification submission portions of questions, I'd like to have students grade each other's submissions as part of the learning process.

It does not. It does have support for manual grading, but you'd have to build your own peer-grading system on top of that. That being said, there's no reason that we couldn't build a peer-grading feature into PrairieLearn - it seems like a perfectly sensible feature to have!

**Comment by a6** [comment]
Thank you, this answers all my questions.

I agree that a <textarea> submission option would be nice. It opens the platform up to open-ended questions.

**Comment by nwalters512** [comment]
Closing this out as there aren't any open questions here.
