### ISSUE TITLE
Updates to group work support

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2894]
@frankyhao @zhining4 I merged #2518 so that faculty can get ready for Fall semester, but I also added a number of comments on the PR. Could you please address these in the (closed) PR, and open a new PR to make requested changes?

**Comment by frankyhao** [comment]
No problem, I will try to address the code changes during this week and finish basic features (support for exam/more auto group assignments methods) in another PR.
