### ISSUE TITLE
triesPerVariant and constantQuestionValue are undocumented

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2905]
The `triesPerVariant` and `constantQuestionValue` parameters for homework assessment questions are currently undocumented: https://github.com/PrairieLearn/PrairieLearn/blob/3a972e46e1f48d74cb683a2335c449affb157171/schemas/schemas/infoAssessment.json#L272 and: https://github.com/PrairieLearn/PrairieLearn/blob/3a972e46e1f48d74cb683a2335c449affb157171/schemas/schemas/infoAssessment.json#L81

In general we don't really describe in the docs how the points scheme works for assessments of type Homework and Exam. We have a very brief description when we talk about [assessment type](https://prairielearn.readthedocs.io/en/latest/assessment/#assessment-types), but we don't talk about when new variants get generated, etc.

**Comment by echuber2** [comment]
What would a minimum viable product look like for this documentation? Does it need the larger discussion of how points work for different types or when exactly a variant is generate?

**Comment by mfsilva22** [comment]
I think just having it included in the documentation would be helpful. Some people may find this useful and not even know it exists.

**Comment by jonatanschroeder** [comment]
Just adding a note here, to make sure it's included in the docs: the `triesPerVariant` setting is ignored in exam type assessments (which uses the point list as the number of tries), as well as for questions with `singleVariant` set to true (which have unlimited tries regardless of this setting). This is what I understood from the code while working on #3601 so if this is wrong please let me know so I can fix that code too...

**Comment by jonatanschroeder** [comment]
Adding documentation for `triesPerVariant` in #3601. I don't feel confident enough in understanding `constantQuestionValue` to reliably write documentation for it at the moment.

**Comment by mwest1066** [comment]
> Adding documentation for `triesPerVariant` in #3601. I don't feel confident enough in understanding `constantQuestionValue` to reliably write documentation for it at the moment.

The meaning of `constantQuestionValue` is this:

For Homeworks (not Exams), we use a variable called `instance_questions.current_value` to determine how many points are awarded for a correct answer. The logic is this:

1. Initialization:
    * `instance_questions.current_value` is initialized to be `assessment_questions.points`
    * `instance_questions.points` is initialized to be 0
2. Whenever a question is answered correctly (ignoring partial credit for simplicity):
    * `instance_questions.points += instance_questions.current_value` (award `current_value` points)
    * `instance_questions.current_value += assessment_questions.points` (increase `current_value`)
3. Whenever a question is answer incorrectly:
    * `instance_questions.current_value = assessment_questions.points` (reset to initial value)

The above scoring mechanism rewards "runs" of successful answers. This is a slightly "gamified" scoring system.

The effect of `constantQuestionValue` is keep `instance_questions.current_value` always fixed at `assessment_questions.points` and to never change it. This removes the gamification aspect.

The gamified scoring system (with variable `current_value`) is a holdover from a very early version of PrairieLearn. I now believe that, in practice, it doesn't add any value and it just makes the code and scoring systems more complex. I would personally be in favor of either defaulting to `constantQuestionValue=true` or just removing the variable-`current_value` code entirely and always treating the `current_value` as fixed.

**Comment by mwest1066** [comment]
> Just adding a note here, to make sure it's included in the docs: the `triesPerVariant` setting is ignored in exam type assessments (which uses the point list as the number of tries), as well as for questions with `singleVariant` set to true (which have unlimited tries regardless of this setting). This is what I understood from the code while working on #3601 so if this is wrong please let me know so I can fix that code too...

I believe this is correct.

**Comment by jonatanschroeder** [comment]
> The above scoring mechanism rewards "runs" of successful answers. This is a slightly "gamified" scoring system.
> 
> The effect of `constantQuestionValue` is keep `instance_questions.current_value` always fixed at `assessment_questions.points` and to never change it. This removes the gamification aspect.
> 
> The gamified scoring system (with variable `current_value`) is a holdover from a very early version of PrairieLearn. I now believe that, in practice, it doesn't add any value and it just makes the code and scoring systems more complex. I would personally be in favor of either defaulting to `constantQuestionValue=true` or just removing the variable-`current_value` code entirely and always treating the `current_value` as fixed.

This is indeed confusing and not very intuitive. I also don't see enough student "documentation" (or whatever counts as stuff students see to understand what to expect) to make this a practical gamification element (i.e., students probably don't understand it enough to be excited about trying it). I am in favour of either removing it, or changing `constantQuestionValue` to default to `true` and adding better clues in the question if it is set to `false`.

Given these constant value discussion are not directly related to #3601 I won't mess up with the documentation for it.

**Comment by mwest1066** [comment]
> This is indeed confusing and not very intuitive. I also don't see enough student "documentation" (or whatever counts as stuff students see to understand what to expect) to make this a practical gamification element (i.e., students probably don't understand it enough to be excited about trying it). I am in favour of either removing it, or changing `constantQuestionValue` to default to `true` and adding better clues in the question if it is set to `false`.

I completely agree. I've broken this out into #3618.

> Given these constant value discussion are not directly related to #3601 I won't mess up with the documentation for it.

That's reasonable.

**Comment by mwest1066** [comment]
Closing in favor of #3618, which proposes to remove `constantQuestionValue` entirely.

Docs for `triesPerVariant` was added in #3601
