### ISSUE TITLE
Cannot delete files from side-panel

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#2909]
Front-end component does not allow the user to delete a file when the attached file is viewed in the side-panel. One can still successfully delete a file on the assessment view. 

![image](https://user-images.githubusercontent.com/7872295/90910202-cdbe9500-e38b-11ea-87fa-b141853d82cd.png)

**Comment by jonatanschroeder** [comment]
This is no longer a bug.
