### ISSUE TITLE
Groupwork permission checkboxes

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#2924]
When I check Join Groups, Create Groups, and Leave Groups, the checkboxes don't stay checked when re-opening config. Student Permissions at the top indicates that those settings have been applied, but it would be nice to have the checkboxes reflect the current status of the permissions when opening

**Comment by glherman** [comment]
Actually, it looks like the permissions might be getting lost sometimes. After I switched my effective user mode to student and then returned, my permissions got lost.

**Comment by glherman** [comment]
Yeah, already accidentally deleted my permissions by not re-checking the boxes.

**Comment by frankyhao** [comment]
I'll edit this part later, so the checkboxes will be shown according to the current status. Instructors will not need to re-checking the boxes everytime.
