### ISSUE TITLE
Sync error indicator does not indicate what it is

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2925]
If we have a sync error in an `infoAssessment.json` file (for example) then we render a red cross next to the assessment on the instructor assessments page. But there is no indication about what that red cross means, and clicking on it doesn't reveal any further information or take you anywhere.

**Comment by tdy** [comment]
Saving from slack:
> it means the `sync_errors` (or maybe `sync_warnings`?) column in the `assessments` table (or `questions` -- anything that can be synced) is not empty

**Comment by mwest1066** [comment]
This also applies to sync warnings, which display a yellow triangle with no extra info. It would be great to have a popover on these.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/875833/127708557-780cb8b3-2b4d-4820-9f11-0e9d2a3f3451.png">
