### ISSUE TITLE
Gradebook duplicating entries for some users

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#2927]
Screenshot shows two rows of the a gradebook. First row is normal. (Number of entries matches number of assignments.) All other rows in the gradebook appear normal like this. Second row is the outlier. It has double the spaces expected.

![Screen Shot 2020-08-24 at 11 06 18 AM](https://user-images.githubusercontent.com/9003346/91069400-e1d0f380-e624-11ea-8220-9858d8b06863.png)

**Comment by tdy** [comment]
The duping is occurring like this:

Q1 | Q2 | E1 | E2 | | | | |
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 
q1_score | q2_score | e1_score | e2_score
q1_score | q1_score | q2_score | q2_score | e1_score | e1_score | e2_score | e2_score
q1_score | q2_score | e1_score | e2_score
q1_score | q2_score | e1_score | e2_score

So far I've noticed that the dupes are students who have taken your course previously (though possibly just a red herring). I'm guessing this has something to do with the group changes in `instructorGradebook.sql`.

**Comment by mwest1066** [comment]
Yep, I bet the group changes are responsible.

**Comment by zhining4** [comment]
I will fix that soon.

**Comment by daviddalpiaz** [comment]
Update: The number of users with this duplication is growing. Also, I have now seen at least one user that has each record tripled.

**Comment by zhining4** [comment]
I have fixed and tested that, it should work now. Just wait for the merge!
