### ISSUE TITLE
Workspace question requires `workspace` directory

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#2942]
When developing locally on Docker, if you write a question involving workspaces but do not have `workspace` as a subdirectory, you will get the error

```
error: Error from startup(): Error: ENOENT: no such file or directory, scandir '/course/questions/[my-question]/workspace'
```

and the workspace will fail to open.  I did not see anything in the documentation stating that this directory was necessary.  I would suggest simply adding something to that effect to the docs.  Or, if it is possible, PL could create this directory automatically if it does not exist.

**Comment by tdy** [comment]
Ah oops, forgot to document this. Thanks!

Just as an FYI before the docs get updated -- we copy the contents of `/course/questions/.../workspace` into the workspace image's home dir (e.g., starter code, readme, etc).

> Or, if it is possible, PL could create this directory automatically if it does not exist.

@mwest1066 thoughts?

**Comment by mwest1066** [comment]
I think we should allow the question to not have a `workspace` directory, in which case we would just not copy any initial files. We could make an empty `initial.zip` in this case?
