### ISSUE TITLE
Display uploaded files for File questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#295]
Suggested by @lotrfan.

Display inline for text format files, or download/view links for binary.

@zillesc makes the good point that we shouldn't base the inline/link choice by sniffing the file contents, because students sometimes upload a binary file when they were supposed to upload text, and seeing a horrible mess displayed should prompt them to reconsider.

**Comment by zillesc** [comment]
Here's how I showed students what they had uploaded.  No promise that this is pretty.   Look for 'uploadedContents'

[question.html and client.js](https://gist.github.com/zillesc/327a1eea054a80d44397)

**Comment by mwest1066** [comment]
Implemented in v3 file upload elements.
