### ISSUE TITLE
Home page jumbotron looks weird in safari

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#2956]
Chrome:
<img width="911" alt="Screen Shot 2020-08-27 at 7 00 20 PM" src="https://user-images.githubusercontent.com/14169175/91506525-e94c0300-e897-11ea-95c3-7224994ff4e5.png">

Safari:
<img width="859" alt="Screen Shot 2020-08-27 at 7 00 14 PM" src="https://user-images.githubusercontent.com/14169175/91506537-f10ba780-e897-11ea-8d8b-a216b5c107ab.png">

Since this is the home page and is meant to make a good impression to all, consider using vanilla styling in the jumbotron so that it looks nice in safari (for example) as well as chrome.

**Comment by tdy** [comment]
Hmm on my end I can only reproduce this if my Safari is zoomed out at <100%. I'll see if I can fix this or just ditch the `fa-stack` circles if not.

**Comment by jonatanschroeder** [comment]
Is this still the case with the latest updates in the home page? I don't have access to Safari to test.

**Comment by nwalters512** [comment]
I cannot reproduce this at any zoom level.
