### ISSUE TITLE
Groupwork assessments sometimes don't allow students to pick own groups

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3016]
https://prairielearn.engr.illinois.edu/pl/course_instance/118734/assessment_instance/1670236

This assessment allows students to create, join, and leave their own groups but in student view I get the following:

![image](https://user-images.githubusercontent.com/1790491/91865929-8a8bde00-ec37-11ea-92f5-be8960ff0f2e.png)

(cc @mfsilva22 )

**Comment by mfsilva22** [comment]
I get the same issue. I created on assessment with the group feature:

"uuid": "57647020-8252-46CE-ABD0-39CAF4CB1876",
  "type": "Homework",
  "title": "Errors, Big-O notation, plots",
  "set": "Lecture",
  "number": "3",
  "groupWork": true,
   "allowIssueReporting": false,

and I use the config setting 

![image](https://user-images.githubusercontent.com/12501485/91911674-3274cc00-ec77-11ea-8f5f-e5db2045852d.png)

I am set as instructor for the course, and in the instructor view, I can see all the questions without issue. If I click the Student View button, I get the same error reported above.

**Comment by frankyhao** [comment]
@mfsilva22 just wanna confirm, is this a problem still consistently existing recently? I still did not get to reproduce the issue successfully.

**Comment by frankyhao** [comment]
Mariana recently solved this issue by putting herself into a group first. I am closing this issue because the entire authn system for PL is going to be changed by another PR
