### ISSUE TITLE
Instructor information box does not render Duration correctly

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3025]
See the screenshot below. I guess we haven't formatted the duration into a string inside the SQL?

<img width="1120" alt="Untitled" src="https://user-images.githubusercontent.com/875833/91990639-98089d00-ecf7-11ea-864c-f879dc99bffe.png">

**Comment by echuber2** [comment]
Related? https://github.com/PrairieLearn/PrairieLearn/issues/2149

**Comment by jonatanschroeder** [comment]
Resolved in #9998.
