### ISSUE TITLE
Exam may create test with incorrect number of questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#308]
As @lotrfan points out in #306, using this [`info.exam.json`](https://gist.githubusercontent.com/lotrfan/839f7793b412d8617d15/raw/e63d72c1812ccb250f104950fc4b5591a9f5a2a4/info.exam.json) generates tests with sometimes 4 and sometimes 5 questions. It should always be 5, so something is wrong with the randomization.

**Comment by lotrfan** [comment]
My guess was that it was picking 2 questions from the first group and 3 from the second, but the second group only had 2 questions in it

**Comment by mwest1066** [comment]
Yep! I was just writing up this fact. Detailed explanation for reference below.

The reason this is happening is that we are asking for 5 questions, but we are giving two groups, one of which has 3 questions and the other of which has two questions. The way `randCategoryChoices()` works means that we will either choose (3,2) or (2,3) questions from the two groups. The first of these is fine, and means that we will choose all the questions, but the second is impossible because there are only 2 questions in the second group, so we can't choose 3 of them.

This manifests as a call to `randNElem()` asking for 3 members of an array that only has two elements in it. This just returns both elements, which avoids failing but doesn't give a good outcome.

**Comment by mwest1066** [comment]
To fix this properly we need to either check the test `info.json` and error if there aren't enough questions in each group, or we need to change the randomization to avoid this situation.

I think we haven't hit this bug in production because everyone using this type of test either had exactly the correct number of questions per group, or they had very large question pools where the issue won't arise.

I'm tempted to not fix this bug right now, because I feel like we need to think more about this whole way of specifying question pools for exams. This array-of-arrays-of-arrays format is not very friendly.

**Comment by mwest1066** [comment]
I'll leave this issue open so we don't forget about it, but I'm removing it from the milestone.

**Comment by mwest1066** [comment]
Eliminated by PLv2.
