### ISSUE TITLE
Don't set workspace hosts unhealthy if the error was due to the container

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3081]
As @nicknytko pointed out, we currently set the workspace host to unhealthy if there is any error during launch: https://github.com/PrairieLearn/PrairieLearn/blob/05e00bfa577ec2d4edd0d40085ecb56419acc7c2/workspace_host/interface.js#L1124

However, these errors might be caused by problems with the workspace itself. Maybe the instructor set an invalid image name. Maybe the image has an error inside it that means it can't start up correctly.

Instead of always setting the host to unhealthy, we should just set the workspace to `stopped` (with an appropriate error message) and return. This would be probably be easier to implement if we rewrite this function as async/await rather than using `waterfall()`. It could be something like:

```
try {
    ...
    await _getInitialZipAsync(); // errors from this will be caught by the top-level catch which will set host to unhealthy
    ...
    try {
        await _pullImage(); // errors from this will be caught immediately
    } catch (err) {
        workspaceHelper.updateState(workspace_id, 'stopped', `Error! Unable to pull image. Click "Reboot" to try again. Detail: ${err}`);
        return; // immediately exit from the initSequence(); don't set host to unhealthy
    }
    ...
} catch (err) {
    workspaceHelper.updateState(workspace_id, 'stopped', `Error! Click "Reboot" to try again. Detail: ${err}`);
    markSelfUnhealthy((err2) => {...});
    ...
}
```

**Comment by tdy** [comment]
Does this resolve the following item from #2935? Or is there more to be done for this:

> Don't automatically go to unhealthy if we fail to launch a workspace. This could occur due to user error such as an invalid image name. Instead use a docker daemon health check like PrairieGrader.
