### ISSUE TITLE
Fix websocket proxying issue on workspaces

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3089]
On prod websocket proxying will sometimes break until all servers are restarted.  This seems to be related to the fact that we are running multiple frontend servers on one host?

When this bug occurs, all websocket connections will get denied from the proxy.  This breaks code execution on Jupyter and the whole interface for vscode in general.

**Comment by mwest1066** [comment]
I see errors like:
```
{"message":"Error proxying workspace request: Error: connect EHOSTUNREACH 10.0.0.168:19397","level":"error","timestamp":"2020-09-11T12:34:12.050Z"}
```

**Comment by mwest1066** [comment]
This has been fixed for a while now. Closing.
