### ISSUE TITLE
upgrade psql clients to 12

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#3099]
I noticed our plbase environments are still using the v11 clients. We should investigate upgrading to 12.

https://github.com/PrairieLearn/PrairieLearn/blob/51a5e0942eaeb8f1118fd79a09d2d99c09146fef/environments/centos7-plbase/plbase-install.sh#L11

**Comment by mwest1066** [comment]
I've been holding off on this because AWS Aurora only supports 11 at the moment and we might want to switch to that.

**Comment by nwalters512** [comment]
We're now running on (and require) Postgres 15.
