### ISSUE TITLE
SPIKE: Element Inheritance

### ISSUE THREAD

**Issue by bevansm** [PrairieLearn/PrairieLearn#3101]
- How does element inheritance work?
- What flags should be "reserved" keys?
- How does a "blank" element without student input work?

**Comment by mebird** [comment]
- python, question writing:
  - how do we validate if a question should be validated for the attribute?
     - we need to have defined keywords. `arg
     - it doesn't make sense to enable all features for all elements (i.e. the checkboxes of multiple choice questions)
       - feature toggles? do we instead stray away from inheritance and towards offering helper functions which will help do everything?
       - ideally we'd just do a class type inheritance, but this is python we're talking about... with a bunch of pre-existing code. how do we do this without mass rewrites?
     - well defined elements should be using `pl.check_attribs` to validate html attributes. in order to avoid errors thrown left and right, we should append scores onto this.
  - every question seems to be responsible for its own grading display logic :/

**Comment by mebird** [comment]
- ok. inheritance is going to be nasty.
  - wrapper as a way to attach an attribute
  - not all elements handle partials/weight -> pre-req is for them to do that, since we have rendering set up
- let's think of a top level wrapper. must be direct on element. if there's more than one child, error thrown.
  - validate this like pl-overlay
  - one child, must have partials, weight, state attached
  - do we attach state on via manual grading?
    - state should be via manual... manual should be state mangagement/ui, child element should still be managing score & weight
    - we can look at implicitly attaching scores later -- is there any way to check if the child element is already rendering this? i really, really, don't want to do it as is :/
    - this would have to be a hook type refactor for state
- we should be able to pass through some sort of list and then conditionally change ui state
 - ok, basic red box around div in "manual" mode, otherwise, w/e
 - that way child elements don't have to be a part of their own rendering

**Comment by mebird** [comment]
- composition/decorators is probably the way to go
  - set of functions to get first child.
  - specify partials to attach to? -> need to enforce arg_name convention
  - basically anchors to partials
  - red box around outer div
- we should force elements to control their own partials at a low level.
  - how do we deal with file elements?
- we should have a "manual grading" box that's just a "null element"
- react composition > inheritance here.

**Comment by mebird** [comment]
- let's do composition
- single wrapper, single purpose

**Comment by mebird** [comment]
- we need to look into states and how we handle these -> leave in a todo for all of this for now
  - `grading_jobs` => table that shows old grading events
  - we already update this
  - we can add a manual flag there
- bare minimum ui time

**Comment by eliotwrobson** [comment]
Can this issue be closed? It doesn't seem like there's a concrete action item here, and this has been moved to done on the corresponding project.

**Comment by nwalters512** [comment]
I think it's marked as done because the corresponding project was closed. I agree there's nothing actionable here. If anyways wants to continue talking about this, a Discussion is probably the right place to do so.
