### ISSUE TITLE
Add assessment-level toggle to turn off attached files widget

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#3102]
Some courses that collect a lot of files for manual grading have described issues with students not following instructions and attaching files in the "attach files" sidebar widget, which was meant for a different purpose in the CBTF originally.

Maybe there should be an assessment-level option to toggle whether that widget will appear at all.

Related: this other bug with the widget UX. https://github.com/PrairieLearn/PrairieLearn/issues/2909

**Comment by nwalters512** [comment]
This was implemented in #10426.
