### ISSUE TITLE
Enrollment error for LTI logins is unhelpful

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3109]
At the moment the enrollment page hard-rejects LTI logins: https://github.com/PrairieLearn/PrairieLearn/blob/51a5e0942eaeb8f1118fd79a09d2d99c09146fef/pages/enroll/enroll.js#L13

We are getting reports that students don't know what to do about this. I guess we should give them a nicer error message and maybe a button that says "Login again with a regular account" that bounces to a logout that bounces again to login?

**Comment by echuber2** [comment]
In case we have multiple courses using LTI at once and the same student also is trying to log in conventionally, I had thought it might make sense to somehow sandbox these identities that are logged in at the same time and let the user switch between them with a dropdown in the top bar or something. On the other hand, Dave had previously expressed that we should move towards disallowing LTI users to move around PL freely and fence their interactions into the one assessment they had LTI-linked into. In that case, perhaps it would still make sense to sandbox the identity to that one assessment view, but not bother the user with needing to toggle between identities (or log out and in).

**Comment by nwalters512** [comment]
This was closed by #5281. We'll be improving how LTI authn/authz works when working on Canvas integration (https://github.com/PrairieLearn/PrairieLearn/pull/5543).
