### ISSUE TITLE
Only send workspace heartbeats when page is visible

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3112]
To be able to stop workspaces faster, it would be good to use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) in the client and only send heartbeats when the page is visible. This would allow us to stop the workspace when the tab has been backgrounded for too long.

**Comment by tdy** [comment]
Workspace heartbeats are emitted here: https://github.com/PrairieLearn/PrairieLearn/blob/b7c3105ccd65bbb6316ccf5bf13cac26f235cc68/pages/workspace/workspace.ejs#L184-L188

**Comment by nwalters512** [comment]
This was done in #7196.
