### ISSUE TITLE
Remove SSO logouts and just remove PL authn cookie

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3113]
At the moment the "Logout" button tries to do an actual SSO logout. This leaves the user on an unhelpful page without any easy way to login again. This makes it harder to do things like let a user logout and login again for #3109

**Comment by trombonekenny** [comment]
I think we should do both (delete the cookie and do the SSO logout). Maybe we could ask the browser to launch a different window for the SSO sign out and redirect the current window back to the PL login?

**Comment by nwalters512** [comment]
Only legacy Shibboleth authentication will redirect to the SSO logout page; our other authentication methods no longer do this.
