### ISSUE TITLE
Check query planner for `chunks_insert`

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3121]
Because of the LEFT JOINs in `chunks_insert` it is not clear to me that the query planner will use the index for the `assessments` join. We should check this once things are deployed. It's not a problem for the moment because `assessments` is currently a small table so seq scans won't be too bad.

**Comment by nwalters512** [comment]
@mwest1066 I don't think we've hit any issues with this in production, do you think this is safe to close out?

**Comment by mwest1066** [comment]
We are seeing only very occasional seq scans on `assessments` (I see 7 in the past week) so I guess this is ok.
