### ISSUE TITLE
Element caching does not work with chunks

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3123]
I believe this will lead to a bug where a PL server won't have up-to-date course element files if the elements were previously cached. In other words, a server will *never* get new course chunks once it has an entry in `courseElementsCache`. Once we throw multiple servers into the mix, and especially with syncs happening on different machines than actually serve questions, the course element cache won't work in its current form. There's a couple potential solutions here, I think:

* Key the cache on course ID *and* Git hash - this will invalidate the cache when a sync occurs, because a new hash will be associated with the course.
* Eliminate the cache entirely. Very robust, less efficient. a.k.a. "caching is hard, let's not."

The former is my preferred strategy. Anyone have any other thoughts?

_Originally posted by @nwalters512 in https://github.com/PrairieLearn/PrairieLearn/pull/2891#discussion_r487492492_

**Comment by mwest1066** [comment]
Apparently @nicknytko already fixed this in #2507

**Comment by nicknytko** [comment]
Yeah, and to be honest I'm not sure this is a new bug with the chunking functionality.  On the current live server, I think that course element info won't get updated until a server restart.  I just don't think it's been a big issue until now because course elements seem to be very rarely updated, and I think most people would be developing them locally (thus not running into this).

**Comment by mwest1066** [comment]
Excellent point. I now seem to remember talking about this recently. Let's continue to ignore it and get #2507 merged soon 😄

**Comment by nwalters512** [comment]
We do actually reload a course's elements as part of the syncing process:

https://github.com/PrairieLearn/PrairieLearn/blob/57a2255d372f457bc6655b37b60e40bf1458c240/sync/syncFromDisk.js#L50

But independently of chunks, this breaks as soon as we have multiple servers in the mix.

**Comment by mwest1066** [comment]
> But independently of chunks, this breaks as soon as we have multiple servers in the mix.

Yep, I think we realized this recently. We've been running four PL servers (on one host) since April and no one has noticed yet that course elements don't reload properly 😄

**Comment by mwest1066** [comment]
I think that this will actually be better with chunks? We should pull new element chunks whenever we are about to run question code, and that would be the right time to upload the element cache locally?
