### ISSUE TITLE
Set up the local dev environment to mimic chunks behavior

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3125]
At the moment we server local dev directly from the course directory. In contrast, chunk servers will only have the minimal required content (e.g., a single question and `serverFilesCourse`). Code that loads a file out of another question will thus work in local dev, but fail in production. There is code in #2891 to symlink directories to make local dev look more like prod. We should activate this by default for local dev.

**Comment by nwalters512** [comment]
Closing as a duplicate of #7348, which has slightly more information in the issue description.
