### ISSUE TITLE
MC questions with more than 26 options display weirdly

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3133]
If you have more than 26 visible answers for `pl-multiple-choice` you get this:
<img width="56" alt="Untitled 2" src="https://user-images.githubusercontent.com/875833/93132931-0d7f5080-f69c-11ea-9da0-2279c8aa8f56.png">

**Comment by tdy** [comment]
We're using this to get the key, so it just keeps going down the unicode list after (z). What should the 27+ keys be? (aa), (bb), etc?

https://github.com/PrairieLearn/PrairieLearn/blob/8248232e447438610040d52941bb40d92d44e74b/elements/pl-multiple-choice/pl-multiple-choice.py#L188-L189choice.py#L189

**Comment by mwest1066** [comment]
Fixed by #3254
