### ISSUE TITLE
Cache docker layer info for percentage calculation

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3152]
Here's a simple idea that I think might significantly improve the accuracy of our percentage calculations. This would replace #3105 .

The idea is to cache the information about layers and their sizes. This way we'll be inaccurate on the first pull of an image, but all subsequent pulls should be much more accurate. We compute and cache `progressDetailsInit`, which is an object that we will use to initialize `progressDetails` (that is, it has all the totals, but all the current values set to zero).

* [ ] Replace https://github.com/PrairieLearn/PrairieLearn/blob/03f3c1c6882ad27601d2ecd13534f645c2115368/workspace_host/interface.js#L886 with an attempt to get the cached information:
```
let progressDetails = await cache.getAsync(`workspaceProgressInit:${workspace_image}`) || {};
let progressDetailsInit = {};
```

* [ ] Add the update of the initial value at https://github.com/PrairieLearn/PrairieLearn/blob/03f3c1c6882ad27601d2ecd13534f645c2115368/workspace_host/interface.js#L903
```
progressDetailsInit[key] = {...output.progressDetail, current: 0};
```

* [ ] Once we've got all the info we should set the cached value at https://github.com/PrairieLearn/PrairieLearn/blob/03f3c1c6882ad27601d2ecd13534f645c2115368/workspace_host/interface.js#L894
```
cache.set(`workspaceProgressInit:${workspace_image}`, progressDetailsInit);
```

**Comment by nwalters512** [comment]
We could also grab this information _as_ we sync the image into the image registry, which would help ensure that for all future images, we never have a workspace boot where we don't have information about layer sizes (+/- cache evictions).

**Comment by mwest1066** [comment]
I think we actually only need to cache the `total` and to use this as the first initialization value.
