### ISSUE TITLE
Confirmation dialog for unsaved file even though file was submitted

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3153]
I'm running an exam in TA role and student view\. One of the questions is a file-upload question with external grading. Once the grading finishes and I get 100%, the question is closed and I can't submit any longer. But if I then click on "Next question" or "Assessment Overview", a warning is given: "Leave site? Changes you made may not be saved." Even though the file was already submitted, and wasn't changed again. This was tested on Chrome and Edge Chromium.

This was discussed on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1600474411047100

I'm not posting the question given it's being delivered to students this week, but can provide in private if required.

**Comment by tdy** [comment]
This occurs when certain query strings are not accounted for. Not sure exactly what circumstances cause these query strings to appear:

* On submission, the form is serialized with variant/csrf query params:
`_file_upload_65eba3ecfc2c4de85f2486d1360bfd6698ef8c63=%5B%7B%22name%22%3A%22lab1.c%22%2C%22contents%22%3A%22I2luY2x1ZGUgPHN0ZGlvLmg%2BDQojaW5jbHVkZSA8c3RkbGliLmg%2BDQojaW5jbHVkZSA8bWF0aC5oPg0KDQppbnQgbWFpbih2b2lkKSB7DQogIGRvdWJsZSB0Ow0KICBwcmludGYoInQ9ICIpOw0KICBzY2FuZigiJWxmIiwgJnQpOw0KICBwcmludGYoIlxueD0lLjNsZlxuIiwNCgkgOSpzcXJ0KHQpKnBvdyhzaW4oNSp0KSwxKS83ICsNCgkgMypwb3coY29zKDIqdCksIDEpLzcNCgkgK3BvdygxLjAvOSx0KSk7DQogIHN5c3RlbSgiUEFVU0UiKTsNCiAgcmV0dXJuIDA7DQp9DQo%3D%22%7D%5D&__variant_id=1&__csrf_token=MjYzZDZiMTgxZWFhMWJmMjQ1MTlhN2E0ZDNlZDdjZWExMGU0YzdhZDdlNDQwNjBmY2E5MDI3M2RkZTZkNTljMQ.kfahdma8.eyJ1cmwiOiIvcGwvY291cnNlX2luc3RhbmNlLzEvaW5zdGFuY2VfcXVlc3Rpb24vMS8iLCJhdXRobl91c2VyX2lkIjoxfQ`

* On reload, those params are gone (thus the confirmation dialog):
`_file_upload_65eba3ecfc2c4de85f2486d1360bfd6698ef8c63=%5B%7B%22name%22%3A%22lab1.c%22%2C%22contents%22%3A%22I2luY2x1ZGUgPHN0ZGlvLmg%2BDQojaW5jbHVkZSA8c3RkbGliLmg%2BDQojaW5jbHVkZSA8bWF0aC5oPg0KDQppbnQgbWFpbih2b2lkKSB7DQogIGRvdWJsZSB0Ow0KICBwcmludGYoInQ9ICIpOw0KICBzY2FuZigiJWxmIiwgJnQpOw0KICBwcmludGYoIlxueD0lLjNsZlxuIiwNCgkgOSpzcXJ0KHQpKnBvdyhzaW4oNSp0KSwxKS83ICsNCgkgMypwb3coY29zKDIqdCksIDEpLzcNCgkgK3BvdygxLjAvOSx0KSk7DQogIHN5c3RlbSgiUEFVU0UiKTsNCiAgcmV0dXJuIDA7DQp9DQo%3D%22%7D%5D`

**Comment by tdy** [comment]
@mwest1066 @nicknytko Do you know which situations cause a question form to be submitted with extra `__variant_id` and `__csrf_token` params? Would it be reasonable to just strip those params when we diff the form states?

**Comment by echuber2** [comment]
I think the routing middleware bounces query strings to the end, maybe that's not cooperating here?

**Comment by echuber2** [comment]
This is what I was referring to, but maybe it doesn't apply here at all:

https://github.com/PrairieLearn/PrairieLearn/blob/5cce4fa7760abbcad3819e8997eff340cc6c676f/server.js#L504-L512
