### ISSUE TITLE
Width stretches past actual viewport

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#316]
See the top RHS.

<img width="1920" alt="screen shot 2016-03-16 at 15 58 43" src="https://cloud.githubusercontent.com/assets/877821/13828566/1500786e-eb90-11e5-8e1b-ee2bb8bf8bba.png">

**Comment by mwest1066** [comment]
I'm not sure exactly what is causing the problem or how to fix it. We have [a hack](https://github.com/PrairieLearn/PrairieLearn/blob/master/frontend/css/local.css#L29) already in the CSS to mitigate this by shifting the logout button left.

This is going to need someone much more expert in CSS than me to fix, I'm afraid :-)
