### ISSUE TITLE
Cron errorAbandonedJobs is not multi-server safe

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3160]
`cron/errorAbandonedJobs.js` calls https://github.com/PrairieLearn/PrairieLearn/blob/622417be74eb5f4f03dcf345e1dc631fd1690154/lib/server-jobs.js#L345

This checks which running jobs are not present in the _local_ server's job list: https://github.com/PrairieLearn/PrairieLearn/blob/622417be74eb5f4f03dcf345e1dc631fd1690154/lib/server-jobs.js#L349

Any missing jobs are killed.

This will kill any jobs started by a different server, because they won't be in the local server's job list.

To fix this, we should store the server `instance_id` in the `jobs` (or `job_sequences`?) table so we can only kill our own jobs. Maybe we should add a new table called `hosts` that has one row per VM instance so we can refer to them. This table could have a `heartbeat_at` column that we update every 10 seconds or so.

It would also be good to add a cron job that looks for jobs that belong to hosts that are no longer alive (last heartbeat too long ago) and kills them.

**Comment by nicknytko** [comment]
I think this should be okay, since we're only running cron on the main server anyway?  Or do we want to move away from this in the future?

**Comment by mwest1066** [comment]
> I think this should be okay, since we're only running cron on the main server anyway? Or do we want to move away from this in the future?

I think we should fix it so that we can run multiple main servers if needed (and at some point we might figure out a scheme to have chunk servers handle all the routes of main servers, in which case it would be nice to be truly multi-server safe).

I don't think this is very high priority, however, for the reason you mentioned (we can avoid multiple main servers). This is why I didn't label this as "high impact" 😄

**Comment by nwalters512** [comment]
This caused a few impacts to staff lately - a job was killed before it could release its lock, and that caused a few courses to be temporarily un-syncable.

**Comment by nwalters512** [comment]
This is appearing more regularly. This is the root cause of #6454.
