### ISSUE TITLE
Latex rendering error

### ISSUE THREAD

**Issue by BenjaminCosman** [PrairieLearn/PrairieLearn#3164]
![image](https://user-images.githubusercontent.com/4876098/93893278-4e7df300-fca2-11ea-89ed-a05c653fb3af.png)
![image](https://user-images.githubusercontent.com/4876098/93893677-c3e9c380-fca2-11ea-92d2-305189511d43.png)

Latex Markdown involving two or more underscores does not render properly - it looks like the Markdown rule treating them as italics is taking precedence over the Latex rule treating them as subscript indicators.

**Comment by mwest1066** [comment]
The markdown rendering happens first (the latex is rendered client-side by mathjax), so I guess this isn't too surprising. Does it work if you write `<span>$a_2 b_8$</span>` in the markdown, to protect the math?

**Comment by BenjaminCosman** [comment]
No, <span>$a_2 b_8$</span> identically to $a_2 b_8$

**Comment by mwest1066** [comment]
It looks like PL is using [showdown](https://github.com/showdownjs/showdown) to render the markdown: https://github.com/PrairieLearn/PrairieLearn/blob/b7c3105ccd65bbb6316ccf5bf13cac26f235cc68/elements/pl-file-editor/pl-file-editor.js#L50

Maybe we should turn on the `literalMidWordUnderscores` option? Docs at https://github.com/showdownjs/showdown

**Comment by mwest1066** [comment]
@BenjaminCosman if you could make & test a patch for this and submit a PR then that would be awesome!

**Comment by BenjaminCosman** [comment]
Fixed by #3355
