### ISSUE TITLE
Add a Manual Grading "Element" to the Element Library

### ISSUE THREAD

**Issue by bevansm** [PrairieLearn/PrairieLearn#3171]
**Adding Manual Grade Flag to Elements**

As an instructor who wants to use manual grading, I want to add a "manual=true" flag in an HTML element, so that I can specify that the element is for manual grading.

- Can all elements support the "manual=true" flag? ie. pl-file-upload
- Is it possible to implement this for all elements given time constraints? (In other words, is there a lot of programming for each element to implement this). Is there a workaround?
- What is the ideal JSON data structure produced by an element that is flagged "manual=true"? (the data exported to CSV)

Blocked by:
- [Manual Grading "Element" Spike](https://github.com/PrairieLearn/PrairieLearn/projects/9#card-45195508)

**Comment by mebird** [comment]
- We don't have the endpoint set up to submit the form, but this is a good first pass of things

**Comment by jonatanschroeder** [comment]
All the rationale for this element has been replaced with other implementation strategies. Closing.
