### ISSUE TITLE
Sometimes the graded files are not properly copied to the workspace

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3176]
In a few cases students (and even myself in one case) have been able to open the Workspace, but the graded file is not found there. Typically Resetting the workspace is a decent workaround, unless they had opened the Workspace to edit a previously saved file, in which case Resetting would lose all their previous work (see #3172).

This is sort of random, and I can't easily find a scenario where this can reliably be reproduced.

**Comment by tdy** [comment]
It's possible PL Canada hasn't received patch #3146 yet (cc @mwest1066).

If it is the same bug, `Reboot` should suffice (i.e., shouldn't need the destructive `Reset`).

**Comment by jonatanschroeder** [comment]
Students report that reboot doesn't work.

**Comment by mwest1066** [comment]
Can you tell us a workspace ID (URL) or student/question/assessment that had this bug?

**Comment by jonatanschroeder** [comment]
We haven't worked with workspaces for a while, so anything that existed would probably have died already. I'll try to reproduce it and let you know, but it won't be in the next few days.

**Comment by mwest1066** [comment]
Sounds good

**Comment by mwest1066** [comment]
Fixed by the storage rewrite in #3728
