### ISSUE TITLE
disable simultaneous logins

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#3192]
ECE 310 staff pointed out that multiple simultaneous logins by the same person could be an attack vector for cheating during a proctored exam. We should investigate logging and reporting it somewhere if multiple auth cookies are working on the same assessment at the same time. Or better, enforce only one active auth cookie when in `"mode": "Exam"`

Unfortunately, I think this will require smarter session management in PL than we currently have. But if we did switch to a more managed session framework it would not be too difficult to implement.

**Comment by echuber2** [comment]
Wasn't there also a browser extension people tried using to collaborate on the ace editor? That could allow remote driving even with only one login.

**Comment by echuber2** [comment]
How would this improved session management go along with LTI? I think LTI embeds have the same vuln right now (e.g., a co-conspirator Bob logs into Coursera using Alice's account, to help Alice on the exam--I think their LTI launchers both launch into the same session).

Sometimes students have bad internet connections and need to reconnect during the exam, so I would recommend having a "newer" auth cookie invalidate ALL existing ones on the server, including the new one. If you only invalidate older ones, this would mean that someone could reconnect and continue, but a co-conspirator Bob trying to help would knock Alice out of the exam, and then Bob could still peruse the exam contents without monitoring.

Instead, I think it should work like this: if Bob logs in while Alice is already in the exam with the proctor, it locks both Bob and Alice's PL session, requiring the proctor to enter the PL password again to continue (and display a message that something strange is going on, which the proctor can note). This would still work fine if Alice needs to reconnect legitimately; the proctor will just have to enter the password again.

**Comment by trombonekenny** [comment]
Yes, exam passwords should be refactored to fit into improved session management too.

**Comment by nwalters512** [comment]
While we still allow simultaneous logins, we now collect and log "fingerprints" (IP, session ID, user agent) for actions taken on assessment instances: https://prairielearn.readthedocs.io/en/latest/assessment/#client-fingerprint-tracking-and-changes. These fingerprints can be used to identify when an assessment instance is being worked on from more than one browser.
