### ISSUE TITLE
Restrict networking in workspaces

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3193]
(breaking this out of #2504)

Add an option like `allowNetworkAccess` (default `false`) for workspaces. Possible implementation strategies:
* https://stackoverflow.com/a/47008421
* https://www.eisfunke.com/article/docker-wireguard-systemd.html

**Comment by echuber2** [comment]
Just bumping this issue; I think this may be important for fall CBTF if professors will still assume network access will be blocked.

**Comment by echuber2** [comment]
Dave added a fresh issue: https://github.com/PrairieLearn/PrairieLearn/issues/4498

**Comment by echuber2** [comment]
Maybe this too: https://gvisor.dev/docs/user_guide/networking/#disabling-external-networking

**Comment by echuber2** [comment]
Another resource: https://dev.to/andre/docker-restricting-in--and-outbound-network-traffic-67p

Perhaps you've already found a good option, though.

**Comment by mwest1066** [comment]
> Perhaps you've already found a good option, though.

Yeah, I ended up going with blocking network access via our infrastructure firewall setup.
