### ISSUE TITLE
Directory delete/unpack is a race condition while unpacking chunks

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3208]
When unpacking a chunk we currently delete and then recreate the targetDirectory: https://github.com/PrairieLearn/PrairieLearn/blob/b11c990682600c9e3b0b626747ad959eb6e338d5/lib/chunks.js#L699

This will cause an error for any other code that's currently accessing the question (for example).

To fix this, we could either add locking code or unpack into a temp directory and then move the temp directory over the old one atomically. See https://stackoverflow.com/questions/307437/moving-a-directory-atomically

**Comment by nwalters512** [comment]
IIRC the temp+move/rename strategy was what we originally discussed when designing chunks - that's probably just an oversight on my part when this was implemented!

**Comment by mwest1066** [comment]
Haha, no worries, we haven’t hit this yet in production.
