### ISSUE TITLE
Downloaded "*_scores_compass.csv" from stats page does not compute extra credit correctly

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#322]
See, e.g., TAM 212 Homework 3A: Projectile motion. Students who completed the assignment before the "early submission" deadline should receive 130% credit, but the score export .csv gives these students 100%.

**Comment by rbessick5** [comment]
I haven't checked any HW set which offers partial credit to late submissions, but I suspect that PL isn't discounting these scores correctly either (based on talking with Matt on Tuesday)

**Comment by mwest1066** [comment]
Fixed in ae648c1d0829c6b07fdec76486f5c3c8a6d4bc9b
