### ISSUE TITLE
Enforce file size limit for workspace graded files

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3224]
* [ ] Check file size of graded files:
    * [ ] `interface.getGradedFiles()`: check `fs.stat()`
    * [ ] `workspace.getGradedFilesFromS3()`: [check HEAD object](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property)
* [ ] Propagate error to end user
* [ ] Share size limit with file uploads (refactor to `config`): https://github.com/PrairieLearn/PrairieLearn/blob/5bc2995e7607845df849362470d7ac752d0b81d1/server.js#L187-L189

**Comment by nwalters512** [comment]
Config options for `workspaceMaxGradedFilesCount` and `workspaceMaxGradedFilesSize` were added in #6982.
