### ISSUE TITLE
Timed-out workspaces immediately stop again after reboot

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3227]
@gcevans reports a student whose workspace stopped due to timeout, but when they reboot the instance it is almost immediately stopped again. The workspace row in question is below.

```
prairielearn=> select * from workspaces where id = 9551;
-[ RECORD 1 ]------+--------------------------------------------------------------------------
id                 | 9551
state              | stopped
workspace_host_id  |
hostname           | ip-10-0-0-176.us-east-2.compute.internal:18386
launched_at        | 2020-09-30 14:57:38.513846+00
heartbeat_at       | 2020-09-30 13:29:03.421837+00
launch_uuid        |
launch_port        |
created_at         | 2020-09-29 07:43:50.085462+00
state_updated_at   | 2020-09-30 14:58:32.332581+00
message            | Connection was lost for more than 10 min. Click "Reboot" to keep working.
message_updated_at | 2020-09-30 14:58:32.332581+00
version            | 1
running_at         | 2020-09-30 14:57:44.380547+00
stopped_at         | 2020-09-30 14:58:32.332581+00
rebooted_at        | 2020-09-30 13:00:33.934046+00
reset_at           |
```

**Comment by mwest1066** [comment]
In the row above, note that the workspace was recently `launched_at` and then almost immediately `running_at`, but shortly after was `stopped_at`.

Weirdly, `rebooted_at` is a long time before `launched_at`.

**Comment by mwest1066** [comment]
Here's another one:
```
-[ RECORD 1 ]------+--------------------------------------------------------------------------
id                 | 10815
state              | stopped
workspace_host_id  |
hostname           | ip-10-0-0-196.us-east-2.compute.internal:23817
launched_at        | 2020-09-30 15:02:17.120108+00
heartbeat_at       | 2020-09-30 15:24:26.326909+00
launch_uuid        |
launch_port        |
created_at         | 2020-09-30 15:00:23.023672+00
state_updated_at   | 2020-09-30 15:34:33.065057+00
message            | Connection was lost for more than 10 min. Click "Reboot" to keep working.
message_updated_at | 2020-09-30 15:34:33.065057+00
version            | 2
running_at         | 2020-09-30 15:02:20.450614+00
stopped_at         | 2020-09-30 15:34:33.065057+00
rebooted_at        | 2020-09-30 15:01:07.716128+00
reset_at           | 2020-09-30 15:02:14.158158+00
```

**Comment by tdy** [comment]
The message is a heartbeat timeout. Are the heartbeats not being sent anymore after coming back? Like the socket died? Or maybe we're timing out before we receive new heartbeats or something?

**Comment by echuber2** [comment]
I bet this is related to #3226

**Comment by mwest1066** [comment]
@tdy I think for the first workspace I posted, the problem is that the heartbeat is old, because we only send heartbeats every five minutes. That is:

1. We reboot an old workspace and it starts running. In the first example, this was at `14:57:44`
2. At this point, `heartbeat_at` is still very old, because we haven't yet sent a new heartbeat. In the example, we have `heartbeat_at = 13:29:03`
3. The cron job runs to look for running workspaces without recent heartbeats, and it finds this one and stops it: https://github.com/PrairieLearn/PrairieLearn/blob/d1c6cf1f56ba9aadd491d0d34daf3a370fc80552/cron/workspaceTimeoutStop.sql#L8

The core problem is that we are not sending a heartbeat right when we start running. We can fix this by either:

1. Setting `heartbeat_at = now()` when we start running.
OR
2. Changing `workspaceTimeoutStop.sql` to not stop recently-started workspaces (before the first heartbeat has a chance to come in).

**Comment by tdy** [comment]
Is prod running a different heartbeat interval? I think we send heartbeats every 1 min, and the cron runs every 5 min, so I'm still a bit confused how they're instantly timing out.

> 1. Setting heartbeat_at = now() when we start running.

Yeah this makes sense. I could've sworn we already did this before, so this is either a regression or I'm just mixing something up.

**Comment by tdy** [comment]
> I think we send heartbeats every 1 min, and the cron runs every 5 min, so I'm still a bit confused how they're instantly timing out.

Ohh wait, we just recently lowered the cron interval to 1 min, so there's a race condition here with both being 1 min intervals.
