### ISSUE TITLE
Check exam statistics (observed weirdness with 

### ISSUE THREAD

**Issue by zillesc** [PrairieLearn/PrairieLearn#324]
My recent exam saw the following for the last two questions listed in the stats (stats have changed).  The first of the two questions had a higher response rate and lower average, but looks closer to what I'd expect to be the target for discrimination.  
<img width="594" alt="screen shot 2016-03-30 at 1 28 11 pm" src="https://cloud.githubusercontent.com/assets/1738461/14187382/61c23840-f748-11e5-937e-480af4101bb8.png">

**Comment by mwest1066** [comment]
Eliminated by PLv2.
