### ISSUE TITLE
Distinction in tab title/icon between local test and production environment

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3246]
It would be great to have an easy way to distinguish, in the tab title, the local testing environment from the production environment. Something as simple as adding `[TEST]` to the start of the title of the page would probably suffice. A different favicon would also be an alternative.

**Comment by mwest1066** [comment]
Great idea! In `pages/partials/navbar.ejs` and children we can check for `config.devMode` which is `true` when running locally and `false` in production. I'm not sure exactly what to put in the navbar, but I'd be happy to merge anything that looks reasonable.
