### ISSUE TITLE
Show UID of student who submitted answer (useful for groupwork)

### ISSUE THREAD

**Issue by astrosticks** [PrairieLearn/PrairieLearn#3248]
Currently, submissions on groupwork can leave the author of a submission a mystery to other teammates:

![image](https://user-images.githubusercontent.com/32315760/94836829-0e70eb80-03d9-11eb-9b26-7690465232db.png)

This makes it hard to reach out to the person who made the submission to get advice, give feedback, etc.

I would suggest showing the UID of the user who made a submission in the submission's description field, e.g. the above example can be reworded as `Submitted by user@domain.net at [timestamp]`. If the submission belongs to the student currently viewing the page, the field can instead say `You submitted at [timestamp]`.

**Comment by mfsilva22** [comment]
Great point! This goes well with the idea of adding the UID to the assessment overview (not yet available when instructors create the groups).

**Comment by astrosticks** [comment]
> this goes well with the idea of adding the UID to the assessment overview

Does this have an issue?

**Comment by mfsilva22** [comment]
It appears in "ideas" inside the "Group Work" project. I have not created an issue yet for this. I need to get the screenshots (I think Frankie was not able to reproduce this issue). I will try to do this now
