### ISSUE TITLE
Group members info not available

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#3249]
Here is an example of an assessment in Exam mode that uses group option where instructor sets the group. Note that I don't see the UI that includes the team members:

![image](https://user-images.githubusercontent.com/12501485/94843265-0f5a4b00-03e2-11eb-828c-340d32ff33b3.png)

![image](https://user-images.githubusercontent.com/12501485/94843307-226d1b00-03e2-11eb-8f3d-8f8224318253.png)

Here is an example of an assessment in Homework mode that students can create their own groups. Students have the information about team members:

![image](https://user-images.githubusercontent.com/12501485/94843789-ce166b00-03e2-11eb-9689-401443d8cb5f.png)

We should have the info about group members available for any assessment mode, any group formation option.

**Comment by frankyhao** [comment]
The group work mode #2914 for the exam is not merged yet because I still need to make a few changes. 
I'll try to get it done ASAP
