### ISSUE TITLE
Local autograder docs for WSL2

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3253]
All the autograder-related docs for Windows currently apply to WSL1. I seem to remember pl-help discussions about WSL2 gotchas, but I don't remember details. Like the jobs dir needs to be linux-side or something?

We should provide both WSL1 and WSL2 instructions where applicable:

* [External grading: running locally (on Docker)](https://prairielearn.readthedocs.io/en/latest/externalGrading/#running-locally-on-docker)
* [Workspaces: running locally (on Docker)](https://prairielearn.readthedocs.io/en/latest/workspaces/#running-locally-on-docker)
* And any others I've missed

**Comment by jonatanschroeder** [comment]
I can do some updates.
