### ISSUE TITLE
Checking of formula "correctness" for formula problems

### ISSUE THREAD

**Issue by DallasTrinkle** [PrairieLearn/PrairieLearn#326]
It would be helpful to run a minimal parser on "formula" questions--say, at the "save" step--so that if a student enters "sin((x)" they have an opportunity to correct it to "sin(x)" without getting it incorrect first. Likely would just need to check that it can be evaluated for a test set of inputs (which would need to be specified somewhere in the question... perhaps in the info.json file?).

**Comment by mwest1066** [comment]
Implemented in v3 `pl_symbolic_input` element.
