### ISSUE TITLE
Github changing default repo branch to 'main' from 'master'

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#3264]
Git course repos depend upon the default 'master' branch existing, but Github recently changed the default branch name to 'main' on new repositories. 

Depending on Github repository setup, this may result in an error on cloning new course repositories:

![image](https://user-images.githubusercontent.com/7872295/94965190-e607f080-04af-11eb-8177-95ffc85fc7ec.png)

**Comment by andrewstec** [comment]
After adding a `master` branch with the data, it works: 

![image](https://user-images.githubusercontent.com/7872295/94965291-12237180-04b0-11eb-9fe2-cde2c8e52f51.png)

**Comment by trombonekenny** [comment]
https://github.com/github/renaming

I'm not sure if this is our bug or GitHub's. It looks like they have some "coming soon" features that will map `master -> main` in different circumstances that seems like it would help here without us changing things.
