### ISSUE TITLE
Display workspace_logs in the instructor assessment instance log

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3267]
At the moment instructors don't have any visibility into what students are doing with workspaces. To partially address this, we should add all the events in the `workspace_logs` table to `sprocs/assessment_instances_select_log.sql` so they will show up on the instructor assessment instance Log view: https://github.com/PrairieLearn/PrairieLearn/blob/8915641f8d91e65a617defa5ff81f667451a1eef/pages/instructorAssessmentInstance/instructorAssessmentInstance.js#L40

**Comment by nwalters512** [comment]
Instructors can now access the logs by opening the workspace and clicking the "Logs" button.
