### ISSUE TITLE
Chunks are not pushed after sync errors

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3269]
At the moment the existence of `hadJsonErrors` on sync will block chunk generation:
https://github.com/PrairieLearn/PrairieLearn/blob/8915641f8d91e65a617defa5ff81f667451a1eef/pages/shared/syncHelpers.js#L150

The problem with this is that an error in one question will cause all chunk generation to stop. Under the new robust syncing model, other questions are still being synced and so instructors will see the updated questions (via instructor routes) but students will not (via student routes on chunk servers).

I think it's ok to unconditionally generate chunks for everything, whether or not we `hadJsonErrors`. I think we want to generate chunks even for objects that had errors, so that the student view is the same as the instructor view, whatever that is.

**Comment by nicknytko** [comment]
Do we also want to generate chunks if the sync itself failed?  i.e. `err` was non-null?  I'm unsure what sort of state we'd be in then.
