### ISSUE TITLE
Broken tools/load-test.js from falling slightly out-of-date

### ISSUE THREAD

**Issue by cbt-sys-adm** [PrairieLearn/PrairieLearn#3272]
### Two malfunctions in load-test script (maybe drifted out-of-date):
- [ ] The handy `tools/load-test.js` script seems to have fallen behind changes in page paths/routes.
  _(Minor tweaks needed in order to fetch the desired pages/links/questions)_

- [ ] In `middlewares/authn.js`, the ["load-testing override cookie" login-bypass](https://github.com/PrairieLearn/PrairieLearn/blob/8915641f8d91e65a617defa5ff81f667451a1eef/middlewares/authn.js#L32) fails to populate user identity.
  It calls `users_select_or_insert` but not `sql.select_user`, but [presumes results from `select_user`](https://github.com/PrairieLearn/PrairieLearn/blob/8915641f8d91e65a617defa5ff81f667451a1eef/middlewares/authn.js#L44-L49).
  _(Should mimic the two queries like ["bypass auth for local /pl/ serving"](https://github.com/PrairieLearn/PrairieLearn/blob/8915641f8d91e65a617defa5ff81f667451a1eef/middlewares/authn.js#L63) successfully does)_

- [ ] Minimal `--debug` flag could help diagnose/validate `load-test.js` behavior.

### Possible low-priority follow-ups (Should these be separate "enhancement" issue?):
- [ ] Perhaps another intermediary page-fetch or link-following step is appropriate for a fuller fix? _Am not sure._
- [ ] A couple other hard-coded values could use `--args` or mini config-file to ease overriding.
- [ ] Is unclear if the script intends or needs to lookup the Sp15 instance, since it seems to end up in the "course" questions anyway.
- [ ] Comments in `load-test.js` could briefly mention `authn.js` bypass & the "loadtest@prairielearn.org" fake user?
- [ ] Dump script results/stats in suitable format for import into a log/graph tool, maybe CloudWatch???

**Comment by mwest1066** [comment]
Thanks for bringing this up to date! It definitely bit rotted as the main server code had changes made to it. It would be great to add an entry in `tests/` to run `tools/load-test`, which would make sure we keep it up to date in the future.

**Comment by nwalters512** [comment]
`tools/load-test.js` is no longer in this repository.
