### ISSUE TITLE
Downloading assessment submissions with large files crashes server

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3281]
Trying to download `_all_submissions.csv` for an assessment with jupyter workspaces with large file submissions can crash the PL server: 

```
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: /PrairieLearn/lib/nonblocking-csv-stringify.js:44
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: return callback(null, chunks.join(''));
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: ^
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: RangeError: Invalid string length
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at Array.join (<anonymous>)
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at Stringifier.<anonymous> (/PrairieLearn/lib/nonblocking-csv-stringify.js:44:38)
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at Stringifier.emit (events.js:315:20)
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at Stringifier.EventEmitter.emit (domain.js:483:12)
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at endReadableNT (_stream_readable.js:1220:12)
Oct 04 17:40:45 ip-10-0-0-204.us-east-2.compute.internal node[47123]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
Oct 04 17:40:46 ip-10-0-0-204.us-east-2.compute.internal systemd[1]: prairielearn2.service: main process exited, code=exited, status=1/FAILURE
```

Related:

https://github.com/nodejs/node-v0.x-archive/issues/14170
https://github.com/nodejs/help/issues/1061

Not sure the best way to fix that is, but I suppose we should be stripping out file submissions anyway from `_all_submissions.csv`?

**Comment by mwest1066** [comment]
I think we just need to copy this: https://github.com/PrairieLearn/PrairieLearn/blob/05f78f0eb658c659667cab5c654834f088b7922a/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql#L110 to here: https://github.com/PrairieLearn/PrairieLearn/blob/05f78f0eb658c659667cab5c654834f088b7922a/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql#L147 to strip `_files`

**Comment by nwalters512** [comment]
We now use Postgres cursors and streaming file generation, which has alleviated the "string too big" problem documented here.
