### ISSUE TITLE
Rendering bug in pl-text (pl-drawing)

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3282]
Text gets shifted+clipped more and more as text length grows.

Reproducible using the moment of inertia example in [element/drawingGallery](https://prairielearn.engr.illinois.edu/pl/course/108/question/4942664/preview) by appending more and more characters to the integral:

<img width="250px" src="https://user-images.githubusercontent.com/2503508/95039943-c7fce480-0697-11eb-92bf-9d73380c8f6a.gif"/>

**Comment by tdy** [comment]
Also worth noting that even the unchanged demo has regressed. The two `x1="20"` tags were [**aligned as of Sept 20, 2019**](https://github.com/PrairieLearn/PrairieLearn/blob/a695f4bed2b49c34f07a7872937add85bb54f75b/doc/elements/pl-text.png) but are no longer aligned:

<img width="250px" src="https://user-images.githubusercontent.com/2503508/95134377-6769b800-0728-11eb-9fc8-53578a5742b4.gif"/>

**Comment by echuber2** [comment]
Which browsers/platforms does this happen on?

**Comment by nwalters512** [comment]
This is no longer reproducible:

<img width="224" alt="Image" src="https://github.com/user-attachments/assets/97ce7a2e-aa27-4da9-bb47-fb0cc6d95939" />

The above screenshot is Chrome, but it looks the same in Safari and Firefox.
