### ISSUE TITLE
Run full graphical desktop inside workspace

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3290]
Pulled from #2504:

> Make a demo question to run a full graphical desktop inside a workspace. We'd need a browser-based VNC/RDP client like https://guacamole.apache.org or https://novnc.com in a workspace container that runs a linux graphical desktop and a VNC server. This would be useful for running things like Matlab, CAD programs, etc.

**Comment by nicknytko** [comment]
[Xpra](https://xpra.org/) is a x11 forwarder with an HTML5 client that we can consider using here.

An alternative method of achieving this would be to create or use a browser-based UI like [OS.js](https://demo.os-js.org/), which has [wrappers around xpra](https://www.youtube.com/watch?v=c0safRR0ldM) that we could use.  I have no idea how easy it would be to embed OS.js into a workspace container, but rolling our own interface similar to this could work.

**Comment by mwest1066** [comment]
I've also seen sites using [noVNC](https://novnc.com/) for this.
