### ISSUE TITLE
More workspace images/questions

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3300]
Some examples from #2504 (but we don't have to be limited to these):

* [ ] VS Code (theia): https://hub.docker.com/r/theiaide/theia/
* [x] RStudio: https://hub.docker.com/r/rocker/rstudio/
* [ ] Observable: https://observablehq.com/

---

Existing demos:

* [x] VS Code (code-server): https://hub.docker.com/r/codercom/code-server
    * question: https://prairielearn.engr.illinois.edu/pl/course/108/question/7972699/
* [x] Jupyter notebooks: https://hub.docker.com/r/jupyter/datascience-notebook
    * image: https://github.com/PrairieLearn/PrairieLearn/tree/master/workspaces/jupyterlab
    * question: https://prairielearn.engr.illinois.edu/pl/course/108/question/9045312/
* [x] xterm.js: https://hub.docker.com/r/xtermjs/xterm.js/
    * image: https://github.com/PrairieLearn/PrairieLearn/tree/master/workspaces/xtermjs
    * question: https://prairielearn.engr.illinois.edu/pl/course/108/question/8677505/

**Comment by nwalters512** [comment]
The current PL-provided workspaces and questions have been sufficient since we launched. If folks would like to request other workspace images, we can open individual issues to track them.

**Comment by echuber2** [comment]
Worth noting that Theia doesn't offer much benefit over VS Code in this case, RStudio is implemented now (as checked off in the list).
