### ISSUE TITLE
Pagination problem on issues page

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3304]
On the issues listing, if there are more than 100 issues, pagination takes place. But if the current filter includes less than 100 items, the pagination still shows, even though a second page wouldn't have anything.

**Comment by jonatanschroeder** [comment]
![image](https://user-images.githubusercontent.com/1004907/95412351-a4c37680-08dd-11eb-8389-c34e9e493757.png)

**Comment by mwest1066** [comment]
Dup of #1350
