### ISSUE TITLE
Better handling of killed grading jobs

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3308]
Sometimes grading jobs will just die with no reason, with no notification to students or instructors (https://ca.prairielearn.org/pl/course_instance/1678/instructor/grading_job/590282). In cases like these (possibly based on a timeout or a periodic check of pending jobs), it would be helpful to have some way to either:

1. Automatically restart the job and provide the result; or

2. Notify the student that the job failed, ask them to submit again with no attempt penalty.

**Comment by jonatanschroeder** [comment]
I haven't seen this in years, so closing. I'll reopen if it comes up again.

**Comment by nwalters512** [comment]
For future reference, #10532 will probably have helped here.
