### ISSUE TITLE
testInfo semester not fully implemented?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#333]
Error reading file: D:\GitHub\pl-lis490teg\tests\ex13\info.json Error validating file 'D:\GitHub\pl-lis490teg\tests\ex13\info.json' against 'schemas/testInfo.json': Error in JSON file specification: Error in field "data": has additional properties (value: 'data.semester')

When I search the repo I see it mentioned in course-db.js but nowhere else (documentation or schema file). Is that why I'm getting an error? How do I fix it?

**Comment by mwest1066** [comment]
The concept of "semesters" is implemented in the current master branch and in some unmerged branches, but it isn't yet deployed to production. Just remove any mention of "semester" in your course info.json files and you'll be good to go (you'll probably get warnings on your dev install, but no errors).
