### ISSUE TITLE
Select closing of issues in bulk

### ISSUE THREAD

**Issue by margoseltzer** [PrairieLearn/PrairieLearn#3341]
It seems that there are two options for closing issues: one at a time or all open issues. It would be extraordinarily useful to be able to close all issues selected by the filter options. That is, I can view a set of issues by selecting a particular question or other kinds of filters and I would then like to close just those issues.

**Comment by mwest1066** [comment]
Dup of #2154

**Comment by nwalters512** [comment]
Since this is tracked in #2154, I'm going to close this so we can keep all conversation and progress in one place.
