### ISSUE TITLE
Pl-dropdown grades 0% on submission

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#3362]
Pl-dropdown is labelling submissions as 0% on the UI whether the submissions are incorrect or correct. It would be ideal if the submissions could not show a 0% grade beside submissions until they are graded. Other elements just show submissions as such: `highlighted text`.

0% showing up under submissions on pl-dropdown:
![image](https://user-images.githubusercontent.com/7872295/96491009-7bb4b700-11f6-11eb-8e9d-d97d182b6683.png)

**Comment by jonatanschroeder** [comment]
A student just reported this bug in class. To clarify: if a student uses "Save only" (not "Save & Grade") on a question with a dropdown, the dropdown will show a "0%" in the submission box, even though it wasn't graded.
