### ISSUE TITLE
Remove old PL/CBTF course matching security

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#3373]
Now that we've switched to `examUuid` linking to tie access to PL assessments to the CBTF scheduler, we should deprecate and remove the old fuzzy-logic `course_id` matching. This would help the institutions who use mode:Exam but not the CBTF.

That's cleaning up the stanzas in https://github.com/PrairieLearn/PrairieLearn/blob/49aca95bda41e01f4d89092b03094e9f7c3ce583/sprocs/check_assessment_access_rule.sql#L91 and the `course_instances.ps_linked` column, and updating the tests to make sure the access rule works as expected.

@mwest1066 and @trombonekenny chatted about this in Slack, but I couldn't find an issue for this work.

**Comment by trombonekenny** [comment]
Would also obsolete #1373

**Comment by trombonekenny** [comment]
Updated TAM 251 and 212 ZJUI course instances `ps_link` to false. Need to complete this issue. Self-poke.

**Comment by trombonekenny** [comment]
Maybe less important if ZJUI are using their own server now, but we still need to clean this up.

**Comment by nwalters512** [comment]
#11041 and #11042 contain the remaining followup work here (removing the `course_instances.ps_linked` column). The rest of this has been done!
