### ISSUE TITLE
Long blocking of event loop

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3376]
We blocked for 73 seconds! (this was `prairielearn2.log`)

```
{"time":73495,"level":"verbose","message":"BLOCKED: Blocked for 73495ms (set config.blockedAtWarnEnable for stack trace)","timestamp":"2020-10-23T19:51:06.377Z"}
```

**Comment by nwalters512** [comment]
We've done a lot of work to minimize blocking time since this was opened, and haven't faced anything nearly this egregious in some time.
