### ISSUE TITLE
Statistics don't show in TA role

### ISSUE THREAD

**Issue by jakebailey** [PrairieLearn/PrairieLearn#339]
When I try to access an exam in my TA role, I first get a circle at the bottom of the page:

![image](https://cloud.githubusercontent.com/assets/5341706/14864677/8d676310-0c80-11e6-8af7-70a3c05968e7.png)

This will stay no matter what page I try to navigate to. To get past this (and get to the CSVs), I refresh and get:

![image](https://cloud.githubusercontent.com/assets/5341706/14864681/935cbe82-0c80-11e6-8ab8-2bb372ecfda2.png)

Which at least gives me the file access, but doesn't show me any of the nice graphics. The console shows the error:

```
Uncaught TypeError: Cannot read property 'get' of undefined
app.js:239
```

I'm guessing that the permissions are such that TAs don't have access to the statistics, but do to the files.

**Comment by mwest1066** [comment]
Eliminated by PLv2.
