### ISSUE TITLE
Proctor Password

### ISSUE THREAD

**Issue by mattoxb** [PrairieLearn/PrairieLearn#343]
One of the proctors for the remote students insists that they have a "proctor password" that will unlock an exam for a student to be sure they don't have access before they arrive to get it proctored.  This could be a field in the "allowAccess" block or something....

**Comment by trombonekenny** [comment]
Might be worth investigating PL integration with Safe Exam Browser (http://safeexambrowser.org/news_en.html) which supports proctor and exit passwords and could be applicable there.

**Comment by mwest1066** [comment]
Implemented in 57dc0e0ab9ec67d17db8e1aca76fb185a7322810
