### ISSUE TITLE
Does PL API not work for students?

### ISSUE THREAD

**Issue by parthsaxena** [PrairieLearn/PrairieLearn#3449]
If a student generates a personal access token (which they are **able** to do), are they are not able to use this access token to use the PL API? If so, what is the reasoning behind this design philosophy?

**Comment by mwest1066** [comment]
Correct, students currently cannot access the API. There is no particular reason for this, other than no one had ever requested it so there was no real reason to implement it.

**Comment by parthsaxena** [comment]
It would provide opportunities to develop third-party applications to access PrairieLearn. For example, I was attempting to develop a mobile application to allow students to view their Gradebook, but, in its current state, the PL API is closed off from student access.
