### ISSUE TITLE
Updating question points in instructor assessment instance page does not take credit into account

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3450]
Assume a student submits a question during a time when credit is not 100. If an instructor opens the assessment instance for that student, and changes the points awarded to that student, the assessment score will be awarded based on 100 credit instead, regardless of what the credit was during the time. ~~I think it should take into consideration the credit that was active when the question itself was last submitted (I believe that's the field submissions.credit) to make the points computation instead.~~ It may be good to at least show the credit value for a question at the moment the question was submitted, so that the instructor can make an informed decision on how to apply the value. Note that the instructor has the ability to change the actual score of the question afterwards.

**Comment by mwest1066** [comment]
I like the idea of at least showing the credit, or giving the instructor a checkbox to let them choose whether credit should be taken into account when changing the score.

See #818, #1921, and #3451

**Comment by jonatanschroeder** [comment]
Closing in favour of #6781, which is more comprehensive (any kind of manual grading, instead of only the instance log).
