### ISSUE TITLE
hjson for config files

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#348]
PrairieLearn configs might be more userfriendly, especially to novice coders, if it parsed them as hjson instead of strict json?

https://hjson.org/

**Comment by mwest1066** [comment]
[Goodbye Hjson!](http://hjson.org) - looks like it's going EOL.

**Comment by trombonekenny** [comment]
I guess we follow up in #1158 and close this out. /sigh/
