### ISSUE TITLE
Assessment instance configurations are not updated on sync

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#3529]
**Expected behaviour:** 

An assessment instance should inherit configuration set in the assessment `infoAssessment.json` file after it is synced.

**Actual behaviour:** 

An assessment instance is not inheriting the configuration set in the assessment `infoAssessment.json` file, as the `showClosedAssessment: false` and `showClosedAssessmentScore: false` flags were not implemented after running a sync.

**Steps to reproduce:** 

1. Create an assessment Exam type where these settings are implemented in the configuration at the start of the exam: 

```
            "timeLimitMin": 150,
            "showClosedAssessment": true,
            "showClosedAssessmentScore": true,
```

2. Have a student access the assessment, which will create an assessment instance for the student.

3. Update the assessment settings following configuration properties: 

```
            "showClosedAssessment": false,
            "showClosedAssessmentScore": false,
```

4. Run Sync for the course.

5. Have the student attempt to see the score after the exam closes after the given time limit passes. The student should be able to.

**Comment by jonatanschroeder** [comment]
I don't think this is a problem at this point. Closing.
