### ISSUE TITLE
Students complaining about 

### ISSUE THREAD

**Issue by zillesc** [PrairieLearn/PrairieLearn#354]
Students opened the following post on my Piazza.  I haven't verified the problem, but at least 2 have observed it.  I tried, but couldn't open this issue against Binglin's fork.

**PrarieLearn Bug With Wrong Links For Questions?**

Has anyone else had the issue with PrairieLearn where you go to click on a question link and it takes you to a different question? Like for tonight's homework when I click the link on the page showing all the question types

     #4.570 Decimal to Two's Complement Binary Conversion

I navigate to a the page displaying questions that don't pertain to Decimal to Two's Complement Binary Conversion.  In this case I get 

     #4.570 Two's Complement Binary Subtraction Problems

The numbers are the same ($4.570) but the content of the questions is different from what the link says on the page showing a list of question types.

EDIT: This has happened before, but the first time I paid no mind to it. 

----

**Another student followed-up with:**

It happens when you don't reload the overview page after navigating to it. It's just a workaround but this happens regularly to me too

**Comment by chen386** [comment]
#357

**Comment by mwest1066** [comment]
Fixed by f11c1b9e73a248d6e06bbf37b38c2b588d2bad12
