### ISSUE TITLE
From Issues page add link to student's assessment instance

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3549]
The issues page links to the student's assessment instance question. It would be really helpful if it also had a link to the student's assessment instance itself. The reasoning is that sometimes an issue requires us to review grades manually, and currently we need to navigate to the assessment, find the student, go to Details and then change it.

The link could come from the assessment instance question page itself.

**Comment by echuber2** [comment]
Doesn't an issue's individual viewing page include the reporting student's actual problem variant on the same page? I'll have to check that again later, but it did in the past.

**Comment by jonatanschroeder** [comment]
It does, but not the instance of the assessment, which allows me to change the grade. The instance question page doesn't have that option.

**Comment by echuber2** [comment]
I see. Maybe one solution is to add a "return to assessment log" in the right-hand instructor panel that appears on any question instance.

**Comment by jonatanschroeder** [comment]
The interesting thing is that the instructor panel already has support for that kind of link, since the student view of the question has that link when viewed by an instructor. So the options could be:

* Have the issue point to the student view of the question -- the instance_question link -- when there is an instance_question assigned to the Issue (problem: the tabs with links to change Files/Settings would not be visible, which could be important depending on the Issue);
* Include the same "Assessment Instance" section that is visible in the student view in the question preview page.

**Comment by mwest1066** [comment]
> * Have the issue point to the student view of the question -- the instance_question link -- when there is an instance_question assigned to the Issue (problem: the tabs with links to change Files/Settings would not be visible, which could be important depending on the Issue);

I'm sorry to only now comment on this after you already implemented the other option in #3568, but I actually think it would be conceptually cleaner to fix the issue with the idea above. That is, link to the student view of the question. This way we can keep "instructor view of question" and "student view of question" completely separate. I worry that it's confusing to show the instructor view of a question but with a link to a student's assessment instance. I also think it's conceptually cleaner to link from the issue to the page that the student was on when they filed the issue.

Regarding your comment above about the missing links to Files/Settings on the student question page, there is a link from the student question page to the instructor question page (the QID link), in case someone needs to go there to debug. I'd be happy to change that link to make it more obvious, if you think that's needed?

What do you think? I'm happy to be persuaded that I'm wrong about this 😄

**Comment by jonatanschroeder** [comment]
I'd argue that, even if Issues are changed to point to instance questions, it would make sense to keep the link to the assessment instance, since we're showing the student submissions: we may want to check the rest of the student's data if we're showing a specific variant. This may also be useful if #3567 is addressed.

But I am fine with switching to link to the instance question. I was just trying to minimize the impact on instructors that may already be familiar with one particular flow, especially if the issue is related to files/settings that need to be addressed.

**Comment by jonatanschroeder** [comment]
Also to consider: since the issue list is per course and not per instance, it is possible that users would have access to issues that are not in instances they have access to. For example, an instructor that is an Owner or Editor in the course, but not an Instructor in the instance. How should this be handled? If we expect them to have access to the issue/question, then linking to the question is the best approach in this case (status quo). If we don't expect them to have access to the issue then should we have a warning that they don't have access to it? Or somehow hide it?

**Comment by mwest1066** [comment]
> Also to consider: since the issue list is per course and not per instance, it is possible that users would have access to issues that are not in instances they have access to. For example, an instructor that is an Owner or Editor in the course, but not an Instructor in the instance. How should this be handled? If we expect them to have access to the issue/question, then linking to the question is the best approach in this case (status quo). If we don't expect them to have access to the issue then should we have a warning that they don't have access to it? Or somehow hide it?

I believe this is handled by #3020 (or at least this question will be heavily impacted by #3020).
