### ISSUE TITLE
Review application of showClosedAssessmentScore

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3553]
Currently the `showClosedAssessmentScore` setting only applies for the period of time where the setting is applied. As soon as that time period ends (e.g., the end of the exam), the setting resumes to the default. In practice this means that `showClosedAssessmentScore` set to `false` will hide the score during the exam, but will show it as soon as the exam ends.

My suggestion is to decouple this setting from the access rules and set it outside of that list. For example, replace it with a `hideAssessmentScoresUntil` setting that is set to a specific date-time when the scores become visible.

This is probably going to be more important once manual grading becomes available, since instructors would probably want to control when manual grades become public, and publish all of the grades together instead of when each submission is graded (@andrewstec , @cheeren).

**Comment by mwest1066** [comment]
As an immediate fix, I suggest adding `assessments.show_closed_assessment_score` at the assessment level, and use this as the default (which can be overridden inside access rules).

**Comment by jonatanschroeder** [comment]
Related: #3779, #3616 .

**Comment by jonatanschroeder** [comment]
As of now you can work around this with the last access rule containing:
```
        {
            "startDate": "[SOME DATE]",
            "showClosedAssessment": false,
            "showClosedAssessmentScore": false,
            "active": false
        }
```

**Comment by jonatanschroeder** [comment]
Closing in favour of #10318 and #6860.
