### ISSUE TITLE
Question title shows up as "undefined" under certain situations

### ISSUE THREAD

**Issue by chen386** [PrairieLearn/PrairieLearn#356]
To reproduce this, go to any question, submit with arbitrary answer, then click next question, previous question, next question, previous question, the question title shows as undefined.

Since the phenomenon is reproduced in the current commit as well as [04e9f90](https://github.com/PrairieLearn/PrairieLearn/commit/04e9f9067d383d0358956dfc47cd8c67183d026a), I think this has nothing to do with shuffling.

**Comment by mwest1066** [comment]
Fixed by f11c1b9e73a248d6e06bbf37b38c2b588d2bad12
