### ISSUE TITLE
Randomization in test questions is very periodic

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#360]
I have a test question that draws from five possible variants. In generating some test sessions, the 2nd and 5th version come up frequently, and the 3rd version somewhat frequently, but the 1st and 4th versions very rarely. It seems like whatever randomized function is choosing from among the questions has a very bad periodicity.

**Comment by mwest1066** [comment]
Can you post a code snippet here? PL is using the Mersenne Twister PRNG variant [MT19937](https://en.wikipedia.org/wiki/Mersenne_Twister) which should be very reliable, but I'd definitely like to make sure that we are randomizing well. Note that PL is doing true (PRNG) random generation, which can sometimes look non-random to a human. We've had a long-standing plan (see #26) to add anti-correlation, but we haven't implemented that yet.

**Comment by echuber2** [comment]
We're using the SimpleClient with a simple test configuration like this:
```
{
    "type": "Exam",
    "title": "Some title here",
    "set": "Set title",
    // ...
    "options": {
        "qidGroups": [[[
          "question_set1",
          "question_set2",
          "question_set3",
          "question_set4",
          "question_set5"
        ]]],
        "nQuestions":1
    },
    "multipleInstance": true
}
```
My anecdotal experience is that trying to launch instances of this as a student user frequently produces set 2 or set 5, sometimes repeatedly, for example. Now I'm thinking the issue may be MT itself, as it's currently being seeded with the system time, and MT is susceptible to similar output with very similar seeds. In that case the issue may be that my spamming new sessions in succession will simply cause this result. I don't know much about cryptography, but I've dug up a few articles complaining that MT has a tendency to fall into trends of similar feedback occasionally, so it's not always recommended for Monte-Carlo type tasks where more or less even coverage is desired. I suggest that another algorithm like WELL could be added as an alternative, or even something that is "worse" for true randomness but more equal in coverage, such as a Hammersley or Sobol sequence.

Also this isn't a high-priority issue, it's just something that stuck out to me. There's a more pressing issue I'd like to submit about partial submissions in test forms.

**Comment by mwest1066** [comment]
Thanks for looking into this. It definitely seems to be occurring. Here is a short test program that shows the problem: https://gist.github.com/mwest1066/2a6faed2e309a756c536c3a998605077

The output is:

```
we generate 10000 random integers from 0 to 4
the random number generator is re-seeded from the current time on every call
counts[i] is the number of times that integer i is generated
counts [ 1976, 1910, 2044, 2010, 2060 ]
pairs[i][j] is the number of times that integer j was generated immediately after integer i
pairs [ [ 1118, 209, 219, 212, 219 ],
  [ 221, 1081, 190, 212, 206 ],
  [ 219, 210, 1186, 191, 238 ],
  [ 209, 204, 229, 1167, 200 ],
  [ 209, 206, 220, 228, 1197 ] ]
```

The `counts` array should have all entries equal to about 2000, which it does.

The `pairs` array should have all entries approximately equal to 400, which it definitely does not. Instead the diagonal of `pairs` is much larger, indicating that we tend to see repeats of random numbers.

It's not yet clear to me what the best way is to fix this.

**Comment by mwest1066** [comment]
I suspect that the problem with frequent re-initializations is that the time values we are using are very similar, so we are initializing with very similar seeds.

I tried changing the above test code to use `process.hrtime()` (nanosecond resolution) and it seems to fix the problem:

```
we generate 10000 random integers from 0 to 4
the random number generator is re-seeded from the current time on every call
counts[i] is the number of times that integer i is generated
counts [ 1956, 1957, 2012, 2123, 1952 ]
pairs[i][j] is the number of times that integer j was generated immediately after integer i
pairs [ [ 370, 394, 385, 434, 374 ],
  [ 420, 376, 383, 424, 354 ],
  [ 385, 397, 387, 412, 431 ],
  [ 438, 412, 457, 423, 392 ],
  [ 343, 378, 400, 430, 401 ] ]
```

Note that the `pairs` array is now all fairly equal, with the diagonal (successive generations of the same value) being about the same as any other possibility.
