### ISSUE TITLE
Leading/trailing code are not documented for Python grader

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3613]
The Python grader docs don't mention `leading_code.py` and `trailing_code.py`.

**Comment by mfsilva22** [comment]
These were added later. In essence, the leading code is needed in some situations when using workspaces, and also the order-blocs, for example, to add variables or import libraries. 

We made this quick change before the summer started and forgot to modify the documentation. I will add text there later.
