### ISSUE TITLE
Support for internationalization of main interface

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3615]
Provide support for additional languages for main interface. Language could be defined based on student preferences (browser settings) or on course (or course instance) defaults. Look at i18n node module as possible starting point for implementation.

**Comment by nwalters512** [comment]
Unfortunately I think we lack the resources to do this properly at the moment, and even if we had them, the costs would probably outweigh the benefits at our current scale. I'm going to close this for the time being, but we should consider this again in the future if and when it makes sense to.
