### ISSUE TITLE
Copy per-test question difficulty/discrimination plots from v1

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#367]
Copy the difficulty/discrimination plots from v1 and add them to `pages/adminAssessment`. In v1 these are implemented in `frontend/require/TestDetailView.js`, `frontend/require/TestDetailView.html`, and `backend/server.js` in the `computeTestStats()` function.

<img width="733" alt="diffdiscplot" src="https://cloud.githubusercontent.com/assets/875833/19158916/1059d952-8bb0-11e6-85d8-e0d4b0dd21ec.png">

**Comment by parasgithub** [comment]
The score_perc value is indeed correct for the newer homeworks. I will make the changes to use score_perc in place of points/max_points.
