### ISSUE TITLE
Integration with third party apps

### ISSUE THREAD

**Issue by gprakarsh** [PrairieLearn/PrairieLearn#3703]
I want to use the PrairieLearn API to create a portal (a mobile application) where I can view upcoming assessments, grades etc. along with info from other learning platforms such as Compass2g and Moodle. 

However, I don't see a way to do that right now. What can be done here?

**Comment by jonatanschroeder** [comment]
One of our TAs managed to get some of this information from the PL API: https://prairielearn.readthedocs.io/en/latest/api/. Basically they use the assessments list and the access rules of each assessment to get the upcoming assessments. You can probably get grades from the assessment instance (or the log). Does that help? Is there anything in particular that you are unable to do with that?

**Comment by astrosticks** [comment]
@jonatanschroeder Those docs you linked mention that the API is only for instructors, but I think that OP is requesting API access for students

**Comment by nwalters512** [comment]
I'm going to close this in favor of #5312.
