### ISSUE TITLE
pl-integer-input bound by JS integer value limits

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3708]
It seems an input that is longer than what JS supports (15 decimal digits) is silently truncated by JS, even though both PostgreSQL and Python support longer numbers. This leads to a weird situation where, if the student provides an input larger than this limit in a `pl-integer-input`, the value shown in the submission box doesn't match what was submitted.

One possible approach (suggested by @mwest1066) would be to reject numbers (format error) that are too large for JavaScript to support. In essence this would mean reject any number larger than 2^53-1 or smaller than -(2^53-1) (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). If the question actually needs a number that large, a custom `parse`/`grade` function would be needed, working with `data["raw_submitted_answers"]`.

Other alternatives would require either the use of `BigInt` in JS, or a way to provide different arguments to the element to handle very large numbers in a different way.

**Comment by jonatanschroeder** [comment]
To consider: https://www.npmjs.com/package/json-bigint

**Comment by eliotwrobson** [comment]
I think the only issue here is Json serialization of the integer, correct? If so, the integer can just be stored as a string and converted back to a Python integer by grader code.
