### ISSUE TITLE
Course instance access/enrollment based on LDAP group membership

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3718]
Shibboleth/LDAP can be set up to include course enrollment as LDAP group membership. We can take advantage of this information to ensure only students enrolled in the actual course can have access to the course instance. This would probably include some sort of:

1. Link a course instance to an LDAP group;
2. Have access rules linked to membership in the group (similar to the LTI "institution");
3. Update shib authentication to save group membership information for the user.

This will probably require #3301 to ensure course enrolment is periodically refreshed.

Note that, for students that drop the course, this would not remove the enrollment, but it would block them from accessing the course once that drop is seen by the system.

@mwest1066, for testing this, it would be useful to have a sample HTTP request for `pl/shibcallback`, including headers that contain this information.

**Comment by trombonekenny** [comment]
I'm less in favor of parsing custom Shibboleth attributes for authorization as I would be revisiting and properly implementing modern LTI. We do the Shib group auth for the CBTF scheduler and IMO it's really scalable when it comes to multiple institutions, potentially passes too much information when it does, requires too many people outside of the elearning config to set it up. 

LTI and smarter session-based auth, even if it's a bigger lift, seems smarter.

**Comment by jonatanschroeder** [comment]
I believe as @trombonekenny mentioned LTI is a way better approach to this, so closing in favour of LTI-based verification.

**Comment by trombonekenny** [comment]
https://www.imsglobal.org/spec/lti-nrps/v2p0/ in particular

**Comment by mwest1066** [comment]
I agree that LTI is the way to go here.

**Comment by jgfoster** [comment]
Given that LTI is a EE feature, would you be open to a PR from the community supporting LDAP as a feature in the CE?

**Comment by mwest1066** [comment]
@jgfoster in the 3+ years since this issue was opened we haven’t seen any interest in LDAP support, so I’m afraid that with our small team and limited resources we aren’t wanting to take on the maintenance of LDAP code at this time.

**Comment by trombonekenny** [comment]
@jgfoster There are some other issues tracking modernizing enrollment management in PrairieLearn. You might want to follow those as we discuss the next generation of enrollment. While I don't think we'd directly add LDAP (it can be very institutional in how to configure and troubleshoot), we _are_ likely to add things like CSV support or an API. You could combine that with site-local scripts that used LDAP and populated the data PL would need. That should work, right?

**Comment by jgfoster** [comment]
@mwest1066 & @trombonekenny, My primary interest is in a CE option that does not require Google. If you could point me towards the discussion I could follow it and maybe look for a way to contribute.

**Comment by mwest1066** [comment]
I think @trombonekenny is referring to #9217
