### ISSUE TITLE
Add an "allowRetakes" option that enforces one retake per scheduled exam

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#375]
This would fit the model of retakes used by AE 483 (@tbretl) and ESPL.

**Comment by nwalters512** [comment]
@mwest1066 I believe we've been using PT to do retakes without this config and things have been going fine - do you think we can close this?

**Comment by mwest1066** [comment]
Yep, this is no longer relevant now that PT controls things.
