### ISSUE TITLE
Manual Grading: Manual Grading Feature With Other Grading Workflows

### ISSUE THREAD

**Issue by bevansm** [PrairieLearn/PrairieLearn#3788]
In order to support manual grading alongside internally/externally graded questions, we should move away from the singular "External/Internal/Manual" question type flag in the database, and instead look towards refactoring this into three boolean columns.

The largest concern with this refactor is backwards compatibility and migration.

**Comment by jonatanschroeder** [comment]
Closing this in favour of:

* Separate manual points for individual questions that allow manual grading to be combined with other types of grading (see #5909).
* Include options to run internal grading functions for external grading questions (see #6262).
