### ISSUE TITLE
In exam mode: Give warning as Assessments main page to "Stop here until told"

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#379]
One of Mindy's spiels each time to students in the CBTF reminds them they can login to the computer, login to PrairieLearn, and go right up to the Assessments page but then stop until they're told.

Can we work something into the student UI when in the testing center to either have a click-through there, or just a big visual to "stop here" before continuing?

**Comment by mwest1066** [comment]
I only implemented this in v2 as it was much easier to do (which is why v2 exists).
