### ISSUE TITLE
Groupwork data missing

### ISSUE THREAD

**Issue by Yucheng-Jiang** [PrairieLearn/PrairieLearn#3813]
I managed to download all data files of cs233(fall2020) but found all the students data related to ''group work'' are missing.  The submission, log,  and instance questions files only record TA and instructor's data. Also students group work scores are null in gradebook.

**Comment by mwest1066** [comment]
@frankyhao can you take a look at this?

**Comment by mwest1066** [comment]
I think we just need to change the JOINs on `users` to be LEFT JOINs and add a LEFT JOIN on groups: https://github.com/PrairieLearn/PrairieLearn/blob/c0beb25780ae5eeab62341a95b849dd6eecf13b3/api/v1/endpoints/queries.sql#L67

**Comment by frankyhao** [comment]
Yeah, I only changed JOIN for queries in pages and may forget to change this one for gruops

**Comment by Yucheng-Jiang** [comment]
any update?
