### ISSUE TITLE
Problems with deployment of #2626

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3824]
Although #2626 was merged, problems were encountered during deployment and so it was reverted. The issues are:

1. After deployment we started to accumulate large numbers of "stuck" running queries from here: https://github.com/PrairieLearn/PrairieLearn/blob/7543da03935e54f0462d5b2aca0f52f7577cd55e/middlewares/selectAndAuthzInstanceQuestion.sql#L1 I don't know what's causing this. I can't see anything that looks risky in the PR, but something is clearly wrong. I'll try and do some more testing on a live staging server sometime next week.

2. While attempting to test the above issue, I noticed that the migration creates `effective_advance_score_perc` as `NULL`, which would be fine except that this comparison: https://github.com/PrairieLearn/PrairieLearn/blob/fb99f8f1f779354876288f9b74224438d3845308/sprocs/question_order.sql#L23 will then always result in `locking = NULL` for questions other than the first (because `FALSE OR NULL = NULL`, see https://www.postgresql.org/docs/current/functions-logical.html) and hence `sequence_locked = NULL` lower in the query.

    The `sequence_locked` value is eventually used here: https://github.com/PrairieLearn/PrairieLearn/blob/fb99f8f1f779354876288f9b74224438d3845308/middlewares/selectAndAuthzInstanceQuestion.sql#L89 and `AND NOT sequence_locked` becomes `AND NOT NULL` which is `AND NULL`, so access to every question is locked. This will be fixed the next time someone syncs that course, but until then no student can access any question in the course (except the first question in each assessment).

    I haven't thought carefully about whether it would be better to make `effective_advance_score` be `DEFAULT 0 NOT NULL` and leave all the code as is, or to change the code to deal safely with `effective_advance_score = NULL`.  I guess the former is probably simpler.

**Comment by astrosticks** [comment]
@mwest1066 Attempting to merge the latest changes from master into forceSequential, I'm getting an error when trying to start the server: `{...,"routine":"errorMissingColumn","message":"column aq.effective_advance_score_perc does not
 exist"},...`. Could this have something to do with the fact that `migrations/227_force_sequential_questions__add.sql` was reverted, but its index hasn't been replaced by another migration since then, leaving the docker image thinking that migration 227 already happened?

**Comment by mwest1066** [comment]
We are trying again with #4497 now that #4412 is deployed.

**Comment by nwalters512** [comment]
@mwest1066 i believe we can close this now?

**Comment by mwest1066** [comment]
Yes, we finally got this fixed up and deployed, although we still have some residual bugs from it (see #6312 and #6158) 😭
