### ISSUE TITLE
Rendering rivets template functions with arguments fails

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#384]
Example is `pl-tam212/questions/changeBasisOffsetInv`

**Comment by rbessick5** [comment]
This appears to render properly whenever there is one component, but fails when both e_r and e_theta are needed (according to John's testing/observation).

**Comment by mwest1066** [comment]
Appears to have been a bug in the questions. They were calling the `vector` template function rather than `vectorInBasis`.
