### ISSUE TITLE
Run v2 question code in containers

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3851]
Following #1626 it would be awesome to add the ability to run v2 questions within this new containerized environment. Could we wrap them in python? Something like:

1. When `calculation.js` wants to run a function like `generate()`: https://github.com/PrairieLearn/PrairieLearn/blob/e9d7d530f6767ffb776e3019609d7edb85f2b32f/question-servers/calculation.js#L64
2. It gets a `pythonCaller` just like we do inside `freeform.js`: https://github.com/PrairieLearn/PrairieLearn/blob/e9d7d530f6767ffb776e3019609d7edb85f2b32f/question-servers/freeform.js#L868
3. The `calculation.js` code then makes a special call to the python worker to tell it to run `generate()` but in "JS-mode". This could be done by adding another argument which is `lang=python` or `lang=javascript` here: https://github.com/PrairieLearn/PrairieLearn/blob/e9d7d530f6767ffb776e3019609d7edb85f2b32f/lib/python-caller-trampoline.py#L56
4. If we are `lang=javascript` then we exec `node javascript-trampoline.js`, where we have a new `javascript-trampoline.js` which just loads the `server.js` file, executes the desired function, returns the data, and then exits. The contents of this would be basically the same as the current `calculation.js` functions (like `generate()`).

**Comment by nwalters512** [comment]
This was implemented in #4934.
