### ISSUE TITLE
Reorganize the deployment of experimental features

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3869]
Based on the current list of experimental features partially deployed (group work, manual grading, pl-order-blocks, etc.) and being deployed soon (force order, broken questions, gradebook, etc.), I propose that we include a method for allowing the partial release of these features in a controlled way.

A table of features should be created, with some internal identification (e.g., `manual_grading`) and a user-friendly name and description suitable for instructors/course owners. To avoid discrepancies between installations these features should be created via migration script.

A feature may be enabled or disabled for a course (or maybe course instance), see below. A locals variable (e.g., `features`) should be populated by the course/course instance middleware, and all feature implementations should check if their feature record is enabled before displaying links or data. For some features this may require an additional check with an exception if the user attempts an operation that can only be performed if the feature is enabled. Some features, even if enabled, could also show a warning to instructors (e.g., in question preview, if workspace is used, a "workspace is experimental" warning could be shown).

Features can be in various stages:

* Private beta: in this case admins have the ability (via a page in the Admins view) to enable/disable these features for individual courses. Once enabled, course owners can then disable the feature if they would like to remove it for some reason, but they can't enable it unless the admin has enabled it as well.
* Public beta: in this case all course owners have the ability (via a separate tab in the course or course instance) to enable the feature. All public features are listed (as well as private features enabled for that course), and owners can enable specific features. On enabling a feature, a warning is given that the feature may include bugs or be incomplete (wording to be discussed), and may be subject to frequent changes with minimal warning.
* Release candidate: same as the public beta, but the feature is enabled by default.
* Fully deployed: in this case the feature is enabled for all courses. The feature is maintained until a "garbage collection" PR is able to remove all checks for the feature in the implementation.

There should also be a way for admins to list all courses that have a feature enabled, so that they can track its use.

**Comment by nwalters512** [comment]
As of https://github.com/PrairieLearn/PrairieLearn/pull/7507, we have feature flags. They aren't user-visible and can't be used by instructors to opt themselves into features, but this is still much better than we had before. If we decide we want to allow self-service opting-in of features, this can be tracked in a separate issue.
