### ISSUE TITLE
pl-matrix-component-input feedback field should be generally enabled.

### ISSUE THREAD

**Issue by cheeren** [PrairieLearn/PrairieLearn#3872]
I'd like to be able to justify a custom grade(data) score with feedback text like below:

data["partial_scores"]["mtxworst1"]["feedback"] = "wrong entries"

Such a construct currently dies on rendering.

**Comment by mwest1066** [comment]
What's the error?

**Comment by cheeren** [comment]
From conversation, I now know that the pl-matrix-component-input expects a list of feedback strings, and then only if the partial credit flag is set. 

Lessons: 1) the partial_scores feedback field is often used by the elements for specific purposes, and shouldn't be overwritten -- this should be documented for each element. 2) this idea for partial_scores score justification (just don't call it feedback) lends itself to a possible feature request. 

I'll close this issue and write up two different ones later.
