### ISSUE TITLE
Allow font changing to support accessibility

### ISSUE THREAD

**Issue by harsh183** [PrairieLearn/PrairieLearn#3873]
For example reading difficulties like dyslexia or other cognitive issues. Arial, Comic Sans, Open Dyslexic (some like it) etc.

I opened a similar issue in class transcribe https://github.com/classtranscribe/FrontEnd/issues/295 that might have some interesting information on this as well.

**Comment by mwest1066** [comment]
Isn't this exactly the use-case for [user stylesheets](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#user_stylesheets)?

**Comment by harsh183** [comment]
Sure but how many users will know how to do this and set it up? Is the answer for accessibility just telling users implement it themselves?

**Comment by nwalters512** [comment]
I don't think the answer should be "implement it yourselves", but I'm also hesitant to implement this at the application level. I would expect users requiring specific fonts to use a browser that supports customizing them at the browser level, like Firefox (https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use).

Do you have any prior art for this functionality being built into specific websites? I haven't see this functionality (or a recommendation to implement it) in the pretty extensive accessibility work I've done at work, so I'm curious where else this is showing up in the wild.

**Comment by harsh183** [comment]
Wow thanks for the quick reply! The Firefox settings page looks like a much better guide that most people could figure out over the initial link that was shared where one has to modify CSS. [Some online dyslexic guides take a similar approach with CSS rules](https://www.amydentata.com/2014/11/11/how-make-your-web-experience-dyslexia-friendly/). 

It's a little ironic I'm not too familiar with accessibility set ups myself. I'm willing to try and experiment and report back. I'm slowly trying to figure out what works for me. 

This idea comes from how lots of people I know change fonts on their android phones to be nicer to read. Unfortunately it's a non standard feature (e.g Samsung might but my stock photo Xioami doesn't) and the options are third party apps while some even root the phone. 

~~and yes I've done too many pl problems on my phone to count~~

Firefox phone for instance allows me to change the font size but not the font itself. Likewise, Chrome since they both defer to system settings. 

Another issue I'm thinking of is in terms of CBTF. I know it's been a long time since we've had a proper real life cbtf exam but I wonder if I could read questions properly without messing up similar words far too often I might not even need 1.5x time. Over there I don't think I can set up the custom font size (or dark mode extension which helps me read) either. 

Software in general is quite helpful, in terms of spelling while I write modern technology has really helped. Check out https://www.wired.com/story/end-of-dyslexia/.

**Comment by mwest1066** [comment]
Closing because this should be done at the browser level rather than the application level.
