### ISSUE TITLE
Documentation about scoring flooring

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#391]
Just dropping this here to get it out of my email. Do we have PL's method and philosophy for point scoring documented anywhere? If so, we should.

> Hi Chris, the percentage scores are computed by floor(points/max_points). We are doing this so that the displayed data (which shows integer percentage scores) is exactly the same as the data in the CSV file and the internal computations. We’ve had problems in the past when the internal representation is not identical to what the student sees on the screen. For example, we used to display rounded (not floored) percentage scores and store the exact number internally, but then a student would think that they have 100% but they actually have 99.6%. This then caused unhappiness when the scores were downloaded and used later in the gradebook.

**Comment by mwest1066** [comment]
Will be fixed by #392
