### ISSUE TITLE
v2: Dynamics reference pages are a hot steaming pile of hacks

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#393]
The link to reference pages off https://prairielearn.engr.illinois.edu/pl/2/assessmentInstance/1069/ fails for students in Firefox with the error:

https://prairielearn.engr.illinois.edu/pl/2/assessmentInstance/clientFiles/index.html
invalid input syntax for integer: "clientFiles"

Seems to work in Chrome, so we'll suggest that to students who have problems.

**Comment by mwest1066** [comment]
Will be fixed by #370
