### ISSUE TITLE
Chunk download caching also caches rejections

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3939]
We add the promise for the chunk fetch to the caching map: https://github.com/PrairieLearn/PrairieLearn/blob/d65d09050494d13f2d6937341c2eaddf7e7a17f4/lib/chunks.js#L753 but we never remove it.

This means that we will cache promise rejections and not properly retry (and we are accumulating memory in the Map). To fix this I think we need to add a `finally()` handler to clean up. We could use a wrapper around `ensureChunk()` which does something like:
```
const ensureChunkOneAtATime = async (courseId, chunk, pendingChunkKey) => {
    const pendingChunkPromise = pendingChunksMap.get(pendingChunkKey);
    if (pendingChunkPromise) {
        // If this chunk is already being loaded, reuse the existing promise
        return pendingChunkPromise;
    }
    const chunkPromise = ensureChunk(courseId, chunk).finally(() => pendingChunksMap.delete(pendingChunkKey));
    // is there are race condition here because we are installing the delete handler before we set the Map entry?
    pendingChunksMap.set(pendingChunkKey, chunkPromise);
    return chunkPromise;
};
```

Alternatively, perhaps we could use [async.memoize()](https://caolan.github.io/async/v3/docs.html#memoize) which does not cache errors. Memoization is a bit of a memory leak, of course, but that might be ok.

**Comment by mwest1066** [comment]
@nwalters512 I think the `finally()` above won't cause a race condition because we won't start executing `ensureChunk()` until the next tick. What do you think? Any other ideas about how to handle deletion from the Map?

**Comment by nwalters512** [comment]
I ultimately went with a simple `finally()` handler on #5182. I don't think there would have been a race condition in your example code, but I especially think there won't be with the implementation I landed on since I attach the `finally()` handler after adding the promise to the map.
