### ISSUE TITLE
Change homepage to only show enrolled courses, add "add course" page

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#395]

**Comment by trombonekenny** [comment]
Whose data source for enrollment? User supplied data? AD groups? Scheduler data?

**Comment by mwest1066** [comment]
Initially I was thinking to make it just like Craig did with the scheduler, where you get a list of all possible courses and you can add any of them. At some point we can tie this to scheduler or rosters or whatever else.

**Comment by trombonekenny** [comment]
OK. If you did want to see what course groups they're in, Shib can be configured to return that information. I can help you set that up.

**Comment by mwest1066** [comment]
It would certainly be nice to auto-add all courses that a student is actually enrolled in. Once I implement the basic thing I'll get you to add this.
