### ISSUE TITLE
Grade upload: require student ID and submission ID to match

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3997]
If a CSV file has both student ID and submission ID, currently the file ignores the student ID. This can lead to confusion if the file, due to an error, shows one user but uploads to another. I believe that if multiple identifying fields are used, then all must match in order to select a submission to grade. In other words, if the file contains a submission ID and a student ID, and the student associated to the specific submission doesn't match the student in the file, then the upload should fail. Same goes for instance ID.

**Comment by mwest1066** [comment]
This seems like a good safety check.

**Comment by jonatanschroeder** [comment]
Just to put this in here: currently the Download CSV for manual grading uses UID as the column name, but the upload requires `uid` (case-sensitive). In order to ensure this safeguard works as expected it's probably better to (1) have all column names be treated as case-insensitive (e.g., change all column names to lowercase), or (2) have the download version use lowercase names. I'd personally prefer option 1.

**Comment by mwest1066** [comment]
> I'd personally prefer option 1.

Agreed.
