### ISSUE TITLE
Safe Exam Browser support

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#413]
Integrate PL with [Safe Exam Browser](http://safeexambrowser.org) to enable [BYOD](https://en.wikipedia.org/wiki/Bring_your_own_device) exams and remote testing.

**Comment by trombonekenny** [comment]
Besides the header matching and the into/out-of test security, a few other things to consider or test:

Could PL generate the .seb files? And sign them? What would that hosting workflow look like?

Does SEB work with the typical PL flow, including letting students run other permitted software (Matlab, maybe an IDE?, maybe a VM?)

**Comment by mwest1066** [comment]
Implemented long ago.
