### ISSUE TITLE
System for feedback tracking around questions

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#415]
Implement a system where students can report feedback on individual questions (and maybe tests), especially for reporting buggy questions, suggestions, etc.

Similar to DeVry's Sidebar: http://olc.onlinelearningconsortium.org/effective_practices/sidebar-enhancing-faculty-satisfaction-through-integrated-online-faculty-communi (theirs is about faculty reporting content problems to instructional designers; ours would be students to tests writers)

Workflow would give feedback to the student(s) about issues and their status, and feedback could be managed by course staff without PrairieLearn staff involvement. Sidebar uses Trello as a backend; that's worth exploring?

Could be a good hackathon task (Trello APIs and workflows). It would also give us an avenue besides incident reports for students to complain about question content.

**Comment by trombonekenny** [comment]
Similar to #116

**Comment by mwest1066** [comment]
My concept for this is that it would be controllable (on/off) on a per-assessment basis. For example, it would be good to have it turned on for homeworks with new questions, and for all exams. For well-tested homeworks it would normally be turned off.

The interface should be button on the question page (right-hand column) like "Report a problem" (or "Edit problem report" if there is already a report). This would open a text-box and accompanying buttons for "Submit report", "Cancel" (and "Delete report" if one already exists).

The DB storage should follow a similar pattern to the `points` in `instance_questions`. That is, we should add columns to `instance_questions` to store the problem report text and the time of reporting. In addition, there should be a `question_report_logs` table to store the history of every time a report is added, deleted, etc.

For instructors, the number of problem reports should be shown on the admin pages as a [Bootstrap badge](http://getbootstrap.com/components/#badges) showing report counts on lists of assessment questions, and list of assessment instances. The details should be shown on the assessment instance page.

For managing problem reports from the instructor side each report should have a `report_resolved` flag that the instructor can toggle. All of the badges showing problem report counts should only show unresolved reports. It's not clear to me whether students should see the "resolved" status. It would also be good to add "resolve all reports for this question" and "resolve all reports for this assessment" buttons.

**Comment by trombonekenny** [comment]
I guess I have two questions about workflow.

1) Would students go back and look at the questions again after reporting problems with it? If it's a lot of one time use, finish the problem, complain, and never look back then you don't have really think about designing in. If students do go back and check it (maybe along with their grade?), then you'd have a reason to code it in.

2) Do instructors typically engage in conversation around issues with questions, or make a decision and don't elaborate (or feel they need to at-the-question)? Maybe acknowledge is a better term than resolve? Or would we want a discussion like the git issues allows? (I'm guessing not.) Maybe the instructor interface could have a few quick buttons for common responses "Don't care", "You're wrong", "You're right; I've adjusted your points", "We'll talk about it in class", etc. Maybe a mailto: link to the student if they want more easy discussion?

I like tracking this inside PL - it means the people who are already in looking at results and grades can see issues without being pulled to a different interface. Trello is neat but probably not appropriate here. I also agree with making the feedback toggleable, but I feel like if we make it easy and attractive there's not much reason to not look for feedback?

It is also worth having a feedback toggle for the assessment as a whole as well as the individual questions?

**Comment by trombonekenny** [comment]
This came up today with Lane Schwartz who was looking for a configurable feedback widget in the questions to Likert scale measure student feedback on questions, regarding quality, difficulty, helpfulness for learning, etc. Something that did anonymous aggregate feedback to the instructor to evaluate their assessment.

**Comment by mwest1066** [comment]
I think the Issues system solves most of this? What's still needed?

**Comment by mwest1066** [comment]
Closing because PL Issues implement most of this, and there are other GitHub issues open about specific improvements.
