### ISSUE TITLE
Auditing/alerting of PL exams vs CBTF scheduled exams

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#420]
Using data from the scheduler and PL, build a system to help audit and identify discrepancies between the two with exam scheduling. For example, a course has an exam scheduled in the CBTF but no PL exam open during that time frame, etc. (Or multiple quizzes posted, perhaps inaccurately.) Ideally this is something that could alert ahead of time if things don't match up.

**Comment by mwest1066** [comment]
Fixed by 5c82094822864fc6e222dcbe04e880cff318f6b2
