### ISSUE TITLE
pl-variable-output: label as Octave/Matlab

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4248]
Would you accept a patch to change the label from Matlab to Octave/Matlab (or Matlab/Octave) if you prefer?

Or maybe the labels could be customizable?  As sometimes Octave dev, I'd be happier to be advertising Octave to my students!

**Comment by eliotwrobson** [comment]
I think this is a pretty harmless change @cbm755 , but I'm not sure about the value add vs code bloat here. Do most people not know that the code is valid in both languages?

**Comment by cbm755** [comment]
I'm not sure what the target audience will be aware of: many students in a course are likely encountering *all* these tools for the first time...

The languages are not quite compatible; especially if one is using packages/toolboxes.

So I guess some kind of customization would be ideal.  Since its not apparently an automatic "no", I'll see if I can poke around in the code (although of course happy enough if someone gets to it first!)

- - - -

For reference, here's one of my questions:

![image](https://github.com/PrairieLearn/PrairieLearn/assets/818622/9f0ab7c0-135a-43e3-80d8-7207cc3b2c85)

(I have an open issue to learn enough Bootstrap to copy the look of the built-in widget)

**Comment by eliotwrobson** [comment]
@cbm755 Are you sure that the Matlab output will always be compatible with Octave? If so, it's just a one-line change to the heading in the mustache template here: https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/elements/pl-variable-output/pl-variable-output.mustache#L4

However if there is some incompatibility, there will need to be more substantial code changes.
