### ISSUE TITLE
pl-number-input: Add user-controlled threshold for switching to scientific notation

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#4253]
Currently in the `pl-number-input` element, large numbers are only formatted as scientific notation if they are above 1E12. Personally, I think that should be reduced to 5 or 6, but ideally this would be a user-controlled parameter - maybe `scinot-threhold` or something similar?

In [`pl-number-input.py`](https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-number-input/pl-number-input.py#L47) the relevant code is:

```
def format_true_ans(element, data, name):
    a_tru = pl.from_json(data['correct_answers'].get(name, None))
    if a_tru is not None:
        # Get comparison parameters
        comparison = pl.get_string_attrib(element, 'comparison', COMPARISON_DEFAULT)
        if comparison == 'relabs':
            # FIXME: render correctly with respect to rtol and atol
            a_tru = '{:.12g}'.format(a_tru)
```

I was about to start working on a PR to implement this but there's a `# FIXME` note from @nicknytko (if I read git blame correctly) that I don't fully understand.

P.S. Because of this hard-coded setting we (@jake-bobowski and I)  have to go through work-arounds with `parse` to correctly format the numbers:

![119284306-404af280-bbf4-11eb-90b8-dcfce6cb8811](https://user-images.githubusercontent.com/2507459/119390139-76828380-bc81-11eb-8296-8034d5c61307.png)

**Comment by jonatanschroeder** [comment]
I'd probably be in favour of a more generic option that determines the format to be used (e.g., `.6g` in your case) for string representations.
