### ISSUE TITLE
Can PrairieLearn be integrated with Honorlock

### ISSUE THREAD

**Issue by maxieds** [PrairieLearn/PrairieLearn#4263]
Can PrairieLearn be configured to be run in combination with [Honorlock](https://honorlock.com/)? A current solution for me is to use my LMS generated quiz assignments and run them through Honorlock to detect cheating for exams proctored in the online format. This software looks very promising for what I really need to do.

Apologies if this is not a good forum to ask that question. I found no information on the PrairieLearn FAQ nor Knowledge Base, and searching around yields no solid leads for information about this topic. 

Thanks in advance.

**Comment by cheeren** [comment]
I've invited you to the general PL slack channel.

**Comment by maxieds** [comment]
Thanks, Cinda!

I think I resolved the issue after posting on the Slack channel last night. I will repeat what I understood there in case anyone else is in this boat of having to use Honorlock with Canvas and finds this via a search (or data mining adventure). The cheating in this class when exams are given in the online-only pandemic format was so rampant this year that using Honorlock was the only alternative we came up with in place of oral exams for an in depth calculus class.

Basically, for my course, we rely on students being able to authenticate to Honorlock via our roster on the Canvas LMS. Honorlock support in this LMS allows the course staff to create a third-party based exam. You can provide an external link. My understanding is that after authenticating with Canvas / HL, the students will be directed to take the graded assessment on the external (e.g., PL) site with the usual protections that the HL platform enables. My use case is still going to require testing. I'm currently waiting on approval for my course space on the main PL.org site. 

I do not want to waste the developers' time here, so I will proactively close the issue. Many thanks to this option with ``sympy`` processing of plaintext math formulas! 😺
