### ISSUE TITLE
Feature request to add more built-in reserved function names for symbolic input parsing

### ISSUE THREAD

**Issue by maxieds** [PrairieLearn/PrairieLearn#4268]
@jonatanschroeder @echuber2 @cheeren 

I am following up from a discussion about several work arounds and in-progress features for PL recently on the Slack forum. I have a very strong use case for adding a few more built-in reserved function names that are parsed when invoking the input element tag ``pl-symbolic-input``. These functions are stock in intro calculus classes so that they should most likely be integrated by default. The list of actively accepted functions given on my course workspace on [PL.org](https://www.prairielearn.org/) (Illinois / UIUC version of the software) is:

![Screen Shot 2021-05-29 at 6 26 19 PM](https://user-images.githubusercontent.com/22165688/120086796-12602500-c0b0-11eb-9d74-ffc2e44c63a9.png)

Minimally, I will need support for the following functions: ``ln / sec / cot / csc / atan / asin / acos`` and perhaps even some hyperbolic trig function names are nice as well with ``atanh / acosh / asinh / etc``. I realize that support for a subset of my requested functions is already in the works. Can one of the developers please try to add the remaining function names sometime soon?

I also mentioned that I am interested in hacking around the PL source to eventually file a pull request to offer more robust support for reserved function names in the symbolic input elements. The tag already supports on-the-fly definitions of custom variable names to be used in the symbolic parsing. I aim to do the same to add on-the-fly support for custom function names in the ``pl-symbolic-input`` element tag. I do not know how long this will take me, but I will start looking at the task tonight. E.g., eventually I would like the following to work:
```html
<pl-symbolic-input 
     answers-name="du" 
     variables="x, dx" 
     extra-functions="ln, sec, asinh, atanh, atan"
     label="$14x^6dx$"
>
</pl-symbolic-input>
```
Many thanks for the helpful discussions on learning and using PL!

**Comment by mwest1066** [comment]
Following the pattern of #4217 is the way to add more core functions, but I agree that it would be awesome to allow the question writer to specify the list of functions, just like is currently done with the variable list.

**Comment by maxieds** [comment]
@mwest1066 
Am I correct in interpreting the sources for the symbolic-input element (and its helper class) that the parser that checks the symbolic input for correctness does not handle reserved function names evaluated at multiple variables? All of the examples I see are univariate. I thought to add ``max/min`` and then support for multivariate functions when I get the PR in, but there does not seem to be immediate support for handling that use case.

**Comment by mwest1066** [comment]
I'm not sure (I didn't write this element). It's certainly possible that this is a limitation of the current code. We are being very careful with parsing because `sympy` is not safe on general untrusted input (see the comments [here](https://github.com/PrairieLearn/PrairieLearn/blob/27076937668b04969fb3a1697ec7f414064da4c7/lib/python_helper_sympy.py#L44)). If current functions are limited to a single element, it would be awesome to fix this to allow `max`/`min`/etc.

**Comment by jonatanschroeder** [comment]
If my multiple variables you mean functions with two arguments, then it supports `log(a, b)`... Is that what you mean?

**Comment by maxieds** [comment]
@jonatanschroeder 
Yes, my bad. That makes sense.

**Comment by maxieds** [comment]
I think this can be closed whenever the pull request is merged.
