### ISSUE TITLE
parse fractions in numeric answers

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#43]
Students seem to expect that they can enter numeric answers in the form "3/2" instead of "1.5". This is probably due to familiarity with WebAssign (used for math classes at UIUC), which can accept this. We should probably change things to handle this.

**Comment by cdschmit** [comment]
Is this still just a wish-list item? I seem to have more and more students attempting to enter fractions.

**Comment by mwest1066** [comment]
@cdschmit are the students doing this on v2 or v3 questions? We've tried to mitigate the issue in v3, but I'm open to revisiting this issue if it's still a problem.

**Comment by cdschmit** [comment]
Hmmm...Yeah, I think it is a V2 problem. In v3, does it evaluate? I'll update it and see what happens.

**Comment by mwest1066** [comment]
In v3 it currently doesn't evaluate, but it tells students that it's invalid and it lets them try again with no penalty (doesn't count as a grading attempt).

**Comment by mwest1066** [comment]
For some reason (experience with other platforms) it does seem that some students expect to be able to type fractions into numeric answer boxes. Is it easy to implement this without pulling in all of sympy? Just special-casing strings with a `/` in them?
