### ISSUE TITLE
Cannot use mathjax inside a dropdown pl-answer

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4339]
Here's a snippet of my html:
```
    <pl-dropdown sort="random" answers-name="ans1">
      <pl-answer correct="true">Critical points of $f(x,y)$</pl-answer>
      <pl-answer>The local maxima of the function $f(x,y)$</pl-answer>
      <pl-answer>The global extrema of the function $f(x,y)$</pl-answer>
    </pl-dropdown>
```

The math is silently erased and I get:
![tmp-screenshot](https://user-images.githubusercontent.com/818622/120551615-17242200-c3ab-11eb-8b06-392423e9f3ca.png)

(note no "f(x,y,)").

Is this a browser limitation or our fault?  If browser limitation does one to to build our own widget (sounds harder).  If our fault, maybe there is an easy fix?

**Comment by mwest1066** [comment]
> Is this a browser limitation or our fault? If browser limitation does one to to build our own widget (sounds harder). If our fault, maybe there is an easy fix?

I'm afraid that it's a browser limitation. As described in #3145, `<pl-dropdown>` renders using the HTML `<select>` element which only supports plain text, not the elements that MathJax outputs.

I like @nicknytko's suggestion from #3145 to switch to a custom implementation that leverages the Bootstrap dropdown widget.

**Comment by cbm755** [comment]
Apologies for poor search, closing dupe of #3145.
