### ISSUE TITLE
Show quiz and exam scores even when details are hidden

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#434]
We should have `allowAccess` rules like:

    {
        "role": "Student",
        "level": "Score"
    }

This means that students would have access to this assessment, but only to see their total score. We could use this for quizzes and exams, so they would show up in the list of all assessments with scores, but the student would not be able to actually see the questions and other details in the assessment.

This feature might help to reduce the incidences of students claiming at the end of semester that they took a quiz that they didn't take.

**Comment by trombonekenny** [comment]
Does the student gradebook functionality resolve this?

**Comment by mwest1066** [comment]
Implemented in #1722
