### ISSUE TITLE
pl-file-upload: scary "Unable to decode file" in preview for binary files

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4350]
A great first step would be to say "Binary file: preview currently not not implemented".  Or "preview currently not implemented for this file type".

I checked .jpg, png and pdf and got:
![Screenshot from 2021-06-04 15-44-17](https://user-images.githubusercontent.com/818622/120869704-e16a6f00-c54b-11eb-9ccb-a275b1b853df.png)

(I didn't check .zip).

That error message is a little too scary.  I think students will repeatedly upload, assuming they did something wrong.  Then they will bother me on a discussion forum! ;-)

- - - -
- 
Workaround: For now, I will add text telling students they can verify their upload by clicking `[download]`

**Comment by firasm** [comment]
I agree, that message is a bit alarmist.

The message can be updated with a fix to the following files:

- [pl-file-preview.py - line 38](https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-file-preview/pl-file-preview.py#L38)
- [pl-file-upload.js - line 185](https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-file-upload/pl-file-upload.js#L185)

As far as the message, here's another suggestion: "The file was successfully uploaded, but a preview is not available."
