### ISSUE TITLE
pl-file-upload: preview images and pdf files with thumbnails

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4351]
Non-urgent, but it would be great to show a little thumbnail of at least some common image formats and pdf files.

Currently it looks like this:
![Screenshot from 2021-06-04 15-44-17](https://user-images.githubusercontent.com/818622/120869704-e16a6f00-c54b-11eb-9ccb-a275b1b853df.png)

**Comment by eliotwrobson** [comment]
Seems to be partially resolved by https://github.com/PrairieLearn/PrairieLearn/pull/4813

Not sure if there is some significant obstacle to doing this for PDFs though.

**Comment by eliotwrobson** [comment]
So this might be doable for a number of file types with this python package: https://github.com/algoo/preview-generator

Not sure if that will be a mess on the backend though.

**Comment by jonatanschroeder** [comment]
This may be an option: https://www.w3docs.com/snippets/html/how-to-embed-pdf-in-html.html

**Comment by eliotwrobson** [comment]
> This may be an option: https://www.w3docs.com/snippets/html/how-to-embed-pdf-in-html.html

That's probably the easiest solution if we just want to do PDFs. It would also be cool to enable syntax highlighting for known languages (maybe through `highlight.js`).

**Comment by jonatanschroeder** [comment]
Solution for PDF already used elsewhere in PL:
https://github.com/PrairieLearn/PrairieLearn/blob/master/apps%2Fprairielearn%2Fsrc%2Fpages%2FinstructorFileBrowser%2FinstructorFileBrowser.html.ts#L396-L408

Same for pl-file-preview.

**Comment by jonatanschroeder** [comment]
> It would also be cool to enable syntax highlighting for known languages (maybe through `highlight.js`).

This is the only thing in this PR that is not yet implemented. @eliotwrobson do you think this is useful or just "cool"? In that case it may be worth moving this to a new separate issue. That said, it may be tricky to do that client-side. You can do it with highlight.js, but you probably don't want to load [a pretty big bundle](https://bundlephobia.com/package/highlightjs@9.16.2) just for that (and if I get it correctly, you may also need to load the individual languages separately).

**Comment by eliotwrobson** [comment]
@jonatanschroeder I think it's pretty redundant given that this is just for files that have already been submitted. Makes sense to skip if adds too much overhead.
