### ISSUE TITLE
Add new panel for "Reference Material" for questions

### ISSUE THREAD

**Issue by lslavice** [PrairieLearn/PrairieLearn#4359]
Some questions could really benefit from having a separate "reference material" panel/section that can include things like definitions for helper functions that must be used, samples of input/output, or other "see the appendix" type information. 

The idea is that this reference material could be housed in a separate panel from the question and submission panels, keeping the question panel free to be the "story" for the question and allowing students to scroll through the reference material as needed while they create their submission.

Here are a couple of examples of what I'm talking about, from a hurriedly-thrown-together online exam platform a colleague of mine created because of covid. There is a PL-type question + submission column/panel on the left, with a separately-scrollable reference material column/panel on the right: 

![image (10)](https://user-images.githubusercontent.com/70032904/121027970-64224280-c775-11eb-9192-e46e90081320.png)

![image (9)](https://user-images.githubusercontent.com/70032904/121027961-61275200-c775-11eb-9f3f-d35abd8f4b21.png)

This feels like a higher level design decision for PL than I can directly contribute because it would (ideally) use space to the right of the existing question panel, so I'm opening this issue. I'd love for some discussion to happen here, especially if this is something that other people would find useful! Right now, this is a critical feature that is blocking us from adopting PL for our exams. :(

**Comment by firasm** [comment]
Interesting @lslavice - what about using an iFrame to do this in Prairie Learn? 

Similarly (and perhaps cleaner and nicer), all of the bootstrap components are available in PL also. 

- How about a [Modal ](https://getbootstrap.com/docs/5.0/components/modal/#scrolling-long-content)?
- It can even be a [full screen modal](https://getbootstrap.com/docs/5.0/components/modal/#scrolling-long-content)

So it would look something like this if student clicked a button for the reference material
<img width="1664" alt="Screen Shot 2021-06-12 at 11 52 43 AM" src="https://user-images.githubusercontent.com/2507459/121786464-b8ae2f00-cb74-11eb-8cd0-01b3dd9c08f1.png">

Happy to help you implement this in a question if this works for you, but everything can happen within a single question using the `question.html` file and if you want to bring in randomized content, the `server.py` file.

**Comment by lslavice** [comment]
Thanks for thinking about this! We could use an iFrame or other components, but I don't think that we would be able to situate anything outside the usual question box. I worry that if we try to split the question box horizontally, then we end up with two "tall and skinny" boxes which would create bizarre formatting. The modals are a good idea (and get around this issue), but then students can't construct their answer while viewing the reference material at the same time. :/ 

What I'm imagining is using some of the horizontal screen space for a reference material panel/section. And I think that has to be a decision from the PL team.

**Comment by lslavice** [comment]
Just as an update, this is what we ended up doing: making the question panel be as wide as possible so that we can fit a set of answers next to the reference material the students need to look at. But it would be nice if we could move the reference material panel outside of the question box because sometimes it blocks some of the answers, plus having the question panel be that wide isn't good for actually reading the material.


![image](https://user-images.githubusercontent.com/70032904/135163311-97302966-2e66-4a67-aa57-a471f86b8ceb.png)

**Comment by nwalters512** [comment]
👋 for folks wishing to provide reference information, "cheat sheets", and so on, we generally encourage one of two things:

- Add that content directly to the question (as you've done!)
- Use `clientFilesCourse` or `clientFilesAssessment` to host a PDF and make it available in an assessment's `text` property as documented here: https://prairielearn.readthedocs.io/en/latest/faq/#how-can-we-provide-a-cheat-sheet-for-cbtf-exams

Not to get too much into unsolicited instructional design advice, but in pretty much all the examples posted here, the "Reference material" information reads as core information necessary to correctly answer a question, and it may be better to try to implement it directly into the main question "story" itself as opposed to trying to separate it somehow 🙂 

We like to avoid having too many ways to accomplish the same thing, and given that we already have two ways to achieve this, I'm going to go ahead and close out this issue. I'm glad you were able to find something that works well for you! If you have a really compelling use case for separating out part of the question like this, feel free to open a new issue with the specifics of that use case.
