### ISSUE TITLE
cannot set more than one pl-multiple-choice as correct

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4380]
So I tried:
```
<pl-multiple-choice answers-name="acc" weight="1">
  <pl-answer correct="false">$3 = 4$</pl-answer>
  <pl-answer correct="true">I like cats</pl-answer>
  <pl-answer correct="true">I really like cats</pl-answer>
</pl-multiple-choice>
```
What happens is only one of my `true` radio buttons shows.   I think both should show.  And either should be correct (but user can only choose one).

- - - - 
My real question use-case is:

```
[   ]  I consent to blah blah blah
[   ]  I do not consent to blah blah blah
(No wrong answer here and no pressure).
```
(both are correct but to get points you must pick one and you cannot pick both)

**Comment by mfsilva22** [comment]
You can add a `server.py` file with the following:

def grade(data):

    data["score"] = 1
    data['partial_scores']['answers_name_for_mc_element'] = {'score': None}

**Comment by cbm755** [comment]
Thanks for that!  I have other parts to the question so futzing around with "score" still...

But is there some fundamental reason why I cannot have multiple true?  like OOTB without swearing at `parse` and `grade`?

**Comment by mfsilva22** [comment]
I am not sure I would say we have a fundamental reason, but it is not implemented as of now. We have thought about implementations that would help with survey questions, but never got to it. 

For the time being, I would suggest just using the grade function. I have used the code above in many of my survey questions, and they often include more parts as well. You can just set all the partial scores, and then sum them all, so that you have the overall `data["score"]`.

**Comment by cbm755** [comment]
I have a Slack thread elsewhere trying all that, but I just cannot get it to work.  I have the score working, but the red/green check/cross etc are not cooperatiing

**Comment by cbm755** [comment]
My best effort thus far:
```py
def grade(data):
    # any answer is ok for consent MC
    consent = 'consent'
    del data['partial_scores'][consent]
    local_bullshit = 0
    if consent in data['submitted_answers'].keys():
        local_bullshit = 1

    score = 0
    variables = data['partial_scores'].keys()
    for name in variables:
        score += data['partial_scores'][name]['score']
    score += local_bullshit
    data['score'] = score / len(variables)
```

**Comment by mfsilva22** [comment]
That is why I don't use the `partial_score` and instead set it to None. I don't like the marks either when creating surveys.

**Comment by cbm755** [comment]
Ah I will try that instead of `del`!

**Comment by cbm755** [comment]
Ok, thanks so much, that is very close to what I want.  I can get the red thingy if they leave it blank, but otherwise use your `del` trick to hide it.   This seems to fragile for production so I think I'll use an alternative soln but pasting here if it helps someone:

```py
    # TODO: is this always the right length?
    number_of_parts = len(data['partial_scores'].keys())
    score = 0

    consent = 'consent'
    if consent in data['submitted_answers'].keys():
        score += 1
        # set to None avoids misleading green/red thingies
        data['partial_scores'][consent] = {'score': None}

    # no file submission gives no points
    if data['submitted_answers']['_files'] == []:
        print("giving zero for files")
        data['partial_scores']['_files'] = {'score': 0, 'weight': 1}
    else:
        data['partial_scores']['_files'] = {'score': 1, 'weight': 1}

    variables = data['partial_scores'].keys()
    for name in variables:
        if name == consent:
            # force skip the consent
            continue
        score += data['partial_scores'][name]['score']
    data['score'] = score / number_of_parts
```

**Comment by cbm755** [comment]
Summary:
  * `data['partial_scores'][foo] = {'score': None}` will prevent rendering of green/red feedback thingies
  * `del data['partial_scores'][foo]` will NOT prevent rendering of green/red feedback thingies and they will likely be incorrect from user perspective.
  * If you change scoring, you have to manually recalculate the sum
Probably that last point is well-known: there is a somewhere in the docs the discusses the first two?

**Comment by mfsilva22** [comment]
I will be working on improving the documentation this summer, and will make sure to address this point. I think we have an open issue for docs, I should try to add your comment there, so I can close this issue

**Comment by cbm755** [comment]
Do you have an issue number for the `pl-survey-question` or similar?   Or should we leave this open as a  request to allow multiple `correct="true"` elements?

**Comment by mfsilva22** [comment]
You can leave it open for future development.

**Comment by cbm755** [comment]
BTW, my production solution was to use a separate question for a survey: and your original suggestion worked perfectly there!  thanks

**Comment by eliotwrobson** [comment]
The pl-multiple-choice element now allows for manually setting the score for incorrect answers, satisfying this use case. This issue can be closed now.

**Comment by mwest1066** [comment]
Thanks @eliotwrobson!
