### ISSUE TITLE
Browser line-breaks awkward places near TeX

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4382]
Input:
```
<p>
  ...
  (Here we are looking for an expression in terms of $c$.)
</p>
```

Rendering:
- - - -
![Screenshot from 2021-06-16 23-44-26](https://user-images.githubusercontent.com/818622/122346206-919d8780-cefd-11eb-8cd9-ea4a5f066772.png)
- - - -
Which is suboptimal :(

I asked Firefox for the actual source code of the rendered page and saw:
```
</span>.
  (Here we are looking for an expression in terms of <mjx-container class="MathJax" jax="CHTML" style="font-size: 125.7%;"><mjx-math class="MJX-TEX"><mjx-mi class="mjx-i"><mjx-c class="mjx-c1D450 TEX-I"></mjx-c></mjx-mi></mjx-math></mjx-container>.)
</p>
```
Which looks reasonable enough.  So maybe not our bug?

- - - - 
 
If not fixible in PL, does anyone know of a workaround (like `\mbox{}` in LaTeX) to tell the browser that we REALLY DON'T want that line-break?

**Comment by cbm755** [comment]
I read [1] and can confirm this workaround:
`(Here we are looking for an expression in terms of <nobr>$c$.)</nobr>`
(but sounds like `<nobr>` is non-standard)
![Screenshot from 2021-06-17 00-10-11](https://user-images.githubusercontent.com/818622/122349043-adeef380-cf00-11eb-9788-9758e4b4c9d5.png)

[1] https://stackoverflow.com/questions/19212188/avoid-line-break-between-html-elements

**Comment by jonatanschroeder** [comment]
I don't know if there's an easy way to fix this in general, since there could be situations where a line break after the Latex may be permissible. In this case the `nobr` you listed is valid, but it's deprecated (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr) and should be avoided, as it's not guaranteed to be supported in all browsers in the future. My suggestion is that you use something like: `<span class="text-nowrap">$c$)</span>`.

**Comment by mwest1066** [comment]
I believe the plain HTML/CSS is to use [`white-space: nowrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) like this:
```
(Here we are looking for an expression in terms of <span style="whitespace: nowrap">$c$.)</span>
```

(this avoids the use of the bootstrap CSS `text-nowrap` class within a question)

**Comment by nwalters512** [comment]
Closing as there isn't really anything that PrairieLearn can do about this. As pointed out above, instructors can add custom markup to their question to control how content breaks.
