### ISSUE TITLE
Allow pl-answer to have well-defined classes that can be used for formatting

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4391]
I have had questions where I wanted to have some formatting for multiple choice or checkbox, e.g.:

```
    <style>
      div.checkbox-options .form-check:nth-child(odd) {
          background-color: #dae0e5;
      }
    </style>
    
    <div class='checkbox-options'>
      <pl-checkbox answers-name='q' partial-credit='true' partial-credit-method='PC'>
        <pl-answer correct='true'>...</pl-answer>
        ...
      </pl-checkbox>
    </div>
```

The issue is that this is based on `form-check` being the class used in `pl-checkbox` for an individual answer box, but I think relying on that can be a problem if at some point in the future this is no longer the case. It would be good to have some other class (e.g., `pl-answer-box` or something similar) that can be more reliably used for this kind of formatting.

**Comment by echuber2** [comment]
It's a reasonable request. I'll just add that if anyone is concerned about the element internals "breaking" their hacks/customizations down the road, one solution is to fork the default PL element as a course element.

**Comment by jonatanschroeder** [comment]
I don't like to describe that workaround as a "solution". Forking the default element means any future updates to the element code (features, bug fixes, etc.) need to be manually merged by instructors later.

**Comment by echuber2** [comment]
It's also hard to guarantee that there wouldn't be some other breaking changes that would change the behavior of ad-hoc hacks and modifications, though.

**Comment by jonatanschroeder** [comment]
@eliotwrobson you're playing with `pl-checkbox` and `pl-multiple-choice`, do you think this can be added to those PRs?

**Comment by eliotwrobson** [comment]
@jonatanschroeder sure! I'll start by adding this to the `pl-multiple-choice` in this PR: https://github.com/PrairieLearn/PrairieLearn/pull/6775

The changes to checkbox will be based on the changes in the multiple choice PR.

**Comment by jonatanschroeder** [comment]
> Speaking of which, if you have some time, I need some help with getting the javascript for the dropdown PR working correctly. I think it's the last real obstacle to merging that.

Sure, can you expand on what you need help with?

**Comment by eliotwrobson** [comment]
> Sure, can you expand on what you need help with?

Will discuss on the PR, basically just figuring out how to make the dropdown element work as a selector.

**Comment by nwalters512** [comment]
This change would effectively make the HTML structure part of an element's public API, and thus make it very difficult to make _any_ future changes to elements in a backwards-compatible way. We won't be implementing this at this time. If there are particular widely-desired style modifications for elements, we can consider implementing them as official attributes on an element-by-element, feature-by-feature basis.
