### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by JustinYokota** [PrairieLearn/PrairieLearn#4423]
The documentation for the grade function suggests that data["partial_scores"][NAME] is a numeric value corresponding to the score. This is incorrect; data["partial_scores"][NAME] is a dictionary, with data["partial_scores"][NAME]["score"] containing the score for a question.

**Comment by nwalters512** [comment]
AFAICT the docs correctly document this, e.g.

https://github.com/PrairieLearn/PrairieLearn/blob/2207a5b0fb6383d846fd9bdcc157193c1a87a4a6/docs/devElements.md?plain=1#L103

If you can point to a specific line in the current docs that's incorrect, please open a new issue with that!
