### ISSUE TITLE
natural logarithm 

### ISSUE THREAD

**Issue by jake-bobowski** [PrairieLearn/PrairieLearn#4463]
It would be really nice if PrairieLearn symbolic-input question accepted ln (the natural logarithm).  As far as I can tell, symbolic-input questions will only accept log.  It would be nice if log was assumed to be base 10 and ln to be base e.

**Comment by maxieds** [comment]
@jake-bobowski 
I have already submitted a pull request [here](https://github.com/PrairieLearn/PrairieLearn/pull/4334) to make that happen. It does not seem to be on the radar of the PL admins or on the priority list for their revisions to the sources any time soon. I actually found trying to use PL to encode problem solutions for an integral calculus course that even more standard function names were missing. The pull request I put into the queue over a month ago handles this problem pretty well, I think. If you are running your own server or Docker instance, you can feel free to clone my branch that implements this functionality. 😺

**Comment by jake-bobowski** [comment]
@maxieds 
Thanks for pointing me to your pull request.  It looks like you've thought about this problem is a lot more detail than me and came up with a good solution.  @firasm and I are preparing to use PL in first-year physics courses.  The natural logarithm comes up frequently and it would be confusing to ask students to always use log!

**Comment by maxieds** [comment]
@jake-bobowski 
Yes, I noticed that. The Stewart Calculus book also defines the convention that ``log`` means the base-10, or Richter scale type operation, whereas everywhere else it means the natural logarithm. Note that I added documentation [at this page](https://github.com/maxieds/PrairieLearn/blob/add-custom-reserved-functions-to-symbolic-input-element-v2/docs/elements.md#pl-symbolic-input-element) that allows for users to define custom function names to be symbolically handled by ``sympy`` -- even when there is no explicit definition to evaluate. At that point the symbolic processor stops and will still recognize that ``MyFuncName(10 * x + 3)`` is the same as ``MyFuncName(3 + x * 10)``, for example. 

I'm glad you are finding it useful. Unfortunately, I was not able to use PL through Canvas for my class this summer.

**Comment by firasm** [comment]
> the symbolic processor stops and will still recognize that MyFuncName(10 * x + 3) is the same as MyFuncName(3 + x * 10)

@maxieds that sounds like a very useful feature!

**Comment by echuber2** [comment]
> It does not seem to be on the radar of the PL admins or on the priority list for their revisions to the sources any time soon

I think a lot of people are traveling around this time. (I also bookmarked your PR to review myself, although I'm not an admin.) I'm sure it will be added soon.
