### ISSUE TITLE
Possible typo in unused function "begiTransactionAsync"

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#4473]
https://github.com/PrairieLearn/PrairieLearn/blob/6db55619751f2bc3dc272ae8062efd3219d40539/prairielib/lib/sql-db.js#L363

The function name here seems like it's probably a typo. I don't think anything calls it currently though.

**Comment by mwest1066** [comment]
Yep, definitely a typo. Want to fix it?

**Comment by echuber2** [comment]
Sure.
