### ISSUE TITLE
Slack join link in docs nonfunctional

### ISSUE THREAD

**Issue by brghena** [PrairieLearn/PrairieLearn#4486]
https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/requestCourse.md contains a link to join the PrairieLearn slack organization, however the link is out-of-date and no longer works. Could a new link be added?

**Comment by nwalters512** [comment]
cc @trombonekenny I believe you control https://go.illinois.edu/joinplslack - can you point it at the correct join link?

**Comment by trombonekenny** [comment]
I have been using https://go.illinois.edu/PrairieLearnSlack which explains why that wasn't updated. I've updated https://go.illinois.edu/joinplslack too but I'm not sure we need two different go links in the docs?
