### ISSUE TITLE
Adopt versioning system for PL?

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#4541]
Hi all,

Since PL is now a mature product, I wanted to make a plug for adopting some sort of versioning system for PrairieLearn. It seems from the [changelog](https://github.com/PrairieLearn/PrairieLearn/blob/master/ChangeLog.md), there are some version numbers (perhaps a mix of calendar and semantic?) but they don't appear anywhere in PL that I can see except the [releases](https://github.com/PrairieLearn/PrairieLearn/releases) page.

I'm sure we all know this but the overall the main benefits of versioning are:
- Link PRs and issues to versions
- transparency on when new features make it from `main` to production
- tracking and hunting bugs
- easily revert to a previous version if a bug hits production
- allows for `production` and `beta` deployments (locally or otherwise)
- permits migration paths and allows more flexibility in choosing which version to deploy
- Use of GitHub actions and bots to handle/automate version bumps

Versioning is a bit of grunt-work unfortunately, but it is superior to deploying and tracking git SHAs - the one caveat is that versioning only makes sense **after a project is reasonably stable**.

The three main options that may work are:

## 1. [Semantic versioning](https://semver.org)

**Summary**

Given a version number MAJOR.MINOR.PATCH, increment the:

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.
- Additional labels for pre-release and build metadata are available as extensions to the -MAJOR.MINOR.PATCH format.

**Pros**:
- well-established, and familiar 

**Cons**:
- Version inflation with frequent releases (soon PL will be at v `2.500.1` etc...)

## 2. [Calendar versioning](https://calver.org)

**Summary**:

- Major - The first number in the version. 2 and 3 are Python's famous major versions. The major segment is the most common calendar-based component.
- Minor - The second number in the version. 7 is the most popular minor version of Python.
- Micro - The third and usually final number in the version. Sometimes referred to as the "patch" segment.
- Modifier - An optional text tag, such as "dev", "alpha", "beta", "rc1", and so on.

**Pros**:
- Fits nicely with a calendar or date-based release schedule 
- Most famous example is Ubuntu version (20.04, 21.04 etc...)

**Cons**:
- version numbers are long
- Not as well accepted

## 3. Ad-hoc versioning

Not sure how to describe this other than to increment major, minor, patch versions "when it feels right".

## Context:

Apologies if this is not relevant, but I was trying to figure out "what is the current version of PL" and I hit a roadblock because the [changelog](https://github.com/PrairieLearn/PrairieLearn/blob/master/ChangeLog.md) seems to be out of sync with the [News](https://www.prairielearn.org/pl/news_items) (also it seems CA PL has a different news section! very odd).

Would love some thoughts on this, and I'm happy to volunteer to do some of this work.

**Comment by tdy** [comment]
related: [deployment status page (#3178)](https://github.com/PrairieLearn/PrairieLearn/issues/3178)

**Comment by trombonekenny** [comment]
Bump for this coming up in conversation again.

**Comment by trombonekenny** [comment]
PS does this:

```javascript
utilities.getGitHash = function(callback) {

    var dir = process.cwd();
    var out = {};

    fs.readFile(dir + '/.git/HEAD', 'utf8', function(err, result) {
        if (ERR(err, callback)) return;

        var headref = result.trim();

	if (headref.startsWith("ref: ")) {
	    // ref: refs/heads/githash  ---> githash
	    out.branch = headref.split('/').pop();

            fs.readFile(dir + '/.git/refs/heads/' + out.branch, 'utf8', function(err, result) {
                if (err) {
                    if (err.code == 'ENOENT') {
                        // no such file or directory, might be packed away
                        // TODO get this out of .git/packed-ref
                        out.commit = 'none yet';
                        out.short_hash = 'none yet';
                    }
                } else {
                    if (ERR(err, callback)) return;
                }

                if (result) {
                    out.commit = result.trim();
                    out.short_hash = out.commit.substring(0, 7);
                }
                //console.log(out);
                callback(null, out);
            });
        } else {
	    // Detached head state
	    out.branch = '';
	    out.commit = headref;
	    out.short_hash = out.commit.substring(0, 7);
	    callback(null, out);
	}
    });
};
```

**Comment by nwalters512** [comment]
I won't comment on specific versioning strategies, but the fact that `ChangeLog.md` is unmaintained is definitely confusing. I opened #6606 to remove it.

**Comment by nwalters512** [comment]
We've been using Git commit hashes to refer to current/released versions both internally and in release announcements posted to Slack and GitHub. We're likely to continue doing so into the foreseeable future. At this point, any kind of formal versioning scheme is almost certainly more work for us than it's worth.
