### ISSUE TITLE
Assignment grade download CSV in Canvas format

### ISSUE THREAD

**Issue by w-chang** [PrairieLearn/PrairieLearn#4547]
Can the option to download grades from PrairieLearn formatted for Canvas instead of Compass2g be added to the list of links in the "Download" tab?

**Comment by mwest1066** [comment]
Here are [Canvas docs for CSV uploads](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-import-grades-in-the-Gradebook/ta-p/807).

**Comment by mwest1066** [comment]
@jonatanschroeder do you upload CSVs with assessment scores into Canvas? Could you tell me what format it needs? In particular, what is the "ID" column that the [docs](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-import-grades-in-the-Gradebook/ta-p/807) reference?

**Comment by jonatanschroeder** [comment]
> @jonatanschroeder do you upload CSVs with assessment scores into Canvas? Could you tell me what format it needs? In particular, what is the "ID" column that the [docs](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-import-grades-in-the-Gradebook/ta-p/807) reference?

I've done a few local tests, and here's the deal:

* The docs list several columns as required, but it works with only part of them. The columns you actually need are: **Student** (full name, can be "last, first", e.g., "Schroeder, Jonatan", or "first last", e.g., "Jonatan Schroeder"), **SIS Login ID** (for us this is the UIN, not sure how it would work with Illinois) and **Section** (from my tests the column must be there, but it doesn't need to have any valid data, even blank worked).
* About the assignment columns, the Assignment ID makes it easier to map to a Canvas assignment, but if the name matches exactly without an ID it works too. If the name doesn't match exactly the upload process will ask to confirm which assignment it is (or to create an assignment), so working with the name only should be fine.
![image](https://user-images.githubusercontent.com/1004907/128645365-4becd8d9-56da-4749-92ad-c9f9f1ddc7cc.png)

Let me know if you have any other questions.

**Comment by jonatanschroeder** [comment]
![image](https://user-images.githubusercontent.com/1004907/128645397-13518cda-c344-41e8-b139-3e95734b7373.png)

**Comment by mwest1066** [comment]
> I've done a few local tests, and here's the deal [...]

Excellent! This is exactly what I needed to know to add "score_for_canvas.csv" and "points_for_canvas.csv" options to the Downloads page.

**Comment by wadefagen** [comment]
We built a browser-based tool to take an {external tool CSV, Canvas gradebook export} to transform them into a CSV into something that Canvas will accept (https://waf.cs.illinois.edu/tools/Canvas-External-Grade-Import-Tool/) to solve this for other tools.

I can confirm confirm @jonatanschroeder's tests with Illinois' Canvas.  Specifically, a minimally functional CSV file has the following:
- Headers in Row #1 of the CSV
- `Student` as the first column and contains the student's name (Canvas defaults to `{{last}}, {{first}}`)
- `SIS Login ID` as the second column and contains the student's netid **without @illlinois.edu**
- `Section` as the third column with no data
- All remaining columns as grade columns

Canvas also (optionally) accepts a second header column in Row #2 with the `Student` value set to `    Points Possible` (four spaces preceding the string).  All other identification columns are blank and the grade columns contain the maximum points for an assignment.  Canvas does accept scores over the maximum value (basically becomes extra credit) and also accepts `0` maximum points for an extra credit assessment.  Here's a minimal CSV that Canvas@Illinois accepts:

![image](https://user-images.githubusercontent.com/7505610/132257591-ac22d6ec-3375-46d5-bd19-48eaf1dad62b.png)

Canvas (at least at Illinois) does not allow for any internal scaling -- the points are summed to create the category and course grade.  It may not make sense to have `score_for_canvas.csv` given this "feature" of Canvas?

**Comment by mwest1066** [comment]
> I can confirm confirm @jonatanschroeder's tests with Illinois' Canvas. Specifically, a minimally functional CSV file has the following:

Awesome info, thanks!

> Canvas (at least at Illinois) does not allow for any internal scaling -- the points are summed to create the category and course grade. It may not make sense to have `score_for_canvas.csv` given this "feature" of Canvas?

Oh wow, this is "interesting".

**Comment by mwest1066** [comment]
It turns out that we can't implement this in way that works for multiple universities because their Canvas setups don't use consistent identification schemes for students. Instead, we will support this via grade export direct to Canvas with LTI 1.3, which will be available for beta testing starting in Fall 2024.
