### ISSUE TITLE
matplotlib error while starting up tests

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4586]
I'm running tests from the docker instance on my machine (KDE Neon, Ubuntu 20.04 base)

```
# start container 
docker run -it --rm -p 3000:3000 -v ~/git/PrairieLearn/:/PrairieLearn --name pl prairielearn/prairielearn

# enter the container (from a different terminal)
docker exec -it pl bash

# run the tests
cd PrairieLearn/
npm test
```

I will get the following error: 
```
bash-4.2# npm test
> PrairieLearn@3.2.0 test
> make test
nyc --reporter=lcov mocha tests/index.js
  database
    ✔ should match the database described in /database (713ms)
    ✔ should not contain "ON DELETE CASCADE" foreign keys from soft-delete to hard-delete tables (621ms)
  Administrator pages
    1. view administrator overview page
      ✔ should load successfully (225ms)
      ✔ should parse (61ms)
      ✔ should contain QA 101
error: Unexpected STDERR data: Matplotlib created a temporary config/cache directory at /tmp/matplotlib-inyn61_c because the default path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
 {"childIsNull":false,"callbackIsNull":true,"timeoutIDIsNull":true,"outputStdout":"","outputStderr":"","outputBoth":"","outputData":"","stack":"Error\n    at PythonCaller._errorData (/PrairieLearn/lib/code-caller.js:87:4587)\n    at PythonCaller._logError (/PrairieLearn/lib/code-caller.js:87:5113)\n    at PythonCaller._handleStderrData (/PrairieLearn/lib/code-caller.js:86:1534)\n    at Socket.emit (events.js:375:28)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:261:11)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","lastCallData":null}
  AdministratorQuery page
    ✔ visit queries page (81ms)
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
```

@echuber2 suggested this hack to make it happy: 
```
# hack to fix the matplotlib error
mkdir -p /root/.config/matplotlib
chmod a+rx /root /root/.config
chmod -R a+rwx /root/.config/matplotlib
```

it prevents the errors from happening during start up, but any tests which use matplotlib will still fail. 

Other things tried: running docker as root, and running the docker container with `-v /var/run/docker.sock:/var/run/docker.sock` don't fix the problem.

**Comment by mwest1066** [comment]
Rather than running `npm test`, can you instead try running `make test`?

I think this error might be caused by a hideous misfeature in npm v7:

> The user, group, uid, gid, and unsafe-perms configurations are no longer relevant. When npm is run as root, scripts are always run with the effective uid and gid of the working directory owner.

See https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

@jonatanschroeder mainly fixed this in #3818, but it looks like we still have a leftover `npm test` in `docker/test_js.sh` which is causing your problem.

**Comment by SethPoulsen** [comment]
Seems to fix the issue, no more matplotlib errors. 

I do get a couple other small errors later on if running the full test suite, but seems unrelated.

**Comment by mwest1066** [comment]
> Seems to fix the issue, no more matplotlib errors.
> 
> I do get a couple other small errors later on if running the full test suite, but seems unrelated.

Thanks!
