### ISSUE TITLE
pl-order-blocks/ranking grading algorithm and feedback

### ISSUE THREAD

**Issue by jeffgerickson** [PrairieLearn/PrairieLearn#4652]
The `ranking` grading algorithm for `pl-order-blocks` questions removes submitted items that should be excluded, and then counts the number of indices i such that either

- i=1 and ranking(i)==1, or
- i>1 and (ranking(i)==ranking(i-1) or ranking(i)==ranking(i-1)+1)

and divides by the correct number of items.  This grading algorithm is rather opaque, especially because there is currently no support for feedback along with the grade.

I'd like to suggest three alternatives; I can split these into separate issues if necessary.

### Non-consecutive ranks

This requires the least change from the current algorithm. The grading algorithm removes submitted items that should be excluded, and then counts the number of indices i where either 

- i=1 and ranking(i) is the smallest ranking in every correct solution
- i>1 and ranking(i) ≥ ranking(i-1)

and divides by the correct number of items.  The only difference is that rankings in the question do not have to be consecutive. 

There should be a corresponding `feedback` option that shows which items are out of order.

### Longest correct prefix

The grade is the length of the longest correctly ordered prefix of the correct items;.  This should be used with `feedback="first-wrong"`, which is currently not supported.  (I'm starting from the assumption that all grades should include feedback, that is consistent with the grading algorithm.)

### Longest non-decreasing subsequence

The grade is the length of the longest non-decreasing subsequence of the submitted rankings divided by the number of items.  As a graded solution, the student sees their submitted list, with items in the longest non-decreasing subsequence shaded green, and other items shaded red.  ("_Items in red should be ranked either above some earlier item, or below some later item._")  Rankings supplied in the question do not need to be consecutive.  I'd recommend requiring **all** items to be marked `correct="true"`; otherwise, there should be an additional penalty for including incorrect items.

I would use this grading method in this question:
https://www.prairielearn.org/pl/course_instance/128710/instructor/question/9063329/preview

**Comment by SethPoulsen** [comment]
These all seem like sensible grading methods to me. Some other questions we should probably ask as well like--how transparent should we be to students about which grading method we are using? should the help-text we show for students tell them which grading method is being used to assign them partial credit? I would think probably yes.

I agree having a default feedback that corresponds to each grading mode seems a good idea.

**Comment by SethPoulsen** [comment]
I'm going to tag some other people here who I know are using the element so we can make sure we implement something that works well for everyone: @Frozemint @jonatanschroeder @cheeren @ygertner @jasonxia17 

Please tag in others who you think might have opinions on this as well. 
What do you guys think about the proposed grading algorithms? What should be the default? Are there others that you guys think would make sense?

**Comment by jasonxia17** [comment]
Longest non-decreasing subsequence makes the most sense to me as a default. It's directly rewarding points for the number of items which are in the correct order, and it gives the student more actionable feedback compared to the other grading methods (e.g. students are more likely to be able to correct all of their mistakes on the second attempt instead of needing additional iterations of feedback).

**Comment by Frozemint** [comment]
I am also drawn towards the simpler grading algorithms, as they will also be easier to explain and for students to understand. With what I've heard from students, the last thing I want is to make online school any more complicated or frustrating.

Maybe we should also consider one more criteria for grading algorithms: the requirement that they are more forgiving (or as forgiving as possible) from a student's perspective? As in, if an answer is "approximately correct but only slightly out of order", then the algorithm should award "approximately full credits". 

In terms of feedback, the problem of telling the student what tiles are out of place or shouldn't be placed in the first place, I am reminded of a puzzle game: https://en.wikipedia.org/wiki/Mastermind_(board_game), where we have a correct ordered sequence of colours arranged by the dealer, and the player must deduce the correct colours and the ordering. When the player makes a guess, the dealer provides feedback to the player by indicating the number of misplaced colour blocks and colours that do not belong. Perhaps that could be of some inspiration for how to provide feedback?

**Comment by jeffgerickson** [comment]
@Frozemint  As much as I love Mastermind (even though my 11-year-old trounces me every time), I can't imagine using `grading=mastermind`.  I worry that students would spend too much time trying to solve the grading puzzle, instead of working on the actual problem being graded.

I agree with "forgiving" (grade ≈ distance to correct answer), but I also want "transparent"!

**Comment by SethPoulsen** [comment]
So to summarise: it seems it would be good to have the instructor be able to select different partial credit schemes, with corresponding feedback mechanisms. The details of the partial credit scheme should also be shown in the help text of the element so that there is transparency and the student knows what they are getting themselves in to. 

To put it out there, this is not something I have time to do at the moment, so if someone else wants to, you are welcome to. I should be able to find time to review code if someone else writes it, especially if it includes a good test suite.

**Comment by SethPoulsen** [comment]
We have added a few new grading and feedback mechanisms since this was opened, I am going to consider it resolved for now, people can feel welcome to open a new issue if there is a particular feedback mechanism they want to talk about.
