### ISSUE TITLE
pl-order-blocks not rendering special HTML characters correctly

### ISSUE THREAD

**Issue by nealterrell** [PrairieLearn/PrairieLearn#4665]
Blocks containing HTML special characters (&lt;, &gt;, &quot;, &amp;, etc.) are being rendered with HTML encoding, escaping those characters as literal `&lt;` etc. This was not an issue in the past; a block like this:

```
<pl-answer>if number < 12 or number > 24:</pl-answer>
```

used to look like this (running on the Berkeley PL instance):

![image](https://user-images.githubusercontent.com/10083341/129657004-17e59074-cc03-4788-9c96-8576278424ba.png)

The same question running on a local up-to-date PL:

![image](https://user-images.githubusercontent.com/10083341/129657044-36ac9a0a-df33-4b17-b601-a8e7f2d3b0da.png)

The `user_code.py` that is generated for external grading also sees the characters written with their HTML encoding, which is obviously bad.

The `pl-answer` above is actually malformed HTML, but the issue persists in all ways even when rewritten with an escaped inner HTML on the answer:

```
<pl-answer>if number &lt; 12 or number &gt; 24:</pl-answer>
```

@jonatanschroeder identified a quick fix for the rendering in the browser:

![image](https://user-images.githubusercontent.com/10083341/129657176-8c99f433-035c-4834-a7cb-8bad58d23e7d.png)

This does fix the rendering, but the user_code.py is not fixed.

**Comment by SethPoulsen** [comment]
@Frozemint I haven't ever used the element with the external grader. Do you know where in the element code that the input is prepared to be sent to `user_code.py` ?
