### ISSUE TITLE
Previewer users are missing Questions item in navbar

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4670]
This bug applies after #3020 is merged.

Steps to reproduce:

1. In local dev, as admin user, change effective course role to "Previewer".
2. Navigate to course instance Assessments page.
3. Observe that the "Questions" navbar item is not visible, but it should be.
4. Click on the course number in the navbar.
5. Observe that the "Questions" tab is visible and accessible, which is correct.

The same problem occurs for users with a course instance role but course role = None.

**Comment by jonatanschroeder** [comment]
I cannot reproduce this error anymore, in either master or in #10277. I'm tagging it as resolved.

**Comment by mwest1066** [comment]
Thanks!
