### ISSUE TITLE
Course "Viewer" with no course instance access cannot view Questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4673]
Reported by Eric Larson.

This occurred in XC 101 where users default to have `course_role = Viewer` and no course instance access.

![pl_error_xc101_demo_access](https://user-images.githubusercontent.com/875833/129983864-5cabdad7-6ed0-4835-8700-e0a496d29e49.jpg)

**Comment by firasm** [comment]
Ha! I was just about to report this as well - two people on my team had this issue, but it sounds like I can fix the issue with access permissions.

Thanks for the fast fix!
