### ISSUE TITLE
Need to make courses/CIs always be a (possibly empty) list

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4676]
After #3020 is merged, we should apply a similar change to #4674

**Comment by jonatanschroeder** [comment]
I believe this is already the case, only it's in `locals.authz_data.course_instances` instead of `locals.course_instances`. Check #4683.

**Comment by jonatanschroeder** [comment]
Is this still a problem?

**Comment by nwalters512** [comment]
I'm not even really sure what this is referring to, and none of the sprocs listed in #4674 exist anymore. I'm going to close this.
