### ISSUE TITLE
external grader question results not shown without refresh

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#4694]
Steps to reproduce:

1. Create assessment that includes an externally graded question.
2. Submit answer to said question as student or instructor-viewing-as-student.

The result will simply be "Graded" but no additional information is shown. Upon refreshing, the expected results appear.

@jonatanschroeder

**Comment by jonatanschroeder** [comment]
The issue is that `pages/partials/questionScorePanel.ejs` uses the value of `authz_result.authorized_edit` which is available when the page is loaded, but not available in the partials itself when the web socket obtains the new version of the panel when grading finishes. Investigating further.
