### ISSUE TITLE
Remove question_tags.number and sort by tags.number instead

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#473]

**Comment by mwest1066** [comment]
@nwalters512 looks like we had this long-standing item to just drop `question_tags.number`, which I still agree with. I can’t see any reason to retain `question_tags.number`, so maybe the sync rewrite is a good time to drop it?

**Comment by nwalters512** [comment]
@mwest1066 sounds good, I'll add that as part of the syncing work!
