### ISSUE TITLE
Create a framework for canvas drawing in questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#475]
Many courses need questions that involve drawing on a canvas within a question. For example, sketching curves in calculus, drawing free body diagrams in mechanics, and drawing trees in CS data structures.

To help support this, we need:

1. A standard JavaScript library to programmatically render drawings and support user editing. A candidate is [Fabric.js](http://fabricjs.com).

2. Figure out how to render standard components needed for lots of questions. For example, coordinate systems (axes with labels), component labels (preferably supporting LaTeX), and course-specific components (e.g., beams, hinges, forces, distributed loads).

Two examples of this (both of which have problems) have been used in TAM 212 and TAM 251. Ask @mwest1066 for examples of these and more details.

**Comment by trombonekenny** [comment]
@mfsilva22 seems like she's working on a version of this?

**Comment by mwest1066** [comment]
Implemented by @mfsilva22 and @nicknytko with the `pl-drawing` element.
