### ISSUE TITLE
Unable to modify student data in assessment view

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#4784]
On the assessment view page, I'm no longer able to click into the table cell and modify a value. 

Double clicking on either the points or percentage bar no longer opens a form pop-up.

<img width="1549" alt="assessment-data" src="https://user-images.githubusercontent.com/833642/131772129-5a34d301-0ad9-4963-8cbc-5800a1b51b8f.png">

**Comment by mwest1066** [comment]
It looks like you have only "Viewer" access to student data, which does not allow editing. Click on the course name in the top menu bar (e.g., "CS 101") then click on the "Staff" tab. In the "Student data access" column, change your access to "Editor" for the relevant course instance.

**Comment by coatless** [comment]
@mwest1066 thanks! That was it. Sorry for the noise.

**Comment by mwest1066** [comment]
> @mwest1066 thanks! That was it. Sorry for the noise.

No worries! Sorry for the confusion with the new permissions model.
