### ISSUE TITLE
Server jobs does not correctly echo "git clone" progress

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#479]
When `git clone` is run via the web interface, the progress updates are not captured and echoed to the remote client. The "checking out" progress is echoed, but without newlines or overwrite so it looks funny.

This is presumably caused by the fact that git is printing TTY control characters to erase lines and things like that. Perhaps we could translate these to newlines on the server?

**Comment by trombonekenny** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Colors-in-Git

Git automatically colors most of its output, but there’s a master switch if you don’t like this behavior. To turn off all Git’s colored terminal output, do this:

$ git config --global color.ui false

The default setting is auto, which colors output when it’s going straight to a terminal, but omits the color-control codes when the output is redirected to a pipe or a file.

**Comment by nwalters512** [comment]
I'm not able to reproduce this with the latest version of PL. When adding and syncing a repo for the first time, I now see all the output from `git clone`:

<img width="1036" alt="Screenshot 2022-11-02 at 17 04 38" src="https://user-images.githubusercontent.com/1476544/199624722-c9757d9b-db13-45f9-8226-d96f7bbc777b.png">
