### ISSUE TITLE
Configuring data["params"] from infoAssessment.json

### ISSUE THREAD

**Issue by jasonxia17** [PrairieLearn/PrairieLearn#4799]
Let's say I had a question for students to practice multiplying two `n x n` matrices, and `data["params"]["matrix_size"]` determines the size of the two matrices generated. I want to give this question in HW1 and HW2; in HW1 the matrix size should be `2 x 2`, and in HW2 the matrix size should be `3 x 3`. It would be cool if there was a way to do this:

```
HW1's infoAssessment.json:

{
    "id": "matrix_multiplication",
    "points": 1,
    "params": {"matrix_size": 2}
}

--------------------------------------------------------------

HW2's infoAssessment.json:

{
    "id": "matrix_multiplication",
    "points": 1,
    "params": {"matrix_size": 3}
}
```

**Comment by mwest1066** [comment]
I think you want #3848?

**Comment by mwest1066** [comment]
Closing in favor of #3848
