### ISSUE TITLE
New splash page for CBTF needed

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#480]
The homepage on exam mode systems was set to https://prairielearn.engr.illinois.edu, which linked into the individual courses. With PL being upgraded, we'll still need that browser homepage launch-spot.

Do PL course (or semester instances of courses) have direct URLs? Or will they click into PL, and then choose their class from the dropdown on the menu bar?

Would it make more sense to tie the splash page into the reports instead of PL?

**Comment by mwest1066** [comment]
Resolved in the new CBTF setup.
