### ISSUE TITLE
Accessing raw_submitted_answers

### ISSUE THREAD

**Issue by jheller12** [PrairieLearn/PrairieLearn#4804]
It would be useful to access all of a student's raw_submitted_answers for an assessment (say in case of input deemed invalid).

**Comment by eliotwrobson** [comment]
@nwalters512 isn't this already possible using the raw_submitted_answers entry in the data dictionary?

**Comment by jonatanschroeder** [comment]
I believe this is for assessment downloads, which don't include this column.
