### ISSUE TITLE
Having to press two tabs to get to the next pl-string-input

### ISSUE THREAD

**Issue by tom11my** [PrairieLearn/PrairieLearn#4816]
when I’m in a pl-string-input  element and I’ve just input a string, I have to press tab twice to get the next element. It’s a small thing but I think it would improve user experience to only have to press tab once.

**Comment by cbm755** [comment]
Is the first tab just getting you to the question mark button `[?]`?  B/c that's probably the way it needs to be for accessibility reasons.

When authoring questions, I sometimes remove the `[?]` question box from repeated elements for this reason.  Maybe a way to do that globally and automatically would be useful, like "show-question-button-only-for-first-input-of-any-type".

**Comment by nwalters512** [comment]
@cbm755 is correct, the first tab goes to the question button that provides information about that input. Being able to focus the info button is important for accessibility.

> Maybe a way to do that globally and automatically would be useful, like "show-question-button-only-for-first-input-of-any-type".

Doing this globally would add quite a lot of complexity; we currently work hard to ensure that elements don't need to be aren't aware of the presence or order of other elements on the page. I think `show-help-text="false"` will remain the preferred way to hide help text if instructors deem that that's the desired behavior.
