### ISSUE TITLE
pl-matching docs

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4822]
Documentation for pl-matching includes an image that doesn't match the example:
![Docs](https://user-images.githubusercontent.com/1004907/133636805-e7621848-5487-4d49-95fd-aaa6634af649.png)

Reported by @mfsilva22 
@nealterrell if you have time? You mentioned a patch in pl-matching, can you add this?

**Comment by nealterrell** [comment]
Yeah I can get it later today.
