### ISSUE TITLE
Questions page: new optional columns

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4825]
Since it's now possible to have new columns on the questions page that are not shown by default, here are some columns that would help me:

* grading method (Internal, External, Manual);
* elements in use (this is probably going to be tricky, since it may require some parsing, but just throwing it out as an option if anyone has a clever idea);
* external grader image.

**Comment by firasm** [comment]
- Question Number would be useful for me (so I can download the page and construct URLs: https://ca.prairielearn.com/pl/course_instance/2327/instructor/question/230794/preview)

**Comment by jonatanschroeder** [comment]
> - Question Number would be useful for me (so I can download the info on the page and construct URLs: https://ca.prairielearn.com/pl/course_instance/2327/instructor/question/230794/preview)

Can't you get that from the href in the first column?

**Comment by firasm** [comment]
Ah, you're right - indeed I can! Okay maybe we don't need Question number.

I have some more ideas here in #3368, but those are just additional tags that we'd like to filter by - not sure if that would be possible under the current scheme.
