### ISSUE TITLE
Shibboleth fails from IllinoisNet

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#483]
```
opensaml::FatalProfileException

The system encountered an error at Mon Jan 9 22:24:50 2017

To report this problem, please contact the site administrator at root@localhost.

Please include the following message in any email:

opensaml::FatalProfileException at (https://prairielearn.engr.illinois.edu/Shibboleth.sso/SAML2/POST)

Your client's current address (130.126.255.105) differs from the one used when you authenticated to your identity provider. To correct this problem, you may need to bypass a proxy server. Please contact your local support staff or help desk for assistance.
```

I think this happens on IllinoisNet because they use a 10.x.x.x IP to talk to the authentication servers on campus, and then the NAT'd 130.126.255.x IP to talk to the AWS IP. Dave is checking with Tech Services. I have a feeling they'll give us a different shibboleth configuration for servers outside UIUC IP space. (However they fixed this for uofi.box.com)

**Comment by mwest1066** [comment]
Fixed. The fix was to set `checkAddress="false" consistentAddress="true"` in `shibboleth2.xml`.
