### ISSUE TITLE
pl-matching counters don't match the options in answer panel

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4831]
When submitting a pl-matching answer using counter-type "upper-alpha", the answer panel shows incorrect option counters with correct option text. In essence, the text of the answer shows the correct option, but the counter doesn't match the test (in my case the answer always showed A/B/C/D/E regardless of the correct answer). The same thing happens with decimal or lower-alpha, but full-text works fine.
@nealterrell

**Comment by nealterrell** [comment]
Got it, thanks.
