### ISSUE TITLE
LTI-based item data exports broken (null)

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#4832]
The data exports for some LTI items may return "null" data fields. It seems this is because of how the SQL is written; LTI-managed sessions don't have the same name or user ID fields as institution-managed sessions.

This issue was noted a while back on the Slack. I'm making an issue so it doesn't get lost, but I don't have the example at hand right now. You can replicate it by trying to export CSV for data on an LTI-based item with existing attempts.

**Comment by echuber2** [comment]
@tdy this is on my todo list but I'll probably ask for your help reviewing the postgres (if I can manage to make a PR)

**Comment by trombonekenny** [comment]
Can you be more specific on which query isn't working how you expect? That would help us investigate.

**Comment by echuber2** [comment]
I wish I'd taken better notes when this came up the first time. In the fall, we saw an issue where some exports had "null" [sic] in a column instead of any kind of useful username. However, I can't find an example that still has that specific symptom, so it seems the situation has changed a little bit. I think the relevant part is https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql

Now, there are still a few issues for LTI item exports:

- `scores.csv` has an unfriendly on-demand LTI identifier string for UID and blank for UIN. No human-readable names.
- `scores_by_username.csv` has the hex prefix of the LTI identifier for "username" and nothing human-readable.
- `best_files.zip` has directories named by the LTI identifiers, which include illegal characters for some filesystems (primarily, the identifiers include `:` (colon) which will mess up NTFS on Windows).
- similar issues for some of the other exports

At this point, I guess I'd mainly suggest we ensure that each export has at least one human-readable column with a real name or something to help match things up, and the directory and file names in the zipped exports should be sanitized.

**Comment by echuber2** [comment]
Closing this for now as I can't reproduce the symptoms currently. Will reopen if it starts happening again.
