### ISSUE TITLE
Groups page renders page from POST instead of redirecting

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4857]
Most pages, after a POST is completed, will redirect to a GET request. This makes sense since, if the page is reloaded for some reason (refresh, browser closes/reopens, etc.), you want the current view of the page, you don't want to re-take the POST action. This is not done in the instructor assessment groups page. In there the POST actions actually render the same page again from the POST itself. It seems this is done to retain any error messages to be shown on the page in case of errors, but that can be achieved through other means (e.g., query strings).

**Comment by nwalters512** [comment]
This was fixed in #7905.
