### ISSUE TITLE
GIFT format for importing questions

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#489]
Moodle has a markup language for question that's just text. https://docs.moodle.org/32/en/GIFT_format

> GIFT format allows someone to use a text editor to write multiple-choice, true-false, short answer, matching missing word and numerical questions in a simple format that can be imported. The GIFT format is also an export file format available in Question bank. The format has been developed within the Moodle Community but other software may support it to a greater or lesser degree. 

That could be useful as quick way to prototype quizzes - either as a assessment type of its own (that doesn't include the normal questions/ hierarchy), or to import into questions somehow.

If anything, it dramatically lowers the bar for question development, at least for the simple formats it supports: multiple choice, MC with multiple right answers, true-false, short answer, matching, missing word, numerical questions, essay, description.

http://buypct.com/gift_reference.pdf is a quick, handy reference/primer.

**Comment by lotrfan** [comment]
225 uses/used a custom markdown format... something like

``` markdown
---
{
    "uuid": "0ae475f1-e4ca-4c8a-b759-ca2e4eb37d1f",
    "title": "Advantages of fossil fuels (checkbox)",
    "topic": "Energy",
    "tags": ["MC"],
    "type": "Checkbox",
    "options": {
        "numberAnswers": 5,
        "minCorrectAnswers": 1,
        "maxCorrectAnswers": 3
    }
}
---

Which of the following are advantages of fossil fuels relative to renewable energy sources? Select all that apply.

![](power-station.jpg)

- @@ Cheap
- @@ High energy density
- @@ Provide energy on demand
- Non-polluting
- Low energy density
- Low production of carbon dioxide
- High production of carbon dioxide
- Secure
- Sustainable
- Low energy return
```

(for https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/fossilFuelsCheckbox/info.json)

This is processed to create PL's `info.json`; the script has support for converting code blocks to images (via pygments) and rendering latex (used mainly for tikz diagrams).

A full exam is created by using that and some other scripts, tied together with some `make` magic.

**Comment by mwest1066** [comment]
Want to contribute this script? You could put it in `PrairieLearn/tools` and add something about to `doc/` and `README.md`.

**Comment by nwalters512** [comment]
@trombonekenny AFAICT, this predates V3 questions. Do you still think it's worth it to try to implement this?

**Comment by nwalters512** [comment]
I'm very hesitant to build/support a DSL for elements that we can embed in Markdown. That'll be a huge maintenance burden and wouldn't play well with tools like Prettier. I'd much rather just use standard HTML, even in Markdown question files.

**Comment by mwest1066** [comment]
I don't think we should support this -- v3 questions and further improvements in that direction are much more likely to be useful.

**Comment by trombonekenny** [comment]
GIFT as a format could be very helpful, especially for exports from things like Canvas into PL with existing collections of, say, MC questions. I wouldn't necessarily tie this into the markdown discussion, since that's entirely different. I foresee something like the GIFT functionality as a one-time importer that makes questions based on templates and data supplied by the GIFT txt.

**Comment by trombonekenny** [comment]
This could be done by something in `tools` like the other question converters, though.

**Comment by nwalters512** [comment]
Yeah, I think starting this as an external tool is the way to go. If that proves to work well and be valuable, we can consider integrating it into PrairieLearn itself.

**Comment by trombonekenny** [comment]
Do we want to leave this open as a request for a converter? Or leave it closed (and findable later if we do resurrect something?)
