### ISSUE TITLE
For Craig: Confirm on exams before submit if not all questions are answered

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#49]

**Comment by kevinwang** [comment]
There is already this modal which appears when Finish is clicked:

![](http://f.kev.wang/i/1geOwo.png)

Do you want a second confirmation modal? Or perhaps some bold text in the existing modal indicating that there are unanswered questions?

**Comment by mwest1066** [comment]
Good question. I'm not sure. @zillesc seemed to think that "finish with unanswered questions" was a failure mode that we should worry about, but I now think that it's probably just a special case of students clicking "finish" when they really wanted to click "grade", and so this is best addressed within the context of #259.

I like the idea of adding text to the existing modal if there are unanswered questions. I'm actually not sure how to add text to the modals (at present they are all hard-coded in the HTML), so I'm happy to skip this if it's hard or messy to implement.

**Comment by mwest1066** [comment]
Thinking about this further, I like @kevinwang's suggestion of adding some bold text to the modal if there are unanswered questions when the student clicks "Finish". Maybe even bold text with [`text-danger`](http://getbootstrap.com/css/#helper-classes-colors), just to try and get through to chronically inattentive people?
