### ISSUE TITLE
Slow assessment_questions_calculate_stats()

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4915]
Running `assessment_questions_calculate_stats(125174104)` takes about 5 seconds. It can be reduced to 0.1 seconds by:

1. Save 2 seconds by removing the `users_is_instructor_in_course_instance()` call: https://github.com/PrairieLearn/PrairieLearn/blob/5b997eabb69a0b5707f6b0e2ab2d615069455756/sprocs/assessment_questions_calculate_stats.sql#L18
2. Save 1 second by removing the `LEFT JOIN groups LEFT JOIN group_users JOIN enrollments`: https://github.com/PrairieLearn/PrairieLearn/blob/5b997eabb69a0b5707f6b0e2ab2d615069455756/sprocs/assessment_questions_calculate_stats.sql#L13
3. Save 2 seconds by changing `(ai.user_id, ai.group_id) AS u_gr_id` to `coalesce(ai.user_id, ai.group_id) AS u_gr_id` in all three locations: https://github.com/PrairieLearn/PrairieLearn/blob/5b997eabb69a0b5707f6b0e2ab2d615069455756/sprocs/assessment_questions_calculate_stats.sql#L23

We can't apply the above changes immediately because they will change behavior, but we should try and restructure things so that we can do this.

**Comment by nwalters512** [comment]
@mwest1066 I'm taking a look at this now - can you elaborate on what this means?

> We can't apply the above changes immediately because they will change behavior, but we should try and restructure things so that we can do this.

Does this mean that the change in behavior is ultimately desirable/tolerable and that we should make these changes, or something else?

**Comment by mwest1066** [comment]
> Does this mean that the change in behavior is ultimately desirable/tolerable and that we should make these changes, or something else?

The behavior changes are too severe to be tolerable. But I think we could re-engineer things (with some more work) so that we get speed improvements with only minor behavior changes. The changes I made above were very simple, just to test out the idea that a huge speedup is possible. Taking them in turn:

1. We do want to only include students in statistics. However, calling a sproc once per row (like we are doing with `users_is_instructor_in_course_instance`) is way too expensive. Thinking in terms of loops, this means that for every user we are calling `users_is_instructor_in_course_instance()`, which then goes off and does a bunch of SELECTs over other tables. SQL is generally more efficient when we process data whole-table-at-a-time, if that makes sense? The ways I can think of t fix this are:

    1. Inline the query from `users_is_instructor_in_course_instance()` into the main `assessment_questions_calculate_stats()` query. This might require some rearrangement to first do a WITH-query to figure out which assessment instances are associated with students (non-instructors).
    2. Similar to (1), but write a sproc like `course_instances_select_students(course_instance_id)` that returns a table of all students (non-instructors) in a given course instance. Then we could do a single whole-table JOIN on this in `assessment_questions_calculate_stats()` to select out who is a student.
    3. Add a new column to `assessment_instances` to record whether the user is a student (non-instructor) at the time that the AI is created. Then we can very cheaply filter out instructors in `assessment_questions_calculate_stats()`. I think this is my preferred option, because it will give the fastest execution and also records history "as it happened". We should probably display this on the `instructorsAssessmentInstance` page in the top card, just for visibility/debugging. I guess for group assessment_instances we should just check whether the creating user is an instructor.

2. I think that if we use option (3) above (store `is_instructor` in `assessment_instances`) then we won't need to all this JOINing on groups/group_users anyway, because it's only being done to test whether the user is an instructor.

3. Because we can have assessment instances owned either by groups or by single users, it was my "clever" idea to use the tuple `(ai.user_id, ai.group_id) AS u_gr_id` as the unique identifier (exactly one of `user_id` or `group_id` will be NULL). However, it seems that using tuples is really slow in postgres. My hack above was to `coalesce()` them into a single integer, but this is a bit dangerous because we can have collisions between the IDs for users and groups. Some ideas for this:

    1. Change `user_id` (and/or `group_id`) to a UUID rather than a BIGINT, which means we can assume we'll never have collisions. This is probably too invasive to actually do it, but I'm always tempted by the idea of using UUIDs as primary keys to avoid all issues with collisions. There are lots of blog posts describing this, with discussions about the speed tradeoffs.
    2. The column `assessments.group_work` tells us whether this assessment is intended for groups or single users. In general, a group-work assessment will only have associated `assessment_instances` with non-NULL `group_id` (and hence `user_id = NULL`), whereas a non-group-work assessment will be the reverse. However, if an instructor flips the `assessments.group_work` setting after some assessment instances have already been created then we can end up with a mixture of assessment instances owned by groups or individuals. I've been trying to write all queries to support this use case, because we do see people doing this in practice. For the particular query under discussion (`assessment_questions_calculate_stats`) we could just ignore all assessment instances of the "wrong" type (e.g., individual assessment instances for a group-work assessment). However, I'd prefer to use a generic solution because there are other pages where we really do want to use all assessment instances, even if they are of the wrong type.
    3. Evil (or "clever"?) hack: we could use `coalesce(user_id, -group_id)` (note the negative sign) to get a unique identifier that avoids collisions. I assume that this will be just as fast as the simple (but collision-prone) fix that I tried. Of course this will never scale if we add a third type of assessment (individual, group-work, something else?), but YAGNI. I think this is my preferred option.

I think that there are lots of other page queries that are suffering from the same slowdowns as this statistics query. The problems came about because of group work (which introduced `assessment_instances.group_id`) and the new permissions system (which introduced `users_is_instructor_in_course_instance()`). For example, I think this is also causing the very slow rendering of the `instructorAssessments` page (I can't find an Issue filed for this). Also see #5092 as related.
