### ISSUE TITLE
Start out pl-order-blocks in alphabetical order

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4920]
Add an option to alphabetized lines in shuffle-options (motivated by https://dl.acm.org/doi/pdf/10.1145/3017680.3017704). It makes the lines more easily findable for students but likely doesn't give anything away compared to pure shuffling.

Originally suggested by @nathanielweinman in https://github.com/PrairieLearn/PrairieLearn/issues/3476

**Comment by ataraxie** [comment]
Is this related to the `source-blocks-order` attribute? From the [docs](https://prairielearn.readthedocs.io/en/latest/elements/#pl-order-blocks-element):

> The order of the blocks in the source area. One of the following: `random` or `ordered`.

Is the idea to have a new value `alphabetized` for this attribute?
