### ISSUE TITLE
Clarify docs on needing to give access to both courseInstance and assessment

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#494]
Reported by @mfsilva22

**Comment by mwest1066** [comment]
See https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/accessControl.md#two-level-of-access-control-for-assessments for details.

**Comment by mfsilva22** [comment]
I guess I am still not doing this correctly. In "incoCourseInstance.json" I have
	"allowAccess": [
	    {
            "uids": ["xxx@illinois.edu","yyy@illinois.edu" ],
	    "startDate": "2017-01-11T00:00:01", 
            "endDate": "2017-05-20T23:59:59"
        },
		{
		"startDate": "2017-01-11T00:00:01", 
		"endDate": "2017-05-20T23:59:59"
		}	
	]
For HW1, the infoAssessments.json has:
   "allowAccess": [
        {
            "role": "TA",
            "endDate": "2017-05-20T23:59:59"
        },
        {
            "uids": ["xxx@illinois.edu","yyy@illinois.edu" ],
            "endDate": "2017-05-20T23:59:59"
        },
{..}
]
However students will netid xxx and yyy are still not able to see the assignment (not authorized).
What am I missing?

**Comment by mfsilva22** [comment]
Something still seems to not work for me. When I go to the gradebook, I see that student XX already started working on HW1. So if I try to change the effective role = student and effective user = XXX@illinois.edu, then I can see HW1, but HW 2 still gives me the same error 

"Error processing request
Not authorized
Error ID: MKE2BZMNPZX7 "

The other students (my CAs listed in infoAssessments" and "infoCourseInstance") have not started working on the assignments. So when I try to change the effective user to be any of them, I get the same error.

Do students need to start an assignment first in order for me to get access to the assessment?

**Comment by mwest1066** [comment]
Ok, I think I've really fixed it this time :-)
