### ISSUE TITLE
Enforce naming conventions with ESLint camelcase rule

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#4964]
ESLint has a [`camelcase` rule](https://eslint.org/docs/rules/camelcase) that we should use to enforce our coding standards. We'll likely have to mess with the configuration to account for the fact that we make extensive use of `snake_case` when interacting with the database - we may want to limit the rule to only check function/variable names.

**Comment by SethPoulsen** [comment]
Is the python linter already enforcing the standards for python variables or do we need to reconfigure that too?

**Comment by nwalters512** [comment]
Good question - it looks like we'd need a flake8 plugin to do that. I created an issue to track that work too: https://github.com/PrairieLearn/PrairieLearn/issues/4965

**Comment by nwalters512** [comment]
Recent developments in our naming conventions mean that we will in fact name some variables with `snake_case`.
