### ISSUE TITLE
Add related resources information to questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5]
Add a field for "related resources" in the `info.json` for each question and display it somewhere on the question page (presumably in the sidebar).

Eventually this should augmented by recommendation-engine-generated resources and click-throughs should be tracked.

**Comment by nwalters512** [comment]
@mwest1066 is this something we still need? I think placing this information inline in questions is the way to go?

**Comment by eliotwrobson** [comment]
@nwalters512 agreed putting information in line is the way to go. With the pl-template element, people can easily re-use HTML containing this information, so we don't even need a new feature to facilitate less duplication. I think this should be closed @mwest1066

**Comment by mwest1066** [comment]
Yep, I agree that inline in the question is better.
