### ISSUE TITLE
Add course_instance_id to all routes to enable more flexible forwarding

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5001]
At the moment our load balancers can forward "core" routes like question pages based on the `course_instance_id`. However, static assets, workspaces, etc, all use routes without the `course_instance_id` in them, making it impossible to fully forward specific course instances to different backend servers.

To fix this, we can make sure that we embed the `course_instance_id` into all routes where we have one.

**Comment by mwest1066** [comment]
The most important (and easiest) routes to fix are the one for static assets (especially `node_modules` assets).

**Comment by nwalters512** [comment]
As of #7709, assets are now served from a configurable prefix, which makes it possible for us to have canary servers work correctly with static assets.
