### ISSUE TITLE
installingLocal docs may need rename, note about yarn bootstrap on entrypoint scripts

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#5030]
Looking at the instructions for how to run PL in Docker with the local development branch checked out and mounted:

https://prairielearn.readthedocs.io/en/latest/installingLocal/

Since it's no longer really recommended to install all the dependencies (database server, etc.) and run entirely local, but rather to use Docker and run with the latest files mounted, maybe "installing with local source code" is less accurate than "running in Docker with latest development code"? I'm not sure how to phrase it best.

[Edited:]
It might be worth noting that when special entrypoint scripts are in use, e.g. `/bin/bash -c '/PrairieLearn/tools/start_workspace_tmux.sh'`, then users may need to update this to `/bin/bash -c 'yarn && /PrairieLearn/tools/start_workspace_tmux.sh'`, or even to re-chown generated files to their local user account (1000, whatever). I think I could build some of that into `start_workspace_tmux.sh` itself at least.

**Comment by nwalters512** [comment]
The tmux script has been merged; @echuber2 is there anything you want to update in the docs about that?

I opened #7285 to resolve the main issue here.

**Comment by echuber2** [comment]
I'll need to refresh my memory about https://github.com/PrairieLearn/PrairieLearn/pull/5031 first. I had tested those tweaks back at the time but then I switched to keeping `node_modules` in a Docker volume instead, so I ended up not needing all of the improvements myself.
