### ISSUE TITLE
partial_scores dictionary entries not being created for pl elements with answers-name

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#5032]
Example issue
I had the following code in `question.html`
```
<pl-integer-input answers-name="extra_elem1"></pl-integer-input>
<pl-integer-input answers-name="extra_elem2"></pl-integer-input>
```
and then this in `server.py`
```
def grade(data):
  extra_elem1 = data['submitted_answers']['extra_elem1']
  extra_elem2 = data['submitted_answers']['extra_elem2']

  elem_list = data['correct_answers']['elem_list']

  if extra_elem1 == extra_elem2:
    data['partial_scores']['extra_elem1']['score'] = 0
    data['partial_scores']['extra_elem2']['score'] = 0
    data['partial_scores']['extra_elem1']['feedback'] = 'Please enter two different elements'
    return data
```
which gave me a `KeyError: 'extra_elem1'`
To fix this, I added the following to my `def generate(data):` function
```
  data['correct_answers']['extra_elem1'] = elem1
  data['correct_answers']['extra_elem2'] = elem2
```
this got rid of the `KeyError`. 

Alternatively, I could get rid of the error by modifying `grade` and not modifying `generate`
```
def grade(data):
  extra_elem1 = data['submitted_answers']['extra_elem1']
  extra_elem2 = data['submitted_answers']['extra_elem2']

  elem_list = data['correct_answers']['elem_list']

  if extra_elem1 == extra_elem2:
    data['partial_scores']['extra_elem1'] = {'score': 0}
    data['partial_scores']['extra_elem2'] = {'score': 0}
    data['partial_scores']['extra_elem1']['feedback'] = 'Please enter two different elements'
    return data
```
Would be good for any pl-element with an `answers-name` field to automatically generate all `partial_scores` fields.

**Comment by eliotwrobson** [comment]
Going to go ahead and close this. Unfortunately, the `partial_scores` field is only modifyable during the `grade` stage (see https://prairielearn.readthedocs.io/en/latest/question/#question-serverpy), which doesn't get executed if there are any format errors found during parse. Getting around this limitation would require a pretty substantial rework of the way PL does grading.

Even for this particular case, without a correct answer set there's no grading that can be done aside from just marking the partial score as zero (different than ignoring grading entirely), and this might break some people's questions.
