### ISSUE TITLE
Warn when leaving question with unsaved answers during exams

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#506]
When a student tries to navigate away from a question page that has unsaved changes to an answer, we should pop up a dialog asking whether they are sure they want to leave.

To do this, we could use [`onbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) or [`onunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunload). We would then need to get the current submission from the question and compare it to the last saved submission to determine whether there are unsaved changes.

**Comment by trombonekenny** [comment]
Bump from feedback from Wade after CS400's first LTI Coursera final (students might be new to PL).

> The PL interface was not intuitive to several students in different ways: Selecting an answer and pressing "Next Question" does NOT save the answer nor give any warning that it was not saved (ex: a pop-up or warning, etc).  This caused confusion where students believed they had answered questions but it was not recorded.

**Comment by echuber2** [comment]
CS 445 online students also complained about this aspect being unintuitive. If someone is going back and forth and using "Save Only" a lot, they may forget to save after their last edit. This would strongly impact students who prefer to save along the way and grade all at once at the end.
