### ISSUE TITLE
error when trying to generate a question when the exam expires

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#5079]
When I was solving a timed exam with allowRealTimeGrading: false, I clicked to go to "next question" as the time expired, and got the following error:

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/12501485/140665716-093a3e8c-b63a-4d20-b908-c1ba71705b9a.png">

I was doing this in local development, using one of the assessments in the example course.

**Comment by jonatanschroeder** [comment]
Resolved by #9803.
