### ISSUE TITLE
Enable no-use-before-define ESLint rule

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#5095]
https://eslint.org/docs/rules/no-use-before-define is a very good rule that would have caught problems like that fixed by https://github.com/PrairieLearn/PrairieLearn/pull/5093 - we should enable it! Unfortunately, our code has a lot of non-compliant code at the moment, so this will require some refactoring.

**Comment by SethPoulsen** [comment]
I just tried running it and got 260 errors :upside_down_face:

**Comment by SethPoulsen** [comment]
The worst offenders are files related to the instructor file editor, they have far more than anywhere else in the codebase, so those are probably the only place that will require any serious thought/refactoring.

**Comment by SethPoulsen** [comment]
There are only 109 errors if its configured with `"functions": false` that could be a good first step if we want to do it incrementally.

**Comment by nwalters512** [comment]
Closing in favor of TypeScript tooling, which will catch these kinds of issues more reliably than ESLint.
