### ISSUE TITLE
pl-matching: allow options to be listed above/below statements

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5118]
For long statements/options the visual representation of the matching element looks weird. In these cases it would be good to have an argument to show the options above or below the statements instead of on the right side.

**Comment by ffund** [comment]
I could really use this, too. Here's an example of a pl-matching question that's not really usable in the side-by-side format, but would be great with the options below the statement:

![image](https://user-images.githubusercontent.com/2316553/157286667-70e77e78-4c73-4a32-a8de-22df142f0a45.png)
