### ISSUE TITLE
Win10 Docker documentation: Allow access to C: drive

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#513]
There's a step missing from https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/installing.md where Windows users need to configure Docker to let containers access the hard disk.

docker: Error response from daemon: C: drive is not shared. Please share it in Docker for Windows Settings.
See 'docker run --help'.

Maybe we can throw a quick screen grab in there?

**Comment by mwest1066** [comment]
For docker toolbox (needed on anything less than Win10Pro):

run Docker Quickstart Terminal
To find the IP use "docker-machine ip default" # will print 192.168.99.100
When doing path mapping, use format like /c/mfsilva.UIFO/Documents/xxx

**Comment by mwest1066** [comment]
For reference, this is the Windows docker issue that some people have hit: https://github.com/docker/docker/issues/27423

**Comment by mwest1066** [comment]
On docker toolbox for Windows, you need to add a new virtualbox shared folder:

add a new shared folder (if not in c:/Users)
VirtualBox -> Settings
Shared Folders
Add:
c/Github <-> C:\Github
enable "auto-mount" and "share permanently"
-v /c/Github/pl-tam251:/course
get IP address underneath the whale picture

**Comment by mwest1066** [comment]
Here are some other random notes about doc updates:

add info about "createuser postgres"
add instructions for giving docker permissions to C:
add instructions to run docker and get a command prompt on the VM
add info about "createdb postgres; dropdb postgres"

**Comment by mwest1066** [comment]
Implemented in 129d96dbca6f0e09ee41e6a1324eaff77965aa28
