### ISSUE TITLE
Calculation questionDir points to path of question being generated, even if the question has its template set to something else

### ISSUE THREAD

**Issue by jakebailey** [PrairieLearn/PrairieLearn#515]
[This line](https://github.com/PrairieLearn/PrairieLearn/blob/85f9342adb12f36eaaabf570aab19ff87e8fc0fd/question-servers/calculation.js#L30) shows the path in question.

If I have a question `baseProblem` which implements a question and has local files saved (say, for templating out code to hand out), and a question `otherProblem` uses `baseProblem` as a template, then when generating `otherProblem`, the `getData` function is given the path for the child question, and the code fails since the parent is the one that actually has that data.

Is this choice intentional? Right now, I'm solving this by adding a symlink to the child problem to the parent so that the files can be found, but that doesn't feel right. If possible, it'd be nice if the directory passed were for the actual question being run so that the server code can depend on files that are normally in its local directory.

**Comment by jakebailey** [comment]
Or, pass in the parent's path as another argument, but I don't know enough about JS to know if that's okay. I don't want to unexpectedly break someone's code.

**Comment by mwest1066** [comment]
Closing as WONTFIX because it’s a legacy v2 feature
