### ISSUE TITLE
Multiple choice and checkbox questions display answer.html after grading

### ISSUE THREAD

**Issue by angrave** [PrairieLearn/PrairieLearn#518]
If `answer.html` exists then multiple choice and checkbox questions should display its contents after the student's response has been graded to allow students to understand why a particular answer(s) is/are correct.

The typical contents of `answer.html` will be an HTML snippet e.g.
```
<p>The price of cheese is weakly correlated with precipitation forecasts</p>
```

**Comment by mwest1066** [comment]
#116 is essentially a dupe

**Comment by mwest1066** [comment]
Implemented by v3 questions.
