### ISSUE TITLE
Manually regrading a question updates the score, but not the UI glyph

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#5193]
When I regrade a question by uploading the modified `..._for_manual_grading.csv` file, the scores are updated correctly, but the UI glyphs stay the same.

## Before manual regrading

<img width="189" alt="Screen Shot 2021-12-14 at 7 49 18 PM" src="https://user-images.githubusercontent.com/2507459/146119825-1f2486a3-cafb-48b1-8a76-d31bcc373f80.png">

## After manual regrading

<img width="242" alt="Screen Shot 2021-12-14 at 7 49 03 PM" src="https://user-images.githubusercontent.com/2507459/146119810-cf81647d-d145-435c-b030-60fa07191374.png">

This is the case everywhere these scores appear, including on the assessment overview and the individual question page.

Let me know if there's anything else I can contribute to make this issue clearer!

**Comment by jonatanschroeder** [comment]
Duplicate of #5005

**Comment by firasm** [comment]
Oops! Thanks, closing issue.
