### ISSUE TITLE
DevOps: Formatter

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#5204]
The formatter is overly strong during development. It takes a long time to scan files, requires weird workflows, CI/CD tests are always failing for reasons always related to formatting, formatter is not in package.json but in Makefile etc. Everything seems broken-up and slightly different in this workflow requirement so that it makes development awkward.

Can we place the formatter in before a merge perhaps and have the CI/CD tests pass during pushes?

I feel like Jacob Two Two of the formatting world. There is too much formatting when we just need background tests to pass/fail in the pipeline and tell me about my code quality --- not the formatting code quality. It's nice to have CI/CD run async to a workflow without needing to run the tests locally all the time.

**Comment by nwalters512** [comment]
I'd highly recommend setting up your editor to automatically format files when you save them - that should free you up from having to think much about formatting during your save/commit/push loop.

> Can we place the formatter in before a merge perhaps and have the CI/CD tests pass during pushes?

This would require us to have conditional CI flows and remember to manually check formatting before merging. It's very much a best practice to have a consistent, predictable CI pipeline.

**Comment by nwalters512** [comment]
> formatter is not in package.json but in Makefile etc. Everything seems broken-up and slightly different in this workflow requirement so that it makes development awkward.

Having formatting tasks in a Makefile instead of `package.json` is definitely an idiosyncrasy compared to other JS projects, though since we also work with Python tools, I can see the argument for using a Makefile instead.

Can you elaborate on "broken up and slightly different"?

**Comment by andrewstec** [comment]
That's fair. The formatting during save works and should solve 99% of the pain. Sometimes I am restarting containers, and going back in them to run commands like the formatter in my current flow, but it should be easily workable from my IDE since the filesystem is mounted.

The only issue is that it gets frustrating to start-up a container, go inside it, format/lint, etc.

It also takes time to configure an IDE for a different workflow, even if there is a benefit. All the little things add up.

Thanks for the suggestion and I will look into it with VS Code soon.

**Comment by nwalters512** [comment]
@andrewstec after working with the new linting setup for a few more weeks, are there any specific documentation/process changes that you think we could make? Otherwise, let's go ahead and close this issue.

**Comment by andrewstec** [comment]
Nope! Anything to automate the process and ensure that VS Code is setup with ease is always great since we do not have onboarding time. 

In terms of what gets a person from a fresh VS Code IDE install to something that they can run tests on (ie. default launch file) with a recommended Docker setup, and auto-formatter/linter on save would be kick-ass. There is a lot of potential for a really nice workflow with the CI/CD setup. Unfortunately, this may requires some more work and code probably. 

It also assumes that VS Code is the IDE to support. It looks like VS Code is the way things are going, but I know JetBrain fans refuse to let go of their favourite IDE.

**Comment by andrewstec** [comment]
Good luck!
