### ISSUE TITLE
Add CSV export option for all events

### ISSUE THREAD

**Issue by kevinwang** [PrairieLearn/PrairieLearn#521]
This should export the full CSV log of events that you can get (including Begin/Close) when you click Details next to an assessmemt score, but for all users at once.

**Comment by mwest1066** [comment]
@kevinwang: here are a few suggestions about how I would implement this.

The code that dumps all the events for a particular assessment instance is in `pages/instructorAssessmentInstance/instructorAssessmentInstance.sql`. I would pull this out into a Postgres function in a new file called something like `sprocs/select_assessment_instance_logs.sql` that takes an `assessment_instance_id` as an argument.

Then in `pages/instructorAssessment/` I would add a new CSV file block. This requires adding code to the JS, SQL, and EJS files in this directory. The new SQL code would just get all assessment instance ids and then call the above function on each of them (using Postgres JOIN LATERAL) to produce the list of all events.

**Comment by mwest1066** [comment]
Implemented long ago.
