### ISSUE TITLE
Allow teams to manage their own membership

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#522]
From @mwest1066 

if someone knows how to get github to allow team maintainers to add people from outside the org then I’d like to know

**Comment by kevinwang** [comment]
This could potentially be achieved with a web app which invites users using the API token of a machine user which is configured to be an owner of the organization.

A team maintainer would log into such an app using OAuth, the app would verify that the logged in user maintains teams, and then allow the user to invite users to the org and their specific teams.

**Comment by trombonekenny** [comment]
I was thinking more around researching reconfiguring the org to remove that limitation, and what the impact of opening things up might be.

**Comment by kevinwang** [comment]
In that case, I don't think that's possible.

https://help.github.com/articles/inviting-users-to-join-your-organization/

> Only organization owners can invite users to join an organization.

**Comment by mwest1066** [comment]
Closing because it's not possible with the current GitHub model
