### ISSUE TITLE
generate_uuids tool run from inside docker

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#523]
There's no clear way to run the https://github.com/PrairieLearn/PrairieLearn/blob/master/tools/generate_uuids.py script from inside docker. This would be beneficial because running it outside of docker means having the python software there, and downloading the PrairieLearn repo just for that single file.

This could be fixed by being able to run a terminal into the docker image and running it (documented) or making it a web-based tool that can get run from the standalone-development environment.

**Comment by kevinwang** [comment]
Here's what I do:

```bash
curl -s https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/master/tools/generate_uuids.py | python - .
```

It's not short, but I just leave it in a makefile.

**Comment by trombonekenny** [comment]
That assumes you're in an environment with curl and python. Those aren't defaults in Windows 10 - the tools are inside the docker, but we need to trigger them somehow.

**Comment by lotrfan** [comment]
something like

```
docker run --rm -v $PWD:/course prairielearn/prairielearn python /PrairieLearn/tools/generate_uuids.py /course
```

run from the root of your course directory will update things.

If you just want a shell,

```
docker run -it --rm -v $PWD:/course prairielearn/prairielearn /bin/bash
```

**Comment by mwest1066** [comment]
@lotrfan: what's the point of the --rm in your first commandline above?

**Comment by lotrfan** [comment]
It deletes the container when it's done; otherwise the container would stick around in a 'stopped' state (see them with `docker ps -a`), taking up disk space and probably preventing deleting old PL images.

**Comment by mwest1066** [comment]
Nice!

I don't suppose you could send me a PR adding this to installing.md and also the python tools thing to uuid.md?
