### ISSUE TITLE
documentation: overview of v2 new models

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#524]
Update the documentation to have an overview of the new data models/organization for v2.

Course versus Class
courseInstance as Semester
Where permissions are set (in JSON except for syncing from github to production - maybe that could be made clearer in the standalone devel copy)

tests -> Assessments
all Exams now working like RetryExam

Topics and Tags, where needed, where enforced, what default/automatic ones are, future uses

Permission models: Instructor sees everything, TA acts like student wrt allowAccess

**Comment by mwest1066** [comment]
Should be resolved by the current v3 docs

**Comment by coatless** [comment]
Maybe consider adding a table highlighting the differences?

 e.g. 
![screen shot 2018-10-22 at 8 17 34 am](https://user-images.githubusercontent.com/833642/47609925-39dd4580-da0e-11e8-8fdd-1276ac07b3e4.png)
