### ISSUE TITLE
Make documentation .md files generate random UUIDs where needed

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#525]
To easier enable copy/pasting default configurations, can we make the documentation hosted on github auto-generate any embedded UUIDs each time the page loads?

GitHub function? Fancy Markdown? Embedded JS?

**Comment by kevinwang** [comment]
GFM sanitizes script tags when rendering on GitHub (for obvious reasons (XSS)), so I imagine that any kind of "dynamic" Markdown content would be difficult to achieve.

I experimented with generating a uuid inside an SVG (like how CI badges handle dynamic content), but GitHub aggressively caches images, even when `Cache-Control` and `ETag` headers are set.

Example: http://pl.kev.wang/cgi-bin/uuid.svg

Caching behavior:

![](http://pl.kev.wang/cgi-bin/uuid.svg)

So I guess the next best solution would just be to link to a page that generates the uuid value. But of course that would require *more web apps*. 😛

**Comment by kevinwang** [comment]
Alternatively, we can host the full documentation on [GitHub Pages](https://help.github.com/articles/user-organization-and-project-pages/#project-pages) and then we can do dynamic content with JS.

**Comment by mwest1066** [comment]
I would definitely like to move docs to a real website. The best thing might just be to stick it on prairielearn.engr. I'd like the prairielearn.engr homepage to have a big button in the middle for "sign in", but then some extra links at the bottom or somewhere like "what is PL", "docs for instructors", etc.

**Comment by lotrfan** [comment]
I have http://prairielearn.readthedocs.io/ set up, although haven't really done much with it; I think there's potential to have it preprocess the markdown and generate UUIDs.

**Comment by mwest1066** [comment]
I like the read the docs site. It needs a small amount of cleanup. Could you give me access/ownership of it? I'm mwest1066 on readthedocs.

**Comment by lotrfan** [comment]
Added; right now it doesn't automatically build... it looks there are instructions for setting up the webhook on github here: http://docs.readthedocs.io/en/latest/webhooks.html

**Comment by kevinwang** [comment]
Does it support client JS code? That's the main topic of this issue!

**Comment by mwest1066** [comment]
I'd be happy to use it even without the client JS for UUID generation, actually. Just as a nicer doc site.

**Comment by lotrfan** [comment]
(that's a good point...)

Not sure; mkdocs (which is what it's using to build the site) can add client-side js (http://www.mkdocs.org/user-guide/configuration/#extra_javascript), but I'm not sure if readthedocs will pass it through though.

**Comment by mwest1066** [comment]
Fixed by making UUIDs only locally unique: #1564
