### ISSUE TITLE
Clarification on lack of student data view for users with course permissions

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5284]
A very common question on the PL slack relates to course staff that fail to give themselves student data permission to the course instances. This is an understandably confusing case, since these users often have full control of the course from term to term, and often don't need access to student data for some time.

My proposal: keep the gradebook page (and other pages that require student data access) accessible to users that have course Viewer permission or above, but if the staff member doesn't have student data access, directs them to request this permission from the course owner (maybe list the owners?). If the staff member is an owner, provide a link to the staff page itself.

**Comment by trombonekenny** [comment]
Agree, this is turning into a support load. We could use the Gradebook to bring a self-documenting page pointing people to the news article and Staff tab.

**Comment by trombonekenny** [comment]
2 more emails about it today.

**Comment by echuber2** [comment]
I agree with the proposal.

**Comment by nwalters512** [comment]
Since this is continuing to cause a support load for us, I'll prioritize this and take it on.

**Comment by trombonekenny** [comment]
This came up in office hours today.
