### ISSUE TITLE
"View Variant" event miss from groupwork assessment log 

### ISSUE THREAD

**Issue by Yucheng-Jiang** [PrairieLearn/PrairieLearn#5286]
Issue: "View Variant" event tag is missed from groupwork assessment log. However, It functions normal in all other types of assessments. 

- Reproduce the error:
1. Open a groupwork assessment in a course
2. Click on Question 1
3. (optional) Click on assessment overview and then come back to Question 1 again
4. Check log file (method to check log file is described below), there is no log activity tagged with "View Variant"
5. Open any other type of assessment (hw, exams, ...), repeat same behavior, there should be at least one log activity tagged with "view variant"

Method to view logs:
  In instructor / TA view "Go to your course > your course instance > assessment name > Students tab. The links in the first column on that sheet take you to their results and log unified in one page. Scroll down to the bottom to see the detailed log" (quote from Eric Huber's instruction).

  It is also missed from log files in API, which can be downloaded using the end point `/pl/api/v1/course_instances/:course_instance_id/assessment_instances/:assessment_instance_id/log`

**Comment by jonatanschroeder** [comment]
The same issue also happens with "View assessment overview" events. Found the problem that caused it, PR on the way.

**Comment by Yucheng-Jiang** [comment]
I opened a GA log file through API, seems like "view variant" is still missing. Is this a separate issue on API side?

**Comment by nwalters512** [comment]
The fix has been merged but has not been deployed yet. Keep an eye on #announce on Slack!
