### ISSUE TITLE
Remove UIDs from JSON files for access rules

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#5303]
To ensure that folks in Canada can store course data on github.com while remaining in compliance with privacy laws, we should allow folks to create access rules via the web UI that are **not** stored in course JSON. We can store these as typical access rules but can differentiate them with a DB column that flags a row as "added manually". We'll ignore those rows when syncing (not create, update, or delete them), but they'll still. We'll then need a little UI to allow people to create and edit these rules.

**Comment by winstan** [comment]
This is no longer necessary (at least in BC) as recent legislation has removed the hard data residency requirement for Private Information.

**Comment by firasm** [comment]
very interesting @winstan! Do you have a reference or source for this? How recent is this?

**Comment by winstan** [comment]
It's recent: November 25, 2021.
https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-management-technology/information-privacy/resources/2021-amendments/foippa_amendments_data_residency.pdf

**Comment by nwalters512** [comment]
We're going to do this anyways as part of #10318! Closing this to keep discussion in one place.
