### ISSUE TITLE
Add index for group_id in group_logs table

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5306]
The group_logs table is currently used in the assessment instance log page and API entry (via sproc), by filtering the log by group_id, but there is no group_id index for this table. As the table grows with time it is probably a good idea to keep an index by group_id to the table.

A quick scan through the code shows that this table is never filtered in any other way that does not involve at least group_id filtering, so this index should be enough, but this may need to be revisited if new interfaces to this log are created (e.g., by student/user_id).

**Comment by jonatanschroeder** [comment]
@nwalters512 I believe this is resolved, can you confirm?

**Comment by nwalters512** [comment]
Yep, #5520 added this!
