### ISSUE TITLE
Add Description to question

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#532]
For question views that show Title and QID (should be named ID or Directory? Folder? #527), add a Description field. This text field would let instructors store metadata about the content of the problem.

This is especially useful if the QIDs are programmatic (Q001, Q002, Q003) and there's no other indication of what the problem is.

**Comment by mwest1066** [comment]
I assume the Description would only be visible to the course staff. This becomes more important as we have more course staff over the years using a particular question (either within a single course or even cross-courses).

It's possible that we should call this "instructorNotes" or something rather than "Description", to make the purpose clearer.

I should note that I haven't heard a lot of requests for this feature, so it's possible that no one really wants it.

**Comment by eliotwrobson** [comment]
In looking at the question navigation screen, it seems like there's not really a place where a question description might go on the screen that cleanly that would make this easy to read by an instructor. Would it be better just to add this as an allowable field in the `info.json` and show it on the `Settings` panel for the question? I don't really think there's any benefit to making the contents of these questions searchable (and this can be done anyway just by downloading the git repo for the course and searching the entire project anyway).

**Comment by nwalters512** [comment]
I'm not 100% sure if this is the same thing, but there's also been talk of adding the ability to attach instructor-visible Markdown content to questions. That could contain a description, notes about solutions, changelogs, and really any other information. If we're willing to give up the possibility of showing a description on the question list page (which is already super crowded), it might be nice to use the more general solution of arbitrary Markdown.

**Comment by eliotwrobson** [comment]
Skimming the discussion, I think that Markdown makes a lot more sense than having a text only description in a Json file. Using that separate tab as was mentioned is probably the way to go!

**Comment by nwalters512** [comment]
@trombonekenny any opposition to closing this in favor of #5357?

**Comment by nwalters512** [comment]
Closing in favor of #5357. If there's something in this issue that isn't sufficiently solved for by the other issue, we can continue discussion there or open another issue to tackle that specifically.
