### ISSUE TITLE
pl-order-blocks ranking problems don't accept partial credit 

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5368]
I believe pl-order-blocks should support partial credit in `ranking` mode now (#5261), and the docs say it should be:

> For the dag and ranking grading methods, you may specify none for no partial credit or lcs (default) for partial credit based on the LCS edit-distance from the student solution to some correct solution.

but it doesn't: 

https://github.com/PrairieLearn/PrairieLearn/blob/5d9562c2cd3fbf77dd0901206aa8faeaca77801f/elements/pl-order-blocks/pl-order-blocks.py#L63

![image](https://user-images.githubusercontent.com/2316553/153073236-f1ffae42-04fd-46b5-8dd3-a1d9a6f48659.png)

**Comment by nwalters512** [comment]
@SethPoulsen going to assign this one to you!

**Comment by SethPoulsen** [comment]
Ooops, that's my bad. Thank you for catching this @ffund. I will have a fix very shortly.

**Comment by SethPoulsen** [comment]
@ffund As a temporary work around, if you don't specify a `partial-credit` attribute on the `pl-order-blocks` element, it should work (at least this is working for me when I test it).

**Comment by ffund** [comment]
> @ffund As a temporary work around, if you don't specify a `partial-credit` attribute on the `pl-order-blocks` element, it should work (at least this is working for me when I test it).

That's interesting, I'll try that. If that's the default, how do you specify no partial credit? I tried "none" and it raised an error, and I tried "default" and it accepted it but then graded my test answer as 0% when it should have been 100%.

**Comment by SethPoulsen** [comment]
Oh, sorry. I thought you _wanted_ to have partial credit. 

If you don't want partial credit, that won't be possible until I finish this bug fix.

**Comment by ffund** [comment]
I did want partial credit for some questions, so that workaround is partly helpful ;) thanks

**Comment by SethPoulsen** [comment]
PR fix is up: #5370. @ffund feel free to review if you like, Github won't let me officially request a review from you for some reason (maybe because you aren't part of the PrairieLearn organization, or haven't reviewed PRs here before? I don't know.)

**Comment by SethPoulsen** [comment]
The real problem is that `pl-order-blocks` is a complicated element with a lot of different configuration options, so I don't always manually test them all

We _do_ have automated tests running on it, but apparently not enough. 

I need to add more tests to cover all the different configuration options so that things like this don't happen anymore.
