### ISSUE TITLE
Client files question path not available in file function

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#5372]
The option `data["options"]["client_files_question_path"]` does not appear to exist in the `file` function.  The files are still accessible if the name is stored elsewhere, e.g. a `data['params']['client_files_question_path']` entry that was created in `generate`.  Don't know whether this is a bug or intended behavior, but this limitation isn't mentioned in [https://prairielearn.readthedocs.io/en/latest/question/#accessing-files-on-disk](https://prairielearn.readthedocs.io/en/latest/question/#accessing-files-on-disk).

You might not generally need to access that directory if you are dynamically generating files with `file`, but I am using the `file` function to dynamically modify a skeleton file stored in that directory, so I need to be able to read it.

This has an easy workaround for users as I mentioned above -- storing the path elsewhere.  But, it might be worth at least updating the docs if this is the case.

**Comment by nwalters512** [comment]
I suspect this is a bug, yeah. I'd caution you or anyone else against persisting paths via `params` as a workaround, as we make absolutely no guarantees that those paths will remain unchanged over time. I'll do my best to look into this today. In the meantime, if you can post or send a link to a variant where this didn't work as expected, that'd help me debug here!
