### ISSUE TITLE
Not enough memory to run Julia

### ISSUE THREAD

**Issue by ctessum** [PrairieLearn/PrairieLearn#5373]
Hello,

I'm teaching a class ([CEE 492: Data Science for Civil and Environmental Engineering](https://uiceds.github.io/syllabus/)) where we use the [Julia](https://julialang.org/) programming language with PrairieLearn.

The issue is that the Julia compiler seems to use more memory than other language interpreters or compilers do, and also in the class we have some moderately data-intensive assessments, and we often run into the 1GB memory limit in the PL grader and workspace containers so we ended up having to grade a lot of the assessments by hand. In some cases, even if the answer key code fits within 1gb, students often write less efficient code that uses more memory and still causes the grader to crash, which leads to some student frustration.

Would it be possible to increase the memory limit in the PL workspace and autograder containers? All of the assignments we currently have in the class require less than 3.5gb, but probably 2gb would be fine. Possibly 1.5 gb, but that would be more limiting with regard to what kind of assessments we could have. It also might be fine to just allow the use of swap space in the containers, but I haven't tested that yet with my assessments.

My class will be offered again next fall, and I know of at least one other class that will also be using Julia on PL next fall. Thanks for your consideration!

**Comment by ctessum** [comment]
Hello! I was wondering if it would be possible to get an update on any progress or plans regarding this? I'm starting to plan my class for next fall, and I need to make a decision regarding whether I should plan for the availability of additional memory, or focus on making things work with the system as-is. I know of at least one other course that is in the same situation. Thanks for your consideration!

**Comment by nwalters512** [comment]
@ctessum we added config options for swap in https://github.com/PrairieLearn/PrairieLearn/pull/5790 and updated that config in our production environments to set `MemorySwap` to 4GB. Can you confirm if things are working any better for you now?

**Comment by ctessum** [comment]
Yes, it works now, thank you! 

At least in production it's fine, I still have issues in my local docker environment but that's not as big of a problem.

**Comment by mwest1066** [comment]
Excellent! Thanks for confirming. The local environment may still not have access to swap because that's controlled (in part) by your local docker configuration which PL can't alter.
