### ISSUE TITLE
ReadTheDocs integration

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#539]
We have http://prairielearn.readthedocs.io/ autobuilding, but some cleanup/formatting of the `docs/` directory would help to make it look good.

Once this is configured correctly we can point to it from the main PL homepage(s).

If anyone wants to tackle this and needs admin access to the RTD website then let me know.

**Comment by trombonekenny** [comment]
Done?

**Comment by mwest1066** [comment]
Implemented in 38cadadab4188c0f73af486309a910328a0670a9
