### ISSUE TITLE
Display a simpler 'usage' message for exams with no retry-able questions

### ISSUE THREAD

**Issue by zillesc** [PrairieLearn/PrairieLearn#540]
Currently all 'exam' assessments include this message:

> To do this assessment, go to each question and save an answer for it. At any time you can use the blue “Grade and continue” button below to grade all currently saved answers. The assessment will be automatically “finished” six hours after the last answer submission. The “Current value” of each question is the maximum points that could be earned now for a correct answer, while the “Awarded points” is how many points you have actually received for the question. To try an incorrect question again, save a new answer for it and regrade. Questions with zero remaining attempts cannot be tried again. The total points is the sum of all question points.

For exams without any questions that can be attempted multiple times, a simpler message should be displayed.  For example:

> To do this assessment, go to each question and save an answer for it. At any time you can use the blue “Grade and continue” button below to grade all currently saved answers. When you are done, you can click "Finish assessment" button; the assessment will be automatically “finished” six hours after the last answer submission.  The total points is the sum of all question points.

**Comment by mwest1066** [comment]
When we load an assessment instance in `middlewares/selectAndAuthzAssessmentInstance.sql` we could add some SQL to check whether all questions only have a single `points` value and then set a flag like `no_retries_available`. When we render `pages/studentAssessmentInstanceExam` we could check for this flag and display the messages as Craig describes above.

**Comment by longpt214** [comment]
Another way is to show the number of remaining retried attempts in a warning message after users clicks on "submit and grade" button.

**Comment by trombonekenny** [comment]
Another ping on this issue: Hit a student today when he thought he had multiple submissions but only was allowed one.

**Comment by mwest1066** [comment]
Fixed by 7d7228972103fe2522631894dfe23b0b65e9e46e
