### ISSUE TITLE
Update screenshot of issues page in docs

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5404]
The docs related to issue reporting (https://prairielearn.readthedocs.io/en/latest/assessment/#issue-reporting) have a really outdated screenshot of the issues page. This should probably be updated to the new view of the page.

Related: #4093

**Comment by michaelfromyeg** [comment]
Hey! I've been looking to help out with PL development and this seems like a rather easy first ticket to get started with; am I okay to take this one on?

If so, I should be able to have a PR up in the next few days, or at least within the week!

**Comment by jonatanschroeder** [comment]
Sure that should be fine. The page will likely be updated in the future, but not in the near future, so go for it.

**Comment by michaelfromyeg** [comment]
PR is open!^ I can't request reviews it seems but it should be good to go!
