### ISSUE TITLE
Implement server-side sessions

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#5416]
Right now, users authenticate solely via a cookie. If the cookie says it's valid and the signature matches, we trust it. However, this leaves us unable to invalidate sessions, which would be really useful during a potential security incident or if we find a bug with authentication code.

We should switch to using server-side sessions that are persisted in the database. We can build this on top of http://expressjs.com/en/resources/middleware/session.html with a custom session store to interact with a new `sessions` table, which we're envisioning would have the following schema:

- `session_id`: A UUID that uniquely identifies a session; used as the session ID (the value of the cookie)
- `user_id`: Maps to a user in the `users` table
- `authn_provider_name`: Just like the field that we currently store in the signed cookie. This is useful for displaying messages that are specific to LTI sessions.
- `created_at`: Date the session was created
- `expires_at`: Stores when the session will expire. If the cookie for this session is used after this date, it's considered invalid.
- `invalidated_at`: Date the session was invalidated. We'll do soft-deletes instead of removing the row entirely so that we can use this as forensic data during a hypothetical investigation.
- `data`: A JSON column storing other arbitrary data about this session (flash messages, etc.)

We'll need some logic to handle packing and unpacking `user_id` and `created_at` from the session object. That is, `req.session.user_id` should correspond to the user ID, but we don't actually want to store that in the `data` JSON blob.

Currently PL extends sessions by N hours every time there's a request. However, we'd place a lot of pressure on Postgres if we actually tried to update the row on every single request. So, instead of that, we'll only update `expires_at` to be N hours from now if `(NOW() + N hours) - expires_at >= 24 hours`.

We should ensure that sessions and their corresponding cookies are invalidated when a user explicitly logs out.

To avoid breaking existing sessions when we deploy this change, we should write some code to migrate existing `pl_authn` cookies to the new system.

**Comment by trombonekenny** [comment]
We should consider the case where a user may have different authentication scopes: like, for example, Shibboleth auth for most courses but LTI authentication for a single course instance. Right now you can only have one authenticated session so they invalidate each other when they context switch. If there was a way to have multiple sessions and have the right one scoped to the course instance it's tied to, that would make it easier for the user?

**Comment by nwalters512** [comment]
Infrastructure for this was added in #7143, but we still don't use sessions for storing auth data. Currently, they're just used for flash messages.

**Comment by nwalters512** [comment]
We started dual-writing user authentication information in #8620, which has been deployed in production for ~8 months now. #9964 will cut us over to only using the session for this. I believe this issue can be closed now!
