### ISSUE TITLE
Not able to download scores from assessment

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#542]
I get the following error when I try to download the scores (TAM210/211_Spring2017_HW1_scores.csv)

![image](https://cloud.githubusercontent.com/assets/12501485/22177120/c79e40ea-dfdd-11e6-8e10-670b3692a3b4.png)

**Comment by mwest1066** [comment]
It was because there was a slash character in the course name. It should be fixed now.

**Comment by mfsilva22** [comment]
thanks!
