### ISSUE TITLE
Don't mislead students when quiz only has one attempt (left)

### ISSUE THREAD

**Issue by angrave** [PrairieLearn/PrairieLearn#548]
""To try an incorrect question again, save a new answer for it and regrade. Questions with zero remaining attempts cannot be tried again. The total points is the sum of all question points."

^ Not true for single attempt quizzes
Some ideas-

Would also be great if PL explicitly displayed a retry count and a message  so students are clear about how many more times they can submit
e.g.
"You can only submit and grade this quiz once" if remain = 1 and initial = 1
e.g.
"You have submitted for grading %d times(s) you have %d more attempts after this one"

**Comment by mwest1066** [comment]
Dup of #540
