### ISSUE TITLE
Some question numbers have a ".1" suffix in question stats

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5481]
For example:

![image](https://user-images.githubusercontent.com/2316553/156440865-78aa6a87-29d7-4f8e-8a96-df926fb6e738.png)

or

![image](https://user-images.githubusercontent.com/2316553/156440955-8e2c1af0-aaee-467a-bb2b-c20d21d0d482.png)

**Comment by nwalters512** [comment]
One such exam, for reference: https://www.prairielearn.org/pl/course_instance/129047/instructor/assessment/2316772/question_statistics

This looks like an issue with the [`admin_assessment_question_number`](https://github.com/PrairieLearn/PrairieLearn/blob/f5341c7abc43e61b5fe31bafd86d47d26a4b5e6d/sprocs/admin_assessment_question_number.sql) sproc - it should add `deleted_at IS NULL` to the `WHERE` clause when doing the `JOIN LATERAL` on the `assessment_questions` table.
