### ISSUE TITLE
allow-blank in pl-order-blocks

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5496]
Some elements have an `allow-blank` attribute so they will accept a blank answer as a submission, but pl-order-blocks does not. 

I would benefit from having `allow-blank` in order blocks questions, for two reasons:

1. because sometimes that's the correct answer: I use pl-order-blocks to ask questions of the form "Identify which of these events will occur, and put the events that *will* occur in order". Sometimes the correct answer is "None of these events will occur", so I'd want the answer to be blank. 

    As a workaround, I could add a "None of these" source block, but that's awkward and not very intuitive for students.

2. for more forgiving assessments: sometimes a pl-order-blocks question is part of a longer question. If the student leaves the pl-order-blocks part empty, the question is considered invalid and not gradeable, so the student won't get any credit for the part they complete. 

    For some other elements, I can clear format errors in `parse()` if I want the rest of the question to be graded (and the blank part to get zero). But this doesn't work for pl-order-blocks.

**Comment by SethPoulsen** [comment]
@ffund This shouldn't be difficult to implement, its just a matter of adding/remove if statements in a few different places.

If you want to open a PR I'd be happy to review it. 

I'll go ahead and add this to the project board where I keep requested pl-order-blocks features.
