### ISSUE TITLE
Error starting PL Workspaces

### ISSUE THREAD

**Issue by Szplugz** [PrairieLearn/PrairieLearn#5504]
I (and everyone else in my course) get the following error when I try to open a VS Code workspace within a PL question
<img width="1440" alt="Screen Shot 2022-03-10 at 15 16 54" src="https://user-images.githubusercontent.com/69532488/157756405-92519b7a-fab4-49e5-b717-7158d62762b1.png">

I'm not sure if this is a general PL issue with workspaces, or if the issue is specific to my class. But to my knowledge the course staff have not been able to debug it so far and it's been a week, so I thought I'd open an issue here.

**Comment by nwalters512** [comment]
Thanks for the report. Can you link to the particular question that you're looking at? That'll help us debug further.

**Comment by Szplugz** [comment]
Sure - https://www.prairielearn.org/pl/course_instance/128954/assessment_instance/3742534/

**Comment by nwalters512** [comment]
I'm able to successfully run other workspaces, e.g. all those in the example course "Questions using workspaces" assessment (https://www.prairielearn.org/pl/course_instance/4970/instructor/assessment/2224101/questions). As best as I can tell, this is an issue unique to your course's Docker image. @glherman did you perhaps recently update the `cs233illinois/workspace-vscode-wave` Docker image with something that could have broken them? Are you able to successfully run the `lab8/timer` workspace locally?

**Comment by echuber2** [comment]
I've just made a PR to 233's private repo that should help them resolve this.

**Comment by echuber2** [comment]
To summarize, I was able to replicate the issue locally with the existing materials: startup times out because there's too much in the image with the wrong ownership permissions set, and the container times out at startup while fixing the permissions. Some optimizations in the container build materials make this issue go away.

**Comment by nwalters512** [comment]
PR link for posterity, for those who have access to it: https://github.com/PrairieLearn/pl-cs233/pull/583

**Comment by Szplugz** [comment]
Thanks!

**Comment by nwalters512** [comment]
Given that this is an issue with a specific course's content, I'm going to go ahead and close this issue. For posterity, I've opened https://github.com/PrairieLearn/PrairieLearn/issues/5505, which should prevent the need for complicated `chown`ing at either build time *or* runtime, which should in turn prevent this class of timeout from occurring in the first pplace.
