### ISSUE TITLE
Missing argument in gradeAllAssessmentInstances()

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5526]
It looks like we missed one update in #5489. The `gradeAssessmentInstance()` call here: https://github.com/PrairieLearn/PrairieLearn/blob/21c26abd8efedc4e0c1d4558c01b901280c7b0c8/lib/assessment.js#L401 is missing the `requireOpen()` argument.

Looking at this code again, at the moment we will throw an error (and terminate the grading of all instances) if any of these is unexpectedly closed (e.g., due to a race). Should we change `requireOpen` to cause a simple return-with-no-error if the assessment is closed? I don't think we rely on the actually-throw-an-error behavior anywhere if an instance is unexpectedly closed.

**Comment by nwalters512** [comment]
@mwest1066 do you think #5090 adequately describes the desired "don't throw error for unexpectedly-closed assessment" behavior?

**Comment by mwest1066** [comment]
> @mwest1066 do you think #5090 adequately describes the desired "don't throw error for unexpectedly-closed assessment" behavior?

Yep, good call. We should actually do that 😄
