### ISSUE TITLE
Wrap each migration in a transaction

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5530]
At the moment a single migration file can partially execute. For example, consider a migration file that contains:
```
ALTER TABLE foo ADD COLUMN bar;
UPDATE foo SET bar = complex_calculation();
```
We might interrupt this migration while it's running the second line, which would leave the first line already run but the migration won't be listed as complete in the `migrations` table, so we'll try and run it again the next time we do migrations. This will then fail, because we are trying to re-ADD a column.

Our current workaround for this is to write transactions so they can be re-applied multiple times, but this makes them more complicated to write.

To fix this properly, we should wrap each migration file in a separate transaction when running it.

**Comment by nwalters512** [comment]
I tried doing this in #5607 but very quickly hit a roadblock:

```
ALTER TYPE ... ADD cannot run inside a transaction block
```

Looks like Postgres isn't designed to do this :( I think we'll have to go with the "write transactions so they can be re-applied multiple times" approach, even though "this makes them more complicated to write".
