### ISSUE TITLE
Statistics page plots has no x- or y-labels

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#5535]
Just leaving a quick note because a couple of people told me that the Statistics page plots used to have x and y-labels but now they longer do.

Might be a quick fix, but maybe not!

![Screen Shot 2022-03-24 at 9 37 40 AM](https://user-images.githubusercontent.com/2507459/159966741-4af08d8e-aaaa-413b-aa55-89775a9b8230.png)

**Comment by nwalters512** [comment]
Relevant bit of code:

https://github.com/PrairieLearn/PrairieLearn/blob/e43aafb93c510077215b8db004c97b8e3ba8a08e/pages/instructorAssessmentStatistics/instructorAssessmentStatistics.ejs#L29-L38

We are *trying* to add axis labels, but something seems to have broken!
