### ISSUE TITLE
Some elements are not properly disabled when submissions are not permissible

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5540]
Element development allows the elements to use the `data["editable"]` property to disable or otherwise avoid new user input in situations like closed exams or inactive assessments (or, related to #5413, the manual grading page). While most of the simplest elements (integer, number, string, matrix input, matrix component, symbolic, multiple choice, checkbox) become disabled in this scenario, not all elements use this information. Here are the official PL elements that, at this moment, as far as I can identify, would need to be updated to disallow answer editing:

* [x] `pl-file-editor`;
* [x] `pl-file-upload`;
* [x] `pl-dropdown`;
* [x] `pl-order-blocks` (@SethPoulsen tagging you in case you'd like to do something about it);
* [x] `pl-matching` (#10038);
* [x] `pl-rich-text-editor` (tagging myself just to be fair to the people above @jonatanschroeder 😄);
* [x] `pl-drawing` (#10041).

~~`pl-threejs` (not sure if and how precisely this is still being maintained).~~ DEPRECATED

**Comment by SethPoulsen** [comment]
Completed for `pl-orded-blocks` by @Frozemint in #7901

**Comment by jonatanschroeder** [comment]
@nwalters512 @nicknytko with #5540 underway the only element left to address is `pl-drawing` (since `pl-threejs` is deprecated, and I assume won't be maintained anymore for issues like this).

**Comment by nwalters512** [comment]
@jonatanschroeder that should be a trivial fix, I'll do that now.

**Comment by nicknytko** [comment]
> @nwalters512 @nicknytko with #5540 underway the only element left to address is `pl-drawing` (since `pl-threejs` is deprecated, and I assume won't be maintained anymore for issues like this).

This might be as simple as changing this line: https://github.com/PrairieLearn/PrairieLearn/blob/28476ef6cfcf65562c9ec445c3ed5d1377b5f410/apps/prairielearn/elements/pl-drawing/pl-drawing.py#L297

**Comment by nwalters512** [comment]
@nicknytko that's more or less exactly what I did 🙂
