### ISSUE TITLE
Add regrade function with full points awarded to selected questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#562]

**Comment by angrave** [comment]
Prototype a method to "gift points" for bad questions to students and regrade assessment scores.
Suggested KISS implementation: A json file in Sp17/
`adjustScores.json` which contains an array of question uuids e.g.

{ forcecorrect: [ "uuid","uuid"] }

to mark questions that should be regraded as correct with full points.

Plus some way to ensure students are regraded if this file contains new data after syncing
(e.g. possibly a 'regrade' button on an assessment / admin ('regrade all') or (more dangerous:) automatically after resyncing if the file has been modified)
As a prototype this would be subject to change but a starting point for future (possibly breaking) changes and enhancements.

**Comment by angrave** [comment]
- (another KISS) :  Insteda of a adjustScores.json, add a new property for checkbox and MC questions (possibly other question types too) -
e.g. 
"badquestion" : true

- you could also display a warning if assessments include bad questions.
