### ISSUE TITLE
Formalize 'develop' directory

### ISSUE THREAD

**Issue by angrave** [PrairieLearn/PrairieLearn#563]
Informally (private correspondence with MW) PrairieLearn v2  deliberately ignores a 'develop' directory in  a course git repo, and the contents can be upto (say) 10MB.

This should be 'blessed' i.e. included in the documentation specification of the contents of course repo, so that course developers can rely on this assumption and use the develop directory to hold question development materials.

**Comment by nwalters512** [comment]
This hasn't proven necessary in the intervening years. We document all of the directories we use, and any others are fair game for instructors to put arbitrary files in. @angrave let me know if there's a specific use case you're thinking of that isn't addressed by the standard behavior.

**Comment by angrave** [comment]
Directory usage changes over time.
All that is needed is a short documentation promise - ie. the document should say that 'develop' will _never_be used be read by future versions of PrairieLearn
