### ISSUE TITLE
Booleans render as the empty string with html

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5658]
In the `html` package, booleans render as the empty string: https://github.com/PrairieLearn/PrairieLearn/blob/df80443bbe31e40e84791d84686799ae1108c763/packages/html/src/index.ts#L35

I found this behavior a bit surprising and I wasn't sure why it was like that. Perhaps we could change to either render as `"true"`/`"false"` strings or to throw an error?

**Comment by nwalters512** [comment]
One place where this is actually nice is conditionally rendering things, e.g.

```ts
const h = html`
  <div class="container">
    Hello!
    ${alert && html`<div class="alert">${alert.message}</div>`}
  </div>
`;
```

Compare to this:

```ts
const h = html`
  <div class="container">
    Hello!
    ${alert ? html`<div class="alert">${alert.message}</div>` : ''}
  </div>
`;
```

This is also neat for conditionally rendering some elements of lists:

```ts
const h = html`
  <ul>
    ${rows.map((row) => row.visible && html`<li>${row.name}</li>`}
  </ul>
`;
```

**Comment by nwalters512** [comment]
This behavior was changed in #7508.
