### ISSUE TITLE
Re-opening exams is not discoverable

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5663]
If a student's exam is unexpectedly terminated before the session finishes (e.g., like the fire alarm yesterday during the exam) then the CBTF staff will ask instructors to "delete or re-open the student exams" so that students can either start the exam again or continue from where they left off.

"Deleting" an exam is discoverable, but "Re-open" no longer is. "Re-open" used to be an option on the "Action" menu, but now it's no longer there and instead it's accessed as "Remove time limit" under several layers of buttons.

In practice we've found this to be undiscoverable by instructors.

One solution might be to just restore the "Re-open" menu item on the "Action" menu?

@jonatanschroeder I think you reworked some of these dialogs?

**Comment by jonatanschroeder** [comment]
Is this a duplicate of #4811?

**Comment by mwest1066** [comment]
Yep, dup of #4811 😄 -- it's causing lots of confusion today because we had an exam fail yesterday, so it's currently top of mind!
