### ISSUE TITLE
pl-order-blocks can't handle a space in answers-name

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#5664]
a simple question that will trigger the issue: 

```html
<pl-order-blocks answers-name="some name with spaces in it" grading-method="unordered">
  <pl-answer correct="false">1</pl-answer>
  <pl-answer correct="true">2</pl-answer>
  <pl-answer correct="true">3</pl-answer>
</pl-order-blocks>
```

The error that is triggered: 
```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-order-blocks/pl-order-blocks.py", line 335, in parse
    student_answer = json.loads(student_answer)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

reported by a user on PrairieLearn Slack.

**Comment by SethPoulsen** [comment]
The root of the issue is that the order blocks code uses the `answers-name` as part of the HTML `id` for the hidden `input` element that stores the answer: 
https://github.com/PrairieLearn/PrairieLearn/blob/c1463342cd5614445130bc69a1f80e628655aadd/elements/pl-order-blocks/pl-order-blocks.mustache#L43

Each time a user interacts with the drag-and-drop interface, there is some Javascript that updates the value in the hidden input box: 
https://github.com/PrairieLearn/PrairieLearn/blob/c1463342cd5614445130bc69a1f80e628655aadd/elements/pl-order-blocks/pl-order-blocks.js#L34-L35

But the jQuery line at the beginning of the second line fails to find the element because the identifier has a space in it. 

There are hacks you can do to make jQuery find elements even if the id has a space in it, but that might not be the right approach, because technically having a space in an identifier is not valid HTML. Its probably better to use something different as the id, like something with the UUID in it. 

I need to have a look and see if any other elements handle a similar situation in a different way.

**Comment by mwest1066** [comment]
> I need to have a look and see if any other elements handle a similar situation in a different way.

Most elements generate a UUID on the spot for use in situations like this (and don't store this UUID anywhere except in the generated HTML). If `pl-order-blocks` can work with that strategy then it would be very robust.
