### ISSUE TITLE
Incorrect error handling in pullImages for grader hosts

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5669]
During pre-loading of images on grader hosts, if we encounter an error then there is something wrong with the handling of it in the callback stack. An example error trace is:
```
info: Querying for recent images
info: Need to pull 7 images
/PrairieLearn/node_modules/async/dist/async.js:324
if (fn === null) throw new Error("Callback was already called.");
^
Error: Callback was already called.
at /PrairieLearn/node_modules/async/dist/async.js:324:36
at /PrairieLearn/grader_host/lib/pullImages.js:85:15
at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
at /PrairieLearn/grader_host/lib/pullImages.js:69:21
at /PrairieLearn/node_modules/dockerode/lib/docker.js:118:7
at Modem.buildPayload (/PrairieLearn/node_modules/docker-modem/lib/modem.js:320:19)
at ClientRequest.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:302:10)
at ClientRequest.emit (events.js:400:28)
at ClientRequest.emit (domain.js:475:12)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at Socket.emit (domain.js:475:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by mwest1066** [comment]
I had a brief attempt at simplifying the callback logic in #5668 but I wasn't confident that it would actually fix anything.

**Comment by mwest1066** [comment]
Here's another similar stack trace that we just had, but not in different code:
```
info: Received job!
info: received [REDACTED] from queue
info: Logging job [REDACTED] to S3: [REDACTED]
/PrairieLearn/node_modules/async/dist/async.js:324
if (fn === null) throw new Error("Callback was already called.");
^
Error: Callback was already called.
at /PrairieLearn/node_modules/async/dist/async.js:324:36
at /PrairieLearn/node_modules/async/dist/async.js:3674:17
at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
at /PrairieLearn/grader_host/index.js:274:20
at /PrairieLearn/node_modules/dockerode/lib/docker.js:118:7
at Modem.buildPayload (/PrairieLearn/node_modules/docker-modem/lib/modem.js:320:19)
at ClientRequest.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:302:10)
at ClientRequest.emit (events.js:400:28)
at ClientRequest.emit (domain.js:475:12)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at Socket.emit (domain.js:475:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by echuber2** [comment]
The async-stacktrace library may not be playing nice with the async library. For async-stracktrace, if a callback is null, it rethrows the error itself:

https://github.com/Pita/async-stacktrace/blob/860431f7ab50e8139fddf86a2495ddc4a3476a84/ERR.js#L49-L58

But the async library sets callback to null to show that it's already been called on the error:

https://github.com/caolan/async/blob/6927a814ad505920179e5dd50e3ccb085f591273/dist/async.js#L322-L329

**Comment by echuber2** [comment]
From the `async` library documentation:

> Multiple callbacks
> 
> Make sure to always return when calling a callback early, otherwise you will cause multiple callbacks and unpredictable behavior in many cases.
> 
> ```js
> async.waterfall([
>     function(callback) {
>         getSomething(options, function (err, result) {
>             if (err) {
>                 callback(new Error("failed getting something:" + err.message));
>                 // we should return here
>             }
>             // since we did not return, this callback still will be called and
>             // `processData` will be called twice
>             callback(null, result);
>         });
>     },
>     processData
> ], done)
> ```
> 
> It is always good practice to return callback(err, result) whenever a callback call is not the last statement of a function.

It looks like there are many places where we should probably be returning like it describes. @nwalters512

**Comment by nwalters512** [comment]
Yeah, calling callbacks multiple times is universally a bad idea, and isn't specific to `async`. We use `async` and `async-stacktrace` extensively together throughout PL - this is not an issue with either of them. The `docker.createImage` call [here](https://github.com/PrairieLearn/PrairieLearn/blob/c1463342cd5614445130bc69a1f80e628655aadd/grader_host/index.js#L268) ends up with `callback` being invoked multiple times. Identifying *why* that's the case is our next step.

**Comment by nwalters512** [comment]
after deploying improved logging, we get a little more information: 

```
Apr 26 20:11:37 ip-172-31-29-82.ca-central-1.compute.internal node[5039]: info: Logging job XXX to S3: prairielearn-ca-grading/job_XXX
Apr 26 20:11:37 ip-172-31-29-82.ca-central-1.compute.internal node[5039]: info: Successfully pulled "${image}" image
Apr 26 20:11:37 ip-172-31-29-82.ca-central-1.compute.internal node[5039]: error: Error pulling "prairielearn/grader-c" image; attempting to fall back to cached version
Apr 26 20:11:37 ip-172-31-29-82.ca-central-1.compute.internal node[5039]: error: createImage error: read ECONNRESET {"code":"ECONNRESET","errno":-104,"stack":"Error: read ECONNRESET\n    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)","syscall":"read"}
```

**Comment by nwalters512** [comment]
I added a few more logs:

- `globalLogger.info(`Pulling image: ${JSON.stringify(params)}`);` immediately before the `docker.createImage` call
- `globalLogger.warn(`createImage callback called for image "${image}"`);` immediately inside the `docker.createImage` callback

I now see the following:

```
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: info: Logging job 7529144 to S3: prairielearn-ca-grading/job_7529144
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: info: Pulling image: {"fromImage":"769954110362.dkr.ecr.ca-central-1.amazonaws.com/prairielearn/grader-c","tag":"latest"}
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: warn: createImage callback called for image "prairielearn/grader-c"
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: info: Successfully pulled "${image}" image
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: warn: createImage callback called for image "prairielearn/grader-c"
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: error: Error pulling "prairielearn/grader-c" image; attempting to fall back to cached version
Apr 26 20:19:47 ip-172-31-29-82.ca-central-1.compute.internal node[7410]: error: createImage error: read ECONNRESET
```

So it appears as though `dockerode` is indeed calling our own callback twice.

**Comment by echuber2** [comment]
^Following the thread's link to the moby issue, it sounds like it might happen if the image is updated on the registry while the pull is still being attempted.

**Comment by nwalters512** [comment]
I added the following logs to `dockerode`:

https://github.com/apocas/dockerode/blob/9a50c266497860d15a4ef2e213d54b4684db5e30/lib/docker.js#L117

```js
    this.modem.dial(optsf, function(err, data) {
      console.trace('createImage callback called');
      callback(err, data);
    });
```

I see that even at that level, the `modem` is invoking its callback twice:

```
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: info: Pulling image: {"fromImage":"769954110362.dkr.ecr.ca-central-1.amazonaws.com/prairielearn/grader-c","tag":"latest"}
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: Trace: createImage callback called
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at /PrairieLearn/node_modules/dockerode/lib/docker.js:118:15
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Modem.buildPayload (/PrairieLearn/node_modules/docker-modem/lib/modem.js:338:7)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:281:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.emit (events.js:412:35)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.emit (domain.js:475:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.socketOnData (_http_client.js:515:22)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.emit (events.js:400:28)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.emit (domain.js:475:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at addChunk (internal/streams/readable.js:293:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at readableAddChunk (internal/streams/readable.js:267:9)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.Readable.push (internal/streams/readable.js:206:10)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: warn: createImage callback called for image "prairielearn/grader-c"
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: info: Successfully pulled "${image}" image
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: Trace: createImage callback called
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at /PrairieLearn/node_modules/dockerode/lib/docker.js:118:15
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Modem.buildPayload (/PrairieLearn/node_modules/docker-modem/lib/modem.js:320:19)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:302:10)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.emit (events.js:400:28)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at ClientRequest.emit (domain.js:475:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.socketErrorListener (_http_client.js:475:9)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.emit (events.js:400:28)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at Socket.emit (domain.js:475:12)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at emitErrorNT (internal/streams/destroy.js:106:8)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: at processTicksAndRejections (internal/process/task_queues.js:82:21)
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: warn: createImage callback called for image "prairielearn/grader-c"
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: error: Error pulling "prairielearn/grader-c" image; attempting to fall back to cached version
Apr 26 20:31:48 ip-172-31-29-82.ca-central-1.compute.internal node[10821]: error: createImage error: read ECONNRESET {"code":"ECONNRESET","errno":-104,"stack":"Error: read ECONNRESET\n    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)","syscall":"read"}
```

**Comment by echuber2** [comment]
Looks like modem may need the timeout adjusted. I made a PR, one sec

**Comment by echuber2** [comment]
Closed the PR - as Nathan noted, the timeout didn't change anything. The docker-modem library may be calling after each https response instead of waiting for the actual resolution.

**Comment by nwalters512** [comment]
This looks to be an issue with `docker-modem`. It calls `buildPayload` on a `response` event (https://github.com/apocas/docker-modem/blob/e5f75ea4b13dd504a24f92d6257aad5b4ba8f3d4/lib/modem.js#L281) and on an `error` event (https://github.com/apocas/docker-modem/blob/e5f75ea4b13dd504a24f92d6257aad5b4ba8f3d4/lib/modem.js#L302). This is supported by the line numbers we see referenced in stack traces. It looks like we get a successful response and the immediately get an `ECONNRESET` for some reason.

**Comment by nwalters512** [comment]
I've found that enabling Docker debug mode (`{"debug": true}` in `/etc/docker/daemon.json`) reliably causes the `ECONNRESET` error to go away 👀

**Comment by echuber2** [comment]
I wonder if the ECONNRESET is to be expected in this case (load balancing on the registry side?) and debug mode just ignores it as a warning.

**Comment by nwalters512** [comment]
`ECONNRESET` is from communication with the Docker daemon itself, not with the registry.

**Comment by echuber2** [comment]
Okay, in that case, it looks like we have the limit on concurrent init pulls (`config.parallelInitPulls`) set to 5, but for the daemon the limit defaults to 3 (https://docs.docker.com/engine/reference/commandline/dockerd/). Would it make sense to increase the limit? See: https://stackoverflow.com/questions/43479614/docker-parallel-operations-limit

**Comment by nwalters512** [comment]
This is not related to the download limit. We aren't attempting to actually download more that 2 images concurrently, and even then, Docker does not error if you try to exceed that limit.

**Comment by nwalters512** [comment]
Dumping context at the end of the day: this is definitely a bug with `docker-modem`. The fact that it's even possible for it to call a callback multiple times is completely wrong. I'm going to file an issue on `docker-modem` about this tomorrow. In the meantime, see https://github.com/PrairieLearn/PrairieLearn/pull/5678 for a change that should prevent this from happening now. We'll cut over more pieces of the external grader to use `async`/`await` if this is successful; that should help us defend against similar issues in the future.

**Comment by nwalters512** [comment]
Here's the issue I opened on the `docker-modem` repo: https://github.com/apocas/docker-modem/issues/142

**Comment by nwalters512** [comment]
We no longer use callbacks in `grader-host` (or we wrap them in `Promise`), so this should never occur again.
