### ISSUE TITLE
Python grader has version conflicts between scipy and networkx

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#5679]
The networkx library requires `scipy>=1.8` now:

https://github.com/networkx/networkx/blob/a4696ddb6f5fb2370976e9c14b057d056fbb9fb0/requirements/default.txt#L2

However, the Python grader is still trying to pin `scipy==1.7.1`:

https://github.com/PrairieLearn/PrairieLearn/blob/6728e9402a471f4f8de405c828ae6cddded7a523/graders/python/requirements.txt#L5

This may be causing problems for some courses, based on Slack discussions.

To reproduce the issue with the latest Python autograder:

``` bash
$ sudo docker run -it --rm -u 0 --entrypoint /bin/bash prairielearn/grader-python
bash-4.2# python3
```

``` python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> G = nx.wheel_graph(3)
>>> A = nx.adjacency_matrix(G)
<stdin>:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/networkx/linalg/graphmatrix.py", line 173, in adjacency_matrix
    return nx.to_scipy_sparse_matrix(G, nodelist=nodelist, dtype=dtype, weight=weight)
  File "/usr/local/lib/python3.9/site-packages/networkx/convert_matrix.py", line 1019, in to_scipy_sparse_matrix
    A = to_scipy_sparse_array(
  File "/usr/local/lib/python3.9/site-packages/networkx/convert_matrix.py", line 921, in to_scipy_sparse_array
    A = sp.sparse.coo_array((d, (r, c)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
```

But updating scipy in the container fixes this issue:

``` bash
bash-4.2# pip3 install --force-reinstall --no-deps scipy==1.8.0
```

``` python
bash-4.2# python3
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> G = nx.wheel_graph(3)
>>> A = nx.adjacency_matrix(G)
<stdin>:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
>>> A
<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>
```

**Comment by mwest1066** [comment]
What triggered this bug? Did we upgrade networkx? Rather than upgrading scipy could we instead downgrade networkx? I'm a bit worried about upgrading scipy because I thought there was an incompatibility with pytorch? But maybe we removed pytorch?

**Comment by nwalters512** [comment]
> What triggered this bug? Did we upgrade networkx?

Yep, courtesy of yours truly 😬: https://github.com/PrairieLearn/PrairieLearn/pull/5650

I don't see `pytorch` as a dependency in the Python grader `requirements.txt`: https://github.com/PrairieLearn/PrairieLearn/blob/6728e9402a471f4f8de405c828ae6cddded7a523/graders/python/requirements.txt

**Comment by mwest1066** [comment]
> Yep, courtesy of yours truly 😬: #5650
> 
> I don't see `pytorch` as a dependency in the Python grader `requirements.txt`: https://github.com/PrairieLearn/PrairieLearn/blob/6728e9402a471f4f8de405c828ae6cddded7a523/graders/python/requirements.txt

I can see two strategies here:
1. Downgrade `networkx` immediately as a short-term fix, and then after the semester is over upgrade everything in the grader image.
2. Upgrade `scipy` right now and hope that there aren't any other incompatibilities introduced.

Thoughts?

**Comment by mwest1066** [comment]
> Realistically, 1. is probably the safest. Let's get through finals and then we can do all our deferred maintenance!

Sounds good. Can you PR that?
