### ISSUE TITLE
MultipleTrueFalse questions not recording correct scores

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#568]
Reported by Bruce.

Possible side effect of v2 migration - server bug or config files need updating?

You can reproduce this with the exampleCourse HW1 MTF question. Even if you get all the answers correct, the score stays 0%.

![1](https://cloud.githubusercontent.com/assets/10765199/22516461/7b30e0c8-e86b-11e6-9098-cafb8186f8ab.PNG)

**Comment by echuber2** [comment]
CS421 had this issue as well.

**Comment by mwest1066** [comment]
Fixed in 5228c440817d0891ecbfc87eb35cdeae572ffbbb (slightly hacky, but will hold until the correct fix comes with #574).
