### ISSUE TITLE
make docker/start_postgres.sh accept $PGDATA

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#5689]
`docker/start_postgres.sh` has hardcoded paths for pgdata. We should make it work with the PGDATA environment variable so we can point it to other places, like persistent storage or a tmpfs docker volume.

**Comment by trombonekenny** [comment]
On my dev system with an SSD, I saw a 400% increase in speed in `make test` by running /var/postgres in a tmpfs (RAM disk).

**Comment by nwalters512** [comment]
This was done in #5751.
