### ISSUE TITLE
Add sidebar with links to each panel of instructorAssessment page

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#570]
Just a simple list of the panel headings (e.g., Access Rules, Score Statistics, Duration Statistics, etc.) floating on the side of the page with links to jump to those sections.

**Comment by rbessick5** [comment]
This is completely because I'm lazy and don't like scrolling down to the "Downloads" section to pull grades for Compass.

**Comment by mwest1066** [comment]
Closing in favor of #593

**Comment by mwest1066** [comment]
Implemented in #1300
