### ISSUE TITLE
Pages loading slowly on production PL

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#571]
Page loads on https://prairielearn.engr.illinois.edu are slow (seconds up to a minute or two; or time-outs)

Culprit seems to be really high CPU load on the PostgreSQL server.

Find the query that's killing the CPU and tame it. :)

**Comment by mwest1066** [comment]
Fixed by 47b841b939b908ae399aa6617d224ed641f0a9b7 and 647f7c94d08e3f8ce0e1a0644a502b7d64669afa
