### ISSUE TITLE
Still recording only 0s with MTF and Checkbox questions

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#575]
Testing the same content as MTF and Checkbox questions on the 421 PL instance, we are still getting all 0s even after yesterday's fixes. Haven't spun up a local instance of PL to check it in-depth yet. @mwest1066

**Comment by trombonekenny** [comment]
Suggests #568 didn't resolve it.

**Comment by mwest1066** [comment]
Presumably related to #574

**Comment by mwest1066** [comment]
I fixed #574. Can you please test your MTF and Checkbox questions again to see if they now work as expected?

**Comment by echuber2** [comment]
I think it's working, although the model of using >50% as a threshold and actually awarding the full points remaining for that trial, is a bit confusing.

**Comment by mwest1066** [comment]
Agreed on the 50% threshold thing, and I plan to change that soon. I'm closing this issue as fixed for now.
