### ISSUE TITLE
Let students see their own previous variants by clicking on score badge

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5763]
Currently, if a student submits a (not single variant) HW question, and has no more tries for that variant, once they click away they cannot see that submission. When they open the question again, they see a new variant.

However, students like to see their own previous submission, either to help with exam review, or to revisit incorrect attempts.

It would be cool if these score badges were click-able, and let students review the variant + submission associated with the score:

![image](https://user-images.githubusercontent.com/2316553/168375234-a5e797f1-5181-4932-9276-923399c68c9c.png)

(on both assessment overview and question pages.)

**Comment by jonatanschroeder** [comment]
Related: #3158, #29

**Comment by glherman** [comment]
My students have been asking for this functionality this semester and recommend this implementation
