### ISSUE TITLE
pl-multiple-choice partial credit

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#5796]
As far as I know, it doesn't seem like there's a built-in way to give partial credit in pl-multiple-choice elements. It would be really nice to have this as a feature, and then have a different icon display the partial credit given.

**Comment by mwest1066** [comment]
Do you mean assigning partial scores to specific answers, so that you could say that answer (a) is completely correct, but answer (b) is worth half points? Assuming this is what you mean, I think this would be a great feature!
