### ISSUE TITLE
Student's add course button not working

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#580]
From Chris Schmitz:

I have a student who can't add ECE110 as a course. Someone shared a "direct link" to homework 3 to allow him to access it. He can see it in the list, but it refuses to be added. He shared this video (I hope it is public): https://drive.google.com/file/d/0ByucyOjm8r2QVTg1cENMdDRsWVE/view

Student was using arch linux and firefox. The student confirmed he could add the course from a windows machine.

Dave couldn't reproduce the problem in docker dev or production from his CentOS firefox.

**Comment by trombonekenny** [comment]
@jakebailey can help test.

**Comment by jakebailey** [comment]
Worked for me on my Arch laptop, with `firefox 51.0.1-1`. I clicked the ESPL add course button it worked.

**Comment by mwest1066** [comment]
I'm closing this due to lack of reproducibility.

**Comment by echuber2** [comment]
Video link is dead, but I wonder if this is related to the issue with popovers. (See https://github.com/PrairieLearn/PrairieLearn/pull/1499 )
