### ISSUE TITLE
Dev: Load from disk slow, especially with tags

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#581]
From Lawrence:

Re: docker instance (not production) performance: It takes nearly a minute to load the cs241 course from disk. The last few steps take most of the time (e.g. Syncing tags from git repository to database...). I wonder if there is an easy to fix to speed this up? It would be appreciated... (e.g. are the indices declared for the docker DB?)  The cs126 course has about 200 tags, 14 assessments and 200 questions and is growing.

**Comment by angrave** [comment]
Course number typo in first sentence: s/load the cs241 course/load the cs126 course/

**Comment by mwest1066** [comment]
We are doing this in a pretty inefficient way at the moment, but it was fairly fast for my course on my machine so I never worried about optimizing it. I'll see what I can do to speed it up.

**Comment by trombonekenny** [comment]
Poke on this because Mariana and Chris have both complained to me this week that "Load from disk" is slow. Mariana said it was after a certain release and she told Matt about it.

**Comment by mwest1066** [comment]
Yeah, it's on the queue, just hasn't quite got to the top yet.

**Comment by trombonekenny** [comment]
`pl-mse304` is another repo to test against. It's load seems slower than necessary.

**Comment by jdoherty7** [comment]
Just chiming in that this improvement would be nice to have.

**Comment by trombonekenny** [comment]
Summer 2019 syncing improvements resolved this. Syncs, even with lots of tags and topics, are super fast now.
