### ISSUE TITLE
Add "how to make production PrairieLearn" files and documentation to project

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#582]
Help contributors who want to run a production environment PrairieLearn. Right now documentation and some system-level configurations are missing. i.e.

Apache and Shibboleth configurations
Syncing from github and github organization configuration
Other things?

**Comment by trombonekenny** [comment]
Ping on this, as ZJUI is asking.

**Comment by fkohrt** [comment]
I just discovered PrairieLearn and am quite excited about it! After trying a few similar tools I am delighted how easy it is to spin up a development instance. However, for this repository to be more useful to newcomers, some documentation on how to set up a production instance would be very neat.

**Comment by nwalters512** [comment]
We now have a basic guide for configuring a production instance: https://prairielearn.readthedocs.io/en/latest/running-in-production/setup/. If folks find that information is missing, we encourage them to ask on Slack or GitHub Discussions!
