### ISSUE TITLE
Multiple submissions possible for a single question_instance in Homework mode

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#583]
To reproduce:
1) Open a question within a homework assignment
2) Copy the url ***/pl/course_instance/#/question_instance/##/
3) Paste into as many new browser tabs as you like
4) Answer the question in any one browser tab and submit
5) Previously loaded browser tabs will still accept (and grade, score) submissions. All submissions (from every tab) will be listed below after submission.

If the url in (2) is reloaded in a new tab after any submission is made, it will force a new question instance (i.e., generate new numbers) with a new submission history. 

After submitting, the additional /?variant_id=## appears on the url; copying the complete url (including this variant_id) returns to the older, graded variant, but does not allow for a new submission.

**Comment by rbessick5** [comment]
See, e.g., this assessment history from TAM 251, HW 3, by user bldssrr2@illinois.edu (direct link: https://prairielearn.engr.illinois.edu/pl/course_instance/445/instructor/assessment_instance/26151 )

For each question, a single variant is generated, followed by four submission/grade submission/score question/score assignment cycles. The first submission is always garbage (zeroes for all entries), followed by the same (correct) score submitted roughly 30 seconds apart each. Total time spent from loading first question to 100% score is about 4 minutes.

**Comment by mwest1066** [comment]
Fix in ae9c6497090b457d725dc18dd07de96468a83fe2
