### ISSUE TITLE
"assessment instance is not open" in manual grading

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5835]
On some assessments in which I have used "Grade and close all instances" in the Students menu, when I open a submission in manual grading, I get an error page with "assessment instance is not open".

**Comment by jonatanschroeder** [comment]
This could be a case of students that never opened the instance question (see #1718), can you confirm if that's the case? If so, the fix in #5836 will now change this message to indicate there is no gradable submission, for clarity.

**Comment by jonatanschroeder** [comment]
Just checking, the manual grading list of submissions for an assessment question should not list such questions, so the only way to get to the manual grading page that I can think of is from the manual grading button on student's assessment log, is that where you're coming from?

**Comment by ffund** [comment]
On some of them I get "Instance question does not have a gradable submission" and on some of them I get "assessment instance is not open".

**Comment by jonatanschroeder** [comment]
Ok, I was able to reproduce it. It is exactly the same problem as #5834, but it happens when the assessment is closed. So #5836 will fix this too.
