### ISSUE TITLE
Error drawing grading function

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#584]
I wrote a new grading algorithm for FBD drawing.  The function named  mechanicsObjectsGrading.ProcessObjectsInsideEllipse is saved in pl-tam210\serverFilesCourse\ mechanicsObjectsGradingNew.js”. Everything works fine on my local machine, however, when I try to submit the problem on the live server, I get the error message: 

"mechanicsObjectsGrading.ProcessObjectsInsideEllipse is not a function"

Bug or I am doing something wrong? All my other grading functions work.

**Comment by mwest1066** [comment]
I'm waiting to hear back from Mariana and TAs as to whether this issue has been resolved.

**Comment by mwest1066** [comment]
Mariana confirmed by email that this has been resolved.
