### ISSUE TITLE
Add "fixed position" multiple choice answers

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#585]
Add the ability to force a multiple choice answer to be first or last in the list of answers (or maybe to force it to a specific index in the order), rather than being randomized. This would be useful for allowing "none of the above" answers to be forced last, or for the "True" answer to be forced first, for example.

**Comment by mwest1066** [comment]
On further thought, I'm not sure whether this actually has much utility rather than simply wording the answer as "None of the other answers". Non-randomized answer order is detrimental to exam security, so I'm hesitant to support it unless it's really needed.

**Comment by cdschmit** [comment]
This has been on the back of my mind. When I was writing MC exams for ECE110, we examined with CITL the importance and effect of the ordering of numerical answers. If and when I start mapping MC problems into PL with randomly-generated answers + distractors, I'd like to be able to order them numerically.

**Comment by trombonekenny** [comment]
My experience with MC quizzes in Blackboard and Moodle is that they may give you a toggle to randomize the answers or not. They don't give you any other ordering options on top of randomization or sequential.

**Comment by cdschmit** [comment]
I agree, fixed or random. I wouldn't expect the code to choose the order in some intelligent way...I would do that. Something like {answer/4, answer/2, answer, 2*answer, none of these}.

**Comment by mwest1066** [comment]
Fixed or random implemented with `fixed_order` option for `<pl_multiple_choice>` v3 element.
