### ISSUE TITLE
Assessment instances page: minor issues with group assessments

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5885]
The assessment instances page (Students tab) has a button for "Students only", that filters assessments listing only those assigned to students (i.e., not including staff instances). This button doesn't work for group assessments. Using this filter lists no entry at all.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/1004907/172234176-399eb801-95c1-4f4a-a6a3-f145d70db8d4.png">

Another issue in the same page: when deleting an assessment, the modal for deletion does not list the group being deleted. 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1004907/172234109-47c7dafb-d39c-4e96-b55a-0b841d6bf8cf.png">

**Comment by tanyongzhi** [comment]
Hi! I would like to tackle this issue, but I'm having trouble replicating it. I am struggling to access the homework using the "Student" role. Changing the view to "student view" via the dropdown on the upper right corner and attempting the homework still shows a Staff role in the Students tab. 

Any help would be greatly appreciated!

**Comment by jonatanschroeder** [comment]
Hi, @tanyongzhi, welcome to the team! I assume you are trying to access the homework as student to be able to enrol as a student in a local environment and attempt the assessment, is that correct? If so, there are a few possible ways to do it, but one better option is to:

1. Go to the PrairieLearn home page (https://localhost:3000/ or whatever suits your environment);
2. At the top menu, click on "Queries";
3. Select "generate_and_enroll_users.sql";
4. Type the ID of the course instance you want to add students to (this is the number that follows "`course_instance/`" in the URL) and run the query;
5. For group assessments: back to the assessment, go to the Groups tab, and select "Auto" to create random groups;
6. Back to the queries page, select "generate_assessment_instances.sql" (for individual assessments) or "generate_assessment_instances_group.sql" (for group assessments), and run the query with the appropriate assessment ID.

The sequence above should enroll a set of students (30 by default), assign them to groups, and create an assessment instance for each group. This should be enough to test your implementation of the code above.

Good luck, and feel free to ask more questions if you have any concerns.

**Comment by tanyongzhi** [comment]
> I assume you are trying to access the homework as student to be able to enrol as a student in a local environment and attempt the assessment, is that correct?

That's right! I'll give your suggestion a go, thanks for the help!

**Comment by tanyongzhi** [comment]
For the first issue, what should be the expected behavior? I think it makes sense to show all groups with at least one user with the "Student" role. So basically all the "Students Only" button will do is to filter out all groups with no students at all.

**Comment by jonatanschroeder** [comment]
> For the first issue, what should be the expected behavior? I think it makes sense to show all groups with at least one user with the "Student" role. So basically all the "Students Only" button will do is to filter out all groups with no students at all.

Yes, listing all groups with at least one user with Student role makes sense.

**Comment by tanyongzhi** [comment]
Can we close this issue?
