### ISSUE TITLE
Feedback is not shown in question.html and submission.html while exams are still open

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#589]
Two problems: (1) feedback is not passed to submission.html, and (2) feedback is not shown while an exam is still open, which is a change from PLv1.

**Comment by mwest1066** [comment]
Not entirely fixed yet.

**Comment by jakebailey** [comment]
Currently, feedback is given in answer.html for 233 only, as of version 2.2.1.
