### ISSUE TITLE
Single variant answer panel visibility

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#5914]
@ffund was in office hours today asking when students see the answer panel in single variant questions.

She would like the functionality where students can see the correct answer panel after they get the question right (or in case of a homework, after having earned all of the available points).

Something like being able to see a closed type:exam assessment, but also for homeworks.

From the Slack discussion, she uncovered issues #895 #2083 and #3191 but we weren't sure what the expected behavior was

**Comment by ffund** [comment]
Per discussion in office hours on 7/12: Matt confirms that for a Homework-type assessment, where students can keep submitting even after earning all available credit, the correct answer panel will never appear for a single variant question. He also said that it would be reasonable for the answer panel to appear after getting the question correct, so I may go ahead and implement that. 

(We also discussed an orthogonal issue: whether or not students should be prevented from submitting again, after earning all the credit and seeing the correct answer panel. IMO they should still be able to submit again; there may be multiple correct answers and maybe they want to try out others?)
