### ISSUE TITLE
Grading job page has no route for access without course instance

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#5928]
The questions page has, for each submission that includes external grading, and info button that opens a modal that contains a button linking to the corresponding grading page. If the question was opened through a course instance, the link works (`/pl/course_instance/XXX/instructor/grading_job/YYY`), but if the question was opened through a course, the link points to a 404 (`/pl/course/XXX/grading_job/YYY`). This seems to be related to a missing route in server.js for this URL pattern. 

Given the existing link to that page, it probably makes sense to either include this route, though proper authz should probably be considered when doing so (should this URL be allowed for grading jobs associated to a course instance? what permissions should be required to see it?). See:
https://github.com/PrairieLearn/PrairieLearn/blob/1f6ad256ee17a601fe6567162789bf3cbf78cc47/pages/instructorGradingJob/instructorGradingJob.js#L14-L16

**Comment by jonatanschroeder** [comment]
Current workaround is to open these questions with a course instance selected.

**Comment by echuber2** [comment]
What are the circumstances where somebody would be looking at grading jobs for a question that doesn't belong to a course instance? Instructor testing only?
