### ISSUE TITLE
Split instructorAssessment page into sub-pages

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#593]
`pages/instructorAssessment` has become much too big, making it slow to load and also very long to scroll through and find things in. We should separate it out into sub-pages like "question list", "statistics", "data downloads", "instance list", etc. To navigate between the subpages we will need some kind of sub-navbar below the top-level navbar.

**Comment by rbessick5** [comment]
This would be a good resolution to #570 as well.

**Comment by mwest1066** [comment]
Implemented in #1300
