### ISSUE TITLE
Number of points earned for all final submissions

### ISSUE THREAD

**Issue by cdschmit** [PrairieLearn/PrairieLearn#594]
Last semester, the "final submissions" csv file would have the number of points earned for each problem. This was important for two reasons, one being that the "scores" csv file was rounding, but the other because it was easier to catch/correct when PL didn't like an entry because of format issues. Now, the file looks like the "final submission" scores are reported as a binary 0/1 in the final submissions although the "scores" file looks accurate. Is there anyway to get the points-per-problem back?

**Comment by mwest1066** [comment]
I added question point/score information to `final_submissions.csv`. This hasn't been deployed to the production server yet.
