### ISSUE TITLE
Extra Credit possibility for assessments

### ISSUE THREAD

**Issue by rtfreedman** [PrairieLearn/PrairieLearn#598]
Possible extra credit for assessments would be nice to have. Suggested implementation (kind of dependent on maxPoints implementation) would be to add another flag "extraCredit" or "extraPoints" that takes a number which allows amount of extracredit over maxPoints (or, if maxPoints isn't present, the points to be considered extracredit for an exam subtracted from total points possible).

Extra credit could also be useful on a question level as well (or zone: "Extra credit zone") to specify which questions would be considered extra credit (so ec questions would go over 100% but not other questions, maybe).

**Comment by nwalters512** [comment]
The notion of "bonus points" was introduced in https://github.com/PrairieLearn/PrairieLearn/pull/4090, which I think fulfills this ask. If we're still missing some desired functionality, please open a new issue!
