### ISSUE TITLE
"History" of awarded points should show all attempts

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#6031]
Currently, the "history" of awarded points in the Homework view (on the assessment page and the question page) only includes variants where 100% credit was awarded, plus the last variant where partial credit was awarded (unless they earned 100% on the last attempt...)

The "history" should show all attempted variants, including zero-credit and partial-credit attempts, because:

* the current behavior is unintuitive and undocumented (as far as I can tell)
* greater transparency for current and future non-trivial question grading schemes
* will allow the badges in the "history" section to be used for #5763 (then students will be able to e.g. click on an attempt where they earned zero credit to review it with a TA)
* provides some slight motivation to make a serious attempt on the first try, instead of submitting random values and clicking through to see a solved example (students will want to have that "all green" assessment page)
* students will see if they have many failed attempts at a question. This could encourage them to seek help or go review their notes before re-attempting, instead of trying to brute-force their way to a correct answer.
* when students complain to their instructor that "I tried this question a million times and I still can't get it" they will be able to give a more precise estimate of the number of failed attempts (it was actually only 80 attempts, etc.)

Disadvantages: 

* it would be discouraging to see lots of failed attempts on the assessment page

**Comment by ffund** [comment]
My alternative proposal if ^ seems too discouraging:

- rename "History" to "Points History" on assessment and question page
- on question page only, in the points box on the right side, add an "Attempt History" list under "Points History"

**Comment by ffund** [comment]
Following some discussion with Matt, we decided that on both the assessment page and the question page we should show all of the attempts (*instead* of the current "awarded points" list, not in addition to.)

To avoid being too discouraging, we will use the non-judgmental "secondary" badge color instead of the success/danger/warning colors:

![image](https://user-images.githubusercontent.com/2316553/182611115-bb68a177-eafe-4fa8-93e4-1161d81b3838.png)

Also, if there is an unreasonable number of attempts, we should show a smaller number of badges with a `...` or equivalent to reveal more.

**Comment by mwest1066** [comment]
> To avoid being too discouraging, we will use the non-judgmental "secondary" badge color instead of the success/danger/warning colors.

I love this idea!
