### ISSUE TITLE
Students can enter the same wrong answer twice (open-ended issue)

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#608]
A TAM 212 student posted the following regarding his Quiz:

> I took quiz two today and on one of the problems I got it wrong once, then I changed the answer and saved it, but after I saved it I realized I made a mistake so I changed it back to the original incorrect answer and moved on so I wouldn't run out of time. After I finished the next question I submitted my answers thinking that PrairieLearn would register that I had already put that incorrect answer and it wouldn't score it again, but it scored it incorrect again causing me to lose another two points.  So I lost credit twice for the same incorrect answer.
> 
> I was worried that it would mark it as incorrect again, but I couldn't really avoid this. I had already saved a different answer that I knew was incorrect so I couldn't check my answer on a different question without getting it wrong again. I could have either spent more time on the same question and possibly not had time for other questions, or I could answered the rest of the questions and hoped that they were all correct and come back and hope I had enough time to find a different answer for the first question.

At present, I'm not sure what we could do to handle this situation.

**Comment by rbessick5** [comment]
I can think of a few possible remedies for the situation above, but all seem to have drawbacks:

1) Refuse submissions which are identical to a previous submission. This would be done as part of the data-validation of a submission (which doesn't exist yet), and checked against all previous submissions. Of course, if a student enters the "same" answer, but it isn't an identical string, this check would fail.

2) Provide a "Grade This Question" button on individual questions, so a student can leave a "submitted, not graded" answer on one problem while submitting a different one. This has been suggested before, with the drawback that it will tempt students to iterate on a single question, without ever moving on.

3) Provide a "Clear current submission" button that puts the question in and 'unanswered' state so grading won't affect it, or creates a submission that can't be graded as either correct or incorrect. This seems like it wouldn't play nice with the DB schema for submissions.

4) Provide a "Don't grade this question" check-box that a student could use to temporarily exempt a question from grading. This could create weirdness when interpreting the time-stamps of submissions and grading events.

Any thoughts on how else we could address this?

**Comment by mwest1066** [comment]
We'll handle this case eventually with #258, but I'm closing this as WONT-FIX for now.
