### ISSUE TITLE
Editing a course instance CIID fails to sync with Git if "master" branch has been renamed

### ISSUE THREAD

**Issue by nealterrell** [PrairieLearn/PrairieLearn#6161]
We renamed the "master" branch to "main" on our Github repository. Syncing files in general works fine (the sync sequence runs `git reset --hard origin/main`), but attempting to change a course instance CIID using the button on `course_instance/.../settings` page errors on sync step 3, when the job tries to run `git reset --hard origin/master`.

EDIT: same error occurs when trying to create a new course instance using the button on the "Course instances" page.

**Comment by echuber2** [comment]
I think this was the issue resolved here: https://github.com/PrairieLearn/PrairieLearn/pull/6146

@mwest1066 Maybe this just hasn't been deployed on Neal's server yet?

**Comment by nwalters512** [comment]
Yeah, this has been fixed and deployed to all our hosted servers (https://github.com/PrairieLearn/PrairieLearn/discussions/6159). @nealterrell you'll need to prompt whoever maintains your instance to upgrade.
