### ISSUE TITLE
Manually graded workspace not saving

### ISSUE THREAD

**Issue by justindr21** [PrairieLearn/PrairieLearn#6173]
I've been trying to develop a question locally with a jupyter notebook workspace that can be manually graded by instructors. Pressing the save button does not seem to save the changes made as no changes can be seen in the submitted answers window when I preview the answer. Could this possibly be an issue or might I be setting something up wrong for this? I am doing this locally, with the default PL jupyter notebook image but I have added a package to it manually as per the discussion [here](https://github.com/PrairieLearn/PrairieLearn/discussions/6044#discussioncomment-3282054). If more context is necessary, please let me know. Thanks!

**Comment by jonatanschroeder** [comment]
Make sure you set up your workspace to include the files you want to be submitted (`gradedFiles` in https://prairielearn.readthedocs.io/en/latest/workspaces/#infojson), as only those files will be considered part of the solution. Also, make sure you include a `pl-file-preview` element in your submission panel, to see which files were submitted.

**Comment by jonatanschroeder** [comment]
@justindr21 could you confirm the message above solved your issue, so that we can close it?

**Comment by justindr21** [comment]
Yes, thanks for letting know. The solution seemed to be a permission issue on the jupyter notebook image. The discussion on it is on slack but I am not sure if I can link slack here.
