### ISSUE TITLE
pl-matching using answer strings directly

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#6183]
The pl-matching element gives answers an alphabetical label (a, b, c, d) and then uses that to match the answer to the original. That's a cognitive jump to skim the answers, identify that the correct answer is (for example) **c.**, and then match the correct option to the letter **c.**

For textual answers, could we just have the answer in the pulldown box and skip the **a. b. c. d.** decoding? Maybe a setting to toggle this behavior?

For example, in the image below, couldn't we just have Sorry!, Chess, Monopoly, etc. as drop down answers?

![image](https://user-images.githubusercontent.com/10765199/187565060-24eb0d47-270f-45f7-b2f4-1abf5d239249.png)

**Comment by jonatanschroeder** [comment]
This is possible, just set `counter-type` to `full-text`. https://prairielearn.readthedocs.io/en/latest/elements/#customizations_8

**Comment by trombonekenny** [comment]
Perfect, thanks for the pointer. I'm not sure how I missed that; maybe the RTD formatting.
