### ISSUE TITLE
sqldb parameter in SQL comments errors

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#620]
If you give an sqldb call a parameter that only lives in a comment inside the SQL, i.e.

`/* WHERE age = $age */`

it errors.

**Comment by mwest1066** [comment]
This only errors if you don't use `$age` elsewhere in the actual query, correct?

I'm tempted to make this a WONT-FIX, because fixing it means that `sqldb` will need to actually parse the SQL template string enough to find comments. How important is this functionality?

**Comment by mwest1066** [comment]
Closing as wont-fix because it's a pain to fix :-) (and it doesn't seem very critical). Please re-open if it's more serious than I'm understanding.
