### ISSUE TITLE
Add flag to hide "Correct answer" panel on questions

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#623]
Externally-graded (read: coding) questions don't have a correct answer in the sense that a multiple choice or true/false question does. Therefore, we should have the ability to hide the "Correct answer" panel on questions that don't technically have one.

**Comment by echuber2** [comment]
Some instructors would like to hide what the correct answer would have been in general, too. For example, it's often the case that the order in which students attempt problems can provide clues to how to solve other problems, which is more of a metagame than may be desired.

Some element types seem to have an attribute to control this already that affects what the answer pane displays. At a minimum, the existing element types could be revised to always have such an attribute; if the answer panel itself isn't hidden, then there is always the ability to replace the correct answer panel contents with "(Hidden)" (etc.).

**Comment by nicknytko** [comment]
@echuber2 is this being worked on?

**Comment by echuber2** [comment]
@nicknytko Not by me, currently.
