### ISSUE TITLE
Handle partially-correct responses for externally graded questions

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#627]
With the current grading model, it's assumed that all questions are binary right/wrong. With externally graded questions, the obvious use case is to autograde code, where we'll want to assign points based on the score.

Things to consider:
* How does this work with max points? Is `points` simply `maxPoints * score`?
* How does this work with homework questions, where amount of points earned increases with each successive correct answer?

**Comment by mwest1066** [comment]
Implemented in 60a0161d6d0349d696d666b9e8e7c9fe7bce905d and 9b11996babef905420bec1679adf669f6890e123
