### ISSUE TITLE
Use buttons instead of adding tabindex=0 to elements

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6272]
Grepping for `tabindex="0"` reveals a number of places where we're currently misusing non-interactive elements. While we have tried to improve accessibility by adding `role="button"` in many places, it's still best practice to just use a button if you want a button.

**Comment by SincerelyBrittany** [comment]
Hi @nwalters512 can I work on this issue?

**Comment by nwalters512** [comment]
Hey @SincerelyBrittany, it'd be great to have your help on this! Accessibility is hugely important, so this would have a great impact. It looks like you might be new here, so let me know if you have any questions about getting your dev environment set up, or anything else!

**Comment by ighmaZ** [comment]
Hi @nwalters512 ! i wanna work on this issue

**Comment by SincerelyBrittany** [comment]
> Hey @SincerelyBrittany, it'd be great to have your help on this! Accessibility is hugely important, so this would have a great impact. It looks like you might be new here, so let me know if you have any questions about getting your dev environment set up, or anything else!

Yes I am new here 🙂, I would love a quick guide on how to get my dev environment set up properly. Also, I wanted to confirm that I am updating all instances of tabindex="0" with a role of button to a button correct? For example: [the workspace](https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/workspace/workspace.ejs#L99) and the [instructorCourseAdminSettings](https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ejs#L59) should both be updated, correct?

**Comment by nwalters512** [comment]
@SincerelyBrittany great! Take a look at https://prairielearn.readthedocs.io/en/latest/installing/, that should get you started.

> Also, I wanted to confirm that I am updating all instances of tabindex="0" with a role of button to a button correct? For example: [the workspace](https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/workspace/workspace.ejs#L99) and the [instructorCourseAdminSettings](https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ejs#L59) should both be updated, correct?

Great question. Both need to be updated, but in different ways. The former is being used as a button, so that should indeed be switched to `<button>`. However, the latter is actually used as a link; note the presence of the `href` attribute. In that case, we should keep it as an `<a>`, but remove the `tabindex` and `role` attributes, as those are unnecessary or flat-out incorrect to have there.

@ighmaZ I've already assigned this issue to Brittany. If you'd like to contribute, there are many more issues to pick from!

**Comment by ighmaZ** [comment]
@nwalters512  sure mate!

**Comment by jonatanschroeder** [comment]
Just make sure that popovers with trigger set to focus are properly addressed: https://getbootstrap.com/docs/4.1/components/popovers/#dismiss-on-next-click. For those cases keeping an `a` is probably the easiest approach. Replacing the popover with a tooltip or modal may be a better option in some cases, though that would probably be a bit more complicated.

**Comment by echuber2** [comment]
In the past, we had some bugs with popovers not working correctly on touch devices. Modals seem more foolproof.

**Comment by nwalters512** [comment]
We should switch to the `click` trigger for popovers. We've done this in PrairieTest and this works reliably with plain `<button>`. This will require some extra JS to correctly dismiss popovers when new ones are opened, but we've already largely proved that out in PT.
