### ISSUE TITLE
Save external grading start and end times

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#629]
They're currently being returned from the external grader, but we don't store them in the database. For sake of having lots of good data, those should be tracked.

Currently:
* start time = time at which the grading script begins
* end time = last known time before we have to finalize a json blob to upload and report as a result

**Comment by mwest1066** [comment]
Implemented by @nwalters512 in aa9647d79286120b7f102eb2e610dd462b6d3f32
