### ISSUE TITLE
Workspace runs before migrations, may start as unhealthy

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6329]
When starting a Docker container, it starts two different servers in parallel: the workspace host, and the regular PL server. When there are pending migrations, the PL server will identify those migrations and run them. However, depending on which migrations and code exist, (e.g., if there are sprocs that use tables that were created by a migration), the workspace host will start before the migration runs, so it may fail to run as expected, and will start in an unhealthy state. This is the output that I get when running PL with branch `mg-rubrics` (#6271) while the Docker image is on the current `master` branch:

```
Starting PrairieLearn...
yarn run v1.22.19
$ /PrairieLearn/node_modules/.bin/nodemon -L server.js
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,json,sql
[nodemon] starting `node server.js`
error: Error initializing workspace host: type "rubrics" does not exist {"code":"42704","data":{"sql":"CREATE FUNCTION\n    rubric_gradings_insert(\n        IN rubric_id BIGINT,\n        IN adjust_points DOUBLE PRECISION,\n        IN applied_rubric_items JSONB,\n        INOUT computed_points DOUBLE PRECISION,\n        OUT rubric_grading_id BIGINT\n    )\nAS $$\nDECLARE\n    rubric rubrics;\nBEGIN\n    SELECT * INTO rubric FROM rubrics AS r WHERE r.id = rubric_id;\n\n    IF NOT FOUND THEN\n        RAISE EXCEPTION 'Could not find rubric %d.', rubric_id;\n    END IF;\n\n    IF computed_points IS NULL THEN\n        SELECT LEAST(GREATEST(rubric.starting_points + SUM(COALESCE(ari.points, ri.points)) + COALESCE(adjust_points, 0),\n                              rubric.min_points), rubric.max_points)\n        INTO computed_points\n        FROM JSONB_TO_RECORDSET(applied_rubric_items) AS ari(rubric_item_id BIGINT, points DOUBLE PRECISION, note TEXT)\n             JOIN rubric_items AS ri ON (ri.id = ari.rubric_item_id);\n    END IF;\n\n    INSERT INTO rubric_gradings\n        (rubric_id, computed_points, adjust_points)\n    VALUES\n        (rubric_id, computed_points, adjust_points)\n    RETURNING id INTO rubric_grading_id;\n\n    INSERT INTO rubric_grading_items\n        (rubric_grading_id, rubric_item_id, points, note)\n    SELECT\n        rubric_grading_id, ari.rubric_item_id, COALESCE(ari.points, ri.points), ari.note\n    FROM JSONB_TO_RECORDSET(applied_rubric_items) AS ari(rubric_item_id BIGINT, points DOUBLE PRECISION, note TEXT)\n         JOIN rubric_items AS ri ON (ri.id = ari.rubric_item_id);\nEND;\n$$ LANGUAGE plpgsql VOLATILE;\n","sqlError":{"code":"42704","file":"parse_type.c","length":95,"line":"275","message":"type \"rubrics\" does not exist","name":"error","position":"272","routine":"typenameType","severity":"ERROR"},"sqlFile":"rubric_gradings_insert.sql","sqlParams":[]},"file":"parse_type.c","length":95,"line":"275","name":"error","position":"272","routine":"typenameType","severity":"ERROR","stack":"Async Stacktrace:\n    at /PrairieLearn/workspace_host/interface.js:203:13\n    at /PrairieLearn/sprocs/index.js:183:11\n    at PostgresPool.<anonymous> (/PrairieLearn/sprocs/index.js:177:15)\n\nerror: type \"rubrics\" does not exist\n    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"}
warn: Marked self as unhealthy: error: type "rubrics" does not exist
info: Running migration 20220905173159__rubrics__create.sql
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
```
This causes the local instance to have issues with workspaces, which are unable to run. It will also cause some weird issues like the terminal eventually printing messages that `_pushAllRunningContainersToS3` isn't running, so the small timer that logs this error is active, but the  timer that actually pushes the containers is not.

I realize this is a pretty niche issue, but just reporting in case there is some way to address it.

**Comment by nwalters512** [comment]
I think the right way to handle this is to run the workspace server from inside the main PL process when in dev mode. AFAIK there's no technical reason that we need to have it running in a separate process; that's just how it happened to be implemented.

In production, we always take care to apply any pending migrations before deploying new workspace hosts.

**Comment by jonatanschroeder** [comment]
One side-effect that I don't know if it will be an issue is that restarting the server will also restart the workspace host. Considering that the server is restarted often in a dev environment, would that be an issue? In particular, would restarting the workspace host also restart (or otherwise affect) running workspaces? Again, I know very little of how workspaces work in the background, so this may be a non-issue.

**Comment by nwalters512** [comment]
That very well might be an issue, yeah. Ideally our code could reconnect to running containers when it boots back up, but I'm not sure if it does. If it doesn't already, that'd be great to add as part of this.

@mwest1066 unfortunately I suspect that there will be a non-trivial amount of refactoring involved here, all the logic is currently implemented at the top level of the file 😭

**Comment by mwest1066** [comment]
Yeah, this is going to involve some actual work. I'm not sure it's high priority right now.

@jonatanschroeder as a workaround for development, in the past I've started everything manually (start PL first, then start the workspace host).

**Comment by jonatanschroeder** [comment]
> @jonatanschroeder as a workaround for development, in the past I've started everything manually (start PL first, then start the workspace host).

Yeah, workaround for me now is to start PL in a branch without migrations then switch...
