### ISSUE TITLE
External Grading: /grade/results doesn't exist when binding volume

### ISSUE THREAD

**Issue by mfbutner** [PrairieLearn/PrairieLearn#6340]
With the external graders all of the directories specified in the documentation (/grade/tests, /grade/student, etc.) are already created. The sole exception is /grade/results which took me a while to figure out. I tried to workaround this problem by creating it in my DockerFile but since a bind mount is created to /grade and /grade/results isn't in the directory being mounted from the /grade/results created in my DockerFile was destroyed. 

This then means in my grading script I have to ensure that I create this directory before attempting to write to /grade/results/results.json. This isn't hard, just a little annoying to have to have.

I propose adding an empty results directory in the grade directory that you mount from so that others aren't caught by this like I was.

**Comment by nwalters512** [comment]
I'm afraid we probably can't do this in a backwards-compatible way. If someone was using `mkdir` without the `-p` flag to create that directory, their grading script would now fail unexpectedly. Do you have any ideas for we could do this in such a way that all existing grading scripts would continue to work?

**Comment by mfbutner** [comment]
@nwalters512 The only ideas I have a hacky and terrible and probably not guaranteed to work in all situations but basically amount to building a new image from the provided image that replaces `mkdir` with `mkdir -p`. It's so bad that I can't seriously recommend doing it. 

I guess if we ever go to a new version of PL where we are allowed to make breaking changes, it would be something to consider doing there.

**Comment by nwalters512** [comment]
Yeah, for better or worse we're committed to backwards compatibility for most user-provided code, including this. Any hacky solutions wouldn't account for folks creating the directory with languages other than shell scripts.

I'm going to close this to keep our issues list actionable. If you feel the documentation around this could be improved, I'd encourage you to submit a PR!
