### ISSUE TITLE
Feature request: hovering over LaTeX should display the source code

### ISSUE THREAD

**Issue by BenjaminCosman** [PrairieLearn/PrairieLearn#6345]
I'd like it to be easier for students to use LaTeX in their text answers. Often a question uses a symbol they don't know the TeX code for; it would be nice if they could just mouse over the symbol and see the code. It would be even nicer if there were also a quick way to _copy_ the code (e.g. by select-copy, right-click, etc). This feature could be toggleable if it is not universally desirable.

**Comment by nwalters512** [comment]
We use [MathJax](https://www.mathjax.org) to render LaTeX. If you can find some native or third-party solution for doing this, I think we'd be happy to add it!

**Comment by trombonekenny** [comment]
Or perhaps an add-on to the [Ace Editor](https://ace.c9.io/) that makes creating MathJax code easier?

**Comment by nwalters512** [comment]
@BenjaminCosman great find! We were just missing a tiny bit of config - I opened https://github.com/PrairieLearn/PrairieLearn/issues/6345 to add it.
