### ISSUE TITLE
Feature Request: line breaks in `pl-python-variable` for large dictionaries

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6347]
The `pl-python-variable` is great for displaying python variable contents if the amount of material shown is small. However, if there is lots of data, say for a web API response, then it quickly becomes an unfeasible view.

The goal would be to allow `pl-python-variable` to go from: 

```python
{ "key1": "value1",  "key2": "value2",  "key3": "value3"}
```

To something along the lines of: 

```python
{ 
 "key1": "value1", 
 "key2": "value2",  
 "key3": "value3"
}
```

The temporary solution proposed by @echuber2 on [Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1663615555186629?thread_ts=1663551225.140169&cid=C266KEH9A):

```python
import json
o = {'name': 'bob'}
json.dumps(o, indent=1)
'{\n "name": "bob"\n}'
```

**Comment by echuber2** [comment]
Until an option is added to `pl-python-variable` to do this automatically, you can use a drop-in wrapper around basic types like this:

```python3
#!/usr/bin/env python3

import json

class IndentWrapper:
    def __init__(self, obj, indent=1):
        self.obj = obj
        self.indent = indent
    def __repr__(self):
        try:
            return json.dumps(self.obj, indent=self.indent)
        except TypeError:
            return repr(self.obj)

o = {'name': 'bob'}
w = IndentWrapper(o)
# Now display variable w
```

If you try to wrap something that isn't JSON serializable like a set, then the exception handler will use the default repr.
