### ISSUE TITLE
Feature Request: Vim keybinds for editor

### ISSUE THREAD

**Issue by aadityadhruv** [PrairieLearn/PrairieLearn#6355]
The current text editor is very simple. Are there any plans to improve the editor, and support different keybinds, such as Vim, Emacs etc?

**Comment by nwalters512** [comment]
Which editor are you referring to, a VS Code workspace or the text editor that appears inline in a question? A screenshot would be helpful.

**Comment by aadityadhruv** [comment]
Sorry about that. I mean the default text editor, such as this one:

![image](https://user-images.githubusercontent.com/67942447/191614988-52f98340-35fc-429e-afdc-c04add412210.png)

**Comment by nwalters512** [comment]
Ah! It looks like Ace does natively support Ace and Emacs keyboard bindings. For instance, we could stick `this.editor.setKeyboardHandler('ace/keyboard/vim');` somewhere after this line

https://github.com/PrairieLearn/PrairieLearn/blob/979a92eaef56ab88380c22aba90540323d7c4672/elements/pl-file-editor/pl-file-editor.js#L18

Of course, we'd want this to be configurable, and we'd probably want to remember this setting via local storage.

We probably won't get to this for a while, but feel free to open a PR adding this - we'd be happy to merge it!

**Comment by aadityadhruv** [comment]
Thank you! I'll probably open a PR with this soon!

**Comment by aadityadhruv** [comment]
Where would be a good option to add an option to let the user change the keybindings?

**Comment by echuber2** [comment]
There is a user settings page that doesn't have much on it currently:
https://www.prairielearn.org/pl/settings
https://github.com/PrairieLearn/PrairieLearn/tree/master/pages/userSettings

On the other hand, maybe it would make sense for the setting to be part of a header decoration on the text editor itself. Or maybe it could be in both places.

**Comment by nwalters512** [comment]
+1 to putting this in the element header itself. I'd recommend persisting the setting with [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage); that's much simpler to implement than inventing a way for elements to contribute to user settings that are persistent on the server (there is no prior art for that).

**Comment by louisunlimited** [comment]
@aadityadhruv If you are still working on this, feel free to shoot me an email or comment down my thread, happy to work with you! #6460

**Comment by aadityadhruv** [comment]
@nwalters512 Thanks for letting me know! @louisunlimited Sure I would love to help you! What can I work on? Looks like you've got some stuff working already,

**Comment by louisunlimited** [comment]
Yes, you can either look at the new pr here or there's a branch called FileEditor that you can find in my fork.

**Comment by nwalters512** [comment]
@aadityadhruv #6476 implements the foundational bits for configuring and persisting settings for `<pl-file-editor>`. It should be relatively straightforward to implement support for configuring different keybindings on top of that!

**Comment by simonCS124** [comment]
Hi there, I found a bug in my code when switching from other keybindings to the "default" keybinding. The keybinding remains the same as the previous one even after clicking the "save changes" button. I have to say I am unsure how to re-enable the default ace editor keybindings (I believe we can pass in "null" inside the setKeyboardHandler method).

**Comment by nwalters512** [comment]
@simonCS124 since this is related to your specific code changes, please continue this discussion as a comment on your PR.

**Comment by simonCS124** [comment]
> @simonCS124 since this is related to your specific code changes, please continue this discussion as a comment on your PR.

understood

**Comment by nwalters512** [comment]
As of #6666, Vim keybindings are now available!
