### ISSUE TITLE
Sync course failed when copying a question-- TypeError: Cannot read properties of undefined (reading 'assessments')

### ISSUE THREAD

**Issue by kzj52** [PrairieLearn/PrairieLearn#6361]
Hello, I got one issue from course ME330, Fall 2022. When I tried to copy one question to modified into a new question, the error message pops up: 
      **Sync course failed with this result:
      TypeError: Cannot read properties of undefined (reading 'assessments')
      Please go back and try again.**

The webpage is https://www.prairielearn.org/pl/course_instance/129462/instructor/edit_error/317783
![image](https://user-images.githubusercontent.com/58677659/191878521-d2b4a4a5-49d8-4846-9ce8-1c25f3d4c695.png)

**Comment by nwalters512** [comment]
For posterity, Wayne reported this on Slack too: https://prairielearn.slack.com/archives/C266KEH9A/p1663962097478559
