### ISSUE TITLE
Add assessment log entry when exam timer expires

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6368]
At the moment PL shows the "end of exam" as the last time the student took an action (e.g., viewed a page). The assessment log does not show when the exam time expired, and thus it can look like a student got less than the full time for the exam. To fix this, we should add a log entry for timer expiration.

**Comment by jonatanschroeder** [comment]
Given that instructors can extend the time limit, I imagine this would be an additional entry for exam open/end time change events, based on the time expiration of that event, but only if the assessment is open at the time of that event and no time changes happen in between. It may occasionally happen more than once if an instructor reopens an assessment after it was closed due to expiration time.

**Comment by jonatanschroeder** [comment]
Small issue here: when an assessment instance is created with a time limit, that limit is never set in any logs. Which means, if the time limit is ever changed by the instructor, there is currently no reliable way to obtain the original time limit. My suggestion: add a new entry in `assessment_state_logs` when the assessment instance is created. This has the advantage that the value is never lost, with the caveat that it would only affect future assessments.

Another option is to use the assessment's time limit if there is no record of `assessment_state_logs` set before that time limit, which is a good heuristic for most cases. Of course this isn't foolproof, as it wouldn't capture time expiry events for assessment instances that were extended (and potentially re-opened) by an instructor after expiry, though these events are (I believe) relatively rare. Of course nothing stops us from doing both the new log entry and this heuristic, which would limit the missing events to assessment instances created before this is deployed.

@mwest1066 @nwalters512 thoughts?

**Comment by nwalters512** [comment]
After looking at #6369 and seeing your description of how looking at the instance's time limit isn't foolproof, I'm inclined to go the route of adding a new log and _not_ inspecting the current assessment state at all. I think showing no information is better than showing potentially misleading or inaccurate information in the logs.

FWIW, over in PT we frequently add new types of audit log without worrying about backfilling historical data, and I think that's also the correct thing to do here.
