### ISSUE TITLE
Persist workspace container logs for debugging

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6374]
It's currently difficult to debug issues with workspace containers after the fact, as we don't have any way to retrieve logs from containers that no longer exist. To improve our ability to debug, we should persist workspace logs somewhere. A few ideas:

- Log to CloudWatch streams, one per workspace/version combo. Docker actually has native support for this, and it works pretty much automatically when running on EC2 (which we are): https://docs.docker.com/config/containers/logging/awslogs/
- Dump logs to S3 before we shut down a container; we can use the Docker API to get all logs.

I think CloudWatch is my preferred option here. Because it's built into Docker, we don't have to think about manually flushing logs if a container dies unexpectedly (or deliberately when we will it). It's probably more expensive than S3, but if we set an appropriate retention policy (say, 7 days), we should be able to keep costs relatively low in the long term. Note that the majority of CloudWatch pricing comes from ingestion ($0.50/GB), whereas storage is only slightly more expensive than S3 ($0.03/GB to store, vs $0.023/GB for S3).

**Comment by nwalters512** [comment]
@mwest1066 I'd like to get your thoughts here before I start working on this!

**Comment by mwest1066** [comment]
I'm nervous about the cost of CloudWatch for this. Do you have any idea about the log volume that each workspace session would generate? Also, could some course's custom workspace image cause a lot of logs to be created?

**Comment by nwalters512** [comment]
> Do you have any idea about the log volume that each workspace session would generate?

Looking at a random Jupyter workspace in production, it's produced about 100K of logs in the hour that it's been running. I don't have any idea if this is representative of the average workspace.

> Could some course's custom workspace image cause a lot of logs to be created?

I think unfortunately they could, and unfortunately there don't seem to be any way to configure the `awslogs` driver to e.g. only upload the first 10MB from a given contianer.

I guess S3 is the way to go? I'm thinking about the best way to handle that. Thinking about that more, I really don't think we should only flush when a container dies in case we need to debug in real time. Maybe flush the last minute's worth of logs every minute to a new file named according to the current time? If we're worried about a single workspace potentially producing gigabytes of logs, we could also track how many bytes we've uploaded per container and just drop anything past a certain threshold.

**Comment by mwest1066** [comment]
> I guess S3 is the way to go? I'm thinking about the best way to handle that. Thinking about that more, I really don't think we should only flush when a container dies in case we need to debug in real time. Maybe flush the last minute's worth of logs every minute to a new file named according to the current time? If we're worried about a single workspace potentially producing gigabytes of logs, we could also track how many bytes we've uploaded per container and just drop anything past a certain threshold.

This sounds like a good plan. I agree that being able to rate-limit this feels important. Rather than always flushing every minute to a new file, I wonder whether we could have a command we could trigger to flush a workspace log and start on a new file? I'm thinking that the log files would then have names like `<workspace-id>-part<n>` and our "log viewer" would need to pull all the parts and reconstruct the full log.
