### ISSUE TITLE
Force CI to use same python version as servers

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#6447]
Right now the CI is using python 3.10, but there are servers with versions as old as 3.8. 

![image](https://user-images.githubusercontent.com/25016959/193852797-1f6025c3-9f78-42e2-a6e4-34158c61adb5.png)

This has caused problems in the past with type annotations that shouldn't have been allowed getting through CI and causing problems.

It could cause other problems too, as we know python is not the best ever at maintaining backward compatibility. 

I think we should make sure CI runs on the same version as the servers. 

related discussion: https://github.com/PrairieLearn/PrairieLearn/pull/6334#discussion_r986976383

**Comment by mwest1066** [comment]
But isn't this the version of python on the host, not the version inside the container where the tests are actually running (and where we have 3.8)?

**Comment by SethPoulsen** [comment]
No, I really think the docker container is running 3.10:

```sh
seth@seth:$ docker exec -it mypl python --version
Python 3.10.6
```

**Comment by mwest1066** [comment]
Yep, I see this now. I think that https://github.com/PrairieLearn/PrairieLearn/blob/8aa64dc4fba864027b17c15bd3009226ef2753cf/images/plbase/plbase-install.sh#L62 just installs and activates the "current" version of python. I guess we'll need to modify this somehow to tell it to install a specific python version (3.8 in our case)?

**Comment by SethPoulsen** [comment]
Yep, or 3.11 if we want to solve this at the same time as https://github.com/PrairieLearn/PrairieLearn/issues/6536

**Comment by echuber2** [comment]
Would it suffice to follow the line Matt indicated with:
```bash
conda install python=3.8
```
I think this changes the base version so if it succeeds, it might be the simplest. Otherwise you might need to use `conda create` to install 3.8 in an environment and then `conda activate` in various other places to make sure it's used.

**Comment by SethPoulsen** [comment]
sounds good to me, if it works

**Comment by eliotwrobson** [comment]
So based on the discussion above, I actually tried this and ran into some issues. Basically, I think that even though conda gets used to install some packages, all of the python is being executed by the `python3` command, and I think it's using the system version of python to do this (instead of a virtual environment). In other words, the version of python being used to run everything is tied to the OS used by the container.

However, since the Python tests only need to run on an environment that has 3.8 (the issue of setting the Python version in the published docker image is really separate), I think there's an easier way of doing this by setting a separate workflow.

**Comment by SethPoulsen** [comment]
huh, interesting. I thought to use conda at all you had to be using the python version in the environment it creates.

I'm not sure I understand the last part of your comment. Did the stuff you tried end up working, or no?

**Comment by eliotwrobson** [comment]
@SethPoulsen so installing conda will let you set up virtual environments, but these live separately from the core python installation that your system uses to run (and you can still install packages on that core installation with pip, which is the installation command the container uses). As far as I can tell, the PL application doesn't set up a virtual environment with conda to execute everything.

The stuff I tried didn't end up working, but I discussed with @nwalters512 and apparently the live PL will move to executing all Python code within the prairielearn docker container itself, so this issue of version discrepancy will go away anyway.

**Comment by nwalters512** [comment]
After the work done over winter break, the US servers are now running all question code in the `prairielearn/prairielearn` docker image. I'm going to keep this open for the time being until we can make the same changes on our remaining servers.

**Comment by eliotwrobson** [comment]
@nwalters512 wasn't this resolved a little while ago?

**Comment by nwalters512** [comment]
Yep - all question now runs inside the official container!
