### ISSUE TITLE
Error: Another user is already syncing or modifying the course:

### ISSUE THREAD

**Issue by yuliaUU** [PrairieLearn/PrairieLearn#6454]
I cant seem to finds a way to resolve the following issue after pressing Pull from remote Git Repository:
![image](https://user-images.githubusercontent.com/54612866/194199515-6a67fe43-0dc5-4a0f-ada0-c04e219cd9f9.png)

**Comment by nwalters512** [comment]
Hi @yuliaUU, I've manually released the lock. It appears as though AWS changed the configuration of our database such that our locks, which would normally be released after 10 minutes of inactivity, now take 24 hours to be released. We'll get that patched up so this doesn't happen again!

**Comment by GSathish** [comment]
@nwalters512 I am having a similar problem. Here is the error message:

```
Did not acquire lock coursedir:/data1/courses/pl-ubc-cpen221
Error: Another user is already syncing or modifying the course: /data1/courses/pl-ubc-cpen221
Error: Another user is already syncing or modifying the course: /data1/courses/pl-ubc-cpen221
    at Object.<anonymous> (/srv/sysconf/ca/main/revisions/23124882069eb8286ba9559b359cbb14257e9601/sync/syncFromDisk.js:130:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by GSathish** [comment]
@nwalters512 I would like to make a small question change before a quiz starts at 4pm (in 2 hours) so this feels a bit urgent. Sorry about the rush!

**Comment by GSathish** [comment]
Thanks @nwalters512, for the quick fix

**Comment by nwalters512** [comment]
@GSathish thanks for reporting! If something is urgent, please reach out on the PrairieLearn Slack - GitHub isn't a good forum for real-time support.
