### ISSUE TITLE
Calendar view to aggregate assignments across courses

### ISSUE THREAD

**Issue by louisunlimited** [PrairieLearn/PrairieLearn#6459]
Currently, I found it hard to navigate between all my PL courses looking for assignments and deadlines. I was wondering if a calendar / todo list view can be added to PL to display all 'due's in one page? I would like to try a pr if this is not on your dev calendar anytime soon.

**Comment by nwalters512** [comment]
This is actually one of the oldest open issues for PrairieLearn: #152. I'm going to close this as a duplicate; feel free to add any specific thoughts or requests for this to that issue! We'd welcome a PR, but we'd encourage you to drop by the PL Slack to talk over features and implementation before you start diving into code.
