### ISSUE TITLE
Value of max_points is not reported on instructor view of assessment

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#646]
This is useful when, e.g., uploading to Compass if we want to convert score (percentage) into raw points before uploading (since we want to weight HW assignments proportionally, rather than equally).

It could be included in the [Assessment]: Questions panel, since that is where the individual question base points and max points are displayed.

I can currently get this value by switching to Student View and opening the assessment, so it is not urgent.

**Comment by mwest1066** [comment]
Do you mean the `max_points` for the assessment? Mean that if a student got 40/50 points (giving 80%), then we are talking about the "50" value here?

If so, that is listed in the CSV file called something like `TAM_212_Sp17_HW1_instances.csv` which is linked at the top of the "Assessment instances" panel. I've also just added a link to this CSV file in the Downloads panel to make it clearer that this is available (this change is not yet live).

If you are talking about something else or want a different/easier way to get this info then let me know.

**Comment by rbessick5** [comment]
Yes, I'm looking for exactly `max_points` for the assessment.

I may not be importing to Compass most efficiently -- I usually download the `*_scores_by_username.csv` file, then convert percentages to points in Excel via `score*max_points/100` before uploading to Compass. It's because we average the HW proportionally (so we want to know point values). When I import quizzes (which are weighted equally), I can just use percentages.

For my use case, I guess an extra `*_points_by_username.csv` download would be the file I really want, so maybe that's a more accurate enhancement to request.

**Comment by mwest1066** [comment]
I added `*_points_by_username.csv` just now, which will go live in the next deploy.
