### ISSUE TITLE
Feature Request: Customize PLFileEditor

### ISSUE THREAD

**Issue by louisunlimited** [PrairieLearn/PrairieLearn#6460]
When I was playing with the default PLFileEditor yesterday, I found this script embedded in html:
<img width="493" alt="Screen Shot 2022-10-07 at 17 40 28" src="https://user-images.githubusercontent.com/20884681/194671979-972dd3ab-4938-4fd7-904e-f63093640f93.png">
If I modify this function and pasted it in console, we can actually change stuff like color theme (though not persistent). 
I noticed a similar request in Issue #6355, are these editor settings (like color theme) also a good feature to implement?

**Comment by nwalters512** [comment]
I think we'd be happy to accept a PR for this!

**Comment by louisunlimited** [comment]
Thank you!! I will do a PR soon. What would be the best way for implementing such feature? a drop down, modal, or off canvas? Selection / text input?

**Comment by louisunlimited** [comment]
As a side note, through the process of reading the docs, I found that ace does have a native settings panel that can be accessed with hotkeys(win:`ctrl-,` or mac:`cmd-,`) like this:
<img width="373" alt="Screen Shot 2022-10-08 at 02 32 01" src="https://user-images.githubusercontent.com/20884681/194695812-87ed25ce-e745-4055-900f-8cc6a6297d9f.png">
However, the default ace setting key bind conflicts with default browser shortcuts:
`cmd-` for 'Make everything on the page smaller'(whilst the short cut for settings is `cmd-,`). Also, `cmd-,` does not seem to work in Safari.

I would argue that showing this amount of settings to students might not be appropriate, especially the fact that users will able to change file mode from one coding language to another. Unnecessary confusions may occur during this process. Hence, I would say it's best to implement our own 'settings page/modal/etc.' with fewer settings. (despite the fact that this 'default setting' is still accessible via keyboard shortcuts.) Or, should I just link this default ace setting to a button to resolve shortcut conflicts and let this be it?

**Comment by louisunlimited** [comment]
@nwalters512 What I have right now is a settings button that will pop something up when clicked. Right now it's popping the default settings from ace and I'm still trying to figure out a way of saving it. (I'm thinking settings can turn into a save button) that will only save "Themes" and "Keybinding" for now. 
<img width="689" alt="Screen Shot 2022-10-09 at 13 09 50" src="https://user-images.githubusercontent.com/20884681/194772670-15ce55cd-0a56-4744-8f01-de10465d3042.png">

**Comment by nwalters512** [comment]
@louisunlimited Nice! I'd be inclined to build custom UI for this - I wouldn't want to prevent users with options if the save button won't actually save them. I think a lot of these options also wouldn't be relevant for most users.

**Comment by louisunlimited** [comment]
@nwalters512 Thanks for the insight! Should that mean I should just pop up a modal or something as the "settings" page instead? I was wondering if you have any prior thoughts on this. :D

**Comment by nwalters512** [comment]
Yep, a modal sounds ideal for this!

**Comment by louisunlimited** [comment]
@nwalters512  It seems there aren't simple solutions for getting a modal working correctly. So what I did right now was having the settings screen replace the editor element. Seems like a good solution to me! Should I just proceed with this?
![Screen Recording 2022-10-11 at 14 18 10](https://user-images.githubusercontent.com/20884681/195180008-4be89790-f1f0-453c-9dd6-7e5e1c6712e6.gif)

**Comment by nwalters512** [comment]
When talking about what does or doesn't work, it's helpful to have code to point to. At this point, it's probably best to open a draft PR where you can reference specific commits with what didn't work for modals. Let's pick up conversation there once you open a PR.

**Comment by louisunlimited** [comment]
@nwalters512 Somehow the modal is woking again. I opened a draft PR so you can check the modal out.
