### ISSUE TITLE
Review behaviour when change of grading method affects assessment points

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6479]
After the changes in #5909, changing a question in the web interface, particularly the grading method, may affect the assessment points when the assessment is synced. I don't believe this is done properly right now.

(AFK, adding this here to test and check when I'm available again)

**Comment by jonatanschroeder** [comment]
Just tested locally, not an issue. Changing the question's file causes a full course sync to be triggered.

**Comment by mwest1066** [comment]
Excellent.
