### ISSUE TITLE
Probable race condition in testHomework

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#650]
Probably related to the issue @mwest1066 was seeing where the homework tests were failing.

The problem occurs in `testHomework.js`, during `"11. regrading"`. During this test, a `POST` is made to an endpoint to start the regrade process. The `POST` completes before the regrade has actually run; the regrade is run as a job in the background. From what I can tell, it's possible that the next testing steps (which assert that the results of the regrade are as expected) will be executed before the jobs performing the regrade complete. Worse, they'll happen concurrently with the regrade, which consists of a number of steps.

The particular issue I'm seeing, which is somehow very reproducible on my machine, occurs when the two questions have been regraded, but the assessment has not. So, the first two score checks succeed, and the assessment score check fails.

I've tried to piece together what happens next. After that final assertion, mocha then calls the `afterAll` hook to clean up the database; during database deletion, the regrading job tries to complete, and an `Uncaught Error: pool is draining and cannot accept work` exception bubbles up to the hook. Although the deletion continues, the query in `after` gets an early callback with that error, and the homework test finishes immediately and the next test begins. The next test the tries to create a new copy of the database while the deletion is in progress, which of course causes problems, and then everything breaks.

**Comment by mwest1066** [comment]
Ah, of course! Thank you so much for figuring this out! I was going crazy trying to spot the race. I had forgotten that the POST to initiate regrading simply launches a background job. I'll fix it. I think that all the `after` hooks should work fine once we wait for everything to finish. I assume these are failing because we have a still-active transaction when they attempt to run.
