### ISSUE TITLE
PrairieLearn Darkmode Implementation

### ISSUE THREAD

**Issue by armanmoztar** [PrairieLearn/PrairieLearn#6505]
I'm not sure if a dark mode option already exists but I was wondering if prairielearn could implement a dark mode option that essentially toggles the page to a dark theme. I think a dark mode feature for would be useful for students, especially if many are using the site at a later time in the day or at night. There could be a toggle option somewhere in the settings and so I just thought I'd throw this idea out there.

**Comment by echuber2** [comment]
It's been proposed before and I think some provisional work was done on it, but it sounds like it's off the table for now:
https://github.com/PrairieLearn/PrairieLearn/pull/2108
https://github.com/PrairieLearn/PrairieLearn/issues/1190

There are a lot of accessibility and compatibility issues to consider, considering all the different elements that PL lets courses create or combine. However I've heard of students using browser add-ons to use community-created dark themes already.

**Comment by nwalters512** [comment]
Yeah, this is off the table at the very least until a) https://github.com/twbs/bootstrap/pull/35857 lands and b) we upgrade to Bootstrap 5. The latter would be a huge effort and is not currently a priority.

I'm going to close this as there's nothing actionable for us to do at the moment.
