### ISSUE TITLE
Question Development Mode on Production to Erase errors

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6508]
When questions are developed using the web interface directly on production, each time an error is generated there is an issue created. However, these issues can arise due to needing to navigate between views. Thus, they are spurious errors in nature. 

Would it be possible to place questions not linked to an assignment into a "development mode" where errors generated are not leaving a permanent issue being raised?

**Comment by nwalters512** [comment]
I don't think we plan to implement this. We rely on persistence of errors to actually render them back to the user on `GET` requests, and persisted errors are a useful part of our workflow of helping instructors with their questions.

There might be a hidden request here for easier management of issues. If that's the case, I'd recommend opening a new issue with more details (what your current workflow looks like, what parts of it are painful, what parts of it you'd like to improve, etc).
