### ISSUE TITLE
Allow pl-order-block to use partial credit for ordered method

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6513]
In `pl-order-block`, from my understanding, the "ordered" method is similar to the ranking/dag methods where the ranking is implicitly the order of correct answers. With that in mind, would it make sense to include partial credit support for the ordered method using the same principle as ranking or dag?

There is, of course, the workaround, which is to set the method to ranking and give each answer a strictly increasing ranking number, but since these are equivalent it might be simpler to just allow the same partial credit to be used.

**Comment by mwest1066** [comment]
@SethPoulsen: thoughts?

**Comment by SethPoulsen** [comment]
Ya, sounds good to me. The only reason it hasn't been done is because no one has asked.
