### ISSUE TITLE
Instructors cannot view student assessment instances for group work

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6519]
If an instructor views the assessment instance log for a group work instance, they're unable to click through to see the assessment instance page. That behavior is implemented in two places:

https://github.com/PrairieLearn/PrairieLearn/blob/bcaabc9988fa4836cb21f4e86c871621cfeada35/pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.js#L167-L169

https://github.com/PrairieLearn/PrairieLearn/blob/bcaabc9988fa4836cb21f4e86c871621cfeada35/pages/studentAssessmentInstanceHomework/studentAssessmentInstanceHomework.js#L98-L100

Instructors should always be able to see their students' instances, even if they weren't in the group (as they almost never are).

**Comment by jonatanschroeder** [comment]
This is weird, as I do this all the time to help students struggling to debug their submission... Is there a specific case where this problem happens?

**Comment by nwalters512** [comment]
@jonatanschroeder are you viewing the assessment instance overview (list of questions), or the individual questions? The latter works; the former does not. Viewing the overview is probably not as common of a use case, but the fact that it (AFAIK) does not work is a bug, which is what I'm documenting here.

**Comment by jonatanschroeder** [comment]
Got it, that makes sense.

**Comment by jonatanschroeder** [comment]
This was fixed in #9106.
