### ISSUE TITLE
Wrong assessment instance rendered if instructor is in group

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6520]
If an instructor has been added to some assessment instance's group, they'll see that particular instance when they click on *any* of their students' assessment instances.

I believe this is because the group (and thus the assessment) is looked up based on the current user's ID, rather than on the assessment instance. This is almost certainly related to #6519.

**Comment by jonatanschroeder** [comment]
I believe this is fixed.
