### ISSUE TITLE
Clearer handling of blank manual points value in manual grading page

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#6524]
Hello,

On a test question (that is auto-graded) where a student made a mistake, I wanted to give them some partial credit (manually) and add a comment. I'm able to update the points, but I can't add feedback to this page

<img width="334" alt="Screen Shot 2022-10-21 at 7 40 41 PM" src="https://user-images.githubusercontent.com/2507459/197315551-a45339ff-79ef-43fd-80c2-d055ae7314fe.png" width=40%>

Here's the error message: 

```
invalid input syntax for type double precision: ""
Error ID: 9YFC6T0PDG1Z
```
The link to it: https://ca.prairielearn.com/pl/course_instance/2439/instructor/assessment/18427/manual_grading/instance_question/35327256

Let me know if you have other info or suggestions needed

**Comment by echuber2** [comment]
Do you need to enter _something_ in the points field (even if you don't intend to _change_ the value, as you've already registered the value you want)? Try putting 1.5 in the manual points box again, perhaps?

(Sorry if this is way off! I don't have access to the manual grading feature yet and I haven't tried it out. But if this is on the right track, it seems it would be simple to either interpret a blank field as a no-op, or auto-populate it with the previously-entered value, or both.)

**Comment by firasm** [comment]
Hmm - thanks! Good tip, that seems to have worked. I entered 0 in the manual points field and then I could add my feedback!

**Comment by jonatanschroeder** [comment]
I'll keep the issue open, to provide a better message in this case. The field should indeed be mandatory.
