### ISSUE TITLE
Upgrade to Node 18

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6535]
As of today, Node 18 has transitioned to LTS: https://nodejs.org/en/blog/release/v18.12.0/. We should update our base image, deploy tooling, etc. to use Node 18.

**Comment by trombonekenny** [comment]
[Node 16 dropped to End-of-Life status](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sept 9, 2023-- early to coincide with OpenSSL 1.1.1's end date. We should revisit switching to 18.

**Comment by trombonekenny** [comment]
https://nodejs.org/en/blog/release/v18.18.0

**Comment by jonatanschroeder** [comment]
Seems like Node 20 enters active mode next week, it may be worth moving straight to 20?

**Comment by nwalters512** [comment]
Agreed, moving straight to 20 seems like a good idea.

**Comment by trombonekenny** [comment]
https://nodejs.org/en/blog/release/v20.9.0 looks like it released/LTS'd today.

**Comment by nwalters512** [comment]
For folks watching this ticket: we're currently blocked on the fact that Node 20 requires a version of `glibc` newer than what is available on Amazon Linux 2, which itself is end-of-life. We had already planned to rebuild our hosts on AL2023, but the fact that this is required to move to Node 20 means we'll try to get this done even sooner.
