### ISSUE TITLE
Use schemas for the database

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#657]
This will allow better diffs of tables and give us a logical separation between the PL and PS tables.

Using these for sprocs will also allow us to better "version" them.

**Comment by mwest1066** [comment]
> @mwest1066 #4412 did this for sprocs. Do you think there's still value in pursuing other uses of schemas in the db, or can we close this?

I don't think there is any real advantage to doing this for the tables, and it would just create a huge amount of change noise and less-readable code.
