### ISSUE TITLE
Time out workspaces after tab in background for certain period

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#6599]
If a workspace tab is in the background for more than X minutes, we should prompt the user to see if they're still there. After another timeout, we should unload the iframe entirely and stop the socket heartbeat so that the workspace container can be killed.

Relevant API: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by mwest1066** [comment]
I think it might even be fine to just stop heartbeating after a tab has been backgrounded for too long (maybe 1 hour?). I feel like I'd prefer this as a user -- I always hate it when some bank website forces itself to the front when I'm working on something else.

**Comment by nwalters512** [comment]
Oh man, do websites have the ability to foreground themselves? But yeah, I agree that that's probably sufficient. After the timeout, we can replace the page (specifically the iframe) with a nice big "workspace timed out due to inactivity, click this button to reload!" thing.

**Comment by mwest1066** [comment]
> Oh man, do websites have the ability to foreground themselves?

I've seen horrible hacks that do things like open new windows and then talk to them using `postMessage()`. I'm not sure which of these still work but I agree that we definitely don't want to go this route.

> After the timeout, we can replace the page (specifically the iframe) with a nice big "workspace timed out due to inactivity, click this button to reload!" thing.

Yes! That would be very clear and friendly. We could even display the time (or interval?) after which it timed out, for extra clarity.
