### ISSUE TITLE
Adding "bad html" in manual feedback in the box through manual grading can break rendering of the page

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#6600]
If you add in "bad" html in the manual feedback box while Manual Grading, it can cause the rendering of the page to break.

Here's the "result" of this bug:

I was able to fix it by just removing the comment that was added.

<img width="1440" alt="Screen Shot 2022-10-27 at 1 27 29 AM" src="https://user-images.githubusercontent.com/2507459/199575015-99af6211-5ace-4568-ae1b-97dae8f56d5f.png">

**Comment by firasm** [comment]
Small aside: I quite appreciate the feedback being in markdown so if there was a way to keep that, that would be nice!

I use scripts to inject boiler plate text and the markdown formatting is nice.

**Comment by nwalters512** [comment]
@jonatanschroeder I'd encourage you do what GitHub does and persist raw Markdown in the database and render it on the fly; that gives us a lot of flexibility with changing up editors or display down the line. Does the rich text editor you use support that? If not, I think we should find a different one, or use a raw Markdown editor like GitHub does.

**Comment by jonatanschroeder** [comment]
> @jonatanschroeder I'd encourage you do what GitHub does and persist raw Markdown in the database and render it on the fly; that gives us a lot of flexibility with changing up editors or display down the line. 

That is the plan right now, and how it's working at this point.

> Does the rich text editor you use support that? If not, I think we should find a different one, or use a raw Markdown editor like GitHub does; we could add some buttons for italics, bold, lists, etc. if we want to maintain a bit of the GUI-ness.

The one used in pl-rich-text-editor saves html, but I use showdown to convert it to markdown depending on the options. It's not currently in use in the manual grading interface, there the feedback is set with a simple textarea.

**Comment by jonatanschroeder** [comment]
To clarify: I'm proposing the xss+cheerio be done during rendering, on the fly.

**Comment by nwalters512** [comment]
Ah, ok, that wasn't clear. Sounds good to me! I'd probably go the route of using rehype/remark on the server, unless there's a specific reason you're thinking of using `xss`+`cheerio` here?

**Comment by jonatanschroeder** [comment]
Remark/rehype would be a replacement for showdown, not xss+cheerio (see #6480). The xss here is to ensure there are no scripts or other nasty inputs that may have been introduced by a naive or malicious grader (though I assume there is some level of trust we expect from graders, this is just a precaution).

The cheerio path is to ensure that any malformed html tags in the markdown content (e.g., a closing div tag without the corresponding opening tag) does not mess up with the page set up. Neither showdown nor xss get rid of it directly, I just tested remark and it doesn't do this either, and in other places where this kind of processing is done (e.g., the preview panel in pl-file-editor) jquery takes care of this processing. So even if we were to switch this to remark, the underlying problem remains, and xss+cheerio (or at the very least cheerio, if we trust grader feedback) is required.

**Comment by jonatanschroeder** [comment]
>  I just tested remark and it doesn't do this either

Seems like my tests were not properly set up. Indeed remark2rehype doesn't do it, but remark-raw does, so switching to remark here should be a valid approach that doesn't require cheerio. Using xss is still up for debate, do you have any thoughts? Should we allow the feedback to have scripting tags or other JS content (e.g., `onclick` attributes)?
