### ISSUE TITLE
`pl-external-grader-results` has invalid handling of test worth 0 points

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6603]
Based on this code: https://github.com/PrairieLearn/PrairieLearn/blob/b1bd7622bee7b2352906bcd0ab00a3218d8b58c3/elements/pl-external-grader-results/pl-external-grader-results.py#L113-L119

The expected behaviour seems to be that a question worth 0 points should not show any points. The problem is that `round_value` returns a string, so `test['max_points']` will not be `== 0`, but `== '0'`. As a result, a test worth 0 points will always show up as passed.

**Comment by jonatanschroeder** [comment]
This seems to have been introduced in #2578.

**Comment by mwest1066** [comment]
But in JS `'0' == 0` is in fact true 😄

We aren't using === here, which is saving us in this case. I'm not saying this is generally nice, of course!

**Comment by nwalters512** [comment]
@mwest1066 this is Python code, so unfortunately we can't rely on type coercion here.

@jonatanschroeder It looks like the fix will just be to change the comparison to `== '0'`? Not sure if there are more subtleties I'm missing here.

**Comment by mwest1066** [comment]
> @mwest1066 this is Python code, so unfortunately we can't rely on type coercion here.

🤦 I'll show myself out now

**Comment by jonatanschroeder** [comment]
> @jonatanschroeder It looks like the fix will just be to change the comparison to `== '0'`? Not sure if there are more subtleties I'm missing here.

I don't see any problems with doing that, since the string is already expected to be formatted properly. Another option would be to use `results_test.get('max_points', 0)` instead of `test['max_points']`.
