### ISSUE TITLE
Feature: `pl-collapse` decorative bootstrap element for collapsing content

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6609]
When working with a _large_ data table, there needs to be the ability to collapse large tables. 

One option would be to use the [`collapse`](https://getbootstrap.com/docs/4.3/components/collapse/) bootstrap styling:
 
<img width="800" alt="df-sales-example" src="https://user-images.githubusercontent.com/833642/199861248-3a5a5109-527f-4a73-a5bc-f5ce66f217bc.png">

```html
<p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapse-df-sales" aria-expanded="false" aria-controls="collapseExample">
    Data Frame: df_sales (click to view)
  </button>
</p>
<div class="collapse" id="collapse-df-sales">
  <div class="card card-body">
      <pl-python-variable params-name="df_sales"></pl-python-variable>
  </div>
</div>
```

Another possible option would be to use the [`details` HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag:

<img width="279" alt="df-sales-details-example" src="https://user-images.githubusercontent.com/833642/199861876-942b5eb2-bee2-45e8-89ec-4f6d6e17e258.png">

```html
<details>
  <summary>Data Frame: df_sales (click to view)</summary>
  <pl-python-variable params-name="df_sales"></pl-python-variable>
</details>
```

If `collapse` could be added to `pl-python-variable`, there could be some nice truncation and a decrease in custom styling:

```html
<pl-python-variable params-name="df_sales" collapse="true"></pl-python-variable>
```

**Comment by nwalters512** [comment]
Have you considered using the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element? It's not nearly as much markup as what you have, and it allows us to avoid setting a precedent of building this into arbitrary elements. IMO we should keep purely presentational things like this out of elements wherever possible.

**Comment by coatless** [comment]
@nwalters512 I did this after chatting with @echuber2 on Slack and updated the example above, c.f. 

https://prairielearn.slack.com/archives/C266KEH9A/p1667519694812719 

I think it might be time to consider more decorative elements if the goal is to not build design functionality into submission elements. c.f. #1753

**Comment by nwalters512** [comment]
I'm not strictly opposed to that kind of element, but I'm curious why using standard semantic HTML tags isn't the best option. What benefit do we gain by wrapping them in our own abstraction?

**Comment by eliotwrobson** [comment]
Based on discussion on slack, it seems like there's interest in creating separate elements with these abstractions, but probably not worth building into the python variable element itself
