### ISSUE TITLE
PUBLISH can't be processed

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6619]
When rolling back an installation of 20fea5e6e49631b53a21db4b00d936440b67f553 on the canary main servers we got this error: https://sentry.io/organizations/prairielearn-inc/issues/3721855226/?project=6704263

This came from a canary main server and I'm guessing it was in the process of being shut down. I think this is a redis error, so we might be shutting down the redis connection while we are still processing external grading jobs, or something like that?

**Comment by nwalters512** [comment]
I think your hunch is correct: we need to ensure that external grading results processing has finished before we shut down Socket.io and its Redis adapter.
