### ISSUE TITLE
Saved responses not echoed in student mode

### ISSUE THREAD

**Issue by jmryan2000** [PrairieLearn/PrairieLearn#662]
In PL 2.10, when I am in student mode and save a question response, the saved response is not echoed back.  The responses are saved, the grading happens normally, and the responses are included in the downloaded csv file.  They just aren't re-displayed below the response listing as they were in PL 2.9.

**Comment by mwest1066** [comment]
Thanks for the bug report! It should be fixed now in version 2.10.1. Let me know if the bug is still there.
