### ISSUE TITLE
Update Student Link generation in dev container

### ISSUE THREAD

**Issue by nelson-lojo** [PrairieLearn/PrairieLearn#6628]
When working in a development container, viewing the Student View link for an assessment uses https even in the case where the dev container serves the instructor view with http. 

Suggestion by Nathan Walters on [linked slack thread](https://prairielearn.slack.com/archives/C266KEH9A/p1667968115903609?thread_ts=1667888643.153889&cid=C266KEH9A): "We should probably use the protocol of the request when constructing the link."

**Comment by jonatanschroeder** [comment]
This should be pretty easy to implement, basically just check `req.secure` to determine if it should be `http` or `https`. Also note that the course instance has the same issue.

**Comment by trombonekenny** [comment]
In my experience, this is trickier wrt load balancers and proxies so it's not as simple as checking `req` (or trusting what Express sees as the final destination encoding if it's been through a proxy).

**Comment by jonatanschroeder** [comment]
> In my experience, this is trickier wrt load balancers and proxies so it's not as simple as checking `req` (or trusting what Express sees as the final destination encoding if it's been through a proxy).

For those cases we have an override config setting.
