### ISSUE TITLE
Unresolved feature request: Vim keybinds for editor #6355

### ISSUE THREAD

**Issue by simonCS124** [PrairieLearn/PrairieLearn#6667]
Hi there, I have a similar idea to create keybinding feature #6355 for PrairieLearn. It will be awesome if I can get a chance to make some contributions to PrairieLearn. I have finished the first prototype #6666  for this feature and would like suggestions regarding the code I write. Thank you!

**Comment by nwalters512** [comment]
There's no need to create a separate issue to let us know about your PR. You can continue any discussion about this feature or link to your PR on #6355. I'll do my best to review it today!

**Comment by simonCS124** [comment]
Dear Nathan,

       I apologize for the inconvenience; I will post the follow-up comments inside issue #6355. Also, thank you so much for taking the time to review my code, and I will try my best to resolve any existing issues ASAP. Have a good day!

Sincerely,
Jinheng Li
发件人: Nathan Walters ***@***.***>
日期: 星期二, 2022年11月29日 下午1:14
收件人: PrairieLearn/PrairieLearn ***@***.***>
抄送: Li, Simon ***@***.***>, Author ***@***.***>
主题: Re: [PrairieLearn/PrairieLearn] Unresolved feature request: Vim keybinds for editor #6355 (Issue #6667)

There's no need to create a separate issue to let us know about your PR. You can continue any discussion about this feature or link to your PR on #6355<https://urldefense.com/v3/__https:/github.com/PrairieLearn/PrairieLearn/issues/6355__;!!DZ3fjg!_LZXsWmDd2Vfwt9vIJ7A6EfD29YLBaSVbzG9wspxWNhooJ-Z71GWfOjZeZn9ZFRY3odMsK4khq1-IQZJsXnF24zaPAuW$>. I'll do my best to review it today!

―

**Comment by nwalters512** [comment]
No worries at all! We're glad to have you contributing 🎉
