### ISSUE TITLE
using latex text in figures only works inside client.js and server.js

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#67]
I would like to use this feature inside my "helper.js" file.

**Comment by mwest1066** [comment]
Added in 02f52dda29f7e7d0bf1ff30d8f84a253de2b9d61

There is a new `make_tex_images.py` command in the main `PrairieLearn` directory. If you run it from that directory then it should automatically generate all the TeX images correctly for all JavaScript files in both the `questions` and `courseCode` directories.
