### ISSUE TITLE
Student UI feedback about closed assessments

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#670]
Assessments that are closed to the student aren't visibly different enough (on the question page). This brings confusion about why PL isn't accepting any answers (looks like a bug), instead of telling the student the assessment is closed.

From a 5/26/2017 3:48pm Slack cbtf-admin message from Matt:
> Yeah, we could be clearer. We do say “Time completed: XXX” on the overview page, and the “submission” buttons are all missing, but I guess we could add something saying “No further answers can be submitted because the assessment is closed.”

**Comment by mwest1066** [comment]
Implemented in 7d7228972103fe2522631894dfe23b0b65e9e46e
