### ISSUE TITLE
Example questions from the PL knitting circle 6/7

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#674]
Tim was looking an example of questions that create parameterized files for the student to download. (Or maybe it was image creation based on parameterized data.) Or whatever our term is for variables that are per-instance randomized to the student.

Colin was looking for examples of drag-drop (presumably like https://docs.moodle.org/33/en/Drag_and_drop_onto_image_question_type). I'm not sure if that's possible with a pre-existing question, but we could hint at toolboxes that are already in use in other places to minimize reinventing the wheel.

Colin was also looking for an example of an essay answer question.

**Comment by nicknytko** [comment]
@trombonekenny is this still an issue?  There's still no real drag and drop element but there's https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/demoRandomPlot/server.py for parameterized downloads and the file editor w/ markdown for essay questions.

**Comment by nwalters512** [comment]
Essay questions can now be done with `<pl-rich-text-editor>`. If a drag-and-drop element is still desired, let's spin that into a new issue.
