### ISSUE TITLE
Github webhook to PL submission -> external grader?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#675]
Could we prototype how we'd collect submissions for an external grader from a Github webhook? Is the same framework that allows the "make upload" submissions work extendable in this way?

Mattox would be interested for CS 421 this summer. He's using the CS github-dev.cs.illinois.edu GitHub Enterprise server.

**Comment by mwest1066** [comment]
Sure, should be pretty easy to get this working. Can we talk about details at the knitting circle next Wed?

**Comment by nwalters512** [comment]
@trombonekenny do you think this is still desirable? Given the introduction of workspaces since this issue was created, I don't think there's as much of a need for this kind of workflow (short of maybe https://github.com/PrairieLearn/PrairieLearn/issues/6525). I'd err on the side of closing this.

**Comment by trombonekenny** [comment]
I think it can be closed, or continued via #6525 if that discussion/code goes anywhere.
