### ISSUE TITLE
`pl-dropdown` semantics and possible deprecation 

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#6774]
Mainly a discussion item for now, but might be worth pursuing. Currently, the `pl-dropdown` and `pl-multiple-choice` elements seem to have identical semantics in the sense that they only allow the student to input one correct answer from a given ordered list. However, they are separate elements with different semantics for the developer (identified by a distinct tag and don't have all the same options, for example https://github.com/PrairieLearn/PrairieLearn/issues/2668).

Instead of trying to make sure they behave close to identically, wouldn't it be better to deprecate `pl-dropdown` and make using a dropdown a display option for `pl-multiple-choice`? That way, the missing options from `pl-dropdown` will all get added along with reducing the amount of code that needs to be maintained on the backend. This might also make things easier for course content developers, since they can try different display options without having to change as much code or semantics. Thoughts?

**Comment by nwalters512** [comment]
This makes a lot of sense to me. This could be as easy as `display="dropdown"`.

**Comment by mwest1066** [comment]
Yep, I'm on board.

**Comment by firasm** [comment]
I'd love this! it would simplify my scripts a lot too 😁

**Comment by jonatanschroeder** [comment]
> That's a very good point. Getting random HTML to display within a `<select>` is pretty much impossible without reimplementing the dropdown in JS; not even Bootstrap styles will fix that. Agreed that we shouldn't try to support that; we can just document it.

I was thinking replacing the select with a hidden input controlled by this: https://getbootstrap.com/docs/4.0/components/dropdowns/

We've had instructors with issues showing formulas in dropdown, this would fix that too.

**Comment by eliotwrobson** [comment]
Bootstrap dropdowns seem like a nice way to push things forward. Then we could even allow for dividers and other logic.

**Comment by nwalters512** [comment]
Ah, good call! We'll have to be careful to ensure that it behaves like a `<select>` from an accessibility standpoint. The docs make it seem like most of that is already taken care of; we may just have to add an appropriate `aria-label`.

**Comment by jonatanschroeder** [comment]
Related: #3145

**Comment by eliotwrobson** [comment]
Sounds like this refactor is the direction things are going. I'll bundle this with the duplicate checking and an uplifting of the backend logic. I think I'll be able to get started next week.

**Comment by eliotwrobson** [comment]
Open PR has been updated with screenshots and some discussion. I think it's worth continuing the discussion there, as there are still a few pieces of the implementation that I have questions about how to proceed on. Overall though, it seems like the new submission and display logic is working, and this seems like a really good way to integrate the features from these two elements in a useful way!
