### ISSUE TITLE
Feature Request: Incorporate copy code mechanics from pl-variable-output to pl-python-variable output

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6786]
I think the `pl-python-variable` feature could benefit from being able to generate output code for the underlying object being shown if desired. This feature exists already for the `pl-variable-output` that is constrained to display matrix/vector outputs.

c.f. 
https://prairielearn.readthedocs.io/en/latest/elements/#pl-variable-output-element 

My thought to provide an output format for the _dataframe_ part would be:

```python
import pandas as pd
df = pd.DataFrame({'col1': [1, 2],
                   'col2': [0.5, 0.75]},
                  index=['row1', 'row2'])

out_records = df.to_dict('split')

df_variable_name = "my_df"

code_string = f"""import pandas as pd
{df_variable_name} = pd.dataframe({out_records})
"""

print(code_string)
```

This should give: 

```python
import pandas as pd
my_df = pd.dataframe({'index': ['row1', 'row2'], 'columns': ['col1', 'col2'], 'data': [[1, 0.5], [2, 0.75]]})
```

Potentially, the element could receive a "tab" feature with the default tab showing the Pandas dataframe in a similar manner. In the _second_ tab, we could incorporate the above reconstruction code for students to be able to re-create the data frame.

**Comment by eliotwrobson** [comment]
I think this would be well suited for a dataframe specific element. For other Python objects, I think that this is consistent with the current default behavior.

**Comment by coatless** [comment]
@eliotwrobson well, the current behavior focuses on _displaying_ the actual variable instead of displaying the contents while assigning it to a variable.  Maybe incorporating a variable assignment option overall would be desirable? Many of the elements grew organically based on course needs.
