### ISSUE TITLE
Feature Request: Incorporate _R_ dataframe specific types and indexes into `pl-python-variable`/`pl-dataframe`

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6787]
The `pl-python-variable` element is constrained to only interpreting a _pandas_ data frame as an object present in _Python_.  That is, the `pl-python-variable` applies a _Python_ specific interpretation of a data frame (e.g. 0-based indices). With the incorporation of https://github.com/PrairieLearn/PrairieLearn/issues/6131, the element now becomes aware of _Pandas_ specific data types. 

However, the nature of a DataFrame structure differs only slightly between _R_ and _Python_. It would be nice to take advantage of the tabular display of data by merely modifying the output to be _R_ specific by starting row indices at 1 and allowing for `dtype` to be specific to _R_'s atomic types (e.g. `numeric`, `integer`, `character`, `logical`, ...)

**Comment by eliotwrobson** [comment]
Is there a builtin way of doing this in Pandas? This just seems like a relabeling of data types, but unless people find R data types easier to read than their Python equivalents, I'm not sure who this might help.

**Comment by coatless** [comment]
@eliotwrobson this is just adding a mapping of Python's Pandas data types to _R_ data types via a dictionary lookup. The goal here would be to re-use the `pl-dataframe` element for either Python or _R_ problems. As it stands now, the element mainly focuses on a _Python_ orientation of a data frame.  

At a later time, this could be expanded to Mathematica's [Dataset](https://reference.wolfram.com/language/ref/Dataset.html) or Julia's [Dataframes.jl](https://dataframes.juliadata.org/stable/). Glancing at the docs, I'm not seeing an immediate mapping table, but I can look more over next week/write one.

https://dataframes.juliadata.org/stable/man/comparisons/
https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html

**Comment by coatless** [comment]
Returning back, I think the following covers a majority of the Pandas <-> R data type translation:

| R                                                                                       | Pandas     |
| --------------------------------------------------------------------------------------- | --------- |
| integer                                                                                 | [`Int{8,16,32,64}`](https://pandas.pydata.org/docs/user_guide/integer_na.html#integer-na), [`UInt{8,16,32,64}`](https://pandas.pydata.org/docs/user_guide/integer_na.html#integer-na), [`np.int{8,16,32,64}`](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases), [`np.uint{8,16,32,64}`](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases) and [`np.integer`](https://numpy.org/doc/stable/reference/arrays.scalars.html#integer-types)   |
| numeric                                                                                   | [`np.float{16, 32, 64, 96, 128}`](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases) and [`np.floating`](https://numpy.org/doc/stable/reference/arrays.scalars.html#floating-point-types)    |
| complex                                                                                   | [`np.complex{64, 96, 128, 256}`](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases) and [`np.complexfloating`](https://numpy.org/doc/stable/reference/arrays.scalars.html#complex-floating-point-types)    |
| character                                                                               | `object`  (default)   |
| character                                                                               | `string`    |
| logical                                                                                  | `bool`    |
| [POSIXct](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html), [POSIXt](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html) | `datetime64[ns]` |
| [POSIXct](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html), [POSIXt](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html) | `period[*]` |
| [POSIXct](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html), [POSIXt](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html)              | `timedelta64[ns]`      |

You can experiment around with dtype conversions using: 

https://colab.research.google.com/github/coatless/colab-notes/blob/main/01-pandas-to-r-data-types.ipynb

Useful reference links: 

- Pandas dtypes: https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes
- NumPy dtypes: https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases
- Reticulate: https://rstudio.github.io/reticulate/articles/calling_python.html
- rpy2: https://rpy2.github.io/doc/latest/html/generated_rst/notebooks.html

**Comment by eliotwrobson** [comment]
@coatless In the mapping to R list types, is that just checking that a given series type contains the corresponding scalar and mapping those? The scalar and timestamp mappings seem pretty straightforward.

**Comment by coatless** [comment]
@eliotwrobson Try:

```python
import pandas as pd 

def convert_pandas_dtype_to_r(s):
  # Force series to avoid odd element-wise output
  series_dtype = s.dtype

  if pd.api.types.is_float_dtype(s):
    return "numeric"
  elif pd.api.types.is_integer_dtype(s):
    return "integer"
  elif pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s):
    return "character"
  elif pd.api.types.is_categorical_dtype(s):
    # Check if ordered
    if s.cat.ordered:
      return "ordered factor"
    return "factor"
  elif pd.api.types.is_bool_dtype(s):
    return "logical"
  elif pd.api.types.is_complex_dtype(s):
    return "complex"
  elif pd.api.types.is_datetime64_any_dtype(s):
    return "POSIXct"
  elif pd.api.types.is_timedelta64_dtype(s) or pd.api.types.is_period_dtype(s):
    return "Not supported"

  return "Unknown"

# Plug in here:
frame.agg([convert_pandas_dtype_to_r])
```


https://colab.research.google.com/github/coatless/colab-notes/blob/main/01-pandas-to-r-data-types.ipynb#scrollTo=r4xs2L40D4H2

**Comment by eliotwrobson** [comment]
Added the type conversion functionality to #6800 with the above function, thanks @coatless!
