### ISSUE TITLE
Feature Request: Incorporate sorting of data inside of `pl-dataframe` element

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6788]
The current data frame output is _static_ and does not provide an interactive way to explore data.  To combat this, potential a sorting feature could be included (c.f. https://stackoverflow.com/questions/14267781/sorting-html-table-with-javascript ) or the output of the dataframe could shift to using a `datatable` representation (c.f. https://datatables.net/examples/basic_init/)

To support this, we potential could modify the `.to_html()` call:

https://github.com/PrairieLearn/PrairieLearn/blob/7a3934c5e6853a5019b57320a16a6bae59677a8d/elements/pl-python-variable/pl-python-variable.py#L41

The modification would be adding a new class `interactive-dataframe`:

 ```python
classes = ['pl-python-variable-table']
if interactive:
 classes.append('interactive-dataframe')
```

This would cause the `.to_html()` call to generate:

```
'<table border="1" class="pl-python-variable-table interactive-dataframe">...'
```

Within the HTML render, we would need to incorporate the following Javascript initialization for [Datatables](https://datatables.net):

```js
$(document).ready(function(){
    $('.interactive-dataframe').DataTable();
});
```

**Comment by eliotwrobson** [comment]
Played around with the data table library and it seems really cool! Makes it feel much easier to interact with the data being displayed. I know there's been discussion in the past about wanting a better way to display data and tables in PL, and I think this seems like a really great gateway into that.

**Comment by eliotwrobson** [comment]
So exploring this some, I think we'd need to set up the Datatable as an external dependency for this to really be doable. I'm not sure what the policy around doing that is exactly, or whether there have been dependencies added for a single element before.
