### ISSUE TITLE
Migrate Pandas Dataframe code from pl-python-variable into new element pl-dataframe

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6789]
@eliotwrobson has done a fantastic job in https://github.com/PrairieLearn/PrairieLearn/pull/6744.

Though thinking about the new options proposed, there has been a bunch of _dataframe_ specific components that don't really make sense being merged with a standardized Python structure, e.g. we have _two_ distinct tracks:

- Scalar/Dictionary/List/Tuple (part of base Python)
- Pandas data frame (found in an external package)

Should we potentially split off the data frame components into a `pl-dataframe` element? This element could be used more generally to display data tables. My thought on this relates to incorporating even _more_ features that are data frame specific. For example, we might want to mirror the capabilities of `pl-variable-output` to embed a _dataframe_ export for students to use (c.f. https://github.com/PrairieLearn/PrairieLearn/issues/6786), incorporate _R_-specific `dtypes` and indices (c.f. https://github.com/PrairieLearn/PrairieLearn/issues/6787), or allow for sorting _within_ the output table (c.f. https://github.com/PrairieLearn/PrairieLearn/issues/6788).

For backwards compatibility, we could retain the existing dataframe options but add a redirect to `pl-dataframe` similar to the existing `pl-code` usage within the element.

https://github.com/PrairieLearn/PrairieLearn/blob/7a3934c5e6853a5019b57320a16a6bae59677a8d/elements/pl-python-variable/pl-python-variable.py#L50

So, something along the lines of:

```python
 html += f'<pl-dataframe show-header="{show_header}" show-index="{show_index}" show-dimensions="{show_dimensions}">
</pl-dataframe>'
```

**Comment by eliotwrobson** [comment]
Thanks for the shoutout! I think these features all seem really cool! If we go this far (especially adding some level of interactivity), then it makes sense to split this off into a different element. All of the changes thus far have really been extensions of the existing functionality of the `pl-python-variable` element (since these are just minor modifications to the display). I'm curious what others think about this.
