### ISSUE TITLE
Access control institution

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#681]
Make a table for institutions in access control, i.e. not hard-coded for UIUC, sane defaults, and documentation.

**Comment by trombonekenny** [comment]
Done?

**Comment by mwest1066** [comment]
Afraid not. These are still hard-coded in https://github.com/PrairieLearn/PrairieLearn/blob/master/schemas/infoCourseInstance.json#L65 and are plain strings in the DB: https://github.com/PrairieLearn/PrairieLearn/blob/master/database/tables/course_instance_access_rules.pg#L5

**Comment by mwest1066** [comment]
Done now.
