### ISSUE TITLE
Autograder / Batch usage summary to Slack #ops-bot

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#682]
Would it make sense to dump some data about external grader usage to #ops-bot (I'm thinking a nightly report like the email) to get an idea of what usage is like?

**Comment by mwest1066** [comment]
Good idea. @nwalters512 is adding a grading dashboard anyway so this might be fairly easy to add on? In general, a daily summary of usage to ops-bot would be a nice way to keep track of things.

**Comment by nwalters512** [comment]
Yeah, should be pretty simple. I can't see #ops-bot, what kind of things are posted there right now? Is there any existing infrastructure around posting updates to Slack?

**Comment by mwest1066** [comment]
Implemented.
