### ISSUE TITLE
Make sync errors list the file where the error was encountered

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#683]
Since ea836bd40dd3cd89174954dbfb5d0b85cc9fdc4c now reports assessments with invalid date strings, we should do better reporting to not just show the error but in which file it occurred.

Even the extended error dump with local dev lists the `assessment_id` but that doesn't easily connect to which file(s) need to be edited.

From a #pl-help chat with Tim and Matt on 6/28. https://prairielearn.slack.com/archives/C266KEH9A/p1498661239291737

**Comment by mwest1066** [comment]
Fixed.
