### ISSUE TITLE
add check that endDate cannot be before startDate

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#684]
When validating allowAccess stanzas, check that the EndDate is after the startDate.

**Comment by trombonekenny** [comment]
Had another support incident for this today.

**Comment by trombonekenny** [comment]
Another bump

**Comment by trombonekenny** [comment]
Another bump

**Comment by mwest1066** [comment]
@trombonekenny want to fix this? The most certain way would be to add a constraint on the DB table. But that might give an ugly error message, so we could also check it in JS at https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/course-db.js#L96 (inside the `idName == 'tid'` statement).
