### ISSUE TITLE
Navigation back from questions with graphics throws you out to login screen

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#686]
In the course pl-ae483, if I access any question that has graphics (e.g., framePositionAndOrientation, findingW) through the live website (prairielearn.engr.illinois.edu), through an assessment (e.g., Exam 1 or Exam 2), then I hit “Back” in the browsers navigation bar, I am thrown to the PL login screen and not back to the assessment.

This occurs on chrome and safari. It does not occur with questions in pl-ae483 that do not have graphics.

**Comment by mwest1066** [comment]
Was due to errors that reset cookies. Resolved by 1afb7b4428426f3738b96be61a105151093f0f8f
