### ISSUE TITLE
Add ADFS auth support

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#687]
ADFS auth is needed for ZJU. We will presumably use ADFS 2016 that is based on OpenID/OAuth2, similar to the current Google auth. See:

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers

**Comment by mwest1066** [comment]
Turns out that ZJU can only support ADFS 3.0 (Windows Server 2012 R2). @trombonekenny found out that UIUC has an ADFS server and has contacted the right folks to get a test setup going.

**Comment by mwest1066** [comment]
ZJU Fall semester starts Sep 14. We will plan to test auth integration and network connectivity around the start of August.

**Comment by trombonekenny** [comment]
Closed?

**Comment by mwest1066** [comment]
Implemented in 238e21d242ffef605edb7edc266a89448f4c4580
