### ISSUE TITLE
pl-rich-text-editor: Math does not get inserted in Safari

### ISSUE THREAD

**Issue by timng0** [PrairieLearn/PrairieLearn#6880]
Reported by a student: The math/formula button does not insert anything when used in Safari. The student reported that this works in Chrome. I have tried this in Firefox (works) and Safari (does not work).

<img width="931" alt="Screen Shot 2023-01-09 at 15 13 48" src="https://user-images.githubusercontent.com/97652792/211409574-116c68de-3528-4e0a-8785-4cad639eb63a.png">

Safari, blank space highlighted:
<img width="829" alt="Screen Shot 2023-01-09 at 15 14 37" src="https://user-images.githubusercontent.com/97652792/211409694-ce741c0f-d61c-4de2-8767-89fd21efae95.png">

Expected, in Firefox:
![Screenshot 2023-01-09 at 15-15-38 admin_reflection1 (Preview) - CAPP 30271 wi23 PrairieLearn](https://user-images.githubusercontent.com/97652792/211409884-21e965ca-7e31-45e5-8787-5531df829150.png)

**Comment by jonatanschroeder** [comment]
Any chance you could check the developer tools console to check if any errors are shown?

**Comment by timng0** [comment]
Yes, this error appears:
```
[Error] Unhandled Promise Rejection: TypeError: MathJax.tex2chtmlPromise is not a function. 
(In 'MathJax.tex2chtmlPromise(value)', 'MathJax.tex2chtmlPromise' is undefined)
	(anonymous function)
	rejectPromise
	promiseReactionJob
```
