### ISSUE TITLE
Incorporate variable name scope into JSON conversion

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6883]
When trying to debug a PrairieLearn question that uses JSON, it would be great if we could know the offending variable. This requires capturing the name of the variable as it enters into `pl.to_json()` and `pl.from_json()`

For example, we have: 

```
import numpy as np 

my_variable = np.array([1+2j, 3+4j, 5+6j])
data['params']['output'] = pl.to_json(my_variable)
```

Then, we would design a type error being: 

```
ValueError: Variable `my_variable` with type complex should have both real and imaginary pair values inside of value.
                    {variable_name}
```

instead of: 

```
ValueError: Variable of type complex should have value with real and imaginary pair
```

This is easier said than done as the tricky part is getting the `variable_name` prior to it entering the function's scope...

## Proposed Solution 1: Stack search for variable name

One approach would be to use the [`inspect`](https://docs.python.org/3/library/inspect.html) library from python and navigate the stack. 

```python
import inspect

def variable_name(variable):
  """
  Obtain the name of variable passed into the function as a string regardless of the scope.
  The pass stack goes from outer to inner.

  If the variable name is not found, return the name "variable"
  """
  for current_stack in reversed(inspect.stack()):
    names = [variable_name for variable_name, variable_value in current_stack.frame.f_locals.items() if variable_value is variable]
    if len(names) > 0:
      return names[0]
```

This is probably a bit _expensive_ if the stack is large as the variable name is searched based on the value held: 

Some demos:

```python
number_value = 123
list_value = [1, 4, 5]
check_boolean_true = True
check_boolean_false = False

# Direct call
print(variable_name(number_value))
# number_value
print(variable_name(list_value))
# list_value
print(variable_name(check_boolean_true))
# check_boolean_true
print(variable_name(check_boolean_false))
# check_boolean_false
```

In nested situations:

```python
## Explore variable name structure across frames
def nested_func_global(y):
  return variable_name(y)

def nested_func_local_arg(y):
  return variable_name("bogus")

def nested_func_local_definition(y):
  res = "hi"
  return variable_name(res)

## Nested calls

print(nested_func_global(number_value))
# number_value
print(nested_func_global(list_value))
# list_value
print(nested_func_global(check_boolean_true))
# check_boolean_true
print(nested_func_global(check_boolean_false))
# check_boolean_false

## Nested calls with local function scope

print(nested_func_local_arg(number_value))
# variable
print(nested_func_local_definition(number_value))
# res
```

### Drawback: Duplicate values 

However, the drawback of this approach is if a variable has a duplicate value. So, if we have two variables with the same value of `True`, we can't easily detect the _correct_ name. 

```python
check_boolean_true = True
check_boolean_false = False

check_boolean_true_v2 = True
check_boolean_false_v2 = False

# Direct call
print(variable_name(check_boolean_true_v2))
# check_boolean_true
```

## Proposed Solution 2: One-back variable name search

Another approach, though restricted to a _single_ scope level, would be to inspect the name of the variable as it was passed into the conversion function:

```python
import inspect
def to_json(v):
  names = [variable_name for variable_name, variable_value in inspect.currentframe().f_back.f_locals.items() if variable_value is v][0]
  return names

number_value = 55
print(to_json(number_value))
# number_value
```

### Drawback: Nested Calls

If we tried with a nested call: 

```python
def nested_call(y):
  return to_json(y)

number_value = 55
print(nested_call(number_value))
# y
```

We would receive the name of the variable supplied in the nested call. Not the outmost variable name. Given the design of the function, I'm not sure how frequently the use case would be.

**Comment by eliotwrobson** [comment]
Couldn't we just attempt to do a `json.dumps` call as soon as a variable is passed in to the `to_json` function, and that will raise an error that includes call site in the stack trace? I think that could be simpler than the proposed solutions (as having to use inspect to do stuff like this could cause issues, and as you state, is unreliable in some cases).
