### ISSUE TITLE
PL v3 question format

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#689]
This is a tracking issue for the new v3 question format. This will be a new additional question format. All existing questions will continue to work without modification.

# Examples

Questions with `server.py` in Python: [`PrairieLearn/exampleCourse/questions/postitionTimeGraph`](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/positionTimeGraph) and [`../ballToss2`](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/ballToss2)

Custom elements written in Python: [`PrairieLearn/question-servers/elements/`](https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/elements/)

Python library that can be imported from any `server.py` or Python element: [`PrairieLearn/question-servers/freeformPythonLib/prairielearn.py`](https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/freeformPythonLib/prairielearn.py)

All Python calls are going via [`PrairieLearn/lib/python-caller-trampoline.py`](https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/python-caller-trampoline.py)

# High priority

* [x] Question unit test system.
* [ ] Exam grading system ("Grade" button on questions, no whole-exam grading).
* [ ] Partial credit for v3 questions (not applied to v2 question types).
* [x] File upload element (is there a pure server-side solution?).
* [ ] ADFS authentication.
* [ ] Client-side code for Mariana: PrairieDraw and fabric questions
* [x] Per-course elements.
* [ ] Redirect instructor pages to add variant query so that refresh will be stable.
* [ ] Check for submissions that are identical to previously graded submissions and mark as invalid so they don't get graded again.
* [ ] Change `test` to function to take a `correct`/`incorrect`/`invalid` parameter so we can make buttons that select this and can put one of each in the test suite.

# Renaming

* [x] Element type: `Freeform` to `v3`
* [x] Element `name` to `param_name` and `answer_name`
* [x] `server.get_data()` to `generate()`
* [x] add `server.prepare()` called after element prepares
* [x] `server.gradeAnswer()` to `grade()`
* [x] `grade()` stays the same
* [x] add `server.parse()`
* [x] add `server.render()`
* [x] leave `score` the same
* [x] `true_answer` to `correct_answers`
* [x] Element function args to `(data)`, add checks on what is modified
* [x] `submitted_answer` to `submitted_answers` (and for `raw_`)

# To Do list

* [ ] Add error during HTML parsing if unknown `pl_*` elements are found.
* [x] Fix exams.
* [x] Fix instructor questions.
* [x] Add "Save" button to Homework questions.
* [ ] Add "Grade" button to Exam questions. Remove whole-exam grading?
* [x] Shift all locking into sprocs and use repeated calls at the top of all functions to `lock_by_variant`, etc.
* [x] Delete `public/localscripts/questionFreeform.js` and remove load in question pages.
* [ ] Check that we are actually updating params/true_answer/etc after each phase (parse, etc).
* [x] Use broken variant and submission to determine which panels to render.
* [x] Sync to production with deleted questions leaves around spurious question directories with `__pycache__` files in them.
* [ ] Internal rename of 'Freeform' to 'v3'.
* [x] Add double-underscore prefix to csrfToken and variant_id in question form.
* [ ] addNumbers question with true answer 14 and 2 sig figs will accept 15 as an answer. This is probably ok, but it broke the automatic tests.
* [x] The "no grade because invalid format" logic.
* [x] In `saveSubmission()` only write `raw_submitted_answer` and save the writing of `submitted_answer` for after parsing, so we will know whether parsing has been done. Check that parsing occurred when rendering the submission and short-circuit if not.
* [x] Add element function `test` that takes an option ("correct", "incorrect", "invalid") and uses correct_answer to construct a raw_submitted_answer that will have that property
* [x] Don't store consoleLog in variant, but just put it in errors.
* [x] Speed up python calling.
* [x] Use a single PythonCaller for rendering all panels.
* [x] Support the case where the module doesn't exist.
* [x] Support the case where the function doesn't exist.
* [x] Add checks for non-modification of `data` attributes that shouldn't be modified.
* [x] Fix docs for `data` (no more `options`)
* [x] Make final decisions on names (e.g., "Standard" instead of "Freeform").
* [x] Make element `grade()` walk the HTML.
* [x] One reason for adding a validate/convert step to elements would be to allow the string->number conversion of `submitted_answer` before rendering for exams, where answers are saved and displayed before they are graded. Otherwise the render functions will need to cope with both converted and unconverted submitted answers. Or is the right thing to do here to just get rid of saving answers?
* [x] Allow `grade()` to modify `submitted_answer` to store parsed data.
* [x] Separate out `score` and `feedback` inside `question_data` (don't put them in a `grading` object).
* [x] Should we have a separate `partial_grades` object? What should it be called?
* [x] Don't turn element function errors into internal PL errors. Instead, catch them and keep going.
* [ ] Should we default to requiring all elements correct to get the question correct (or question score is minimum of element scores) or question score is weighted average of element scores? This interacts with retries as a means of getting more points. This could be controlled by whether there are "weights" set for elements (any element without a weight must be correct for the question to be correct). Or there could be a "must_be_correct" attribute.
* [x] Don't have separate `multipleChoiceSubmittedAnswer` elements, etc, but add methods to elements to handle `true_answer` and `submitted_answer` rendering.
* [x] Should we have elements take arguments like `input="submitted_answer.var"` and `output="true_answer.var"`?
* [x] Separate `question_data` into mutable and immutable parts. Or should be pass `variant`/`submission` objects separately, perhaps decomposed into mutable/immutable?
* [x] Auto-generate the contents of `submission.html` and `answer.html` if they aren't provided.
* [x] Make `grade()` an optional function? (E.g., in elements that do not accept input.)
* [x] Call the `grade()` function in `server.py` after all the element `grade()` functions are complete.
* [x] Specify function signatures for `server.py` functions.
* [x] Specify function signatures for element functions.
* [x] Specify the naming conventions for element data storage in `params`, `true_answer`, etc. Including `params._weights`, etc.
* [ ] Support partial scores for questions. Remove `correct` variable from submissions/grading_logs.
* [x] Don't pass `params` to the client for `Freeform` questions.
* [ ] Support multi-attempt questions. Allow `grade()` to modify `question_data`.
* [x] Rename `Freeform` question type to `Standard`?
* [x] Rename `get_data()` to `generate()` or `prepare()`?
* [x] Rename `grade()` to `score()`? Can we standardize on grade/score usage?
* [x] Rename `score` variables to `score_perc`?
* [x] Rename `true_answer` to `correct_answer` to match HTML panel name?
* [x] Rename `question_data` to `data`?
* [x] Rename element `name` to `var`?
* [x] Rewrite all elements in Python.
* [x] Rewrite `question.html` parsing and element calling in Python. Do we really want to support JavaScript elements at all?
* [x] Rename panels to `question`/`submitted_answer`/`correct_answer`? No.
* [ ] Parse HTML elements in document order, not by the element order as done now. Re-parse HTML returned by `render()` functions. Be strict about HTML errors.
* [ ] How do we enable an HTML style where we have three distinct question/sub/ans panel blocks? At the moment `pl_number_input` will error if it is included three times. We need to either set `panel='question'` when doing `prepare()` to only run one copy, or we need to add an attribute to `pl_number_input` to tell it that it's a repeat (e.g., `"show"="submitted"`).
* [x] Should we remove `<pl_answer_panel>` in favor of a boolean mustache variable called `answer_panel`? This would allow `{#answer_panel}...{/answer_panel}` which would avoid any concerns about valid nesting of elements.
* [x] Add support for generated files and images.
* [ ] Add CSRF tokens to `question_data` to allow questions to generate upload scripts.
* [ ] Clean up the "options" concept for questions.
* [x] Can we have something better than the current question template system?
* [x] Add support for per-course element directories.
* [x] Figure out the correct Python path for question `server.py` code and element code to allow them to load helper code (like `question-servers/freeformPythonLib/prairielearn.py`) and course-specific libraries.
* [x] Switch to mustache for `{{}}` templating to make templates dumber.
* [ ] Add object to track statistics related to specific variant options.
* [ ] Change element weights to be floats?
* [x] Log an error for any question that has non-empty consoleLog.
* [ ] Add `totalTimeout` to `PythonCaller` to make sure there are no long-running child processes.
* [ ] Add support for JavaScript servers and elements.

## Ways to improve elements

* [x] Add server-side validation for elements (`numberInput` precision, missing answers, etc).
* [x] Add lots of options to standard elements (`multipleChoice`, etc) such as multiple true answers, rendering options (inline), etc.

## Things that must be done but that will not change the interface

* [ ] Set `random.seed()` in `question-servers/python_caller.py`. We should probably pass `variant_seed` for that call to `python_caller`.
* [ ] Add support for proper encoding and decoding of numpy arrays in json.

## Things that will help developers

* [x] Append STDOUT and STDERR onto `variant.console` from `render()`, `grade()`, etc (currently only captured for `prepare()`.
* [ ] Improve errors when processing HTML. For elements with an error, print the line number and the block of HTML that is the offending element.
* [x] Errors from questions need to be put in the `errors` table and exposed to instructors.
* [x] How can we help with question testing?
* [ ] Add lots of error checking. How should we test?
* [ ] Document that elements are for convenience and have sensible default behavior, but that everything can be overridden as desired.
* [x] Documentation for elements.
* [ ] Add helper program to run `server.py` code from the commandline. Also support parsing `question.html` and calling element code from the commandline. The user should be able to select which "phase" to run (generate variant, render question, grade question, etc).
* [ ] Add "debug" option for question development that will output extremely detailed information as the question is generated/rendered/graded. All elements should provide detailed logging when this flag is set.
* [x] Should we have a `generate_correct_raw_submitted_answer()` function in elements and `server.py` that can take the `params`/`true_answer` and generate input data that will parse without error and be graded as correct? This would be helpful for automated tests. We could also have `generate_incorrect_raw_...()` and `gererate_unparseable_raw...()` to test for failures.

## Things that are only important for client-side development

* [x] Add support for `client.js` for questions. Where does this load? Do we also need support for custom HTML head lines?
* [x] Add support for `client.js` for elements. Do they need to be able to provide extra HTML head lines?
* [ ] Add client-side validation for elements (`numberInput` precision, missing answers, etc).

**Comment by tbretl** [comment]
## Things in Tim's queue

* [ ] Handle different methods of comparison in number_input
* [ ] Create docs for each PL element [here](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/newQuestion.md)
* [ ] Create `submission_panel` and `answer_panel` elements (like question_panel) - these are "top-level" elements that other things are contained in
* [ ] Tell students what the requirements are for a given method of comparison (e.g., HTML pop-up in the element?)
* [ ] Provide feedback to students when requirements are not met.
* [ ] Create `<figure>` element that takes a filename to display and an optimal width and height.
* [ ] Migrate names (e.g., matrixInputPy.py -> matrix_input.py)
* [ ] Show submitted_answer in matrix_input
* [ ] Refactor code to move library-like methods to a separate module in freeformPythonLib
* [ ] Handle commas in matrix_input
* [ ] Add python language support in matrix_input and matrix_output

**Comment by tbretl** [comment]
Subsumed by #817.
