### ISSUE TITLE
mention PL/PS enforcement on student assessment list

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#693]
On the assessment list in exam mode, for courses that enforce CBTF scheduler reservation checking, mention this at the bottom. Something like:

> Exams in this course are only available to students with CBTF checked-in reservations.

That would help 1) identify why a student might not see their exam listed, and 2) give the student and proctors a clue on how to resolve it.

**Comment by trombonekenny** [comment]
Adding into the pages/studentAssessments view when mode == 'Exam' is straightforward enough. I have that working in a local branch.

It shows up in the local dev docker too, when emulating Exam mode, which might not be relevant since we don't have any PS/PL linkage. Adding a middleware check to see if `exams.pl_course_id` is set for a course could be used as a toggle, (i.e. res.locals.course.ps_linked = true) but that seems sloppy too since any PS course that links any `pl_course_id` (say last spring in the CBTF and courseInstance) I mean it would only have to happen once for any PS course to apply to all of them.

So should we just skip the check and print the warning regardless of environment? Or trigger off something else when in local dev?

**Comment by mwest1066** [comment]
I don't think it matters too much what it says in local dev. PR?
