### ISSUE TITLE
mocha --parallel sometimes fails silently in CI

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#6940]
There's an issue with the invocations of `mocha --parallel` in `docker/test_js.sh` which is used by the CI workflow. It seems that on some systems, this can fail silently.

To reproduce:

- Checkout 325b89b686ff2ea0e94b00c0684e7535d884e3e4 (prior to the chalk fix) and rebuild a container for testing.
- In the container, make this edit to a few lines in `Makefile` to speed up the example:

Old:
```Makefile
test-js: test-prairielearn test-prairielib test-grader-host test-workspace-host test-packages
test-prairielearn: start-support
        @yarn mocha --parallel "tests/**/*.test.{js,mjs}"
```
Modified: (The text here doesn't reflect this, but you need to use tabs, not spaces.)
```Makefile
test-js: test-prairielearn
test-prairielearn: start-support
        @yarn mocha --parallel "tests/access.test.js" "tests/database.test.js"
        echo finished with no error but should have failed
```

- Run: `docker/test_js.sh`. On a 4-core CPU, this seems to succeed with no error (but it should have failed).
- Now try again without `--parallel`. It should fail as expected.

Similarly, I note this behavior:

- Using `--parallel --jobs 2` has the problem (test succeeds when it should not).
- Using `--parallel --jobs 1` does not have the problem (test fails as expected).
- Using `--bail --parallel --jobs 2` does not have the problem (test fails as expected).
- (Accordingly:) Using `--bail --parallel` (no jobs limit) does not have the problem (test fails as expected). Maybe this is an acceptable workaround for now?

This may be related to a bug with mocha's parallel mode that was previously reported: https://github.com/mochajs/mocha/issues/4559

**Comment by nwalters512** [comment]
The bug reported upstream appears to only affect ESM files that import from `mocha`, neither of which applies to us. It's possible that this is a similar but unrelated issue?

**Comment by echuber2** [comment]
Yeah, I don't think it's exactly the same, but there could be a root cause they only bandaided over before.
