### ISSUE TITLE
Stale chunks

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6949]
We had a situation just now where the chunk for the `demo/proofBlocks` question in `exampleCourse` was out of date. That is, the chunk did not match the current on-disk version of the question. We’ve also seen this happen a few times before with other courses, which I’ve always attributed to having a server die during a sync, after we’ve synced but before we’ve computed the new chunks. I’m not sure what happened with the `proofBlocks` situation, but in general we won’t recover from a stale chunk without manual intervention (normally editing the question is enough to force a regeneration, but this doesn't work for `exampleCourse` questions).

Part of the problem here is that re-syncing will not fix the stale chunks. This is because we update the stored course git hash in the DB during stage 2: https://github.com/PrairieLearn/PrairieLearn/blob/76a325a8436dda70c54711adace5e0ef8215cc4b/pages/shared/syncHelpers.js#L145-L146
but the actual sync-to-DB and chunk generation happens in stage 3: https://github.com/PrairieLearn/PrairieLearn/blob/76a325a8436dda70c54711adace5e0ef8215cc4b/pages/shared/syncHelpers.js#L188

If we die during stage 3 then we will have updated the stored git hash but not actually completed the sync. The next time we sync, we will use the updated hash as `startGitHash` so we won't detect that we still need to update the chunk: https://github.com/PrairieLearn/PrairieLearn/blob/76a325a8436dda70c54711adace5e0ef8215cc4b/pages/shared/syncHelpers.js#L193-L194

I think the solution here might be as simple as re-ordering the steps so that `updateCourseCommitHash()` is only called after all other sync steps are complete (and chunks are generated). My only question is whether there is any reason why we currently update the course hash before running sync.

**Comment by nwalters512** [comment]
I agree with the fix outlines here. We do need the hash to generate new chunks, but there's no reason to commit that to the DB until the very end.

We should also think carefully about which hash we use as the starting hash to generate chunks. If we fail to generate chunks during one sync, we'd want to use the starting hash from *that* sync instead of whichever one was left on disk.

A final, maybe tangential thought: it would be nice to add logs for chunk generation to the overall sync logs. I've had questions about which chunks were or were not generated in the past, and that's pretty much impossible to reconstruct.

**Comment by mwest1066** [comment]
> I agree with the fix outlines here. We do need the hash to generate new chunks, but there's no reason to commit that to the DB until the very end.

You mean this in the sense of passing `oldHash`/`newHash` to `updateChunksForCourse()`, right? Is there any other reason you are aware of to have the hash updated in the DB for sync to work correctly?

> We should also think carefully about which hash we use as the starting hash to generate chunks. If we fail to generate chunks during one sync, we'd want to use the starting hash from _that_ sync instead of whichever one was left on disk.

I don't think I'm following here. Generating chunks is idempotent so it should always be safe to use the last hash for which sync+chunk-generation fully succeeded, right? The worst thing that could happen if we use a too-old hash is that we regenerate some chunks that didn't need it?

> A final, maybe tangential thought: it would be nice to add logs for chunk generation to the overall sync logs. I've had questions about which chunks were or were not generated in the past, and that's pretty much impossible to reconstruct.

Excellent point. Do you just mean outputting this into the serverJob output?

**Comment by nwalters512** [comment]
> You mean this in the sense of passing `oldHash`/`newHash` to `updateChunksForCourse()`, right? Is there any other reason you are aware of to have the hash updated in the DB for sync to work correctly?

Yep, that's what I mean. We do also need the hash updated to correctly invalidate question render caches. Now that I think about it, there's some complexity there: say we only generate half the chunks for a given sync and then crash. If we update the hash in the DB, we'll fail to generate the rest of the chunks on the next sync; if we don't update the hash, we won't invalidate the render cache. I'm almost wondering if updating the commit hash and writing new chunks should be done in a transaction to make that atomic 🤔 

> I don't think I'm following here. Generating chunks is idempotent so it should always be safe to use the last hash for which sync+chunk-generation fully succeeded, right? The worst thing that could happen if we use a too-old hash is that we regenerate some chunks that didn't need it?

Correct; it's safe to use an old hash. My point is that we need to ensure we *actually* use the old hash. I saw a call to `getOrUpdateCourseCommitHash` at the start of the sync process and thought that might *actually* update the hash in the DB, but that'll just pull the hash off the course it's given, so I now believe that should be safe.

> Do you just mean outputting this into the serverJob output?

Yep, exactly!

**Comment by mwest1066** [comment]
Fixed by #7477 and #7972
