### ISSUE TITLE
Add custom placeholder in more elements

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6968]
Elements like `pl-string-input` and `pl-rich-text-editor` allow a custom placeholder to be placed. This would be useful in other elements, like:

* [x] `pl-number-input`
* [x] `pl-integer-input`
* [x] `pl-symbolic-input`
* [x] `pl-big-o-input`
* [ ] `pl-matrix-input`

**Comment by eliotwrobson** [comment]
This has now been done for all of the most commonly used text input elements:

- pl-string-input
- pl-symbolic-input
- pl-big-o-input
- pl-integer-input
- pl-number-input
- pl-units-input

Any text input elements that aren't as actively maintained and don't have this feature will have this listed in follow-up refactor PRs.
