### ISSUE TITLE
Feature: `pl-card` to simplify the requirements of bootstrap card usage.

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6971]
This is a sister issue to https://github.com/PrairieLearn/PrairieLearn/issues/6609 as it seeks to improve the decorative PrairieLearn element options. I would argue this is also different than the proposed #6747 PR as it seeks to provide a _structured_ component that could be incorporated into templates. I'm revisiting the issue as #6800  revisited the age-old issues of bootstrap logic in documentation (c.f. https://github.com/PrairieLearn/PrairieLearn/issues/1753) and unofficial usage in courses complicating the upgrade process to Bootstrap v5. 

**Note:** The element was previously discussed on Slack ([message thread - 12/14/22](https://prairielearn.slack.com/archives/C0XBTPZMZ/p1671032771179739))

The proposal here is to move toward a `pl-card` implementation matching the HTML + mustache templating of:

```html
<div class="card my-2">
{{#title}}
<div class="card-header">
{{title}
</div>
{{/title}}
<div class="card-body">
{{content}}
</div>
</div>
```

The `pl-card` element would then be used as:

```html
<pl-card title="Title here">
<pl-question-panel>
<markdown>Some content</markdown>
</pl-question-panel>
</pl-card>
```

**Comment by coatless** [comment]
I think this work.

**info.json**

```json
{
    "controller": "pl-card.py"
}
```

**pl-card.mustache**

```html
<div class="card my-2">
{{#title}}
<div class="card-header">
{{{title}}}
</div>
{{/title}}
<div class="card-body">
{{{content}}}
</div>
</div>
```


**pl-card.py**

```python
import lxml.html
import prairielearn as pl

TITLE_DEFAULT = ""

def prepare(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)
    required_attribs = []
    optional_attribs = ["title"]
    pl.check_attribs(element, required_attribs, optional_attribs)


def render(element_html, data):
    element = lxml.html.fragment_fromstring(element_html)

    # Get title
    title = pl.get_string_attrib(element, "title", TITLE_DEFAULT)

    # Retrieve content
    content = pl.inner_html(element)

    # Create and return html
    html_params = {"title": title, "content": content}
    with open("pl-card.mustache", "r", encoding="utf-8") as f:
        html = chevron.render(f, html_params).strip()

    return html
```

**Comment by tdy** [comment]
IMO `pl-card` should have `header`, `title`, and `subtitle` attributes to mirror bootstrap's `card-header`, `card-title`, and `card-subtitle` classes. I can work on this one if there are no objections.
