### ISSUE TITLE
Enhance: Add images to PrairieLearn Elements docs

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6981]
There are a few elements missing from the PairieLearn element documentation:

- [pl-big-o-input](https://prairielearn.readthedocs.io/en/latest/elements/#pl-big-o-input-element)
- [pl-dataframe](https://prairielearn.readthedocs.io/en/latest/elements/#pl-dataframe-element)
- [pl-file-preview](https://prairielearn.readthedocs.io/en/latest/elements/#pl-file-preview-element)
- [pl-question-panel](https://prairielearn.readthedocs.io/en/latest/elements/#pl-question-panel-element)
- [pl-answer-panel](https://prairielearn.readthedocs.io/en/latest/elements/#pl-answer-panel-element)
- [pl-hide-in-panel](https://prairielearn.readthedocs.io/en/latest/elements/#pl-hide-in-panel-element)
- [pl-hide-in-manual-grading](https://prairielearn.readthedocs.io/en/latest/elements/#pl-hide-in-manual-grading-element)
- [pl-manual-grading-only](https://prairielearn.readthedocs.io/en/latest/elements/#pl-manual-grading-only-element)
- [pl-external-grader-results](https://prairielearn.readthedocs.io/en/latest/elements/#pl-external-grader-results-element)
- [pl-hidden-hints](https://prairielearn.readthedocs.io/en/latest/elements/#pl-hidden-hints-element)

Also, the [`pl-rich-text-editor`](https://prairielearn.readthedocs.io/en/latest/elements/#pl-rich-text-editor-element) needs to have the link to the demo question added to the bottom of the page, c.f. `[element/richTextEditor]` in `example implementations.

**Comment by jonatanschroeder** [comment]
I don't think conditional elements like pl-question-panel and pl-manual-grading-only would benefit from images.
