### ISSUE TITLE
Feature: Serialization of `sets` and `tuples`

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#7000]
Need to think about ways to incorporate `sets` and `tuples` in JSON serialization. 

Related to https://github.com/PrairieLearn/PrairieLearn/pull/6953#discussion_r1088479325

**Comment by echuber2** [comment]
Does `dict` work already? Sets could be stored as dict keys with placeholder values, or stored as a list with a set tag. Tuples could be handled as a list too.

**Comment by eliotwrobson** [comment]
Dict already works, but there might be issues with recursive definitions

**Comment by eliotwrobson** [comment]
Looking at this again, I'm wondering whether it's worth doing this as opposed to including instructions on how to format + store a formatted string for an object using pprint.

In fact, the existing python variable element is really just a thin wrapper around the pl-code element and the pprint library. It may be worth deprecating this element in favor of providing instructions on how to format Python variables for output to the user. Thinking about some use cases, it may actually be less verbose to use pl-code than pl-python-variable.

**Comment by echuber2** [comment]
It may be useful to have serialization for these other types in general. I know general-case serialization (e.g. of functions, classes, environment state, etc.) is a bag of worms for security.

**Comment by eliotwrobson** [comment]
@echuber2 I'm definitely not against some generic socialization if other elements would use it and instructors find it painful. But implementing that for just this element increases the maintenance burden for something that may be worth deprecating to begin with.
