### ISSUE TITLE
Log which chunks were updated during a sync

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#7022]
We've periodically had weird issues with chunk generation that are difficult to debug after the fact. We should log which chunks were generated during a sync, and perhaps which files were identified as changed.

**Comment by SethPoulsen** [comment]
This link might not live long: https://prairielearn.slack.com/archives/C0XBTPZMZ/p1675202105635459

In this case, chunks were not regenerated when the content was synced from a remote git repo, but then the chunks were regenerated once the files were edited on the site.

**Comment by nwalters512** [comment]
We had another instance of chunks not being updated today: https://prairielearn.slack.com/archives/C266KEH9A/p1679458437313139

**Comment by SethPoulsen** [comment]
Looks like same exact condition as before: Chunk failed to be invalidated when the edit was synced through git, but then updating through the web UI forced the chunk to be invalidated and thus regenerated.
