### ISSUE TITLE
Explore automated building of Docker images

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#707]
Currently, someone must manually build and deploy our Docker images every time there is a change. Additionally, courses are all but forced into hosting their own images, seeing as we don't want to give write access to the PrairieLearn DockerHub account to everyone working with containers. Courses must also know to rebuild their images whenever we update a base image with a bugfix or improvement. As the number of people using external grading grows, this is obviously not scalable.

We should explore ways that we could automate the building of our Docker images, both our base images and any images created by courses. This presents a number of challenges:

* identifying image inheritance (Dockerfile `FROM` directive) and rebuilding "child" images when their parents are changed
* only rebuilding images when relevant files have changed
* changing images automatically for courses solves our problem of propagating changes from the base image, but it does potentially cause problems: what if a course accidentally deploys a broken Dockerfile and that image is built and deployed in the middle of an exam?

Coincidentally, those are exactly the challenges not solved by DockerHub, which does almost what we want, but not quite.

Developing this service would be a pretty big undertaking but I think it's necessary in the long run. Obviously open to suggestions of existing services that might solve our problems instead of having to build this from scratch :slightly_smiling_face:

**Comment by mwest1066** [comment]
I wonder whether non-docker containerization systems might be better suited to this? I'm thinking specifically about app-containerization systems like http://flatpak.org. See http://docs.flatpak.org/en/latest/working-with-the-sandbox.html for their security model. I haven't looked in detail at how dependency tracking and rebuilding are handled, but at least they seem to be considering this problem: http://docs.flatpak.org/en/latest/flatpak-builder.html

**Comment by nwalters512** [comment]
Interesting, I'll have to check that out in more detail when I have time.

**Comment by nwalters512** [comment]
Given that we don't require a base image anymore, I'm closing this. Having people build + host their own containers is fine as long as they don't depend on any PL code.
