### ISSUE TITLE
Add link to student's submission in Manual Grading Page

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#7097]
Currently if you're manually grading a particular question, there's no way (that I could see) to go to the student's entire assessment so you can look at how they answered another question.

I suggest adding a link in the yellow "Staff Information" panel to quickly go to that student's assessment instance overview page. Something like this, perhaps just above or below "AID":
https://ca.prairielearn.com/pl/course_instance/2575/instructor/assessment_instance/797315

<img width="580" alt="Screenshot 2023-02-02 at 3 31 28 PM" src="https://user-images.githubusercontent.com/2507459/216474755-a3cf1090-101b-4b9a-ae91-fddf2089251f.png">

**Comment by jonatanschroeder** [comment]
There is, the link is called "View log", see the bottom-right corner.

**Comment by firasm** [comment]
Ah, so it does! Ok thanks.
