### ISSUE TITLE
Add multiple-choice suffixes to numeric input elements

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#712]
Going beyond #711, it would be nice to be able to specify a list of possible suffixes and a correct option, so the student would have to pick the correct suffix. For example:

```text
<number_input label="$v_x=$" suffixes="$m$,$m/s$,$m/s^2$" correct-suffix="$m/s$">
```

The list of choices could be rendered with a dropdown:

```text
$v_x=$ [INPUT] [Select \/]
```

where the `[Select \/]` element is a dropdown with the list of possible suffixes.

**Comment by eliotwrobson** [comment]
Isn't this covered by the introduction of the dropdown element? The units use case will be covered by the introduction of the units element, but I think this original issue can be closed.
