### ISSUE TITLE
Bulk Edit Sharing Sets

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#7122]
With the initial implementation of sharing sets (see #6770), each question that you want to share to another course must be added manually to a sharing set. 

We should add a bulk-editing feature that allows you to edit the sharing set of a whole bunch of questions at once using regex on the QIDs.

It would be really nice if you could declare your rules/regexs on the sharing page, then it would auto-update on Sync, but it might to some work to figure out how to do that in an efficient manner.

**Comment by jeffgerickson** [comment]
It would be great if PL could share all questions with a particular tag as one sharing set.

(That's kind of orthogonal to this feature; I also want bulk-tag-editing.)

**Comment by jeffgerickson** [comment]
Bump.

**Comment by nwalters512** [comment]
A friendly reminder that "bump" is not a productive comment and just creates noise for people subscribed to this issue.

**Comment by SethPoulsen** [comment]
Now that Sharing information is set in the JSON (#10029), I consider this to be implemented, as people can use whatever tooling they want to automate editing sharing info in the JSON.

(I've done it myself with a simple find and replace in vs code and it worked great!)
