### ISSUE TITLE
Sharing Set Page, View all questions in a sharing set

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#7150]
It would be great to have a page that shows all of the questions in a given sharing set. This would be linked from the sharing set name, both on the settings page for questions and on the course sharing settings page

**Comment by jeffgerickson** [comment]
This requires some careful planning.  Some courses have literally thousands of questions.

Keeping those questions sufficiently organized for _internal_ use is already a significant challenge.  Organizing them for _external_ use begs for a more hierarchical structure and user interface for question organization, instead of the flat interface with tags that we have now.

**Comment by jeffgerickson** [comment]
Now that we’re actually sharing question, let me ping this one.

I think a good first-order interface **for consumers** would be to add all imported shared questions **to the consumer’s** Questions page, but then add the ability to filter by imported sharing set (or native/none).

A similar interface for **producers** would be to allow Questions to be filtered by _exported_ sharing set.

So I guess I’m imagining a fifth column “Sharing Set” (which would be hidden for courses that neither produce nor consume sharing sets).

- For each question from another repo’s sharing set, list the source repo and sharing set name.  “🡠 CS 374/Automata Builder Questions”
- For each native question included in outgoing sharing set, list the sharing set name(s). “➔ Automata Builder Questions; ➔ SIGSCE 2026 Demo”
- For questions in neither category, leave blank
- Dropdown menu at the top of the column allowing selection by incoming or outgoing sharing set.

**Comment by jeffgerickson** [comment]
See discussion at #8502

**Comment by SethPoulsen** [comment]
You can now see all questions in a sharing set on the Questions page, using the 'Sharing' column to filter them. 

So I consider this implemented.
