### ISSUE TITLE
List institution Sign-On first before Google/Microsoft etc

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#7174]
Proposing a minor change in the order of sign-in options to improve the student experience.

Currently the login options are listed (at least on the Canadian server) with Google first, and then the institution logins.

<img width="495" alt="Screenshot 2023-02-16 at 11 00 22 AM" src="https://user-images.githubusercontent.com/2507459/219462175-64af9915-f599-4524-a868-b50051c73a90.png">

I suggest changing the order so that it lists all the institutional logins first, and move Google at the very bottom so it's de-emphasized. 

I know I can restrict my course enrolment to only be through my institution login, but the "Sign in with Google" button is just asking to be clicked (partially because of the colour, and partially because it's first) and that leads to an Access denied button if students are getting sent to an assignment/course, and a blank page with no courses if they're logging in from the ca.prairielearn.com.

**Comment by echuber2** [comment]
Maybe there could be a note on this popup warning that some courses may require institution login, so Google is only to be used with _person_ Google accounts for public-access/non-degree courses, like MOOCs.

**Comment by nwalters512** [comment]
https://github.com/PrairieLearn/PrairieLearn/pull/6151 is probably going to be how we end up resolving this: that will make it easy to recover from using the "wrong" method so you can safely limit your course to only institutional sign-on.

The list of institutions will get much longer over time, so I'm quite hesitant to bury the general-case buttons at the bottom of a long list. Regarding adding explanatory text to this page: a) that's not accurate as many institutions just use Google auth directly with institutional accounts, and b) students don't read things anyways 😅

**Comment by nwalters512** [comment]
We don't currently plan to implement this. With #6151, even if students click the wrong button, they'll be redirected to the right place eventually. We have a _lot_ of users who haven't integrated their institution's SSO (including every brand new user), so we don't want to make it harder for them to get started and log in.
