### ISSUE TITLE
Add course_id column to variants table

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#7176]
Variants are currently associated with "parent" entities via the following columns:

- `question_id`
- `course_instance_id`
- `instance_question_id`

However, this poses an issue in a world where question sharing exists. If an instructor creates a variant from the course question preview page (e.g. http://localhost:3000/pl/course/2/question/446/preview), only `question_id` will be populated, and that's not enough information for us to know whether information about a given variant (for instance, issues created from it) should be visible in the course from which a question is shared.

If we ensure that variants are always associated with a course, this can provide pretty foolproof logical isolation for variants generated from shared questions.

cc @SethPoulsen this is related to our conversation yesterday.

**Comment by mwest1066** [comment]
Makes 100% sense to me.
