### ISSUE TITLE
students netid for external grading

### ISSUE THREAD

**Issue by egunter** [PrairieLearn/PrairieLearn#719]
It would be helpful if the netid of the student being graded could be passed, perhaps as an environment variable through to the programming environment to be used when executing external auto graders.  That way the netid can be incorporated into the report returned (and recorded).
---Elsa

**Comment by nwalters512** [comment]
Our philosophy is that a student's identity shouldn't ever be a part of a grading decision, and I think we'll stick to that unless there's a really compelling use case for knowing a student's identity in grading code. If such a case exists, let us know and I can reopen this issue for further discussion!
