### ISSUE TITLE
command line environment in Docker container

### ISSUE THREAD

**Issue by egunter** [PrairieLearn/PrairieLearn#720]
It would be helpful to have a listing of what command line tools are available in 
prairielearn/centos7-base
and derived Docker containers for Prairie Learn.  I am finding tools like bc don't exist, and so I am using ocaml, for which Matt kindly built me a container, to do much of what I might otherwise do with command line tools.  It works for me, but it is not a general purpose way that will fit most people.
---Elsa

**Comment by trombonekenny** [comment]
Hi Elsa,

If you run something like `docker run -it prairielearn/centos7-ocaml /bin/bash` you can start a shell in the container and see what's available. That's probably the easiest route.

Docker containers tend to be built on the slim side in terms of packages, for space and portability. The idea is you can add what you need (manually to the shell with `yum install bc`, and later to the [container's Dockerfile](https://github.com/PrairieLearn/PrairieLearn/blob/master/environments/centos7-ocaml/Dockerfile) so it's there for every initialization.)

**Comment by mwest1066** [comment]
The command to run an external grading docker container with a shell is:

```text
docker run -it --rm --entrypoint=/bin/bash prairielearn/centos7-ocaml
```

@nwalters512: I don't we've documented this anywhere?

**Comment by nwalters512** [comment]
We're moving away from hosting containers and offering a base container; those no longer make sense now that there's no PL-specific code that has to be in these containers.
