### ISSUE TITLE
Add timeout to workspace host health check

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#7200]
We check for workspace host health by pinging the `/status` endpoint on each host:

https://github.com/PrairieLearn/PrairieLearn/blob/ce0d20ba002b2e970554e5979e4223607b9a5201/cron/workspaceHostTransitions.js#L109

However, this doesn't include a timeout, which means that it will hang indefinitely if a host is a particular kind of unhealthy (for instance, the event loop is stuck doing some really long synchronous task). If that's the case, we should probably just mark the host as unhealthy instead of waiting indefinitely for a response that may never come. We can achieve that by adding a timeout to this request.

**Comment by mwest1066** [comment]
Agreed, a timeout here sounds like exactly the correct thing to do.
