### ISSUE TITLE
v2 question renders parameter out of order when sub/sup tags used nearby

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#723]
Colin pointed out that when he does something like this in his question.html:

````
<p>The inlet and outlet pipe dimensions are descrived in Figures 1 and 2. air enters the chamber at a rate of {{params.D}} kg/hr. Creatine enters the chamber at a rate of {{params.C}} lb<sub>m</sub>/hr. </p>
````
It renders in the browser as:

> The inlet and outlet pipe dimensions are descrived in Figures 1 and 2. air enters the chamber at a rate of <sub>m</sub>/hr. 739 kg/hr. Creatine enters the chamber at a rate of 482 lb

Note how it jumbles around the unit for the second params entry and put it in front of the first params entry.

This is happening on several questions of his. Switching to MathJAX for the subscripts works (changes the font), but it'd be nice to hunt this down. I didn't encourage the v3 question type yet, but I wanted to. :)

Example links:

https://prairielearn.engr.illinois.edu/pl/course_instance/3197/instructor/question/406504/
https://github.com/PrairieLearn/pl-bioe201/blob/master/questions/exam2CQ3/question.html

**Comment by mwest1066** [comment]
Closing as WONTFIX. Workaround is to use latex as @trombonekenny describes above, or move to the new v3 question format.
