### ISSUE TITLE
Additional roles for access control assignment

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#725]
David V. mentioned that he has a large group of course assistants that he might want to give early access to assessments, but not necessarily give them all the permissions of the TA role.

Could we support additional 'roles' that exist to group uids and apply that role to different rules, but still give them the same effective permissions as 'Student'? So he could make a "CA" role in courseInstance.json and reference it in the assessment info.json?

**Comment by mwest1066** [comment]
Dup of #226
