### ISSUE TITLE
Manually-graded instance question shows 0% despite having full points

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#7311]
@ffund reported this issue on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1678296976199299

Relevant assessment instance: https://us.prairielearn.com/pl/course_instance/129723/assessment_instance/5355820

On the assessment overview page, question 15 is shown as having 0%, even though the exam as a whole has 100/100 points:

![image](https://user-images.githubusercontent.com/1476544/223802141-b5c3ee3e-8d89-4c89-a2b5-2aeef02c3d70.png)

There are inconsistencies on the instance question page as well: the question is shown as having 10/10 points, and the submission itself is shown as 100% correct, but the "submission status" percentage is still 0:

<img width="273" alt="Screenshot 2023-03-08 at 10 26 53" src="https://user-images.githubusercontent.com/1476544/223803128-25738ff4-9cd3-4a00-aa44-43b40a82bf91.png">
<img width="479" alt="Screenshot 2023-03-08 at 10 26 58" src="https://user-images.githubusercontent.com/1476544/223803129-a24ace4d-2267-4029-a7ce-812c74d55ab5.png">

**Comment by firasm** [comment]
I have a very similar situation where the "Score" is not showing the correct percentage, even though the points are correct.

Instance: https://ca.prairielearn.com/pl/course_instance/2575/instructor/assessment_instance/800314 (let me know if you need access)

<img width="1715" alt="Screenshot 2023-03-08 at 10 48 49 AM" src="https://user-images.githubusercontent.com/2507459/223807170-5703ae17-6f20-44a2-ac79-d0aa384c37db.png">
