### ISSUE TITLE
Move pl-graph rendering from client side to server side

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7322]
Currently `pl-graph` uses [viz.js](https://github.com/mdaines/viz.js/) to render the graph client-side. However, this library hasn't been maintained for a while. Additionally, the server-side code already uses `pygraphviz`, which has a method `draw` that renders the graph using the same functionality. `pl-graph` does not provide any functionality that would require client-side rendering, as the graph data is generated server-side and never changed in the client.

I believe it makes sense to replace `viz.js` with a reference to an image created server-side. The library already exists and is in use, with the same underlying code, so I wouldn't even expect a considerable difference in resulting image.

**Comment by eliotwrobson** [comment]
Are there any existing examples of elements that display images rendered server-side to the client? Just want to try and be consistent if this is already being done somewhere.

**Comment by jonatanschroeder** [comment]
I was about to comment: how should the image be served? Using data URL would be a simple option, with a slight penalty on bandwidth (base64 encoding), though the penalty may not be that bad since these images are usually not that heavy.

Dynamic file loading is currently not an option as there is no support (AFAIK) for element-based dynamic files. Adding a new path on server.js to support this may be an option, but it may be overkill. If it's done, though, it should probably be done in a way that is flexible enough for other elements to use in the future.

@mwest1066 @nwalters512 any other ideas?

**Comment by nwalters512** [comment]
Does pygraphviz support rendering to an SVG? I'd be inclined to do that and return it from `render()`.

**Comment by eliotwrobson** [comment]
Based on the docs, looks like SVG rendering is supported: https://pygraphviz.github.io/documentation/latest/_modules/pygraphviz/agraph.html#AGraph

**Comment by jonatanschroeder** [comment]
SVG makes a lot of sense, for sure.

**Comment by jonatanschroeder** [comment]
Just realized the PR doesn't update the references to viz.js in the docs. @eliotwrobson do you have the bandwidth?

**Comment by eliotwrobson** [comment]
I can try to take a look in a few days.
