### ISSUE TITLE
Ensure consistency in handling of timezone columns

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7344]
For the `display_timezone` column in `course_instances`, the sync process always sets this column to a default value based on the course (or a fixed value if the course doesn't have it), so it could be potentially tagged as `NOT NULL` as well.

https://github.com/PrairieLearn/PrairieLearn/blob/c2dbb6219bb52ae0bbe54aedf2ed355e0934b71a/sync/fromDisk/courseInstances.js#L34

Curiously, the same field in `pl_courses` may be set to null, though it may be an interesting idea to change that too for consistency.

https://github.com/PrairieLearn/PrairieLearn/blob/c2dbb6219bb52ae0bbe54aedf2ed355e0934b71a/sync/fromDisk/courseInfo.js#L29

Additionally, this should also allow a lot of queries that currently coalesce the course instance value with the course value to simplify and use `ci.display_timezone` only (whenever the course instance is expected to exist, of course). For example:

https://github.com/PrairieLearn/PrairieLearn/blob/c2dbb6219bb52ae0bbe54aedf2ed355e0934b71a/middlewares/selectAndAuthzAssessmentInstance.sql#L27
https://github.com/PrairieLearn/PrairieLearn/blob/c2dbb6219bb52ae0bbe54aedf2ed355e0934b71a/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.sql#L8

Related: #7320.

**Comment by mwest1066** [comment]
Note that there is also `institutions.display_timezone` which is NOT NULL. This is the correct fallback for `pl_courses.display_timezone`. I think we should make both `pl_courses.display_timezone` and `course_instances.display_timezone` NOT NULL and on sync we should use:
* For course instances: `display_timezone: courseInstance.timezone ?? courseTimezone`
* For courses: `display_timezone: courseInfo.timezone ?? institutionTimezone`
I 100% agree that having all `display_timezone` columns be NOT NULL would significantly simply lots of queries and keep everything consistent.

**Comment by mwest1066** [comment]
Also see https://github.com/PrairieLearn/PrairieLearn/pull/7382 and especially https://github.com/PrairieLearn/PrairieLearn/pull/7382#discussion_r1153871876

**Comment by jonatanschroeder** [comment]
Summarizing the relevant discussion from #7382 (@nwalters512 and @mwest1066 please feel free to add):

* It makes sense to add the `display_timezone` to institution, since this field is already available on PT.
* The course should default to the institution timezone, not a fixed `America/Chicago`.
* The timezone for the default institution should be considered as well, particularly for local development. Ideally it should be `UTC`, but this may confuse instructors that have local courses that don't have a timezone set at the course-level.
* It may be a good idea to have a temporary default of `America/Chicago` to give instructors a chance to update their `infoCourse.json`. A news item, sync warning or similar process will likely cause instructors to be aware of this (is this a good idea?).
* The course repo creation process should set the timezone in `infoCourse.json` to that of the institution by default.

**Comment by nwalters512** [comment]
The default institution is currently implicitly created with `America/Chicago` as the default timezone. I think we should change the default for `institutions.display_timezone` _and_ the "Default" institution timezone (that's confusing) to `UTC`.

I'll need to think a bit about the right way to roll this out.

**Comment by jonatanschroeder** [comment]
I did a bit more digging in the code. The course sync process does not treat the absence of a timezone as a null, it just doesn't update it in that case:

https://github.com/PrairieLearn/PrairieLearn/blob/c2dbb6219bb52ae0bbe54aedf2ed355e0934b71a/sync/fromDisk/courseInfo.sql#L6-L9

So to set a course's timezone to NULL would require the course creation to set it to NULL on insert, which doesn't seem to be the case in any of what I could find. I think it should be safe to change the course's timezone to NOT NULL.

**Comment by mwest1066** [comment]
We don't have any courses with `display_timezone IS NULL` but we do have eight course instances like this. I'm definitely in favor of making all these be `NOT NULL` and fixing up the NULL ones.
