### ISSUE TITLE
Clean up R workspace question

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#7352]
From https://github.com/PrairieLearn/PrairieLearn/pull/4826#discussion_r1143793526:

Need to remove from `question.html`:

https://github.com/PrairieLearn/PrairieLearn/blob/6c4ae75662b3bfb2997ed4fa61258b8881271465/exampleCourse/questions/demo/workspace/rstudio/question.html#L18

Modify `info.json`:

https://github.com/PrairieLearn/PrairieLearn/blob/6c4ae75662b3bfb2997ed4fa61258b8881271465/exampleCourse/questions/demo/workspace/rstudio/info.json#L17-L23

by adding the key of: 

```json
        "gradedFiles": [
            "student.R",
        ]
```

Move the `demo.R` code into the `workspace/` folder and rename it to `student.R`.

This should give the directory structure of:

```sh
workspace
`-- rstudio                      # for an externally graded workspace question
    +-- info.json               # metadata for rstudio
    +-- question.html      # HTML template for rstudio
    |
    +-- tests                    # external grading files (see other doc)
    |   +-- ans.R
    |   +-- test_01_exists.R
    |   +-- test_02_type.R
    |   +-- test_03_length.R
    |   +-- test_04_components_exist.R
    |   +-- test_05_types.R
    |   `-- test_06_correct_components.R
    |
    `-- workspace          # copied into the student's workspace container home dir (optional)
        `-- student.R
```

**Comment by jonatanschroeder** [comment]
Not sure if you want to make it together, but https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/demo/autograder/r/createRObject/question.html makes reference to a workspace that doesn't exist, and is not added to any example assessment.
