### ISSUE TITLE
pl-graph issue

### ISSUE THREAD

**Issue by ShatteredSk1es** [PrairieLearn/PrairieLearn#7360]
Any way to stop PL from shrinking the networkx generated graph?

**Comment by nwalters512** [comment]
Please share more details - screenshots and code examples of what isn't working would be appreciated.

**Comment by ShatteredSk1es** [comment]
I've attached a screenshot of the code I'm using to generate the graph along with the graph itself. I tried to increase node-size by 800 but it outputted the exact same graph. Not sure if it's relevant but I am using this in pl-overlay because I need to place some input-boxes on top of the graph


<img width="768" alt="Screenshot 2023-03-22 at 10 30 42 PM" src="https://u
<img width="682" alt="Screenshot 2023-03-22 at 10 33 53 PM" src="https://user-images.githubusercontent.com/63728547/227112798-8dd91fa3-f45d-457b-926c-58e4c60b01a3.png">
ser-images.githubusercontent.com/63728547/227112759-28aecbdb-c669-4a11-9837-3bc0d9e76811.png">

**Comment by eliotwrobson** [comment]
Can you share the HTML you're using for `pl-graph`? I think using the `draw_networkx` function instead of the method used in the example question (passing the networkx graph the `pl-graph` backend) might be the cause of this. See https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/element/graph.

**Comment by ShatteredSk1es** [comment]
I think you might be right

<img width="791" alt="Screenshot 2023-03-23 at 4 13 46 PM" src="https://user-images.githubusercontent.com/63728547/227384946-48d416c9-3fbc-451f-96a5-6353aa333b52.png">

**Comment by eliotwrobson** [comment]
@ShatteredSk1es did the code you posted produce the expected results?
