### ISSUE TITLE
pl-order-blocks grading does not correctly respect indentation settings

### ISSUE THREAD

**Issue by armandofox** [PrairieLearn/PrairieLearn#7516]
using `pl-order-blocks` to create a question in which the student *may* indent their constructed solution for readability, but indentation *should not* be considered in grading. the docs say that specifying `indentation="true"` for the `pl-order-blocks` element, and `indent="-1"` for each answer, should do this; but when graded (using `ranking`) it still is marked wrong if i deliberately indent some lines in my solution. 
here is a minimal repro `question.html`.  if you drag the blocks in the correct order BUT add indentation to either of them, the grader will say it's incorrect.

```html
<pl-question-panel>Put the blocks in order.
  You may indent the elements for your own readability if you wish, but
  indentation won't affect the correctness of your solution.
</pl-question-panel>

<pl-order-blocks
  format="code"
  answers-name="answers"
  source-blocks-order="random"
  indentation="true"
  grading-method="ranking">

  <pl-answer ranking="10" indent="-1" correct="true">first block </pl-answer>
  <pl-answer ranking="20" indent="-1" correct="true">second block</pl-answer>
</pl-order-blocks>
```

**Comment by mwest1066** [comment]
@mfsilva22 is this the same issue you observed yesterday?

Tagging @SethPoulsen here.
