### ISSUE TITLE
pl-external-grader-results consistent use of colors

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7536]
#7496 changed the color for green/red in tests, but not in the score, so the score now has a different shade of green as the tests. We should probably change this for consistency.

<img width="196" alt="image" src="https://user-images.githubusercontent.com/1004907/233362825-f2cbdb04-7d98-4b9e-bd16-a5b0a629c3b2.png">

**Comment by jonatanschroeder** [comment]
This might require reviewing a few other elements, since the same tone (or a similar one, at least to my colourblind eyes 🥲) is used in pl-file-upload and pl-file-preview.

**Comment by michaelfromyeg** [comment]
Happy to take this on if it's available. Looking at #7496, I can try to do a broader skim and check for other references to the old green / any other 'bad contrasts' per the [contrast checker](https://webaim.org/resources/contrastchecker/). I can correct the one mentioned here, in pl-file-upload, and pl-file-preview at minimum.

(I have one final left, but I'd start working on it this Sunday and should finish then.)

**Comment by jonatanschroeder** [comment]
I'd encourage leveraging python/colors.py to set some defaults that are used by all of these elements.

**Comment by eliotwrobson** [comment]
@michaelfromyeg if you still want to look at this issue, I would also suggest trying to see if parts of `colors.py` can be replaced by an external colors dependency (like this one https://pypi.org/project/colour/), since that file is pretty long and can probably have some of its contents shortened. It also seems like the colours library has some built-in color picking functionality as well.

Probably worth handling with https://github.com/PrairieLearn/PrairieLearn/issues/7191, since that will also change the default display with this element.

**Comment by michaelfromyeg** [comment]
@eliotwrobson sounds good! Seems like a nice add and will take a look at that linked issue as well. I should be able to take a look at this this weekend.

**Comment by michaelfromyeg** [comment]
PR open @eliotwrobson; my use of Coloraide was a bit limited, but I think it's a start and we can look to do more fancy things in the future. It at least removes the hard-coded CSS color strings from `colors.py`.

I did a look at some other green use but I think it's probably best to focus on these feedback elements for now.

I'm not sure I follow #7191 - do you still think I should tackle some of that work in the PR?

**Comment by eliotwrobson** [comment]
> my use of Coloraide was a bit limited, but I think it's a start and we can look to do more fancy things in the future. It at least removes the hard-coded CSS color strings from `colors.py`.

I think this is a great start! Just being able to remove that huge hardcoded list is a big win in my book.

> I'm not sure I follow #7191 - do you still think I should tackle some of that work in the PR?

If you have time, it would be awesome to attack both at once (since fewer PRs means an overall shorter development cycle), and they both have to do with colors/styling for that element. Feel free to post and ask questions on that issue if you're confused about what should be done.

**Comment by jonatanschroeder** [comment]
> If you have time, it would be awesome to attack both at once (since fewer PRs means an overall shorter development cycle), and they both have to do with colors/styling for that element. 

There is a trade-off involved. Adding multiple changes in the same PR makes the review process more complex. I don't think it's a good idea to combine these two changes. That said, I'd be in favor of updating other elements and components that use similar colors in the same PR.

**Comment by michaelfromyeg** [comment]
I'll look around a bit more today -- broadly, should we be updating "feedback" greens/reds to `green3`/`red3` respectively, or all greens? (I'm pretty sure it's the former, just want to check.)

**Comment by jonatanschroeder** [comment]
> I'll look around a bit more today -- broadly, should we be updating "feedback" greens/reds to `green3`/`red3` respectively, or all greens/reds? (I'm pretty sure it's the former, just want to check.)

My opinion is that updates should be limited to elements that use it in the context of correct/incorrect/partially correct (which would also require a yellow), though I should point out some of these use bootstrap classes instead. @mwest1066 thoughts?

**Comment by eliotwrobson** [comment]
I think sticking to feedback should be ok for now. It would also be good to somehow indicate what colors are "recommended" for green/red to indicate correct/incorrect in the code somewhere. Since these are custom colors, maybe we can make them "correct_green" and "incorrect_red" or something?

**Comment by michaelfromyeg** [comment]
Agreed on all counts. The bootstrap one is a bit tricky, I wonder if there's a nice way to work that in. That's, for example, why I didn't change the "100%" badge color in the initial PR. I'll look into a 'clean' way to hopefully do this ish across the board.

**Comment by nwalters512** [comment]
FWIW, Bootstrap 5's `text-success` color passes WCAG 2.1 AA for large text on the `#F7F7F7` background in use here. I view the fact that we need to pass colors from Python to JavaScript to HTML as an _extreme_ hack and one that we should do away with at our earliest opportunity (that is, when we move to Bootstrap 5 and can use the standard Bootstrap colors). Let's not worry about badges for now; that gets into "recompile Bootstrap from source" territory, which we want to avoid at all costs.

**Comment by michaelfromyeg** [comment]
I completely agree on the hack comment; it was tedious to do even once and not ideal to replicate this pattern. That being said, I do think the feedback section looks quite a bit better with the consistent shade of green (and I personally prefer the 'hack-y color pass' to indirect references to the same custom color/hex code in a few spots). Using Bootstrap built-in for colors everywhere would address all concerns (accessibility, color consistency, and code cleanliness) so I think that's a good long (or medium?) term goal.
