### ISSUE TITLE
Manual grading: simpler access to autograder

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7554]
One thing I often find myself doing when manually reviewing code subject to autograding is doing simple modifications to the code and testing them in the question preview, to confirm which simple changes would fix a problem. This may be too much to ask, but it would be great if there were some way to perform that from within the manual grading interface itself.

**Comment by nwalters512** [comment]
To clarify, you want to make the changes and test them, but without creating a submission or a grading job for the instance question?

**Comment by jonatanschroeder** [comment]
Not sure what I want. Maybe a submission would be fine, as long as the submission is not associated to the student. I'm just brainstorming here.

**Comment by nwalters512** [comment]
And the "copy code, click on QID, paste code" workflow is for sure too much work? 😛 this feels like an extremely niche use case and I'm not sure how to build this as a generic feature. Maybe some kind of "fork instance question" button that makes a copy of the question + all submissions that isn't associated with any instance question? It's not clear to me that we should associate this potential feature with manual grading at all.

**Comment by jonatanschroeder** [comment]
Sure, I'm happy to close it. I just found myself repeating that pretty frequently, but indeed this may be a bit niche.
