### ISSUE TITLE
pl-string-input space removal options are applied only in grade and not parse

### ISSUE THREAD

**Issue by mfbutner** [PrairieLearn/PrairieLearn#7555]
I'm not sure if this is a "bug" or not but I was surprised to find that `pl-string-input`'s `remove-spaces` and `remove-leading-trailing` parameters are applied in the `grade` method when I expected them to be applied in the `parse` method as they have to do with the format of the input. This is in contrast to its `normalize-to-ascii` which while also having to do with the format of the input was applied in the `parse` method.

@eliotwrobson Is there a reason for applying the options in the methods as they are that I'm missing?

**Comment by eliotwrobson** [comment]
I don't think there's a specific reason for this (the unaltered student input is always readable with `raw_student_input`). So I think this can be added when this element gets overhauled eventually.

**Comment by eliotwrobson** [comment]
@nwalters512 Do you have any opinions here? I've finally gotten to overhauling the internals of the string element. I'm tempted not to change this for backwards compatibility, but seems a little strange some of these changes are only done in grade.

**Comment by mfbutner** [comment]
I guess the hard thing here is how should these options be interpreted. Is it that 
1. The string input should be graded as if the white space didn't exist
2. Should white space be removed from the user's input when it is entered

If it is 1. then the options should be applied in grade but if it is 2. then it should be applied in parse. 

I'd still prefer for them to be handled in parse because anytime I have to override the grade method for `pl-string-input` where I have added `remove-spaces` and `remove-leading-trailing` I have to manually readd the code to do these operations again.

**Comment by nwalters512** [comment]
I think we should change the behavior from what is there now. I think if these attributes were named `ignore-spaces` and such, the current behavior would make sense. But given that whey specifically use the word "remove", that implies mutation and this the fact that this should happen during parsing.


We can always add an `ignore-*` variant of these attributes if people need to opt back in to the old behavior for some reason?


And that said, we should probably use the value from `raw_submitted_answer` when displaying the submitted value back to the user - does that make sense?
