### ISSUE TITLE
Manual grading not updating feedback in some cases

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7556]
As reported by @firasm. In some situations it seems the manual grading feedback is not getting updated on the manual grading UI. Upload works as expected. One case:

https://ca.prairielearn.com/pl/course_instance/2575/instructor/assessment/26411/manual_grading/instance_question/53805670

From what I could gather, in these cases the grading job record is also not created. I was unable to reproduce the issue locally, but I'm 99% sure this is related to the test here failing:

https://github.com/PrairieLearn/PrairieLearn/blob/a878642fd27f17230fd2ce27c3d25fc419b75536/sprocs/instance_questions_update_score.sql#L188-L194

I'm not sure which of these is the culprit, since I expect `arg_feedback` to be not null in this case, and there is a submission for this instance question so I'm pretty sure `found_submission_id` should be not null as well. Investigating.

In #6271 this will likely be resolved since the sproc has been revamped into a lib function, but we should review to ensure that whatever is causing this is addressed there.

**Comment by jonatanschroeder** [comment]
I'm more confident that this test is indeed the one failing. Changing the auto points updates the instance question but not the submission score, which is consistent with the expected behaviour if this test were to fail.

**Comment by jonatanschroeder** [comment]
Ok, may be related: it seems this particular instance question has more than one variant, but the latest variant has no submission. This seems to explain the issue. I'll work on a fix later today.

**Comment by firasm** [comment]
I think it looks like that this happened because this was a Group Assignment, but we decided one of the students' work was not passing quality, so we "separated them" into their own group by deleting them from a group, creating a new group, and then "creating a submission on their behalf".
