### ISSUE TITLE
big-oh-input: simplify before taking limits

### ISSUE THREAD

**Issue by jeffgerickson** [PrairieLearn/PrairieLearn#7573]
The `big-oh-input` element is timing out when evaluating expressions that grow exponentially.  There is an active assignment in CS 374, where the correct answer is `factorial(n)`.  Over the last week, several dozen students have experienced timeouts with inputs of the form `n*factorial(n-1)`, leading to the incorrect error message “invalid, not gradeable”.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/2807510/234415376-dbcc32b8-5bd7-4aa3-8093-f8281b9dcebc.png">

See for example: https://us.prairielearn.com/pl/course/243/question/9071122/preview?variant_id=74394191

I believe the timeout is caused by the way sympy computes limits of quickly growing functions.  Executing `limit(n*factorial(n-1)/factorial(n), n, oo)` takes well over five minutes on my laptop, I assume because sympy is _actually computing factorials_ of large integers.  Cursory examination of the code suggests that sympy is converting limits involving the factorial function (and possibly other combinatorial functions) into limits involving infinite _series_.  I haven’t been able to reproduce the same time-out using simpler exponential functions.  Surprisingly, `limit( sqrt(n)*factorial(n-1/2)/factorial(n), n, oo)` immediately returns the correct answer `1`, presumably because the function values are no longer integers.

Fortunately, sympy is actually pretty good about symbolic simplification!  Executing `limit( simplify (n*factorial(n-1)/factorial(n)), n, oo)` immediately returns the correct answer `1`.

**I recommend inserting a call to `simplify` inside any call to `limit` in the `big-oh-input` code.**  The only reasonable alternative seems to be *never use factorials*, but that would really suck: Factorials show up naturally in running times of backtracking algorithms (for example, TSP).

**Comment by nwalters512** [comment]
@eliotwrobson can you take a look at this?

**Comment by eliotwrobson** [comment]
Sure, busy with end of semester stuff but can do it next week.
