### ISSUE TITLE
Partial credit

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#761]
# Partial credit for exams

## Changes to DB:

* [x] Add column `instance_questions.points_list_original`
* [x] Add column `grading_jobs.v2_score`
* [x] Add column `submissions.v2_score`

## Changes to logic

* [x] Modify `instance_questions.points_list`, but always compute from `instance_questions.points_list_original`.
* [x] I think we should intercept v2 question scores in `lib/question.js` and `question-servers/calculation.js`. That is, we should return two scores from the `grade()` function, namely a `score` and a `v2_score`. For v2 questions, `score` will be 0 or 1, while `v2_score` will be fractional. For v3 questions, `score` will be fractional and `v2_score` will be `null`. Then we should write both `score` and `v2_score` into corresponding columns in `grading_jobs` and `submissions`. All point calculations will only use `score`, however. When we display a submission we will have access to both `score` and `v2_score` and can display as appropriate.

## Changes to UI

* [x] Wherever we display any kind of points: display shorter of `String(v)` or a floored version of `v.toFixed(2)`, so `1` will become `1` and `1.001` will become `1.00`.

# Partial credit for homework

## Changes to `infoAssessment.json`:

* [x] New attribute `constantQuestionValue` for each Homework Assessment (default=`False`).
* [x] New attribute `triesPerVariant` for each question, value positive integer (default=1).

## Changes to DB (`database/tables`, `sync`, `migrations`):

* [x] Add column `assessments.constant_question_value`
* [x] Add column `variants.num_tries` to store the current number of graded submissions.
* [x] Add column `assessment_questions.tries_per_variant`
* [x] Add column `instance_questions.variants_points_list`

## Logic changes:

* [x] Value changes only if `constantQuestionValue=False`.
* [ ] Modify `studentAssessmentInstanceHomework.ejs` to tell students what's going on (will need to switch on `constantQuestionValue`).
* [x] Points for a valid submitted answer is computed as `floor(score*value)`. If points is greater than the last non-zero entry in `variants_points_list`, then replace this entry with `points`.
* [x] Points for question is computed as sum of entries in `variants_points_list`.
* [x] Increment `variants.num_tries` whenever a submission is graded.
* [x] If a question is not `singleVariant` then create a new variant (and close the old variant) if `num_tries` is greater than or equal to `tries_per_variant` or if `score_perc` for a valid submitted answer is 100.
* [ ] If question is not of type `v3`, then the percent correct is drawn from `submissions.v2_score` and in the same label append text `awarded full credit` or `awarded no credit`.

## UI changes:

* [x] Add middle row to question sidebar UI labeled `Awarded` showing the non-zero entries in `instance_questions.variants_points_list`.

![screen shot 2017-09-02 at 2 00 16 pm](https://user-images.githubusercontent.com/14169175/29998066-26b263b8-8fe7-11e7-9e11-fcc9c6a182e0.png)

* [x] Indicate number of tries left (`tries_per_variant - num_tries`) as badge on `Grade` button at bottom of question panel.

<img width="150" alt="screen shot 2017-09-02 at 1 07 26 am" src="https://user-images.githubusercontent.com/875833/29996745-ff205c0a-8fc9-11e7-93e9-024e3fd00125.png">

* [x] Wherever we display any kind of points: display shorter of `String(v)` or a floored version of `v.toFixed(2)`, so `1` will become `1` and `1.001` will become `1.00`.

## Regrading features

* [ ] Allow instructors to add 3 points or whatever to each student for a given question
* [ ] Allow instructors to reset a given question.

## Notes:

* Define `maxScoredVariants` to be `ceil(maxPoints / points)`. It would be nice if this is an integer but for backwards compatibility it isn't.

## Decisions that still need to be made:

* [x] We already have an `instance_questions.points_list` column, which we will use to track the available points for exam questions. We could repurpose this for homework questions to store the points accumulation over variants, or we could add another column. *Decision* - We will add another column called `instance_questions.variants_points_list`.
* [x] For backwards compatibility we could have `value` change. If the first graded submission to a new variant is 100% correct, then we do `value += points`. If any graded submission at any time is less than 100% correct we reset `value` back to `points`. (Make this a legacy option, default for now, that will be removed in future version?) *Decision* - Leave off grey boxes. Make `value` change an option (default true).
* [x] We already have the question `info.json` option `singleVariant` which corresponds to the column `questions.single_variant`. How does this interact with `static` in `infoAssessment.json`? *Decision* - Keep things as they are, don't use `static`/`dynamic` property for now.
* [x] If we choose not to restrict `maxPoints` to an integer multiple of `points`, then we could add another row to the Question UI labeled `Total` and showing a label with `sum-of-entries-in-pointsList / maxPoints`. *Decision* - Add a middle row labeled `Awarded` with the list of points, keep third row `Points` with the total / max.

## Things to rethink after semester is done

Generation
* [ ] New attribute `generation` for each question, value `static` or `dynamic` (default=`dynamic`) in `infoAssessment.json`
* [ ] Add column `assessment_questions.generation` to DB
* [ ] Remove option that `value` changes.
* [ ] If a question is `static` then never create a new variant.
* [ ] If a question is `dynamic` then create a new variant if `num_tries` is greater than or equal to `tries_per_variant` or if `score_perc` for a valid submitted answer is 100 (may have to make this “is greater than or equal to some threshold”).

## Other
* [ ] Bring back the grey boxes.

<img width="188" alt="screen shot 2017-09-02 at 1 07 17 am" src="https://user-images.githubusercontent.com/875833/29996678-c07c6030-8fc8-11e7-9ae2-f963a194289d.png">

**Comment by tbretl** [comment]
Subsumed by #817.
