### ISSUE TITLE
Possible `get_uuid()` changes

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#7654]
Per discussion in office hours with @mwest1066, vanilla uuids generated by this function may not be usable as ids in HTML because they start with numbers, not letters. To avert this problem, the `get_uuid()` function could be modified to only return uuids that start with a letter.

**Comment by jonatanschroeder** [comment]
Aren't UUIDs typically prefixed by some text anyway?

**Comment by eliotwrobson** [comment]
> Aren't UUIDs typically prefixed by some text anyway?

Yes, but sometimes people (me in office hours) don't do this, and certain components silently fail.

**Comment by mwest1066** [comment]
This feels like a safe change that would remove a class of hard-to-debug problems, so I think it's worth doing.

**Comment by eliotwrobson** [comment]
This could be as simple as rejection sampling. I'm not sure if anyone is using UUIDs for anything other than their non-conflicting properties.

**Comment by jonatanschroeder** [comment]
Wouldn't adding a random letter prefix resolve your issue? Is there any code that depends on this having a specific format?

**Comment by eliotwrobson** [comment]
> Is there any code that depends on this having a specific format?

That's what I'm wondering. The code in this repository is probably unaffected by this change, but it's possible (though unlikely) some course code could be sensitive to this.

**Comment by eliotwrobson** [comment]
Thought about this some; I think the main property that client code might depend on for uuids is the length. So instead of adding a random letter prefix, we can just replace the first character with a randomly chosen letter (preserving the length). Then we can check for a couple of basic properties with some short test cases.

**Comment by jonatanschroeder** [comment]
Since UUID is hex, you should be able to replace an initial 0-9 with g-p without loss of randomization...
