### ISSUE TITLE
config.authType options

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#7668]
Pulled down the latest version of `master` and had Zod errors on booting with my previously working config:

```
  errors: [
    {
      received: 'x-auth',
      code: 'invalid_enum_value',
      options: [ 'none', 'x-trust-auth' ],
      path: [ 'authType' ],
      message: "Invalid enum value. Expected 'none' | 'x-trust-auth', received 'x-auth'"
    }
  ]
```

I'm not sure what all options should be in there (based on [searching](https://github.com/search?q=repo%3APrairieLearn%2FPrairieLearn%20authtype&type=code) it seems like `none` is the only thing current PL keys off of) and I can't seem to find the previous schema if we had one. 

The config breaking change was unexpected-- I just can't tell if my config was non-standard or if we should add `x-auth` to the options in `lib/config.js`  The [docs ](https://github.com/PrairieLearn/PrairieLearn/blob/4c226f80efb92dd2204a695a33181b061ff04839/docs/running-in-production/authentication.md?plain=1#L33) reference `x-auth`

**Comment by nwalters512** [comment]
Adding `x-auth` to the allowed values would be fine. As you point out, we don't currently ascribe meaning any value besides `none`.
