### ISSUE TITLE
broken variant flagging works unexpectedly with single-variant questions

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#769]
If a single-variant question has an error (e.g. an element is missing a required parameter), it will be flagged as broken, and the user will see "Broken question due to error in question code". Normally, you could fix the code and generate a new variant to proceed, but since the question is single-variant, you can't generate a new variant.

Not sure what the right solution is here. Maybe prevent single-variant questions from short-circuiting if it's flagged as broken?

**Comment by mwest1066** [comment]
Will be fixed by #1041
