### ISSUE TITLE
Add pl_number_input attribute to disable correct answer checking and help text.

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#772]
Maybe also provide attributes for custom help text and template text?

The use-case for this is when we want to input a number but there really isn't a correct value. For example, it might be that a question wants to ask students to pick a number between 10 and 20 and in a separate box write out its prime factorization, which the question `grade()` function would then check.

I ran into this problem when making a question that asked "What score would you like for this question?"

**Comment by nicknytko** [comment]
Is this still necessary since grading functionality can be overridden in the question server code?

**Comment by mwest1066** [comment]
It looks like we might have fixed this somewhere along the way. If you just don't provide a correct answer for `pl-number-input` then it simply doesn't grade it, which makes sense.

We also added the `show-placeholder-text` attribute at some point, so I think this issue is effectively completely implemented?

**Comment by nicknytko** [comment]
It seems so, I’m going to close this out.
