### ISSUE TITLE
Clean up typed-checking `query*` functions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#7739]
As discussed on Slack with @nwalters512 we could clean up our queries with some new functions:
* `queryRows()` -- the equivalent of the current `queryValidatedRows()`
* `queryOneRow()` -- the equivalent of the current `queryValidatedOneRow()`
* `queryOptionalRow()` -- the equivalent of the current `queryValidatedZeroOrOneRow()`

Each of these functions should support two new features:
* Optional `params` argument. All functions should work with three arguments as `query*(sql, params, type)` and two arguments as `query*(sql, type)`.
* Auto-detect single-column mode. At the moment we have separate `*SingleColumn*` versions of all functions, but this is very error-prone in practice. Instead we should check whether exactly one column was returned and treat this the same way the `SingleColumn` variants do at the moment. That is, apply the type-checking directly to the object in that column and return the column value (or a list of them) rather than the row or list of rows.

**Comment by nwalters512** [comment]
Unfortunately the name `queryOneRow` is already taken by our legacy callback-based code. We could use either `queryRow` or `querySingleRow` instead - any preference?
