### ISSUE TITLE
Homework grading changes

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#790]
Things to reconsider for Homework grading:

* [ ] Show "1 try left" on Grading button for questions with multiple `triesPerVariant`.
* [ ] Don't increase `value` for questions with multiple `triesPerVariant` unless 100% on first try for a new variant.
* [ ] Make History entry show submission percentages rather than points.
* [ ] The last increment of history before maxing out a question is always the full `value`, even if less points were awarded because `max_points` was hit.
* [ ] Don't keep accumulating history when points are already maxed out to avoid ridiculously long history lists.

**Comment by tbretl** [comment]
Subsumed by #817.
