### ISSUE TITLE
Clarify behavior of "Grade" button (and "Save" button) on student questions

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#791]
Currently, the "Grade" button behaves more like "Save and Grade" in that it grabs the current inputs, creates a submission, and then grades it. If a previous submission was saved, not graded using "Save", a student might expect the Grade button to score that previous submission rather than create a new one.

Since the input fields are auto-populated with the most current submission on load/reload, this does not create an issue if a question is returned to and immediately graded (since it simply creates a second, duplicate submission with the same values). However, if a student has changed the input values but wants to return to the previous submission, they must reload the question or retype the existing answer.

**Comment by rbessick5** [comment]
It also occurs to me that, if a student loads a question whose most recent submission is "graded, incorrect" and immediately clicks "Grade", a new copy of the incorrect submission would be made, then graded (incorrect again).

We could address both problems by making "Grade" select the most recent submission and -- if it exists and has not been graded already -- grade it. We would want this button to be disabled unless such a submission exists. However, this would require two clicks to score an answer; one to "Save" the answer and a second to "Grade" the question.

We could also have three buttons: "Save answer", "Grade saved answer", and "Save and grade answer", but more buttons could cause more confusion, mis-clicks, etc.

**Comment by mwest1066** [comment]
I dislike the idea of adding an extra button :-)

I'd like input from the UI experts about what to do with this issue (if anything).

**Comment by mwest1066** [comment]
Changed "Grade" to "Save and grade" in 4b88ed0ea7a5017746fc807cb0016efc566a35e2
