### ISSUE TITLE
Better handling of assessment changes for assessment instances created by staff

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#7917]
Currently if an instructor uses student mode to create an assessment instance for an exam-type assessment, and then changes settings for the assessment that affect which questions should be chosen (e.g., new questions, or changes in question alternative settings), the original instance will not be changed with the new settings. This is somewhat expected (since by design exam-type assessments will remain unmodified if settings change), however it can be confusing for instructors as they test the different assessment settings in student mode.

My suggestion is that, in student mode for a user with staff access, if an assessment instance is opened and the assessment settings were modified since the assessment instance was created, a warning is provided to the instructors recommending a new instance. If the warning provides the ability to delete the current instance and create a new one, even better. I'm not sure what the best way of identifying "settings were modified" is, though.

**Comment by nwalters512** [comment]
Thought for determining if setting were modified: track `updated_at` for assessment rows and `created_at` for assessment instances, prompt to recreate if `assessment_instances.created_at < assessments.updated_at`?

**Comment by jonatanschroeder** [comment]
Assessment instances already have a `date` column that effectively acts as a `created_at`, I believe.

**Comment by trombonekenny** [comment]
I'm jumping into this conversation because having a quick way to delete my (instructor's) student assessment instance and restart it without digging through the Students tab would be helpful. I'd use it for for content development and working through labs and wanting a fresh version each hour.

We have `assessment_instances.date` but no `assessments.updated_at`. Do we need to add that? I see a `assessments.sync_job_sequence_id` which seems logical to link that back to a timestamp but I don't see that populated in my dev install.

**Comment by jonatanschroeder** [comment]
Question is: what counts as an update? If it's a sync, then finding the last sync for the course should be enough, though that may catch syncs that did not actually change the assessment. Is that important?

Would a simple "reset assessment" button, always available or staff in their own assessments (or possibly for staff with student data editor permission in student assessments), be enough? This could be placed in the "Staff information" panel. This would be a separate issue than the warning itself, though.

**Comment by nwalters512** [comment]
I think the simple thing that Jonatan suggests is good enough for most cases and is certainly a big improvement over the current state of things.
