### ISSUE TITLE
Add autoformatting via Prettier on json configurations

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#7922]
Extracted from https://github.com/PrairieLearn/PrairieLearn/pull/7903#discussion_r1219950400

**Comment by jonatanschroeder** [comment]
#8187 handles JSON files, but at this point does not handle example and test courses, which I believe was the original discussion in the original comment, so I won't mark this issue as resolved at this point.

**Comment by eliotwrobson** [comment]
Can this now be closed after https://github.com/PrairieLearn/PrairieLearn/pull/10267 was merged?
