### ISSUE TITLE
Students are reporting problems adding the course in PL

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#796]
Can we hunt this down?

**Comment by lightalchemist** [comment]
Same for my course. Strangely, the same students reported that they are able to add the course using their phones...

**Comment by mwest1066** [comment]
@lightalchemist Have you observed this personally? Any chance of seeing a student with this issue try it on a browser with the JS console open to view errors?

**Comment by lightalchemist** [comment]
@mwest1066 I haven't observed this personally but a few students in my course (UIUC CS411) has reported this problem on Piazza. The interesting this is they can add the course on their phones. I can request those affected students to send me a screenshot of the JS console, and when/if they do, I will send you a copy on the slack channel.

**Comment by mwest1066** [comment]
Jon Ryan reported that he could get this to happen on Windows10/Chrome by waiting a long time after clicking the Add button and before clicking the Confirmation button.

**Comment by mwest1066** [comment]
Fixed by #1499
