### ISSUE TITLE
Division by zero during grading

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#797]
Reported by @IouJenLiu: I got division by zero error, when I click grade in student view. Instructor's view works fine.

See Slack for more screenshots with full data.

![err1](https://user-images.githubusercontent.com/875833/30228625-24956712-94a4-11e7-9bfd-29178d7f2f24.png)

**Comment by mwest1066** [comment]
Turns out this was because all questions had zero points set. We should at least not die in that case, even if we don't compute anything sensible.

**Comment by jmryan2000** [comment]
UIowa ran into this bug, too.  It would be nice to have the application gracefully handle this.  Until we get the auto-grader implemented, it would be nice to set the free format response questions to zero points so that students' scores accurately reflect what is graded within PL.

**Comment by trombonekenny** [comment]
@jmryan2000 You might try adding "gradingMethod": "manual" to the question's info.json, ala https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/fibonacciUploadManual/info.json  That removes the "grade" button entirely, or the notion of points (students only see 0/0). That's for questions that are just saved in the system and manually graded elsewhere.

It was added for the v3 stuff, but I don't think it requires it? Might want to test and see if that works for you?

**Comment by jmryan2000** [comment]
@trombonekenny Thanks for the suggestion.  These questions actually already had the "gradingMethod": "Manual" set.  Here is an example:

    "uuid": "1ed68c42-229c-4620-b7f3-732d56cc35f0",
    "title": "FindMinMaxArray",
    "topic": "FreeResponse",
    "tags": [
        "Array"
    ],
    "clientFiles": [
        "client.js",
        "question.html",
        "answer.html",
        "submission.html"
    ],
    "type": "Calculation",
    "gradingMethod": "Manual"
}
