### ISSUE TITLE
No files were present in this submission

### ISSUE THREAD

**Issue by gonzk** [PrairieLearn/PrairieLearn#7974]
Link: https://ca.prairielearn.com/pl/course_instance/3232/instance_question/58522518/

This homework is manually graded and whenever students click on Save, under Files, they are told there are no files present in the submission. Students are using a Jupyter workspace

![image](https://github.com/PrairieLearn/PrairieLearn/assets/67614919/987d838f-cc51-4c38-854a-956c46ce211e)

**Comment by jonatanschroeder** [comment]
Did you include any files in the [`gradedFiles` setting on info.json](https://prairielearn.readthedocs.io/en/latest/workspaces/#infojson)? These are the files that will be listed in the submitted answer. It should have something like:

```
      "gradedFiles": [
          "Workbook.ipynb"
      ]
```

**Comment by gonzk** [comment]
Ohhh I see, we removed that because it was going to be manually graded. Adding that back in fixed the issue. THank you!
