### ISSUE TITLE
provider mismatch for user_id

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#801]
user_id 33750 had previously logged into PrairieLearn with his Google account with uid netid@illinois.edu, provider 'google'

When he logged into PL in the CBTF with shibboleth, he got the error "provider mismatch for user_id 33750' The error id is in proctor chat 9/11 8:57pm.

The row in `users` had a UIN, so I presume the scheduler didn't care the provider was google (or maybe PL set it too).

Dave fixed it by changing the provider to shibboleth for user_id 33750. The student was able to take their exam.

There are 4 users (now 3) in the DB with @illinois.edu uids and google provider. Besides the one I fixed, one other (24839) has a UIN set.

These should all get fixed to provider shibboleth and the google auth set to not allow illinois.edu logins? Or some other workaround (but I think uid is unique)

**Comment by mwest1066** [comment]
We could also just reset the provider rather than rejecting it. Maybe this would be friendlier?

**Comment by trombonekenny** [comment]
Sure, if it doesn't break things that different providers can toggle between a shared uid.
