### ISSUE TITLE
Update circuit example question

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#8128]
PR #8115 introduced [schemdraw](https://schemdraw.readthedocs.io/en/latest/), a library for generating diagrams of circuits. Currently, there are questions in the example course that use statically generated circuit diagrams (for example, [this](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/demo/annotated/engCircuit)). Change these to use schemdraw, including dynamic labels.

**Comment by Anmol-Ghadia** [comment]
Can you assign this to me?

**Comment by eliotwrobson** [comment]
@Anmol-Ghadia done! You'll have to wait for #8115 to get merged (or add the library manually on your local dev environment then rebase).

**Comment by eliotwrobson** [comment]
@Anmol-Ghadia the PR has been merged! Should be good to get started if you pull from master.

In addition to using it to render the circuit in [this question](https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/demo/annotated/engCircuit), it would be great if that same question could be updated to use the `pl-units-input` element instead of `pl-number-input`.
