### ISSUE TITLE
Document pointing local PL to >1 course directories

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#813]
From Rebecca from a knitting circle, but it's a FAQ I've seen in other places especially as people see other people's content and copy things between them. Is it just another docker directory mapping, or does something need to change in the config.json to support more courses?

**Comment by mwest1066** [comment]
We don't actually support it, but it would be trivial to add. You just need to change `docker/config.json` and `Dockerfile`. I suggest adding `course2`, `course3`, etc. These need to go in `mkdir courseX` in `Dockerfile` and also in `docker/config.json`. Then in the docs we can tell people to add extra `-v SOMETHING:/course2 -v OTHERTHING:/course3` etc.

Want to send me a PR?

**Comment by dowobeha** [comment]
I want to second this issue.

**Comment by tdy** [comment]
This is purely documentation? Or also add a couple extra courses (`course2`, `course3`) into the default docker configs.

**Comment by mwest1066** [comment]
Also needs to create the directories in `Dockerfile` and add them as courseDirs in `docker/config.json`. Plus documentation.
