### ISSUE TITLE
Logout improvements

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#816]
Activate logout from Google OAuth2. Also delete local authn cookies to ensure logout.

Check whether we still have a spurious logout download with Azure.

**Comment by nwalters512** [comment]
The `pl_authn` cookie is deleted upon logout, and logout is enabled for all authentication methods. @mwest1066 is there anything else to do here?

**Comment by mwest1066** [comment]
I agree that we good to go here.
