### ISSUE TITLE
Submission info button not opening a modal

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#8188]
In the question preview page it seems the ℹ️ button for each submission that opens the modal with grading job info is not working. The button doesn't act at all, and only collapses the submission panel. I believe it may be related to recent changes in the JS assets for the page, investigating. [Raised on Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1689363159243639).

**Comment by jonatanschroeder** [comment]
It seems this issue only happens if the submission is grading when the page is loaded, and the submission content is loaded via socket after grading is complete. After refreshing the page the button works again.

**Comment by jonatanschroeder** [comment]
Found the problem: in #7904, the question functionality was moved from a partial to an asset. During this transition, some jquery code was replaced with vanilla JS. In particular, this code:
https://github.com/PrairieLearn/PrairieLearn/blob/92e03fb6fbaae08db5ffddbc9087aa15856caa64/apps/prairielearn/src/pages/partials/externalGradingLiveUpdate.ejs#L88-L90
was replaced with:
https://github.com/PrairieLearn/PrairieLearn/blob/2193f2cc25a80282fabe0e54bb8566addc1ebb22/apps/prairielearn/assets/scripts/question.ts#L116

While in general the functionality of both is pretty similar, the jquery version will run any scripts that are part of the code, while the `outerHTML` version will not. In particular, the script that adds a click event to the info button is part of this code.

One fix might be to move the script to a different part, but that would only solve this particular issue. It would not resolve another issue that is likely happening as well: in these cases any other script included in the submission panel (such as element scripts or question scripts) would not run either. So a proper fix should ensure that any code here indeed runs as necessary.

**Comment by jonatanschroeder** [comment]
Relevant: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations

**Comment by nwalters512** [comment]
@jonatanschroeder thanks for finding this. We want to retain existing behavior, which will mean executing any script tags when they're inserted. I'd be perfectly happy to reintroduce jQuery code here if that means it will handle this case successfully. In the long term, we can figure out how exactly jQuery handles this and duplicate its behavior with vanilla DOM APIs.

**Comment by echuber2** [comment]
From the sound of it, this _might_ have been related to the issue that @nowaktx was recently experiencing with code injected into CS 128's feedback.
