### ISSUE TITLE
Rounded right logic on elements

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#8193]
As part of the push to make elements display consistently, some PRs have added items to the input group that elements use for displaying information (suffix, score badge, invalid sign, etc). This has made the logic for deciding where to put the `rounded-right` class somewhat complicated and prone to mistakes. See https://github.com/PrairieLearn/PrairieLearn/pull/8192/files for an example.

Either remove the rounded-right class entirely, or add a helper function that works out the logic of how to display this correctly so that elements can have this without logic duplication.

This affects the following elements / consistency PRs:

- #8192 
- #8191 
- #8189 
- #7934 
- #6980

Context is in the discussion and related issues here: https://github.com/PrairieLearn/PrairieLearn/discussions/7353

Alternatively, it would be great if there were an easier way to do this (always have the ends of the input group rounded).

**Comment by nwalters512** [comment]
Possibly a naive question: none of the Bootstrap input group examples (https://getbootstrap.com/docs/4.6/components/input-group/) use an explicit `rounded-right` class. Is there a reason we can't do whatever those examples are doing and avoid the need for `rounded-right` entirely?

**Comment by eliotwrobson** [comment]
> Is there a reason we can't do whatever those examples are doing and avoid the need for `rounded-right` entirely?

Not in particular, I've just been following what's in the mustache templates currently. A lot of those have some wonky stuff and haven't been revised in a long time. The proposed solution (without `rounded-right`) would be _much_ simpler, and I would strongly prefer doing this over the current style.

I can try and play around with this and see if the template can be cleaned up. Though someone who knows more bootstrap / HTML can probably do a much better job than I can; the mustache templates are pretty bloated and could use some attention to help reduce the amount of markup that they generate.

**Comment by echuber2** [comment]
The examples on the Bootstrap documentation are putting a border-radius on those items in general, but selectively zeroing out the `border-top-right-radius` (etc.) to remove the rounding for the internal faces. It looks like they do have a special "prepend" and "append" class set aside for that, but in other cases it looks like they use smart CSS selectors to automatically do this where it's appropriate. We could probably do something similar to automatically get rounding around a whole group of divs that go together.

**Comment by eliotwrobson** [comment]
@echuber2 I'm not really familiar with how CSS selectors work, but if you're able to get a small example of this working, I can add it to the other elements mentioned here.

**Comment by eliotwrobson** [comment]
> Is there a reason we can't do whatever those examples are doing and avoid the need for `rounded-right` entirely?

Inspired by this, I deleted the `rounded-right` class from everything and it works completely as expected. Galaxy brain thinking, will remove from all elements.
