### ISSUE TITLE
Add recommended VSCode settings to docs

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#8279]
See title, these should be put in some section detailing contributing / developer best practices.

A starting point for this file is here: https://github.com/PrairieLearn/PrairieLearn/blob/49a99f5cefd7a13bb5ef73e49d30d03004be6d16/.vscode/settings.json

The linked configuration will run black + isort every time a Python file is saved. It would be great if there were a way to run prettier with a similar setup.

**Comment by mwest1066** [comment]
Some other bits that I have:
```
 "files.associations": {
    "*.ejs": "html"
  },
  "emmet.includeLanguages": {
    "ejs": "html"
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": false,
  "html.format.templating": true,
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.formatOnSave": true
  },
  "[sql]": {
    "editor.formatOnSave": true
  },
  "[python]": {
    "editor.formatOnType": true
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "javascript.updateImportsOnFileMove.enabled": "always",
```

**Comment by eliotwrobson** [comment]
Not needed since vs code configs have been added to the repo
