### ISSUE TITLE
Elements documentation is out of date

### ISSUE THREAD

**Issue by jakebailey** [PrairieLearn/PrairieLearn#829]
The main thing I've noticed is that `scripts` is actually `elementScripts` (and so on), and there are other undocumented paths. There may be other things to add.

**Comment by trombonekenny** [comment]
Missing docs for `pl_file_preview` and `pl_external_grader_results` (from https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/fibonacciUploadManual/question.html)

**Comment by mwest1066** [comment]
Resolved by #1554
