### ISSUE TITLE
Documentation inconsistency on "Running natively" page?

### ISSUE THREAD

**Issue by gmerritt** [PrairieLearn/PrairieLearn#8356]
At the bottom of the "Running natively" documentation page...

https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/installingNative.md
https://prairielearn.readthedocs.io/en/latest/installingNative/

...appears the text "**_To stop the server use Ctrl-C, and to restart it repeat the node server command above._**"

However, there does not seem to be any such explicit "node server command" elsewhere on this page?

There is, however, what seems to be a related command on the "Running in Production" documentation page:

`NODE_ENV=production node server.js --config /path/to/config.json`

https://prairielearn.readthedocs.io/en/latest/running-in-production/setup/
https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/installingNative.md

I'm not sure what sort of change might be preferred to correct what seems to be an inconsistency on the "Running natively" page (Reference the non-"node server" commands above on the page? Add in some "node server" command suggestion?) but it seems to me that something does not quite line up on the page as-is.

Thanks!

**Comment by nwalters512** [comment]
The documentation was recently changed from `node server` to `make start`; I can file a PR to update the description. I believe the "Running in production" docs also need to be updated.
