### ISSUE TITLE
For local dev, show http://localhost:3000/ on a separate console line

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#840]
Requested by Carl

**Comment by eliotwrobson** [comment]
@mwest1066 doesn't this happen now?

**Comment by mwest1066** [comment]
It currently says:
```
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
```

I can't remember why Carl requested this, or whether the current format is sufficiently "on a separate console line" for his needs. We haven't heard anything further about this issue in the last six years so I think we can close this issue.
