### ISSUE TITLE
Enhancement: show pl-manual-grading-only-element to graders on all submissions in the Manual Grading interface

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#8452]
`pl-manual-grading-only-element` is a super useful element ([documented here](https://prairielearn.readthedocs.io/en/latest/elements/#pl-manual-grading-only-element)) that was designed to work well with recent Manual Grading features.

However, it currently doesn't show up in auto-graded questions, even when you're looking at the submission from within the Manual Grading interface (and even when "gradingMethod": "Manual" in `info.json` and when `"manualPoints":1` in the `infoAssessment.json` file).
. 

<img width="1277" alt="Screenshot 2023-09-06 at 3 51 02 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/f310c321-27ea-450c-99c0-b2513fe1c5ae">

Here is the relevant bit that I think should be viewable on any question (if `<pl-manual-grading-only>` is specific in `question.html`) when looking at it from the Manual Grading interface.

```
<pl-manual-grading-only>
    This is a test
<markdown>
# Grader notes

This is a really tough question ... more students than we expect get this wrong!
</markdown>
<pl-manual-grading-only>
```

**Comment by nwalters512** [comment]
@firasm as far as I can tell, this is user error. If the HTML snippet you sent above is exactly what you have in your question, it's malformed: you need to close `<pl-manual-grading-only>` with `</pl-manual-grading-only>`, but you have two opening tags. I tested this with properly-structured HTML and it works as intended. Let me know if that's the case for you too.

**Comment by firasm** [comment]
HA! it was indeed user-error, but not the one you found (that was a copy/paste issue in GitHub).

I had a copy of the question in a different folder and wasn't updating the question I thought it was.

Indeed this works as expected...thank you and sorry! 🙏🏽
