### ISSUE TITLE
False errors from oversized-integer checking in Python JSON serialization

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8462]
In #6980 we added this check: https://github.com/PrairieLearn/PrairieLearn/blob/c3bf6a18c19324f5c97df65c79afd714f79e6c17/apps/prairielearn/python/zygote.py#L94 to prevent Python's bignum integers from leaking back into JSON and causing problems for `pl-integer-input`.

Unfortunately this check is falsely triggering for floating-point numbers as well. For example, entering the answer `2.8e16` into a `pl-number-input` will always trigger an error from `assert_all_integers_within_limits()` despite the fact that we aren't wanting this to be an integer at all.

**Comment by mwest1066** [comment]
Summarizing from https://prairielearn.slack.com/archives/C0XBTPZMZ/p1694185041384289

## Problem description

The problem occurs with `pl-number-input` (note this is not `pl-integer-input`) when the student inputs a floating point number string like `"2.8e20"`. This is passed as the `raw_submitted_answer` to `parse()` which parses this to a `submitted_answer` as `float(2.8e20)`. This is serialized to JSON as `280000000000000000000`. At this point everything is ok. We then proceed to `grade()`. During the call to Python, it parses the submitted answer as `int(2.8e20)` (a Python `bignum`) and grades it. Grading works ok because Python transparently converts between bignums and floats as needed. However, we now serialize the `data` structure back to JSON which calls `assert_all_integers_within_limits()`. This fails because we now have a large integer as the submitted answer.

In summary, we are currently unable to roundtrip a large floating point number from Python -> JSON -> Python -> JSON. This is due to the facts that:
1. Python serializes large floating point numbers and large integers to the exact same JSON (both `float(2.8e20)` and `int(2.8e20)` are serialized as `280000000000000000000`),
2. Python parses large numbers (without exponential notation or fractional part) as integers (bignums), and
3. we altered the serialization code path to error if large integers are present.

This problem was caused by #6980 which was fixing #3708. The fix was successful but it had this unfortunate side effect on the handling of large floating point values.

## Potential solutions

1. We could fix the fact that Python loses float/int type information when serializing to JSON. One way to do this would be to continue serializing floats as plain JSON values but change ints to serialize as `{_type_: 'int', _value_: ...}`, using the same format as for numpy objects and other special types. During parsing we could then parse values back to float or int as appropriate, retaining the type information. This would allow us to remove the `assert_all_integers_within_limits()` check because we would now be able to safely serialize bignum ints. In turn this would allow us to remove all the warnings and special behavior in `pl-integer-input` that only allows values up to 2^53 to be entered, instead allowing arbitrarily large integers.
2. We could fix the fact that Python parses large numbers as ints. Instead we could force it to parse all numbers over 2^53 as floats. In this case we would retain the `assert_all_integers_within_limits()` check during serialization to ensure that instructor code is not inadvertently trying to save a value that would not safely roundtrip. If we do this then I think we should alter `pl-integer-input` to raise a parse error if a submitted answer exceeds 2^53, rather than storing the submitted answer as a string in this case.
3. We could simply remove the check to `assert_all_integers_within_limits()` during serialization. If we do this then we should add additional safety checks to `pl-integer-input` to ensure that both the correct answer and submitted answer are within the 2^53 limit.

I currently tentatively favor approach (1) above.

**Comment by eliotwrobson** [comment]
As much as I'm a fan of (1), I think this is actually going to be quite difficult to implement without dealing with some hairy backwards compatibility issues. For example, if integers are used as keys in a dictionary that needs to be serialized, how can we ensure that this dictionary is preserved?

I lean towards option 2, as this means the least number of backwards compatibility issues. I am in favor of allowing for answers to `pl-integer-input` over the 2^53 size limit, since integers larger than this size aren't super uncommon, and the only technical limitation is backwards compatibility with existing custom grader code. However, my greatest concern is limiting backwards compatibility issues, so I don't really mind if this feature gets dropped, at the end of the day this can be done by custom instructor code. However, we should shoot for a solution so the data types for serialized objects are preserved, as this can be a real headache when debugging.

**Comment by mwest1066** [comment]
Discussed in dev meeting with @nwalters512 @eliotwrobson @jonatanschroeder @mwest1066: conclusion is that option (2) from https://github.com/PrairieLearn/PrairieLearn/issues/8462#issuecomment-1712927506 is the safest option (just the change to JSON parsing, not the changes to `pl-integer-input`). This option is safe because it's already a fatal error if we have large integers (or large floats) in the JSON, so all we are doing is choosing a particular way to handle these safely (convert them to floats).

It's a separate question about whether we should also alter the behavior of `pl-integer-input`, which we defer at the moment.

**Comment by eliotwrobson** [comment]
Docs about how to use a custom JSON decoder in Python: https://docs.python.org/3/library/json.html#json.JSONDecoder

**Comment by eliotwrobson** [comment]
@mwest1066 Now that the custom int parse function has been merged, should we make a separate issue for the `pl-integer-input` behavior? I think it should be a pretty straightforward change to make.

**Comment by mwest1066** [comment]
Fixed by #8492

**Comment by mwest1066** [comment]
> @mwest1066 Now that the custom int parse function has been merged, should we make a separate issue for the `pl-integer-input` behavior? I think it should be a pretty straightforward change to make.

Oh sorry, I missed this yesterday. See https://github.com/PrairieLearn/PrairieLearn/pull/8495#issuecomment-1726101377
