### ISSUE TITLE
c autograder expected output extra space

### ISSUE THREAD

**Issue by wrigjl** [PrairieLearn/PrairieLearn#8469]
I'm seeing some extra space when using the C autograder. The "expected" output box has some extra space before "BEGIN OUTPUT" (which comes from my tests). The bottom box is what I expect.

![image](https://github.com/PrairieLearn/PrairieLearn/assets/678779/885b80ec-f801-4e5d-ad8a-6f415d8a224d)

**Comment by jonatanschroeder** [comment]
A change to this behaviour to make it clearer is in progress, but one option you can use in the meantime, is to include the `msg=` option in the `test_run` call, to specify a custom message suitable for this case.
