### ISSUE TITLE
Occasional assessment instance constraint violations on exam start

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#849]
![error_processing_request](https://user-images.githubusercontent.com/875833/31318511-8a7e2b4a-ac19-11e7-8b63-59c9ba5e3cbe.png)

**Comment by trombonekenny** [comment]
Any idea what causes that?

**Comment by mwest1066** [comment]
Fixed by 640c2734f0011848b34fad55963b2c14d2d78b51
