### ISSUE TITLE
Winter break changes

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#853]
Matt:
* [x] Downgrade severs over break.
* [ ] Change Apache to mpm_worker.
* [ ] Enlarge root disk space in production.
* [x] Fix httpd log rotation in production.
* [x] Add log rotation for PL in production.
* [x] Upgrade to NodeJS 8 LTS
* [x] Delete `ShortAnswer` question type (currently in use by two BioE 201 questions).
* [x] Delete `File` question type somehow?
* [ ] Rename `Freeform` to `v3` in the DB.

Nathan:
* [x] Upgrade to Bootstrap 4
* [x] Upgrade to Font Awesome 5
* [x] Upgrade all `package.json` packages

Important grading changes:
* [x] Change sig figs grading to default to +/- 0.51 ULP.
* [x] Change default rtol/atol to 1e-2/1e-8.
* [ ] Change checkbox grading to give partial credit by default.

Dave:
* [x] Fix websockets to not poll.

Matt:
* [x] Add assessment `allowAccess` rule like `"schedulerExamID": 252` to link PL and PS exams.

Unclaimed:
* [x] Check whether students can add courses in production.
* [x] Python zygote support.
* [ ] Change `test()` to take a parameter for (correct, incorrect, invalid).
* [ ] Make "report issue" default to true and add more issue-handling buttons.
* [ ] Change `allowAccess` processing to be first-match rather than max-credit
* [ ] Change question `info.json` to `infoQuestion.json` with backwards compatibility.
* [x] Rename exampleCourse questions to "Symbolic input", etc.
* [ ] Auto-enroll everyone into exampleCourse?
* [ ] Add max-points per zone.
* [ ] Change assessment "credit" to be per-question, not per-assessment.
* [x] Eliminate numbering in multiple choice and checkbox elements? MW: I think we should keep it.
* [ ] Re-add a "grade all saved questions" button for exams.
* [ ] Only auto-close Exams in Exam mode.
* [ ] Stop running question code from within transactions. It's too dangerous if a question infinite-loops and we take up a DB client for this time (maybe forever for a v2 question).
* [ ] Restructure python libraries, for example putting `prairielearn.py` into `lib` (and make these libraries more visible to instructors?).

Not a high priority:
* [x] Upgrade to PostgreSQL 10 (not yet available on RDS) - note that v10 does stricter date checking, and will - for example - error on a Feb 29 date in a non-leap-year
* [ ] Unify homework and exam grading schemes?
* [ ] Consider removing increasing `value` for HW questions

**Comment by trombonekenny** [comment]
Delete `File` question type?

**Comment by eliotwrobson** [comment]
@nwalters512 should we go ahead and close this? Seems like almost everything has been done / is covered in other issues.

**Comment by mwest1066** [comment]
Yeah, many of these are either complete or captured in other issues. Close this one out.
