### ISSUE TITLE
Add download best submission CSV file

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#862]

**Comment by egunter** [comment]
It would be useful if there were a way to download a csv file containing the submission that PrairieLearn has as the basis of the grade it shows to the students.  Students will sometimes make a submission that gets full credit or nearly full credit, and then try a bunch of other stuff that doesn't compile or is significantly wrong afterwards and they will just leave it there and not replace it with the previous good answer.  However, they expect their grade to be based on the good submission, not the last submission even if regrading is done outside PL.
