### ISSUE TITLE
Empty save prevents future saves

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#864]
On E3 for CS 233, if you click "Save" without uploading a file (to create an empty submission) then clicking "Save" in the future will give an error.

**Comment by nwalters512** [comment]
@mwest1066 I assume this was with v2 questions? I haven't heard anything like this issue for years, even with the continued usage of v2 questions; I'm inclined to close it.

**Comment by mwest1066** [comment]
Yeah, this was pre-v3 so no longer relevant.
