### ISSUE TITLE
Possible race condition when rebooting workspaces during launch

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8648]
From a recent workspace launch log it looks like there might be a race condition where clicking "Reboot" at a certain point during the launch causes PL to end up with an incorrect workspace host assignment.

See https://us.prairielearn.com/pl/workspace/1257087/logs/version/1

**Comment by nwalters512** [comment]
Another instance of this: https://us.prairielearn.com/pl/workspace/1262453/logs
