### ISSUE TITLE
dev: Document newer functions (queryRow, queryOptionalRow)

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#8659]
The newer query functions (queryRow, queryOptionalRow, etc.) are not documented in the postgres package's README file.

**Comment by madisonbrading** [comment]
Hi! I am interested in contributing to this project and am wondering if there is a simple issue you would suggest I tackle to get a general understanding of how to contribute. not sure best place to reach out so decided to comment on a recent issue! Any help would be greatly appreciated.

**Comment by nwalters512** [comment]
@madisonbrading Thanks for your interest! I'd recommend either starting a [GitHub Discussion](https://github.com/PrairieLearn/PrairieLearn/discussions) or joining us on [Slack](https://www.prairielearn.com/slack) to discuss potential contributions.
