### ISSUE TITLE
coveralls might not be working on travis CI

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#870]
Saw this on the end of a Travis CI build report. Is coveralls reporting working?

![coveralls1](https://user-images.githubusercontent.com/10765199/31841909-403dfafa-b5b1-11e7-9764-cc779f55abf8.png)

**Comment by mwest1066** [comment]
@nwalters512 would you mind fixing this?

**Comment by trombonekenny** [comment]
Fixed in a recent PR.
