### ISSUE TITLE
Add option to use min element score as question score

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#874]
Chris Schmitz needs this for ECE 110 by Tuesday midnight.

**Comment by cdschmit** [comment]
Just to be clear, the assessment goes live at midnight. I don't plan on staying up that late...I'm a morning person.

**Comment by mwest1066** [comment]
Good to know :-) I'm working on this now.

**Comment by mwest1066** [comment]
Implemented in PR #858

**Comment by cdschmit** [comment]
Okay, just to be clear. I understand that i need to add some text to the server.py file...The info in green at PR#858 doesn't quite look correct to me...

**Comment by mwest1066** [comment]
Sorry Chris, this isn't merged yet. I'll email you separately when you should update your questions.
