### ISSUE TITLE
Cross/tick symbols not showing up for element score boxes in production

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#876]
The symbols that show whether a specific multiple-choice or checkbox answer is correct don't show up in production (at least for me with Safari). They do work locally.

**Comment by tbretl** [comment]
Can you give an example question? These symbols are showing up for me with Safari on production right now.

**Comment by tbretl** [comment]
(in ballToss2 and positionTimeGraph in the PL example course)

**Comment by tbretl** [comment]
Also for PQ4P4A in PHYS 100 on production, for example.

**Comment by mwest1066** [comment]
Huh, problem has vanished. I guess I was on a flakey network or something. Sorry for the noise!
