### ISSUE TITLE
Add option to suppress partial score labels for input elements

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#878]
Input elements now display their own partial scores. Sometimes, doing so doesn't make sense. For example consider the question `partialCredit1` in `PrairieLearn/exampleCourse`. It looks strange to have the input element say "0%" and to have the submission panel header say something like "23%".

**Comment by eliotwrobson** [comment]
@nwalters512 can this be closed? I think this is already possible by just emptying out/manually changing the partial scores dictionary for the corresponding input element.

**Comment by mwest1066** [comment]
It's true that we can do this via Python code, but this is pretty obscure for many instructors. I think it would be better to add a `"show-partial-score"="false"` attribute to (all?) elements.

**Comment by eliotwrobson** [comment]
@mwest1066 I'm not sure what the use cases would be outside of custom graded questions, where emptying out the partial scores dictionary is pretty straightforward in the grader code. I think it's a fine option to add, but doesn't seem useful outside of this specific context. Would anyone want to hide the partial scores for a question that doesn't use custom grading?

**Comment by jonatanschroeder** [comment]
This is a bit of a niche problem, but assume a question where the instructor wants to give an all-or-nothing set of items (https://prairielearn.readthedocs.io/en/latest/question/#the-partialcredit-option). In this case, the instructor may expect the student to provide a correct answer to all items before awarding points, and may want to reduce changes that students stumble upon the answer through trial and error.

Another option where this may be useful is in manually-graded questions using gradable elements (e.g., `pl-string-input`), where the grading of the question as a whole means individual items may not receive individual partial score tags.

I understand your point of view, and I agree that this option would not be used often outside of custom grading scenarios, but forcing an instructor to use a programmatic solution when a simple argument can be used instead may not always be a best approach, even when custom functions are already in place. There are instructors that may be trained to use very targeted pieces of code, often borrowed from others, and may not have enough expertise to expand on that code to provide such functionality.

So I'm in favour of keeping this issue open, though I understand that it can be kept a low priority. Note that elements like `pl-checkbox` and `pl-matching` already have options (`hide-score-badge`) that provide such functionality.

**Comment by eliotwrobson** [comment]
@jonatanschroeder that all sounds reasonable. I asked about closing this because a lot of these old issues describe features that have already been implemented, but if there you see a reasonable use case then this is a pretty simple thing to add to existing elements, so it makes sense to keep it open.

**Comment by eliotwrobson** [comment]
This has now been done for all of the most commonly used text input elements:

- pl-string-input
- pl-symbolic-input
- pl-big-o-input
- pl-integer-input
- pl-number-input
- pl-units-input

As a result, going to close this issue. Remaining elements that have not been as actively maintained will have this feature listed as part of follow-up refactor issues.
