### ISSUE TITLE
Consider adding an option to show full height to pl-file-preview element

### ISSUE THREAD

**Issue by derikvanschaik** [PrairieLearn/PrairieLearn#8793]
As a student who uploads code files to PraireLearn, it would be a nice enhancement if I could view my file in full without scrolling within the tiny preview box.  Currently I see something like:

![PrairieLearnScreenshot](https://github.com/PrairieLearn/PrairieLearn/assets/61720674/4d04bdff-40b8-418a-ae5e-60132438eb00)

This could be done by adding a 'Show in Full' button somewhere near the preview box and adding some css such as
```
[id^='file-preview'] .file-preview pre {
  max-height: 200px;
}
[id^='file-preview'] .file-preview.show-in-full pre {
  max-height: 100%;
}
```
https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/elements/pl-file-preview/pl-file-preview.css#L34

**Comment by harivamsi9** [comment]
Hey I can take up this issue!
