### ISSUE TITLE
Update readthedocs configuration file

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#8794]
As per https://blog.readthedocs.com/migrate-configuration-v2/, we need to update our docs configuration to a new version. At this point readthedocs is refusing to receive updates in the documentation based on the old version.

**Comment by trombonekenny** [comment]
The interesting part from this is

> When using a v2 configuration file, the local settings from the web interface are ignored.

Which is nice - to put all of those settings into version control - but it means someone who has access to how it's currently configured in the web probably needs to write the [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html)

**Comment by nwalters512** [comment]
I'll take care of this today.
