### ISSUE TITLE
Support authentication using Okta / OpenIDConnect

### ISSUE THREAD

**Issue by myriath** [PrairieLearn/PrairieLearn#8845]
Me and my senior design team at Iowa State University are using this to create a learning environment for one of our courses. We would like to be able to use ISU's existing Okta SSO infrastructure to connect to PrairieLearn.

We already have a mostly functioning setup in my forked repo (https://github.com/myriath/PrairieLearn/tree/oktaintegration), just trying to get the login button to appear when running in production. I think it has something to do with the supported providers in the postgres database. I am not very experienced with SQL and am wondering how I might fix that.

Initially, I started this for Okta alone but it has expanded to a more general OIDC interface using passport-openidconnect, with each part being configurable.

**Comment by myriath** [comment]
I believe the issue with SQL has been resolved, so the OIDC login should be fully functional now

**Comment by nwalters512** [comment]
As discussed on #8851, we won't be adding OIDC as a login method at this time.
