### ISSUE TITLE
Do not present 'stale' variants

### ISSUE THREAD

**Issue by ppannuto** [PrairieLearn/PrairieLearn#8860]
We've run into the issue a few times now where a student reports an issue with a question, we fix and deploy the underlying problem, and yet new students keep getting presented with broken, already-fixed questions.

While the 'nuclear option', i.e., update the question `uuid` works to wipe out all variants, most often, we have a situation where it's only a very rare corner case that we needed to fix. We don't want to remove the successful variants folks have already done for homework, we just need to delete a few specific variants, or really just not allow buggy variants to be presented moving forward.

Specifically, I think a rule that would satisfy our needs is that a new instance presented to a student should require that `timestamp(variant generation) >= timestamp(server.py)`; older variants should simply be skipped / not presented to any new students.

**Comment by eliotwrobson** [comment]
I think this would be fixed by #3552, and this issue is essentially a duplicate of the issue that PR resolves.

**Comment by jonatanschroeder** [comment]
> Specifically, I think a rule that would satisfy our needs is that a new instance presented to a student should require that `timestamp(variant generation) >= timestamp(server.py)`; older variants should simply be skipped / not presented to any new students.

To clarify a misconception: students will only be presented with variants created before a specific timestamp if they opened the variant before that particular timestamp. If a student that never opened a variant starts one (or that starts a new variant after running out of attempts in the previous variant), a new variant is created. The issue that is probably causing this is that older, broken variants cannot be dismissed by students.

Also, using the timestamp of server.py is not necessarily a good way to determine if a variant is stale. I've had cases where I was able to update server.py (or question.html) after students had already started, and the old variants were still valid. server.py includes functions that don't necessarily affect question generation, like changes in parse/grade function.

**Comment by ppannuto** [comment]
I agree #3552 looks great, but it also looks large and complex. I was hoping for something simpler that could be deployed on the order of days/weeks to fix the immediate challenges faced this term.

---

re: misconception, I think I probably used the wrong language, but trying to express the desired effect differently, I might say 

   "a variant should never be displayed to a student, for any reason, if its creation timestamp is older than any of the materials used to create the variant".

This is a coarse-grained fix that would certainly invalidate more variants than is strictly necessary, but is also a very simple rule which could be a short-term bridge until something more capable like #3552 can come into being.

Perfect is the enemy of good for me here—what is the minimum viable solution that could be deployed ASAP?

**Comment by nwalters512** [comment]
> "a variant should never be displayed to a student, for any reason, if its creation timestamp is older than any of the materials used to create the variant".

We are simply not going to implement this. Many instructors regularly release minor fixes to existing questions in a backwards-compatible way that does not require the recreation of the entire variant. We are not willing to break existing workflows that instructors rely on.

#3552 is going to be the foundation of a long-term fix to this problem. I can imagine that we could build finer-grained options on top of it, such as "invalidate any variant created before XYZ".

#3552 isn't particularly complex, though it will require some care to deploy; it just hasn't received much love lately. I'll start the work to revive it.

**Comment by nwalters512** [comment]
I've started working on getting #3552 into a deployable state, starting with #8881. We've let this PR sit there for too long. It's time to ship it.

**Comment by ppannuto** [comment]
I'll close this issue then — no reason for a short term hack if the real fix is more imminent now. Thanks!
