### ISSUE TITLE
console log not visible

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#889]
In question `QuaternionToMatrix` in course `pl-cs498sl`, there is an error. The "Console log" for this error is visible to `tbretl@illinois.edu` but not to `cfan12@illinois.edu`. Seems also to be the case in other courses (e.g., `pl-cs498pl`). Both the "Issue" and the "Associated data" are visible to both.

This is likely a permissions problem. It appears to have been introduced sometime recently.

**Comment by mwest1066** [comment]
Same as #956
