### ISSUE TITLE
Programmatic editing of `info*.json` files

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8898]
We plan to add web UI for editing the data in `info*.json` files. In the simplest cases this will include UI to edit things like the `title` in `infoCourse.json`, while in more complex cases we'll have the ability to edit things like the list of questions in an assessment.

To implement this we'll need to be able to programmatically modify the contents of the `info*.json` files to make the changes. I can think of two basic approaches to this, as follows.

## Strategy 1: modify the JSON, sync to the DB

For this strategy we would read the `info*.json` file from disk, modify it, write it back, and then call `syncDiskToSql()`.

#### Pros:
* This fits with PL's traditional approach of regarding the JSON as the source of truth.
* We could get started quickly with minimal new code, because it relies on our well-tested `syncDiskToSql()` functionality.
* For simple changes, like changing the `title` in `infoCourse.json`, this strategy would be very straightforward.
* It's possible to easily support properties which aren't currently synced to the DB, such as the `comment` property.
* We could make the minimal necessary change to the JSON file. In principle we could even retain (most of) the whitespace in the existing file if we wanted.

#### Cons:
* Changes are quite slow, because we need to run through the full `syncDiskToSql()` process. There are ways of speeding this up (implementing partial sync, deferring the push to GitHub to a later background job), but it's always going to be slower than making changes directly in the DB.
* Identifying the correct part of the JSON to change will require specialized code in more complex cases. For example, to edit the points for an assessment question, we will need to figure out which entry in the JSON corresponds to the `assessment_question_id` that we want to alter. This code feels like it could be fragile and hard to test.

## Strategy 2: modify the DB, serialize to JSON

This strategy would make the change directly in the DB and then call a (hypothetical) `syncSqlToDisk()` function, which might actually be functions like `syncQuestionSqlToDisk()`, `syncAssessmentSqlToDisk()`, etc.

#### Pros:
* Updates would be very fast (assuming sync is allowed to proceed in the background).
* The code to make updates would generally be very straightforward.

#### Cons:
* We'd need to write serialization code for the different types of objects and test it. We'd presumably want tests that check the DB->JSON->DB roundtrip (rather than JSON->DB->JSON).
* We would need to check cases where there is information in the JSON file that isn't currently synced to the DB, and start syncing this. For example, the `comment` properties in JSON objects.
* To make this fast we'd want to do the sync in the background, after completing the response. This would require new code to support background syncing in general and also we'd want some kind of version number so that we can prevent any more changes while a `syncToDisk` is still pending.

## "Upgrading" JSON

Historically PL has never altered any of the `info*.json` files on disk, which means that we need to be fully backwards compatible with all schemas that have ever existed for these files. Over time this is a growing burden. It would be nice to have a plan such as:
1. Initially new options in an `info*.json` file are opt-in.
2. At some point, we auto-convert existing `info*.json` files to use the new schema.
3. After some long time (two years?) we remove support for the old schema.

The above "upgrade" functionality could be implemented with either strategy 1 or 2 above for editing JSON files, but I feel like this would be simpler with strategy 2. With strategy 1 we'd need to handcraft upgrade code for each type of change we wanted to make, whereas strategy 2 gives us this upgrade functionality essentially for free.

## My thoughts

I currently think that strategy 2 is preferable. It feels like more work up front (the need to write and test the `syncSqlToDisk()` functions, and to verify that we aren't losing any information from a JSON file by roundtripping it JSON->DB->JSON) but this seems much cleaner than having a bunch of janky special-case code to modify bits of JSON files. I also like the general idea of regarding the DB as the source of truth and the JSON as a serialization of it.

## Questions

1. Do we care about trying to make minimal edits to people's JSON files? That is, should we try and preserve whitespace and things like that, or should we go to the other extreme and prettify all JSON all the time? The answer to this might push us towards strategy 1 or 2.
    - As @jonatanschroeder points out, we already do programmatic editing of JSON files when we edit QIDs in the UI. This updates the QIDs in all `infoAssessment.json` files and does not attempt to preserve whitespace. Based on this precedent and the fact that it hasn't caused any complaints over the years, we decided to continue to not worry about preserving whitespace. We thus answered this question with a "no".
3. What do we think about background sync? I think we will want to do the "sync to GitHub" part in the background anyway when editing `server.py` and other files, which at the moment have annoyingly long wait times when you save a change.
4. Am I forgetting about any cases of information in the JSON file that is not 1-to-1 synced to the DB and which would be hard to regenerate during a DB->JSON sync? Things like `comment` properties are easy because we just need to add this column to more tables, but there might be cases that aren't so straightforward.
5. What's everyone's general opinion about strategy 1 versus strategy 2? Are there other strategies than these two, or other variants of these strategies that we should consider?

**Comment by jonatanschroeder** [comment]
One concern with option 2 is the possibility of Git conflict changes. If the sync happens in the background, it would fail without an immediate feedback to the instructor. Even if there is some way to provide this feedback (issue or similar), it would require the instructor to check that eventually, which is error prone. If the sync happens in the foreground, you lose the main advantage of this approach.

Personally I'd be in favour of option 1 but with some review of the sync process that allows partial sync (e.g., only the affected question or assessment). This would require some rethinking of the sync process, since many of the processes rely on sync happening in a specific order (e.g., the assessment sync relies on the mapping of QID to question ID from the question sync), or that specific sync have already been done (e.g., changing the grading method does not trigger a recomputation of the manual/auto points process since it's assumed that assessment sync will run soon after). That said, this kind of review would have to happen with option 2 anyway as well.

**Comment by nwalters512** [comment]
We've decided to go with option 1, and this has already started to be implemented on e.g. the course settings and question settings pages!
