### ISSUE TITLE
make the return / enter key map to "save" by default and not to "grade"

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#890]
The return key and the enter key map to "grade" by default (e.g., after typing a number into a `pl_number_input` element). This means that if a student presses one of these keys "by accident," then their submission gets graded.

(A wonderful recent version of this is - "the mouse wire pressed enter on the numeric keypad.")

It would be better if the return key and the enter key both mapped to "save" (or nothing) by default.

**Comment by mwest1066** [comment]
Fixed in #2156
