### ISSUE TITLE
Extra features for client fingerprints

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8924]
We are intending to merge #8798 as an MVP and then follow up with more features. These include:
* Store fingerprints on more events. See https://github.com/PrairieLearn/PrairieLearn/pull/8798#discussion_r1401375855. For example, when we create a variant and when we create an assessment instance. Maybe when we score questions and assessment instances (but maybe not, because this can happen out of band).
* Use different colors for each fingerprint number in the assessment instance log table: https://github.com/PrairieLearn/PrairieLearn/pull/8798#discussion_r1401372246
* Add a news item or blog post: https://github.com/PrairieLearn/PrairieLearn/pull/8798#discussion_r1401366866
* Add fingerprint information to the CSV export: https://github.com/PrairieLearn/PrairieLearn/pull/8798#discussion_r1410023829

**Comment by jonatanschroeder** [comment]
One more request: change the popover that includes the IP to allow the text inside to be selected/copied.

Another interesting option: make the IP address a link to some service that provides additional info (e.g.: https://client.rdap.org/?type=ip&object=15.156.29.87).

**Comment by mwest1066** [comment]
I think these are now all resolved? @jonatanschroeder and @mylesw27?

**Comment by mylesw27** [comment]
> I think these are now all resolved? @jonatanschroeder and @mylesw27?

Yes, with the exception of a news item or blog. However, if I remember correctly there was a snag on doing this? I can't recall entirely but if we think this is still useful, I can write something up about client fingerprints.

**Comment by mwest1066** [comment]
Correct, we are still waiting on @nwalters512 to decide whether (that is, when) he wants to set up a blog on the main website. For now I think we can close this issue, however.
