### ISSUE TITLE
Don't show true answer for singleVariant questions

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#895]

**Comment by trombonekenny** [comment]
Would you add that logic here? https://github.com/PrairieLearn/PrairieLearn/blob/b836b0002af3c1bd945e41ad67b5d523c829b3c4/lib/question.js#L1102

**Comment by mwest1066** [comment]
Yes, that looks like the right spot.

**Comment by trombonekenny** [comment]
Actually it's not. singleVariant questions don't trigger that branch. They don't get the "Try question again" button ... they just stick to whatever was tried in them previously.

And they don't show the Correct answer panel (at least in my testing), so this bug is already fixed in prod.

**Comment by mwest1066** [comment]
Sounds like this is fixed already.
