### ISSUE TITLE
New variants can be created when assessment is not active

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#9030]
Steps to reproduce:

- Switch to "Student view" (_not_ "Student view without access restrictions").
- Start HW1 in the test course. Do not open any questions.
- Edit the assessment access rule to be just `"active": false`; sync the course.
- Click one of the questions.
- Observe that a new variant is created even though the assessment isn't active.

This can be reproduced for exams as well.

This behavior is not necessarily problematic, as students won't be able to do anything that gives them points (that is, they can't submit to it). However, this behavior would be confusing to anyone who is reviewing the assessment instance log, of if creating a variant generates an issue when the assessment isn't active. Instructors might rightfully consider that `"active": false` implies that an assessment is immutable.

It is possible that this behavior is intentional, but I suspect it's just sort of an accident of how things work.

If this is _not_ intentional behavior, I'd like to propose some changes that will fix it:

- If an assessment is not active and a user opens a question for which there is no existing variant, display a page stating that new variants can't be created.
- If a Homework assessment is not active and user opens a question for which there _is_ at least one existing variant, show the most recent variant instead of generating a new one.
  - This behavior is necessary because visiting the `pl/course_instance/##/instance_question/##` route will create a new variant if there are not any open variants. In _general_ this is acceptible behavior, but I'm proposing that it's undesirable when an assessment is not active.

**Comment by mwest1066** [comment]
> It is possible that this behavior is intentional, but I suspect it's just sort of an accident of how things work.

Correct, this was an oversight when implementing `"active":false`.

I agree with your proposed fixes. As @jonatanschroeder  pointed out, this might also be a good time to implement this proposed fix: https://github.com/PrairieLearn/PrairieLearn/issues/1718#issuecomment-605531705
