### ISSUE TITLE
Issue with VSCode Workspace Persistence in Quiz Assessment: Incorrect File Handling on Question Transition

### ISSUE THREAD

**Issue by harivamsi9** [PrairieLearn/PrairieLearn#9048]
I believe this is a bug.

So, I create a Quiz assessment, and I have added two questions in it. Both of these questions are VScode Workspace questions (different workspaces for each).

So what I noticed is that when I open 1st question (getGreenTintedValues) in the workspace, and fill out the answer, and click "save and grade". It is working as expected so far, and performing the grading. (Note: do not close this file in the editor now. You may close the tab/browser, but not the file which was open in the editor in this question workspace.)

Now, I move on to the 2nd question (getAverageRedPixelValue.py), and click on "open workspace". Now, I can see something like 
![image](https://github.com/PrairieLearn/PrairieLearn/assets/44733128/d766667e-2e55-4536-a281-69649cd26a7f)

It says that the file related to only the 1st question could not be opened. I have to close this, and then open the actual 2nd question python file.

I believe the expected functionality should be something like either: 1. show the homepage on the VSCode all times when opened initially, or 2. Show the file which user will have (or we can give them an option to open a file by default when they launch initially)

Please have a look into this, and let me know.

**Comment by nwalters512** [comment]
I'm actually not able to reproduce this. Can you share links to these two questions and confirm exactly which Docker image you're using?

**Comment by echuber2** [comment]
Similar to a known issue in CS 421: https://github.com/PrairieLearn/PrairieLearn/issues/5076

**Comment by nwalters512** [comment]
@harivamsi9 following up again: were you able to reproduce this with an officially-supported image? If not, I'll close this as there's nothing actionable for us.

**Comment by harivamsi9** [comment]
Hi, for some reason, I am unable to use codecom/code-server, it shows this error. 
<img width="625" alt="image" src="https://github.com/PrairieLearn/PrairieLearn/assets/44733128/45a4d0e9-3ee5-4b76-ba3c-00d555cadaa1">

**Comment by nwalters512** [comment]
This sounds like an unrelated issue and one that isn't actually an issue with PrairieLearn itself; I suspect your workspace configuration is missing something. If you'd like support getting your workspace working, please start a GitHub Discussion with your question's JSON configuration file and anything you've already tried. I'm going to close this issue since I don't think there's anything actionable for us.
