### ISSUE TITLE
Add checkbox at start of exam to confirm identity and enrollment

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#908]
[ ] I am STUDENT NAME (NETID) and I am enrolled in COURSE NAME and have permission to take this exam. I have not gained unauthorized access to any exam information and I will not convey any information about this exam to any person other than official course staff. I am aware that I am bound by the UofI Student Code, particularly sections XXX and YYY relating to the conduct of exams and I will be subject to the full penalties for academic integrity violations, up to and including termination from the university.

Disable "start exam" button until the above checkbox is checked.

**Comment by tdy** [comment]
Related/same with #967?
