### ISSUE TITLE
Undefined role listed in public view of shared question

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9094]
Pages like https://us.prairielearn.com/pl/public/course/1305/question/9105205/preview show undefined beside the user name in the top-right corner, in what (I assume) is expected to be the role in the course.

<img width="203" alt="image" src="https://github.com/PrairieLearn/PrairieLearn/assets/1004907/cae698c7-4d92-4204-955e-64560756b709">

**Comment by mwest1066** [comment]
@SethPoulsen can we add this to #9397?

**Comment by SethPoulsen** [comment]
I've added a new checkbox for it, thanks.
