### ISSUE TITLE
cross-course question linkage

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#914]
Assuming the permissions are available (not sure where or how you'd set them), allow assessments to link into other courses' questions.

Let question owners see aggregate usage and scores, compare across courses

**Comment by nwalters512** [comment]
@SethPoulsen is now working on this feature! A WIP PR is here: #6770. Additional work is tracked in this project: https://github.com/PrairieLearn/PrairieLearn/projects/22. I'm going to close this issue in favor of the smaller, more granular ones that Seth has been creating.
