### ISSUE TITLE
Add make to PL docker software

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#918]
https://github.com/PrairieLearn/PrairieLearn/blob/b80d1fefa719e4e9e51ca684440ab9aa89e4329e/Dockerfile#L16

If I wanted to add `make` to the PL docker, is that line the right place to insert it?

I use the PL container for PL and PS development and it would be handy to have make preloaded in that environment.

**Comment by nwalters512** [comment]
Yeah, you'd want to make it a part of the big `yum install` command.

**Comment by trombonekenny** [comment]
Added a while ago.
