### ISSUE TITLE
Figure not showing within pl_multiple_choice

### ISSUE THREAD

**Issue by xiaoruipearl** [PrairieLearn/PrairieLearn#920]
Here is an example where the figure will not show up:
<pl_multiple_choice>
    <pl_answer> <pl_figure ......> </pl_answer>
</pl_multiple_choice>

Note that if it was a pl_checkbox, the figure will show.
(checkbox sometimes is not working as well)

**Comment by mwest1066** [comment]
Fixed with new HTML renderer
