### ISSUE TITLE
reduce messaging about automatic saving within workspaces

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#9213]
![Screenshot 2024-01-07 at 5 36 24 PM](https://github.com/PrairieLearn/PrairieLearn/assets/9003346/d123873b-0f45-4824-b6de-74ec512d6e9f)

The current messaging within workspaces could be misleading to students. More specifically, automatic saves are done *intermittently*, so I could see a situation where a student loses work because they expected instantaneous automatic saving.

Talking to Nathan a bit, messaging about saving is tricky because this messaging applies across all varieties of worksapces (JupyterLab, VSCode, etc) so one solution would be to simply remove any messaging and have instructors give specifics about how saving should work in their courses. Or, a general message to save often, and save before exiting a workspace.

**Comment by caitlinchee-kirkpatrick** [comment]
Hi there! After reading the issue, I propose we can change the text message from "Your files are automatically saved" to a message that tells students to remember to save before exiting as you said. We can also go one step further and provide a popup to remind them to save their work before leaving if they try to close their tab. What do you think?

**Comment by caitlinchee-kirkpatrick** [comment]
Perhaps we can advise the instructor to tell their students at the beginning of the course to save as they would know what workspaces are being used. However, I agree that we should just remove the text to avoid that risk. Does this sound reasonable?

**Comment by caitlinchee-kirkpatrick** [comment]
This sounds like a good solution. I will work on this and get back to you!
