### ISSUE TITLE
Unexpected behaviour with `multipleInstances` is set to true before access rule applies

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9214]
For this assessment, the current time is Sun Jan 7th, 22:56:00

```
{
    "uuid": "adceead4-cf48-4e31-bf73-3a8ea2a90ade",
    "type": "Exam",

    # snipped 

    "multipleInstance": true,
    "allowAccess": [
        {
            "startDate": "2024-01-01T00:00:00",
            "endDate": "2024-05-31T00:00:00",
            "active": false
        },
```

I see the "New Instance" button when I don't think it's appropriate:

<img width="1311" alt="Screenshot 2024-01-07 at 10 54 19 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/283eac25-ebd6-4bd6-8d7f-ef7a6e0203d2">

Fair enough that when you try to start it, you can't actually start it:

<img width="1306" alt="Screenshot 2024-01-07 at 10 54 35 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/7583c56f-6912-4cdd-8b31-8428450787c4">

--------

Removing `"multipleInstance": true,`

```
{
    "uuid": "adceead4-cf48-4e31-bf73-3a8ea2a90ade",
    "type": "Exam",

    # snipped 

    "multipleInstance": true,
    "allowAccess": [
        {
            "startDate": "2024-01-01T00:00:00",
            "endDate": "2024-05-31T00:00:00",
            "active": false
        },
```

produces the correct behaviour:

<img width="1536" alt="Screenshot 2024-01-07 at 10 53 27 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/d1331ef6-9bfa-4560-a6b2-9864802c577b">

Actually, now that I think about it, this is probably because of the infamous "if an access rule doesn't apply and none is listed, then it defaults to something specific."

**Comment by nwalters512** [comment]
@firasm would your expectation be that the "new instance" button is hidden entirely, or disabled? I guess I lean towards removing it.

**Comment by nwalters512** [comment]
Removing it leaves kind of a weird gap in the column, and it's not clear that it's because this is a multi-instance assessment:

<img width="1131" alt="Screenshot 2024-01-10 at 15 08 25" src="https://github.com/PrairieLearn/PrairieLearn/assets/1476544/c2b61b5c-888e-44fc-b3dd-c4d12afe0b9e">

Maybe a disabled link is better?

This is another case where #2185 would be nice, we wouldn't even be asking this question if we had moved multiple instances into a subpage.

**Comment by firasm** [comment]
I think it should say the truest thing possible, which in this case, is "Not Started" consistent with behaviour when students don't have access to it.

**Comment by jonatanschroeder** [comment]
> I think it should say the truest thing possible, which in this case, is "Not Started" consistent with behaviour when students don't have access to it.

Now what should be shown if there are existing instances, but you cannot create any new ones anymore? "Not Started" does not reflect that case.

**Comment by firasm** [comment]
If there are existing instances, then it would either show their Score (autograded), Pending (any manual grading in it), or "Score Not Shown" - depending on the access rule. 

Maybe I'm misunderstanding it.

**Comment by firasm** [comment]
*update* ohhh I see now. A new row is created when there's a new instance possible. 

I see... yea that's tricky, no good options 🤷🏽‍♂️

**Comment by nwalters512** [comment]
> Maybe what would be best is if students don't have the ability to create new instances, that the button (and the row) just not be there. The previous instance would still be there with the score or pending or not shown.

This doesn't match the behavior of single-instance assessments, and wouldn't be compatible with access rules that use `"active": false` to show the assessment to students _before_ they get a chance to start it.
