### ISSUE TITLE
hideInEnrollPage should be true by default

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9216]
I think I've brought this up before, but thought I'd finally create an issue for discussion.

IMHO, the `hideInEnrollPage` setting should be true by default. Students shouldn't be able to enrol into courses if people forget to add this setting 🙃. 

Several arguments for:

- The potential negative effects of this are substantially higher than the minor inconvenience if instructors expect students to be able to self-enrol and the students aren't able to (unless settings change)
- The template course doesn't have this setting set to true, so most people wouldn't even know about it
- There's no way to remove students if they accidentally enrol
- Most PL courses (at least at UBC) aren't MOOCs and enrolling in the course has specific meaning

Only one argument against:

- It's the reverse of current behaviour

**Comment by nwalters512** [comment]
We haven't written up specific plans for this yet, but: the enroll page is going away entirely fairly soon. I don't think it's worth the effort to change the behavior or defaults of this flag.

**Comment by firasm** [comment]
Oh good! Even better. 

I'll close the issue.

**Comment by nwalters512** [comment]
I opened #9217 so we can start discussing the removal of the enrollments page and related changes.
