### ISSUE TITLE
More than 10 rubric entries in Manual Grading results in duplicates shortcuts

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9231]
I'm trying to add in a rubric from an existing assessment and it has over 10 entries. When I added the 10th rubric entry, it recycled the shortcuts to start at 1. When I then pressed `1`, both rubric items were selected.

Several resolution options: 

- Doing two digit rubric shortcuts? This would probably pretty complicated (delays between etc...)
- The shortcuts can move to a Modifier Key + letter? 
- Have no shortcuts beyond 9?

<img width="549" alt="Screenshot 2024-01-14 at 6 24 16 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/d6accdc3-5623-4f0b-a172-6ac3e9c2bfec">

**Comment by jonatanschroeder** [comment]
Did a quick test, seems like an off-by-one error. The 11th rubric item has a keyboard shortcut, the 12th doesn't. Fix is simple, should come shortly.
