### ISSUE TITLE
Example does not exist anymore in docs/oldQuestion.md,

### ISSUE THREAD

**Issue by justindhillon** [PrairieLearn/PrairieLearn#9234]
In [docs/oldQuestion.md](https://github.com/PrairieLearn/PrairieLearn/blob/master/docs/oldQuestion.md), the example to [fibonacciExternal](https://github.com/PrairieLearn/PrairieLearn/tree/21be1db08978b6f8a8ca76c1e53681fe2ebe2fce/exampleCourse/questions/fibonacciExternal) does not exist. We do however have [fibonacciEditor](https://github.com/PrairieLearn/PrairieLearn/tree/21be1db08978b6f8a8ca76c1e53681fe2ebe2fce/exampleCourse/questions/fibonacciEditor) and [fibonacciUpload](https://github.com/PrairieLearn/PrairieLearn/tree/21be1db08978b6f8a8ca76c1e53681fe2ebe2fce/exampleCourse/questions/fibonacciUpload). Should I change the example to one of those? Or is there a diffrent way we want to deal with this?

These broken links where found with [link-inspector](https://github.com/justindhillon/link-inspector). If you find this pr useful, give the project a star ⭐

This is what docs/oldQuestion.md looks like right now:

## `File` question type

- Example: [`fibonacciExternal`](https://github.com/PrairieLearn/PrairieLearn/tree/21be1db08978b6f8a8ca76c1e53681fe2ebe2fce/exampleCourse/questions/fibonacciExternal)
- Required files: `info.json`, `question.html`, `answer.html`
- Options schema: [`File` options](https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/src/schemas/schemas/questionOptionsFile.json)

**Comment by nwalters512** [comment]
Neither `fibonacciEditor` nor `fibonacciUpload` are actually File-type questions. I'd recommend searching through the Git history to find the `fibonacciExternal` question that's referenced there and updating the link to point to that.

**Comment by justindhillon** [comment]
Thanks @nwalters512! In PR #9235 , it now points to fibonacciExternal.
