### ISSUE TITLE
Invalid instructor question links

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#9246]
Reported by @firasm

On [this page](https://ca.prairielearn.com/pl/course_instance/6665/instructor/assessment_instance/1156383) the "instructor view" link for the question is https://ca.prairielearn.com/pl/course_instance/6665/instructor/question// -- note the missing `question_id` between the last two slashes. All other links work fine.

Firas reports that both the AID (the assessment directory name) and the QID were renamed after the students completed their work. But that seems to be irrelevant because this actually seems broken on all instructor assessment instance pages.

## Code

The missing value is `instance_question.question_id` in the following line:
https://github.com/PrairieLearn/PrairieLearn/blob/8b4a523eb62877cb309df496127d6e879ec9a11a/apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.ejs#L170

I think the problem was introduced by #9072 -- the `select_instance_questions` query in `instructorAssessmentInstance.sql` returns a `question_id` but it's missing from this type:
https://github.com/PrairieLearn/PrairieLearn/blob/8b4a523eb62877cb309df496127d6e879ec9a11a/apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.js#L49-L53

There seem to be a lot of columns returned by that query that are missing from that type?

## Screenshot of the page above

![image](https://github.com/PrairieLearn/PrairieLearn/assets/875833/2fa3aec2-4418-4f71-a73b-699b45c07fc5)

**Comment by firasm** [comment]
Thanks @mylesw27 !
