### ISSUE TITLE
Review student page behaviour for empty groups

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9255]
This is separated from #9106 to allow that PR to proceed without further changes. #9106 fixes #4161, allowing instructors to view student pages even though they are not in the corresponding group. However, this does not properly work when the group is empty. This is related to the fact that `groups.ts` has queries that assume that the group has at least one member, e.g., https://github.com/PrairieLearn/PrairieLearn/blob/156482054aa06426fcb5ee14fc1e0f074fd3f39b/apps/prairielearn/src/lib/groups.ts#L116-L117

There may be other cases where this is an issue as well. This is low priority (as I assume checking assessment instances for empty groups is not an important need of instructors), but should be handled at some point soon.

**Comment by nwalters512** [comment]
I'll take care of this. I think it's a mistake to try to use the same query for fetching both group members and config. I've managed to reproduce the problem with #9106 as a starting point, so I can keep fixing things until they work.
