### ISSUE TITLE
Teach `sqldb.call()` to use named arguments

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#927]
If passed `params` as an object, `call()` should use the named-argument syntax: https://www.postgresql.org/docs/10/static/sql-syntax-calling-funcs.html

The SQL will look like:
```sql
SELECT * FROM func(param1 => $1, param2 => $2)
```

**Comment by trombonekenny** [comment]
Tracking in PrairieLearn/PrairieLib#3
