### ISSUE TITLE
pl-integer-input not using the configured base

### ISSUE THREAD

**Issue by steven-wolfman** [PrairieLearn/PrairieLearn#9288]
I have a question that uses a `pl-integer-input` with base 16. When a student inputs a very long hexadecimal value like `FFFFFFFFFFFFFFD8`, the code ends up crashing inside PL at this line: 
https://github.com/PrairieLearn/PrairieLearn/blob/f9b268e686ae916562f2fc4c74ff08cf1902e8ea/apps/prairielearn/elements/pl-integer-input/pl-integer-input.py#L161

I'm not sure if this would work anyway, but it also seems likely that this should use `base` in this case, as happens in the other `int` conversions.

**Comment by eliotwrobson** [comment]
Do you have screenshots of the error message? Does it happen with smaller hex values?

**Comment by steven-wolfman** [comment]
Sure..

<img width="696" alt="image" src="https://github.com/PrairieLearn/PrairieLearn/assets/982149/3ecc9adf-5dec-4dbf-874e-528ac5d9c015">

That's a live student submission. So, I omitted the user ID.

It only happens with larger values. Specifically, I believe this is how the rendering code re-renders a very large input to the screen when it was left as string in the `submitted_answers`.

Ah.. and I guess that means we probably do not want to try to convert this to `int` at all, since it will just fail again? Certainly, I don't think it should be trying to convert this to an `int` in the wrong base, however :(

**Comment by eliotwrobson** [comment]
This has to do with some subtleties related to how the data in this element gets stored for oversized answers. I'll have to sit down and play with it some, it's unfortunately a little confusing.
