### ISSUE TITLE
init script does not dereference variable name

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#9296]
Just curious, should this be `$DEV` and not just `DEV`? If nobody noticed then maybe it's not a variable used by anyone.

https://github.com/PrairieLearn/PrairieLearn/blob/177f25b770126533e8ac727cf8472711ad9220e0/docker/init.sh#L10

**Comment by jonatanschroeder** [comment]
Fixed in #9953.
