### ISSUE TITLE
Instructors cannot create a group with themselves in it

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#9297]
This can be considered a regression, possibly introduced by #9095. Instructors may want to join groups to test out group functionality, which is a valid use case. Creating a group as an instructor, whether that's via the "Add a group" button on the assessment groups page or via viewing the assessment as an instructor, fails with the following flash message:

> Failed to create the group XYZ. User user@example.com is not enrolled in this course

**Comment by jonatanschroeder** [comment]
To resolve: add call to users_is_instructor_in_course_instance here:
https://github.com/PrairieLearn/PrairieLearn/blob/master/apps%2Fprairielearn%2Fsrc%2Flib%2Fgroups.ts#L239

And only throw exception of it returns false.
