### ISSUE TITLE
Wrong judgement when redefined a variable

### ISSUE THREAD

**Issue by Nakasu-ksm** [PrairieLearn/PrairieLearn#9304]
In my work I trying to write a code after this comment
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
In the question it not ask not to defined a variable again
I don't think there's anything wrong with my code, I think it's more a matter of judging the code, ask if the code is judging the memory address of the variable.

But there is a problem with my code displaying after scoring, it shows the result in error, the content is returning the next value of the enum via an enum

here the example of the code

first the lock code
xxx = Enum('xxx', ['xxx', 'xx', 'x'])

#grade (write your code in this cell and DO NOT DELETE THIS LINE)
xxx = Enum('xxx', ['xxx', 'xx', 'x'])

(I redefined the enum, But it looks like there is a problem with the redefinition, but as a matter of principle python reassignments don't change the memory address, I don't think there should be an error in judgment)

**Comment by nwalters512** [comment]
It sounds like you're a student in a course, is that right? This isn't a suitable place to ask for help. Since grading is controlled by your instructor, you should contact your course staff/instructor for any questions about how your work was graded.
