### ISSUE TITLE
Allow students whose group role does not have submission permission to see past submissions

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#9328]
This is a follow-up to the group roles permissions (https://github.com/PrairieLearn/PrairieLearn/pull/9106). Students have been requesting, and we agree, that students who have view access to a question but not submission access should be able to see past submissions. Currently, only the student who has submission access is able to view past submissions. We have many questions with short-responses and many-part questions where students often work incrementally through questions. Being able to see past submissions helps students review material and figure out why they got questions wrong initially. Students are currently resorting to sharing screenshots with each other.

**Comment by nwalters512** [comment]
@glherman can you confirm if this is a Homework-type assessment? I believe what you're describing is just the standard behavior for a multi-variant question on a Homework exam, and isn't unique to group assignments with roles. You can reproduce the inability to see the previous variant/submission even as someone with both view and submit permissions:

- View the question
- Submit to the question
- Return to the assessment overview
- Click the same question
- Observe that you now see a new variant with no submissions

I think what you're asking for is what's described in https://github.com/PrairieLearn/PrairieLearn/issues/3158 and is currently being implemented in https://github.com/PrairieLearn/PrairieLearn/pull/6105, is that correct?

**Comment by jonatanschroeder** [comment]
Indeed I just tried locally with a group+role assessment, and students without submit permission can still see submissions in the same variant.

**Comment by glherman** [comment]
Relayed this back to the 233 instructors. They have confirmed.
