### ISSUE TITLE
Clarify that "points available for this attempt" are added to existing points

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9353]
The question footer includes a note in the form "XX points available for this attempt", which is fine in the first attempt. However, when students get a partial score in the first attempt, following attempts will show the number of points that can be added to the existing points. This causes some confusion with some students, as some believe this to be a new total instead of added points. I believe adding "XX **additional** points" may clarify this confusion, though it should probably only list that if the question already has some awarded points.

**Comment by Toby-J-Carter** [comment]
I'll take a look at this.
