### ISSUE TITLE
v3 question with hints?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#938]
Do we have an example in a v3 question of how to give "hints" for incorrect answers?

**Comment by nwalters512** [comment]
@trombonekenny some elements now support a notion of feedback for incorrect answers, e.g. the `feedback` attribute for `<pl-multiple-choice>` and `<pl-checkbox>`. Is that sufficient to close this issue, or did you have something else in mind for this?

**Comment by eliotwrobson** [comment]
There's also the `pl-hidden-hints` element. Though I think that it's very simple to write an example of a custom graded question with custom hints for certain wrong answers.

**Comment by eliotwrobson** [comment]
Looks like the question [demo/custom/gradeFunction](https://www.prairielearn.org/pl/course_instance/4970/instructor/question/1152385/preview/) has an example of custom hints for wrong answers in the form of feedback. I think this issue can be closed.
