### ISSUE TITLE
C Grader Suggestion: Partial credit on test_run for the C grader

### ISSUE THREAD

**Issue by myriath** [PrairieLearn/PrairieLearn#9393]
Would it be possible to assign partial credit based on the number of matched correct outputs in the C grader? Currently it seems like the grader can only do all or nothing per each test, which means I'd need to run multiple tests for each part of the student's code, but that makes the checking part of my test very inefficient. 

I'd like to be able to just run one test_run() command in the tests.py and have it parse out how many correct outputs there were and add them up based on the total points for the test.

It doesn't seem like this would be that complicated to add, just another option to the test_run() function.

**Comment by jonatanschroeder** [comment]
@myriath there is a tentative implementation of this in #9426 now. I would appreciate it if you could test it in your scenario. In essence, if you want to test this, you will need to temporarily change your grader image in info.json to `prairielearn/grader-c:f7d99b6d7ad646faa32b49514af9f75447d59a5b`, and then add, in your call to `self.test_run`, the argument `must_match_all_outputs="partial"`, as described here: https://prairielearn--9426.org.readthedocs.build/en/9426/c-grader/#running-a-program-and-checking-its-standard-output. I have tested this myself and it seems to be working, but it would be nice to have a double-check from you to make sure it matches your user case.

**Comment by myriath** [comment]
I am unsure of the info.json file you are talking about, I tried editing the image part of both my docker command and the docker-compose.yml and it didn't like it very much, so I wasn't able to test it yet. 

However, looking through the code it seems to be doing effectively the same thing as my hacky solution I put together on my end, the only difference is I have the partial credit before the reject output check. That's probably just me misusing the rejects as a way to highlight the error message for each test case that failed rather than explicitly fail the test if any reject messages come up.
