### ISSUE TITLE
Questions in student mode don't have names

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#947]
Expected behavior: the blue panel header on questions should show the question name
Actual behavior: the blue panel header is empty.

**Comment by tbretl** [comment]
I assume you are talking about exam assessments only?

**Comment by nwalters512** [comment]
Yeah, this was in the context of exams, didn't check if it's also true for homeworks.

**Comment by tbretl** [comment]
Cool. It's not.

**Comment by mwest1066** [comment]
Same as #778 and #1149
