### ISSUE TITLE
Element needed: pl_file_link

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#949]
Now that v3 questions no longer supports `<%= clientFilesCourse %>` templating, we need an element that supports linking to a file, optionally in a new tab. `pl_file_download` tells the browser to download the file, which doesn't support viewing a file in the browser.

**Comment by coatless** [comment]
This was addressed/added in PR #1463 by adding a `download="false"` to `pl-download-file` to prevent downloading the file.

**Comment by mwest1066** [comment]
Done.
