### ISSUE TITLE
Exams do not handle deleted questions correctly

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#952]
`sprocs/question_order.sql` needs to patch:

```
-    AND aq.deleted_at IS NULL
+    AND (a.type = 'Exam' OR aq.deleted_at IS NULL)
```

We need to change `studentAssessmentInstanceExam.sql` (and maybe other files) so they don't use alternative groups, because these will be deleted for deleted questions. We should either add a `deleted_at` flag to alternative groups, so they can persist, or we should add a `zone_id` to assessment questions so they don't need to join over alternative groups to find the zone.

**Comment by trombonekenny** [comment]
+1 note, Bruce ran into this ME 270 HW9.

**Comment by mwest1066** [comment]
Same as #1356

**Comment by mwest1066** [comment]
Closing as dup of #1356
