### ISSUE TITLE
RStudio workspace needs a few more R packages

### ISSUE THREAD

**Issue by eddelbuettel** [PrairieLearn/PrairieLearn#9562]
The next block in STAT 447 covers a few add-on packages.  We have those in the autograder, but not in the workspace as I realized when I was prepping the quiz that is currently on.

It is easy to add those but it would 'cost us' another few mb.  I could guestimate that by locally enhancing the image but I guess maybe abother 10% or so?

**Comment by mwest1066** [comment]
That's fine, just submit a PR!

**Comment by eddelbuettel** [comment]
Rocking.  And the timing is right as everybody is out of town next week.  Will do.

**Comment by eddelbuettel** [comment]
Hm, am I missing a `docker build` trick here?  Is there a (non-)default compression option I am not using?

```sh
edd@rob:~/git/prairielearn/workspaces/rstudio(master)$ docker images| grep workspace
local-pl-workspace-rstudio-as-is     latest          3fdd1042e113   2 seconds ago   2.91GB
local-pl-workspace-rstudio           latest          45aeeac47b29   3 minutes ago   3.1GB
prairielearn/workspace-rstudio       latest          251201821baf   3 weeks ago     2.33GB
edd@rob:~/git/prairielearn/workspaces/rstudio(master)$ 
```

Last line is what got (auto-)pulled, the above is my build here -- which shocked me because of the 'too large to be plausible' difference -- and the first line may explain it: a build of your (current) Dockerfile here without any changes.

The difference then is the 200mb from added packages.

**Comment by echuber2** [comment]
@eddelbuettel Can we close this issue? It sounded like https://github.com/PrairieLearn/PrairieLearn/pull/9577 concluded with a private fork of the image.
