### ISSUE TITLE
Websockets polling instead of streaming

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#959]
It appears the websockets used in PL aren't streaming in the production environment. The client reverts to polling every second, which uses up concurrent sessions on the server. You can observe this by looking at the `/var/log/httpd` logs. The impact is that clients working on lots of externally graded problems tend to DoS the server.

We assume there's some misconfiguration in the Apache proxy config.

**Comment by trombonekenny** [comment]
Existing config:

```
######################################################################
# socket.io proxy
RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://localhost:6001/$1 [P,L]
ProxyPass        /socket.io http://localhost:6001/socket.io
ProxyPassReverse /socket.io http://localhost:6001/socket.io
######################################################################
```

**Comment by trombonekenny** [comment]
I was troubleshooting on `pl-dev` two avenues: 1) the highest debugging for mod_rewrite to confirm if the RewriteRule was being triggered correctly (not sure it was) and 2) that the config stanza doesn't work properly in the global httpd.conf context. I was trying that config inside the conf.d/ssl.conf VirtualHost for the site.

I'm not sure either of those were productive. Re-running ansible on pl-dev might be smart to reset the configs.

**Comment by nwalters512** [comment]
Fixed by https://github.com/PrairieLearn/ansible-pl/pull/32
