### ISSUE TITLE
all_submissions.csv doesn't provide the score for each submission

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9594]
I’m trying to find a CSV download of the score a student earned each time (within an assessment) they click “Save and Grade”.

<img width="200" alt="Screenshot 2024-03-17 at 1 33 41 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/c38cebff-7807-4aa4-ac11-df4b5a12dbaf">

I figured the [all_submissions.csv](https://us.prairielearn.com/pl/course_instance/147046/instructor/assessment/2406147/downloads/CPSC_210_2023W2_E2-P2_all_submissions.csv) would give me what I want as it has the following description: 

> All submitted answers for all students for all assessment instances. Not all submitted answers will have been used to compute the final score, as some may have been superseded by subsequent attempts.

However, unfortunately that file does not seem to match the "score" for that submission (all the rows seem to have the "best" submission). For a [particular student](https://us.prairielearn.com/pl/course_instance/147046/instance_question/367452499/), I've highlighted the rows in yellow. The score showing is `29.4` for all submissions rather than the full range (19, 29, 25). 

<img width="758" alt="Screenshot 2024-03-17 at 1 30 28 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/9c51b705-42d3-4a02-9e48-428558b6be41">

**Comment by nwalters512** [comment]
In your screenshot, the "Score" column is not showing 29.4, the "Question points" column is showing 29.4. If you look at the _actual_ "Score" column, you'll see exactly the numbers you're looking for.

![Screenshot 2024-03-17 at 13 55 55](https://github.com/PrairieLearn/PrairieLearn/assets/1476544/c7ccee44-757f-46f6-a9e6-4ede8f3018e0)

**Comment by firasm** [comment]
Ah sorry, there were a lot of columns and I was only scanning for larger numbers and not reading the titles. Sorry and Thanks!
