### ISSUE TITLE
Use all workspaces to calculate safety margin

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#9620]
In #7107 we changed the `desired_active_host_count` for workspaces to exclude workspaces on unhealthy hosts, in response to #804 and #803. While this was the correct thing to do, it had the side effect of also excluding workspaces on unhealthy hosts from the calculation of the safety margin (the extra capacity we keep around to make sure that we can handle new workspaces). This means that when we set all workspace hosts to unhealthy (to trigger an upgrade) we calculate that we need zero safety margin, which is not correct. This can result in additional workspace startup time immediately after a deploy.

Instead, we should be calculating the safety margin based on the total number of workspaces. That is, I think we should change https://github.com/PrairieLearn/PrairieLearn/blob/daa419e01b0fdc959a5771f27fb355a40be73878/apps/prairielearn/src/sprocs/workspace_loads_current.sql#L119 to be
```
workspace_jobs_capacity_desired := workspace_active_on_healthy_hosts_count + workspace_active_count * (workspace_capacity_factor - 1);
```

However, if we simply make this change then we run the risk of once again starting up too many workspace hosts too quickly (the problem described in https://github.com/PrairieLearnInc/sysconf/issues/803#issuecomment-1414723426). We'll eventually fix that with sproc elimination, but for now I think it would be a good idea to add a rate limit for new workspace host creation. One easy way to do this might be to change https://github.com/PrairieLearn/PrairieLearn/blob/daa419e01b0fdc959a5771f27fb355a40be73878/apps/prairielearn/src/ee/cron/workspaceHostLoads.ts#L159 to something like
```
MaxCount: Math.min(needed, config.maxWorkspaceHostSimultaneousLaunch),
```
where `config.maxWorkspaceHostSimultaneousLaunch` is set to something like 3, given that we run this every 10 seconds by default.

**Comment by nwalters512** [comment]
@mwest1066 workspace hosts no longer use sprocs at all, so I'm not concerned about the particular problem of rapid scaling that you linked to. Do you think there are other things to be concerned about with that?

**Comment by mwest1066** [comment]
> @mwest1066 workspace hosts no longer use sprocs at all, so I'm not concerned about the particular problem of rapid scaling that you linked to. Do you think there are other things to be concerned about with that?

Oh great point, I'd forgotten about this fact. Based on this, I do _not_ think we should add rate limiting.
