### ISSUE TITLE
Fix display of duration in instructor panel

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9697]
The question duration in the instructor panel is showing the duration in milliseconds instead of a formatted interval:
![320585958-563d4bde-38bb-4a0e-9ddc-c340f489d08f](https://github.com/PrairieLearn/PrairieLearn/assets/1004907/3465bdee-45df-46eb-8019-2ec5825e502f)

This is likely the result of a change in query that replaced the interval duration with an IntervalSchema, which uses milliseconds to represent the duration.

**Comment by czhou578** [comment]
Can I try taking on this issue?
