### ISSUE TITLE
R autograder

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#970]
- [x] Add docker image based off of [`prairielearn/centos7-base`](https://hub.docker.com/r/prairielearn/centos7-base/) ([source](https://github.com/PrairieLearn/PrairieLearn/blob/9374dd1d2d65d863be9df21f35b8285166ae5500/environments/centos7-base/Dockerfile), [CS 225](https://github.com/PrairieLearn/PrairieLearn/blob/9374dd1d2d65d863be9df21f35b8285166ae5500/environments/centos7-cs225/Dockerfile)) and [`rocker`](https://github.com/rocker-org/rocker/blob/7c99ef6c45053e703d43f0bcecd9e30f56c72df6/r-base/Dockerfile)
    - [ ] minor port from debian to RHEL-based infrastructure
- [x] Verify code highlighting for _R_ exists c.f. 

https://github.com/PrairieLearn/PrairieLearn/blob/9374dd1d2d65d863be9df21f35b8285166ae5500/exampleCourse/questions/fibonacciEditor/question.html#L15

Mode file located at [`/public/javascripts/ace/mode-r.js`](https://github.com/PrairieLearn/PrairieLearn/blob/9374dd1d2d65d863be9df21f35b8285166ae5500/public/javascripts/ace/mode-r.js)

- [x] Provide a modified [`testthat`](https://cran.r-project.org/package=testthat) (see [`R/reporter-junit.R`](https://github.com/r-lib/testthat/blob/eda2d54a78e75e76f5544b78a14b50e88d926689/R/reporter-junit.R)) that outputs unit test results to JSON c.f. ["grade result" section of external autograders](http://prairielearn.readthedocs.io/en/latest/externalGrading/#grading-result). 

Did I forget anything?

**Comment by nwalters512** [comment]
It's no longer necessary to base the image on the PrairieLearn base, so you can base it on whatever image you want. Other than that, this looks good!

**Comment by nwalters512** [comment]
@coatless We now have `graders/r` and `graders/r-previous`. Can this issue be closed?
