### ISSUE TITLE
Add autocorrect="off" in pl-string-input and similar elements

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9729]
A non-standard attribute of HTML inputs is [autocorrect](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocorrect), which is supported by Safari (and I believe respected, at least partially, by Chromium browsers, though I couldn't find an official source for this). This option disables the autocorrect feature when typing strings. This should be added to `pl-string-input` elements by default, in the same way as autocomplete. Other elements with text-based inputs (e.g., pl-symbolic-input, possibly pl-integer-input) may benefit from the same attribute.

**Comment by jgfoster** [comment]
I'm going to recommend this to my students (without discouraging anyone else from working on it). 

The following are some note from the Slack discussion: 

All our elements live in [this directory](https://github.com/PrairieLearn/PrairieLearn/tree/master/apps/prairielearn/elements). [Contributors] should be able to grep for `<input` and/or `autocomplete` in that directory to find relevant places where this should be added....

Our contributing guide is [here](https://github.com/PrairieLearn/PrairieLearn/blob/master/CONTRIBUTING.md).

**Comment by jonatanschroeder** [comment]
Closed at #9752.
