### ISSUE TITLE
helperConfig. file causing Git issue when cloning

### ISSUE THREAD

**Issue by Toby-J-Carter** [PrairieLearn/PrairieLearn#9736]
Currently the helperConfig. file (apps/prairielearn/src/tests/helperConfig.) is causing the following error when cloning the PrairieLearn repo on Windows using terminal or GitHub Desktop. The file is currently empty.
```
`error: invalid path 'apps/prairielearn/src/tests/helperConfig.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
When running `git restore --source=HEAD :/`:
`error: invalid path 'apps/prairielearn/src/tests/helperConfig.`

For my most recent changes, I simply deleted the file on GitHub on my branch before cloning, which solved the issue.

**Comment by jonatanschroeder** [comment]
Thanks for reporting. It seems this file has been created by mistake. A simple fix would be a PR that removes this file, as it does not appear to be in use anywhere.
