### ISSUE TITLE
Review button for new variant when in previous variants

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#9780]
When I click on a previous variant, the button for "Try a new variant" shows. This button creates a new variant if no open variant exists, but if an open/incomplete variant exists, it switches to the open variant (i.e., a variant that has no submission, or one that has been saved but not graded, or one where the submission is ungradable, or one with multiple tries per variant). I believe this behaviour is expected and should remain, but the text of the button ("Try a new variant") is misleading. Ideally, if there is an open variant in the current instance question that is not the current one, we should change the text to something that says "Go to latest variant" or equivalent.

Also, that latest variant is never shown in the history. Should it? At least if it has a submission? In that case it could show "Open", or if it has a valid submission (e.g., >1 tries per submission) the percentage of the submissions so far plus "/Open"? Possibly with a different colour?

_Originally posted by @jonatanschroeder in https://github.com/PrairieLearn/PrairieLearn/pull/6105#pullrequestreview-2027246974_

**Comment by mwest1066** [comment]
I like all of these ideas, including the use of a different color for the latest variant badge.
