### ISSUE TITLE
Linux local docker dev workspace not working

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#9805]
Running Ubuntu 22.04 LTS launching PrairieLearn in docker. It mounts in a jobs directory and `/var/run/docker.sock` and works for externally graded questions. I launch PrairieLearn with `make dev`

To get workspaces working in that environment, I load another shell in that running container and run `make dev-workspace-host`  It loads.

When I launch the `demo/workspace/xtermjs` example course question and workspace, the tab loads but eventually ends with STOPPED: Error starting container. Click "Reboot" to try again (and the spinning throbber keeps spinning). Here's what I see on the dev-workspace-host with debugging:

```
bash-5.2# DEBUG=prairielearn:interface make dev-workspace-host
[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `yarn dev:no-watch`
info: Workspace server listening on port 8081
info: Workspace host ready
info: Launching workspace-6-1 (useInitialZip=false)
  prairielearn:interface init: configuring workspace +0ms
info: Pulling docker image: prairielearn/workspace-xtermjs
  prairielearn:interface Docker pull output:  { status: 'Pulling from prairielearn/workspace-xtermjs', id: 'latest' } +489ms
  prairielearn:interface Docker pull output:  {
  status: 'Digest: sha256:e1fd9dbce2a16eeee3462e14815778a4ccf78b9f5efe48442583bd31c28669f9'
} +32ms
  prairielearn:interface Docker pull output:  {
  status: 'Status: Image is up to date for prairielearn/workspace-xtermjs:latest'
} +1ms
  prairielearn:interface Creating docker container for image=prairielearn/workspace-xtermjs +12ms
  prairielearn:interface Exposed port: 8080 +0ms
  prairielearn:interface Networking enabled: false +0ms
  prairielearn:interface Network mode: bridge +0ms
  prairielearn:interface Env vars: WORKSPACE_BASE_URL=/pl/workspace/6/container/ +0ms
  prairielearn:interface User binding: 1001:1001 +0ms
  prairielearn:interface Port binding: 8080:1101 +0ms
  prairielearn:interface Volume mount: /home/mussulma/.prairielearn_ag_jobs/workspaces/workspace-6-1/current:/home/student +1ms
  prairielearn:interface Container name: workspace-653df9f2-684d-446c-87b3-1551502a8afd +0ms
  prairielearn:interface Creating directory /jobs/workspaces/workspace-6-1/current +1ms
error: Error starting container for workspace 6 Max startup time exceeded for workspace 6 (version 1, launch uuid 653df9f2-684d-446c-87b3-1551502a8afd) {"stack":"Error: Max startup time exceeded for workspace 6 (version 1, launch uuid 653df9f2-684d-446c-87b3-1551502a8afd)\n    at <anonymous> (/PrairieLearn/apps/workspace-host/src/interface.js:544:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
[]
error: Error looking up container for launch_uuid 653df9f2-684d-446c-87b3-1551502a8afd Cannot read properties of undefined (reading 'Id') {"stack":"TypeError: Cannot read properties of undefined (reading 'Id')\n    at _getDockerContainerByLaunchUuid (/PrairieLearn/apps/workspace-host/src/interface.js:355:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/PrairieLearn/apps/workspace-host/src/interface.js:294:19)"}
```

It's failing in https://github.com/PrairieLearn/PrairieLearn/blob/b63a3a73174e12768b017e787e590b42a1d2ce6a/apps/workspace-host/src/interface.js#L349

The `[]` in the debugging above is a console.log I put in for `containers`, which make sense for the error. But I'm not sure how to troubleshoot further.

**Comment by trombonekenny** [comment]
@SethPoulsen Did you see something similar?

**Comment by echuber2** [comment]
@trombonekenny Try adding back `--add-host=host.docker.internal:172.17.0.1`. This is the issue I was referring to with https://github.com/PrairieLearn/PrairieLearn/pull/9802

**Comment by SethPoulsen** [comment]
That did not work for me. I've got the same OS setup as Dave, Ubuntu 22.04. My terminal:

```
(base) seth@seth-t14s:~/git/PrairieLearn$ docker run -it --rm -p 3000:3000     -e NODEMON=true    -v "$HOME/git/PrairieLearn:/PrairieLearn"     -v "$HOME/pl_ag_jobs:/jobs"    -e HOST_JOBS_DIR="$HOME/pl_ag_jobs"     -v /var/run/docker.sock:/var/run/docker.sock  --add-host=host.docker.internal:172.17.0.1   prairielearn/prairielearn
Starting PrairieLearn...
[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `yarn dev:no-watch`
[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,ts,json,sql
[nodemon] starting `yarn dev:no-watch`
info: Workspace server listening on port 8081
info: Workspace host ready
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
info: Launching workspace-1-1 (useInitialZip=true)
info: Pulling docker image: codercom/code-server:3.4.1
error: Error starting container for workspace 1 Max startup time exceeded for workspace 1 (version 1, launch uuid 7b046115-bf29-4876-984f-1a8ec6ba4450) {"stack":"Error: Max startup time exceeded for workspace 1 (version 1, launch uuid 7b046115-bf29-4876-984f-1a8ec6ba4450)\n    at <anonymous> (/PrairieLearn/apps/workspace-host/src/interface.js:543:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}

```

**Comment by SethPoulsen** [comment]
strangely, my error actually looks different than Dave's, I don't have the ` Error looking up container for launch_uuid `, only the `Max startup time exceeded` error. (This could be due to different logging configs though, I don't know.

**Comment by echuber2** [comment]
For the "time exceeded" error, try removing your mount of the local /PrairieLearn source and using what's already in the image for that.

**Comment by SethPoulsen** [comment]
that did not solve the problem, I still get the same error output

**Comment by trombonekenny** [comment]
Give it a little bit of time. Does the second error show up?

**Comment by SethPoulsen** [comment]
oh, you're right Dave, the second error did show up eventually after a while: 

```
error: Error looking up container for launch_uuid 7b046115-bf29-4876-984f-1a8ec6ba4450 Cannot read properties of undefined (reading 'Id') {"stack":"TypeError: Cannot read properties of undefined (reading 'Id')\n    at _getDockerContainerByLaunchUuid (/PrairieLearn/apps/workspace-host/src/interface.js:354:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/PrairieLearn/apps/workspace-host/src/interface.js:294:19)"}
```

**Comment by echuber2** [comment]
The outdated codercom/code-server:3.4.1 image may also be chowning lots of stuff slowly and causing the launch to time out. This is a long-standing issue that motivated our other derived VS Code images, like the one currently in PR.

**Comment by trombonekenny** [comment]
> The outdated codercom/code-server:3.4.1 image may also be chowning lots of stuff slowly and causing the launch to time out. This is a long-standing issue that motivated our other derived VS Code images, like the one currently in PR. (The "other" images being ad-hoc ones that course staff made for themselves.)

I was using the xterm image / example course question. I don't think it does any chown commands: https://github.com/PrairieLearn/PrairieLearn/blob/master/workspaces/xtermjs/Dockerfile

**Comment by echuber2** [comment]
I was referring to Seth's output:
> info: Pulling docker image: codercom/code-server:3.4.1

With the xtermjs one, in contrast, I was able to reproduce your issue locally by removing the --add-host and fix the issue by putting it back.

**Comment by trombonekenny** [comment]
Thanks for confirming, @echuber2. I'm not sure why it fails for @SethPoulsen. The VSCode example question (with the outdated image you mentioned above) worked fine too.

And I learned the `make -j 2 dev dev-workspace-host` trick, which is nice.

**Comment by trombonekenny** [comment]
It's a little unsatisfying that we need to do the docker host configuration for workspaces when we don't need it for external graders, but I understand that the workspace is doing different dockerode commands and engaging with the host docker differently. The documentation change resolves this issue for me (and makes me want to revisit docker-compose as a more supported natural way to run non-native dev).

**Comment by echuber2** [comment]
Seth's case might need another solution then... It doesn't look like he has a custom course mounted in the PL invocation, but the usual trigger for the code-server timeout would be having a lot of pre-installed files in `/home/coder` for the particular question, or in a modified copy of the image.

**Comment by SethPoulsen** [comment]
The only other difference I can see between me and Dave is that I start the server when I start the container, but Dave does those two steps seperately. Dave, what is your command for starting the container by itself without starting the server? is it some variation of `docker start`? (rather than `docker run` which is what I do).

**Comment by jonatanschroeder** [comment]
> The only other difference I can see between me and Dave is that I start the server when I start the container, but Dave does those two steps seperately. Dave, what is your command for starting the container by itself without starting the server? is it some variation of `docker start`? (rather than `docker run` which is what I do).

Just add `bash` at the end of the `docker run` command.

**Comment by echuber2** [comment]
If you have custom options in a `PrairieLearn/config.json`, that might play a role too.

**Comment by SethPoulsen** [comment]
Still not working if I start the container then start the server after. 

My config is empty.

At some point I had to reroute some docker ports because it was interfering with something on my University networks. This could have something to do with it.

**Comment by SethPoulsen** [comment]
Got it working!

My `/etc/docker/daemon.json` looks like: 

```
{
  "default-address-pools":
  [
    {"base":"10.254.0.0/16","size":24}
  ]
}
```

So I instead had to do `--add-host host.docker.internal:10.254.0.1`

**Comment by echuber2** [comment]
Would you like to add a note to https://github.com/PrairieLearn/PrairieLearn/pull/9802 about that? I don't know if it's too much of a special case to mention, but there are probably other faculty who might run into it.

**Comment by SethPoulsen** [comment]
done, thanks

**Comment by trombonekenny** [comment]
> (in case anyone cares, I had to move the docker ports because it interfered with my machine communicating with other devices on my department network, because of how my IT has those IP addresses mapped)

That used to be true for IllinoisNet back in the early days of docker (using the same 10.17.x range)! I think a lot of institutional IT spaces, including ours, have moved away from using that range to try to minimize the conflicts and configuration -- but I understand it's still an issue.

Closing this one out, thanks for the troubleshooting!
