### ISSUE TITLE
Add ability to render html of a Juptyer notebook

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9808]
Instructors often request students to submit jupyter notebooks into PrairieLearn for manual grading. 

This feature request would add the ability to render the html from an `ipynb` in-browser for easier manual grading.

**Comment by moveisi** [comment]
That would be a fantastic add-on. Right now, our TAs need to download ipynb files first and load it somewhere else to view them for marking.

**Comment by jonatanschroeder** [comment]
HTML can be rendered already, check [the pl-xss-safe element](https://prairielearn.readthedocs.io/en/latest/elements/#pl-xss-safe-element).

**Comment by firasm** [comment]
This is currently being worked on by @kurmasz in #9840 ! Thanks so much!!

**Comment by kurmasz** [comment]
It's actually done. We're just waiting on a PR in a dependent package to be accepted.

**Comment by firasm** [comment]
Great news - https://github.com/jsvine/notebookjs/pull/55 is now merged in!

**Comment by kurmasz** [comment]
Nice. I'll try to get that finished up this week.  (I need to make sure some things are set up for classes to start on the 26th first.)

**Comment by nwalters512** [comment]
This was implemented in #9840. This will be live in production shortly.
