### ISSUE TITLE
Shared question page has `(undefined)` after username in navbar

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#9810]
When viewing a shared question page (e.g., https://us.prairielearn.com/pl/public/course/7608/question/9224666/preview) the username in the top right of the navbar has `(undefined)` after it.

<img width="774" alt="image" src="https://github.com/PrairieLearn/PrairieLearn/assets/875833/b21eafed-ca72-4cea-8a45-149d75f2af1b">

**Comment by jonatanschroeder** [comment]
Duplicate of #9094.
