### ISSUE TITLE
Add groups download to the download tab

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#9811]
For group assessments, the `Groups` tab has a download that lets you download a csv with a list of all the groups and the uids of the students in those groups (and students roles if enabled). It'd be nice if this file was also available on the `Downloads` tab, since it's a download and that's where I looked for the csv initially.

**Comment by nwalters512** [comment]
This is already available in the Downloads tab as the `*_groups.csv` file. Implementation:

https://github.com/PrairieLearn/PrairieLearn/blob/fc33f209eae00fddc4f2e66d4f16a2f2ddda0177/apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.html.ts#L147-L159
