### ISSUE TITLE
Running instruction

### ISSUE THREAD

**Issue by wendyguo2002** [PrairieLearn/PrairieLearn#9819]
When I tried to run it locally, I faced the problem "no matching manifest for linux/arm64/v8 in the manifest list entries". "To fix this, open Docker Desktop settings, click on "General", check "Use Rosetta for x86/amd64 emulation on Apple Silicon", and click "Apply & Restart". After Docker Desktop restarts, try the above docker run ... command again.", this is the instruction to fix this error. For someone like me who is not familiar with Docker may not be able to find  "Use Rosetta for x86/amd64 emulation on Apple Silicon" easily because I need to check "Use Virtualization framework" first, and then "Use Rosetta for x86/amd64 emulation on Apple Silicon" will show up below. This took me some time to figure out by checking the Docker web. You may consider reminding users to check "Use Virtualization framework".

**Comment by nwalters512** [comment]
What version of Docker Desktop are you running? In the latest version (4.30.0), checking "Use Rosetta..." will automatically enable "Use Virtualization framework".

**Comment by wendyguo2002** [comment]
My version is 4.29 and may be that's the problem.

**Comment by wendyguo2002** [comment]
I'm unable to reproduce it anymore. That's my first-time use Docker, and "Use Rosetta for x86/amd64 emulation on Apple Silicon" didn't show up until I checked "Use Virtualization framework". However, when I unchecked the "Use Virtualization framework" this time, the "Use Rosetta for x86/amd64 emulation on Apple Silicon" option didn't disappear. That may only happen for the first-time user. You may add something in the document like if you can't find "Use Rosetta for x86/amd64 emulation on Apple Silicon",  make sure you check "Use Virtualization framework".

**Comment by echuber2** [comment]
I have a PR from last week pending here, that does add a few words describing how to turn on the "virtualization" option before the "Rosetta" option: https://github.com/PrairieLearn/PrairieLearn/pull/9802 Hopefully this would help, but input from others is welcome.

**Comment by nwalters512** [comment]
I'll consider this resolved by #9802. Thanks @echuber2!
