### ISSUE TITLE
Random reordering of some assessment columns in exported gradebooks

### ISSUE THREAD

**Issue by moveisi** [PrairieLearn/PrairieLearn#9836]
We recently noticed an unexpected PL behaviour that causes _exported gradebook to reorder assessment columns apparently randomly_, when assessments share the same `set` and `number`. See the screenshot below.

```
"set": "Homework",
"number": "3",
```
In our case, we had two assessments both with same `set` and `number` above (the older one was incorrect and omitted). They show up under Gradebook tab as expected: always the older assessment column comes before the newer one.
When you export the gradebook, they show up as `HW3` and `HW3.1`. However, the problem is that when you **export multiple times**, which assessment will be called `HW3.1` seems to be randomly selected, as shown in the screenshot.
The links to these assessments HW3 (old) and HW3 (new) are available in the [related discussion in Slack pl-help channel](https://prairielearn.slack.com/archives/C266KEH9A/p1715289185324159).

![PL_gradebook_export_BUG](https://github.com/PrairieLearn/PrairieLearn/assets/13824658/851793c0-1b45-463b-8d95-2d1cd6e8bd3d)

**Comment by nwalters512** [comment]
A relevant piece of information: the `.1` suffix actually comes from Pandas, not PrairieLearn. AFAICT, Pandas does that deterministically based on the ordering of the original columns, so it's still on us to produce output in a consistent order. But the raw CSV just has two columns named `HW3`.
