### ISSUE TITLE
courseConfig documentation conflicts with schema

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#99]
In the courseConfig documentation (located [here](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/courseConfig.md)), it says that Superuser is a valid role for a course. However, the [schema](https://github.com/PrairieLearn/PrairieLearn/blob/master/backend/schemas/courseInfo.json) seems to indicate otherwise.

A `node server` reflects that, saying:

>Error in JSON file specification: Error in field "data.userRoles[keys2.0]": must be an enum value (value: 'Superuser')

**Comment by mwest1066** [comment]
Thanks for the note. I've fixed the docs to add the paragraph:

User roles `Student` through `Instructor` can be set in the `courseConfig.json` file. The `Superuser` role can only be specified in the [server `config.json` file](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/serverConfig.md).

**Comment by mwest1066** [comment]
Fixed in 70df1d5964fbca6d0be4512d10a2916ba4f8c650
